;;; Czech translations

(
 ;; Language metadata (used for language picker)
 (:lang-name . "Čeština")
 (:lang-flag . "🇨🇿")

 ;; Language modal (first-visit language selection)
 (:lang-modal-title . "Vyberte svůj jazyk")
 (:lang-modal-subtitle . "Zvolte preferovaný jazyk rozhraní:")

 ;; Navigation
 (:nav-translate . "Přeložit")
 (:nav-review . "Opakování")
 (:nav-flashcards . "Moje kartičky")
 (:nav-dashboard . "Přehled")
 (:nav-decks . "Balíčky")
 (:nav-logout . "Odhlásit se")
 (:nav-home . "Domů")
 (:nav-pricing . "Ceník")
 (:nav-institutions . "Pro instituce")
 (:nav-export-data . "Exportovat data")
 (:nav-open-navigation . "Otevřít navigaci")
 (:theme-light . "Světlý")
 (:theme-dark . "Tmavý")

 ;; App title and branding
 (:app-title . "Hiisi - Studium jazyků")

 ;; Landing page
 (:landing-learn-more . "Zjistit více")
 (:landing-how-it-works . "Jak to funguje")
 (:landing-start-trial . "Vyzkoušet zdarma")
 (:landing-best-value . "Nejlepší hodnota")

 ;; Auth pages
 (:auth-register . "Registrace")
 (:auth-login . "Přihlášení")
 (:auth-email . "E-mail")
 (:auth-password . "Heslo")
 (:auth-password-again . "Potvrzení hesla")
 (:auth-display-name . "Zobrazované jméno")
 (:auth-register-title . "Registrace do Hiisi")
 (:auth-register-subtitle . "Vytvořte nový účet")
 (:auth-login-title . "Přihlášení do Hiisi")
 (:auth-login-subtitle . "Zadejte své přihlašovací údaje")
 (:auth-login-invalid-credentials . "Neplatný e-mail nebo heslo.")
 (:auth-login-rate-limited . "Příliš mnoho pokusů o přihlášení. Počkejte prosím několik minut a zkuste to znovu.")
(:auth-register-rate-limited . "Příliš mnoho pokusů o registraci. Počkejte prosím několik minut a zkuste to znovu.")
(:auth-email-invalid . "Zadejte prosím platnou e-mailovou adresu.")
(:auth-password-too-short . "Heslo musí mít alespoň 8 znaků.")
(:auth-passwords-mismatch . "Hesla se neshodují.")
(:auth-display-name-invalid . "Zobrazované jméno musí mít 1 až 100 znaků.")
(:auth-register-email-exists . "Účet s tímto e-mailem už existuje.")
(:auth-register-unavailable . "Registrace je dočasně nedostupná. Zkuste to prosím znovu později.")
(:auth-register-plan-required . "Před vytvořením účtu si vyberte plán.")
(:auth-preapproved-email-unrecognized . "Použijte e-mailovou adresu z pozvánky, nebo si před vytvořením účtu vyberte plán.")
(:auth-institution-register . "Přicházíte z instituce?")
(:auth-institution-title . "Registrace přes vaši instituci")
(:auth-institution-subtitle . "Použijte školní nebo univerzitní e-mail. Pokud má vaše instituce aktivní přístup k Hiisi, účet se odemkne po ověření e-mailu.")
(:auth-institution-domain-unrecognized . "Tuto institucionální e-mailovou doménu zatím neznáme. Vyberte si plán nebo požádejte svou instituci, aby Hiisi kontaktovala.")
(:subscribe-institution-callout-title . "Používáte Hiisi přes školu nebo univerzitu?")
(:subscribe-institution-callout-body . "Zaregistrujte se institucionálním e-mailem a Hiisi vám automaticky odemkne přístup, pokud je vaše instituce už nastavená.")
(:auth-activation-email-send-failed . "Nepodařilo se odeslat aktivační e-mail. Zkuste to prosím znovu.")
 (:auth-forgot-password . "Zapomenuté heslo?")
 (:auth-no-account . "Nemáte účet?")
 (:auth-have-account . "Již máte účet?")
 (:auth-google . "Google")
 (:auth-google-login-failed . "Přihlášení přes Google se nezdařilo. Zkuste to prosím znovu.")
 (:auth-account-created . "Účet vytvořen!")
 (:auth-check-email . "Zkontrolujte svůj e-mail pro aktivační odkaz.")
 (:auth-redirect-login . "Přesměrování na přihlášení za")
 (:auth-seconds . "sekund...")
 (:auth-go-now . "Přejít nyní")
 (:auth-not-activated . "Účet není aktivován")
 (:auth-activate-title . "Aktivujte svůj účet!")
 (:auth-activated . "Účet aktivován!")
 (:auth-activated-message . "Váš účet byl aktivován. Nyní můžete používat Hiisi.")
 (:auth-redirecting . "Přesměrování za")
 (:auth-go-to-app . "Přejít do aplikace")
 (:onboarding-title . "Jak Hiisi funguje")
 (:onboarding-subtitle . "Překládejte skutečný text, prohlížejte si gramatiku, ukládejte si užitečné položky a později je opakujte.")
 (:onboarding-translate-detail . "Začněte skutečným textem. Hiisi vrátí překlad, zarovnané tvary a navazující studijní kroky na jednom místě.")
 (:onboarding-grammar-detail . "Otevřete gramatický rozbor a uvidíte, které tvary si ve větě odpovídají a jakou roli jednotlivé části hrají.")
 (:onboarding-review-detail . "Ukládejte si užitečné překlady a později je procvičujte rozloženým opakováním, aby zůstaly v dlouhodobé paměti.")
 (:onboarding-decks-detail . "Seskupujte užitečné položky do balíčků, sdílejte je s ostatními a udržujte související materiál pohromadě.")
 (:onboarding-back . "Zpět")
 (:onboarding-next . "Další")
 (:onboarding-skip . "Přeskočit průvodce")
 (:auth-resend-title . "Znovu odeslat aktivační e-mail")
 (:auth-resend-subtitle . "Zadejte svůj e-mail pro získání nového aktivačního odkazu.")
 (:auth-resend-button . "Znovu odeslat aktivační e-mail")
 (:auth-resend-success . "Aktivační e-mail odeslán!")
 (:auth-resend-success-detail . "Zkontrolujte svou schránku pro nový aktivační odkaz.")
 (:auth-resend-rate-limited . "Prosím počkejte několik minut před dalším požadavkem o aktivační e-mail.")
 (:auth-resend-cooldown . "Další e-mail můžete vyžádat za ~a sekund.")
 (:auth-back-to-login . "Zpět na přihlášení")
 (:auth-forgot-password-title . "Zapomenuté heslo")
 (:auth-forgot-password-subtitle . "Zadejte svůj e-mail a pošleme vám odkaz pro obnovení hesla.")
 (:auth-send-reset-link . "Odeslat odkaz pro obnovení")
 (:auth-reset-email-sent . "Odkaz odeslán!")
 (:auth-reset-email-sent-detail . "Pokud účet s tímto e-mailem existuje, brzy obdržíte odkaz pro obnovení hesla.")
 (:auth-reset-rate-limited . "Prosím počkejte několik minut před dalším požadavkem o obnovení hesla.")
 (:auth-reset-invalid-token . "Tento odkaz pro obnovení hesla je neplatný nebo vypršel.")
 (:auth-reset-password-title . "Obnovení hesla")
 (:auth-reset-password-subtitle . "Zadejte své nové heslo níže.")
 (:auth-new-password . "Nové heslo")
 (:auth-confirm-new-password . "Potvrďte nové heslo")
 (:auth-reset-password . "Obnovit heslo")
 (:auth-password-changed . "Heslo změněno!")
 (:auth-password-changed-detail . "Vaše heslo bylo úspěšně změněno. Nyní se můžete přihlásit s novým heslem.")
 (:auth-change-password-title . "Změna hesla")
 (:auth-change-password-subtitle . "Aktualizujte heslo svého účtu.")
 (:auth-current-password . "Současné heslo")
 (:auth-change-password . "Změnit heslo")
 (:auth-back-to-app . "Zpět do aplikace")
 (:auth-password-updated . "Heslo aktualizováno!")
 (:auth-password-updated-detail . "Vaše heslo bylo úspěšně aktualizováno.")
(:auth-current-password-invalid . "Aktuální heslo není správné.")
(:auth-new-password-same . "Nové heslo se musí lišit od současného hesla.")

 ;; Email copy
 (:email-common-hi . "Ahoj")
 (:email-common-tagline . "Hiisi - Učte se překladem")
 (:email-activation-subject . "Aktivujte svůj účet Hiisi")
 (:email-activation-title . "Vítejte v Hiisi")
 (:email-activation-body . "Děkujeme za registraci. Aktivujte svůj účet kliknutím na odkaz níže:")
 (:email-activation-button . "Aktivovat účet")
 (:email-activation-copy-link . "Nebo zkopírujte tento odkaz")
 (:email-activation-expiry . "Platnost odkazu vyprší za 24 hodin.")
 (:email-reset-subject . "Obnovení hesla Hiisi")
 (:email-reset-title . "Žádost o obnovení hesla")
 (:email-reset-body . "Obdrželi jsme žádost o obnovení vašeho hesla. Kliknutím na odkaz níže nastavíte nové heslo:")
 (:email-reset-button . "Obnovit heslo")
 (:email-reset-expiry . "Platnost odkazu vyprší za 1 hodinu.")
 (:email-reset-ignore . "Pokud jste o obnovení hesla nežádali, můžete tento e-mail ignorovat.")
 (:email-reminder-subject-due . "Čas na opakování kartiček Hiisi")
 (:email-reminder-subject-streak . "Udržte si sérii v Hiisi")
 (:email-reminder-cards-due . "kartiček čeká na opakování")
 (:email-reminder-keep-going . "Od posledního opakování uplynulo pár dní. Pět minut dnes stačí, aby vám to, co už jste se naučili, neproklouzlo z paměti.")
 (:email-reminder-button . "Opakovat teď")
 (:email-reminder-settings . "Nastavení upomínek")
 (:email-reminder-preview-title . "Kartičky, které na vás čekají")
 (:email-reminder-translation-label . "Překlad")
 (:email-reminder-more-due-today . "dalších kartiček čeká dnes")
 (:email-trial-subject . "Jak se vám daří ve zkušební době Hiisi?")
 (:email-trial-expiring . "Vaše bezplatná zkušební doba Hiisi končí zítra.")
 (:email-trial-feedback . "Baví vás Hiisi? Napište nám, co vám nejvíc pomáhá.")
 (:email-trial-strengths . "Můžete překládat vlastní texty, ukládat je do kartiček a učit se průběžným opakováním.")
 (:email-trial-reply . "Stačí odpovědět na tento e-mail. Vaše zpráva se dostane přímo k týmu Hiisi.")
 (:email-trial-button . "Vybrat tarif")
 (:email-trial-manage . "Správa předplatného")
 (:email-trial-contact . "Napište nám")
 (:email-plan-nudge-subject . "Vaše překlady čekají")
 (:email-plan-nudge-title . "Vaše překlady čekají")
 (:email-plan-nudge-intro . "Zaregistrovali jste se do Hiisi, ale ještě jste si nevybrali tarif.")
 (:email-plan-nudge-benefits-intro . "S předplatným získáte:")
 (:email-plan-nudge-benefit-translations . "600 překladů měsíčně s gramatickými rozbory")
 (:email-plan-nudge-benefit-flashcards . "Neomezené kartičky s rozloženým opakováním")
 (:email-plan-nudge-benefit-decks . "Vlastní balíčky, které můžete organizovat a sdílet")
 (:email-plan-nudge-pricing . "Tarify začínají na 10 EUR měsíčně, nebo ušetřete s ročním tarifem za 100 EUR ročně (dva měsíce zdarma).")
 (:email-plan-nudge-feedback . "Pokud vám na Hiisi něco nevyhovuje, odpovězte na tento e-mail. Vaše zpráva jde přímo týmu Hiisi.")
 (:email-plan-nudge-button . "Vybrat tarif")
 (:email-plan-nudge-unsubscribe . "Odhlásit tyto e-maily")
 (:email-plan-nudge-unsubscribe-done-title . "E-maily o tarifech jsou vypnuté")
 (:email-plan-nudge-unsubscribe-done-body . "Další připomínky k výběru tarifu už dostávat nebudete.")
 (:email-plan-nudge-unsubscribe-invalid-title . "Tento odkaz není platný")
 (:email-plan-nudge-unsubscribe-invalid-body . "Tento odhlašovací odkaz chybí, vypršel nebo už není platný.")
 (:email-invite-subject . "Pozvánka do Hiisi")
 (:email-invite-title . "Byli jste pozváni do Hiisi")
 (:email-invite-intro . "Byli jste pozváni používat Hiisi zdarma, jako tester, vážený přítel nebo obojí.")
 (:email-invite-details . "Pomocí tlačítka níže si vytvořte účet a začněte používat překlady a kartičky.")
 (:email-invite-button . "Vytvořit účet")
 (:email-invite-issue-reporting . "Když se něco pokazí nebo nebude fungovat správně, dole na každé stránce najdete tlačítko pro nahlášení problému.")
 (:email-issue-completed-subject . "Nahlášený problém v Hiisi je opraven")
 (:email-issue-completed-title . "Problém je opraven")
 (:email-issue-completed-label . "Problém")
 (:email-issue-completed-followup . "Otevřete Hiisi a ověřte opravu nebo pokračujte tam, kde jste skončili.")
 (:email-issue-completed-button . "Otevřít Hiisi")
 (:email-issue-completed-open-link . "Otevřít stránku")

 ;; Translation page
 (:translate-title . "Překlad")
 (:landing-public-translate-title . "Vyzkoušejte si to tady")
 (:translate-input-label . "Zadejte text k překladu")
 (:translate-input-placeholder . "Napište něco...")
 (:translate-from . "Původní jazyk:")
 (:translate-to . "Jazyk překladu:")
 (:translate-select-target-placeholder . "Vyberte jazyk překladu")
 (:translate-submit . "Přeložit")
 (:translate-auto-detect . "Jakýkoliv (Autodetekce)")
 (:translate-empty-state . "Přeložte slovo nebo frázi a tady uvidíte výsledek, gramatický rozbor i studijní akce.")
 (:translate-select-deck-placeholder . "Vyberte balíček (volitelné)")
 (:translate-new-deck . "Nový balíček")
 (:translate-add-to-deck . "Přidat do balíčku")
 (:translate-bookmark . "Uložit")
 (:translate-bookmarked . "Uloženo")
 (:translate-retry . "Vygenerovat znovu")
 (:translate-like-tooltip . "Dobrý překlad")
 (:translate-dislike-tooltip . "Špatný překlad - vyžádat nový")
 (:translate-dislike-confirm . "Toto vygeneruje nový překlad. Pokračovat?")
 (:pronunciation-label . "Výslovnost")
 (:pronunciation-show . "Zobrazit výslovnost")
 (:pronunciation-hide . "Skrýt výslovnost")
 (:grammar-term-examples . "Příklady")
 (:grammar-term-related . "Související pojmy")
 (:grammar-term-modal-title . "Gramatický pojem")
 (:grammar-term-empty . "Vyberte zvýrazněný pojem pro zobrazení detailů.")
 (:extension-login-required . "Před použitím rozšíření prohlížeče se přihlaste do Hiisi.")
 (:extension-session-invalid . "Vaše relace Hiisi už není platná. Přihlaste se znovu.")
 (:extension-activation-required . "Před použitím rozšíření prohlížeče aktivujte svůj účet Hiisi.")
 (:extension-subscription-required . "Před použitím rozšíření prohlížeče spusťte zkušební období Hiisi.")

 ;; Translation and Flashcards
 (:lang-auto . "Auto")
 (:lang-unknown . "?")
 (:lang-target . "Cíl")
 (:translate-deck-create-title . "Vytvořit nový balíček")
 (:translate-deck-name-label . "Název balíčku")
 (:translate-deck-name-placeholder . "např. Základy finštiny")
 (:translate-deck-description-label . "Popis (volitelné)")
 (:translate-deck-cancel . "Zrušit")
 (:translate-deck-create . "Vytvořit")
 (:translate-rate-label . "Ohodnotit překlad")
 (:flashcards-delete . "Smazat")
 (:flashcards-delete-confirm . "Opravdu chcete smazat tuto kartičku?")
 (:flashcards-deck-search-placeholder . "Hledat balíčky...")
 (:flashcards-no-decks . "Zatím žádné balíčky. Nejdřív nějaký vytvořte.")
 (:flashcards-deck-cancel . "Zrušit")
 (:flashcards-recollection-tooltip . "Zapamatování: ~A")
 (:flashcards-recollection-poor . "Slabé")
 (:flashcards-recollection-fair . "Ucházející")
 (:flashcards-recollection-normal . "Normální")
 (:flashcards-recollection-strong . "Silné")
 (:flashcards-recollection-very-strong . "Velmi silné")

 ;; Flashcard review
 (:review-title . "Opakování")
 (:review-session-title . "Opakovací relace")
 (:review-session-subtitle . "Procvičujte uložené kartičky")
 (:review-selector-title . "Vyberte, co chcete opakovat")
 (:review-selector-subtitle . "Vyberte balíček nebo jazykový pár, na který se chcete v této relaci zaměřit.")
 (:review-by-deck . "Opakovat podle balíčku")
 (:review-by-language-pair . "Opakovat podle jazykového páru")
 (:review-all-cards . "Opakovat všechny kartičky")
 (:review-cards-due . "karet k opakování")
 (:review-deck-caught-up . "Vše zopakováno")
 (:review-all-caught-up . "Vše zopakováno!")

 (:review-no-cards . "Žádné kartičky k opakování")
 (:review-no-cards-desc . "Momentálně nemáte žádné kartičky k opakování.")
 (:review-no-cards-hint . "Přeložte nějaký text a klikněte na \"Uložit do kartiček\" pro vytvoření balíčku!")
 (:review-start-translating . "Začít překládat")
 (:review-click-reveal . "Klikněte pro zobrazení odpovědi")
 (:review-grammar-breakdown . "Gramatický rozbor")
 (:review-how-well . "Vzpomněli jste si?")
 (:review-again . "Ne")
 (:review-hard . "Stěží")
 (:review-good . "Ano")
 (:review-easy . "Snadno")
 (:review-progress . "Kartička ~a z ~a")
 (:review-correct-count . "Správně")
 (:review-wrong-count . "Špatně")
 (:landing-mockup-forgot-detail . "1. osoba jednotného čísla préterita slovesa \"olvidar\" (zapomenout)")
 (:landing-mockup-keys-detail . "Přivlastňovací \"mis\" se ženským podstatným jménem v množném čísle \"llaves\" (klíče)")
 (:landing-mockup-home-detail . "Idiomatické \"en casa\" (doma) -- bez členu")
 (:landing-mockup-possession-note . "Ve španělštině préteritum označuje dokončené minulé děje. Osobní zájmeno se obvykle vynechává, protože koncovka slovesa již určuje mluvčího.")
 (:landing-mockup-children-detail . "1. pád množného čísla podstatného jména \"Kind\" (dítě) -- množné číslo přidává -er")
 (:landing-mockup-played-detail . "3. osoba množného čísla préterita slovesa \"spielen\" (hrát)")
 (:landing-mockup-garden-detail . "3. pád: \"in dem\" se stahuje na \"im\", s mužským podstatným jménem \"Garten\" (zahrada)")
 (:landing-mockup-czech-note . "Němčina používá préteritum v psaném vyprávění. \"Im\" je stažený tvar předložky \"in\" a členu \"dem\" (3. pád).")
 (:landing-mockup-deck-title . "Základy italštiny")
 (:landing-mockup-share-deck . "Sdílet balíček")
 (:review-complete . "Opakování dokončeno!")
 (:review-complete-msg . "Zopakovali jste ~a kartiček")
 (:review-again-btn . "Opakovat znovu")
 (:review-translate-more . "Překládat více")
 (:review-streak . "denní série")

 ;; Dashboard
 (:dashboard-title . "Přehled")
 (:dashboard-cards-due . "Kartičky na dnes")
 (:dashboard-total-cards . "Celkem kartiček")
 (:dashboard-mastered-cards . "Zvládnutých kartiček")
 (:dashboard-subscription . "Předplatné")
 (:dashboard-subscribed-until . "Předplaceno do")
 (:dashboard-not-subscribed . "Bez předplatného")
 (:dashboard-recent . "Nedávné překlady")
 (:dashboard-no-translations . "Zatím žádné překlady")
 (:dashboard-streak . "Aktuální série")
 (:dashboard-days . "dní")
 (:dashboard-all-caught-up . "Máte hotovo!")
 (:dashboard-all-caught-up-hint . "Překládejte dál a rozšiřujte svou sbírku.")
 (:dashboard-getting-started . "Začínáme")
 (:dashboard-tip-1 . "Přeložte text, který se chcete naučit")
 (:dashboard-tip-2 . "Klikněte na \"Uložit do kartiček\" u překladů, které si chcete zapamatovat")
 (:dashboard-tip-3 . "Pravidelně opakujte kartičky - rozložené opakování pomáhá dlouhodobému zapamatování")
 (:dashboard-tip-4 . "Hodnoťte upřímně - pomáhá to algoritmu optimálně plánovat opakování")

 ;; Account
 (:account-title . "Účet")
 (:account-subtitle . "Spravujte zde profil, předplatné, připomenutí, exporty i nastavení odstranění účtu.")
 (:account-profile-subtitle . "Udržujte své zobrazované jméno a e-mail aktuální.")
 (:account-export-subtitle . "Stáhněte si kopii uložených překladů, balíčků a historie opakování.")
 (:account-deletion-title . "Odstranění účtu")
 (:account-deletion-scheduled . "Váš účet je naplánován k odstranění na ~A.")
 (:account-deletion-cancel-hint . "Zrušením před tímto datem si účet ponecháte.")
 (:account-deletion-cancel . "Zrušit odstranění")
 (:account-deletion-request . "O odstranění účtu můžete požádat kdykoli. Odstranění je naplánováno na 14 dní od potvrzení. Pokud si to rozmyslíte, kontaktujte podporu před uplynutím této 14denní lhůty.")
 (:account-deletion-confirm . "Naplánovat odstranění účtu za 14 dní od dneška?")
 (:account-deletion-schedule . "Naplánovat odstranění")
 (:account-reminders-title . "E-mailová připomenutí")
 (:account-reminders-subtitle . "Zvolte, zda vám Hiisi může poslat e-mail, když na vás čeká něco k opakování.")
 (:account-reminders-opt-out . "Nezasílat připomenutí ke studiu a pokračování")
 (:account-reminders-save . "Uložit nastavení")

 ;; Subscription
 (:subscribe-title . "Vyberte si plán")
 (:subscribe-choose-plan . "Vyberte si plán")
 (:subscribe-start-today . "Začněte se učit už dnes se 14denní zkušební dobou zdarma")
 (:subscribe-monthly . "Měsíčně")
 (:subscribe-annual . "Ročně")
 (:subscribe-founder-member . "Zakládající člen")
 (:subscribe-monthly-price . "€10")
 (:subscribe-annual-price . "€100")
 (:subscribe-founder-price . "€79")
 (:subscribe-per-month . "/měsíc")
 (:subscribe-per-year . "/rok")
 (:subscribe-monthly-desc . "600 překladů měsíčně. Neomezeně kartiček, balíčků a opakování.")
 (:subscribe-unlimited-flashcards . "Neomezené kartičky")
 (:subscribe-grammar-explanations . "Gramatická vysvětlení")
 (:subscribe-spaced-repetition . "Rozložené opakování")
 (:subscribe-annual-desc . "Vše z měsíčního plánu. Dva měsíce zdarma.")
 (:subscribe-founder-lock . "Cena zůstane stejná, dokud bude vaše předplatné aktivní.")
 (:subscribe-founder-badge . "Omezená nabídka")
 (:subscribe-founder-limit . "Omezeno na prvních 100 členů")
 (:subscribe-manage . "Správa předplatného")
 (:subscribe-activated . "Předplatné aktivováno!")
 (:subscribe-thank-you . "Předplatné je aktivní. Tady můžete spravovat platby a dokoupit další překlady.")
 (:subscribe-start-learning . "Začít se učit")
 (:subscribe-management . "Správa předplatného")
 (:subscribe-active . "Aktivní předplatné")
 (:subscribe-preapproved-access . "Předem schválený přístup")
 (:subscribe-status . "Stav:")
 (:subscribe-status-active . "Aktivní")
 (:subscribe-status-preapproved . "Předem schválený")
 (:subscribe-preapproved-detail . "Tento účet používá předem schválený přístup spravovaný Hiisi.")
 (:subscribe-days-remaining . "Zbývající dny:")
 (:subscribe-renews-on . "Obnovení:")
 (:subscribe-no-subscription . "Žádné aktivní předplatné")
 (:subscribe-access-features . "Vyberte si plán pro plný přístup a správu plateb na jednom místě.")
 (:subscribe-view-plans . "Zobrazit plány")
 (:subscribe-faq-title . "Často kladené otázky")
 (:subscribe-faq-trial-q . "Co se stane po zkušební lhůtě zdarma?")
 (:subscribe-faq-trial-a . "14denní zkušební doba nevyžaduje kartu. Po jejím skončení si zvolte placený plán, abyste si ponechali plný přístup.")
 (:subscribe-faq-cancel-q . "Mohu kdykoliv zrušit?")
 (:subscribe-faq-cancel-a . "Ano! Předplatné můžete zrušit kdykoliv. Přístup si zachováte do konce fakturačního období.")
 (:subscribe-faq-payment-q . "Jaké platební metody přijímáte?")
 (:subscribe-faq-payment-a . "Přijímáme všechny hlavní kreditní a debetní karty prostřednictvím našeho platebního partnera Polar.sh.")
 (:subscribe-copyright . "Lambda Symbolics OÜ © 2026.")
(:subscribe-checkout-unavailable . "Pokladna je dočasně nedostupná. Zkuste to prosím znovu.")
(:subscribe-portal-unavailable . "Správa předplatného je dočasně nedostupná. Zkuste to prosím znovu.")
(:subscribe-founder-sold-out . "Nabídka pro zakládající členy je vyprodaná.")
(:subscribe-founder-unavailable . "Nabídka pro zakládající členy teď není dostupná.")
(:subscribe-checkout-cta . "Předplatit")

 ;; Errors and status
 (:error-generic . "Něco se pokazilo")
(:error-invalid-request . "Neplatná data požadavku.")
(:error-not-found . "Požadovaný prostředek nebyl nalezen.")
(:error-forbidden . "K této akci nemáte přístup.")
(:error-rate-limited . "Chvíli prosím počkejte a zkuste to znovu.")
 (:error-text-too-long . "Text je příliš dlouhý. Maximální délka překladu je 120 znaků.")
 (:error-input-too-long . "Vstup je příliš dlouhý")
 (:error-unknown-source-lang . "Vybraný zdrojový jazyk není podporován.")
 (:error-unknown-target-lang . "Vybraný cílový jazyk není podporován.")
 (:error-unknown-language . "Neznámý jazyk")
 (:error-translation-unavailable . "Překladová služba je dočasně nedostupná. Zkuste to prosím za chvíli.")
 (:error-translation-failed . "Překlad selhal")
 (:error-translation-retry . "Nepodařilo se vygenerovat překlad po několika pokusech. Zkuste přeformulovat text.")
 (:error-quota-exceeded . "Dosažen limit překladů")
 (:error-quota-exceeded-detail . "Vyčerpali jste všechny překlady na tento měsíc. Kvóta se automaticky obnoví každý měsíc.")
 (:quota-low-warning . "Zbývá pouze ~A překladů. Zvažte nákup dalších.")
 (:top-up-button . "Koupit další překlady")
 (:top-up-price . "5 €")
 (:top-up-amount . "300 překladů")
(:review-session-expired . "Vaše opakovací relace vypršela. Začněte prosím novou relaci.")

 (:error-session-expired . "Vaše relace vypršela. Přihlaste se prosím znovu.")
 (:error-session-invalid . "Vaše relace už není platná. Přihlaste se prosím znovu.")
 (:error-custom-flashcard-generation . "Nepodařilo se vytvořit vysvětlení. Zkuste to prosím znovu.")
 ;; Institutions
 (:institutions-page-title . "Hiisi pro školy a univerzity")
 (:institutions-hero-title . "Nástroje pro výuku jazyků vytvořené pro výuku ve třídě")
 (:institutions-hero-subtitle . "Dopřejte svým studentům sdílené balíčky, procvičování s ohledem na gramatiku a pravidelné opakování, které zapadá do skutečné výuky.")
 (:institutions-section-title . "Proč instituce používají Hiisi")
 (:institutions-section-body . "Hiisi pomáhá učitelům proměnit materiály z výuky v řízené studium, které studenti opravdu stíhají. Vytvořte balíčky pro kurz, sdílejte je odkazem a podpořte procvičování slovní zásoby i gramatiky bez další administrativní zátěže.")
 (:institutions-benefit-1 . "Sdílené balíčky a vlastní úkoly, které odpovídají vašemu kurikulu.")
 (:institutions-benefit-2 . "Lajky a nelajky studentů pomáhají vyzdvihnout nejlepší překlady pro běžné fráze z výuky.")
 (:institutions-benefit-3 . "Gramatické rozbory a rozložené opakování podporují víc než jen memorování izolovaných slovíček.")
 (:institutions-benefit-4 . "Podpora s učitelským pohledem od člověka, který pozorně naslouchá a bere potřeby výuky vážně.")
 (:institutions-request-title . "Začněme rozhovor")
 (:institutions-request-subtitle . "Napište nám o své instituci, jazycích i o tom, jakou podporu ve výuce potřebujete. Ozveme se vám do týdne.")
 (:institutions-aside-title . "Co bude následovat")
 (:institutions-aside-body . "Posoudíme vaše potřeby a do týdne se ozveme, abychom probrali přístup a nastavení pro vaši instituci.")
 (:institutions-field-name . "Název instituce")
 (:institutions-field-name-placeholder . "Vaše univerzita")
 (:institutions-field-contact-name . "Jméno kontaktní osoby")
 (:institutions-field-contact-name-placeholder . "Vaše jméno")
 (:institutions-field-contact-email . "Kontaktní e-mail")
 (:institutions-field-contact-email-placeholder . "vy@univerzita.cz")
 (:institutions-field-domains . "E-mailové domény")
 (:institutions-field-domains-placeholder . "univerzita.cz, fit.univerzita.cz")
 (:institutions-field-domains-help . "Seznam e-mailových domén vaší instituce oddělených čárkou")
 (:institutions-field-notes . "Další informace")
 (:institutions-field-notes-placeholder . "Odhadovaný počet studentů, preferovaný fakturační cyklus, speciální požadavky...")
 (:institutions-submit . "Odeslat poptávku")
 (:institutions-success-title . "Děkujeme - Hiisi pro školy a univerzity")
 (:institutions-success-heading . "Děkujeme!")
 (:institutions-success-body . "Obdrželi jsme vaši poptávku. Podíváme se na potřeby vaší instituce a ozveme se vám do týdne.")
 (:institutions-success-back . "Zpět na úvod")

 ;; Footer
 (:footer-privacy . "Zásady ochrany osobních údajů")
 (:footer-terms . "Podmínky služby")

 ;; Early software notice
 (:early-software-notice . "Hiisi je v rané fázi vývoje. Našli jste chybu nebo máte návrh?")

 ;; Privacy Policy
 (:privacy-title . "Zásady ochrany osobních údajů")
 (:privacy-updated . "Poslední aktualizace: leden 2026")
 (:privacy-who-title . "Kdo jsme")
 (:privacy-who-body . "Hiisi provozuje Lambda Symbolics OÜ, společnost registrovaná v Estonsku. Jako estonská společnost dodržujeme Obecné nařízení o ochraně osobních údajů (GDPR) Evropské unie.")
 (:privacy-collect-title . "Jaké údaje shromažďujeme")
 (:privacy-collect-intro . "Při používání Hiisi shromažďujeme následující informace:")
 (:privacy-collect-account-key . "Účetní informace: ")
 (:privacy-collect-account-val . "E-mailová adresa, zobrazované jméno a bezpečně hashované heslo.")
 (:privacy-collect-learning-key . "Vzdělávací data: ")
 (:privacy-collect-learning-val . "Vaše překlady, uložené kartičky a historie opakování.")
 (:privacy-collect-usage-key . "Údaje o používání: ")
 (:privacy-collect-usage-val . "Základní serverové protokoly pro bezpečnost a účely ladění.")
 (:privacy-use-title . "Jak používáme vaše údaje")
 (:privacy-use-auth-key . "Ověřování: ")
 (:privacy-use-auth-val . "K ověření vaší identity a zabezpečení vašeho účtu.")
 (:privacy-use-service-key . "Poskytování služeb: ")
 (:privacy-use-service-val . "K poskytování překladů a správě vaší sbírky kartiček.")
 (:privacy-use-ai-key . "AI překlady: ")
 (:privacy-use-ai-val . "Vaše požadavky na překlad jsou odesílány do OpenRouteru za účelem generování odpovědí. OpenRouter může požadavky předávat nakonfigurovanému poskytovateli modelu. Informace o tom, jak s těmito údaji nakládá, najdete v zásadách ochrany osobních údajů OpenRouteru.")
 (:privacy-third-title . "Služby třetích stran")
 (:privacy-third-intro . "Používáme následující služby třetích stran:")
 (:privacy-third-openrouter-key . "OpenRouter: ")
 (:privacy-third-openrouter-val . "Pro automatické požadavky na překlad.")
 (:privacy-third-mailgun-key . "Mailgun: ")
 (:privacy-third-mailgun-val . "Pro odesílání aktivačních e-mailů a transakčních zpráv.")
 (:privacy-third-polar-key . "Polar.sh: ")
 (:privacy-third-polar-val . "Pro zpracování plateb za předplatné.")
 (:privacy-cookies-title . "Soubory cookie")
 (:privacy-cookies-intro . "Používáme pouze nezbytné soubory cookie:")
 (:privacy-cookies-auth-key . "Ověřovací token: ")
 (:privacy-cookies-auth-val . "Bezpečný soubor cookie s atributem HTTP-only, který udržuje vaše přihlášení.")
 (:privacy-cookies-lang-key . "Preference jazyka: ")
 (:privacy-cookies-lang-val . "K zapamatování vašeho preferovaného jazyka rozhraní.")
 (:privacy-retention-title . "Uchovávání údajů")
 (:privacy-retention-body . "Vaše údaje jsou uchovávány po celou dobu existence vašeho účtu. Při žádosti o smazání je váš účet naplánován na smazání do 14 dnů.")
 (:privacy-rights-title . "Vaše práva (GDPR)")
 (:privacy-rights-intro . "Podle GDPR máte právo:")
 (:privacy-rights-access . "Přístup k vašim osobním údajům")
 (:privacy-rights-export . "Exportovat vaše údaje (dostupné na /app/api/export)")
 (:privacy-rights-correct . "Požádat o opravu nepřesných údajů")
 (:privacy-rights-delete . "Požádat o smazání vašeho účtu a údajů")
 (:privacy-rights-object . "Vznést námitku proti zpracování vašich údajů")
 (:privacy-rights-contact . "Pro uplatnění těchto práv nás kontaktujte na")
 (:privacy-contact-title . "Kontakt")
 (:privacy-contact-intro . "Pro dotazy týkající se ochrany osobních údajů:")
 (:privacy-contact-email-label . "E-mail: ")
 (:privacy-address-1 . "Lambda Symbolics OÜ")
 (:privacy-address-2 . "Harju maakond, Tallinn, Kesklinna linnaosa, Tornimäe tn 5, 10145")

 ;; Terms of Service
 (:terms-title . "Podmínky služby")
 (:terms-updated . "Poslední aktualizace: leden 2026")
 (:terms-1-title . "1. Popis služby")
 (:terms-1-body . "Hiisi je jazyková výuková aplikace, která poskytuje automatické překlady s gramatickými vysvětleními a kartičky s rozloženým opakováním. Službu provozuje Lambda Symbolics OÜ.")
 (:terms-2-title . "2. Registrace účtu")
 (:terms-2-body . "Pro používání Hiisi musíte vytvořit účet s platnou e-mailovou adresou. Jste zodpovědní za zabezpečení svých přihlašovacích údajů.")
 (:terms-3-title . "3. Předplatné a platby")
 (:terms-3-body . "Hiisi nabízí placené plány předplatného (měsíční a roční). Předplatné se zpracovává prostřednictvím Polar.sh.")
 (:terms-3-list-1 . "Předplatné se automaticky obnovuje, pokud není zrušeno před datem obnovení.")
 (:terms-3-list-2 . "Refundace jsou poskytovány v souladu s platnými zákony na ochranu spotřebitele.")
 (:terms-3-list-3 . "Neuhrazení plateb má za následek ztrátu přístupu k prémiovým funkcím.")
 (:terms-4-title . "4. Přijatelné používání")
 (:terms-4-intro . "Souhlasíte, že nebudete:")
 (:terms-4-list-1 . "Používat službu k jakémukoli nezákonnému účelu")
 (:terms-4-list-2 . "Pokoušet se obejít limity používání nebo bezpečnostní opatření")
 (:terms-4-list-3 . "Sdílet své přihlašovací údaje s ostatními")
 (:terms-4-list-4 . "Používat automatizované nástroje pro přístup ke službě způsobem, který zhoršuje výkon pro ostatní")
 (:terms-5-title . "5. Obsah a duševní vlastnictví")
 (:terms-5-body-1 . "Překlady generované Hiisi jsou vytvářeny automaticky a nemusí být unikátní. Své překlady a kartičky můžete používat pro jakýkoli osobní účel, ale nemáte výhradní autorská práva k automaticky generovanému obsahu.")
 (:terms-5-body-2 . "Aplikace Hiisi, značka a původní obsah zůstávají majetkem Lambda Symbolics OÜ.")
 (:terms-6-title . "6. Dostupnost služby")
 (:terms-6-intro . "Hiisi je poskytováno na bázi \"jak je\". Negarantujeme:")
 (:terms-6-list-1 . "Nepřerušenou nebo bezchybnou službu")
 (:terms-6-list-2 . "Přesnost automaticky generovaných překladů")
 (:terms-6-list-3 . "Dostupnost konkrétních funkcí")
 (:terms-6-body . "Funkce můžeme kdykoli upravit nebo ukončit.")
 (:terms-7-title . "7. Omezení odpovědnosti")
 (:terms-7-body-1 . "V maximální míře povolené zákonem nenese Lambda Symbolics OÜ odpovědnost za žádné nepřímé, náhodné, zvláštní nebo následné škody vzniklé z vašeho používání Hiisi.")
 (:terms-7-body-2 . "Naše celková odpovědnost nepřekročí částku, kterou jste zaplatili za službu v 12 měsících předcházejících nároku.")
 (:terms-8-title . "8. Ukončení účtu")
 (:terms-8-body-1 . "Váš účet můžeme pozastavit nebo ukončit, pokud porušíte tyto podmínky. O smazání účtu můžete požádat kdykoli prostřednictvím aplikace.")
 (:terms-8-body-2 . "Po žádosti o smazání je váš účet naplánován na smazání do 14 dnů.")
 (:terms-9-title . "9. Změny podmínek")
 (:terms-9-body . "Tyto podmínky můžeme čas od času aktualizovat. Pokračování v používání Hiisi po změnách představuje přijetí nových podmínek.")
 (:terms-10-title . "10. Rozhodné právo")
 (:terms-10-body . "Tyto podmínky se řídí zákony Estonska. Jakékoli spory budou řešeny u soudů v Estonsku.")
 (:terms-contact-title . "Kontakt")
 (:terms-contact-intro . "Pro dotazy k těmto podmínkám:")
 (:terms-contact-email-label . "E-mail: ")
 (:terms-address-1 . "Lambda Symbolics OÜ")
 (:terms-address-2 . "Harju maakond, Tallinn, Kesklinna linnaosa, Tornimäe tn 5, 10145")

 ;; Decks
 (:decks-title . "Balíčky")
 (:decks-subtitle . "Vytvářejte vlastní balíčky a sdílejte je s ostatními.")
 (:decks-create-title . "Vytvořit balíček")
 (:decks-name-placeholder . "Název balíčku")
 (:decks-desc-placeholder . "Popis")
 (:decks-create-btn . "Vytvořit balíček")
 (:decks-edit-title . "Upravit balíček")
 (:decks-edit-btn . "Upravit balíček")
 (:decks-update-btn . "Uložit změny")
 (:decks-default-badge . "Automatický")
 (:decks-default-description . "Tento balíček se pro tento jazykový pár spravuje automaticky.")
 (:decks-default-readonly . "Automatické balíčky mají pevné názvy a popisy.")
 (:decks-delete-btn . "Smazat balíček")
 (:decks-delete-confirm . "Opravdu chcete smazat tento balíček?")
 (:decks-error-name-required . "Název balíčku je povinný.")
 (:decks-error-name-too-long . "Název balíčku může mít nejvýše ~A znaků.")
 (:decks-error-desc-too-long . "Popis balíčku může mít nejvýše ~A znaků.")
 (:decks-error-default-readonly . "Automatické balíčky nelze upravovat.")
 (:decks-error-default-delete-forbidden . "Automatické balíčky nelze mazat.")
 (:decks-your-title . "Vaše balíčky")
 (:decks-col-updated . "Aktualizováno")
 (:decks-no-decks . "Zatím žádné balíčky.")
 (:decks-open-btn . "Otevřít")
 (:decks-no-desc . "Bez popisu.")
 (:decks-share-title . "Odkaz ke sdílení")
 (:decks-share-info . "Kdokoli s tímto odkazem může balíček importovat:")
 (:decks-share-copy . "Kopírovat odkaz")
 (:decks-share-copied . "Zkopírováno")
 (:decks-add-from-flashcards-title . "Přidat překlady")
 (:decks-add-from-flashcards-info . "Vyberte kartičku a přidejte její překlad do tohoto balíčku.")
 (:decks-open-flashcards . "Přidat z kartiček")
 (:decks-filter-from . "Z jazyka")
 (:decks-filter-to . "Do jazyka")
 (:decks-filter-any . "Jakýkoli jazyk")
 (:decks-filter-include-assigned . "Zahrnout kartičky, které už jsou v balíčku")
 (:decks-flashcards-add . "Přidat")
 (:decks-flashcards-added . "Přidáno")
 (:decks-flashcards-in-deck . "V jiném balíčku")
 (:decks-flashcards-empty . "Žádné kartičky neodpovídají těmto filtrům.")
 (:decks-items-title . "Položky balíčku")
 (:decks-col-original . "Originál")
 (:decks-col-translated . "Překlad")
 (:decks-col-lang . "Cílový jazyk")
 (:decks-no-items . "Zatím žádné položky.")
 (:decks-share-page-title . "Sdílet balíček")
 (:decks-share-preview . "Náhled a import tohoto balíčku.")
 (:decks-import-title . "Import")
 (:decks-import-btn . "Importovat balíček")
 (:starter-decks-title . "Knihovna")
 (:starter-decks-subtitle . "Importujte hotové balíčky od Hiisi a komunity.")
 (:starter-decks-marketplace-btn . "Knihovna")
 (:starter-decks-explanation-language . "Jazyk vysvětlení")
 (:starter-decks-search-label . "Hledat")
 (:starter-decks-source-label . "Zdroj")
 (:starter-decks-source-all . "Všechny balíčky")
 (:starter-decks-search-placeholder . "Hledat v knihovně")
 (:starter-decks-apply-filters . "Použít filtry")
 (:starter-decks-select-triplet-hint . "Vyberte zdrojový a cílový jazyk a procházejte odpovídající balíčky.")
 (:starter-decks-official-badge . "Oficiální")
 (:starter-decks-community-badge . "Komunitní")
 (:starter-decks-by-hiisi . "Od Hiisi")
 (:starter-decks-preview-btn . "Náhled")
 (:starter-decks-card-count . "~A karet")
 (:starter-decks-no-results . "Žádné balíčky neodpovídají těmto filtrům.")
 (:starter-decks-source-cards-title . "Karty v tomto balíčku")
 (:starter-decks-sample-title . "Ukázkové karty")
 (:starter-decks-generating . "Balíček se vytváří...")
 (:starter-decks-generating-detail . "Tento balíček se právě vytváří pro vaši jazykovou trojici. Nechte tuto stránku otevřenou nebo se za chvíli vraťte.")
 (:starter-decks-generation-failed . "Vytváření selhalo")
 (:starter-decks-generation-failed-detail . "Poslední pokus o vytvoření selhal. Zkuste balíček importovat znovu.")
 (:starter-decks-login-detail . "Pro import tohoto balíčku do své sbírky se přihlaste.")
 (:starter-decks-subscribe-btn . "Zobrazit tarify")
 (:starter-decks-subscribe-detail . "Balíčky z knihovny jsou dostupné s aktivním předplatným nebo zkušební verzí.")
 (:library-submit-title . "Odeslat do knihovny")
 (:library-submit-intro . "Odešlete tento balíček do knihovny k administrátorskému schválení před zveřejněním.")
 (:library-submit-btn . "Odeslat balíček")
 (:library-submit-approved . "Schváleno pro knihovnu")
 (:library-submit-approved-detail . "Tento balíček je zveřejněný v knihovně.")
 (:library-submit-pending . "Čeká na schválení")
 (:library-submit-pending-detail . "Tento balíček byl odeslán a čeká na administrátorské schválení.")
 (:library-submit-rejected . "Potřebuje úpravy před zveřejněním")
 (:library-submit-rejected-detail . "Toto odeslání bylo zamítnuto. Upravte balíček a odešlete ho znovu.")
 (:library-error-empty . "Před odesláním tohoto balíčku do knihovny přidejte alespoň jednu kartu.")
 (:library-error-missing-triplet . "Každá karta v odeslaném balíčku do knihovny musí mít úplnou jazykovou trojici.")
 (:library-error-mixed-triplet . "Všechny karty v odeslaném balíčku do knihovny musí sdílet stejnou jazykovou trojici.")
 (:starter-deck-topic-greetings-title . "Pozdravy a představování")
 (:starter-deck-topic-greetings-description . "Pozdravy, jména, zdvořilé základy a fráze pro první setkání.")
 (:starter-deck-topic-travel-title . "Základní cestování")
 (:starter-deck-topic-travel-description . "Nádraží, jízdenky, ceny, pomoc a orientace na cestách.")
 (:starter-deck-topic-numbers-title . "Čísla a ceny")
 (:starter-deck-topic-numbers-description . "Počítání, součty, ceny, patra a běžná množství.")
 (:starter-deck-topic-time-title . "Čas a data")
 (:starter-deck-topic-time-description . "Dny, měsíce, schůzky, čas na hodinách a relativní data.")
 (:starter-deck-topic-food-title . "Restaurace a jídlo")
 (:starter-deck-topic-food-description . "Objednávání, stravovací omezení, nápoje, účet a běžná jídla mimo domov.")
 (:starter-deck-topic-emergency-title . "Pohotovost a zdraví")
 (:starter-deck-topic-emergency-description . "Lékaři, lékárny, příznaky, části těla a naléhavá pomoc.")
 (:starter-deck-topic-directions-title . "Směry a doprava")
 (:starter-deck-topic-directions-description . "Odbočování, zastávky, jízdenky, nástupiště a pohyb po městě.")
 (:starter-deck-topic-school-title . "Škola a vzdělávání")
 (:starter-deck-topic-school-description . "Vyučování, domácí úkoly, zkoušky, školní pomůcky a každodenní školní život.")
 (:starter-deck-topic-university-title . "Univerzita a studium")
 (:starter-deck-topic-university-description . "Přednášky, semináře, studijní obory, úkoly a každodenní život na univerzitě.")

 ;; Flashcards management page
 (:flashcards-title . "Moje kartičky")
 (:flashcards-subtitle . "Všechny vaše uložené kartičky na jednom místě. Hledejte, organizujte a spravujte.")
 (:flashcards-search-placeholder . "Hledat kartičky...")
 (:flashcards-filter-button . "Filtry")
 (:flashcards-filter-title . "Filtrovat kartičky")
 (:flashcards-filter-recollection . "Jak dobře je znáte")
 (:flashcards-filter-any-recollection . "Jakákoli míra znalosti")
 (:flashcards-hide-perfected . "Skrýt zvládnuté kartičky")
 (:flashcards-col-original . "Originál")
 (:flashcards-col-translated . "Překlad")
 (:flashcards-no-cards . "Zatím žádné kartičky. Začněte překládat a vytvořte si nějaké!")
 (:flashcards-image-label . "Obrázek")
 (:flashcards-image-upload . "Nahrát obrázek")
 (:flashcards-image-replace . "Nahradit obrázek")
 (:flashcards-image-remove . "Odstranit obrázek")

 ;; Landing page (redesign)
 (:landing-hero-headline . "Každé slovo vysvětlené. Každé opakování naplánované. Patnáct jazyků.")
 (:landing-hero-subheadline . "Hiisi je překladač, který vás učí gramatiku během čtení, a aplikace pro kartičky, která se buduje sama z toho, co skutečně překládáte.")
 (:landing-hero-trust-line . "14 dní zdarma. Karta není potřeba.")
 (:landing-credibility-languages . "15 jazyků")
 (:landing-credibility-ai . "Každé slovo vysvětlené")
 (:landing-credibility-srs . "Zabudované rozložené opakování")
 (:landing-languages-title . "Jazyky, které podporujeme")
 (:landing-step-1-title . "Vložte větu")
 (:landing-step-1-desc . "Jakkoli dlouhou, v kterémkoli ze 15 jazyků. Dostanete překlad a rozbor gramatiky každého slova.")
 (:landing-step-2-title . "Uložte, co stojí za zapamatování")
 (:landing-step-2-desc . "Jedním kliknutím se z překladu stane kartička s původní větou zachovanou jako kontext.")
 (:landing-step-3-title . "Opakujte ve správný okamžik")
 (:landing-step-3-desc . "Rozložené opakování pomocí SM-2, stejného algoritmu jako v Anki. Kartičky, se kterými se trápíte, se vrací dříve.")
 (:landing-feature-grammar-title . "Každé slovo vysvětlené ve vašem jazyce")
 (:landing-feature-grammar-desc . "Překlady obsahují pád, rod, vid a způsob rozepsané slovo po slovu. Finský partitiv, česká životnost, polský vid, německá dativní stažení, vše popsané a propojené s gramatickým průvodcem.")
 (:landing-feature-srs-title . "Návyk rozloženého opakování, automatizovaný")
 (:landing-feature-srs-desc . "Algoritmus rozloženého opakování SM-2 se přizpůsobí vašemu výkonu. Kartičky, se kterými máte potíže, se zobrazí častěji. Kartičky, které znáte, ustoupí.")
 (:landing-feature-share-title . "Vaše balíčky, nebo komunitní")
 (:landing-feature-share-desc . "Uspořádejte kartičky do tematických balíčků. Sdílejte jakýkoli balíček odkazem, nebo procházejte komunitní knihovnu a najděte balíčky od ostatních.")
 (:landing-pricing-trial-note . "Včetně 14 dní zkušební doby zdarma")
 (:landing-pricing-monthly-after . "14 dní zdarma, pak ~A/měsíc")
 (:landing-pricing-annual-after . "14 dní zdarma, pak ~A/rok")
 (:landing-faq-title . "Často kladené otázky")
 (:landing-faq-trial-cap-q . "Kolik překladů dostanu během zkušební doby?")
 (:landing-faq-trial-cap-a . "Během 14denní zkušební doby můžete přeložit až 200 textů. Po předplacení získáte 600 měsíčně.")
 (:landing-final-cta-title . "První věta zabere pět sekund.")
 (:landing-final-cta-subtitle . "Vložte cokoli ve finštině, češtině, polštině nebo v kterémkoli z dvanácti dalších jazyků. Uvidíte, co s tím Hiisi udělá. Čtrnáct dní zdarma.")

 ;; Trial status (in-app)
 (:trial-status . "Zkušební doba")
 (:error-trial-quota-exceeded . "Dosaženo limitu zkušebních překladů")
 (:error-trial-quota-detail . "Využili jste všech 200 zkušebních překladů. Předplaťte si a pokračujte v učení.")

 ;; Custom flashcards
 (:custom-flashcard-create-title . "Vytvořit kartičku")
 (:custom-flashcard-edit-title . "Upravit kartičku")
 (:custom-flashcard-original . "Původní text")
 (:custom-flashcard-translated . "Překlad")
 (:custom-flashcard-lang-from . "Zdrojový jazyk")
 (:custom-flashcard-lang-to . "Cílový jazyk")
 (:custom-flashcard-note . "Vzdělávací poznámka")
 (:custom-flashcard-forms . "Gramatický rozbor")
 (:custom-flashcard-form-term . "Výraz")
 (:custom-flashcard-form-explanation . "Vysvětlení")
 (:custom-flashcard-add-form . "Přidat gramatický výraz")
 (:custom-flashcard-remove-form . "Odstranit")
 (:custom-flashcard-ai-fill . "Vyplnit pomocí AI")
 (:custom-flashcard-create-btn . "Vytvořit kartičku")
 (:custom-flashcard-update-btn . "Uložit změny")

  ;; Newsletter
  (:newsletter-email-label . "E-mailová adresa")
  (:newsletter-developer-label . "Jsem vývojář")
  (:newsletter-developer-hint . "Posílat technické novinky")
  (:landing-newsletter-title . "Získejte novinky o Hiisi.")
  (:landing-newsletter-body . "Přihlaste se k newsletteru pro produktové novinky, podporu dalších jazyků, startovací balíčky a občasné nabídky pro zakládající členy.")
  (:landing-newsletter-fine-print . "Žádný spam. Jen produktové novinky.")
  (:landing-newsletter-button . "Přihlásit k newsletteru")
  (:newsletter-unsubscribe-page-title . "Odhlásit odběr newsletteru Hiisi")
  (:newsletter-unsubscribe-title . "Odhlásit odběr")
  (:newsletter-unsubscribe-subtitle . "Zadejte e-mail a odhlaste se z novinek o Hiisi.")
  (:newsletter-unsubscribe-button . "Odhlásit odběr")
  (:newsletter-feedback-email-required . "Zadejte prosím svou e-mailovou adresu.")
  (:newsletter-feedback-email-invalid . "Zadejte prosím platnou e-mailovou adresu.")
  (:newsletter-feedback-already-signed-up . "Už jste přihlášeni. Budeme vás informovat!")
  (:newsletter-feedback-signed-up . "Jste na seznamu! Budeme posílat občasné novinky o Hiisi.")
  (:newsletter-feedback-unsubscribed . "Pokud byl tento e-mail přihlášen, byl odebrán z novinek o Hiisi.")
  (:newsletter-feedback-generic-error . "Něco se pokazilo. Zkuste to prosím znovu.")

  ;; Hlásení problémů
 (:issues-open-button . "Nahlásit chybu")
 (:issues-modal-title . "Nahlásit problém")
 (:issues-modal-subtitle . "Popište, co se pokazilo. Aktuální stránku přiložíme automaticky.")
 (:issues-title-label . "Krátký název")
 (:issues-title-placeholder . "Stručné shrnutí problému")
 (:issues-message-label . "Co se stalo?")
 (:issues-message-placeholder . "Uveďte kroky k reprodukci, očekávané chování a co se stalo místo toho.")
 (:issues-submit . "Odeslat hlášení")
 (:issues-cancel . "Zrušit")
 (:issues-success . "Hlášení bylo odesláno. Co nejdříve se na něj podíváme.")
 (:issues-error-required . "Před odesláním prosím popište problém.")
 (:issues-error-title-too-long . "Název hlášení je příliš dlouhý. Prosím, zkraťte ho na méně než 160 znaků.")
 (:issues-error-too-long . "Text hlášení je příliš dlouhý. Zkraťte ho prosím pod 4000 znaků.")
 (:issues-error-rate-limit . "Z tohoto zdroje bylo odesláno příliš mnoho hlášení. Počkejte prosím a zkuste to znovu později.")
 (:issues-error-generic . "Hlášení problému se nepodařilo odeslat. Zkuste to prosím znovu.")

)
