;;; Danish translations
;;; This file mirrors the structure of en.lisp

(
 ;; Language metadata (used for language picker)
 (:lang-name . "Dansk")
 (:lang-flag . "🇩🇰")

 ;; Language modal (first-visit language selection)
 (:lang-modal-title . "Vælg dit sprog")
 (:lang-modal-subtitle . "Vælg dit foretrukne sprog til grænsefladen:")

 ;; Navigation
 (:nav-translate . "Oversæt")
 (:nav-review . "Gentag")
 (:nav-flashcards . "Mine kort")
 (:nav-dashboard . "Oversigt")
 (:nav-decks . "Kortbunker")
 (:nav-logout . "Log ud")
 (:nav-home . "Hjem")
 (:nav-pricing . "Priser")
 (:nav-institutions . "For institutioner")
 (:nav-export-data . "Eksporter data")
 (:nav-open-navigation . "Åbn navigationen")
 (:theme-light . "Lys")
 (:theme-dark . "Mørk")

 ;; App title and branding
 (:app-title . "Hiisi - Sproglæring")

 ;; Landing page
 (:landing-meta-title . "Hiisi: sproglæringsapp med grammatik og flashkort")
 (:app-meta-description . "Hiisi er en sproglæringsapp. Hver sætning, du oversætter, bliver til et flashkort med indbygget grammatik, planlagt med SM-2, Anki-algoritmen. 15 sprog.")
 (:trial-start-cta . "Kom i gang med Hiisi")
 (:subscription-best-value . "Bedste værdi")

 ;; Auth pages
 (:auth-register . "Registrer")
 (:auth-login . "Log ind")
 (:auth-email . "E-mail")
 (:auth-password . "Adgangskode")
 (:auth-password-again . "Bekræft adgangskode")
 (:auth-display-name . "Visningsnavn")
 (:auth-register-title . "Registrer dig på Hiisi")
 (:auth-register-subtitle . "Opret en ny konto")
 (:auth-login-title . "Log ind på Hiisi")
 (:auth-login-subtitle . "Indtast dine oplysninger")
 (:auth-login-invalid-credentials . "Ugyldig e-mail eller adgangskode.")
 (:auth-login-rate-limited . "For mange loginforsog. Vent et par minutter og prov igen.")
(:auth-register-rate-limited . "For mange registreringsforsøg. Vent et par minutter og prøv igen.")
(:auth-email-invalid . "Indtast en gyldig e-mailadresse.")
(:auth-password-too-short . "Adgangskoden skal være mindst 8 tegn lang.")
(:auth-passwords-mismatch . "Adgangskoderne stemmer ikke overens.")
(:auth-display-name-invalid . "Visningsnavnet skal være mellem 1 og 100 tegn langt.")
(:auth-register-email-exists . "Der findes allerede en konto med denne e-mailadresse.")
(:auth-register-unavailable . "Registrering er midlertidigt utilgængelig. Prøv igen senere.")
(:auth-register-plan-required . "Vælg en plan, før du opretter en konto.")
(:auth-preapproved-email-unrecognized . "Brug e-mailadressen fra din invitation, eller vælg en plan, før du opretter en konto.")
(:auth-institution-register . "Kommer du fra en institution?")
(:auth-institution-stage-title . "Institutionsadgang")
(:auth-institution-stage-subtitle . "Brug din skole- eller universitetsmail. Berettigede konti låses op gennem institutionen efter e-mailbekræftelse.")
(:auth-institution-title . "Registrer dig gennem din institution")
(:auth-institution-subtitle . "Brug din skole- eller universitetsmail. Hvis din institution allerede er sat op i Hiisi, låses din konto op efter e-mailbekræftelse; den individuelle 14-dages prøveperiode gælder registrering med en personlig plan.")
(:auth-institution-benefit-email . "Brug din skole- eller universitetsmailadresse.")
(:auth-institution-benefit-access . "Berettigede konti får institutionsadgang efter e-mailbekræftelse.")
(:auth-institution-benefit-fallback . "Hvis domænet ikke genkendes, skal du vælge en individuel plan eller bede din institution om at kontakte Hiisi.")
(:auth-see-included . "Se hvad der er inkluderet")
(:auth-institution-check-access . "Tjek adgang")
(:auth-institution-email-eligible-title . "Institutionsadgang bekræftet")
(:auth-institution-email-eligible-detail . "Fortsæt med denne e-mail for at oprette din konto. Adgangen låses op efter e-mailbekræftelse.")
(:auth-institution-change-email . "Brug en anden e-mail")
(:auth-institution-outcome-note . "Hvis din skole eller dit universitet giver adgang til Hiisi, låses din konto op efter e-mailbekræftelse. Hvis domænet ikke er berettiget, skal du vælge en personlig plan for at starte prøveperioden på 14 dage.")
(:auth-institution-personal-plan-link . "Se personlige planer")
(:auth-institution-domain-unrecognized . "Vi genkender endnu ikke dette institutionsdomæne. Vælg en personlig plan for at starte prøveperioden på 14 dage, eller bed din institution om at kontakte Hiisi.")
(:subscribe-institution-callout-title . "Bruger du Hiisi gennem en skole eller et universitet?")
(:subscribe-institution-callout-body . "Registrer dig med din institutionsmail, så låser Hiisi automatisk adgang op, hvis din institution allerede er sat op.")
(:auth-activation-email-send-failed . "Det lykkedes ikke at sende aktiveringsmailen. Prøv igen.")
 (:auth-forgot-password . "Glemt adgangskode?")
 (:auth-no-account . "Har du ikke en konto?")
 (:auth-have-account . "Har du allerede en konto?")
 (:auth-google . "Google")
 (:auth-google-login-failed . "Google-login mislykkedes. Prøv venligst igen.")
 (:auth-account-created . "Konto oprettet!")
 (:auth-check-email . "Tjek din e-mail for aktiveringslinket.")
 (:auth-redirect-login . "Omdirigerer til login om")
 (:auth-seconds . "sekunder...")
 (:auth-go-now . "Gå nu")
 (:auth-not-activated . "Konto ikke aktiveret")
 (:auth-activate-title . "Aktiver din konto!")
 (:auth-activated . "Konto aktiveret!")
 (:auth-activated-message . "Din konto er blevet aktiveret. Du kan nu bruge Hiisi.")
 (:auth-redirecting . "Omdirigerer om")
 (:auth-go-to-app . "Gå til appen")
 (:onboarding-title . "Hvordan Hiisi fungerer")
 (:onboarding-subtitle . "Oversæt rigtig tekst, se på grammatikken, gem nyttige elementer, og gennemgå dem senere.")
 (:onboarding-translate-detail . "Start med rigtig tekst. Hiisi viser oversættelsen, de tilpassede former og de næste studiehandlinger samlet ét sted.")
 (:onboarding-grammar-detail . "Åbn grammatikgennemgangen for at se, hvilke former der svarer til hinanden i sætningen, og hvilken funktion hver del har.")
 (:onboarding-review-detail . "Gem nyttige oversættelser og gennemgå dem senere med spaced repetition, så de bliver i langtidshukommelsen.")
 (:onboarding-decks-detail . "Saml nyttige elementer i bunker, del dem med andre, og hold beslægtet materiale samlet.")
 (:onboarding-back . "Tilbage")
 (:onboarding-next . "Næste")
 (:onboarding-skip . "Spring guiden over")
 (:auth-resend-title . "Gensend aktiveringsmail")
 (:auth-resend-subtitle . "Indtast din e-mail for at modtage et nyt aktiveringslink.")
 (:auth-resend-button . "Gensend aktiveringsmail")
 (:auth-resend-success . "Aktiveringsmail sendt!")
 (:auth-resend-success-detail . "Tjek din indbakke for det nye aktiveringslink.")
 (:auth-resend-rate-limited . "Vent venligst et par minutter før du anmoder om en ny aktiveringsmail.")
 (:auth-resend-cooldown . "Du kan anmode om en ny mail om ~a sekunder.")
 (:auth-back-to-login . "Tilbage til login")
 (:auth-forgot-password-title . "Glemt adgangskode")
 (:auth-forgot-password-subtitle . "Indtast din e-mail, så sender vi dig et link til at nulstille din adgangskode.")
 (:auth-send-reset-link . "Send nulstillingslink")
 (:auth-reset-email-sent . "Nulstillingslink sendt!")
 (:auth-reset-email-sent-detail . "Hvis en konto findes med den e-mail, vil du snart modtage et link til nulstilling af adgangskoden.")
 (:auth-reset-rate-limited . "Vent venligst et par minutter før du anmoder om en ny nulstilling af adgangskoden.")
 (:auth-reset-invalid-token . "Dette nulstillingslink er ugyldigt eller udløbet.")
 (:auth-reset-password-title . "Nulstil adgangskode")
 (:auth-reset-password-subtitle . "Indtast din nye adgangskode nedenfor.")
 (:auth-new-password . "Ny adgangskode")
 (:auth-confirm-new-password . "Bekræft ny adgangskode")
 (:auth-reset-password . "Nulstil adgangskode")
 (:auth-password-changed . "Adgangskode ændret!")
 (:auth-password-changed-detail . "Din adgangskode er blevet ændret. Du kan nu logge ind med din nye adgangskode.")
 (:auth-change-password-title . "Skift adgangskode")
 (:auth-change-password-subtitle . "Opdater din kontos adgangskode.")
 (:auth-current-password . "Nuværende adgangskode")
 (:auth-change-password . "Skift adgangskode")
 (:auth-back-to-app . "Tilbage til appen")
 (:auth-password-updated . "Adgangskode opdateret!")
 (:auth-password-updated-detail . "Din adgangskode er blevet opdateret.")
(:auth-current-password-invalid . "Den nuværende adgangskode er forkert.")
(:auth-new-password-same . "Den nye adgangskode skal være forskellig fra den nuværende adgangskode.")

 ;; Email copy
 (:email-common-hi . "Hej")
 (:email-common-tagline . "Hiisi - Lær gennem oversættelse")
 (:email-activation-subject . "Aktivér din Hiisi-konto")
 (:email-activation-title . "Velkommen til Hiisi")
 (:email-activation-body . "Tak for din registrering. Aktivér din konto ved at klikke på linket nedenfor:")
 (:email-activation-button . "Aktivér konto")
 (:email-activation-copy-link . "Eller kopiér dette link")
 (:email-activation-expiry . "Dette link udløber om 24 timer.")
 (:email-reset-subject . "Nulstil din Hiisi-adgangskode")
 (:email-reset-title . "Anmodning om nulstilling af adgangskode")
 (:email-reset-body . "Vi har modtaget en anmodning om at nulstille din adgangskode. Klik på linket nedenfor for at angive en ny adgangskode:")
 (:email-reset-button . "Nulstil adgangskode")
 (:email-reset-expiry . "Dette link udløber om 1 time.")
 (:email-reset-ignore . "Hvis du ikke bad om at få nulstillet din adgangskode, kan du ignorere denne e-mail.")
 (:email-reminder-subject-due . "Tid til at gennemgå dine Hiisi-kort")
 (:email-reminder-subject-streak . "Hold din Hiisi-stime i gang")
 (:email-reminder-cards-due . "kort klar til gennemgang")
 (:email-reminder-keep-going . "Der er gået et par dage siden din seneste repetition. Fem minutter i dag er nok til, at det, du allerede har lært, ikke glider ud af hukommelsen.")
 (:email-reminder-button . "Gennemgå nu")
 (:email-reminder-settings . "Administrer påmindelser")
 (:email-reminder-preview-title . "Kort der venter på dig")
 (:email-reminder-translation-label . "Oversættelse")
 (:email-reminder-more-due-today . "flere kort til gennemgang i dag")
 (:email-trial-subject . "Hvordan går din Hiisi-prøveperiode?")
 (:email-trial-expiring . "Din gratis Hiisi-prøveperiode slutter i morgen.")
 (:email-trial-feedback . "Nyder du Hiisi? Fortæl os, hvad der hjælper dig mest.")
 (:email-trial-strengths . "Du kan oversætte rigtige tekster, gemme de bedste elementer som flashcards og lære med distribueret repetition.")
 (:email-trial-reply . "Svar på denne e-mail, så går din besked direkte til Hiisi-teamet.")
 (:email-trial-button . "Vælg et abonnement")
 (:email-trial-manage . "Administrer abonnement")
 (:email-trial-contact . "Skriv til os")
 (:email-plan-nudge-subject . "Dine oversættelser venter")
 (:email-plan-nudge-title . "Dine oversættelser venter")
 (:email-plan-nudge-intro . "Du har oprettet dig i Hiisi, men har endnu ikke valgt et abonnement.")
 (:email-plan-nudge-benefits-intro . "Det får du med et abonnement:")
 (:email-plan-nudge-benefit-translations . "600 oversættelser om måneden med grammatiske gennemgange")
 (:email-plan-nudge-benefit-flashcards . "Ubegrænsede flashcards med distribueret repetition")
 (:email-plan-nudge-benefit-decks . "Egne sæt, som du kan organisere og dele")
 (:email-plan-nudge-pricing . "Abonnementerne starter ved 10 EUR om måneden, eller spar med årsabonnementet til 100 EUR om året (to måneder gratis).")
 (:email-plan-nudge-feedback . "Hvis noget i Hiisi ikke fungerer for dig, så svar på denne e-mail. Din besked går direkte til Hiisi-teamet.")
 (:email-plan-nudge-button . "Vælg et abonnement")
 (:email-plan-nudge-unsubscribe . "Afmeld disse e-mails")
 (:email-plan-nudge-unsubscribe-done-title . "E-mails om abonnement er slået fra")
 (:email-plan-nudge-unsubscribe-done-body . "Du vil ikke modtage flere påmindelser om at vælge et abonnement.")
 (:email-plan-nudge-unsubscribe-invalid-title . "Dette link er ikke gyldigt")
 (:email-plan-nudge-unsubscribe-invalid-body . "Dette afmeldingslink mangler, er udløbet eller er ikke længere gyldigt.")
 (:email-invite-subject . "Du er blevet inviteret til Hiisi")
 (:email-invite-title . "Du er blevet inviteret til Hiisi")
 (:email-invite-intro . "Du er blevet inviteret til at bruge Hiisi gratis som tester, værdsat ven eller begge dele.")
 (:email-invite-details . "Brug knappen nedenfor til at oprette din konto og begynde at udforske oversættelser og flashcards.")
 (:email-invite-button . "Opret konto")
 (:email-invite-issue-reporting . "Hvis noget går i stykker eller føles forkert, er der en knap til at rapportere et problem nederst på hver side.")
 (:email-issue-completed-subject . "Det problem, du rapporterede i Hiisi, er blevet rettet")
 (:email-issue-completed-title . "Problemet er rettet")
 (:email-issue-completed-label . "Problem")
 (:email-issue-completed-followup . "Åbn Hiisi for at kontrollere rettelsen eller fortsætte, hvor du slap.")
 (:email-issue-completed-button . "Åbn Hiisi")
 (:email-issue-completed-open-link . "Åbn side")

 ;; Translation page
 (:translate-title . "Oversæt")
 (:translate-input-title . "Input")
 (:translate-input-label . "Tekst at oversætte")
 (:translate-input-placeholder . "Indtast tekst at oversætte...")
 (:translate-example-chip . "Prøv et eksempel:")
 (:translate-example-sentence . "Jeg glemte mine nøgler derhjemme.")
 (:translate-from . "Kildesprog:")
 (:translate-to . "Målsprog:")
 (:translate-select-target-placeholder . "Vælg målsprog")
 (:translate-submit . "Oversæt")
 (:translate-auto-detect . "Alle (Automatisk)")
 (:translate-empty-state . "Oversæt et ord eller en frase, så ser du resultatet, grammatikgennemgangen og studiehandlingerne her.")
 (:translate-select-deck-placeholder . "Vælg kortbunke (valgfrit)")
 (:translate-result-title . "Oversættelsesresultat")
 (:translate-save-destination-label . "Gem til")
 (:translate-save-to-my-cards . "Mine kort (standard)")
 (:translate-save-to-deck . "Gem i kortsæt")
 (:translate-saved-to-my-cards . "Gemt i Mine kort")
 (:translate-saved-to-deck . "Gemt i ~A")
 (:translate-view-my-cards . "Vis Mine kort")
 (:translate-new-deck . "Opret ny kortbunke")
 (:translate-add-to-deck . "Tilføj til kortbunke")
 (:translate-feedback-label . "Kvalitetsfeedback")
 (:translate-feedback-helpful . "Nyttig")
 (:translate-feedback-helpful-marked . "Markeret som nyttig")
 (:translate-regenerate-translation . "Generer oversættelsen igen")
 (:translate-regenerate-confirm . "Hiisi markerer dette resultat som upræcist og genererer en ny oversættelse. Fortsæt?")
 (:pronunciation-label . "Udtale")
 (:pronunciation-show . "Vis udtale")
 (:pronunciation-hide . "Skjul udtale")
 (:grammar-term-examples . "Eksempler")
 (:grammar-term-related . "Relaterede termer")
 (:grammar-term-modal-title . "Grammatikterm")
 (:grammar-term-empty . "Vælg et fremhævet begreb for at se detaljerne.")
 (:extension-login-required . "Log ind på Hiisi, før du bruger browserudvidelsen.")
 (:extension-session-invalid . "Din Hiisi-session er ikke længere gyldig. Log ind igen.")
 (:extension-activation-required . "Aktivér din Hiisi-konto, før du bruger browserudvidelsen.")
 (:extension-subscription-required . "Start en Hiisi-prøveperiode, før du bruger browserudvidelsen.")

 ;; Translation and Flashcards
 (:lang-auto . "Auto")
 (:lang-unknown . "?")
 (:lang-target . "Mål")
 (:translate-deck-create-title . "Opret ny kortbunke")
 (:translate-deck-name-label . "Kortbunkens navn")
 (:translate-deck-name-placeholder . "f.eks. Finsk grundlag")
 (:translate-deck-description-label . "Beskrivelse (valgfri)")
 (:translate-deck-cancel . "Annuller")
 (:translate-deck-create . "Opret")
 (:translate-rate-label . "Bedøm oversættelse")
 (:flashcards-delete . "Slet")
 (:flashcards-delete-confirm . "Er du sikker på, at du vil slette dette kort?")
 (:flashcards-deck-search-placeholder . "Søg i kortbunker...")
 (:flashcards-no-decks . "Ingen kortbunker endnu. Opret en først!")
 (:flashcards-deck-cancel . "Annuller")
 (:flashcards-recollection-tooltip . "Hukommelse: ~A")
 (:flashcards-recollection-poor . "Svag")
 (:flashcards-recollection-fair . "Rimelig")
 (:flashcards-recollection-normal . "Normal")
 (:flashcards-recollection-strong . "Stærk")
 (:flashcards-recollection-very-strong . "Meget stærk")

 ;; Flashcard review
 (:review-title . "Gentag")
 (:review-session-title . "Gentagelsessession")
 (:review-session-subtitle . "Øv dine gemte flashcards")
 (:review-selector-title . "Vælg hvad du vil gentage")
 (:review-selector-subtitle . "Vælg et kortsæt eller et sprogpar at fokusere din gentagelsessession på.")
 (:review-by-deck . "Gentag efter kortsæt")
 (:review-by-language-pair . "Gentag efter sprogpar")
 (:review-all-cards . "Gentag alle kort")
 (:review-cards-due . "kort til gennemgang")
 (:review-deck-caught-up . "Alt gennemgået")
 (:review-all-caught-up . "Alt gennemgået!")

 (:review-no-cards . "Ingen kort at gentage")
 (:review-no-cards-desc . "Du har ingen flashcards der skal gentages lige nu.")
 (:review-no-cards-hint . "Oversæt noget tekst og klik \"Gem som flashcard\" for at opbygge din samling!")
 (:review-start-translating . "Begynd at oversætte")
 (:review-click-reveal . "Klik for at vise svar")
 (:review-grammar-breakdown . "Grammatisk analyse")
 (:review-how-well . "Kunne du huske det?")
 (:review-again . "Nej")
 (:review-hard . "Knap nok")
 (:review-good . "Ja")
 (:review-easy . "Nemt")
 (:review-progress . "Kort ~a af ~a")
 (:review-correct-count . "Rigtigt")
 (:review-wrong-count . "Forkert")
 (:mockup-forgot-detail . "1. person ental præteritum af \"olvidar\" (at glemme)")
 (:mockup-keys-detail . "Ejestedord \"mis\" med feminint flertalssubstantiv \"llaves\" (nøgler)")
 (:review-complete . "Session fuldført!")
 (:review-complete-msg . "Du gennemgik ~a kort")
 (:review-again-btn . "Gentag igen")
 (:review-translate-more . "Oversæt mere")
 (:review-streak . "dages række")

 ;; Dashboard
 (:dashboard-title . "Oversigt")
 (:dashboard-welcome-title . "Oversæt din første tekst")
 (:dashboard-welcome-subtitle . "Oversæt en nyttig vending, gem den i et kortsæt, og gennemgå den, når det gælder.")
 (:dashboard-take-quick-tour . "Tag en hurtig rundtur")
 (:dashboard-cards-due . "Kort for i dag")
 (:dashboard-total-cards . "Kort i alt")
 (:dashboard-mastered-cards . "Mestrede kort")
 (:dashboard-subscription . "Abonnement")
 (:dashboard-subscribed-until . "Abonnerer til")
 (:dashboard-trial-ends . "Prøveperioden slutter")
 (:dashboard-not-subscribed . "Ikke abonneret")
 (:dashboard-recent . "Seneste oversættelser")
 (:dashboard-no-translations . "Ingen oversættelser endnu")
 (:dashboard-streak . "Gentagelsesrække")
 (:dashboard-days . "dage")
 (:dashboard-all-caught-up . "Du er ajour!")
 (:dashboard-all-caught-up-hint . "Oversæt mere for at udbygge din samling.")
 (:dashboard-no-cards-title . "Opret dine første studiekort")
 (:dashboard-no-cards-hint . "Oversæt tekst, og gem nyttige vendinger for at opbygge din samling.")
 (:dashboard-first-use-checklist-title . "Første skridt")
 (:dashboard-first-use-checklist-translate . "Lav din første oversættelse")
 (:dashboard-first-use-checklist-card . "Gem dit første kort")
 (:dashboard-first-use-checklist-review . "Gennemfør din første repetition")
 (:dashboard-getting-started . "Kom godt i gang")
 (:dashboard-tip-1 . "Oversæt tekst du vil lære")
 (:dashboard-tip-2 . "Klik \"Gem som flashcard\" på oversættelser du vil huske")
 (:dashboard-tip-3 . "Gentag dine flashcards regelmæssigt - spredt gentagelse hjælper dig med at huske langsigtet")
 (:dashboard-tip-4 . "Bedøm ærligt - det hjælper algoritmen med at planlægge dine gentagelser optimalt")

 ;; Account
 (:account-title . "Konto")
 (:account-subtitle . "Administrer profil, abonnement, påmindelser, eksporter og sletning af konto her.")
 (:account-status-title . "Status")
 (:account-profile-subtitle . "Hold dit viste navn og din e-mailadresse opdateret.")
 (:account-export-subtitle . "Download en kopi af dine gemte oversættelser, bunker og repetitionsdata.")
 (:account-deletion-title . "Sletning af konto")
 (:account-deletion-scheduled . "Din konto er planlagt til sletning den ~A.")
 (:account-deletion-cancel-hint . "Du kan annullere før denne dato for at beholde din konto.")
 (:account-deletion-cancel . "Annuller sletning")
 (:account-deletion-request . "Du kan anmode om sletning af kontoen når som helst. Sletning planlægges 14 dage efter bekræftelse. Hvis du fortryder, skal du kontakte support, før denne periode på 14 dage udløber.")
 (:account-deletion-confirm . "Planlæg sletning af konto om 14 dage fra nu?")
 (:account-deletion-schedule . "Planlæg sletning")
 (:account-reminders-title . "E-mailpåmindelser")
 (:account-reminders-subtitle . "Vælg om Hiisi må sende dig e-mails, når der venter noget at repetere.")
 (:account-reminders-opt-out . "Fravælg påmindelser om gentagelse og fortsættelse")
 (:account-reminders-save . "Gem indstillinger")

 ;; Subscription
 (:subscribe-title . "Enkle priser")
 (:subscribe-choose-plan . "Vælg din plan")
 (:subscribe-start-today . "Begynd at lære i dag med en 14-dages gratis prøveperiode")
 (:subscribe-monthly . "Månedlig")
 (:subscribe-annual . "Årlig")
 (:subscribe-founder-member . "Stiftende medlem")
 (:subscribe-monthly-price . "€10")
 (:subscribe-annual-price . "€100")
 (:subscribe-founder-price . "€79")
 (:subscribe-founder-monthly-equivalent . "€6,58/måned, faktureres årligt")
 (:subscribe-founder-savings . "Spar €41/år sammenlignet med månedlig betaling")
 (:subscribe-monthly-billing-equivalent . "€10/måned, faktureres månedligt")
 (:subscribe-monthly-billing-note . "Fleksibel månedlig betaling")
 (:subscribe-per-month . "/måned")
 (:subscribe-per-year . "/år")
 (:subscribe-monthly-desc . "600 oversættelser om måneden. Ubegrænsede flashkort, kortbunker og repetitioner.")
 (:subscribe-unlimited-flashcards . "Ubegrænsede flashcards")
 (:subscribe-grammar-explanations . "Grammatikforklaringer")
 (:subscribe-spaced-repetition . "Spredt gentagelse")
 (:subscribe-annual-desc . "Alt fra månedsplanen. To måneder gratis.")
 (:subscribe-founder-lock . "Prisen er låst, så længe dit abonnement forbliver aktivt.")
 (:subscribe-founder-badge . "Begrænset tilbud")
 (:subscribe-founder-limit . "Begrænset til de første 100 medlemmer")
 (:subscribe-manage . "Administrer abonnement")
 (:subscribe-activated . "Abonnement aktiveret!")
 (:subscribe-thank-you . "Dit abonnement er aktivt. Her kan du administrere betaling og købe flere oversættelser.")
 (:subscribe-start-learning . "Begynd at lære")
 (:subscribe-management . "Abonnementsstyring")
 (:subscribe-active . "Aktivt abonnement")
 (:subscribe-preapproved-access . "Forhåndsgodkendt adgang")
 (:subscribe-status . "Status:")
 (:subscribe-status-active . "Aktiv")
 (:subscribe-status-preapproved . "Forhåndsgodkendt")
 (:subscribe-preapproved-detail . "Denne konto bruger forhåndsgodkendt adgang administreret af Hiisi.")
 (:subscribe-days-remaining . "Dage tilbage:")
 (:subscribe-renews-on . "Fornyes den:")
 (:subscribe-no-subscription . "Intet aktivt abonnement")
 (:subscribe-access-features . "Vælg et abonnement for fuld adgang og betaling samlet ét sted.")
 (:subscribe-view-plans . "Se planer")
 (:subscribe-faq-title . "Ofte stillede spørgsmål")
 (:subscribe-faq-trial-q . "Hvad sker der efter den gratis prøveperiode?")
 (:subscribe-faq-trial-a . "Din 14-dages prøveperiode kræver ikke betalingskort. Når den slutter, skal du vælge en betalt plan for at beholde fuld adgang.")
 (:subscribe-faq-cancel-q . "Kan jeg annullere når som helst?")
 (:subscribe-faq-cancel-a . "Ja! Du kan annullere dit abonnement når som helst. Du beholder adgangen indtil udgangen af din faktureringsperiode.")
 (:subscribe-faq-payment-q . "Hvilke betalingsmetoder accepterer I?")
 (:subscribe-faq-payment-a . "Vi accepterer alle større kredit- og debetkort gennem vores betalingspartner Polar.sh.")
 (:subscribe-copyright . "Lambda Symbolics OÜ © 2026.")
(:subscribe-checkout-unavailable . "Checkout er midlertidigt utilgængelig. Prøv igen.")
(:subscribe-portal-unavailable . "Abonnementsstyring er midlertidigt utilgængelig. Prøv igen.")
(:subscribe-founder-sold-out . "Tilbuddet til stiftende medlemmer er udsolgt")
(:subscribe-founder-unavailable . "Tilbuddet til stiftende medlemmer er ikke tilgængeligt lige nu.")
(:subscribe-checkout-cta . "Abonnér")

 ;; Errors and status
 (:error-generic . "Noget gik galt")
(:error-invalid-request . "Ugyldige forespørgselsdata.")
(:error-not-found . "Den ønskede ressource blev ikke fundet.")
(:error-forbidden . "Du har ikke adgang til dette.")
(:error-rate-limited . "Vent et øjeblik og prøv igen.")
 (:error-text-too-long . "Teksten er for lang. Maksimal oversættelseslængde er 120 tegn.")
 (:error-input-too-long . "Input for langt")
 (:error-unknown-source-lang . "Det valgte kildesprog understøttes ikke.")
 (:error-unknown-target-lang . "Det valgte målsprog understøttes ikke.")
 (:error-unknown-language . "Ukendt sprog")
 (:error-translation-unavailable . "Oversættelsestjenesten er midlertidigt utilgængelig. Prøv igen om et øjeblik.")
 (:error-translation-failed . "Oversættelse mislykkedes")
 (:error-translation-retry . "Kunne ikke generere en oversættelse efter flere forsøg. Prøv at omformulere din tekst.")
 (:error-quota-exceeded . "Oversættelsesgrænse nået")
 (:error-quota-exceeded-detail . "Du har brugt alle dine oversættelser for denne måned. Din kvote nulstilles automatisk hver måned.")
 (:quota-low-warning . "Kun ~A oversættelser tilbage. Overvej at købe flere.")
 (:top-up-button . "Køb flere oversættelser")
 (:top-up-price . "€5")
 (:top-up-amount . "300 oversættelser")
(:review-session-expired . "Din repetitionssession er udløbet. Start en ny session.")

 (:error-session-expired . "Din session er udløbet. Log ind igen.")
 (:error-session-invalid . "Din session er ikke længere gyldig. Log ind igen.")
 (:error-custom-flashcard-generation . "Vi kunne ikke generere forklaringen. Prøv igen.")
 ;; Institutions
 (:institutions-page-title . "Hiisi til skoler og universiteter")
 (:institutions-hero-title . "Sprogundervisningsværktøjer skabt til klasseværelset")
 (:institutions-hero-subtitle . "Giv dine studerende delbare kortbunker, grammatisk bevidst træning og stabile repetitionsrutiner, der passer til virkelig undervisning.")
 (:institutions-section-title . "Hvorfor institutioner bruger Hiisi")
 (:institutions-section-body . "Hiisi hjælper undervisere med at gøre undervisningsmateriale til styret arbejde, som studerende faktisk kan følge med i. Opret kortbunker til et kursus, del dem med et link, og støt arbejdet med ordforråd og grammatik uden ekstra administrativ belastning.")
 (:institutions-benefit-1 . "Delbare kortbunker og egne opgaver, der passer til jeres undervisningsplan.")
 (:institutions-benefit-2 . "Studerendes likes og dislikes hjælper de stærkeste oversættelser frem for almindelige formuleringer i undervisningen.")
 (:institutions-benefit-3 . "Grammatiske gennemgange og fordelt repetition støtter mere end at lære isolerede ordlister udenad.")
 (:institutions-benefit-4 . "Lærernær støtte fra en person, der lytter omhyggeligt og tager klasseværelsets behov alvorligt.")
 (:institutions-request-title . "Lad os tage en snak")
 (:institutions-request-subtitle . "Fortæl os om jeres institution, jeres sprog og den form for undervisningsstøtte, I har brug for. Vi vender tilbage inden for en uge.")
 (:institutions-aside-title . "Hvad sker der nu")
 (:institutions-aside-body . "Vi gennemgår jeres behov og vender tilbage inden for en uge for at drøfte adgang og opsætning for jeres institution.")
 (:institutions-field-name . "Institutionsnavn")
 (:institutions-field-name-placeholder . "Dit universitet")
 (:institutions-field-contact-name . "Kontaktperson")
 (:institutions-field-contact-name-placeholder . "Dit navn")
 (:institutions-field-contact-email . "Kontakt-e-mail")
 (:institutions-field-contact-email-placeholder . "dig@universitet.dk")
 (:institutions-field-domains . "E-maildomæner")
 (:institutions-field-domains-placeholder . "universitet.dk, cs.universitet.dk")
 (:institutions-field-domains-help . "Kommasepareret liste over e-maildomæner for din institution")
 (:institutions-field-notes . "Yderligere oplysninger")
 (:institutions-field-notes-placeholder . "Estimeret antal studerende, foretrukken faktureringscyklus, særlige krav...")
 (:institutions-submit . "Send forespørgsel")
 (:institutions-success-title . "Tak - Hiisi til skoler og universiteter")
 (:institutions-success-heading . "Tak!")
 (:institutions-success-body . "Vi har modtaget jeres henvendelse. Vi gennemgår institutionens behov og vender tilbage inden for en uge.")
 (:institutions-success-back . "Tilbage til forsiden")

 ;; Footer
 (:footer-privacy . "Privatlivspolitik")
 (:footer-terms . "Servicevilkår")

 ;; Early software notice
 (:early-software-notice . "Hiisi er under tidlig udvikling. Fundet en fejl eller har du et forslag?")

 ;; Privatlivspolitik
 (:privacy-title . "Privatlivspolitik")
 (:privacy-updated . "Sidst opdateret: januar 2026")
 (:privacy-who-title . "Hvem vi er")
 (:privacy-who-body . "Hiisi drives af Lambda Symbolics OÜ, et selskab registreret i Estland. Som estisk virksomhed overholder vi EU's generelle databeskyttelsesforordning (GDPR).")
 (:privacy-collect-title . "Data vi indsamler")
 (:privacy-collect-intro . "Når du bruger Hiisi, indsamler vi følgende oplysninger:")
 (:privacy-collect-account-key . "Kontooplysninger: ")
 (:privacy-collect-account-val . "E-mailadresse, vist navn og en sikkert hashet adgangskode.")
 (:privacy-collect-learning-key . "Læringsdata: ")
 (:privacy-collect-learning-val . "Dine oversættelser, gemte flashkort og din repetitionshistorik.")
 (:privacy-collect-usage-key . "Brugsdata: ")
 (:privacy-collect-usage-val . "Grundlæggende serverlogs til sikkerhed og fejlfinding.")
 (:privacy-use-title . "Sådan bruger vi dine data")
 (:privacy-use-auth-key . "Autentificering: ")
 (:privacy-use-auth-val . "Til at bekræfte din identitet og beskytte din konto.")
 (:privacy-use-service-key . "Levering af tjenesten: ")
 (:privacy-use-service-val . "Til at levere oversættelser og administrere din flashkortsamling.")
 (:privacy-use-ai-key . "AI-oversættelser: ")
 (:privacy-use-ai-val . "Dine oversættelsesanmodninger sendes til OpenRouter for at generere svar. OpenRouter kan videresende anmodninger til den konfigurerede modeludbyder. Se OpenRouters privatlivspolitik for, hvordan disse data behandles.")
 (:privacy-third-title . "Tredjepartstjenester")
 (:privacy-third-intro . "Vi bruger følgende tredjepartstjenester:")
 (:privacy-third-openrouter-key . "OpenRouter: ")
 (:privacy-third-openrouter-val . "Til automatiske oversættelsesanmodninger.")
 (:privacy-third-clankermails-key . "ClankerMails: ")
 (:privacy-third-clankermails-val . "Til afsendelse af aktiveringsmails og transaktionsmails.")
 (:privacy-third-polar-key . "Polar.sh: ")
 (:privacy-third-polar-val . "Til behandling af abonnementsbetalinger.")
 (:privacy-cookies-title . "Cookies")
 (:privacy-cookies-intro . "Vi bruger kun nødvendige cookies:")
 (:privacy-cookies-auth-key . "Autentificeringstoken: ")
 (:privacy-cookies-auth-val . "En sikker HTTP-only cookie, som holder dig logget ind.")
 (:privacy-cookies-lang-key . "Sprogpræference: ")
 (:privacy-cookies-lang-val . "Til at huske dit foretrukne sprog i brugerfladen.")
 (:privacy-retention-title . "Opbevaring af data")
 (:privacy-retention-body . "Dine data gemmes, så længe du har en konto. Når du anmoder om sletning, planlægges din konto til sletning om 14 dage.")
 (:privacy-rights-title . "Dine rettigheder (GDPR)")
 (:privacy-rights-intro . "Under GDPR har du ret til at:")
 (:privacy-rights-access . "Få adgang til dine personoplysninger")
 (:privacy-rights-export . "Eksportere dine data (tilgængeligt på /app/api/export)")
 (:privacy-rights-correct . "Anmode om rettelse af unøjagtige data")
 (:privacy-rights-delete . "Anmode om sletning af din konto og dine data")
 (:privacy-rights-object . "Gøre indsigelse mod behandling af dine data")
 (:privacy-rights-contact . "For at udøve disse rettigheder, kontakt os på")
 (:privacy-contact-title . "Kontakt")
 (:privacy-contact-intro . "Ved spørgsmål om privatliv:")
 (:privacy-contact-email-label . "E-mail: ")
 (:privacy-address-1 . "Lambda Symbolics OÜ")
 (:privacy-address-2 . "Harju maakond, Tallinn, Kesklinna linnaosa, Tornimäe tn 5, 10145")

 ;; Brugsvilkår
 (:terms-title . "Brugsvilkår")
 (:terms-updated . "Sidst opdateret: januar 2026")
 (:terms-1-title . "1. Tjenestebeskrivelse")
 (:terms-1-body . "Hiisi er en sproglæringsapp, der tilbyder automatiske oversættelser med grammatiske forklaringer og flashkort med distribueret repetition. Tjenesten drives af Lambda Symbolics OÜ.")
 (:terms-2-title . "2. Oprettelse af konto")
 (:terms-2-body . "For at bruge Hiisi skal du oprette en konto med en gyldig e-mailadresse. Du er ansvarlig for sikkerheden af dine loginoplysninger.")
 (:terms-3-title . "3. Abonnement og betaling")
 (:terms-3-body . "Hiisi tilbyder betalte abonnementer (månedligt og årligt). Abonnementer behandles gennem Polar.sh.")
 (:terms-3-list-1 . "Abonnementer fornyes automatisk, medmindre de opsiges før fornyelsesdatoen.")
 (:terms-3-list-2 . "Refundering sker i overensstemmelse med gældende forbrugerbeskyttelseslovgivning.")
 (:terms-3-list-3 . "Manglende betaling medfører tab af adgang til premiumfunktioner.")
 (:terms-4-title . "4. Tilladt brug")
 (:terms-4-intro . "Du accepterer, at du ikke må:")
 (:terms-4-list-1 . "Bruge tjenesten til ulovlige formål")
 (:terms-4-list-2 . "Forsøge at omgå brugsgrænser eller sikkerhedsforanstaltninger")
 (:terms-4-list-3 . "Dele dine kontooplysninger med andre")
 (:terms-4-list-4 . "Bruge automatiserede værktøjer på en måde, der forringer ydelsen for andre")
 (:terms-5-title . "5. Indhold og immaterielle rettigheder")
 (:terms-5-body-1 . "Oversættelser genereret af Hiisi er skabt automatisk og er muligvis ikke unikke. Du må bruge dine oversættelser og flashkort til personlige formål, men du har ikke eksklusive ophavsrettigheder til automatisk genereret indhold.")
 (:terms-5-body-2 . "Hiisi-applikationen, branding og originalt indhold forbliver Lambda Symbolics OÜ's ejendom.")
 (:terms-6-title . "6. Tjenestens tilgængelighed")
 (:terms-6-intro . "Hiisi leveres \"som den er\". Vi garanterer ikke:")
 (:terms-6-list-1 . "Uafbrudt eller fejlfri tjeneste")
 (:terms-6-list-2 . "Nøjagtigheden af automatisk genererede oversættelser")
 (:terms-6-list-3 . "Tilgængeligheden af bestemte funktioner")
 (:terms-6-body . "Vi kan til enhver tid ændre eller afvikle funktioner.")
 (:terms-7-title . "7. Ansvarsbegrænsning")
 (:terms-7-body-1 . "I det omfang loven tillader det, er Lambda Symbolics OÜ ikke ansvarlig for indirekte, tilfældige, særlige eller afledte skader, der opstår ved brug af Hiisi.")
 (:terms-7-body-2 . "Vores samlede ansvar overstiger ikke det beløb, du har betalt for tjenesten i de 12 måneder før kravet.")
 (:terms-8-title . "8. Lukning af konto")
 (:terms-8-body-1 . "Vi kan suspendere eller afslutte din konto, hvis du overtræder disse vilkår. Du kan til enhver tid anmode om sletning af konto i applikationen.")
 (:terms-8-body-2 . "Ved anmodning om sletning planlægges din konto til sletning om 14 dage.")
 (:terms-9-title . "9. Ændringer af vilkår")
 (:terms-9-body . "Vi kan opdatere disse vilkår fra tid til anden. Fortsat brug af Hiisi efter ændringer udgør accept af de nye vilkår.")
 (:terms-10-title . "10. Lovvalg")
 (:terms-10-body . "Disse vilkår er underlagt estisk lov. Eventuelle tvister afgøres ved domstolene i Estland.")
 (:terms-contact-title . "Kontakt")
 (:terms-contact-intro . "Ved spørgsmål om disse vilkår:")
 (:terms-contact-email-label . "E-mail: ")
 (:terms-address-1 . "Lambda Symbolics OÜ")
 (:terms-address-2 . "Harju maakond, Tallinn, Kesklinna linnaosa, Tornimäe tn 5, 10145")

 ;; Decks
 (:decks-title . "Kortbunker")
 (:decks-subtitle . "Opret brugerdefinerede kortbunker og del dem med andre.")
 (:decks-create-title . "Opret kortbunke")
 (:decks-name-placeholder . "Kortbunkens navn")
 (:decks-desc-placeholder . "Beskrivelse")
 (:decks-create-btn . "Opret kortbunke")
 (:decks-edit-title . "Redigér kortbunke")
 (:decks-edit-btn . "Redigér kortbunke")
 (:decks-actions-title . "Handlinger for kortbunke")
 (:decks-card-actions-title . "Korthandlinger")
 (:decks-update-btn . "Gem ændringer")
 (:decks-default-badge . "Automatisk")
 (:decks-default-description . "Denne kortbunke administreres automatisk for dette sprogpar.")
 (:decks-default-readonly . "Automatiske kortbunker har faste navne og beskrivelser.")
 (:decks-delete-btn . "Slet kortbunke")
 (:decks-delete-confirm . "Er du sikker på, at du vil slette denne kortbunke?")
 (:decks-error-name-required . "Navn på kortbunken er påkrævet.")
 (:decks-error-name-too-long . "Navnet på kortbunken må højst være ~A tegn.")
 (:decks-error-desc-too-long . "Beskrivelsen af kortbunken må højst være ~A tegn.")
 (:decks-error-default-readonly . "Automatiske kortbunker kan ikke redigeres.")
 (:decks-error-default-delete-forbidden . "Automatiske kortbunker kan ikke slettes.")
 (:decks-your-title . "Dine kortbunker")
 (:decks-col-updated . "Opdateret")
 (:decks-no-decks . "Ingen kortbunker endnu.")
 (:decks-open-btn . "Åbn")
 (:decks-view-deck-btn . "Vis kortbunke")
 (:decks-start-review . "Start gennemgang")
 (:decks-no-desc . "Ingen beskrivelse.")
 (:decks-share-title . "Delingslink")
 (:decks-share-info . "Alle med dette link kan importere kortbunken:")
 (:decks-share-copy . "Kopiér link")
 (:decks-share-copied . "Kopieret")
 (:decks-add-from-flashcards-title . "Tilføj flashkort")
 (:decks-add-from-flashcards-info . "Vælg et kort for at tilføje dets oversættelse til denne kortbunke.")
 (:decks-create-new-flashcard . "Opret nyt flashkort")
 (:decks-open-flashcards . "Tilføj eksisterende flashkort")
 (:decks-filter-from . "Kildesprog")
 (:decks-filter-to . "Målsprog")
 (:decks-filter-any . "Alle sprog")
 (:decks-filter-include-assigned . "Inkludér kort, der allerede er i en kortbunke")
 (:decks-flashcards-add . "Tilføj")
 (:decks-flashcards-added . "Tilføjet")
 (:decks-flashcards-in-deck . "I en anden kortbunke")
 (:decks-flashcards-empty . "Ingen kort matcher disse filtre.")
 (:decks-items-title . "Kortbunkens indhold")
 (:decks-col-original . "Original")
 (:decks-col-translated . "Oversættelse")
 (:decks-col-lang . "Målsprog")
 (:decks-no-items . "Ingen elementer endnu.")
 (:decks-share-page-title . "Del kortbunke")
 (:decks-share-preview . "Forhåndsvis og importer denne kortbunke.")
 (:decks-import-title . "Importer")
 (:decks-import-btn . "Importer kortbunke")
 (:starter-decks-title . "Bibliotek")
 (:starter-decks-subtitle . "Importér færdige kortbunker fra Hiisi og fællesskabet.")
 (:starter-decks-marketplace-btn . "Bibliotek")
 (:starter-decks-explanation-language . "Forklaringssprog")
 (:starter-decks-search-label . "Søg")
 (:starter-decks-source-label . "Kilde")
 (:starter-decks-source-all . "Alle kortbunker")
 (:starter-decks-change-language . "Skift")
 (:starter-decks-filters-button . "Filtre")
 (:starter-decks-search-placeholder . "Søg i biblioteket")
 (:starter-decks-apply-filters . "Anvend filtre")
 (:starter-decks-select-triplet-hint . "Vælg kilde- og målsprog for at gennemse matchende kortbunker.")
 (:starter-decks-official-badge . "Officiel")
 (:starter-decks-official-by-hiisi . "Officiel fra Hiisi")
 (:starter-decks-community-badge . "Fællesskab")
 (:starter-decks-by-hiisi . "Fra Hiisi")
 (:starter-decks-preview-btn . "Forhåndsvis")
 (:starter-decks-card-count . "~A kort")
 (:starter-decks-no-results . "Ingen kortbunker matcher disse filtre.")
 (:starter-decks-source-cards-title . "Kort i dette kortsæt")
 (:starter-decks-more-cards-included . "+~A flere kort inkluderet.")
 (:starter-decks-sample-title . "Eksempelkort")
 (:starter-decks-generating . "Forbereder din kortbunke: ~A")
 (:starter-decks-generating-detail . "Vi importerer den, så snart den er klar. Du kan fortsætte med at gennemse Biblioteket eller komme tilbage om lidt.")
 (:starter-decks-generation-failed . "Genereringen mislykkedes")
 (:starter-decks-generation-failed-detail . "Det seneste forsøg på at generere kortbunken mislykkedes. Prøv at importere kortbunken igen.")
 (:starter-decks-login-detail . "Log ind for at importere denne kortbunke til din samling.")
 (:starter-decks-subscribe-btn . "Se planer")
 (:starter-decks-subscribe-detail . "Kortbunker i biblioteket er tilgængelige med et aktivt abonnement eller en prøveperiode.")
 (:library-submit-title . "Indsend til biblioteket")
 (:library-submit-intro . "Indsend denne kortbunke til biblioteket til administrativ gennemgang før udgivelse.")
 (:library-submit-btn . "Indsend kortbunke")
 (:library-submit-approved . "Godkendt til biblioteket")
 (:library-submit-approved-detail . "Denne kortbunke er udgivet i biblioteket.")
 (:library-submit-pending . "Afventer gennemgang")
 (:library-submit-pending-detail . "Denne kortbunke er indsendt og afventer administrativ gennemgang.")
 (:library-submit-rejected . "Kræver ændringer før udgivelse")
 (:library-submit-rejected-detail . "Denne indsendelse blev afvist. Opdater kortbunken og indsend den igen.")
 (:library-error-empty . "Tilføj mindst ét kort, før du indsender denne kortbunke til biblioteket.")
 (:library-error-missing-triplet . "Hvert kort i en biblioteksindsendelse skal have en fuld sprogtrio.")
 (:library-error-mixed-triplet . "Alle kort i en biblioteksindsendelse skal dele den samme sprogtrio.")
 (:starter-deck-topic-greetings-title . "Hilsner og præsentationer")
 (:starter-deck-topic-greetings-description . "Hilsner, navne, høflige grundudtryk og fraser til det første møde.")
 (:starter-deck-topic-travel-title . "Grundlæggende rejser")
 (:starter-deck-topic-travel-description . "Stationer, billetter, priser, hjælp og at finde rundt.")
 (:starter-deck-topic-numbers-title . "Tal og priser")
 (:starter-deck-topic-numbers-description . "Optælling, totaler, priser, etager og daglige mængder.")
 (:starter-deck-topic-time-title . "Tid og datoer")
 (:starter-deck-topic-time-description . "Dage, måneder, aftaler, klokkeslæt og relative datoer.")
 (:starter-deck-topic-food-title . "Restaurant og mad")
 (:starter-deck-topic-food-description . "Bestilling, kosthensyn, drikkevarer, regningen og daglige måltider ude.")
 (:starter-deck-topic-emergency-title . "Nødsituationer og sundhed")
 (:starter-deck-topic-emergency-description . "Læger, apoteker, symptomer, kropsdele og akut hjælp.")
 (:starter-deck-topic-directions-title . "Vejvisning og transport")
 (:starter-deck-topic-directions-description . "Sving, stoppesteder, billetter, perroner og at komme rundt i byen.")
 (:starter-deck-topic-school-title . "Skole og uddannelse")
 (:starter-deck-topic-school-description . "Timer, lektier, prøver, skoleudstyr og hverdagslivet på skolen.")
 (:starter-deck-topic-university-title . "Universitet og studier")
 (:starter-deck-topic-university-description . "Forelæsninger, seminarer, studieretninger, opgaver og hverdagslivet på campus.")

 ;; Flashcards management page
 (:flashcards-title . "Mine kort")
 (:flashcards-subtitle . "Alle dine gemte kort på ét sted. Søg, organiser og administrer.")
 (:flashcards-search-placeholder . "Søg i kort...")
 (:flashcards-filter-button . "Filtre")
 (:flashcards-filter-title . "Filtrer kort")
 (:flashcards-filter-recollection . "Hvor godt du kan dem")
 (:flashcards-filter-any-recollection . "Ethvert niveau")
 (:flashcards-hide-perfected . "Skjul fuldt indlærte kort")
 (:flashcards-col-original . "Original")
 (:flashcards-col-translated . "Oversættelse")
 (:flashcards-no-cards . "Ingen kort endnu. Begynd at oversætte for at oprette nogle!")
 (:flashcards-no-filtered-cards . "Ingen kort matcher disse filtre endnu. Begynd at oversætte for at oprette nogle!")
 (:flashcards-image-label . "Billede")
 (:flashcards-image-upload . "Upload billede")
 (:flashcards-image-replace . "Erstat billede")
 (:flashcards-image-remove . "Fjern billede")
 (:flashcards-pagination-label . "Flashcard-sider")
 (:flashcards-pagination-status . "Side ~A af ~A")
 (:flashcards-pagination-previous . "Forrige")
 (:flashcards-pagination-next . "Næste")

 ;; Landing page (redesign)
 (:landing-hero-headline-v1 . "Oversæt nemt sætninger, og læs grammatikken på dit eget sprog.")
 (:landing-hero-headline-v2 . "Hiisi sørger for, at du ikke glemmer de sætninger, du oversætter.")
 (:landing-hero-headline-v3 . "Gør de sætninger, du oversætter, til ordforråd, du kan bruge.")
 (:landing-hero-subheadline . "Bogmærk en hvilken som helst sætning, så giver Hiisi dig oversættelsen, grammatikken, udtalen og et flashkort, der vender tilbage til repetition.")
 (:trial-cardless-note . "14 dage gratis. Intet kort kræves.")

 ;; Trial status (in-app)
 (:trial-status . "Gratis prøveperiode")
 (:error-trial-quota-exceeded . "Grænse for prøveoversættelser nået")
 (:error-trial-quota-detail . "Du har brugt alle 200 prøveoversættelser. Abonner for at fortsætte med at lære.")

 ;; Custom flashcards
 (:custom-flashcard-create-title . "Opret flashkort")
 (:custom-flashcard-edit-title . "Rediger flashkort")
 (:custom-flashcard-original . "Originaltekst")
 (:custom-flashcard-translated . "Oversættelse")
 (:custom-flashcard-lang-from . "Kildesprog")
 (:custom-flashcard-lang-to . "Målsprog")
 (:custom-flashcard-note . "Pædagogisk note")
 (:custom-flashcard-forms . "Grammatisk analyse")
 (:custom-flashcard-form-term . "Begreb")
 (:custom-flashcard-form-explanation . "Forklaring")
 (:custom-flashcard-add-form . "Tilføj grammatisk begreb")
 (:custom-flashcard-remove-form . "Fjern")
 (:custom-flashcard-ai-fill . "Udfyld med AI")
 (:custom-flashcard-create-btn . "Opret flashkort")
 (:custom-flashcard-update-btn . "Gem ændringer")

  ;; Newsletter
  (:newsletter-email-label . "E-mailadresse")
  (:newsletter-developer-label . "Jeg er udvikler")
  (:newsletter-developer-hint . "modtag tekniske opdateringer")
  (:landing-newsletter-title . "Få Hiisi-opdateringer.")
  (:landing-newsletter-body . "Tilmeld dig nyhedsbrevet for produktopdateringer, nye sprog, startkortpakker og lejlighedsvise tilbud til stiftende medlemmer.")
  (:landing-newsletter-fine-print . "Ingen spam. Kun produktopdateringer.")
  (:landing-newsletter-button . "Tilmeld nyhedsbrev")
  (:newsletter-unsubscribe-page-title . "Afmeld Hiisi-nyhedsbrevet")
  (:newsletter-unsubscribe-title . "Afmeld")
  (:newsletter-unsubscribe-subtitle . "Indtast din e-mail for at stoppe med at modtage Hiisi-opdateringer.")
  (:newsletter-unsubscribe-button . "Afmeld")
  (:newsletter-feedback-email-required . "Indtast din e-mailadresse.")
  (:newsletter-feedback-email-invalid . "Indtast en gyldig e-mailadresse.")
  (:newsletter-feedback-already-signed-up . "Du er allerede tilmeldt. Vi holder dig opdateret!")
  (:newsletter-feedback-signed-up . "Du er på listen! Vi sender lejlighedsvise Hiisi-opdateringer.")
  (:newsletter-feedback-unsubscribed . "Hvis denne e-mail var tilmeldt, er den fjernet fra Hiisi-opdateringer.")
  (:newsletter-feedback-generic-error . "Noget gik galt. Prøv igen.")

  ;; Issue reporting
 (:issues-open-button . "Rapportér en fejl")
 (:issues-modal-title . "Rapportér et problem")
 (:issues-modal-subtitle . "Beskriv, hvad der gik galt. Vi vedhæfter automatisk den aktuelle side.")
 (:issues-title-label . "Kort titel")
 (:issues-title-placeholder . "Kort opsummering af problemet")
 (:issues-message-label . "Hvad skete der?")
 (:issues-message-placeholder . "Angiv trin til at genskabe, forventet adfærd og hvad der skete i stedet.")
 (:issues-submit . "Send rapport")
 (:issues-cancel . "Annullér")
 (:issues-success . "Din rapport blev sendt. Vi ser på den så hurtigt som muligt.")
 (:issues-error-required . "Beskriv problemet, før du sender.")
 (:issues-error-title-too-long . "Sagens titel er for lang. Hold den under 160 tegn.")
 (:issues-error-too-long . "Rapportteksten er for lang. Hold den under 4000 tegn.")
 (:issues-error-rate-limit . "For mange rapporter fra denne kilde. Vent og prøv igen senere.")
 (:issues-error-generic . "Problemrapporten kunne ikke sendes. Prøv igen.")

 ;; Landing page (Programmable Paper)
 (:landing-signal-languages . "Femten sprog")
 (:landing-signal-flashcards . "Kloge flashcards")
 (:landing-signal-pronunciation . "Udtale, du kan læse")
 (:landing-problem-title . "Sætningen, du oversatte i sidste uge. Kan du sige den nu?")
 (:landing-problem-body . "Det øjeblik gentager sig tit. Du ser en vending, sætter den ind i en oversætter, og betydningen giver mening med det samme, lige der i hånden. Der går en uge; ordlyden har forladt hukommelsen, og betydningen fulgte med. At lære én sætning kræver som regel fire forskellige værktøjer:")
 (:landing-tool-translator . "En oversætter til betydningen")
 (:landing-tool-grammar . "En grammatik til strukturen")
 (:landing-tool-pronunciation . "En udtaleguide til lyden")
 (:landing-tool-flashcards . "En flashcard-app til at huske det")
 (:landing-problem-outro . "At bruge alle fire tager tid, og den næste sætning er væk, før kortet er færdigt.")
 (:landing-bookmark-title . "Hvad der sker, når du gemmer en sætning")
 (:landing-bookmark-intro . "Ét tryk, og Hiisi gør sætningen til et struktureret læringsobjekt på få sekunder. Den bliver i dit bibliotek med alt, der hører til:")
 (:landing-bookmark-item-translation . "Den oprindelige sætning og en klar oversættelse")
 (:landing-bookmark-item-pronunciation . "Udtalen skrevet ud, som ordbøgerne gør det")
 (:landing-bookmark-item-grammar . "Grammatik forklaret på det sprog, du helst læser")
 (:landing-bookmark-item-colors . "Farvematchede ord viser, hvilken del der hører til hvilken")
 (:landing-bookmark-item-flashcard . "Et flashcard, der vender tilbage, når din hukommelse har brug for det")
 (:landing-bookmark-cta . "Gem din første sætning")
 (:landing-sources-title . "Én sætning er nok til at begynde")
 (:landing-sources-intro . "Alt, hvad du læser eller hører på et nyt sprog, virker med Hiisi:")
 (:landing-source-lyrics . "Teksten fra en sang, du bliver ved med at afspille")
 (:landing-source-articles . "Artikler på det sprog, du lærer")
 (:landing-source-messages . "Beskeder fra venner med sproget som modersmål")
 (:landing-source-films . "Replikker fra film eller podcasts, du gemmer")
 (:landing-source-page . "Siden, du læser lige nu")
 (:landing-features-title . "Bygget til selvlærte og studerende")
 (:landing-feature-grammar-title . "Grammatik på det sprog, du tænker på")
 (:landing-feature-grammar-body . "Læs fransk grammatik på dansk eller spansk grammatik på polsk. Din opmærksomhed bliver ved sætningen, du lærer.")
 (:landing-feature-colors-title . "Ord parret med farve")
 (:landing-feature-colors-body . "Et ord og dets oversættelse deler samme farve, så du ser hvert ords betydning med ét blik.")
 (:landing-feature-pronunciation-title . "Udtale, du kan læse")
 (:landing-feature-pronunciation-body . "Hver sætning kommer med en skreven udtaleguide, den samme slags som ordbøgerne bruger. Du ser, hvordan den lyder, før du siger den.")
 (:landing-feature-flashcards-title . "Flashcards, der planlægger sig selv")
 (:landing-feature-flashcards-body . "Hver gemt sætning bliver et kort. SM-2-algoritmen bag Anki afgør, hvornår det vender tilbage, så du repeterer netop det, du er ved at glemme.")
 (:landing-feature-decks-title . "Emnedecks til det, der venter")
 (:landing-feature-decks-body . "Skal du rejse næste måned? Begynder du i nyt arbejde? Importér et færdigt deck og repetér fra dag ét.")
 (:landing-feature-directions-title . "Femten sprog, alle retninger")
 (:landing-feature-directions-body . "Oversæt fra spansk til fransk eller fra engelsk til tysk. Hiisi klarer alle retninger i hele sættet.")
 (:landing-flow-title . "Sådan ser læring i Hiisi ud")
 (:landing-flow-body . "Åbn Hiisi. Dagens kort venter allerede, hvert af dem en sætning, du har gemt, med oversættelse og grammatik vedhæftet. Ser du en ny sætning, du vil beholde? Gem den, og i morgen ligger den i repetitionsbunken.")
 (:landing-who-title . "Hvem Hiisi er til")
 (:landing-who-intro . "Har du mistet en nyttig sætning før? Hiisi blev bygget til dig.")
 (:landing-who-beginners . "Begyndere, der bygger deres første vendinger på et nyt sprog")
 (:landing-who-intermediate . "Øvede, der læser godt, men snubler over grammatikken")
 (:landing-who-native . "Modersmålstalere, der genfinder sproget hjemmefra")
 (:landing-who-travellers . "Rejsende og partnere til modersmålstalere, der vil have sætninger, de kan bruge")
 (:landing-final-title . "Begynd med Hiisi i dag")
 (:landing-final-body . "Hiisi giver dig betydningen, grammatikken, udtalen og et flashcard, der kommer tilbage og finder dig. Fra da af er sætningen din.")
 (:landing-final-languages . "Femten sprog står klar, når du er.")
 (:modal-close . "Luk")
)
