;;; German translations
;;; This file must contain all keys from en.lisp

(
 ;; Language metadata (used for language picker)
 (:lang-name . "Deutsch")
 (:lang-flag . "🇩🇪")

 ;; Language modal (first-visit language selection)
 (:lang-modal-title . "Wähle deine Sprache")
 (:lang-modal-subtitle . "Wähle deine bevorzugte Sprache für die Benutzeroberfläche:")

 ;; Navigation
 (:nav-translate . "Übersetzen")
 (:nav-review . "Wiederholen")
 (:nav-flashcards . "Meine Karten")
 (:nav-dashboard . "Dashboard")
 (:nav-decks . "Stapel")
 (:nav-logout . "Abmelden")
 (:nav-home . "Startseite")
 (:nav-pricing . "Preise")
 (:nav-institutions . "Für Institutionen")
 (:nav-export-data . "Daten exportieren")
 (:nav-open-navigation . "Navigation öffnen")
 (:theme-light . "Hell")
 (:theme-dark . "Dunkel")

 ;; App title and branding
 (:app-title . "Hiisi - Sprachenlernen")

 ;; Landing page
 (:landing-meta-title . "Hiisi: Sprachlern-App mit Grammatik und Karteikarten")
 (:landing-meta-description . "Hiisi ist eine Sprachlern-App. Jeder Satz, den Sie übersetzen, wird zu einer Karteikarte mit integrierter Grammatik, geplant mit SM-2, dem Anki-Algorithmus. 15 Sprachen.")
 (:landing-learn-more . "Mehr erfahren")
 (:landing-how-it-works . "So funktioniert's")
 (:landing-start-trial . "Mit Hiisi loslegen")
 (:landing-best-value . "Bestes Angebot")

 ;; Auth pages
 (:auth-register . "Registrieren")
 (:auth-login . "Anmelden")
 (:auth-email . "E-Mail")
 (:auth-password . "Passwort")
 (:auth-password-again . "Passwort bestätigen")
 (:auth-display-name . "Anzeigename")
 (:auth-register-title . "Bei Hiisi registrieren")
 (:auth-register-subtitle . "Neues Konto erstellen")
 (:auth-login-title . "Bei Hiisi anmelden")
 (:auth-login-subtitle . "Anmeldedaten eingeben")
 (:auth-login-invalid-credentials . "Ungültige E-Mail oder ungültiges Passwort.")
 (:auth-login-rate-limited . "Zu viele Anmeldeversuche. Bitte warte ein paar Minuten und versuche es erneut.")
(:auth-register-rate-limited . "Zu viele Registrierungsversuche. Bitte warte ein paar Minuten und versuche es erneut.")
(:auth-email-invalid . "Bitte gib eine gültige E-Mail-Adresse ein.")
(:auth-password-too-short . "Das Passwort muss mindestens 8 Zeichen lang sein.")
(:auth-passwords-mismatch . "Die Passwörter stimmen nicht überein.")
(:auth-display-name-invalid . "Der Anzeigename muss zwischen 1 und 100 Zeichen lang sein.")
(:auth-register-email-exists . "Mit dieser E-Mail-Adresse existiert bereits ein Konto.")
(:auth-register-unavailable . "Die Registrierung ist vorübergehend nicht verfügbar. Bitte versuche es später erneut.")
(:auth-register-plan-required . "Wähle einen Plan, bevor du ein Konto erstellst.")
(:auth-preapproved-email-unrecognized . "Verwende die E-Mail-Adresse aus deiner Einladung oder wähle einen Plan, bevor du ein Konto erstellst.")
(:auth-institution-register . "Kommst du von einer Institution?")
(:auth-institution-stage-title . "Institutioneller Zugang")
(:auth-institution-stage-subtitle . "Nutze deine Schul- oder Universitäts-E-Mail. Berechtigte Konten werden nach der E-Mail-Bestätigung über die Institution freigeschaltet.")
(:auth-institution-title . "Über deine Institution registrieren")
(:auth-institution-subtitle . "Nutze deine Schul- oder Universitäts-E-Mail. Wenn deine Institution bereits in Hiisi eingerichtet ist, wird dein Konto nach der E-Mail-Bestätigung über sie freigeschaltet; die individuelle 14-tägige Testphase gilt für die Registrierung mit persönlichem Plan.")
(:auth-institution-benefit-email . "Nutze deine Schul- oder Universitäts-E-Mail-Adresse.")
(:auth-institution-benefit-access . "Berechtigte Konten erhalten institutionellen Zugang nach der E-Mail-Bestätigung.")
(:auth-institution-benefit-fallback . "Wenn die Domain nicht erkannt wird, wähle einen persönlichen Plan oder bitte deine Institution, Hiisi zu kontaktieren.")
(:auth-see-included . "Anzeigen, was enthalten ist")
(:auth-institution-check-access . "Zugang prüfen")
(:auth-institution-email-eligible-title . "Institutioneller Zugang bestätigt")
(:auth-institution-email-eligible-detail . "Fahre mit dieser E-Mail fort, um dein Konto zu erstellen. Der Zugang wird nach der E-Mail-Bestätigung freigeschaltet.")
(:auth-institution-change-email . "Andere E-Mail verwenden")
(:auth-institution-outcome-note . "Wenn deine Schule oder Universität Zugang zu Hiisi bereitstellt, wird dein Konto nach der E-Mail-Bestätigung freigeschaltet. Wenn die Domain nicht berechtigt ist, wähle einen persönlichen Plan, um die 14-tägige Testphase zu starten.")
(:auth-institution-personal-plan-link . "Persönliche Pläne ansehen")
(:auth-institution-domain-unrecognized . "Diese institutionelle E-Mail-Domain kennen wir noch nicht. Wähle einen persönlichen Plan, um die 14-tägige Testphase zu starten, oder bitte deine Institution, Hiisi zu kontaktieren.")
(:subscribe-institution-callout-title . "Nutzt du Hiisi über eine Schule oder Universität?")
(:subscribe-institution-callout-body . "Registriere dich mit deiner institutionellen E-Mail. Hiisi schaltet den Zugang automatisch frei, wenn deine Institution bereits eingerichtet ist.")
(:auth-activation-email-send-failed . "Die Aktivierungs-E-Mail konnte nicht gesendet werden. Bitte versuche es erneut.")
 (:auth-forgot-password . "Passwort vergessen?")
 (:auth-no-account . "Noch kein Konto?")
 (:auth-have-account . "Bereits ein Konto?")
 (:auth-google . "Google")
 (:auth-google-login-failed . "Die Anmeldung mit Google ist fehlgeschlagen. Bitte versuchen Sie es erneut.")
 (:auth-account-created . "Konto erstellt!")
 (:auth-check-email . "Prüfe deine E-Mails für den Aktivierungslink.")
 (:auth-redirect-login . "Weiterleitung zur Anmeldung in")
 (:auth-seconds . "Sekunden...")
 (:auth-go-now . "Jetzt weiter")
 (:auth-not-activated . "Konto nicht aktiviert")
 (:auth-activate-title . "Aktiviere dein Konto!")
 (:auth-activated . "Konto aktiviert!")
 (:auth-activated-message . "Dein Konto wurde aktiviert. Du kannst Hiisi jetzt nutzen.")
 (:auth-redirecting . "Weiterleitung in")
 (:auth-go-to-app . "Zur App")
 (:onboarding-title . "Wie Hiisi funktioniert")
 (:onboarding-subtitle . "Übersetze echten Text, sieh dir die Grammatik an, speichere nützliche Einträge und wiederhole sie später.")
 (:onboarding-translate-detail . "Beginne mit echtem Text. Hiisi zeigt dir die Übersetzung, die zugeordneten Formen und die nächsten Lernschritte an einem Ort.")
 (:onboarding-grammar-detail . "Öffne die grammatische Aufschlüsselung, um zu sehen, welche Formen sich im Satz entsprechen und welche Funktion jeder Teil hat.")
 (:onboarding-review-detail . "Speichere nützliche Übersetzungen und wiederhole sie später mit verteiltem Wiederholen, damit sie im Langzeitgedächtnis bleiben.")
 (:onboarding-decks-detail . "Ordne nützliche Einträge in Stapel ein, teile sie mit anderen und halte zusammengehöriges Material beieinander.")
 (:onboarding-back . "Zurück")
 (:onboarding-next . "Weiter")
 (:onboarding-skip . "Anleitung überspringen")
 (:auth-resend-title . "Aktivierungs-E-Mail erneut senden")
 (:auth-resend-subtitle . "Gib deine E-Mail-Adresse ein, um einen neuen Aktivierungslink zu erhalten.")
 (:auth-resend-button . "Aktivierungs-E-Mail erneut senden")
 (:auth-resend-success . "Aktivierungs-E-Mail gesendet!")
 (:auth-resend-success-detail . "Überprüfe deinen Posteingang für den neuen Aktivierungslink.")
 (:auth-resend-rate-limited . "Bitte warte einige Minuten, bevor du eine weitere Aktivierungs-E-Mail anforderst.")
 (:auth-resend-cooldown . "Du kannst in ~a Sekunden eine weitere E-Mail anfordern.")
 (:auth-back-to-login . "Zurück zum Login")
 (:auth-forgot-password-title . "Passwort vergessen")
 (:auth-forgot-password-subtitle . "Gib deine E-Mail-Adresse ein und wir senden dir einen Link zum Zurücksetzen deines Passworts.")
 (:auth-send-reset-link . "Link zum Zurücksetzen senden")
 (:auth-reset-email-sent . "Link gesendet!")
 (:auth-reset-email-sent-detail . "Wenn ein Konto mit dieser E-Mail existiert, erhältst du in Kürze einen Link zum Zurücksetzen des Passworts.")
 (:auth-reset-rate-limited . "Bitte warte einige Minuten, bevor du eine weitere Passwort-Zurücksetzung anforderst.")
 (:auth-reset-invalid-token . "Dieser Link zum Zurücksetzen des Passworts ist ungültig oder abgelaufen.")
 (:auth-reset-password-title . "Passwort zurücksetzen")
 (:auth-reset-password-subtitle . "Gib unten dein neues Passwort ein.")
 (:auth-new-password . "Neues Passwort")
 (:auth-confirm-new-password . "Neues Passwort bestätigen")
 (:auth-reset-password . "Passwort zurücksetzen")
 (:auth-password-changed . "Passwort geändert!")
 (:auth-password-changed-detail . "Dein Passwort wurde erfolgreich geändert. Du kannst dich jetzt mit deinem neuen Passwort anmelden.")
 (:auth-change-password-title . "Passwort ändern")
 (:auth-change-password-subtitle . "Aktualisiere dein Kontopasswort.")
 (:auth-current-password . "Aktuelles Passwort")
 (:auth-change-password . "Passwort ändern")
 (:auth-back-to-app . "Zurück zur App")
 (:auth-password-updated . "Passwort aktualisiert!")
 (:auth-password-updated-detail . "Dein Passwort wurde erfolgreich aktualisiert.")
(:auth-current-password-invalid . "Das aktuelle Passwort ist falsch.")
(:auth-new-password-same . "Das neue Passwort muss sich vom aktuellen Passwort unterscheiden.")

 ;; Email copy
 (:email-common-hi . "Hallo")
 (:email-common-tagline . "Hiisi - Lerne durch Übersetzen")
 (:email-activation-subject . "Aktiviere dein Hiisi-Konto")
 (:email-activation-title . "Willkommen bei Hiisi")
 (:email-activation-body . "Danke für deine Registrierung. Bitte aktiviere dein Konto, indem du auf den folgenden Link klickst:")
 (:email-activation-button . "Konto aktivieren")
 (:email-activation-copy-link . "Oder kopiere diesen Link")
 (:email-activation-expiry . "Dieser Link läuft in 24 Stunden ab.")
 (:email-reset-subject . "Setze dein Hiisi-Passwort zurück")
 (:email-reset-title . "Anfrage zum Zurücksetzen des Passworts")
 (:email-reset-body . "Wir haben eine Anfrage zum Zurücksetzen deines Passworts erhalten. Klicke auf den folgenden Link, um ein neues Passwort festzulegen:")
 (:email-reset-button . "Passwort zurücksetzen")
 (:email-reset-expiry . "Dieser Link läuft in 1 Stunde ab.")
 (:email-reset-ignore . "Wenn du kein Zurücksetzen des Passworts angefordert hast, kannst du diese E-Mail ignorieren.")
 (:email-reminder-subject-due . "Zeit, deine Hiisi-Karten zu wiederholen")
 (:email-reminder-subject-streak . "Halte deine Hiisi-Serie am Laufen")
 (:email-reminder-cards-due . "Karten warten auf Wiederholung")
 (:email-reminder-keep-going . "Seit deiner letzten Wiederholung sind ein paar Tage vergangen. Fünf Minuten heute genügen, damit dir nicht entgleitet, was du bereits gelernt hast.")
 (:email-reminder-button . "Jetzt wiederholen")
 (:email-reminder-settings . "Erinnerungen verwalten")
 (:email-reminder-preview-title . "Karten, die auf dich warten")
 (:email-reminder-translation-label . "Übersetzung")
 (:email-reminder-more-due-today . "weitere Karten sind heute fällig")
 (:email-trial-subject . "Wie läuft deine Hiisi-Testphase?")
 (:email-trial-expiring . "Deine kostenlose Hiisi-Testphase endet morgen.")
 (:email-trial-feedback . "Gefällt dir Hiisi? Sag uns, was dir am meisten hilft.")
 (:email-trial-strengths . "Du kannst echte Texte übersetzen, die besten Einträge als Karteikarten speichern und mit verteilten Wiederholungen lernen.")
 (:email-trial-reply . "Antworte einfach auf diese E-Mail, und deine Nachricht landet direkt beim Hiisi-Team.")
 (:email-trial-button . "Tarif wählen")
 (:email-trial-manage . "Abo verwalten")
 (:email-trial-contact . "Schreib uns")
 (:email-plan-nudge-subject . "Deine Übersetzungen warten")
 (:email-plan-nudge-title . "Deine Übersetzungen warten")
 (:email-plan-nudge-intro . "Du hast dich bei Hiisi angemeldet, aber noch keinen Tarif gewählt.")
 (:email-plan-nudge-benefits-intro . "Mit einem Abo bekommst du:")
 (:email-plan-nudge-benefit-translations . "600 Übersetzungen pro Monat mit Grammatikaufschlüsselungen")
 (:email-plan-nudge-benefit-flashcards . "Unbegrenzte Karteikarten mit verteiltem Wiederholen")
 (:email-plan-nudge-benefit-decks . "Eigene Decks, die du organisieren und teilen kannst")
 (:email-plan-nudge-pricing . "Die Tarife beginnen bei 10 EUR pro Monat, oder spare mit dem Jahrestarif für 100 EUR pro Jahr (zwei Monate gratis).")
 (:email-plan-nudge-feedback . "Wenn etwas an Hiisi für dich nicht funktioniert, antworte auf diese E-Mail. Deine Nachricht geht direkt an das Hiisi-Team.")
 (:email-plan-nudge-button . "Tarif wählen")
 (:email-plan-nudge-unsubscribe . "Diese E-Mails abbestellen")
 (:email-plan-nudge-unsubscribe-done-title . "Abo-Erinnerungen deaktiviert")
 (:email-plan-nudge-unsubscribe-done-body . "Du wirst keine weiteren Erinnerungs-E-Mails zur Tarifwahl erhalten.")
 (:email-plan-nudge-unsubscribe-invalid-title . "Dieser Link ist nicht gültig")
 (:email-plan-nudge-unsubscribe-invalid-body . "Dieser Abmeldelink fehlt, ist abgelaufen oder nicht mehr gültig.")
 (:email-invite-subject . "Du wurdest zu Hiisi eingeladen")
 (:email-invite-title . "Du wurdest zu Hiisi eingeladen")
 (:email-invite-intro . "Du wurdest eingeladen, Hiisi kostenlos zu nutzen, als Tester, geschätzter Freund oder beides.")
 (:email-invite-details . "Nutze die Schaltfläche unten, um dein Konto zu erstellen und Übersetzungen sowie Karteikarten zu entdecken.")
 (:email-invite-button . "Konto erstellen")
 (:email-invite-issue-reporting . "Wenn etwas kaputtgeht oder sich falsch anfühlt, gibt es unten auf jeder Seite eine Schaltfläche zum Melden von Problemen.")
 (:email-issue-completed-subject . "Dein Hiisi-Problem wurde behoben")
 (:email-issue-completed-title . "Problem behoben")
 (:email-issue-completed-label . "Problem")
 (:email-issue-completed-followup . "Öffne Hiisi, um die Korrektur zu prüfen oder dort weiterzumachen, wo du aufgehört hast.")
 (:email-issue-completed-button . "Hiisi öffnen")
 (:email-issue-completed-open-link . "Seite öffnen")

 ;; Translation page
 (:translate-title . "Übersetzen")
 (:landing-public-translate-title . "Probier es hier aus")
 (:landing-public-translate-cta-title . "Bleib dran")
 (:landing-public-translate-cta-body . "Speichere Übersetzungen als Lernkarten und wiederhole sie später.")
 (:landing-public-translate-cta-button . "Kostenlose Testphase starten und weiterlernen")
 (:translate-input-label . "Text zum Übersetzen")
 (:translate-input-placeholder . "Text zum Übersetzen eingeben...")
 (:translate-from . "Ausgangssprache:")
 (:translate-to . "Zielsprache:")
 (:translate-select-target-placeholder . "Zielsprache auswählen")
 (:translate-submit . "Übersetzen")
 (:translate-auto-detect . "Beliebig (Automatisch erkennen)")
 (:translate-empty-state . "Übersetze ein Wort oder eine Phrase, dann siehst du hier das Ergebnis, die Grammatikaufschlüsselung und Lernaktionen.")
 (:translate-select-deck-placeholder . "Deck auswählen (optional)")
 (:translate-new-deck . "Neues Deck")
 (:translate-add-to-deck . "Zum Deck hinzufügen")
 (:translate-bookmark . "Merken")
 (:translate-bookmarked . "Gemerkt")
 (:translate-retry . "Neu generieren")
 (:translate-like-tooltip . "Gute Übersetzung")
 (:translate-dislike-tooltip . "Schlechte Übersetzung - neue anfordern")
 (:translate-dislike-confirm . "Dies generiert eine neue Übersetzung. Fortfahren?")
 (:pronunciation-label . "Aussprache")
 (:pronunciation-show . "Aussprache anzeigen")
 (:pronunciation-hide . "Aussprache ausblenden")
 (:grammar-term-examples . "Beispiele")
 (:grammar-term-related . "Verwandte Begriffe")
 (:grammar-term-modal-title . "Grammatikbegriff")
 (:grammar-term-empty . "Wähle einen hervorgehobenen Begriff aus, um Details zu sehen.")
 (:extension-login-required . "Melde dich bei Hiisi an, bevor du die Browser-Erweiterung verwendest.")
 (:extension-session-invalid . "Deine Hiisi-Sitzung ist nicht mehr gültig. Melde dich erneut an.")
 (:extension-activation-required . "Aktiviere dein Hiisi-Konto, bevor du die Browser-Erweiterung verwendest.")
 (:extension-subscription-required . "Starte eine Hiisi-Testphase, bevor du die Browser-Erweiterung verwendest.")

 ;; Translation and Flashcards
 (:lang-auto . "Auto")
 (:lang-unknown . "?")
 (:lang-target . "Ziel")
 (:translate-deck-create-title . "Neuen Stapel erstellen")
 (:translate-deck-name-label . "Stapelname")
 (:translate-deck-name-placeholder . "z. B. Finnisch Grundlagen")
 (:translate-deck-description-label . "Beschreibung (optional)")
 (:translate-deck-cancel . "Abbrechen")
 (:translate-deck-create . "Erstellen")
 (:translate-rate-label . "Übersetzung bewerten")
 (:flashcards-delete . "Löschen")
 (:flashcards-delete-confirm . "Möchten Sie diese Karteikarte wirklich löschen?")
 (:flashcards-deck-search-placeholder . "Stapel suchen...")
 (:flashcards-no-decks . "Noch keine Stapel. Erstellen Sie zuerst einen!")
 (:flashcards-deck-cancel . "Abbrechen")
 (:flashcards-recollection-tooltip . "Erinnerung: ~A")
 (:flashcards-recollection-poor . "Schwach")
 (:flashcards-recollection-fair . "Mäßig")
 (:flashcards-recollection-normal . "Normal")
 (:flashcards-recollection-strong . "Stark")
 (:flashcards-recollection-very-strong . "Sehr stark")

 ;; Flashcard review
 (:review-title . "Wiederholen")
 (:review-session-title . "Wiederholungssitzung")
 (:review-session-subtitle . "Übe deine gespeicherten Karteikarten")
 (:review-selector-title . "Wähle aus, was du wiederholen möchtest")
 (:review-selector-subtitle . "Wähle ein Deck oder ein Sprachpaar für deine Wiederholungssitzung.")
 (:review-by-deck . "Nach Deck wiederholen")
 (:review-by-language-pair . "Nach Sprachpaar wiederholen")
 (:review-all-cards . "Alle Karten wiederholen")
 (:review-cards-due . "Karten fällig")
 (:review-deck-caught-up . "Alles erledigt")
 (:review-all-caught-up . "Alles erledigt!")

 (:review-no-cards . "Keine Karten zur Wiederholung")
 (:review-no-cards-desc . "Du hast gerade keine Karteikarten zur Wiederholung fällig.")
 (:review-no-cards-hint . "Übersetze Text und klicke auf \"Als Karteikarte speichern\", um dein Deck aufzubauen!")
 (:review-start-translating . "Übersetzen starten")
 (:review-click-reveal . "Klicken um Antwort anzuzeigen")
 (:review-grammar-breakdown . "Grammatikanalyse")
 (:review-how-well . "Hast du dich erinnert?")
 (:review-again . "Nein")
 (:review-hard . "Kaum")
 (:review-good . "Ja")
 (:review-easy . "Leicht")
 (:review-progress . "Karte ~a von ~a")
 (:review-correct-count . "Richtig")
 (:review-wrong-count . "Falsch")
 (:landing-mockup-forgot-detail . "1. Person Singular Präteritum von \"olvidar\" (vergessen)")
 (:landing-mockup-keys-detail . "Possessiv \"mis\" mit femininem Pluralsubstantiv \"llaves\" (Schlüssel)")
 (:landing-mockup-home-detail . "Idiomatisches \"en casa\" (zu Hause) -- kein Artikel nötig")
 (:landing-mockup-possession-note . "Im Spanischen kennzeichnet das Präteritum abgeschlossene vergangene Handlungen. Das Subjektpronomen wird meist weggelassen, da die Verbendung den Sprecher bereits anzeigt.")
 (:landing-mockup-children-detail . "Nominativ Plural von \"Kind\" -- Plural bildet sich mit -er")
 (:landing-mockup-played-detail . "3. Person Plural Präteritum von \"spielen\"")
 (:landing-mockup-garden-detail . "Dativ: \"in dem\" verschmilzt zu \"im\", mit maskulinem Substantiv \"Garten\"")
 (:landing-mockup-czech-note . "Im Deutschen wird das Präteritum in Schriftsprache bevorzugt. \"Im\" ist eine Verschmelzung von \"in\" + \"dem\" (Dativartikel).")
 (:landing-mockup-deck-title . "Italienisch Grundlagen")
 (:landing-mockup-share-deck . "Deck teilen")
 (:review-complete . "Sitzung abgeschlossen!")
 (:review-complete-msg . "Du hast ~a Karten wiederholt")
 (:review-again-btn . "Erneut wiederholen")
 (:review-translate-more . "Mehr übersetzen")
 (:review-streak . "Tage Serie")

 ;; Dashboard
 (:dashboard-title . "Dashboard")
 (:dashboard-welcome-title . "Übersetze deinen ersten Text")
 (:dashboard-welcome-subtitle . "Übersetze eine nützliche Wendung, speichere sie in einem Deck und wiederhole sie, wenn es darauf ankommt.")
 (:dashboard-take-quick-tour . "Kurze Tour ansehen")
 (:dashboard-cards-due . "Fällige Karten")
 (:dashboard-total-cards . "Karten insgesamt")
 (:dashboard-mastered-cards . "Beherrschte Karten")
 (:dashboard-subscription . "Abonnement")
 (:dashboard-subscribed-until . "Abonniert bis")
 (:dashboard-trial-ends . "Testphase endet")
 (:dashboard-not-subscribed . "Nicht abonniert")
 (:dashboard-recent . "Letzte Übersetzungen")
 (:dashboard-no-translations . "Noch keine Übersetzungen")
 (:dashboard-streak . "Wiederholungsserie")
 (:dashboard-days . "Tage")
 (:dashboard-all-caught-up . "Alles aufgeholt!")
 (:dashboard-all-caught-up-hint . "Übersetze mehr, um deine Sammlung auszubauen.")
 (:dashboard-no-cards-title . "Erstelle deine ersten Lernkarten")
 (:dashboard-no-cards-hint . "Übersetze Text und speichere nützliche Wendungen, um deine Sammlung aufzubauen.")
 (:dashboard-first-use-checklist-title . "Erste Schritte")
 (:dashboard-first-use-checklist-translate . "Erstelle deine erste Übersetzung")
 (:dashboard-first-use-checklist-card . "Speichere deine erste Karte")
 (:dashboard-first-use-checklist-review . "Schließe deine erste Wiederholung ab")
 (:dashboard-getting-started . "Erste Schritte")
 (:dashboard-tip-1 . "Übersetze Text, den du lernen möchtest")
 (:dashboard-tip-2 . "Klicke bei Übersetzungen auf \"Als Karteikarte speichern\", die du behalten möchtest")
 (:dashboard-tip-3 . "Wiederhole deine Karteikarten regelmäßig - Spaced Repetition hilft beim langfristigen Behalten")
 (:dashboard-tip-4 . "Bewerte ehrlich - das hilft dem Algorithmus, deine Wiederholungen optimal zu planen")

 ;; Account
 (:account-title . "Konto")
 (:account-subtitle . "Verwalte hier Profil, Abo, Erinnerungen, Exporte und die Löschung deines Kontos.")
 (:account-profile-subtitle . "Halte deinen Anzeigenamen und deine E-Mail-Adresse aktuell.")
 (:account-export-subtitle . "Lade eine Kopie deiner gespeicherten Übersetzungen, Decks und Wiederholungsdaten herunter.")
 (:account-deletion-title . "Kontolöschung")
 (:account-deletion-scheduled . "Ihr Konto ist für die Löschung am ~A geplant.")
 (:account-deletion-cancel-hint . "Sie können vor diesem Datum abbrechen, um Ihr Konto zu behalten.")
 (:account-deletion-cancel . "Löschung abbrechen")
 (:account-deletion-request . "Sie können die Kontolöschung jederzeit anfordern. Die Löschung ist 14 Tage nach der Bestätigung geplant. Wenn Sie es sich anders überlegen, kontaktieren Sie bitte den Support, bevor diese 14 Tage ablaufen.")
 (:account-deletion-confirm . "Kontolöschung in 14 Tagen ab heute planen?")
 (:account-deletion-schedule . "Löschung planen")
 (:account-reminders-title . "E-Mail-Erinnerungen")
 (:account-reminders-subtitle . "Lege fest, ob Hiisi dir E-Mails schicken darf, wenn etwas zum Wiederholen auf dich wartet.")
 (:account-reminders-opt-out . "Erinnerungen für Wiederholung und Fortsetzung abbestellen")
 (:account-reminders-save . "Einstellungen speichern")

 ;; Subscription
 (:subscribe-title . "Einfache Preise")
 (:subscribe-choose-plan . "Wähle deinen Plan")
 (:subscribe-start-today . "Starte heute mit einer 14-tägigen kostenlosen Testphase")
 (:subscribe-monthly . "Monatlich")
 (:subscribe-annual . "Jährlich")
 (:subscribe-founder-member . "Gründungsmitglied")
 (:subscribe-monthly-price . "€10")
 (:subscribe-annual-price . "€100")
 (:subscribe-founder-price . "€79")
 (:subscribe-founder-monthly-equivalent . "€6,58/Monat, jährlich abgerechnet")
 (:subscribe-founder-savings . "Spare €41/Jahr gegenüber monatlicher Zahlung")
 (:subscribe-monthly-billing-equivalent . "€10/Monat, monatlich abgerechnet")
 (:subscribe-monthly-billing-note . "Flexible monatliche Zahlung")
 (:landing-pricing-comparison-title . "Kurzvergleich")
 (:subscribe-per-month . "/Monat")
 (:subscribe-per-year . "/Jahr")
 (:subscribe-monthly-desc . "600 Übersetzungen pro Monat. Unbegrenzte Karteikarten, Stapel und Wiederholungen.")
 (:subscribe-unlimited-flashcards . "Unbegrenzte Karteikarten")
 (:subscribe-grammar-explanations . "Grammatikerklärungen")
 (:subscribe-spaced-repetition . "Spaced Repetition")
 (:subscribe-annual-desc . "Alles aus dem Monatsplan. Zwei Monate gratis.")
 (:subscribe-founder-lock . "Der Preis bleibt gleich, solange dein Abo aktiv bleibt.")
 (:subscribe-founder-badge . "Begrenztes Angebot")
 (:subscribe-founder-limit . "Begrenzt auf die ersten 100 Mitglieder")
 (:subscribe-manage . "Abonnement verwalten")
 (:subscribe-activated . "Abonnement aktiviert!")
 (:subscribe-thank-you . "Dein Abonnement ist aktiv. Hier kannst du die Abrechnung verwalten und weitere Übersetzungen kaufen.")
 (:subscribe-start-learning . "Jetzt lernen")
 (:subscribe-management . "Abonnementverwaltung")
 (:subscribe-active . "Aktives Abonnement")
 (:subscribe-preapproved-access . "Vorab genehmigter Zugang")
 (:subscribe-status . "Status:")
 (:subscribe-status-active . "Aktiv")
 (:subscribe-status-preapproved . "Vorab genehmigt")
 (:subscribe-preapproved-detail . "Dieses Konto verwendet einen von Hiisi verwalteten vorab genehmigten Zugang.")
 (:subscribe-days-remaining . "Verbleibende Tage:")
 (:subscribe-renews-on . "Verlängert am:")
 (:subscribe-no-subscription . "Kein aktives Abonnement")
 (:subscribe-access-features . "Wähle einen Tarif für vollen Zugriff und eine zentrale Abrechnungsverwaltung.")
 (:subscribe-view-plans . "Pläne ansehen")
 (:subscribe-faq-title . "Häufig gestellte Fragen")
 (:subscribe-faq-trial-q . "Was passiert nach der kostenlosen Testphase?")
 (:subscribe-faq-trial-a . "Deine 14-tägige Testphase erfordert keine Karte. Wenn sie endet, wähle einen bezahlten Plan, um vollen Zugriff zu behalten.")
 (:subscribe-faq-cancel-q . "Kann ich jederzeit kündigen?")
 (:subscribe-faq-cancel-a . "Ja! Du kannst dein Abonnement jederzeit kündigen. Du behältst den Zugang bis zum Ende deines Abrechnungszeitraums.")
 (:subscribe-faq-payment-q . "Welche Zahlungsmethoden akzeptiert ihr?")
 (:subscribe-faq-payment-a . "Wir akzeptieren alle gängigen Kredit- und Debitkarten über unseren Zahlungspartner Polar.sh.")
 (:subscribe-copyright . "Lambda Symbolics OÜ © 2026.")
(:subscribe-checkout-unavailable . "Der Bezahlvorgang ist vorübergehend nicht verfügbar. Bitte versuche es erneut.")
(:subscribe-portal-unavailable . "Die Abonnementverwaltung ist vorübergehend nicht verfügbar. Bitte versuche es erneut.")
(:subscribe-founder-sold-out . "Das Angebot für Gründungsmitglieder ist ausverkauft")
(:subscribe-founder-unavailable . "Das Angebot für Gründungsmitglieder ist derzeit nicht verfügbar.")
(:subscribe-checkout-cta . "Abonnieren")

 ;; Errors and status
 (:error-generic . "Etwas ist schiefgelaufen")
(:error-invalid-request . "Ungültige Anfragedaten.")
(:error-not-found . "Die angeforderte Ressource wurde nicht gefunden.")
(:error-forbidden . "Du hast darauf keinen Zugriff.")
(:error-rate-limited . "Bitte warte einen Moment und versuche es erneut.")
 (:error-text-too-long . "Text ist zu lang. Die maximale Übersetzungslänge beträgt 120 Zeichen.")
 (:error-input-too-long . "Eingabe zu lang")
 (:error-unknown-source-lang . "Die ausgewählte Ausgangssprache wird nicht unterstützt.")
 (:error-unknown-target-lang . "Die ausgewählte Zielsprache wird nicht unterstützt.")
 (:error-unknown-language . "Unbekannte Sprache")
 (:error-translation-unavailable . "Der Übersetzungsdienst ist vorübergehend nicht verfügbar. Bitte versuche es gleich noch einmal.")
 (:error-translation-failed . "Übersetzung fehlgeschlagen")
 (:error-translation-retry . "Konnte nach mehreren Versuchen keine Übersetzung generieren. Bitte formuliere deinen Text um.")
 (:error-quota-exceeded . "Übersetzungslimit erreicht")
 (:error-quota-exceeded-detail . "Du hast alle Übersetzungen für diesen Monat aufgebraucht. Dein Kontingent wird automatisch jeden Monat zurückgesetzt.")
 (:quota-low-warning . "Nur noch ~A Übersetzungen übrig. Erwägen Sie den Kauf von mehr.")
 (:top-up-button . "Mehr Übersetzungen kaufen")
 (:top-up-price . "5 €")
 (:top-up-amount . "300 Übersetzungen")
(:review-session-expired . "Deine Lernsitzung ist abgelaufen. Bitte starte eine neue Sitzung.")

 (:error-session-expired . "Deine Sitzung ist abgelaufen. Bitte melde dich erneut an.")
 (:error-session-invalid . "Deine Sitzung ist nicht mehr gültig. Bitte melde dich erneut an.")
 (:error-custom-flashcard-generation . "Die Erklärung konnte nicht erstellt werden. Bitte versuche es erneut.")
 ;; Institutions
 (:institutions-page-title . "Hiisi für Schulen und Universitäten")
 (:institutions-hero-title . "Sprachlernwerkzeuge für den Unterricht")
 (:institutions-hero-subtitle . "Geben Sie Ihren Lernenden teilbare Stapel, grammatikbezogene Übungen und verlässliche Wiederholungsroutinen, die in echten Unterricht passen.")
 (:institutions-section-title . "Warum Institutionen Hiisi nutzen")
 (:institutions-section-body . "Hiisi hilft Lehrkräften dabei, Unterrichtsmaterial in angeleitetes Lernen zu verwandeln, mit dem Lernende wirklich Schritt halten können. Erstellen Sie Stapel für einen Kurs, teilen Sie sie per Link und unterstützen Sie Wortschatz- und Grammatikarbeit ohne zusätzlichen Verwaltungsaufwand.")
 (:institutions-benefit-1 . "Teilbare Stapel und eigene Aufgaben, die zu Ihrem Curriculum passen.")
 (:institutions-benefit-2 . "Likes und Dislikes der Lernenden helfen dabei, die stärksten Übersetzungen für häufige Unterrichtsformulierungen nach oben zu bringen.")
 (:institutions-benefit-3 . "Grammatikaufschlüsselungen und verteilte Wiederholung fördern mehr als nur das Auswendiglernen isolierter Wortlisten.")
 (:institutions-benefit-4 . "Unterrichtsnahe Unterstützung von jemandem, der aufmerksam zuhört und die Bedürfnisse im Klassenzimmer ernst nimmt.")
 (:institutions-request-title . "Gespräch beginnen")
 (:institutions-request-subtitle . "Erzählen Sie uns von Ihrer Einrichtung, Ihren Sprachen und der Unterstützung, die Sie für Ihren Unterricht brauchen. Wir melden uns innerhalb einer Woche.")
 (:institutions-aside-title . "Was als Nächstes passiert")
 (:institutions-aside-body . "Wir prüfen Ihre Anforderungen und melden uns innerhalb einer Woche, um Zugang und Einrichtung für Ihre Institution zu besprechen.")
 (:institutions-field-name . "Name der Institution")
 (:institutions-field-name-placeholder . "Ihre Universität")
 (:institutions-field-contact-name . "Kontaktperson")
 (:institutions-field-contact-name-placeholder . "Ihr Name")
 (:institutions-field-contact-email . "Kontakt-E-Mail")
 (:institutions-field-contact-email-placeholder . "sie@universitaet.de")
 (:institutions-field-domains . "E-Mail-Domains")
 (:institutions-field-domains-placeholder . "universitaet.de, cs.universitaet.de")
 (:institutions-field-domains-help . "Kommagetrennte Liste der E-Mail-Domains Ihrer Institution")
 (:institutions-field-notes . "Zusätzliche Informationen")
 (:institutions-field-notes-placeholder . "Geschätzte Anzahl der Studierenden, bevorzugter Abrechnungszyklus, besondere Anforderungen...")
 (:institutions-submit . "Anfrage senden")
 (:institutions-success-title . "Danke - Hiisi für Schulen und Universitäten")
 (:institutions-success-heading . "Danke!")
 (:institutions-success-body . "Wir haben Ihre Anfrage erhalten. Wir prüfen die Bedürfnisse Ihrer Einrichtung und melden uns innerhalb einer Woche.")
 (:institutions-success-back . "Zurück zur Startseite")

 ;; Footer
 (:footer-privacy . "Datenschutz")
 (:footer-terms . "Nutzungsbedingungen")

 ;; Early software notice
 (:early-software-notice . "Hiisi befindet sich in früher Entwicklung. Einen Fehler gefunden oder einen Vorschlag?")

 ;; Datenschutzerklärung
 (:privacy-title . "Datenschutzerklärung")
 (:privacy-updated . "Zuletzt aktualisiert: Januar 2026")
 (:privacy-who-title . "Wer wir sind")
 (:privacy-who-body . "Hiisi wird von Lambda Symbolics OÜ betrieben, einem in Estland registrierten Unternehmen. Als estnisches Unternehmen halten wir die Datenschutz-Grundverordnung (DSGVO) der Europäischen Union ein.")
 (:privacy-collect-title . "Welche Daten wir erfassen")
 (:privacy-collect-intro . "Wenn Sie Hiisi verwenden, erfassen wir folgende Informationen:")
 (:privacy-collect-account-key . "Kontoinformationen: ")
 (:privacy-collect-account-val . "E-Mail-Adresse, Anzeigename und ein sicher gehashtes Passwort.")
 (:privacy-collect-learning-key . "Lerndaten: ")
 (:privacy-collect-learning-val . "Ihre Übersetzungen, gespeicherten Karteikarten und Ihr Wiederholungsverlauf.")
 (:privacy-collect-usage-key . "Nutzungsdaten: ")
 (:privacy-collect-usage-val . "Grundlegende Serverprotokolle für Sicherheits- und Debugging-Zwecke.")
 (:privacy-use-title . "Wie wir Ihre Daten verwenden")
 (:privacy-use-auth-key . "Authentifizierung: ")
 (:privacy-use-auth-val . "Zur Überprüfung Ihrer Identität und zum Schutz Ihres Kontos.")
 (:privacy-use-service-key . "Bereitstellung des Dienstes: ")
 (:privacy-use-service-val . "Um Übersetzungen bereitzustellen und Ihre Karteikartensammlung zu verwalten.")
 (:privacy-use-ai-key . "KI-Übersetzungen: ")
 (:privacy-use-ai-val . "Ihre Übersetzungsanfragen werden an OpenRouter gesendet, um Antworten zu erzeugen. OpenRouter kann Anfragen an den konfigurierten Modellanbieter weiterleiten. Wie OpenRouter diese Daten verarbeitet, finden Sie in der Datenschutzerklärung von OpenRouter.")
 (:privacy-third-title . "Dienste von Drittanbietern")
 (:privacy-third-intro . "Wir verwenden die folgenden Drittanbieter-Dienste:")
 (:privacy-third-openrouter-key . "OpenRouter: ")
 (:privacy-third-openrouter-val . "Für automatische Übersetzungsanfragen.")
 (:privacy-third-mailgun-key . "Mailgun: ")
 (:privacy-third-mailgun-val . "Für den Versand von Aktivierungs- und Transaktions-E-Mails.")
 (:privacy-third-polar-key . "Polar.sh: ")
 (:privacy-third-polar-val . "Für die Verarbeitung von Abonnementzahlungen.")
 (:privacy-cookies-title . "Cookies")
 (:privacy-cookies-intro . "Wir verwenden nur notwendige Cookies:")
 (:privacy-cookies-auth-key . "Authentifizierungs-Token: ")
 (:privacy-cookies-auth-val . "Ein sicheres, nur über HTTP zugängliches Cookie, damit Sie eingeloggt bleiben.")
 (:privacy-cookies-lang-key . "Spracheinstellung: ")
 (:privacy-cookies-lang-val . "Damit Ihre bevorzugte Sprache der Benutzeroberfläche gespeichert bleibt.")
 (:privacy-retention-title . "Speicherdauer")
 (:privacy-retention-body . "Ihre Daten werden gespeichert, solange Sie ein Konto haben. Wenn Sie eine Löschung anfordern, wird Ihr Konto zur Löschung in 14 Tagen vorgemerkt.")
 (:privacy-rights-title . "Ihre Rechte (DSGVO)")
 (:privacy-rights-intro . "Nach der DSGVO haben Sie das Recht auf:")
 (:privacy-rights-access . "Auskunft über Ihre personenbezogenen Daten")
 (:privacy-rights-export . "Export Ihrer Daten (verfügbar unter /app/api/export)")
 (:privacy-rights-correct . "Berichtigung unrichtiger Daten")
 (:privacy-rights-delete . "Löschung Ihres Kontos und Ihrer Daten")
 (:privacy-rights-object . "Widerspruch gegen die Verarbeitung Ihrer Daten")
 (:privacy-rights-contact . "Um diese Rechte auszuüben, kontaktieren Sie uns unter")
 (:privacy-contact-title . "Kontakt")
 (:privacy-contact-intro . "Für Datenschutzanfragen:")
 (:privacy-contact-email-label . "E-Mail: ")
 (:privacy-address-1 . "Lambda Symbolics OÜ")
 (:privacy-address-2 . "Harju maakond, Tallinn, Kesklinna linnaosa, Tornimäe tn 5, 10145")

 ;; Nutzungsbedingungen
 (:terms-title . "Nutzungsbedingungen")
 (:terms-updated . "Zuletzt aktualisiert: Januar 2026")
 (:terms-1-title . "1. Dienstbeschreibung")
 (:terms-1-body . "Hiisi ist eine Sprachlern-Anwendung, die automatisierte Übersetzungen mit grammatischen Erklärungen und Karteikarten mit verteilter Wiederholung anbietet. Der Dienst wird von Lambda Symbolics OÜ betrieben.")
 (:terms-2-title . "2. Kontoregistrierung")
 (:terms-2-body . "Um Hiisi zu nutzen, müssen Sie ein Konto mit einer gültigen E-Mail-Adresse erstellen. Sie sind für die Sicherheit Ihrer Zugangsdaten verantwortlich.")
 (:terms-3-title . "3. Abonnement und Zahlungen")
 (:terms-3-body . "Hiisi bietet kostenpflichtige Abonnements (monatlich und jährlich). Abonnements werden über Polar.sh verarbeitet.")
 (:terms-3-list-1 . "Abonnements verlängern sich automatisch, sofern sie nicht vor dem Verlängerungsdatum gekündigt werden.")
 (:terms-3-list-2 . "Rückerstattungen erfolgen nach den geltenden Verbraucherschutzgesetzen.")
 (:terms-3-list-3 . "Bei ausbleibender Zahlung entfällt der Zugriff auf Premium-Funktionen.")
 (:terms-4-title . "4. Zulässige Nutzung")
 (:terms-4-intro . "Sie verpflichten sich, Folgendes zu unterlassen:")
 (:terms-4-list-1 . "Den Dienst für rechtswidrige Zwecke zu verwenden")
 (:terms-4-list-2 . "Nutzungsbeschränkungen oder Sicherheitsmaßnahmen zu umgehen")
 (:terms-4-list-3 . "Ihre Zugangsdaten mit anderen zu teilen")
 (:terms-4-list-4 . "Automatisierte Werkzeuge so einzusetzen, dass die Leistung für andere beeinträchtigt wird")
 (:terms-5-title . "5. Inhalte und geistiges Eigentum")
 (:terms-5-body-1 . "Von Hiisi erzeugte Übersetzungen werden automatisch erstellt und sind möglicherweise nicht einzigartig. Sie dürfen Ihre Übersetzungen und Karteikarten für persönliche Zwecke nutzen, besitzen aber keine exklusiven Urheberrechte an automatisch generierten Inhalten.")
 (:terms-5-body-2 . "Die Hiisi-Anwendung, die Marke und originale Inhalte bleiben Eigentum von Lambda Symbolics OÜ.")
 (:terms-6-title . "6. Verfügbarkeit des Dienstes")
 (:terms-6-intro . "Hiisi wird in der Form \"wie bereitgestellt\" angeboten. Wir garantieren nicht:")
 (:terms-6-list-1 . "Einen unterbrechungsfreien oder fehlerfreien Dienst")
 (:terms-6-list-2 . "Die Genauigkeit von automatisch generierten Übersetzungen")
 (:terms-6-list-3 . "Die Verfügbarkeit bestimmter Funktionen")
 (:terms-6-body . "Wir können Funktionen jederzeit ändern oder einstellen.")
 (:terms-7-title . "7. Haftungsbeschränkung")
 (:terms-7-body-1 . "Soweit gesetzlich zulässig haftet Lambda Symbolics OÜ nicht für indirekte, zufällige, besondere oder Folgeschäden, die aus Ihrer Nutzung von Hiisi entstehen.")
 (:terms-7-body-2 . "Unsere Gesamthaftung ist auf den Betrag begrenzt, den Sie in den 12 Monaten vor dem Anspruch für den Dienst bezahlt haben.")
 (:terms-8-title . "8. Konto-Kündigung")
 (:terms-8-body-1 . "Wir können Ihr Konto sperren oder kündigen, wenn Sie gegen diese Bedingungen verstoßen. Sie können jederzeit in der Anwendung die Löschung Ihres Kontos anfordern.")
 (:terms-8-body-2 . "Nach einem Löschantrag wird Ihr Konto zur Löschung in 14 Tagen vorgemerkt.")
 (:terms-9-title . "9. Änderungen der Bedingungen")
 (:terms-9-body . "Wir können diese Bedingungen von Zeit zu Zeit aktualisieren. Die weitere Nutzung von Hiisi nach Änderungen gilt als Zustimmung zu den neuen Bedingungen.")
 (:terms-10-title . "10. Anwendbares Recht")
 (:terms-10-body . "Für diese Bedingungen gilt estnisches Recht. Streitigkeiten werden vor den Gerichten Estlands entschieden.")
 (:terms-contact-title . "Kontakt")
 (:terms-contact-intro . "Bei Fragen zu diesen Bedingungen:")
 (:terms-contact-email-label . "E-Mail: ")
 (:terms-address-1 . "Lambda Symbolics OÜ")
 (:terms-address-2 . "Harju maakond, Tallinn, Kesklinna linnaosa, Tornimäe tn 5, 10145")

 ;; Decks
 (:decks-title . "Stapel")
 (:decks-subtitle . "Erstelle eigene Stapel und teile sie mit anderen.")
 (:decks-create-title . "Stapel erstellen")
 (:decks-name-placeholder . "Stapelname")
 (:decks-desc-placeholder . "Beschreibung")
 (:decks-create-btn . "Stapel erstellen")
 (:decks-edit-title . "Stapel bearbeiten")
 (:decks-edit-btn . "Stapel bearbeiten")
 (:decks-actions-title . "Stapelaktionen")
 (:decks-card-actions-title . "Kartenaktionen")
 (:decks-update-btn . "Änderungen speichern")
 (:decks-default-badge . "Automatisch")
 (:decks-default-description . "Dieser Stapel wird für dieses Sprachenpaar automatisch verwaltet.")
 (:decks-default-readonly . "Automatische Stapel haben feste Namen und Beschreibungen.")
 (:decks-delete-btn . "Stapel löschen")
 (:decks-delete-confirm . "Diesen Stapel wirklich löschen?")
 (:decks-error-name-required . "Der Stapelname ist erforderlich.")
 (:decks-error-name-too-long . "Der Stapelname darf höchstens ~A Zeichen lang sein.")
 (:decks-error-desc-too-long . "Die Stapelbeschreibung darf höchstens ~A Zeichen lang sein.")
 (:decks-error-default-readonly . "Automatische Stapel können nicht bearbeitet werden.")
 (:decks-error-default-delete-forbidden . "Automatische Stapel können nicht gelöscht werden.")
 (:decks-your-title . "Deine Stapel")
 (:decks-col-updated . "Aktualisiert")
 (:decks-no-decks . "Noch keine Stapel.")
 (:decks-open-btn . "Öffnen")
 (:decks-view-deck-btn . "Deck ansehen")
 (:decks-start-review . "Wiederholung starten")
 (:decks-no-desc . "Keine Beschreibung.")
 (:decks-share-title . "Teilen-Link")
 (:decks-share-info . "Jeder mit diesem Link kann den Stapel importieren:")
 (:decks-share-copy . "Link kopieren")
 (:decks-share-copied . "Kopiert")
 (:decks-add-from-flashcards-title . "Karteikarten hinzufügen")
 (:decks-add-from-flashcards-info . "Wähle eine Karte aus, um ihre Übersetzung diesem Stapel hinzuzufügen.")
 (:decks-create-new-flashcard . "Neue Karteikarte erstellen")
 (:decks-open-flashcards . "Vorhandene Karteikarten hinzufügen")
 (:decks-filter-from . "Ausgangssprache")
 (:decks-filter-to . "Zielsprache")
 (:decks-filter-any . "Beliebige Sprache")
 (:decks-filter-include-assigned . "Auch Karten anzeigen, die bereits in einem Stapel sind")
 (:decks-flashcards-add . "Hinzufügen")
 (:decks-flashcards-added . "Hinzugefügt")
 (:decks-flashcards-in-deck . "In einem anderen Stapel")
 (:decks-flashcards-empty . "Keine Karten entsprechen diesen Filtern.")
 (:decks-items-title . "Stapelinhalt")
 (:decks-col-original . "Original")
 (:decks-col-translated . "Übersetzung")
 (:decks-col-lang . "Zielsprache")
 (:decks-no-items . "Noch keine Einträge.")
 (:decks-share-page-title . "Stapel teilen")
 (:decks-share-preview . "Vorschau und Import dieses Stapels.")
 (:decks-import-title . "Importieren")
 (:decks-import-btn . "Stapel importieren")
 (:starter-decks-title . "Bibliothek")
 (:starter-decks-subtitle . "Importiere fertige Decks von Hiisi und der Community.")
 (:starter-decks-marketplace-btn . "Bibliothek")
 (:starter-decks-explanation-language . "Erklärungssprache")
 (:starter-decks-search-label . "Suchen")
 (:starter-decks-source-label . "Quelle")
 (:starter-decks-source-all . "Alle Decks")
 (:starter-decks-change-language . "Ändern")
 (:starter-decks-filters-button . "Filter")
 (:starter-decks-search-placeholder . "Bibliothek durchsuchen")
 (:starter-decks-apply-filters . "Filter anwenden")
 (:starter-decks-select-triplet-hint . "Wähle Quell- und Zielsprache, um passende Decks zu durchsuchen.")
 (:starter-decks-official-badge . "Offiziell")
 (:starter-decks-official-by-hiisi . "Offiziell von Hiisi")
 (:starter-decks-community-badge . "Community")
 (:starter-decks-by-hiisi . "Von Hiisi")
 (:starter-decks-preview-btn . "Vorschau")
 (:starter-decks-card-count . "~A Karten")
 (:starter-decks-no-results . "Keine Decks entsprechen diesen Filtern.")
 (:starter-decks-source-cards-title . "Karten in diesem Deck")
 (:starter-decks-more-cards-included . "+~A weitere Karten enthalten.")
 (:starter-decks-sample-title . "Beispielkarten")
 (:starter-decks-generating . "Dein Deck ~A wird vorbereitet")
 (:starter-decks-generating-detail . "Wir importieren es, sobald es bereit ist. Du kannst weiter in der Bibliothek stöbern oder gleich wiederkommen.")
 (:starter-decks-generation-failed . "Erstellung fehlgeschlagen")
 (:starter-decks-generation-failed-detail . "Der letzte Erstellungsversuch ist fehlgeschlagen. Versuche, das Deck erneut zu importieren.")
 (:starter-decks-login-detail . "Melde dich an, um dieses Deck in deine Sammlung zu importieren.")
 (:starter-decks-subscribe-btn . "Tarife anzeigen")
 (:starter-decks-subscribe-detail . "Bibliotheksdecks sind mit einem aktiven Abonnement oder einer Testphase verfügbar.")
 (:library-submit-title . "In die Bibliothek einreichen")
 (:library-submit-intro . "Reiche dieses Deck zur administrativen Prüfung vor der Veröffentlichung in die Bibliothek ein.")
 (:library-submit-btn . "Deck einreichen")
 (:library-submit-approved . "Für die Bibliothek freigegeben")
 (:library-submit-approved-detail . "Dieses Deck ist in der Bibliothek veröffentlicht.")
 (:library-submit-pending . "Wartet auf Prüfung")
 (:library-submit-pending-detail . "Dieses Deck wurde eingereicht und wartet auf die Prüfung durch die Administration.")
 (:library-submit-rejected . "Vor der Veröffentlichung sind Änderungen nötig")
 (:library-submit-rejected-detail . "Diese Einreichung wurde abgelehnt. Überarbeite das Deck und reiche es erneut ein.")
 (:library-error-empty . "Füge mindestens eine Karte hinzu, bevor du dieses Deck in die Bibliothek einreichst.")
 (:library-error-missing-triplet . "Jede Karte in einer Bibliothekseinreichung muss ein vollständiges Sprachtripel haben.")
 (:library-error-mixed-triplet . "Alle Karten in einer Bibliothekseinreichung müssen dasselbe Sprachtripel teilen.")
 (:starter-deck-topic-greetings-title . "Begrüßungen und Vorstellungen")
 (:starter-deck-topic-greetings-description . "Hallo, Namen, höfliche Grundlagen und Formulierungen fürs erste Kennenlernen.")
 (:starter-deck-topic-travel-title . "Unverzichtbares Reisen")
 (:starter-deck-topic-travel-description . "Bahnhöfe, Tickets, Preise, Hilfe und Orientierung unterwegs.")
 (:starter-deck-topic-numbers-title . "Zahlen und Preise")
 (:starter-deck-topic-numbers-description . "Zählen, Summen, Preise, Stockwerke und alltägliche Mengen.")
 (:starter-deck-topic-time-title . "Zeit und Daten")
 (:starter-deck-topic-time-description . "Tage, Monate, Termine, Uhrzeiten und relative Datumsangaben.")
 (:starter-deck-topic-food-title . "Restaurant und Essen")
 (:starter-deck-topic-food-description . "Bestellen, Ernährungswünsche, Getränke, die Rechnung und alltägliche Mahlzeiten außer Haus.")
 (:starter-deck-topic-emergency-title . "Notfälle und Gesundheit")
 (:starter-deck-topic-emergency-description . "Ärzte, Apotheken, Symptome, Körperteile und dringende Hilfe.")
 (:starter-deck-topic-directions-title . "Wegbeschreibung und Verkehrsmittel")
 (:starter-deck-topic-directions-description . "Abbiegen, Haltestellen, Tickets, Bahnsteige und das Fortbewegen in der Stadt.")
 (:starter-deck-topic-school-title . "Schule und Bildung")
 (:starter-deck-topic-school-description . "Unterricht, Hausaufgaben, Prüfungen, Schulsachen und der Schulalltag.")
 (:starter-deck-topic-university-title . "Universität und Studium")
 (:starter-deck-topic-university-description . "Vorlesungen, Seminare, Studienfächer, Aufgaben und der Alltag auf dem Campus.")

 ;; Flashcards management page
 (:flashcards-title . "Meine Karten")
 (:flashcards-subtitle . "Alle gespeicherten Karteikarten an einem Ort. Suchen, organisieren und verwalten.")
 (:flashcards-search-placeholder . "Karten suchen...")
 (:flashcards-filter-button . "Filter")
 (:flashcards-filter-title . "Karten filtern")
 (:flashcards-filter-recollection . "Wie gut du sie kennst")
 (:flashcards-filter-any-recollection . "Beliebiger Kenntnisstand")
 (:flashcards-hide-perfected . "Perfekt beherrschte Karten ausblenden")
 (:flashcards-col-original . "Original")
 (:flashcards-col-translated . "Übersetzung")
 (:flashcards-no-cards . "Noch keine Karteikarten. Beginne mit Übersetzen, um welche zu erstellen!")
 (:flashcards-image-label . "Bild")
 (:flashcards-image-upload . "Bild hochladen")
 (:flashcards-image-replace . "Bild ersetzen")
 (:flashcards-image-remove . "Bild entfernen")
 (:flashcards-pagination-label . "Karteikartenseiten")
 (:flashcards-pagination-status . "Seite ~A von ~A")
 (:flashcards-pagination-previous . "Zurück")
 (:flashcards-pagination-next . "Weiter")

 ;; Landing page (redesign)
 (:landing-hero-headline . "Jedes Wort erklärt. Jede Wiederholung geplant. Fünfzehn Sprachen.")
 (:landing-hero-headline-v1 . "Übersetzen Sie Sätze einfach und lesen Sie die Grammatik in Ihrer eigenen Sprache.")
 (:landing-hero-headline-v2 . "Hiisi sorgt dafür, dass Sie nicht jeden Satz vergessen, den Sie übersetzen.")
 (:landing-hero-headline-v3 . "Machen Sie die Sätze, die Sie übersetzen, zu Wortschatz, den Sie verwenden können.")
 (:landing-hero-subheadline . "Setzen Sie für jeden beliebigen Satz ein Lesezeichen, und Hiisi liefert Ihnen die Übersetzung, die Grammatik, die Aussprache und eine Karteikarte, die später zur Wiederholung zurückkommt.")
 (:landing-hero-trust-line . "14 Tage kostenlos. Keine Karte erforderlich.")
 (:landing-credibility-languages . "15 Sprachen")
 (:landing-credibility-ai . "Jedes Wort erklärt")
 (:landing-credibility-srs . "Verteiltes Wiederholen eingebaut")
 (:landing-languages-title . "Sprachen, die wir unterstützen")
 (:landing-step-1-title . "Fügen Sie einen Satz ein")
 (:landing-step-1-desc . "Beliebig lang, in einer von 15 Sprachen. Sie erhalten die Übersetzung und die Grammatik jedes Wortes aufgeschlüsselt.")
 (:landing-step-2-title . "Speichern, was es wert ist, zu behalten")
 (:landing-step-2-desc . "Ein Klick verwandelt eine Übersetzung in eine Karteikarte, der ursprüngliche Satz bleibt als Kontext erhalten.")
 (:landing-step-3-title . "Wiederholen im richtigen Moment")
 (:landing-step-3-desc . "Verteiltes Wiederholen mit SM-2, demselben Algorithmus wie in Anki. Karten, mit denen Sie kämpfen, kommen früher zurück.")
 (:landing-feature-grammar-title . "Jedes Wort erklärt, in Ihrer Sprache")
 (:landing-feature-grammar-desc . "Übersetzungen enthalten Kasus, Genus, Aspekt und Modus Wort für Wort aufgeschlüsselt. Finnischer Partitiv, tschechische Belebtheit, polnischer Aspekt, deutsche Dativkontraktionen, alles beschriftet und mit einer Grammatikreferenz verknüpft.")
 (:landing-feature-srs-title . "Die Gewohnheit des verteilten Wiederholens, automatisiert")
 (:landing-feature-srs-desc . "Der SM-2-Algorithmus passt sich Ihrer Leistung an. Schwierige Karten erscheinen häufiger. Bekannte Karten treten zurück.")
 (:landing-feature-share-title . "Ihre Stapel oder die der Gemeinschaft")
 (:landing-feature-share-desc . "Ordnen Sie Karteikarten in thematische Stapel. Teilen Sie jeden Stapel per Link oder stöbern Sie in der Gemeinschaftsbibliothek nach Stapeln anderer.")
 (:landing-pricing-trial-note . "14 Tage kostenlose Testphase inklusive")
 (:landing-pricing-monthly-after . "14 Tage kostenlos, danach ~A/Monat")
 (:landing-pricing-annual-after . "14 Tage kostenlos, danach ~A/Jahr")
 (:landing-faq-title . "Häufig gestellte Fragen")
 (:landing-faq-trial-cap-q . "Wie viele Übersetzungen erhalte ich während der Testphase?")
 (:landing-faq-trial-cap-a . "Sie erhalten 200 Übersetzungen während Ihrer 14-tägigen Testphase. Nach dem Abonnement erhalten Sie 600 pro Monat.")
 (:landing-final-cta-title . "Ihr erster Satz dauert fünf Sekunden.")
 (:landing-final-cta-subtitle . "Fügen Sie etwas auf Finnisch, Tschechisch, Polnisch oder in einer von zwölf anderen Sprachen ein. Sehen Sie, was Hiisi daraus macht. Vierzehn Tage kostenlos.")

 ;; Trial status (in-app)
 (:trial-status . "Kostenlose Testphase")
 (:error-trial-quota-exceeded . "Test-Übersetzungslimit erreicht")
 (:error-trial-quota-detail . "Sie haben alle 200 Test-Übersetzungen verbraucht. Abonnieren Sie, um weiterzulernen.")

 ;; Custom flashcards
 (:custom-flashcard-create-title . "Karteikarte erstellen")
 (:custom-flashcard-edit-title . "Karteikarte bearbeiten")
 (:custom-flashcard-original . "Originaltext")
 (:custom-flashcard-translated . "Übersetzung")
 (:custom-flashcard-lang-from . "Ausgangssprache")
 (:custom-flashcard-lang-to . "Zielsprache")
 (:custom-flashcard-note . "Lernhinweis")
 (:custom-flashcard-forms . "Grammatikanalyse")
 (:custom-flashcard-form-term . "Begriff")
 (:custom-flashcard-form-explanation . "Erklärung")
 (:custom-flashcard-add-form . "Grammatikbegriff hinzufügen")
 (:custom-flashcard-remove-form . "Entfernen")
 (:custom-flashcard-ai-fill . "Mit KI ausfüllen")
 (:custom-flashcard-create-btn . "Karteikarte erstellen")
 (:custom-flashcard-update-btn . "Änderungen speichern")

  ;; Newsletter
  (:newsletter-email-label . "E-Mail-Adresse")
  (:newsletter-developer-label . "Ich bin Entwickler")
  (:newsletter-developer-hint . "technische Updates erhalten")
  (:landing-newsletter-title . "Hiisi-Updates erhalten.")
  (:landing-newsletter-body . "Abonnieren Sie den Newsletter für Produktupdates, neue Sprachunterstützung, Starter-Decks und gelegentliche Angebote für Gründungsmitglieder.")
  (:landing-newsletter-fine-print . "Kein Spam. Nur Produktupdates.")
  (:landing-newsletter-button . "Newsletter abonnieren")
  (:newsletter-unsubscribe-page-title . "Hiisi-Newsletter abbestellen")
  (:newsletter-unsubscribe-title . "Abbestellen")
  (:newsletter-unsubscribe-subtitle . "Geben Sie Ihre E-Mail-Adresse ein, um Hiisi-Updates abzubestellen.")
  (:newsletter-unsubscribe-button . "Abbestellen")
  (:newsletter-feedback-email-required . "Bitte geben Sie Ihre E-Mail-Adresse ein.")
  (:newsletter-feedback-email-invalid . "Bitte geben Sie eine gültige E-Mail-Adresse ein.")
  (:newsletter-feedback-already-signed-up . "Sie sind bereits angemeldet. Wir halten Sie auf dem Laufenden!")
  (:newsletter-feedback-signed-up . "Sie stehen auf der Liste! Wir senden gelegentlich Hiisi-Updates.")
  (:newsletter-feedback-unsubscribed . "Falls diese E-Mail angemeldet war, wurde sie aus den Hiisi-Updates entfernt.")
  (:newsletter-feedback-generic-error . "Etwas ist schiefgelaufen. Bitte versuchen Sie es erneut.")

  ;; Problemmeldungen
 (:issues-open-button . "Fehler melden")
 (:issues-modal-title . "Problem melden")
 (:issues-modal-subtitle . "Beschreiben Sie, was schiefgelaufen ist. Ihre aktuelle Seite wird automatisch mitgesendet.")
 (:issues-title-label . "Kurzer Titel")
 (:issues-title-placeholder . "Kurze Zusammenfassung des Problems")
 (:issues-message-label . "Was ist passiert?")
 (:issues-message-placeholder . "Bitte geben Sie Schritte zur Reproduktion, das erwartete Verhalten und das tatsächliche Ergebnis an.")
 (:issues-submit . "Meldung senden")
 (:issues-cancel . "Abbrechen")
 (:issues-success . "Deine Fehlermeldung wurde gesendet. Wir sehen sie uns so bald wie möglich an.")
 (:issues-error-required . "Bitte beschreiben Sie das Problem vor dem Absenden.")
 (:issues-error-title-too-long . "Der Titel der Meldung ist zu lang. Bitte auf unter 160 Zeichen kürzen.")
 (:issues-error-too-long . "Der Meldungstext ist zu lang. Bitte bleiben Sie unter 4000 Zeichen.")
 (:issues-error-rate-limit . "Zu viele Meldungen von dieser Quelle. Bitte warten Sie und versuchen Sie es später erneut.")
 (:issues-error-generic . "Die Problemmeldung konnte nicht gesendet werden. Bitte versuchen Sie es erneut.")

)
