;;; English translations (base language)
;;; This is the authoritative source for all translation keys

(
 ;; Language metadata (used for language picker)
 (:lang-name . "English")
 (:lang-flag . "🇬🇧")

 ;; Language modal (first-visit language selection)
 (:lang-modal-title . "Choose Your Language")
 (:lang-modal-subtitle . "Select your preferred language for the interface:")

 ;; Navigation
 (:nav-translate . "Translate")
 (:nav-review . "Review")
 (:nav-flashcards . "My Cards")
 (:nav-dashboard . "Dashboard")
 (:nav-decks . "Decks")
 (:nav-logout . "Logout")
 (:nav-home . "Home")
 (:nav-pricing . "Pricing")
 (:nav-institutions . "For Institutions")
 (:nav-export-data . "Export Data")
 (:nav-open-navigation . "Open navigation")
 (:theme-light . "Light")
 (:theme-dark . "Dark")

 ;; App title and branding
 (:app-title . "Hiisi - Language Learning")

 ;; Landing page
 (:landing-learn-more . "Learn More")
 (:landing-how-it-works . "How It Works")
 (:landing-start-trial . "Start Free Trial")
 (:landing-best-value . "Best Value")

 ;; Auth pages
 (:auth-register . "Register")
 (:auth-login . "Login")
 (:auth-email . "Email")
 (:auth-password . "Password")
 (:auth-password-again . "Confirm Password")
 (:auth-display-name . "Display Name")
 (:auth-register-title . "Register to Hiisi")
 (:auth-register-subtitle . "Create a new account")
 (:auth-login-title . "Login to Hiisi")
 (:auth-login-subtitle . "Enter your credentials")
 (:auth-login-invalid-credentials . "Invalid email or password.")
 (:auth-login-rate-limited . "Too many login attempts. Please wait a few minutes and try again.")
(:auth-register-rate-limited . "Too many registration attempts. Please wait a few minutes and try again.")
(:auth-email-invalid . "Please enter a valid email address.")
(:auth-password-too-short . "Password must be at least 8 characters long.")
(:auth-passwords-mismatch . "Passwords do not match.")
(:auth-display-name-invalid . "Display name must be between 1 and 100 characters.")
(:auth-register-email-exists . "An account with this email already exists.")
(:auth-register-unavailable . "Registration is temporarily unavailable. Please try again later.")
(:auth-register-plan-required . "Choose a plan before creating an account.")
(:auth-preapproved-email-unrecognized . "Use the email address from your invite, or choose a plan before creating an account.")
(:auth-institution-register . "Coming from an institution?")
(:auth-institution-stage-title . "Institutional access")
(:auth-institution-stage-subtitle . "Use your school or university email. Eligible accounts are unlocked through the institution after email verification.")
(:auth-institution-title . "Register through your institution")
(:auth-institution-subtitle . "Use your school or university email. If your institution is already set up with Hiisi, your account is unlocked after email verification; the individual 14-day trial is for personal plan registration.")
(:auth-institution-benefit-email . "Use your school or university email address.")
(:auth-institution-benefit-access . "Eligible accounts receive institutional access after email verification.")
(:auth-institution-benefit-fallback . "If the domain is not recognized, choose an individual plan or ask your institution to contact Hiisi.")
(:auth-see-included . "See what is included")
(:auth-institution-check-access . "Check access")
(:auth-institution-email-eligible-title . "Institutional access confirmed")
(:auth-institution-email-eligible-detail . "Continue with this email to create your account. Access will unlock after email verification.")
(:auth-institution-change-email . "Use a different email")
(:auth-institution-outcome-note . "If your school or university provides Hiisi access, your account unlocks after email verification. If the domain is not eligible, choose a personal plan to start the 14-day trial.")
(:auth-institution-personal-plan-link . "View personal plans")
(:auth-institution-domain-unrecognized . "We do not recognize that institution email domain yet. Choose a personal plan to start the 14-day trial, or ask your institution to contact Hiisi.")
(:subscribe-institution-callout-title . "Using Hiisi through a school or university?")
(:subscribe-institution-callout-body . "Register with your institutional email and Hiisi will unlock access automatically if your institution is already set up.")
(:auth-activation-email-send-failed . "Failed to send activation email. Please try again.")
 (:auth-forgot-password . "Forgot password?")
 (:auth-no-account . "Don't have an account?")
 (:auth-have-account . "Already have an account?")
 (:auth-google . "Google")
 (:auth-google-login-failed . "Google sign-in failed. Please try again.")
 (:auth-account-created . "Account created!")
 (:auth-check-email . "Check your email for the activation link.")
 (:auth-redirect-login . "Redirecting to login in")
 (:auth-seconds . "seconds...")
 (:auth-go-now . "Go now")
 (:auth-not-activated . "Account not activated")
 (:auth-activate-title . "Activate your account!")
 (:auth-activated . "Account Activated!")
 (:auth-activated-message . "Your account has been activated. You can now use Hiisi.")
 (:auth-redirecting . "Redirecting in")
 (:auth-go-to-app . "Go to App")
 (:onboarding-title . "How Hiisi works")
 (:onboarding-subtitle . "Translate real text, inspect the grammar, save useful items, and review them later.")
 (:onboarding-translate-detail . "Start with real text. Hiisi returns the translation, the aligned forms, and the next study actions in one place.")
 (:onboarding-grammar-detail . "Open the grammar breakdown to see which forms correspond across the sentence and what each part is doing.")
 (:onboarding-review-detail . "Save useful translations, then review them later with spaced repetition so they stay in long-term memory.")
 (:onboarding-decks-detail . "Group useful items into decks, share them with others, and keep related material together.")
 (:onboarding-back . "Back")
 (:onboarding-next . "Next")
 (:onboarding-skip . "Skip guide")
 (:auth-resend-title . "Resend Activation Email")
 (:auth-resend-subtitle . "Enter your email to receive a new activation link.")
 (:auth-resend-button . "Resend Activation Email")
 (:auth-resend-success . "Activation email sent!")
 (:auth-resend-success-detail . "Check your inbox for the new activation link.")
 (:auth-resend-rate-limited . "Please wait a few minutes before requesting another activation email.")
 (:auth-resend-cooldown . "You can request another email in ~a seconds.")
 (:auth-back-to-login . "Back to Login")
 (:auth-forgot-password-title . "Forgot Password")
 (:auth-forgot-password-subtitle . "Enter your email and we'll send you a link to reset your password.")
 (:auth-send-reset-link . "Send Reset Link")
 (:auth-reset-email-sent . "Reset link sent!")
 (:auth-reset-email-sent-detail . "If an account exists with that email, you'll receive a password reset link shortly.")
 (:auth-reset-rate-limited . "Please wait a few minutes before requesting another password reset.")
 (:auth-reset-invalid-token . "This password reset link is invalid or has expired.")
 (:auth-reset-password-title . "Reset Password")
 (:auth-reset-password-subtitle . "Enter your new password below.")
 (:auth-new-password . "New Password")
 (:auth-confirm-new-password . "Confirm New Password")
 (:auth-reset-password . "Reset Password")
 (:auth-password-changed . "Password changed!")
 (:auth-password-changed-detail . "Your password has been successfully changed. You can now log in with your new password.")
 (:auth-change-password-title . "Change Password")
 (:auth-change-password-subtitle . "Update your account password.")
 (:auth-current-password . "Current Password")
 (:auth-change-password . "Change Password")
 (:auth-back-to-app . "Back to App")
 (:auth-password-updated . "Password updated!")
 (:auth-password-updated-detail . "Your password has been successfully updated.")
(:auth-current-password-invalid . "Current password is incorrect.")
(:auth-new-password-same . "New password must be different from current password.")

 ;; Email copy
 (:email-common-hi . "Hi")
 (:email-common-tagline . "Hiisi - Learn through translation")
 (:email-activation-subject . "Activate your Hiisi account")
 (:email-activation-title . "Welcome to Hiisi")
 (:email-activation-body . "Thank you for registering. Please activate your account by clicking the link below:")
 (:email-activation-button . "Activate Account")
 (:email-activation-copy-link . "Or copy this link")
 (:email-activation-expiry . "This link will expire in 24 hours.")
 (:email-reset-subject . "Reset your Hiisi password")
 (:email-reset-title . "Password Reset Request")
 (:email-reset-body . "We received a request to reset your password. Click the link below to set a new password:")
 (:email-reset-button . "Reset Password")
 (:email-reset-expiry . "This link will expire in 1 hour.")
 (:email-reset-ignore . "If you didn't request a password reset, you can safely ignore this email.")
 (:email-reminder-subject-due . "Time to review your Hiisi cards")
 (:email-reminder-subject-streak . "Keep your Hiisi streak going")
 (:email-reminder-cards-due . "cards ready for review")
 (:email-reminder-keep-going . "It has been a few days since your last review. Five minutes today is enough to keep what you have already learned from slipping.")
 (:email-reminder-button . "Review now")
 (:email-reminder-settings . "Manage reminder settings")
 (:email-reminder-preview-title . "Cards waiting for you")
 (:email-reminder-translation-label . "Translation")
 (:email-reminder-more-due-today . "more cards due today")
 (:email-trial-subject . "How is your Hiisi trial going?")
 (:email-trial-expiring . "Your free Hiisi trial ends tomorrow.")
 (:email-trial-feedback . "Are you enjoying Hiisi? Tell us what has helped you most.")
 (:email-trial-strengths . "You can translate real text, save the best items to flashcards, and learn with spaced repetition.")
 (:email-trial-reply . "Reply to this email and your message will go straight to the Hiisi team.")
 (:email-trial-button . "Choose a plan")
 (:email-trial-manage . "Manage subscription")
 (:email-trial-contact . "Email us")
 (:email-plan-nudge-subject . "Your translations are waiting")
 (:email-plan-nudge-title . "Your translations are waiting")
 (:email-plan-nudge-intro . "You signed up for Hiisi but haven't picked a plan yet.")
 (:email-plan-nudge-benefits-intro . "Here is what you get with a subscription:")
 (:email-plan-nudge-benefit-translations . "600 translations per month with grammar breakdowns")
 (:email-plan-nudge-benefit-flashcards . "Unlimited flashcards with spaced repetition")
 (:email-plan-nudge-benefit-decks . "Custom decks you can organize and share")
 (:email-plan-nudge-pricing . "Plans start at EUR 10/month, or save with the annual plan at EUR 100/year (two months free).")
 (:email-plan-nudge-feedback . "If something about Hiisi is not working for you, reply to this email. Your message goes straight to the Hiisi team.")
 (:email-plan-nudge-button . "Choose a plan")
 (:email-plan-nudge-unsubscribe . "Unsubscribe from these emails")
 (:email-plan-nudge-unsubscribe-done-title . "Plan emails turned off")
 (:email-plan-nudge-unsubscribe-done-body . "You will not receive further plan reminder emails.")
 (:email-plan-nudge-unsubscribe-invalid-title . "This link is not valid")
 (:email-plan-nudge-unsubscribe-invalid-body . "This unsubscribe link is missing, expired, or no longer valid.")
 (:email-invite-subject . "You have been invited to Hiisi")
 (:email-invite-title . "You have been invited to Hiisi")
 (:email-invite-intro . "You have been invited to use Hiisi for free, as a tester, valued friend, or both.")
 (:email-invite-details . "Use the button below to create your account and start exploring translations and flashcards.")
 (:email-invite-button . "Create account")
 (:email-invite-issue-reporting . "If something breaks or feels off, there is an issue reporting button at the bottom of each page.")
 (:email-issue-completed-subject . "Your Hiisi issue has been fixed")
 (:email-issue-completed-title . "Issue fixed")
 (:email-issue-completed-label . "Issue")
 (:email-issue-completed-followup . "Open Hiisi to check the fix or continue where you left off.")
 (:email-issue-completed-button . "Open Hiisi")
 (:email-issue-completed-open-link . "Open page")

 ;; Translation page
 (:translate-title . "Translate")
 (:landing-public-translate-title . "Try it here")
 (:translate-input-label . "Text to translate")
 (:translate-input-placeholder . "Enter text to translate...")
 (:translate-from . "Source language:")
 (:translate-to . "Target language:")
 (:translate-select-target-placeholder . "Select target language")
 (:translate-submit . "Translate")
 (:translate-auto-detect . "Any (Auto-detect)")
 (:translate-empty-state . "Translate a word or phrase to see the result, grammar breakdown, and study actions here.")
 (:translate-select-deck-placeholder . "Select deck (optional)")
 (:translate-new-deck . "New deck")
 (:translate-add-to-deck . "Add to deck")
 (:translate-bookmark . "Bookmark")
 (:translate-bookmarked . "Bookmarked")
 (:translate-retry . "Regenerate")
 (:translate-like-tooltip . "Good translation")
 (:translate-dislike-tooltip . "Bad translation - request a new one")
 (:translate-dislike-confirm . "This will generate a new translation. Continue?")
 (:pronunciation-label . "Pronunciation")
 (:pronunciation-show . "Show pronunciation")
 (:pronunciation-hide . "Hide pronunciation")
 (:grammar-term-examples . "Examples")
 (:grammar-term-related . "Related terms")
 (:grammar-term-modal-title . "Grammar term")
 (:grammar-term-empty . "Select a highlighted term to see details.")
 (:extension-login-required . "Log in to Hiisi before using the browser extension.")
 (:extension-session-invalid . "Your Hiisi session is no longer valid. Log in again.")
 (:extension-activation-required . "Activate your Hiisi account before using the browser extension.")
 (:extension-subscription-required . "Start a Hiisi trial before using the browser extension.")

 ;; Translation and Flashcards
 (:lang-auto . "Auto")
 (:lang-unknown . "?")
 (:lang-target . "Target")
 (:translate-deck-create-title . "Create New Deck")
 (:translate-deck-name-label . "Deck Name")
 (:translate-deck-name-placeholder . "e.g., Finnish Basics")
 (:translate-deck-description-label . "Description (optional)")
 (:translate-deck-cancel . "Cancel")
 (:translate-deck-create . "Create")
 (:translate-rate-label . "Rate translation")
 (:flashcards-delete . "Delete")
 (:flashcards-delete-confirm . "Are you sure you want to delete this flashcard?")
 (:flashcards-deck-search-placeholder . "Search decks...")
 (:flashcards-no-decks . "No decks yet. Create one first!")
 (:flashcards-deck-cancel . "Cancel")
 (:flashcards-recollection-tooltip . "Recollection: ~A")
 (:flashcards-recollection-poor . "Poor")
 (:flashcards-recollection-fair . "Fair")
 (:flashcards-recollection-normal . "Normal")
 (:flashcards-recollection-strong . "Strong")
 (:flashcards-recollection-very-strong . "Very Strong")

 ;; Flashcard review
 (:review-title . "Review")
 (:review-session-title . "Review Session")
 (:review-session-subtitle . "Practice your saved flashcards")
 (:review-selector-title . "Choose what to review")
 (:review-selector-subtitle . "Select a deck or language pair to focus your review session.")
 (:review-by-deck . "Review by Deck")
 (:review-by-language-pair . "Review by Language Pair")
 (:review-all-cards . "Review All Cards")
 (:review-cards-due . "cards due")
 (:review-deck-caught-up . "All caught up")
 (:review-all-caught-up . "All caught up!")

 (:review-no-cards . "No Cards to Review")
 (:review-no-cards-desc . "You don't have any flashcards due for review right now.")
 (:review-no-cards-hint . "Translate some text and click \"Save to Flashcards\" to build your deck!")
 (:review-start-translating . "Start Translating")
 (:review-click-reveal . "Click to reveal answer")
 (:review-grammar-breakdown . "Grammar Breakdown")
 (:review-how-well . "Did you recall it?")
 (:review-again . "No")
 (:review-hard . "Barely")
 (:review-good . "Yes")
 (:review-easy . "Easily")
 (:review-progress . "Card ~a of ~a")
 (:review-correct-count . "Correct")
 (:review-wrong-count . "Wrong")
 (:landing-mockup-forgot-detail . "1st person singular preterite of \"olvidar\" (to forget)")
 (:landing-mockup-keys-detail . "Possessive \"mis\" with feminine plural noun \"llaves\" (keys)")
 (:landing-mockup-home-detail . "Idiomatic \"en casa\" (at home) -- no article needed")
 (:landing-mockup-possession-note . "In Spanish, the preterite marks completed past actions. The subject pronoun is usually dropped because the verb ending already identifies the speaker.")
 (:landing-mockup-children-detail . "Nominative plural of \"Kind\" (child) -- plural adds -er")
 (:landing-mockup-played-detail . "3rd person plural preterite of \"spielen\" (to play)")
 (:landing-mockup-garden-detail . "Dative: \"in dem\" contracts to \"im\", with masculine noun \"Garten\" (garden)")
 (:landing-mockup-czech-note . "German uses the preterite in written narrative. \"Im\" is a contraction of \"in\" + \"dem\" (dative article).")
 (:landing-mockup-deck-title . "Italian Basics")
 (:landing-mockup-share-deck . "Share deck")
 (:review-complete . "Session Complete!")
 (:review-complete-msg . "You reviewed ~a cards")
 (:review-again-btn . "Review Again")
 (:review-translate-more . "Translate More")
 (:review-streak . "day streak")

 ;; Dashboard
 (:dashboard-title . "Dashboard")
 (:dashboard-welcome-title . "Translate your first text")
 (:dashboard-welcome-subtitle . "Translate a useful phrase, save it to a deck, and review it when it matters.")
 (:dashboard-take-quick-tour . "Take a quick tour")
 (:dashboard-cards-due . "Cards Due")
 (:dashboard-total-cards . "Total Cards")
 (:dashboard-mastered-cards . "Mastered Cards")
 (:dashboard-subscription . "Subscription")
 (:dashboard-subscribed-until . "Subscribed until")
 (:dashboard-not-subscribed . "Not subscribed")
 (:dashboard-recent . "Recent Translations")
 (:dashboard-no-translations . "No translations yet")
 (:dashboard-streak . "Review Streak")
 (:dashboard-days . "days")
 (:dashboard-all-caught-up . "All caught up!")
 (:dashboard-all-caught-up-hint . "Translate more to build your collection.")
 (:dashboard-getting-started . "Getting Started")
 (:dashboard-tip-1 . "Translate text you want to learn")
 (:dashboard-tip-2 . "Click \"Save to Flashcards\" on translations you want to remember")
 (:dashboard-tip-3 . "Review your flashcards regularly - spaced repetition helps you remember long-term")
 (:dashboard-tip-4 . "Rate honestly - it helps the algorithm schedule your reviews optimally")

 ;; Account
 (:account-title . "Account")
 (:account-subtitle . "Review your profile, subscription, reminders, exports, and deletion settings here.")
 (:account-profile-subtitle . "Keep your display name and email details up to date.")
 (:account-export-subtitle . "Download a copy of your saved translations, decks, and review data.")
 (:account-deletion-title . "Account Deletion")
 (:account-deletion-scheduled . "Your account is scheduled for deletion on ~A.")
 (:account-deletion-cancel-hint . "You can cancel before this date to keep your account.")
 (:account-deletion-cancel . "Cancel deletion")
 (:account-deletion-request . "You can request account deletion at any time. Deletion is scheduled 14 days from confirmation. If you change your mind, please contact support before the 14-day period ends.")
 (:account-deletion-confirm . "Schedule account deletion for 14 days from now?")
 (:account-deletion-schedule . "Schedule deletion")
 (:account-reminders-title . "Email Reminders")
 (:account-reminders-subtitle . "Choose whether Hiisi may email you when there is something to review.")
 (:account-reminders-opt-out . "Opt out of review/continuation reminders")
 (:account-reminders-save . "Save preferences")

 ;; Subscription
 (:subscribe-title . "Simple Pricing")
 (:subscribe-choose-plan . "Choose Your Plan")
 (:subscribe-start-today . "Start learning today with a 14-day free trial")
 (:subscribe-monthly . "Monthly")
 (:subscribe-annual . "Annual")
 (:subscribe-founder-member . "Founding Member")
 (:subscribe-monthly-price . "€10")
 (:subscribe-annual-price . "€100")
 (:subscribe-founder-price . "€79")
 (:subscribe-per-month . "/month")
 (:subscribe-per-year . "/year")
 (:subscribe-monthly-desc . "600 translations a month. Unlimited flashcards, decks, and reviews.")
 (:subscribe-unlimited-flashcards . "Unlimited flashcards")
 (:subscribe-grammar-explanations . "Grammar explanations")
 (:subscribe-spaced-repetition . "Spaced repetition")
 (:subscribe-annual-desc . "Everything in Monthly. Two months free.")
 (:subscribe-founder-lock . "Price locked in while your subscription stays active.")
 (:subscribe-founder-badge . "Limited offer")
 (:subscribe-founder-limit . "Limited to the first 100 members")
 (:subscribe-manage . "Manage Subscription")
 (:subscribe-activated . "Subscription Activated!")
 (:subscribe-thank-you . "Your subscription is active. You can manage billing and buy more translations here.")
 (:subscribe-start-learning . "Start Learning")
 (:subscribe-management . "Subscription Management")
 (:subscribe-active . "Active Subscription")
 (:subscribe-preapproved-access . "Pre-approved access")
 (:subscribe-status . "Status:")
 (:subscribe-status-active . "Active")
 (:subscribe-status-preapproved . "Pre-approved")
 (:subscribe-preapproved-detail . "This account uses pre-approved access managed by Hiisi.")
 (:subscribe-days-remaining . "Days remaining:")
 (:subscribe-renews-on . "Renews on:")
 (:subscribe-no-subscription . "No Active Subscription")
 (:subscribe-access-features . "Choose a plan to unlock full access and manage billing in one place.")
 (:subscribe-view-plans . "View Plans")
 (:subscribe-faq-title . "Frequently Asked Questions")
 (:subscribe-faq-trial-q . "What happens after the free trial?")
 (:subscribe-faq-trial-a . "Your 14-day trial does not require a card. When it ends, choose a paid plan to keep full access.")
 (:subscribe-faq-cancel-q . "Can I cancel anytime?")
 (:subscribe-faq-cancel-a . "Yes! You can cancel your subscription at any time. You'll keep access until the end of your billing period.")
 (:subscribe-faq-payment-q . "What payment methods do you accept?")
 (:subscribe-faq-payment-a . "We accept all major credit cards and debit cards through our payment partner Polar.sh.")
 (:subscribe-copyright . "Lambda Symbolics OÜ © 2026.")
(:subscribe-checkout-unavailable . "Checkout is temporarily unavailable. Please try again.")
(:subscribe-portal-unavailable . "Subscription management is temporarily unavailable. Please try again.")
(:subscribe-founder-sold-out . "Founding offer sold out")
(:subscribe-founder-unavailable . "Founding offer is not available right now.")
(:subscribe-checkout-cta . "Subscribe")

 ;; Generic status

 (:error-generic . "Something went wrong")
(:error-invalid-request . "Invalid request data.")
(:error-not-found . "Requested resource not found.")
(:error-forbidden . "You do not have access to this.")
(:error-rate-limited . "Please wait a moment and try again.")
 (:error-text-too-long . "Text is too long. Maximum translation length is 120 characters.")
 (:error-input-too-long . "Input Too Long")
 (:error-unknown-source-lang . "The source language you selected is not supported.")
 (:error-unknown-target-lang . "The target language you selected is not supported.")
 (:error-unknown-language . "Unknown Language")
 (:error-translation-unavailable . "Translation service is temporarily unavailable. Please try again in a moment.")
 (:error-translation-failed . "Translation Failed")
 (:error-translation-retry . "Unable to generate a translation after multiple attempts. Please try rephrasing your text.")
 (:error-quota-exceeded . "Translation Limit Reached")
 (:error-quota-exceeded-detail . "You've used all your translations for this month. Your quota resets automatically each month.")
 (:quota-low-warning . "Only ~A translations left. Consider purchasing more.")
 (:top-up-button . "Buy More Translations")
 (:top-up-price . "€5")
 (:top-up-amount . "300 translations")
(:review-session-expired . "Your review session has expired. Please start a new session.")

 (:error-session-expired . "Your session expired. Please log in again.")
 (:error-session-invalid . "Your session is no longer valid. Please log in again.")
 (:error-custom-flashcard-generation . "We couldn't generate the explanation. Please try again.")
 ;; Institutions
 (:institutions-page-title . "Hiisi for Schools and Universities")
 (:institutions-hero-title . "Language teaching tools built for the classroom")
 (:institutions-hero-subtitle . "Give your students shareable decks, grammar-aware practice, and steady review routines that fit real teaching.")
 (:institutions-section-title . "Why institutions use Hiisi")
 (:institutions-section-body . "Hiisi helps teachers turn lesson material into guided study students can actually keep up with. Build decks for a course, share them with a link, and support vocabulary and grammar practice without extra administrative overhead.")
 (:institutions-benefit-1 . "Shareable decks and custom tasks that match your curriculum.")
 (:institutions-benefit-2 . "Student likes and dislikes help the strongest translations rise for common classroom phrases.")
 (:institutions-benefit-3 . "Grammar breakdowns and spaced review support more than memorizing isolated word lists.")
 (:institutions-benefit-4 . "Teacher-minded support from someone who listens carefully and cares about classroom needs.")
 (:institutions-request-title . "Start a conversation")
 (:institutions-request-subtitle . "Tell us about your institution, your languages, and the kind of teaching support you need. We will get back to you within a week.")
 (:institutions-aside-title . "What happens next")
 (:institutions-aside-body . "We review your needs and respond within a week to discuss access and setup for your institution.")
 (:institutions-field-name . "Institution Name")
 (:institutions-field-name-placeholder . "Your University")
 (:institutions-field-contact-name . "Contact Name")
 (:institutions-field-contact-name-placeholder . "Your name")
 (:institutions-field-contact-email . "Contact Email")
 (:institutions-field-contact-email-placeholder . "you@university.edu")
 (:institutions-field-domains . "Email Domains")
 (:institutions-field-domains-placeholder . "university.edu, cs.university.edu")
 (:institutions-field-domains-help . "Comma-separated list of email domains for your institution")
 (:institutions-field-notes . "Additional Information")
 (:institutions-field-notes-placeholder . "Estimated number of students, preferred billing cycle, any special requirements...")
 (:institutions-submit . "Submit Inquiry")
 (:institutions-success-title . "Thank You - Hiisi for Schools and Universities")
 (:institutions-success-heading . "Thank You!")
 (:institutions-success-body . "We have received your inquiry. We will review your institution's needs and get back to you within a week.")
 (:institutions-success-back . "Back to Home")

 ;; Footer
 (:footer-privacy . "Privacy Policy")
 (:footer-terms . "Terms of Service")

 ;; Early software notice
 (:early-software-notice . "Hiisi is in early development. Found a bug or have a suggestion?")

 ;; Privacy Policy
 (:privacy-title . "Privacy Policy")
 (:privacy-updated . "Last updated: January 2026")
 (:privacy-who-title . "Who We Are")
 (:privacy-who-body . "Hiisi is operated by Lambda Symbolics OÜ, a company registered in Estonia. As an Estonian company, we comply with the European Union's General Data Protection Regulation (GDPR).")
 (:privacy-collect-title . "Data We Collect")
 (:privacy-collect-intro . "We collect the following information when you use Hiisi:")
 (:privacy-collect-account-key . "Account information: ")
 (:privacy-collect-account-val . "Email address, display name, and a securely hashed password.")
 (:privacy-collect-learning-key . "Learning data: ")
 (:privacy-collect-learning-val . "Your translations, saved flashcards, and review history.")
 (:privacy-collect-usage-key . "Usage data: ")
 (:privacy-collect-usage-val . "Basic server logs for security and debugging purposes.")
 (:privacy-use-title . "How We Use Your Data")
 (:privacy-use-auth-key . "Authentication: ")
 (:privacy-use-auth-val . "To verify your identity and secure your account.")
 (:privacy-use-service-key . "Service delivery: ")
 (:privacy-use-service-val . "To provide translations and manage your flashcard collection.")
 (:privacy-use-ai-key . "AI translations: ")
 (:privacy-use-ai-val . "Your translation requests are sent to OpenRouter to generate responses. OpenRouter may route requests to the configured model provider. See OpenRouter's privacy policy for how they handle this data.")
 (:privacy-third-title . "Third-Party Services")
 (:privacy-third-intro . "We use the following third-party services:")
 (:privacy-third-openrouter-key . "OpenRouter: ")
 (:privacy-third-openrouter-val . "For automatic translation requests.")
 (:privacy-third-mailgun-key . "Mailgun: ")
 (:privacy-third-mailgun-val . "For sending account activation and transactional emails.")
 (:privacy-third-polar-key . "Polar.sh: ")
 (:privacy-third-polar-val . "For subscription payment processing.")
 (:privacy-cookies-title . "Cookies")
 (:privacy-cookies-intro . "We use only essential cookies:")
 (:privacy-cookies-auth-key . "Authentication token: ")
 (:privacy-cookies-auth-val . "A secure, HTTP-only cookie to keep you logged in.")
 (:privacy-cookies-lang-key . "Language preference: ")
 (:privacy-cookies-lang-val . "To remember your preferred UI language.")
 (:privacy-retention-title . "Data Retention")
 (:privacy-retention-body . "Your data is stored as long as you maintain an account. When you request deletion, your account is scheduled for deletion in 14 days.")
 (:privacy-rights-title . "Your Rights (GDPR)")
 (:privacy-rights-intro . "Under GDPR, you have the right to:")
 (:privacy-rights-access . "Access your personal data")
 (:privacy-rights-export . "Export your data (available at /app/api/export)")
 (:privacy-rights-correct . "Request correction of inaccurate data")
 (:privacy-rights-delete . "Request deletion of your account and data")
 (:privacy-rights-object . "Object to processing of your data")
 (:privacy-rights-contact . "To exercise these rights, contact us at")
 (:privacy-contact-title . "Contact")
 (:privacy-contact-intro . "For privacy-related inquiries:")
 (:privacy-contact-email-label . "Email: ")
 (:privacy-address-1 . "Lambda Symbolics OÜ")
 (:privacy-address-2 . "Harju maakond, Tallinn, Kesklinna linnaosa, Tornimäe tn 5, 10145")

 ;; Terms of Service
 (:terms-title . "Terms of Service")
 (:terms-updated . "Last updated: January 2026")
 (:terms-1-title . "1. Service Description")
 (:terms-1-body . "Hiisi is a language learning application that provides automatic translations with grammatical explanations and spaced repetition flashcards. The service is operated by Lambda Symbolics OÜ.")
 (:terms-2-title . "2. Account Registration")
 (:terms-2-body . "To use Hiisi, you must create an account with a valid email address. You are responsible for maintaining the security of your account credentials.")
 (:terms-3-title . "3. Subscription and Payments")
 (:terms-3-body . "Hiisi offers paid subscription plans (monthly and annual). Subscriptions are processed through Polar.sh.")
 (:terms-3-list-1 . "Subscriptions auto-renew unless cancelled before the renewal date.")
 (:terms-3-list-2 . "Refunds are provided in accordance with applicable consumer protection laws.")
 (:terms-3-list-3 . "Non-payment results in loss of access to premium features.")
 (:terms-4-title . "4. Acceptable Use")
 (:terms-4-intro . "You agree not to:")
 (:terms-4-list-1 . "Use the service for any illegal purpose")
 (:terms-4-list-2 . "Attempt to circumvent usage limits or security measures")
 (:terms-4-list-3 . "Share your account credentials with others")
 (:terms-4-list-4 . "Use automated tools to access the service in a way that degrades performance for others")
 (:terms-5-title . "5. Content and Intellectual Property")
 (:terms-5-body-1 . "Translations generated by Hiisi are created automatically and may not be unique. You may use your translations and flashcards for any personal purpose, but you do not hold exclusive authorship rights over automatically generated content.")
 (:terms-5-body-2 . "The Hiisi application, branding, and original content remain the property of Lambda Symbolics OÜ.")
 (:terms-6-title . "6. Service Availability")
 (:terms-6-intro . "Hiisi is provided on an \"as-is\" basis. We do not guarantee:")
 (:terms-6-list-1 . "Uninterrupted or error-free service")
 (:terms-6-list-2 . "Accuracy of automatically generated translations")
 (:terms-6-list-3 . "Availability of specific features")
 (:terms-6-body . "We may modify or discontinue features at any time.")
 (:terms-7-title . "7. Limitation of Liability")
 (:terms-7-body-1 . "To the maximum extent permitted by law, Lambda Symbolics OÜ shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of Hiisi.")
 (:terms-7-body-2 . "Our total liability shall not exceed the amount you paid for the service in the 12 months preceding the claim.")
 (:terms-8-title . "8. Account Termination")
 (:terms-8-body-1 . "We may suspend or terminate your account if you violate these terms. You may request account deletion at any time through the application.")
 (:terms-8-body-2 . "Upon deletion request, your account is scheduled for deletion in 14 days.")
 (:terms-9-title . "9. Changes to Terms")
 (:terms-9-body . "We may update these terms from time to time. Continued use of Hiisi after changes constitutes acceptance of the new terms.")
 (:terms-10-title . "10. Governing Law")
 (:terms-10-body . "These terms are governed by the laws of Estonia. Any disputes shall be resolved in the courts of Estonia.")
 (:terms-contact-title . "Contact")
 (:terms-contact-intro . "For questions about these terms:")
 (:terms-contact-email-label . "Email: ")
 (:terms-address-1 . "Lambda Symbolics OÜ")
 (:terms-address-2 . "Harju maakond, Tallinn, Kesklinna linnaosa, Tornimäe tn 5, 10145")

 ;; Decks
 (:decks-title . "Decks")
 (:decks-subtitle . "Create custom decks and share them with others.")
 (:decks-create-title . "Create Deck")
 (:decks-name-placeholder . "Deck name")
 (:decks-desc-placeholder . "Description")
 (:decks-create-btn . "Create deck")
 (:decks-edit-title . "Edit deck")
 (:decks-edit-btn . "Edit deck")
 (:decks-update-btn . "Save changes")
 (:decks-default-badge . "Automatic")
 (:decks-default-description . "This deck is managed automatically for this language pair.")
 (:decks-default-readonly . "Automatic decks have fixed names and descriptions.")
 (:decks-delete-btn . "Delete deck")
 (:decks-delete-confirm . "Delete this deck?")
 (:decks-error-name-required . "Deck name is required.")
 (:decks-error-name-too-long . "Deck name must be at most ~A characters.")
 (:decks-error-desc-too-long . "Deck description must be at most ~A characters.")
 (:decks-error-default-readonly . "Automatic decks cannot be edited.")
 (:decks-error-default-delete-forbidden . "Automatic decks cannot be deleted.")
 (:decks-your-title . "Your Decks")
 (:decks-col-updated . "Updated")
 (:decks-no-decks . "No decks yet.")
 (:decks-open-btn . "Open")
 (:decks-no-desc . "No description.")
 (:decks-share-title . "Share Link")
 (:decks-share-info . "Anyone with this link can import the deck:")
 (:decks-share-copy . "Copy link")
 (:decks-share-copied . "Copied")
 (:decks-add-from-flashcards-title . "Add translations")
 (:decks-add-from-flashcards-info . "Pick a flashcard to add its translation to this deck.")
 (:decks-open-flashcards . "Add from flashcards")
 (:decks-filter-from . "From language")
 (:decks-filter-to . "To language")
 (:decks-filter-any . "Any language")
 (:decks-filter-include-assigned . "Include flashcards already in a deck")
 (:decks-flashcards-add . "Add")
 (:decks-flashcards-added . "Added")
 (:decks-flashcards-in-deck . "In another deck")
 (:decks-flashcards-empty . "No flashcards match these filters.")
 (:decks-items-title . "Deck Items")
 (:decks-col-original . "Original")
 (:decks-col-translated . "Translated")
 (:decks-col-lang . "Lang To")
 (:decks-no-items . "No items yet.")
 (:decks-share-page-title . "Share Deck")
 (:decks-share-preview . "Preview and import this deck.")
 (:decks-import-title . "Import")
 (:decks-import-btn . "Import deck")
 (:starter-decks-title . "Library")
 (:starter-decks-subtitle . "Import ready-made decks provided by Hiisi and the community.")
 (:starter-decks-marketplace-btn . "Library")
 (:starter-decks-explanation-language . "Explanation language")
 (:starter-decks-search-label . "Search")
 (:starter-decks-source-label . "Source")
 (:starter-decks-source-all . "All decks")
 (:starter-decks-search-placeholder . "Search the Library")
 (:starter-decks-apply-filters . "Apply filters")
 (:starter-decks-select-triplet-hint . "Choose source and target languages to browse matching decks.")
 (:starter-decks-official-badge . "Official")
 (:starter-decks-community-badge . "Community")
 (:starter-decks-by-hiisi . "By Hiisi")
 (:starter-decks-preview-btn . "Preview")
 (:starter-decks-card-count . "~A cards")
 (:starter-decks-no-results . "No decks match these filters.")
 (:starter-decks-source-cards-title . "Cards in this deck")
 (:starter-decks-sample-title . "Sample cards")
 (:starter-decks-generating . "Generating deck...")
 (:starter-decks-generating-detail . "This deck is being generated for your language triplet. Leave this page open or come back in a moment.")
 (:starter-decks-generation-failed . "Generation failed")
 (:starter-decks-generation-failed-detail . "The last generation attempt failed. Try importing the deck again.")
 (:starter-decks-login-detail . "Log in to import this deck into your collection.")
 (:starter-decks-subscribe-btn . "See plans")
 (:starter-decks-subscribe-detail . "Library decks are available with an active subscription or trial.")
 (:library-submit-title . "Submit to Library")
 (:library-submit-intro . "Send this deck to the Library for admin review before publication.")
 (:library-submit-btn . "Submit deck")
 (:library-submit-approved . "Approved for the Library")
 (:library-submit-approved-detail . "This deck is published in the Library.")
 (:library-submit-pending . "Under review")
 (:library-submit-pending-detail . "This deck has been submitted and is waiting for admin review.")
 (:library-submit-rejected . "Needs changes before publication")
 (:library-submit-rejected-detail . "This submission was rejected. Update the deck and submit it again.")
 (:library-error-empty . "Add at least one card before submitting this deck to the Library.")
 (:library-error-missing-triplet . "Every card in a Library submission must have a complete language triplet.")
 (:library-error-mixed-triplet . "All cards in a Library submission must share the same language triplet.")
 (:starter-deck-topic-greetings-title . "Greetings and introductions")
 (:starter-deck-topic-greetings-description . "Hello, names, polite basics, and first-meeting phrases.")
 (:starter-deck-topic-travel-title . "Essential travel")
 (:starter-deck-topic-travel-description . "Stations, tickets, prices, help, and getting around.")
 (:starter-deck-topic-numbers-title . "Numbers and prices")
 (:starter-deck-topic-numbers-description . "Counting, totals, prices, floors, and everyday quantities.")
 (:starter-deck-topic-time-title . "Time and dates")
 (:starter-deck-topic-time-description . "Days, months, appointments, clock time, and relative dates.")
 (:starter-deck-topic-food-title . "Restaurant and food")
 (:starter-deck-topic-food-description . "Ordering, dietary needs, drinks, the bill, and everyday meals out.")
 (:starter-deck-topic-emergency-title . "Emergency and health")
 (:starter-deck-topic-emergency-description . "Doctors, pharmacies, symptoms, body parts, and urgent help.")
 (:starter-deck-topic-directions-title . "Directions and transportation")
 (:starter-deck-topic-directions-description . "Turning, stops, tickets, platforms, and getting around town.")
 (:starter-deck-topic-school-title . "School and education")
 (:starter-deck-topic-school-description . "Classes, homework, exams, classroom items, and everyday school life.")
 (:starter-deck-topic-university-title . "University and studies")
 (:starter-deck-topic-university-description . "Lectures, seminars, majors, assignments, and everyday campus life.")

 ;; Flashcards management page
 (:flashcards-title . "My Flashcards")
 (:flashcards-subtitle . "All your saved flashcards in one place. Search, organize, and manage.")
 (:flashcards-search-placeholder . "Search flashcards...")
 (:flashcards-filter-button . "Filters")
 (:flashcards-filter-title . "Filter flashcards")
 (:flashcards-filter-recollection . "How well you know them")
 (:flashcards-filter-any-recollection . "Any familiarity")
 (:flashcards-hide-perfected . "Hide perfected cards")
 (:flashcards-col-original . "Original")
 (:flashcards-col-translated . "Translation")
 (:flashcards-no-cards . "No flashcards yet. Start translating to create some!")
 (:flashcards-image-label . "Image")
 (:flashcards-image-upload . "Upload image")
 (:flashcards-image-replace . "Replace image")
 (:flashcards-image-remove . "Remove image")
 (:flashcards-pagination-label . "Flashcards pages")
 (:flashcards-pagination-status . "Page ~A of ~A")
 (:flashcards-pagination-previous . "Previous")
 (:flashcards-pagination-next . "Next")

 ;; Landing page (redesign)
 (:landing-hero-headline . "Every word explained. Every review scheduled. Fifteen languages.")
 (:landing-hero-subheadline . "Hiisi is the translator that teaches you grammar as you read, and the flashcard app that builds itself from what you actually translate.")
 (:landing-hero-trust-line . "14 days free. No card required.")
 (:landing-credibility-languages . "15 languages")
 (:landing-credibility-ai . "Every word explained")
 (:landing-credibility-srs . "Spaced repetition built in")
 (:landing-languages-title . "Languages we support")
 (:landing-step-1-title . "Paste a sentence")
 (:landing-step-1-desc . "Any length, any of 15 languages. Get the translation plus a breakdown of every word's grammar.")
 (:landing-step-2-title . "Save what's worth keeping")
 (:landing-step-2-desc . "One click turns a translation into a flashcard, with the original sentence kept as context.")
 (:landing-step-3-title . "Review at the right moment")
 (:landing-step-3-desc . "Spaced repetition with SM-2, the same algorithm behind Anki. Cards you struggle with come back sooner.")
 (:landing-feature-grammar-title . "Every word explained, in your language")
 (:landing-feature-grammar-desc . "Translations come with case, gender, aspect, and mood laid out word by word. Finnish partitive, Czech animacy, Polish aspect, German dative contractions, all labeled and linked to a grammar reference.")
 (:landing-feature-srs-title . "The spaced repetition habit, automated")
 (:landing-feature-srs-desc . "The SM-2 spaced repetition algorithm adapts to your performance. Cards you struggle with appear more often. Cards you know well fade back.")
 (:landing-feature-share-title . "Your decks, or the community's")
 (:landing-feature-share-desc . "Organize flashcards into themed decks. Share any deck with a link, or browse the community library for decks others have shared.")
 (:landing-pricing-trial-note . "14-day free trial included")
 (:landing-pricing-monthly-after . "14-day free trial, then ~A/month")
 (:landing-pricing-annual-after . "14-day free trial, then ~A/year")
 (:landing-faq-title . "Frequently Asked Questions")
 (:landing-faq-trial-cap-q . "How many translations do I get during the trial?")
 (:landing-faq-trial-cap-a . "You get 200 translations during your 14-day trial. After subscribing, you get 600 per month.")
 (:landing-final-cta-title . "Your first sentence takes five seconds.")
 (:landing-final-cta-subtitle . "Paste anything in Finnish, Czech, Polish, or any of twelve other languages. See what Hiisi does with it. Fourteen days free.")

 ;; Trial status (in-app)
 (:trial-status . "Free Trial")
 (:error-trial-quota-exceeded . "Trial translation limit reached")
 (:error-trial-quota-detail . "You have used all 200 trial translations. Subscribe to continue learning.")

 ;; Custom flashcards
 (:custom-flashcard-create-title . "Create Flashcard")
 (:custom-flashcard-edit-title . "Edit Flashcard")
 (:custom-flashcard-original . "Original Text")
 (:custom-flashcard-translated . "Translation")
 (:custom-flashcard-lang-from . "Source Language")
 (:custom-flashcard-lang-to . "Target Language")
 (:custom-flashcard-note . "Educational Note")
 (:custom-flashcard-forms . "Grammar Breakdown")
 (:custom-flashcard-form-term . "Term")
 (:custom-flashcard-form-explanation . "Explanation")
 (:custom-flashcard-add-form . "Add Grammar Term")
 (:custom-flashcard-remove-form . "Remove")
 (:custom-flashcard-ai-fill . "Fill with AI")
 (:custom-flashcard-create-btn . "Create Flashcard")
 (:custom-flashcard-update-btn . "Save Changes")

  ;; Newsletter
  (:newsletter-email-label . "Email address")
  (:newsletter-developer-label . "I am a developer")
  (:newsletter-developer-hint . "receive technical updates")
  (:landing-newsletter-title . "Get Hiisi updates.")
  (:landing-newsletter-body . "Join the newsletter for product updates, new language support, starter decks, and occasional founder offers.")
  (:landing-newsletter-fine-print . "No spam. Product updates only.")
  (:landing-newsletter-button . "Join newsletter")
  (:newsletter-unsubscribe-page-title . "Unsubscribe from Hiisi Newsletter")
  (:newsletter-unsubscribe-title . "Unsubscribe")
  (:newsletter-unsubscribe-subtitle . "Enter your email to unsubscribe from Hiisi updates.")
  (:newsletter-unsubscribe-button . "Unsubscribe")
  (:newsletter-feedback-email-required . "Please enter your email address.")
  (:newsletter-feedback-email-invalid . "Please enter a valid email address.")
  (:newsletter-feedback-already-signed-up . "You are already signed up. We will keep you posted!")
  (:newsletter-feedback-signed-up . "You are on the list! We will send occasional Hiisi updates.")
  (:newsletter-feedback-unsubscribed . "If this email was subscribed, it has been removed from Hiisi updates.")
  (:newsletter-feedback-generic-error . "Something went wrong. Please try again.")

  ;; Issue reporting
 (:issues-open-button . "Report a bug")
 (:issues-modal-title . "Report an Issue")
 (:issues-modal-subtitle . "Describe what went wrong. We will include your current page automatically.")
 (:issues-title-label . "Short title")
 (:issues-title-placeholder . "Brief summary of the problem")
 (:issues-message-label . "What happened?")
 (:issues-message-placeholder . "Please include steps to reproduce, expected behavior, and what happened instead.")
 (:issues-submit . "Submit Issue")
 (:issues-cancel . "Cancel")
 (:issues-success . "Your issue report was sent. We'll review it as soon as we can.")
 (:issues-error-required . "Please describe the issue before submitting.")
 (:issues-error-title-too-long . "Issue title is too long. Please keep it under 160 characters.")
 (:issues-error-too-long . "Issue text is too long. Please keep it under 4000 characters.")
 (:issues-error-rate-limit . "Too many reports from this source. Please wait and try again later.")
 (:issues-error-generic . "Issue report could not be submitted. Please try again.")

)
