;;; Spanish translations
;;; This file should contain all keys from en.lisp

(
 ;; Language metadata (used for language picker)
 (:lang-name . "Español")
 (:lang-flag . "🇪🇸")

 ;; Language modal (first-visit language selection)
 (:lang-modal-title . "Elige tu idioma")
 (:lang-modal-subtitle . "Selecciona tu idioma preferido para la interfaz:")

 ;; Navigation
 (:nav-translate . "Traducir")
 (:nav-review . "Repasar")
 (:nav-flashcards . "Mis tarjetas")
 (:nav-dashboard . "Panel")
 (:nav-decks . "Mazos")
 (:nav-logout . "Cerrar sesión")
 (:nav-home . "Inicio")
 (:nav-pricing . "Precios")
 (:nav-institutions . "Para instituciones")
 (:nav-export-data . "Exportar datos")
 (:nav-open-navigation . "Abrir navegación")
 (:theme-light . "Claro")
 (:theme-dark . "Oscuro")

 ;; App title and branding
 (:app-title . "Hiisi - Aprendizaje de idiomas")

 ;; Landing page
 (:landing-learn-more . "Más información")
 (:landing-how-it-works . "Cómo funciona")
 (:landing-start-trial . "Iniciar prueba gratuita")
 (:landing-best-value . "Mejor valor")

 ;; Auth pages
 (:auth-register . "Registrarse")
 (:auth-login . "Iniciar sesión")
 (:auth-email . "Correo electrónico")
 (:auth-password . "Contraseña")
 (:auth-password-again . "Confirmar contraseña")
 (:auth-display-name . "Nombre para mostrar")
 (:auth-register-title . "Regístrate en Hiisi")
 (:auth-register-subtitle . "Crear una cuenta nueva")
 (:auth-login-title . "Iniciar sesión en Hiisi")
 (:auth-login-subtitle . "Ingresa tus credenciales")
 (:auth-login-invalid-credentials . "Correo o contrasena incorrectos.")
 (:auth-login-rate-limited . "Demasiados intentos de inicio de sesion. Espera unos minutos e intentalo de nuevo.")
(:auth-register-rate-limited . "Demasiados intentos de registro. Espera unos minutos e inténtalo de nuevo.")
(:auth-email-invalid . "Introduce un correo electrónico válido.")
(:auth-password-too-short . "La contraseña debe tener al menos 8 caracteres.")
(:auth-passwords-mismatch . "Las contraseñas no coinciden.")
(:auth-display-name-invalid . "El nombre visible debe tener entre 1 y 100 caracteres.")
(:auth-register-email-exists . "Ya existe una cuenta con este correo electrónico.")
(:auth-register-unavailable . "El registro está temporalmente no disponible. Inténtalo de nuevo más tarde.")
(:auth-register-plan-required . "Elige un plan antes de crear una cuenta.")
(:auth-preapproved-email-unrecognized . "Usa la dirección de correo de tu invitación o elige un plan antes de crear una cuenta.")
(:auth-institution-register . "¿Vienes de una institución?")
(:auth-institution-stage-title . "Acceso institucional")
(:auth-institution-stage-subtitle . "Usa el correo de tu escuela o universidad. Las cuentas elegibles se desbloquean a través de la institución tras verificar el correo.")
(:auth-institution-title . "Regístrate a través de tu institución")
(:auth-institution-subtitle . "Usa el correo de tu escuela o universidad. Si tu institución ya está configurada en Hiisi, tu cuenta se desbloqueará tras verificar el correo; la prueba individual de 14 días es para el registro con un plan personal.")
(:auth-institution-benefit-email . "Usa la dirección de correo de tu escuela o universidad.")
(:auth-institution-benefit-access . "Las cuentas elegibles reciben acceso institucional tras verificar el correo.")
(:auth-institution-benefit-fallback . "Si no se reconoce el dominio, elige un plan individual o pide a tu institución que contacte con Hiisi.")
(:auth-see-included . "Ver qué está incluido")
(:auth-institution-check-access . "Comprobar acceso")
(:auth-institution-email-eligible-title . "Acceso institucional confirmado")
(:auth-institution-email-eligible-detail . "Continúa con este correo para crear tu cuenta. El acceso se desbloqueará tras verificar el correo.")
(:auth-institution-change-email . "Usar otro correo")
(:auth-institution-outcome-note . "Si tu escuela o universidad proporciona acceso a Hiisi, tu cuenta se desbloquea tras verificar el correo. Si el dominio no es elegible, elige un plan personal para iniciar la prueba de 14 días.")
(:auth-institution-personal-plan-link . "Ver planes personales")
(:auth-institution-domain-unrecognized . "Todavía no reconocemos ese dominio de correo institucional. Elige un plan personal para iniciar la prueba de 14 días, o pide a tu institución que contacte con Hiisi.")
(:subscribe-institution-callout-title . "¿Usas Hiisi a través de una escuela o universidad?")
(:subscribe-institution-callout-body . "Regístrate con tu correo institucional y Hiisi desbloqueará el acceso automáticamente si tu institución ya está configurada.")
(:auth-activation-email-send-failed . "No se pudo enviar el correo de activación. Inténtalo de nuevo.")
 (:auth-forgot-password . "¿Olvidaste tu contraseña?")
 (:auth-no-account . "¿No tienes cuenta?")
 (:auth-have-account . "¿Ya tienes cuenta?")
 (:auth-google . "Google")
 (:auth-google-login-failed . "El inicio de sesión con Google falló. Inténtalo de nuevo.")
 (:auth-account-created . "¡Cuenta creada!")
 (:auth-check-email . "Revisa tu correo electrónico para el enlace de activación.")
 (:auth-redirect-login . "Redirigiendo al inicio de sesión en")
 (:auth-seconds . "segundos...")
 (:auth-go-now . "Ir ahora")
 (:auth-not-activated . "Cuenta no activada")
 (:auth-activate-title . "¡Activa tu cuenta!")
 (:auth-activated . "¡Cuenta activada!")
 (:auth-activated-message . "Tu cuenta ha sido activada. Ya puedes usar Hiisi.")
 (:auth-redirecting . "Redirigiendo en")
 (:auth-go-to-app . "Ir a la app")
 (:onboarding-title . "Cómo funciona Hiisi")
 (:onboarding-subtitle . "Traduce texto real, inspecciona la gramática, guarda elementos útiles y repásalos más tarde.")
 (:onboarding-translate-detail . "Empieza con texto real. Hiisi devuelve la traducción, las formas alineadas y las siguientes acciones de estudio en un solo lugar.")
 (:onboarding-grammar-detail . "Abre el desglose gramatical para ver qué formas se corresponden en la frase y qué función cumple cada parte.")
 (:onboarding-review-detail . "Guarda las traducciones útiles y repásalas más tarde con repetición espaciada para que permanezcan en la memoria a largo plazo.")
 (:onboarding-decks-detail . "Agrupa los elementos útiles en mazos, compártelos con otras personas y mantén junto el material relacionado.")
 (:onboarding-back . "Atrás")
 (:onboarding-next . "Siguiente")
 (:onboarding-skip . "Omitir guía")
 (:auth-resend-title . "Reenviar correo de activación")
 (:auth-resend-subtitle . "Ingresa tu correo para recibir un nuevo enlace de activación.")
 (:auth-resend-button . "Reenviar correo de activación")
 (:auth-resend-success . "¡Correo de activación enviado!")
 (:auth-resend-success-detail . "Revisa tu bandeja de entrada para el nuevo enlace de activación.")
 (:auth-resend-rate-limited . "Por favor espera unos minutos antes de solicitar otro correo de activación.")
 (:auth-resend-cooldown . "Puedes solicitar otro correo en ~a segundos.")
 (:auth-back-to-login . "Volver al inicio de sesión")
 (:auth-forgot-password-title . "Olvidé mi contraseña")
 (:auth-forgot-password-subtitle . "Ingresa tu correo y te enviaremos un enlace para restablecer tu contraseña.")
 (:auth-send-reset-link . "Enviar enlace de restablecimiento")
 (:auth-reset-email-sent . "¡Enlace enviado!")
 (:auth-reset-email-sent-detail . "Si existe una cuenta con ese correo, recibirás un enlace para restablecer tu contraseña pronto.")
 (:auth-reset-rate-limited . "Por favor espera unos minutos antes de solicitar otro restablecimiento de contraseña.")
 (:auth-reset-invalid-token . "Este enlace de restablecimiento es inválido o ha expirado.")
 (:auth-reset-password-title . "Restablecer contraseña")
 (:auth-reset-password-subtitle . "Ingresa tu nueva contraseña abajo.")
 (:auth-new-password . "Nueva contraseña")
 (:auth-confirm-new-password . "Confirmar nueva contraseña")
 (:auth-reset-password . "Restablecer contraseña")
 (:auth-password-changed . "¡Contraseña cambiada!")
 (:auth-password-changed-detail . "Tu contraseña ha sido cambiada exitosamente. Ahora puedes iniciar sesión con tu nueva contraseña.")
 (:auth-change-password-title . "Cambiar contraseña")
 (:auth-change-password-subtitle . "Actualiza la contraseña de tu cuenta.")
 (:auth-current-password . "Contraseña actual")
 (:auth-change-password . "Cambiar contraseña")
 (:auth-back-to-app . "Volver a la app")
 (:auth-password-updated . "¡Contraseña actualizada!")
 (:auth-password-updated-detail . "Tu contraseña ha sido actualizada exitosamente.")
(:auth-current-password-invalid . "La contraseña actual es incorrecta.")
(:auth-new-password-same . "La nueva contraseña debe ser diferente de la contraseña actual.")

 ;; Email copy
 (:email-common-hi . "Hola")
 (:email-common-tagline . "Hiisi - Aprende mediante la traducción")
 (:email-activation-subject . "Activa tu cuenta de Hiisi")
 (:email-activation-title . "Bienvenido a Hiisi")
 (:email-activation-body . "Gracias por registrarte. Activa tu cuenta haciendo clic en el siguiente enlace:")
 (:email-activation-button . "Activar cuenta")
 (:email-activation-copy-link . "O copia este enlace")
 (:email-activation-expiry . "Este enlace caducará en 24 horas.")
 (:email-reset-subject . "Restablece tu contraseña de Hiisi")
 (:email-reset-title . "Solicitud de restablecimiento de contraseña")
 (:email-reset-body . "Hemos recibido una solicitud para restablecer tu contraseña. Haz clic en el siguiente enlace para establecer una nueva contraseña:")
 (:email-reset-button . "Restablecer contraseña")
 (:email-reset-expiry . "Este enlace caducará en 1 hora.")
 (:email-reset-ignore . "Si no solicitaste restablecer tu contraseña, puedes ignorar este correo.")
 (:email-reminder-subject-due . "Es hora de repasar tus tarjetas de Hiisi")
 (:email-reminder-subject-streak . "Mantén tu racha de Hiisi")
 (:email-reminder-cards-due . "tarjetas listas para repasar")
 (:email-reminder-keep-going . "Han pasado unos días desde tu último repaso. Cinco minutos hoy bastan para que no se te escape lo que ya aprendiste.")
 (:email-reminder-button . "Repasar ahora")
 (:email-reminder-settings . "Gestionar recordatorios")
 (:email-reminder-preview-title . "Tarjetas que te esperan")
 (:email-reminder-translation-label . "Traducción")
 (:email-reminder-more-due-today . "tarjetas más para repasar hoy")
 (:email-trial-subject . "¿Cómo va tu prueba de Hiisi?")
 (:email-trial-expiring . "Tu prueba gratuita de Hiisi termina mañana.")
 (:email-trial-feedback . "¿Te está gustando Hiisi? Cuéntanos qué es lo que más te ayuda.")
 (:email-trial-strengths . "Puedes traducir textos reales, guardar los mejores elementos en tarjetas y aprender con repetición espaciada.")
 (:email-trial-reply . "Responde a este correo y tu mensaje llegará directamente al equipo de Hiisi.")
 (:email-trial-button . "Elegir un plan")
 (:email-trial-manage . "Gestionar suscripción")
 (:email-trial-contact . "Escríbenos")
 (:email-plan-nudge-subject . "Tus traducciones te están esperando")
 (:email-plan-nudge-title . "Tus traducciones te están esperando")
 (:email-plan-nudge-intro . "Te registraste en Hiisi, pero todavía no has elegido un plan.")
 (:email-plan-nudge-benefits-intro . "Esto es lo que obtienes con una suscripción:")
 (:email-plan-nudge-benefit-translations . "600 traducciones al mes con desgloses gramaticales")
 (:email-plan-nudge-benefit-flashcards . "Tarjetas ilimitadas con repetición espaciada")
 (:email-plan-nudge-benefit-decks . "Mazos personalizados que puedes organizar y compartir")
 (:email-plan-nudge-pricing . "Los planes empiezan en 10 EUR al mes, o ahorra con el plan anual por 100 EUR al año (dos meses gratis).")
 (:email-plan-nudge-feedback . "Si algo de Hiisi no te está funcionando, responde a este correo. Tu mensaje llegará directamente al equipo de Hiisi.")
 (:email-plan-nudge-button . "Elegir un plan")
 (:email-plan-nudge-unsubscribe . "Dejar de recibir estos correos")
 (:email-plan-nudge-unsubscribe-done-title . "Correos sobre planes desactivados")
 (:email-plan-nudge-unsubscribe-done-body . "No recibirás más correos recordatorios para elegir un plan.")
 (:email-plan-nudge-unsubscribe-invalid-title . "Este enlace no es válido")
 (:email-plan-nudge-unsubscribe-invalid-body . "Este enlace para darse de baja falta, ha caducado o ya no es válido.")
 (:email-invite-subject . "Has sido invitado a Hiisi")
 (:email-invite-title . "Has sido invitado a Hiisi")
 (:email-invite-intro . "Has sido invitado a usar Hiisi gratis, como tester, amigo valioso o ambas cosas.")
 (:email-invite-details . "Usa el botón de abajo para crear tu cuenta y empezar a explorar traducciones y tarjetas.")
 (:email-invite-button . "Crear cuenta")
 (:email-invite-issue-reporting . "Si algo se rompe o no se siente bien, hay un botón para reportar problemas al pie de cada página.")
 (:email-issue-completed-subject . "Tu incidencia de Hiisi ha sido solucionada")
 (:email-issue-completed-title . "Incidencia solucionada")
 (:email-issue-completed-label . "Incidencia")
 (:email-issue-completed-followup . "Abre Hiisi para comprobar la solución o seguir donde lo dejaste.")
 (:email-issue-completed-button . "Abrir Hiisi")
 (:email-issue-completed-open-link . "Abrir página")

 ;; Translation page
 (:translate-title . "Traducir")
 (:landing-public-translate-title . "Pruébalo aquí")
 (:translate-input-label . "Texto a traducir")
 (:translate-input-placeholder . "Ingresa el texto a traducir...")
 (:translate-from . "Idioma de origen:")
 (:translate-to . "Idioma de destino:")
 (:translate-select-target-placeholder . "Selecciona el idioma de destino")
 (:translate-submit . "Traducir")
 (:translate-auto-detect . "Cualquiera (Autodetectar)")
 (:translate-empty-state . "Traduce una palabra o una frase y aquí verás el resultado, el desglose gramatical y las acciones de estudio.")
 (:translate-select-deck-placeholder . "Seleccionar mazo (opcional)")
 (:translate-new-deck . "Nuevo mazo")
 (:translate-add-to-deck . "Añadir al mazo")
 (:translate-bookmark . "Guardar")
 (:translate-bookmarked . "Guardado")
 (:translate-retry . "Generar de nuevo")
 (:translate-like-tooltip . "Buena traducción")
 (:translate-dislike-tooltip . "Mala traducción - solicitar una nueva")
 (:translate-dislike-confirm . "Esto generará una nueva traducción. ¿Continuar?")
 (:pronunciation-label . "Pronunciación")
 (:pronunciation-show . "Mostrar pronunciación")
 (:pronunciation-hide . "Ocultar pronunciación")
 (:grammar-term-examples . "Ejemplos")
 (:grammar-term-related . "Términos relacionados")
 (:grammar-term-modal-title . "Término gramatical")
 (:grammar-term-empty . "Selecciona un término resaltado para ver los detalles.")
 (:extension-login-required . "Inicia sesión en Hiisi antes de usar la extensión del navegador.")
 (:extension-session-invalid . "Tu sesión de Hiisi ya no es válida. Inicia sesión de nuevo.")
 (:extension-activation-required . "Activa tu cuenta de Hiisi antes de usar la extensión del navegador.")
 (:extension-subscription-required . "Inicia una prueba de Hiisi antes de usar la extensión del navegador.")

 ;; Translation and Flashcards
 (:lang-auto . "Auto")
 (:lang-unknown . "?")
 (:lang-target . "Destino")
 (:translate-deck-create-title . "Crear nuevo mazo")
 (:translate-deck-name-label . "Nombre del mazo")
 (:translate-deck-name-placeholder . "p. ej., Fundamentos de finés")
 (:translate-deck-description-label . "Descripción (opcional)")
 (:translate-deck-cancel . "Cancelar")
 (:translate-deck-create . "Crear")
 (:translate-rate-label . "Valorar traducción")
 (:flashcards-delete . "Eliminar")
 (:flashcards-delete-confirm . "¿Seguro que quieres eliminar esta tarjeta?")
 (:flashcards-deck-search-placeholder . "Buscar mazos...")
 (:flashcards-no-decks . "Aún no hay mazos. Crea uno primero.")
 (:flashcards-deck-cancel . "Cancelar")
 (:flashcards-recollection-tooltip . "Recuerdo: ~A")
 (:flashcards-recollection-poor . "Débil")
 (:flashcards-recollection-fair . "Aceptable")
 (:flashcards-recollection-normal . "Normal")
 (:flashcards-recollection-strong . "Fuerte")
 (:flashcards-recollection-very-strong . "Muy fuerte")

 ;; Flashcard review
 (:review-title . "Repasar")
 (:review-session-title . "Sesión de repaso")
 (:review-session-subtitle . "Practica tus tarjetas guardadas")
 (:review-selector-title . "Elige qué repasar")
 (:review-selector-subtitle . "Selecciona un mazo o un par de idiomas para enfocar tu sesión de repaso.")
 (:review-by-deck . "Repasar por mazo")
 (:review-by-language-pair . "Repasar por par de idiomas")
 (:review-all-cards . "Repasar todas las tarjetas")
 (:review-cards-due . "tarjetas pendientes")
 (:review-deck-caught-up . "Todo al día")
 (:review-all-caught-up . "¡Todo al día!")

 (:review-no-cards . "No hay tarjetas para repasar")
 (:review-no-cards-desc . "No tienes tarjetas pendientes de repaso en este momento.")
 (:review-no-cards-hint . "¡Traduce texto y haz clic en \"Guardar en tarjetas\" para crear tu mazo!")
 (:review-start-translating . "Empezar a traducir")
 (:review-click-reveal . "Haz clic para revelar la respuesta")
 (:review-grammar-breakdown . "Análisis gramatical")
 (:review-how-well . "¿Lo recordaste?")
 (:review-again . "No")
 (:review-hard . "A duras penas")
 (:review-good . "Sí")
 (:review-easy . "Fácilmente")
 (:review-progress . "Tarjeta ~a de ~a")
 (:review-correct-count . "Correctas")
 (:review-wrong-count . "Incorrectas")
 (:landing-mockup-forgot-detail . "1.ª persona del singular del pretérito de \"olvidar\"")
 (:landing-mockup-keys-detail . "Posesivo \"mis\" con sustantivo femenino plural \"llaves\"")
 (:landing-mockup-home-detail . "Expresión idiomática \"en casa\" -- sin artículo")
 (:landing-mockup-possession-note . "En español, el pretérito indica acciones pasadas completadas. El pronombre sujeto suele omitirse porque la desinencia verbal ya identifica al hablante.")
 (:landing-mockup-children-detail . "Nominativo plural de \"Kind\" (niño) -- el plural añade -er")
 (:landing-mockup-played-detail . "3.ª persona del plural del pretérito de \"spielen\" (jugar)")
 (:landing-mockup-garden-detail . "Dativo: \"in dem\" se contrae en \"im\", con sustantivo masculino \"Garten\" (jardín)")
 (:landing-mockup-czech-note . "El alemán usa el pretérito en la narrativa escrita. \"Im\" es una contracción de \"in\" + \"dem\" (artículo dativo).")
 (:landing-mockup-deck-title . "Italiano básico")
 (:landing-mockup-share-deck . "Compartir mazo")
 (:review-complete . "¡Sesión completada!")
 (:review-complete-msg . "Repasaste ~a tarjetas")
 (:review-again-btn . "Repasar de nuevo")
 (:review-translate-more . "Traducir más")
 (:review-streak . "días de racha")

 ;; Dashboard
 (:dashboard-title . "Panel")
 (:dashboard-welcome-title . "Traduce tu primer texto")
 (:dashboard-welcome-subtitle . "Traduce una frase útil, guárdala en un mazo y repásala cuando importe.")
 (:dashboard-take-quick-tour . "Hacer un recorrido rápido")
 (:dashboard-cards-due . "Tarjetas pendientes")
 (:dashboard-total-cards . "Total de tarjetas")
 (:dashboard-mastered-cards . "Tarjetas dominadas")
 (:dashboard-subscription . "Suscripción")
 (:dashboard-subscribed-until . "Suscrito hasta")
 (:dashboard-not-subscribed . "Sin suscripción")
 (:dashboard-recent . "Traducciones recientes")
 (:dashboard-no-translations . "Aún no hay traducciones")
 (:dashboard-streak . "Racha de repaso")
 (:dashboard-days . "días")
 (:dashboard-all-caught-up . "Todo al día.")
 (:dashboard-all-caught-up-hint . "Traduce más para ampliar tu colección.")
 (:dashboard-no-cards-title . "Crea tus primeras tarjetas de estudio")
 (:dashboard-no-cards-hint . "Traduce texto y guarda frases útiles para crear tu colección.")
 (:dashboard-getting-started . "Primeros pasos")
 (:dashboard-tip-1 . "Traduce el texto que quieras aprender")
 (:dashboard-tip-2 . "Haz clic en \"Guardar en tarjetas\" en las traducciones que quieras recordar")
 (:dashboard-tip-3 . "Repasa tus tarjetas regularmente - la repetición espaciada te ayuda a recordar a largo plazo")
 (:dashboard-tip-4 . "Califica honestamente - ayuda al algoritmo a programar tus repasos de forma óptima")

 ;; Account
 (:account-title . "Cuenta")
 (:account-subtitle . "Administra aquí tu perfil, suscripción, recordatorios, exportaciones y eliminación de la cuenta.")
 (:account-profile-subtitle . "Mantén actualizados tu nombre visible y tu correo electrónico.")
 (:account-export-subtitle . "Descarga una copia de tus traducciones guardadas, mazos e historial de repaso.")
 (:account-deletion-title . "Eliminación de cuenta")
 (:account-deletion-scheduled . "Tu cuenta está programada para eliminarse el ~A.")
 (:account-deletion-cancel-hint . "Puedes cancelar antes de esta fecha para conservar tu cuenta.")
 (:account-deletion-cancel . "Cancelar eliminación")
 (:account-deletion-request . "Puedes solicitar la eliminación de la cuenta en cualquier momento. La eliminación se programa 14 días después de la confirmación. Si cambias de idea, contacta con soporte antes de que termine ese período de 14 días.")
 (:account-deletion-confirm . "¿Programar la eliminación de la cuenta dentro de 14 días a partir de hoy?")
 (:account-deletion-schedule . "Programar eliminación")
 (:account-reminders-title . "Recordatorios por correo")
 (:account-reminders-subtitle . "Elige si Hiisi puede enviarte correos cuando tengas algo pendiente para repasar.")
 (:account-reminders-opt-out . "Desactivar recordatorios de repaso y continuación")
 (:account-reminders-save . "Guardar preferencias")

 ;; Subscription
 (:subscribe-title . "Precios simples")
 (:subscribe-choose-plan . "Elige tu plan")
 (:subscribe-start-today . "Empieza a aprender hoy con una prueba gratuita de 14 días")
 (:subscribe-monthly . "Mensual")
 (:subscribe-annual . "Anual")
 (:subscribe-founder-member . "Miembro fundador")
 (:subscribe-monthly-price . "€10")
 (:subscribe-annual-price . "€100")
 (:subscribe-founder-price . "€79")
 (:subscribe-per-month . "/mes")
 (:subscribe-per-year . "/año")
 (:subscribe-monthly-desc . "600 traducciones al mes. Tarjetas, mazos y repasos ilimitados.")
 (:subscribe-unlimited-flashcards . "Tarjetas ilimitadas")
 (:subscribe-grammar-explanations . "Explicaciones gramaticales")
 (:subscribe-spaced-repetition . "Repetición espaciada")
 (:subscribe-annual-desc . "Todo del plan mensual. Dos meses gratis.")
 (:subscribe-founder-lock . "El precio se mantiene mientras tu suscripción siga activa.")
 (:subscribe-founder-badge . "Oferta limitada")
 (:subscribe-founder-limit . "Limitado a los primeros 100 miembros")
 (:subscribe-manage . "Gestionar suscripción")
 (:subscribe-activated . "¡Suscripción activada!")
 (:subscribe-thank-you . "Tu suscripción está activa. Aquí puedes gestionar el cobro y comprar más traducciones.")
 (:subscribe-start-learning . "Empezar a aprender")
 (:subscribe-management . "Gestión de suscripción")
 (:subscribe-active . "Suscripción activa")
 (:subscribe-preapproved-access . "Acceso preaprobado")
 (:subscribe-status . "Estado:")
 (:subscribe-status-active . "Activa")
 (:subscribe-status-preapproved . "Preaprobado")
 (:subscribe-preapproved-detail . "Esta cuenta usa un acceso preaprobado gestionado por Hiisi.")
 (:subscribe-days-remaining . "Días restantes:")
 (:subscribe-renews-on . "Se renueva el:")
 (:subscribe-no-subscription . "Sin suscripción activa")
 (:subscribe-access-features . "Elige un plan para desbloquear acceso completo y gestionar el cobro en un solo lugar.")
 (:subscribe-view-plans . "Ver planes")
 (:subscribe-faq-title . "Preguntas frecuentes")
 (:subscribe-faq-trial-q . "¿Qué pasa después de la prueba gratuita?")
 (:subscribe-faq-trial-a . "Tu prueba de 14 días no requiere tarjeta. Cuando termine, elige un plan de pago para conservar el acceso completo.")
 (:subscribe-faq-cancel-q . "¿Puedo cancelar en cualquier momento?")
 (:subscribe-faq-cancel-a . "¡Sí! Puedes cancelar tu suscripción en cualquier momento. Mantendrás el acceso hasta el final de tu período de facturación.")
 (:subscribe-faq-payment-q . "¿Qué métodos de pago aceptan?")
 (:subscribe-faq-payment-a . "Aceptamos todas las tarjetas de crédito y débito principales a través de nuestro socio de pagos Polar.sh.")
 (:subscribe-copyright . "Lambda Symbolics OÜ © 2026.")
(:subscribe-checkout-unavailable . "El proceso de pago está temporalmente no disponible. Inténtalo de nuevo.")
(:subscribe-portal-unavailable . "La gestión de la suscripción está temporalmente no disponible. Inténtalo de nuevo.")
(:subscribe-founder-sold-out . "La oferta de miembros fundadores está agotada")
(:subscribe-founder-unavailable . "La oferta de miembros fundadores no está disponible en este momento.")
(:subscribe-checkout-cta . "Suscribirse")

 ;; Errors and status
 (:error-generic . "Algo salió mal")
(:error-invalid-request . "Datos de solicitud no válidos.")
(:error-not-found . "No se encontró el recurso solicitado.")
(:error-forbidden . "No tienes acceso a esto.")
(:error-rate-limited . "Espera un momento e inténtalo de nuevo.")
 (:error-text-too-long . "El texto es demasiado largo. La longitud máxima de traducción es de 120 caracteres.")
 (:error-input-too-long . "Texto demasiado largo")
 (:error-unknown-source-lang . "El idioma de origen seleccionado no es compatible.")
 (:error-unknown-target-lang . "El idioma de destino seleccionado no es compatible.")
 (:error-unknown-language . "Idioma desconocido")
 (:error-translation-unavailable . "El servicio de traducción no está disponible temporalmente. Por favor, inténtalo de nuevo en un momento.")
 (:error-translation-failed . "Traducción fallida")
 (:error-translation-retry . "No se pudo generar una traducción después de varios intentos. Por favor, intenta reformular tu texto.")
 (:error-quota-exceeded . "Límite de traducciones alcanzado")
 (:error-quota-exceeded-detail . "Has usado todas tus traducciones de este mes. Tu cuota se restablece automáticamente cada mes.")
 (:quota-low-warning . "Solo quedan ~A traducciones. Considere comprar más.")
 (:top-up-button . "Comprar más traducciones")
 (:top-up-price . "5 €")
 (:top-up-amount . "300 traducciones")
(:review-session-expired . "Tu sesión de repaso ha expirado. Inicia una nueva sesión.")

 (:error-session-expired . "Tu sesión ha caducado. Inicia sesión de nuevo.")
 (:error-session-invalid . "Tu sesión ya no es válida. Inicia sesión de nuevo.")
 (:error-custom-flashcard-generation . "No pudimos generar la explicación. Inténtalo de nuevo.")
 ;; Institutions
 (:institutions-page-title . "Hiisi para escuelas y universidades")
 (:institutions-hero-title . "Herramientas para la enseñanza de idiomas hechas para el aula")
 (:institutions-hero-subtitle . "Ofrece a tus estudiantes mazos compartibles, práctica con atención a la gramática y rutinas de repaso constantes que encajan en la enseñanza real.")
 (:institutions-section-title . "Por qué las instituciones usan Hiisi")
 (:institutions-section-body . "Hiisi ayuda al profesorado a convertir el material de clase en un estudio guiado que el alumnado realmente puede seguir. Crea mazos para un curso, compártelos con un enlace y apoya la práctica de vocabulario y gramática sin carga administrativa adicional.")
 (:institutions-benefit-1 . "Mazos compartibles y tareas personalizadas que se ajustan a tu plan de estudios.")
 (:institutions-benefit-2 . "Los me gusta y no me gusta del alumnado ayudan a que las mejores traducciones destaquen en frases habituales del aula.")
 (:institutions-benefit-3 . "Los desgloses gramaticales y el repaso espaciado apoyan mucho más que memorizar listas aisladas de palabras.")
 (:institutions-benefit-4 . "Acompañamiento pensado por y para docentes, de alguien que escucha con atención y se toma en serio las necesidades del aula.")
 (:institutions-request-title . "Empecemos a hablar")
 (:institutions-request-subtitle . "Cuéntanos sobre tu institución, tus idiomas y el tipo de apoyo docente que necesitas. Te responderemos en el plazo de una semana.")
 (:institutions-aside-title . "Qué sucede después")
 (:institutions-aside-body . "Revisamos vuestras necesidades y respondemos en el plazo de una semana para hablar sobre el acceso y la configuración para vuestra institución.")
 (:institutions-field-name . "Nombre de la institución")
 (:institutions-field-name-placeholder . "Tu universidad")
 (:institutions-field-contact-name . "Nombre de contacto")
 (:institutions-field-contact-name-placeholder . "Tu nombre")
 (:institutions-field-contact-email . "Correo de contacto")
 (:institutions-field-contact-email-placeholder . "tu@universidad.edu")
 (:institutions-field-domains . "Dominios de correo")
 (:institutions-field-domains-placeholder . "universidad.edu, cs.universidad.edu")
 (:institutions-field-domains-help . "Lista separada por comas de dominios de correo de tu institución")
 (:institutions-field-notes . "Información adicional")
 (:institutions-field-notes-placeholder . "Número estimado de estudiantes, ciclo de facturación preferido, requisitos especiales...")
 (:institutions-submit . "Enviar solicitud")
 (:institutions-success-title . "Gracias - Hiisi para escuelas y universidades")
 (:institutions-success-heading . "Gracias!")
 (:institutions-success-body . "Hemos recibido tu consulta. Revisaremos las necesidades de tu institución y te responderemos en el plazo de una semana.")
 (:institutions-success-back . "Volver al inicio")

 ;; Footer
 (:footer-privacy . "Política de privacidad")
 (:footer-terms . "Términos de servicio")

 ;; Early software notice
 (:early-software-notice . "Hiisi está en desarrollo temprano. ¿Encontraste un error o tienes una sugerencia?")

 ;; Política de privacidad
 (:privacy-title . "Política de privacidad")
 (:privacy-updated . "Última actualización: enero de 2026")
 (:privacy-who-title . "Quiénes somos")
 (:privacy-who-body . "Hiisi es operado por Lambda Symbolics OÜ, una empresa registrada en Estonia. Como empresa estonia, cumplimos con el Reglamento General de Protección de Datos (GDPR) de la Unión Europea.")
 (:privacy-collect-title . "Datos que recopilamos")
 (:privacy-collect-intro . "Cuando usas Hiisi, recopilamos la siguiente información:")
 (:privacy-collect-account-key . "Información de la cuenta: ")
 (:privacy-collect-account-val . "Dirección de correo electrónico, nombre para mostrar y una contraseña almacenada con hash seguro.")
 (:privacy-collect-learning-key . "Datos de aprendizaje: ")
 (:privacy-collect-learning-val . "Tus traducciones, tarjetas guardadas e historial de repaso.")
 (:privacy-collect-usage-key . "Datos de uso: ")
 (:privacy-collect-usage-val . "Registros básicos del servidor para fines de seguridad y depuración.")
 (:privacy-use-title . "Cómo usamos tus datos")
 (:privacy-use-auth-key . "Autenticación: ")
 (:privacy-use-auth-val . "Para verificar tu identidad y proteger tu cuenta.")
 (:privacy-use-service-key . "Prestación del servicio: ")
 (:privacy-use-service-val . "Para proporcionar traducciones y gestionar tu colección de tarjetas.")
 (:privacy-use-ai-key . "Traducciones con IA: ")
 (:privacy-use-ai-val . "Tus solicitudes de traducción se envían a OpenRouter para generar respuestas. OpenRouter puede enrutar las solicitudes al proveedor de modelos configurado. Consulta la política de privacidad de OpenRouter para saber cómo trata estos datos.")
 (:privacy-third-title . "Servicios de terceros")
 (:privacy-third-intro . "Usamos los siguientes servicios de terceros:")
 (:privacy-third-openrouter-key . "OpenRouter: ")
 (:privacy-third-openrouter-val . "Para solicitudes automáticas de traducción.")
 (:privacy-third-mailgun-key . "Mailgun: ")
 (:privacy-third-mailgun-val . "Para enviar correos de activación de cuenta y correos transaccionales.")
 (:privacy-third-polar-key . "Polar.sh: ")
 (:privacy-third-polar-val . "Para procesar pagos de suscripción.")
 (:privacy-cookies-title . "Cookies")
 (:privacy-cookies-intro . "Usamos solo cookies esenciales:")
 (:privacy-cookies-auth-key . "Token de autenticación: ")
 (:privacy-cookies-auth-val . "Una cookie segura, solo HTTP, para mantener tu sesión iniciada.")
 (:privacy-cookies-lang-key . "Preferencia de idioma: ")
 (:privacy-cookies-lang-val . "Para recordar tu idioma preferido de la interfaz.")
 (:privacy-retention-title . "Conservación de datos")
 (:privacy-retention-body . "Tus datos se almacenan mientras mantengas una cuenta. Cuando solicitas su eliminación, tu cuenta se programa para eliminarse en 14 días.")
 (:privacy-rights-title . "Tus derechos (GDPR)")
 (:privacy-rights-intro . "Según el GDPR, tienes derecho a:")
 (:privacy-rights-access . "Acceder a tus datos personales")
 (:privacy-rights-export . "Exportar tus datos (disponible en /app/api/export)")
 (:privacy-rights-correct . "Solicitar la corrección de datos inexactos")
 (:privacy-rights-delete . "Solicitar la eliminación de tu cuenta y tus datos")
 (:privacy-rights-object . "Oponerte al tratamiento de tus datos")
 (:privacy-rights-contact . "Para ejercer estos derechos, contáctanos en")
 (:privacy-contact-title . "Contacto")
 (:privacy-contact-intro . "Para consultas relacionadas con la privacidad:")
 (:privacy-contact-email-label . "Correo electrónico: ")
 (:privacy-address-1 . "Lambda Symbolics OÜ")
 (:privacy-address-2 . "Harju maakond, Tallinn, Kesklinna linnaosa, Tornimäe tn 5, 10145")

 ;; Términos de servicio
 (:terms-title . "Términos de servicio")
 (:terms-updated . "Última actualización: enero de 2026")
 (:terms-1-title . "1. Descripción del servicio")
 (:terms-1-body . "Hiisi es una aplicación de aprendizaje de idiomas que ofrece traducciones automáticas con explicaciones gramaticales y tarjetas de repetición distribuida. El servicio es operado por Lambda Symbolics OÜ.")
 (:terms-2-title . "2. Registro de cuenta")
 (:terms-2-body . "Para usar Hiisi, debes crear una cuenta con una dirección de correo válida. Eres responsable de mantener la seguridad de las credenciales de tu cuenta.")
 (:terms-3-title . "3. Suscripción y pagos")
 (:terms-3-body . "Hiisi ofrece planes de suscripción de pago (mensual y anual). Las suscripciones se procesan mediante Polar.sh.")
 (:terms-3-list-1 . "Las suscripciones se renuevan automáticamente a menos que se cancelen antes de la fecha de renovación.")
 (:terms-3-list-2 . "Los reembolsos se proporcionan conforme a la normativa de protección al consumidor aplicable.")
 (:terms-3-list-3 . "La falta de pago implica la pérdida de acceso a funciones premium.")
 (:terms-4-title . "4. Uso aceptable")
 (:terms-4-intro . "Aceptas no:")
 (:terms-4-list-1 . "Usar el servicio para fines ilegales")
 (:terms-4-list-2 . "Intentar eludir límites de uso o medidas de seguridad")
 (:terms-4-list-3 . "Compartir las credenciales de tu cuenta con otras personas")
 (:terms-4-list-4 . "Usar herramientas automatizadas de manera que degraden el rendimiento para otras personas")
 (:terms-5-title . "5. Contenido y propiedad intelectual")
 (:terms-5-body-1 . "Las traducciones generadas por Hiisi se crean automáticamente y pueden no ser únicas. Puedes usar tus traducciones y tarjetas para cualquier fin personal, pero no tienes derechos exclusivos de autoría sobre contenido generado automáticamente.")
 (:terms-5-body-2 . "La aplicación Hiisi, su marca y su contenido original siguen siendo propiedad de Lambda Symbolics OÜ.")
 (:terms-6-title . "6. Disponibilidad del servicio")
 (:terms-6-intro . "Hiisi se proporciona tal cual. No garantizamos:")
 (:terms-6-list-1 . "Servicio ininterrumpido o libre de errores")
 (:terms-6-list-2 . "Exactitud de las traducciones generadas automáticamente")
 (:terms-6-list-3 . "Disponibilidad de funciones específicas")
 (:terms-6-body . "Podemos modificar o discontinuar funciones en cualquier momento.")
 (:terms-7-title . "7. Limitación de responsabilidad")
 (:terms-7-body-1 . "En la máxima medida permitida por la ley, Lambda Symbolics OÜ no será responsable por daños indirectos, incidentales, especiales o consecuentes derivados de tu uso de Hiisi.")
 (:terms-7-body-2 . "Nuestra responsabilidad total no superará el importe que hayas pagado por el servicio durante los 12 meses anteriores a la reclamación.")
 (:terms-8-title . "8. Terminación de cuenta")
 (:terms-8-body-1 . "Podemos suspender o terminar tu cuenta si incumples estos términos. Puedes solicitar la eliminación de tu cuenta en cualquier momento desde la aplicación.")
 (:terms-8-body-2 . "Tras una solicitud de eliminación, tu cuenta se programa para eliminarse en 14 días.")
 (:terms-9-title . "9. Cambios en los términos")
 (:terms-9-body . "Podemos actualizar estos términos periódicamente. El uso continuado de Hiisi después de los cambios constituye la aceptación de los nuevos términos.")
 (:terms-10-title . "10. Ley aplicable")
 (:terms-10-body . "Estos términos se rigen por las leyes de Estonia. Cualquier disputa se resolverá en los tribunales de Estonia.")
 (:terms-contact-title . "Contacto")
 (:terms-contact-intro . "Para preguntas sobre estos términos:")
 (:terms-contact-email-label . "Correo electrónico: ")
 (:terms-address-1 . "Lambda Symbolics OÜ")
 (:terms-address-2 . "Harju maakond, Tallinn, Kesklinna linnaosa, Tornimäe tn 5, 10145")

 ;; Decks
 (:decks-title . "Mazos")
 (:decks-subtitle . "Crea mazos personalizados y compártelos con otros.")
 (:decks-create-title . "Crear mazo")
 (:decks-name-placeholder . "Nombre del mazo")
 (:decks-desc-placeholder . "Descripción")
 (:decks-create-btn . "Crear mazo")
 (:decks-edit-title . "Editar mazo")
 (:decks-edit-btn . "Editar mazo")
 (:decks-update-btn . "Guardar cambios")
 (:decks-default-badge . "Automático")
 (:decks-default-description . "Este mazo se gestiona automáticamente para este par de idiomas.")
 (:decks-default-readonly . "Los mazos automáticos tienen nombres y descripciones fijos.")
 (:decks-delete-btn . "Eliminar mazo")
 (:decks-delete-confirm . "¿Seguro que quieres eliminar este mazo?")
 (:decks-error-name-required . "El nombre del mazo es obligatorio.")
 (:decks-error-name-too-long . "El nombre del mazo debe tener como máximo ~A caracteres.")
 (:decks-error-desc-too-long . "La descripción del mazo debe tener como máximo ~A caracteres.")
 (:decks-error-default-readonly . "Los mazos automáticos no se pueden editar.")
 (:decks-error-default-delete-forbidden . "Los mazos automáticos no se pueden eliminar.")
 (:decks-your-title . "Tus mazos")
 (:decks-col-updated . "Actualizado")
 (:decks-no-decks . "Aún no hay mazos.")
 (:decks-open-btn . "Abrir")
 (:decks-no-desc . "Sin descripción.")
 (:decks-share-title . "Enlace para compartir")
 (:decks-share-info . "Cualquiera con este enlace puede importar el mazo:")
 (:decks-share-copy . "Copiar enlace")
 (:decks-share-copied . "Copiado")
 (:decks-add-from-flashcards-title . "Añadir traducciones")
 (:decks-add-from-flashcards-info . "Elige una tarjeta para añadir su traducción a este mazo.")
 (:decks-open-flashcards . "Añadir desde tarjetas")
 (:decks-filter-from . "Idioma de origen")
 (:decks-filter-to . "Idioma de destino")
 (:decks-filter-any . "Cualquier idioma")
 (:decks-filter-include-assigned . "Incluir tarjetas que ya están en un mazo")
 (:decks-flashcards-add . "Añadir")
 (:decks-flashcards-added . "Añadido")
 (:decks-flashcards-in-deck . "En otro mazo")
 (:decks-flashcards-empty . "Ninguna tarjeta coincide con estos filtros.")
 (:decks-items-title . "Contenido del mazo")
 (:decks-col-original . "Original")
 (:decks-col-translated . "Traducción")
 (:decks-col-lang . "Idioma destino")
 (:decks-no-items . "Aún no hay elementos.")
 (:decks-share-page-title . "Compartir mazo")
 (:decks-share-preview . "Vista previa e importación de este mazo.")
 (:decks-import-title . "Importar")
 (:decks-import-btn . "Importar mazo")
 (:starter-decks-title . "Biblioteca")
 (:starter-decks-subtitle . "Importa mazos listos para usar de Hiisi y de la comunidad.")
 (:starter-decks-marketplace-btn . "Biblioteca")
 (:starter-decks-explanation-language . "Idioma de explicación")
 (:starter-decks-search-label . "Buscar")
 (:starter-decks-source-label . "Origen")
 (:starter-decks-source-all . "Todos los mazos")
 (:starter-decks-search-placeholder . "Buscar en la biblioteca")
 (:starter-decks-apply-filters . "Aplicar filtros")
 (:starter-decks-select-triplet-hint . "Elige el idioma de origen y destino para explorar mazos compatibles.")
 (:starter-decks-official-badge . "Oficial")
 (:starter-decks-community-badge . "Comunidad")
 (:starter-decks-by-hiisi . "De Hiisi")
 (:starter-decks-preview-btn . "Vista previa")
 (:starter-decks-card-count . "~A tarjetas")
 (:starter-decks-no-results . "Ningún mazo coincide con estos filtros.")
 (:starter-decks-source-cards-title . "Tarjetas de este mazo")
 (:starter-decks-sample-title . "Tarjetas de muestra")
 (:starter-decks-generating . "Generando mazo...")
 (:starter-decks-generating-detail . "Este mazo se está generando para tu trío de idiomas. Deja esta página abierta o vuelve dentro de un momento.")
 (:starter-decks-generation-failed . "La generación falló")
 (:starter-decks-generation-failed-detail . "El último intento de generación falló. Intenta importar el mazo de nuevo.")
 (:starter-decks-login-detail . "Inicia sesión para importar este mazo a tu colección.")
 (:starter-decks-subscribe-btn . "Ver planes")
 (:starter-decks-subscribe-detail . "Los mazos de la biblioteca están disponibles con una suscripción activa o una prueba.")
 (:library-submit-title . "Enviar a la biblioteca")
 (:library-submit-intro . "Envía este mazo a la biblioteca para revisión administrativa antes de su publicación.")
 (:library-submit-btn . "Enviar mazo")
 (:library-submit-approved . "Aprobado para la biblioteca")
 (:library-submit-approved-detail . "Este mazo está publicado en la biblioteca.")
 (:library-submit-pending . "En revisión")
 (:library-submit-pending-detail . "Este mazo se ha enviado y está esperando la revisión administrativa.")
 (:library-submit-rejected . "Necesita cambios antes de publicarse")
 (:library-submit-rejected-detail . "Este envío fue rechazado. Actualiza el mazo y vuelve a enviarlo.")
 (:library-error-empty . "Añade al menos una tarjeta antes de enviar este mazo a la biblioteca.")
 (:library-error-missing-triplet . "Cada tarjeta de un envío a la biblioteca debe tener un trío de idiomas completo.")
 (:library-error-mixed-triplet . "Todas las tarjetas de un envío a la biblioteca deben compartir el mismo trío de idiomas.")
 (:starter-deck-topic-greetings-title . "Saludos y presentaciones")
 (:starter-deck-topic-greetings-description . "Saludos, nombres, fórmulas básicas de cortesía y frases para un primer encuentro.")
 (:starter-deck-topic-travel-title . "Viaje esencial")
 (:starter-deck-topic-travel-description . "Estaciones, billetes, precios, pedir ayuda y moverse de un lugar a otro.")
 (:starter-deck-topic-numbers-title . "Números y precios")
 (:starter-deck-topic-numbers-description . "Contar, totales, precios, pisos y cantidades cotidianas.")
 (:starter-deck-topic-time-title . "Hora y fechas")
 (:starter-deck-topic-time-description . "Días, meses, citas, la hora y fechas relativas.")
 (:starter-deck-topic-food-title . "Restaurante y comida")
 (:starter-deck-topic-food-description . "Pedir, necesidades alimentarias, bebidas, la cuenta y comidas cotidianas fuera de casa.")
 (:starter-deck-topic-emergency-title . "Emergencias y salud")
 (:starter-deck-topic-emergency-description . "Médicos, farmacias, síntomas, partes del cuerpo y ayuda urgente.")
 (:starter-deck-topic-directions-title . "Indicaciones y transporte")
 (:starter-deck-topic-directions-description . "Giros, paradas, billetes, andenes y moverse por la ciudad.")
 (:starter-deck-topic-school-title . "Escuela y educación")
 (:starter-deck-topic-school-description . "Clases, deberes, exámenes, material escolar y la vida diaria en la escuela.")
 (:starter-deck-topic-university-title . "Universidad y estudios")
 (:starter-deck-topic-university-description . "Clases magistrales, seminarios, carreras, trabajos y la vida diaria en el campus.")

 ;; Flashcards management page
 (:flashcards-title . "Mis tarjetas")
 (:flashcards-subtitle . "Todas tus tarjetas guardadas en un solo lugar. Busca, organiza y gestiona.")
 (:flashcards-search-placeholder . "Buscar tarjetas...")
 (:flashcards-filter-button . "Filtros")
 (:flashcards-filter-title . "Filtrar tarjetas")
 (:flashcards-filter-recollection . "Qué tan bien las conoces")
 (:flashcards-filter-any-recollection . "Cualquier nivel")
 (:flashcards-hide-perfected . "Ocultar tarjetas dominadas")
 (:flashcards-col-original . "Original")
 (:flashcards-col-translated . "Traducción")
 (:flashcards-no-cards . "Aún no hay tarjetas. ¡Comienza a traducir para crear algunas!")
 (:flashcards-image-label . "Imagen")
 (:flashcards-image-upload . "Subir imagen")
 (:flashcards-image-replace . "Reemplazar imagen")
 (:flashcards-image-remove . "Eliminar imagen")
 (:flashcards-pagination-label . "Páginas de tarjetas")
 (:flashcards-pagination-status . "Página ~A de ~A")
 (:flashcards-pagination-previous . "Anterior")
 (:flashcards-pagination-next . "Siguiente")

 ;; Landing page (redesign)
 (:landing-hero-headline . "Cada palabra explicada. Cada repaso programado. Quince idiomas.")
 (:landing-hero-subheadline . "Hiisi es el traductor que te enseña gramática mientras lees, y la aplicación de tarjetas que se construye a partir de lo que realmente traduces.")
 (:landing-hero-trust-line . "14 días gratis. Sin tarjeta.")
 (:landing-credibility-languages . "15 idiomas")
 (:landing-credibility-ai . "Cada palabra explicada")
 (:landing-credibility-srs . "Repetición espaciada integrada")
 (:landing-languages-title . "Idiomas que admitimos")
 (:landing-step-1-title . "Pega una frase")
 (:landing-step-1-desc . "De cualquier longitud, en cualquiera de los 15 idiomas. Obtienes la traducción y un desglose gramatical de cada palabra.")
 (:landing-step-2-title . "Guarda lo que merece recordar")
 (:landing-step-2-desc . "Un clic convierte una traducción en una tarjeta, con la frase original guardada como contexto.")
 (:landing-step-3-title . "Repasa en el momento justo")
 (:landing-step-3-desc . "Repetición espaciada con SM-2, el mismo algoritmo que utiliza Anki. Las tarjetas con las que más luchas vuelven antes.")
 (:landing-feature-grammar-title . "Cada palabra explicada, en tu idioma")
 (:landing-feature-grammar-desc . "Las traducciones vienen con caso, género, aspecto y modo desglosados palabra por palabra. Partitivo finés, animacidad checa, aspecto polaco, contracciones en dativo alemán, todo etiquetado y enlazado a una referencia gramatical.")
 (:landing-feature-srs-title . "El hábito de la repetición espaciada, automatizado")
 (:landing-feature-srs-desc . "El algoritmo SM-2 se adapta a tu rendimiento. Las tarjetas difíciles aparecen más a menudo. Las que dominas aparecen menos.")
 (:landing-feature-share-title . "Tus mazos, o los de la comunidad")
 (:landing-feature-share-desc . "Organiza las tarjetas en mazos temáticos. Comparte cualquier mazo con un enlace o explora la biblioteca comunitaria en busca de mazos compartidos por otros.")
 (:landing-pricing-trial-note . "Incluye 14 días de prueba gratis")
 (:landing-pricing-monthly-after . "14 días gratis, luego ~A/mes")
 (:landing-pricing-annual-after . "14 días gratis, luego ~A/año")
 (:landing-faq-title . "Preguntas frecuentes")
 (:landing-faq-trial-cap-q . "¿Cuántas traducciones obtengo durante la prueba?")
 (:landing-faq-trial-cap-a . "Obtienes 200 traducciones durante tu prueba de 14 días. Después de suscribirte, obtienes 600 por mes.")
 (:landing-final-cta-title . "Tu primera frase tarda cinco segundos.")
 (:landing-final-cta-subtitle . "Pega lo que quieras en finés, checo, polaco o cualquiera de los otros doce idiomas. Mira lo que Hiisi hace con ello. Catorce días gratis.")

 ;; Trial status (in-app)
 (:trial-status . "Prueba gratuita")
 (:error-trial-quota-exceeded . "Límite de traducciones de prueba alcanzado")
 (:error-trial-quota-detail . "Has usado las 200 traducciones de prueba. Suscríbete para seguir aprendiendo.")

 ;; Custom flashcards
 (:custom-flashcard-create-title . "Crear tarjeta")
 (:custom-flashcard-edit-title . "Editar tarjeta")
 (:custom-flashcard-original . "Texto original")
 (:custom-flashcard-translated . "Traducción")
 (:custom-flashcard-lang-from . "Idioma de origen")
 (:custom-flashcard-lang-to . "Idioma de destino")
 (:custom-flashcard-note . "Nota educativa")
 (:custom-flashcard-forms . "Análisis gramatical")
 (:custom-flashcard-form-term . "Término")
 (:custom-flashcard-form-explanation . "Explicación")
 (:custom-flashcard-add-form . "Agregar término gramatical")
 (:custom-flashcard-remove-form . "Eliminar")
 (:custom-flashcard-ai-fill . "Rellenar con IA")
 (:custom-flashcard-create-btn . "Crear tarjeta")
 (:custom-flashcard-update-btn . "Guardar cambios")

  ;; Newsletter
  (:newsletter-email-label . "Dirección de correo")
  (:newsletter-developer-label . "Soy desarrollador")
  (:newsletter-developer-hint . "recibir actualizaciones técnicas")
  (:landing-newsletter-title . "Recibe novedades de Hiisi.")
  (:landing-newsletter-body . "Únete al boletín para recibir novedades del producto, nuevos idiomas, mazos iniciales y ofertas ocasionales para miembros fundadores.")
  (:landing-newsletter-fine-print . "Sin spam. Solo novedades del producto.")
  (:landing-newsletter-button . "Unirme al boletín")
  (:newsletter-unsubscribe-page-title . "Cancelar suscripción al boletín de Hiisi")
  (:newsletter-unsubscribe-title . "Cancelar suscripción")
  (:newsletter-unsubscribe-subtitle . "Introduce tu correo para dejar de recibir novedades de Hiisi.")
  (:newsletter-unsubscribe-button . "Cancelar suscripción")
  (:newsletter-feedback-email-required . "Introduce tu dirección de correo.")
  (:newsletter-feedback-email-invalid . "Introduce una dirección de correo válida.")
  (:newsletter-feedback-already-signed-up . "Ya estás registrado. Te mantendremos informado.")
  (:newsletter-feedback-signed-up . "¡Estás en la lista! Te enviaremos novedades ocasionales de Hiisi.")
  (:newsletter-feedback-unsubscribed . "Si este correo estaba suscrito, se ha eliminado de las novedades de Hiisi.")
  (:newsletter-feedback-generic-error . "Algo salió mal. Inténtalo de nuevo.")

  ;; Reporte de problemas
 (:issues-open-button . "Reportar un error")
 (:issues-modal-title . "Reportar un problema")
 (:issues-modal-subtitle . "Describe qué salió mal. Incluiremos automáticamente la página actual.")
 (:issues-title-label . "Título breve")
 (:issues-title-placeholder . "Resumen breve del problema")
 (:issues-message-label . "¿Qué ocurrió?")
 (:issues-message-placeholder . "Incluye pasos para reproducir, el comportamiento esperado y lo que ocurrió en su lugar.")
 (:issues-submit . "Enviar reporte")
 (:issues-cancel . "Cancelar")
 (:issues-success . "Tu aviso se envió. Lo revisaremos lo antes posible.")
 (:issues-error-required . "Describe el problema antes de enviarlo.")
 (:issues-error-title-too-long . "El título del reporte es demasiado largo. Mantenlo por debajo de 160 caracteres.")
 (:issues-error-too-long . "El texto del reporte es demasiado largo. Mantenlo por debajo de 4000 caracteres.")
 (:issues-error-rate-limit . "Demasiados reportes desde este origen. Espera e inténtalo de nuevo más tarde.")
 (:issues-error-generic . "No se pudo enviar el reporte de problema. Inténtalo de nuevo.")

)
