;;; Estonian translations

(
 ;; Language metadata (used for language picker)
 (:lang-name . "Eesti")
 (:lang-flag . "🇪🇪")

 ;; Language modal (first-visit language selection)
 (:lang-modal-title . "Valige oma keel")
 (:lang-modal-subtitle . "Valige liidese eelistatud keel:")

 ;; Navigation
 (:nav-translate . "Tõlgi")
 (:nav-review . "Kordamine")
 (:nav-flashcards . "Minu kaardid")
 (:nav-dashboard . "Ülevaade")
 (:nav-decks . "Kaardipakid")
 (:nav-logout . "Logi välja")
 (:nav-home . "Avaleht")
 (:nav-pricing . "Hinnad")
 (:nav-institutions . "Asutustele")
 (:nav-export-data . "Ekspordi andmed")
 (:nav-open-navigation . "Ava navigatsioon")
 (:theme-light . "Hele")
 (:theme-dark . "Tume")

 ;; App title and branding
 (:app-title . "Hiisi - Keeleõpe")

 ;; Landing page
 (:landing-learn-more . "Loe lähemalt")
 (:landing-how-it-works . "Kuidas see töötab")
 (:landing-start-trial . "Alusta tasuta prooviperioodi")
 (:landing-best-value . "Parim pakkumine")

 ;; Auth pages
 (:auth-register . "Registreeru")
 (:auth-login . "Logi sisse")
 (:auth-email . "E-post")
 (:auth-password . "Parool")
 (:auth-password-again . "Kinnita parool")
 (:auth-display-name . "Kuvatav nimi")
 (:auth-register-title . "Registreeru Hiisi kasutajaks")
 (:auth-register-subtitle . "Loo uus konto")
 (:auth-login-title . "Logi Hiisi sisse")
 (:auth-login-subtitle . "Sisesta oma andmed")
 (:auth-login-invalid-credentials . "Vigane e-post või parool.")
 (:auth-login-rate-limited . "Liiga palju sisselogimiskatseid. Oota paar minutit ja proovi uuesti.")
(:auth-register-rate-limited . "Liiga palju registreerimiskatseid. Oota mõni minut ja proovi uuesti.")
(:auth-email-invalid . "Sisesta kehtiv e-posti aadress.")
(:auth-password-too-short . "Parool peab olema vähemalt 8 märki pikk.")
(:auth-passwords-mismatch . "Paroolid ei ühti.")
(:auth-display-name-invalid . "Kuvatav nimi peab olema 1 kuni 100 märki pikk.")
(:auth-register-email-exists . "Selle e-posti aadressiga konto on juba olemas.")
(:auth-register-unavailable . "Registreerimine on ajutiselt maas. Proovi hiljem uuesti.")
(:auth-register-plan-required . "Vali enne konto loomist pakett.")
(:auth-institution-register . "Tuled õppeasutusest?")
(:auth-institution-title . "Registreeru oma õppeasutuse kaudu")
(:auth-institution-subtitle . "Kasuta kooli või ülikooli e-posti aadressi. Kui sinu asutusel on aktiivne Hiisi ligipääs, avatakse konto pärast e-posti kinnitamist.")
(:auth-institution-domain-unrecognized . "Me ei tunne seda asutuse e-posti domeeni veel ära. Vali pakett või palu oma asutusel Hiisiga ühendust võtta.")
(:subscribe-institution-callout-title . "Kasutad Hiisit kooli või ülikooli kaudu?")
(:subscribe-institution-callout-body . "Registreeru oma asutuse e-postiga ja Hiisi avab ligipääsu automaatselt, kui sinu asutus on juba seadistatud.")
(:auth-activation-email-send-failed . "Aktiveerimiskirja saatmine ebaõnnestus. Proovi uuesti.")
 (:auth-forgot-password . "Unustasid parooli?")
 (:auth-no-account . "Pole veel kontot?")
 (:auth-have-account . "On juba konto?")
 (:auth-google . "Google")
 (:auth-google-login-failed . "Google'iga sisselogimine ebaõnnestus. Palun proovi uuesti.")
 (:auth-account-created . "Konto loodud!")
 (:auth-check-email . "Kontrolli oma e-posti aktiveerimislingi saamiseks.")
 (:auth-redirect-login . "Suunan sisselogimisele")
 (:auth-seconds . "sekundi pärast...")
 (:auth-go-now . "Mine kohe")
 (:auth-not-activated . "Konto pole aktiveeritud")
 (:auth-activate-title . "Aktiveeri oma konto!")
 (:auth-activated . "Konto aktiveeritud!")
 (:auth-activated-message . "Sinu konto on aktiveeritud. Võid nüüd Hiisi kasutada.")
 (:auth-redirecting . "Suunan ümber")
 (:auth-go-to-app . "Mine rakendusse")
 (:onboarding-title . "Kuidas Hiisi töötab")
 (:onboarding-subtitle . "Tõlgi päris teksti, vaata grammatikat, salvesta kasulikke üksusi ja korda neid hiljem.")
 (:onboarding-translate-detail . "Alusta päris tekstist. Hiisi näitab tõlget, vastavusse seatud vorme ja järgmisi õpitegevusi ühes kohas.")
 (:onboarding-grammar-detail . "Ava grammatiline jaotus, et näha, millised vormid lauses omavahel vastavad ja mis rolli iga osa täidab.")
 (:onboarding-review-detail . "Salvesta kasulikud tõlked ja korda neid hiljem ajastatud kordamisega, et need jääksid pikaajalisse mällu.")
 (:onboarding-decks-detail . "Koonda kasulikud üksused kaardipakkidesse, jaga neid teistega ja hoia seotud materjal koos.")
 (:onboarding-back . "Tagasi")
 (:onboarding-next . "Edasi")
 (:onboarding-skip . "Jäta tutvustus vahele")
 (:auth-resend-title . "Saada aktiveerimismeil uuesti")
 (:auth-resend-subtitle . "Sisesta oma e-post, et saada uus aktiveerimislink.")
 (:auth-resend-button . "Saada aktiveerimismeil uuesti")
 (:auth-resend-success . "Aktiveerimismeil saadetud!")
 (:auth-resend-success-detail . "Vaata oma postkasti uue aktiveerimislingi saamiseks.")
 (:auth-resend-rate-limited . "Palun oota mõni minut enne järgmise aktiveerimismeili taotlemist.")
 (:auth-resend-cooldown . "Saad uue meili taotleda ~a sekundi pärast.")
 (:auth-back-to-login . "Tagasi sisselogimisele")
 (:auth-forgot-password-title . "Unustasin parooli")
 (:auth-forgot-password-subtitle . "Sisesta oma e-post ja saadame sulle lingi parooli lähtestamiseks.")
 (:auth-send-reset-link . "Saada lähtestamise link")
 (:auth-reset-email-sent . "Link saadetud!")
 (:auth-reset-email-sent-detail . "Kui selle e-postiga konto eksisteerib, saad peagi parooli lähtestamise lingi.")
 (:auth-reset-rate-limited . "Palun oota mõni minut enne järgmise parooli lähtestamise taotlemist.")
 (:auth-reset-invalid-token . "See parooli lähtestamise link on kehtetu või aegunud.")
 (:auth-reset-password-title . "Lähtesta parool")
 (:auth-reset-password-subtitle . "Sisesta oma uus parool allpool.")
 (:auth-new-password . "Uus parool")
 (:auth-confirm-new-password . "Kinnita uus parool")
 (:auth-reset-password . "Lähtesta parool")
 (:auth-password-changed . "Parool muudetud!")
 (:auth-password-changed-detail . "Sinu parool on edukalt muudetud. Võid nüüd uue parooliga sisse logida.")
 (:auth-change-password-title . "Muuda parooli")
 (:auth-change-password-subtitle . "Uuenda oma konto parooli.")
 (:auth-current-password . "Praegune parool")
 (:auth-change-password . "Muuda parooli")
 (:auth-back-to-app . "Tagasi rakendusse")
 (:auth-password-updated . "Parool uuendatud!")
 (:auth-password-updated-detail . "Sinu parool on edukalt uuendatud.")
(:auth-current-password-invalid . "Praegune parool on vale.")
(:auth-new-password-same . "Uus parool peab erinema praegusest paroolist.")

 ;; Email copy
 (:email-common-hi . "Tere")
 (:email-common-tagline . "Hiisi - Õpi tõlkimise kaudu")
 (:email-activation-subject . "Aktiveeri oma Hiisi konto")
 (:email-activation-title . "Tere tulemast Hiisi'sse")
 (:email-activation-body . "Täname registreerimise eest. Palun aktiveeri oma konto, klõpsates alloleval lingil:")
 (:email-activation-button . "Aktiveeri konto")
 (:email-activation-copy-link . "Või kopeeri see link")
 (:email-activation-expiry . "See link aegub 24 tunni pärast.")
 (:email-reset-subject . "Hiisi parooli lähtestamine")
 (:email-reset-title . "Parooli lähtestamise taotlus")
 (:email-reset-body . "Saime taotluse sinu parooli lähtestamiseks. Uue parooli määramiseks klõpsa alloleval lingil:")
 (:email-reset-button . "Lähtesta parool")
 (:email-reset-expiry . "See link aegub 1 tunni pärast.")
 (:email-reset-ignore . "Kui sa ei taotlenud parooli lähtestamist, võid seda e-kirja ignoreerida.")
 (:email-reminder-subject-due . "Aeg Hiisi kaarte üle vaadata")
 (:email-reminder-subject-streak . "Hoia oma Hiisi seeriat")
 (:email-reminder-cards-due . "kaarti ootab ülevaatamist")
 (:email-reminder-keep-going . "Eelmisest kordamisest on möödas paar päeva. Viis minutit täna piisab, et see, mida oled juba õppinud, ei libiseks meelest.")
 (:email-reminder-button . "Korda nüüd")
 (:email-reminder-settings . "Meeldetuletuste seaded")
 (:email-reminder-preview-title . "Sind ootavad kaardid")
 (:email-reminder-translation-label . "Tõlge")
 (:email-reminder-more-due-today . "kaarti veel täna üle vaadata")
 (:email-trial-subject . "Kuidas su Hiisi prooviperiood läheb?")
 (:email-trial-expiring . "Sinu tasuta Hiisi prooviperiood lõpeb homme.")
 (:email-trial-feedback . "Kas Hiisi meeldib sulle? Kirjuta meile, mis sind kõige rohkem aitab.")
 (:email-trial-strengths . "Saad tõlkida päris tekste, salvestada neist mälukaarte ja õppida hajutatud kordamisega.")
 (:email-trial-reply . "Vasta lihtsalt sellele kirjale, su tagasiside jõuab otse Hiisi tiimini.")
 (:email-trial-button . "Vali pakett")
 (:email-trial-manage . "Halda tellimust")
 (:email-trial-contact . "Kirjuta meile")
 (:email-plan-nudge-subject . "Sinu tõlked ootavad")
 (:email-plan-nudge-title . "Sinu tõlked ootavad")
 (:email-plan-nudge-intro . "Registreerisid end Hiisisse, kuid ei ole veel paketti valinud.")
 (:email-plan-nudge-benefits-intro . "Tellimusega saad:")
 (:email-plan-nudge-benefit-translations . "600 tõlget kuus koos grammatikaselgitustega")
 (:email-plan-nudge-benefit-flashcards . "Piiramatult mälukaarte hajutatud kordamisega")
 (:email-plan-nudge-benefit-decks . "Oma pakid, mida saad korraldada ja jagada")
 (:email-plan-nudge-pricing . "Paketid algavad 10 eurost kuus või säästa aastapaketiga hinnaga 100 eurot aastas (kaks kuud tasuta).")
 (:email-plan-nudge-feedback . "Kui miski Hiisis sinu jaoks ei toimi, vasta sellele kirjale. Su sõnum jõuab otse Hiisi tiimini.")
 (:email-plan-nudge-button . "Vali pakett")
 (:email-plan-nudge-unsubscribe . "Loobu neist kirjadest")
 (:email-plan-nudge-unsubscribe-done-title . "Paketikirjad on välja lülitatud")
 (:email-plan-nudge-unsubscribe-done-body . "Sa ei saa enam paketi valimise meeldetuletuskirju.")
 (:email-plan-nudge-unsubscribe-invalid-title . "See link ei kehti")
 (:email-plan-nudge-unsubscribe-invalid-body . "See loobumislink puudub, on aegunud või ei kehti enam.")
 (:email-invite-subject . "Kutse Hiisisse")
 (:email-invite-title . "Sind on kutsutud Hiisit kasutama")
 (:email-invite-intro . "Sind on kutsutud Hiisit tasuta kasutama testija, hinnatud sõbra või mõlemana.")
 (:email-invite-details . "Loo alloleva nupu abil konto ja hakka kasutama tõlkeid ning mälukaarte.")
 (:email-invite-button . "Loo konto")
 (:email-invite-issue-reporting . "Kui midagi katki läheb või tundub vale, leiad iga lehe allservast vea teatamise nupu.")
 (:email-issue-completed-subject . "Sinu Hiisi veateade on parandatud")
 (:email-issue-completed-title . "Probleem on parandatud")
 (:email-issue-completed-label . "Probleem")
 (:email-issue-completed-followup . "Ava Hiisi, kontrolli parandust või jätka sealt, kus pooleli jäid.")
 (:email-issue-completed-button . "Ava Hiisi")
 (:email-issue-completed-open-link . "Ava leht")

 ;; Translation page
 (:translate-title . "Tõlgi")
 (:landing-public-translate-title . "Proovi siin")
 (:translate-input-label . "Tõlgitav tekst")
 (:translate-input-placeholder . "Sisesta tõlgitav tekst...")
 (:translate-from . "Lähtkeel:")
 (:translate-to . "Sihtkeel:")
 (:translate-select-target-placeholder . "Vali sihtkeel")
 (:translate-submit . "Tõlgi")
 (:translate-auto-detect . "Suvaline (automaattuvastus)")
 (:translate-empty-state . "Tõlgi sõna või fraas ning siin näed tulemust, grammatika lahtikirjutust ja õppetoiminguid.")
 (:translate-select-deck-placeholder . "Vali kaardipakk (valikuline)")
 (:translate-new-deck . "Uus kaardipakk")
 (:translate-add-to-deck . "Lisa kaardipakki")
 (:translate-bookmark . "Salvesta")
 (:translate-bookmarked . "Salvestatud")
 (:translate-retry . "Genereeri uuesti")
 (:translate-like-tooltip . "Hea tõlge")
 (:translate-dislike-tooltip . "Halb tõlge - taotle uut")
 (:translate-dislike-confirm . "See genereerib uue tõlke. Jätkata?")
 (:pronunciation-label . "Hääldus")
 (:pronunciation-show . "Näita hääldust")
 (:pronunciation-hide . "Peida hääldus")
 (:grammar-term-examples . "Näited")
 (:grammar-term-related . "Seotud mõisted")
 (:grammar-term-modal-title . "Grammatikatermin")
 (:grammar-term-empty . "Vali esiletõstetud termin, et näha üksikasju.")
 (:extension-login-required . "Logi Hiisisse sisse enne brauserilaienduse kasutamist.")
 (:extension-session-invalid . "Sinu Hiisi seanss ei kehti enam. Logi uuesti sisse.")
 (:extension-activation-required . "Aktiveeri oma Hiisi konto enne brauserilaienduse kasutamist.")
 (:extension-subscription-required . "Alusta Hiisi prooviperioodi enne brauserilaienduse kasutamist.")

 ;; Translation and Flashcards
 (:lang-auto . "Auto")
 (:lang-unknown . "?")
 (:lang-target . "Siht")
 (:translate-deck-create-title . "Loo uus kaardipakk")
 (:translate-deck-name-label . "Kaardipaki nimi")
 (:translate-deck-name-placeholder . "nt Soome keele alused")
 (:translate-deck-description-label . "Kirjeldus (valikuline)")
 (:translate-deck-cancel . "Tühista")
 (:translate-deck-create . "Loo")
 (:translate-rate-label . "Hinda tõlget")
 (:flashcards-delete-confirm . "Kas oled kindel, et soovid selle kaardi kustutada?")
 (:flashcards-deck-search-placeholder . "Otsi kaardipakke...")
 (:flashcards-no-decks . "Kaardipakke veel pole. Loo üks kõigepealt!")
 (:flashcards-deck-cancel . "Tühista")
 (:flashcards-recollection-tooltip . "Meeldejäävus: ~A")
 (:flashcards-recollection-poor . "Nõrk")
 (:flashcards-recollection-fair . "Rahuldav")
 (:flashcards-recollection-normal . "Tavaline")
 (:flashcards-recollection-strong . "Tugev")
 (:flashcards-recollection-very-strong . "Väga tugev")

 ;; Flashcard review
 (:review-title . "Kordamine")
 (:review-session-title . "Kordamisseanss")
 (:review-session-subtitle . "Harjuta oma salvestatud mälukaarte")
 (:review-selector-title . "Vali, mida korrata")
 (:review-selector-subtitle . "Vali pakk või keelepaar, millele selles kordamisseansis keskenduda.")
 (:review-by-deck . "Korda paki järgi")
 (:review-by-language-pair . "Korda keelepaari järgi")
 (:review-all-cards . "Korda kõiki kaarte")
 (:review-cards-due . "kaarti kordamiseks")
 (:review-deck-caught-up . "Kõik korratud")
 (:review-all-caught-up . "Kõik korratud!")

 (:review-no-cards . "Pole kaarte kordamiseks")
 (:review-no-cards-desc . "Sul pole praegu ühtegi mälukaarti, mis vajaks kordamist.")
 (:review-no-cards-hint . "Tõlgi teksti ja klõpsa \"Salvesta mälukaartidesse\", et oma pakki üles ehitada!")
 (:review-start-translating . "Alusta tõlkimist")
 (:review-click-reveal . "Klõpsa vastuse nägemiseks")
 (:review-grammar-breakdown . "Grammatika analüüs")
 (:review-how-well . "Kas tuli meelde?")
 (:review-again . "Ei")
 (:review-hard . "Vaevalt")
 (:review-good . "Jah")
 (:review-easy . "Kergesti")
 (:review-progress . "Kaart ~a/~a")
 (:review-correct-count . "Õige")
 (:review-wrong-count . "Valesti")
 (:landing-mockup-forgot-detail . "Tegusõna \"olvidar\" (unustama) ainsuse 1. pöörde preteeritum")
 (:landing-mockup-keys-detail . "Omastajaline \"mis\" naissoo mitmuse nimisõnaga \"llaves\" (võtmed)")
 (:landing-mockup-home-detail . "Idiomaatiline \"en casa\" (kodus) -- artiklit pole vaja")
 (:landing-mockup-possession-note . "Hispaania keeles tähistab preteeritum lõpetatud mineviku tegevusi. Aluse asesõna jäetakse tavaliselt ära, sest tegusõna lõpp määrab kõneleja.")
 (:landing-mockup-children-detail . "Nimisõna \"Kind\" (laps) nimetava mitmuse vorm -- mitmus lisab -er")
 (:landing-mockup-played-detail . "Tegusõna \"spielen\" (mängima) mitmuse 3. pöörde preteeritum")
 (:landing-mockup-garden-detail . "Daativ: \"in dem\" tõmbub kokku kujule \"im\", meessoost nimisõnaga \"Garten\" (aed)")
 (:landing-mockup-czech-note . "Saksa keel kasutab preteeritumit kirjalikus jutustuses. \"Im\" on kokku tõmbunud kuju sõnadest \"in\" + \"dem\" (daativi artikkel).")
 (:landing-mockup-deck-title . "Itaalia keele alused")
 (:landing-mockup-share-deck . "Jaga pakki")
 (:review-complete . "Seanss lõpetatud!")
 (:review-complete-msg . "Kordasid ~a kaarti")
 (:review-again-btn . "Korda uuesti")
 (:review-translate-more . "Tõlgi rohkem")
 (:review-streak . "päevane seeria")

 ;; Dashboard
 (:dashboard-title . "Ülevaade")
 (:dashboard-cards-due . "Ootel kaardid")
 (:dashboard-total-cards . "Kaarte kokku")
 (:dashboard-mastered-cards . "Omandatud kaarte")
 (:dashboard-subscription . "Tellimus")
 (:dashboard-subscribed-until . "Tellimus kehtib kuni")
 (:dashboard-not-subscribed . "Tellimus puudub")
 (:dashboard-recent . "Viimased tõlked")
 (:dashboard-no-translations . "Tõlkeid veel pole")
 (:dashboard-streak . "Kordamise seeria")
 (:dashboard-days . "päeva")
 (:dashboard-all-caught-up . "Kõik on üle vaadatud!")
 (:dashboard-all-caught-up-hint . "Tõlgi veel, et oma kogu kasvatada.")
 (:dashboard-getting-started . "Alustamine")
 (:dashboard-tip-1 . "Tõlgi teksti, mida soovid õppida")
 (:dashboard-tip-2 . "Klõpsa \"Salvesta mälukaartidesse\" tõlgetel, mida soovid meelde jätta")
 (:dashboard-tip-3 . "Korda oma mälukaarte regulaarselt - hajutatud kordamine aitab pikaajalise mäluga")
 (:dashboard-tip-4 . "Hinda ausalt - see aitab algoritmil sinu kordamisi optimaalselt ajastada")

 ;; Account
 (:account-title . "Konto")
 (:account-subtitle . "Halda siin oma profiili, tellimust, meeldetuletusi, eksporti ja konto kustutamist.")
 (:account-profile-subtitle . "Hoia oma kuvatav nimi ja e-posti aadress ajakohasena.")
 (:account-export-subtitle . "Laadi alla koopia oma salvestatud tõlgetest, pakkidest ja kordamisandmetest.")
 (:account-deletion-title . "Konto kustutamine")
 (:account-deletion-scheduled . "Sinu konto on planeeritud kustutamiseks kuupäeval ~A.")
 (:account-deletion-cancel-hint . "Saad enne seda kuupäeva tühistada ja konto alles jätta.")
 (:account-deletion-cancel . "Tühista kustutamine")
 (:account-deletion-request . "Konto kustutamist saad taotleda igal ajal. Kustutamine on planeeritud 14 päeva pärast kinnitamist. Kui mõtled ümber, võta ühendust toega enne selle 14-päevase perioodi lõppu.")
 (:account-deletion-confirm . "Kas planeerida konto kustutamine 14 päeva pärast tänast?")
 (:account-deletion-schedule . "Planeeri kustutamine")
 (:account-reminders-title . "E-posti meeldetuletused")
 (:account-reminders-subtitle . "Vali, kas Hiisi võib saata sulle e-kirju, kui sul on midagi kordamiseks ootel.")
 (:account-reminders-opt-out . "Lülita kordamise ja jätkamise meeldetuletused välja")
 (:account-reminders-save . "Salvesta eelistused")

 ;; Subscription
 (:subscribe-title . "Lihtne hinnastus")
 (:subscribe-choose-plan . "Vali oma pakett")
 (:subscribe-start-today . "Alusta õppimist juba täna 14-päevase tasuta prooviperioodiga")
 (:subscribe-monthly . "Kuutellimus")
 (:subscribe-annual . "Aastatellimus")
 (:subscribe-founder-member . "Asutajaliige")
 (:subscribe-monthly-price . "€10")
 (:subscribe-annual-price . "€100")
 (:subscribe-founder-price . "€79")
 (:subscribe-per-month . "/kuus")
 (:subscribe-per-year . "/aastas")
 (:subscribe-monthly-desc . "600 tõlget kuus. Piiramatult õppekaarte, pakke ja kordamisi.")
 (:subscribe-unlimited-flashcards . "Piiramatu arv mälukaarte")
 (:subscribe-grammar-explanations . "Grammatika selgitused")
 (:subscribe-spaced-repetition . "Hajutatud kordamine")
 (:subscribe-annual-desc . "Kõik kuuplaani asjad. Kaks kuud tasuta.")
 (:subscribe-founder-lock . "Hind jääb samaks, kuni sinu tellimus püsib aktiivne.")
 (:subscribe-founder-badge . "Piiratud pakkumine")
 (:subscribe-founder-limit . "Ainult esimesele 100 liikmele")
 (:subscribe-manage . "Halda tellimust")
 (:subscribe-activated . "Tellimus aktiveeritud!")
 (:subscribe-thank-you . "Sinu tellimus on aktiivne. Siin saad hallata arveldust ja osta juurde tõlkeid.")
 (:subscribe-start-learning . "Alusta õppimist")
 (:subscribe-management . "Tellimuse haldamine")
 (:subscribe-active . "Aktiivne tellimus")
 (:subscribe-preapproved-access . "Eelnevalt heaks kiidetud ligipääs")
 (:subscribe-status . "Staatus:")
 (:subscribe-status-active . "Aktiivne")
 (:subscribe-status-preapproved . "Eelnevalt heaks kiidetud")
 (:subscribe-preapproved-detail . "See konto kasutab Hiisi hallatavat eelnevalt heaks kiidetud ligipääsu.")
 (:subscribe-days-remaining . "Päevi jäänud:")
 (:subscribe-renews-on . "Uueneb:")
 (:subscribe-no-subscription . "Aktiivne tellimus puudub")
 (:subscribe-access-features . "Vali pakett, et avada täielik ligipääs ja hallata arveldust ühest kohast.")
 (:subscribe-view-plans . "Vaata pakette")
 (:subscribe-faq-title . "Korduma kippuvad küsimused")
 (:subscribe-faq-trial-q . "Mis juhtub pärast tasuta prooviperioodi?")
 (:subscribe-faq-trial-a . "14-päevane prooviperiood ei nõua kaarti. Kui see lõpeb, vali tasuline pakett, et säilitada täielik ligipääs.")
 (:subscribe-faq-cancel-q . "Kas saan igal ajal tühistada?")
 (:subscribe-faq-cancel-a . "Jah! Võid oma tellimuse igal ajal tühistada. Ligipääs säilib arveldusperioodi lõpuni.")
 (:subscribe-faq-payment-q . "Milliseid makseviise aktsepteerite?")
 (:subscribe-faq-payment-a . "Aktsepteerime kõiki peamisi krediit- ja deebetkaarte meie maksepartneri Polar.sh kaudu.")
 (:subscribe-copyright . "Lambda Symbolics OÜ © 2026.")
(:subscribe-checkout-unavailable . "Maksele suunamine on ajutiselt maas. Proovi uuesti.")
(:subscribe-portal-unavailable . "Tellimuse haldus on ajutiselt maas. Proovi uuesti.")
(:subscribe-founder-sold-out . "Asutajaliikme pakkumine on välja müüdud")
(:subscribe-founder-unavailable . "Asutajaliikme pakkumine ei ole praegu saadaval.")
(:subscribe-checkout-cta . "Telli")

 ;; Errors and status
 (:error-generic . "Midagi läks valesti")
(:error-invalid-request . "Vigased päringuandmed.")
(:error-not-found . "Soovitud ressurssi ei leitud.")
(:error-forbidden . "Sul puudub sellele ligipääs.")
(:error-rate-limited . "Oota hetk ja proovi uuesti.")
 (:error-text-too-long . "Tekst on liiga pikk. Maksimaalne tõlke pikkus on 120 tähemärki.")
 (:error-input-too-long . "Sisend liiga pikk")
 (:error-unknown-source-lang . "Valitud lähtekeel ei ole toetatud.")
 (:error-unknown-target-lang . "Valitud sihtkeel ei ole toetatud.")
 (:error-unknown-language . "Tundmatu keel")
 (:error-translation-unavailable . "Tõlketeenus on ajutiselt kättesaamatu. Palun proovi hetke pärast uuesti.")
 (:error-translation-failed . "Tõlkimine ebaõnnestus")
 (:error-translation-retry . "Tõlget ei õnnestunud mitme katse järel genereerida. Palun proovi oma teksti ümber sõnastada.")
 (:error-quota-exceeded . "Tõlkelimiit täis")
 (:error-quota-exceeded-detail . "Oled kasutanud kõik oma selle kuu tõlked. Sinu kvoot lähtestub automaatselt iga kuu.")
 (:quota-low-warning . "Alles ~A tõlget. Kaaluge juurde ostmist.")
 (:top-up-button . "Osta rohkem tõlkeid")
 (:top-up-price . "5 €")
 (:top-up-amount . "300 tõlget")
(:review-session-expired . "Sinu kordamisseanss on aegunud. Alusta uut seanssi.")

 (:error-session-expired . "Sinu seanss aegus. Palun logi uuesti sisse.")
 (:error-session-invalid . "Sinu seanss ei kehti enam. Palun logi uuesti sisse.")
 (:error-custom-flashcard-generation . "Selgitust ei õnnestunud luua. Proovi uuesti.")
 ;; Institutions
 (:institutions-page-title . "Hiisi koolidele ja ülikoolidele")
 (:institutions-hero-title . "Keeleõppe tööriistad, mis on loodud klassiruumi jaoks")
 (:institutions-hero-subtitle . "Paku oma õppijatele jagatavaid kaardipakke, grammatikat arvestavat harjutamist ja püsivat kordamisrütmi, mis sobib päris õpetusega.")
 (:institutions-section-title . "Miks asutused kasutavad Hiisit")
 (:institutions-section-body . "Hiisi aitab õpetajatel muuta õppematerjali juhendatud harjutamiseks, millega õppijad päriselt kaasa jõuavad. Loo kursuse jaoks kaardipakke, jaga neid lingiga ning toeta sõnavara ja grammatika harjutamist ilma lisahalduse koormata.")
 (:institutions-benefit-1 . "Jagatavad kaardipakid ja oma ülesanded, mis sobivad teie õppekavaga.")
 (:institutions-benefit-2 . "Õppijate meeldimised ja mittemeeldimised aitavad tavapäraste tunniväljendite jaoks parimad tõlked esile tõsta.")
 (:institutions-benefit-3 . "Grammatika jaotused ning hajutatud kordamine toetavad enamat kui üksikute sõnaloendite päheõppimist.")
 (:institutions-benefit-4 . "Õpetajast lähtuv tugi inimeselt, kes kuulab tähelepanelikult ja hoolib klassiruumi vajadustest.")
 (:institutions-request-title . "Räägime sellest")
 (:institutions-request-subtitle . "Kirjelda oma asutust, keeli ja seda, millist õpet toetavat abi vajad. Vastame nädala jooksul.")
 (:institutions-aside-title . "Mis saab edasi")
 (:institutions-aside-body . "Tutvume teie vajadustega ja vastame nädala jooksul, et arutada juurdepääsu ja seadistamist teie asutuse jaoks.")
 (:institutions-field-name . "Asutuse nimi")
 (:institutions-field-name-placeholder . "Sinu ülikool")
 (:institutions-field-contact-name . "Kontaktisiku nimi")
 (:institutions-field-contact-name-placeholder . "Sinu nimi")
 (:institutions-field-contact-email . "Kontakti e-post")
 (:institutions-field-contact-email-placeholder . "sinu@ulikool.ee")
 (:institutions-field-domains . "E-posti domeenid")
 (:institutions-field-domains-placeholder . "ulikool.ee, cs.ulikool.ee")
 (:institutions-field-domains-help . "Komadega eraldatud e-posti domeenide loend sinu asutuse jaoks")
 (:institutions-field-notes . "Lisainfo")
 (:institutions-field-notes-placeholder . "Hinnanguline õpilaste arv, eelistatud arveldustsükkel, erisoovid...")
 (:institutions-submit . "Esita päring")
 (:institutions-success-title . "Aitäh - Hiisi koolidele ja ülikoolidele")
 (:institutions-success-heading . "Aitäh!")
 (:institutions-success-body . "Oleme sinu päringu kätte saanud. Vaatame üle teie asutuse vajadused ja võtame ühendust nädala jooksul.")
 (:institutions-success-back . "Tagasi avalehele")

 ;; Footer
 (:footer-privacy . "Privaatsuspoliitika")
 (:footer-terms . "Kasutustingimused")

 ;; Early software notice
 (:early-software-notice . "Hiisi on varajases arendusfaasis. Leidsid vea või on sul ettepanek?")

 ;; Privacy Policy
 (:privacy-title . "Privaatsuspoliitika")
 (:privacy-updated . "Viimati uuendatud: jaanuar 2026")
 (:privacy-who-title . "Kes me oleme")
 (:privacy-who-body . "Hiisi-d käitab Lambda Symbolics OÜ, Eestis registreeritud ettevõte. Eestis registreeritud ettevõttena järgime Euroopa Liidu üldist andmekaitsemäärust (GDPR).")
 (:privacy-collect-title . "Kogutavad andmed")
 (:privacy-collect-intro . "Kui kasutate Hiisi-d, kogume järgmist teavet:")
 (:privacy-collect-account-key . "Konto teave: ")
 (:privacy-collect-account-val . "E-posti aadress, kuvatav nimi ja turvaliselt räsitud parool.")
 (:privacy-collect-learning-key . "Õppeandmed: ")
 (:privacy-collect-learning-val . "Teie tõlked, salvestatud kaardid ja kordamise ajalugu.")
 (:privacy-collect-usage-key . "Kasutusandmed: ")
 (:privacy-collect-usage-val . "Põhilised serverilogid turvalisuse ja silumise eesmärgil.")
 (:privacy-use-title . "Kuidas me teie andmeid kasutame")
 (:privacy-use-auth-key . "Autentimine: ")
 (:privacy-use-auth-val . "Teie identiteedi kinnitamiseks ja konto turvalisuse tagamiseks.")
 (:privacy-use-service-key . "Teenuse osutamine: ")
 (:privacy-use-service-val . "Tõlkide pakkumiseks ja teie kaardikogu haldamiseks.")
 (:privacy-use-ai-key . "AI tõlked: ")
 (:privacy-use-ai-val . "Teie tõlkepäringud saadetakse vastuste genereerimiseks OpenRouterisse. OpenRouter võib päringud suunata seadistatud mudeliteenuse pakkujale. Vaadake OpenRouteri privaatsuspoliitikat, et teada saada, kuidas neid andmeid töödeldakse.")
 (:privacy-third-title . "Kolmandate osapoolte teenused")
 (:privacy-third-intro . "Kasutame järgmisi kolmandate osapoolte teenuseid:")
 (:privacy-third-openrouter-key . "OpenRouter: ")
 (:privacy-third-openrouter-val . "Automaatsete tõlkepäringute jaoks.")
 (:privacy-third-mailgun-key . "Mailgun: ")
 (:privacy-third-mailgun-val . "Konto aktiveerimis- ja tehingue-kirjade saatmiseks.")
 (:privacy-third-polar-key . "Polar.sh: ")
 (:privacy-third-polar-val . "Tellimuste maksete töötlemiseks.")
 (:privacy-cookies-title . "Küpsised")
 (:privacy-cookies-intro . "Kasutame ainult hädavajalikke küpsiseid:")
 (:privacy-cookies-auth-key . "Autentimisluba: ")
 (:privacy-cookies-auth-val . "Turvaline, HTTP-only küpsis, mis hoiab teid sisselogituna.")
 (:privacy-cookies-lang-key . "Keele eelistus: ")
 (:privacy-cookies-lang-val . "Teie eelistatud kasutajaliidese keeles meelde jätmiseks.")
 (:privacy-retention-title . "Andmete säilitamine")
 (:privacy-retention-body . "Teie andmeid säilitatakse nii kaua, kui teil on konto. Kui soovite kustutamist, planeeritakse teie konto kustutamine 14 päeva jooksul.")
 (:privacy-rights-title . "Teie õigused (GDPR)")
 (:privacy-rights-intro . "GDPR-i alusel on teil õigus:")
 (:privacy-rights-access . "Pääseda ligi oma isikuandmetele")
 (:privacy-rights-export . "Eksportida oma andmeid (saadaval aadressil /app/api/export)")
 (:privacy-rights-correct . "Nõuda ebatäpsete andmete parandamist")
 (:privacy-rights-delete . "Nõuda oma konto ja andmete kustutamist")
 (:privacy-rights-object . "Vaidlustada oma andmete töötlemist")
 (:privacy-rights-contact . "Nende õiguste kasutamiseks võtke meiega ühendust aadressil")
 (:privacy-contact-title . "Kontakt")
 (:privacy-contact-intro . "Privaatsuspuudutavate päringute jaoks:")
 (:privacy-contact-email-label . "E-post: ")
 (:privacy-address-1 . "Lambda Symbolics OÜ")
 (:privacy-address-2 . "Harju maakond, Tallinn, Kesklinna linnaosa, Tornimäe tn 5, 10145")

 ;; Terms of Service
 (:terms-title . "Kasutustingimused")
 (:terms-updated . "Viimati uuendatud: jaanuar 2026")
 (:terms-1-title . "1. Teenuse kirjeldus")
 (:terms-1-body . "Hiisi on keeleõppe rakendus, mis pakub grammatiliste selgitustega automaatseid tõlkeid ja ruumilise kordamisega kaarte. Teenust käitab Lambda Symbolics OÜ.")
 (:terms-2-title . "2. Konto registreerimine")
 (:terms-2-body . "Hiisi kasutamiseks peate looma konto kehtiva e-posti aadressiga. Teie vastutate oma konto volituste turvalisuse säilitamise eest.")
 (:terms-3-title . "3. Tellimus ja maksed")
 (:terms-3-body . "Hiisi pakub tasulisi tellimusplaane (kuu- ja aastapõhised). Tellimusi töödeldakse Polar.sh-i kaudu.")
 (:terms-3-list-1 . "Tellimused uuenevad automaatselt, kui neid ei tühistata enne uuendamise kuupäeva.")
 (:terms-3-list-2 . "Tagasimakseid pakutakse vastavalt kohaldatavatele tarbijakaitse seadustele.")
 (:terms-3-list-3 . "Maksmata jätmine põhjustab juurdepääsu kaotamise premium-funktsioonidele.")
 (:terms-4-title . "4. Aktsepteeritav kasutamine")
 (:terms-4-intro . "Te nõustute mitte:")
 (:terms-4-list-1 . "Kasutama teenust mis tahes ebaseaduslikul eesmärgil")
 (:terms-4-list-2 . "Üritama kasutuspiiranguid või turvameetmeid mööda hiilida")
 (:terms-4-list-3 . "Jagama oma konto volitusi teistega")
 (:terms-4-list-4 . "Kasutama automatiseeritud tööriistu teenusele juurdepääsuks viisil, mis halvendab jõudlust teiste jaoks")
 (:terms-5-title . "5. Sisu ja intellektuaalne omand")
 (:terms-5-body-1 . "Hiisi poolt genereeritud tõlked luuakse automaatselt ja need ei pruugi olla unikaalsed. Võite oma tõlkeid ja kaarte kasutada mis tahes isiklikul eesmärgil, kuid te ei oma automaatselt genereeritud sisu suhtes eksklusiivset autorikaitset.")
 (:terms-5-body-2 . "Hiisi rakendus, kaubamärk ja originaalsisu jäävad Lambda Symbolics OÜ omandiks.")
 (:terms-6-title . "6. Teenuse kättesaadavus")
 (:terms-6-intro . "Hiisi pakutakse \"sellisena, nagu see on\". Me ei garanteeri:")
 (:terms-6-list-1 . "Katkematut või veavaba teenust")
 (:terms-6-list-2 . "Automaatselt genereeritud tõlgete täpsust")
 (:terms-6-list-3 . "Konkreetsete funktsioonide kättesaadavust")
 (:terms-6-body . "Võime funktsioone igal ajal muuta või lõpetada.")
 (:terms-7-title . "7. Vastutuse piiramine")
 (:terms-7-body-1 . "Seaduses lubatud maksimaalses ulatuses ei vastuta Lambda Symbolics OÜ Hiisi kasutamisest tulenevate kaudsete, juhuslike, eriliste või tagajärjeliste kahjude eest.")
 (:terms-7-body-2 . "Meie koguvastutus ei ületa teenuse eest makstud summat 12 kuu jooksul enne nõude esitamist.")
 (:terms-8-title . "8. Konto lõpetamine")
 (:terms-8-body-1 . "Võime teie konto peatada või lõpetada, kui rikute neid tingimusi. Konto kustutamist võite taotleda igal ajal rakenduse kaudu.")
 (:terms-8-body-2 . "Kustutamistaotluse korral planeeritakse teie konto kustutamine 14 päeva jooksul.")
 (:terms-9-title . "9. Tingimuste muudatused")
 (:terms-9-body . "Võime neid tingimusi aeg-ajalt värskendada. Hiisi kasutamise jätkamine pärast muudatusi tähendab uute tingimustega nõustumist.")
 (:terms-10-title . "10. Kohaldatav õigus")
 (:terms-10-body . "Neid tingimusi reguleerivad Eesti seadused. Kõik vaidlused lahendatakse Eesti kohtutes.")
 (:terms-contact-title . "Kontakt")
 (:terms-contact-intro . "Küsimuste korral nende tingimuste kohta:")
 (:terms-contact-email-label . "E-post: ")
 (:terms-address-1 . "Lambda Symbolics OÜ")
 (:terms-address-2 . "Harju maakond, Tallinn, Kesklinna linnaosa, Tornimäe tn 5, 10145")

 ;; Decks
 (:decks-title . "Kaardipakid")
 (:decks-subtitle . "Loo kohandatud kaardipakke ja jaga neid teistega.")
 (:decks-create-title . "Loo kaardipakk")
 (:decks-name-placeholder . "Kaardipaki nimi")
 (:decks-desc-placeholder . "Kirjeldus")
 (:decks-create-btn . "Loo kaardipakk")
 (:decks-edit-title . "Muuda kaardipakki")
 (:decks-edit-btn . "Muuda kaardipakki")
 (:decks-update-btn . "Salvesta muudatused")
 (:decks-default-badge . "Automaatne")
 (:decks-default-description . "Seda kaardipakki hallatakse selle keelepaari jaoks automaatselt.")
 (:decks-default-readonly . "Automaatsetel kaardipakkidel on kindlad nimed ja kirjeldused.")
 (:decks-delete-btn . "Kustuta kaardipakk")
 (:decks-delete-confirm . "Kas oled kindel, et soovid selle kaardipaki kustutada?")
 (:decks-error-name-required . "Kaardipaki nimi on kohustuslik.")
 (:decks-error-name-too-long . "Kaardipaki nimi võib olla kuni ~A märki pikk.")
 (:decks-error-desc-too-long . "Kaardipaki kirjeldus võib olla kuni ~A märki pikk.")
 (:decks-error-default-readonly . "Automaatseid kaardipakke ei saa muuta.")
 (:decks-error-default-delete-forbidden . "Automaatseid kaardipakke ei saa kustutada.")
 (:decks-your-title . "Sinu kaardipakid")
 (:decks-col-updated . "Uuendatud")
 (:decks-no-decks . "Kaardipakke veel pole.")
 (:decks-open-btn . "Ava")
 (:decks-no-desc . "Kirjeldus puudub.")
 (:decks-share-title . "Jagamislink")
 (:decks-share-info . "Igaüks selle lingiga saab kaardipaki importida:")
 (:decks-share-copy . "Kopeeri link")
 (:decks-share-copied . "Kopeeritud")
 (:decks-add-from-flashcards-title . "Lisa tõlked")
 (:decks-add-from-flashcards-info . "Vali kaart, et lisada selle tõlge sellesse kaardipakki.")
 (:decks-open-flashcards . "Lisa kaartidest")
 (:decks-filter-from . "Lähtekeel")
 (:decks-filter-to . "Sihtkeel")
 (:decks-filter-any . "Mis tahes keel")
 (:decks-filter-include-assigned . "Kuva kaardid, mis on juba kaardipakis")
 (:decks-flashcards-add . "Lisa")
 (:decks-flashcards-added . "Lisatud")
 (:decks-flashcards-in-deck . "Teises kaardipakis")
 (:decks-flashcards-empty . "Ükski kaart ei vasta nendele filtritele.")
 (:decks-items-title . "Kaardipaki sisu")
 (:decks-col-original . "Originaal")
 (:decks-col-translated . "Tõlge")
 (:decks-col-lang . "Sihtkeel")
 (:decks-no-items . "Üksusi veel pole.")
 (:decks-share-page-title . "Jaga kaardipakki")
 (:decks-share-preview . "Eelvaade ja impordi see kaardipakk.")
 (:decks-import-title . "Impordi")
 (:decks-import-btn . "Impordi kaardipakk")
 (:starter-decks-title . "Teek")
 (:starter-decks-subtitle . "Impordi Hiisi ja kogukonna koostatud valmis õppepakid.")
 (:starter-decks-marketplace-btn . "Teek")
 (:starter-decks-explanation-language . "Selgituste keel")
 (:starter-decks-search-label . "Otsi")
 (:starter-decks-source-label . "Allikas")
 (:starter-decks-source-all . "Kõik pakid")
 (:starter-decks-search-placeholder . "Otsi teegist")
 (:starter-decks-apply-filters . "Rakenda filtrid")
 (:starter-decks-select-triplet-hint . "Sobivate pakkide sirvimiseks vali lähte- ja sihtkeel.")
 (:starter-decks-official-badge . "Ametlik")
 (:starter-decks-community-badge . "Kogukond")
 (:starter-decks-by-hiisi . "Hiisilt")
 (:starter-decks-preview-btn . "Eelvaade")
 (:starter-decks-card-count . "~A kaarti")
 (:starter-decks-no-results . "Ükski pakk ei vasta nendele filtritele.")
 (:starter-decks-source-cards-title . "Kaardid selles pakis")
 (:starter-decks-sample-title . "Näidiskaardid")
 (:starter-decks-generating . "Pakki genereeritakse...")
 (:starter-decks-generating-detail . "Seda pakki genereeritakse praegu sinu keelekolmiku jaoks. Hoia see leht avatuna või tule hetke pärast tagasi.")
 (:starter-decks-generation-failed . "Genereerimine ebaõnnestus")
 (:starter-decks-generation-failed-detail . "Viimane genereerimiskatse ebaõnnestus. Proovi pakki uuesti importida.")
 (:starter-decks-login-detail . "Logi sisse, et importida see pakk oma kogusse.")
 (:starter-decks-subscribe-btn . "Vaata pakette")
 (:starter-decks-subscribe-detail . "Teegi pakid on saadaval aktiivse tellimuse või prooviperioodiga.")
 (:library-submit-title . "Saada teeki")
 (:library-submit-intro . "Saada see pakk enne avaldamist haldusülevaatuseks teeki.")
 (:library-submit-btn . "Saada pakk")
 (:library-submit-approved . "Teegi jaoks heaks kiidetud")
 (:library-submit-approved-detail . "See pakk on teegis avaldatud.")
 (:library-submit-pending . "Ülevaatamisel")
 (:library-submit-pending-detail . "See pakk on saadetud ja ootab haldusülevaatust.")
 (:library-submit-rejected . "Enne avaldamist on vaja muudatusi")
 (:library-submit-rejected-detail . "See esitamine lükati tagasi. Uuenda pakki ja saada see uuesti.")
 (:library-error-empty . "Lisa vähemalt üks kaart, enne kui saadad selle paki teeki.")
 (:library-error-missing-triplet . "Igal teeki saadetava paki kaardil peab olema täielik keelekolmik.")
 (:library-error-mixed-triplet . "Kõik teeki saadetava paki kaardid peavad jagama sama keelekolmikut.")
 (:starter-deck-topic-greetings-title . "Tervitused ja tutvustused")
 (:starter-deck-topic-greetings-description . "Tervitused, nimed, viisakad põhiavaldused ja fraasid esimeseks kohtumiseks.")
 (:starter-deck-topic-travel-title . "Olulised reisiväljendid")
 (:starter-deck-topic-travel-description . "Jaamad, piletid, hinnad, abi küsimine ja liikumine.")
 (:starter-deck-topic-numbers-title . "Arvud ja hinnad")
 (:starter-deck-topic-numbers-description . "Loendamine, kogusummad, hinnad, korrused ja igapäevased kogused.")
 (:starter-deck-topic-time-title . "Aeg ja kuupäevad")
 (:starter-deck-topic-time-description . "Päevad, kuud, kohtumised, kellaajad ja suhtelised kuupäevad.")
 (:starter-deck-topic-food-title . "Restoran ja toit")
 (:starter-deck-topic-food-description . "Tellimine, toitumisvajadused, joogid, arve ja igapäevased söögikorrad kodust väljas.")
 (:starter-deck-topic-emergency-title . "Hädaolukorrad ja tervis")
 (:starter-deck-topic-emergency-description . "Arstid, apteegid, sümptomid, kehaosad ja kiire abi.")
 (:starter-deck-topic-directions-title . "Teejuhised ja transport")
 (:starter-deck-topic-directions-description . "Pööramised, peatused, piletid, perroonid ja linnas liikumine.")
 (:starter-deck-topic-school-title . "Kool ja haridus")
 (:starter-deck-topic-school-description . "Tunnid, kodutööd, eksamid, koolitarbed ja igapäevane koolielu.")
 (:starter-deck-topic-university-title . "Ülikool ja õpingud")
 (:starter-deck-topic-university-description . "Loengud, seminarid, erialad, ülesanded ja igapäevane elu ülikoolilinnakus.")

 ;; Flashcards management page
 (:flashcards-title . "Minu kaardid")
 (:flashcards-subtitle . "Kõik sinu salvestatud kaardid ühes kohas. Otsi, korrasta ja halda.")
 (:flashcards-search-placeholder . "Otsi kaarte...")
 (:flashcards-filter-button . "Filtrid")
 (:flashcards-filter-title . "Filtreeri kaarte")
 (:flashcards-filter-recollection . "Kui hästi sa neid oskad")
 (:flashcards-filter-any-recollection . "Mis tahes tase")
 (:flashcards-hide-perfected . "Peida täielikult omandatud kaardid")
 (:flashcards-col-original . "Originaal")
 (:flashcards-col-translated . "Tõlge")
 (:flashcards-no-cards . "Kaarte veel pole. Alusta tõlkimist, et neid luua!")
 (:flashcards-image-label . "Pilt")
 (:flashcards-image-upload . "Laadi pilt üles")
 (:flashcards-image-replace . "Asenda pilt")
 (:flashcards-image-remove . "Eemalda pilt")

 ;; Landing page (redesign)
 (:landing-hero-headline . "Iga sõna seletatud. Iga kordamine planeeritud. Viisteist keelt.")
 (:landing-hero-subheadline . "Hiisi on tõlkija, mis õpetab sulle grammatikat lugemise ajal, ja õppekaartide rakendus, mis ehitab end üles sellest, mida sa tegelikult tõlgid.")
 (:landing-hero-trust-line . "14 päeva tasuta. Kaarti pole vaja.")
 (:landing-credibility-languages . "15 keelt")
 (:landing-credibility-ai . "Iga sõna seletatud")
 (:landing-credibility-srs . "Hajutatud kordamine sisse ehitatud")
 (:landing-languages-title . "Toetatavad keeled")
 (:landing-step-1-title . "Kleebi lause")
 (:landing-step-1-desc . "Mis tahes pikkuses, ühes 15 keelest. Saad tõlke ja iga sõna grammatilise analüüsi.")
 (:landing-step-2-title . "Salvesta, mida tasub meeles pidada")
 (:landing-step-2-desc . "Üks klikk muudab tõlke õppekaardiks, algne lause säilib kontekstina.")
 (:landing-step-3-title . "Korda õigel hetkel")
 (:landing-step-3-desc . "Hajutatud kordamine SM-2-ga, sama algoritm, mida kasutab Anki. Kaardid, millega vaevled, tulevad varem tagasi.")
 (:landing-feature-grammar-title . "Iga sõna seletatud, sinu keeles")
 (:landing-feature-grammar-desc . "Tõlked tulevad käände, soo, aspekti ja kõneviisiga sõna-sõnalt lahti kirjutatud. Soome partitiiv, tšehhi elusus, poola aspekt, saksa daatiivi kokkutõmbed, kõik märgistatud ja seotud grammatikaviitega.")
 (:landing-feature-srs-title . "Hajutatud kordamise harjumus automatiseeritult")
 (:landing-feature-srs-desc . "SM-2 algoritm kohaneb sinu sooritusega. Rasked kaardid ilmuvad sagedamini. Kaardid, mida tead, taanduvad.")
 (:landing-feature-share-title . "Sinu pakid või kogukonna omad")
 (:landing-feature-share-desc . "Korralda õppekaardid teemapakkidesse. Jaga mis tahes pakki lingiga või sirvi kogukonna raamatukogu, et leida teiste jagatud pakke.")
 (:landing-pricing-trial-note . "Sisaldab 14 päeva tasuta prooviperioodi")
 (:landing-pricing-monthly-after . "14 päeva tasuta, seejärel ~A/kuu")
 (:landing-pricing-annual-after . "14 päeva tasuta, seejärel ~A/aasta")
 (:landing-faq-title . "Korduma kippuvad küsimused")
 (:landing-faq-trial-cap-q . "Mitu tõlget saan prooviperioodil?")
 (:landing-faq-trial-cap-a . "Saad 200 tõlget 14-päevase prooviperioodi jooksul. Pärast tellimist saad 600 kuus.")
 (:landing-final-cta-title . "Sinu esimene lause võtab viis sekundit.")
 (:landing-final-cta-subtitle . "Kleebi midagi soome, tšehhi, poola või ükskõik millises kaheteistkümnes teises keeles. Vaata, mis Hiisi sellega teeb. Neliteist päeva tasuta.")

 ;; Trial status (in-app)
 (:trial-status . "Tasuta prooviperiood")
 (:error-trial-quota-exceeded . "Proovitõlgete limiit täis")
 (:error-trial-quota-detail . "Oled kasutanud kõik 200 proovitõlget. Telli, et jätkata õppimist.")

 ;; Custom flashcards
 (:custom-flashcard-create-title . "Loo õppekaart")
 (:custom-flashcard-edit-title . "Muuda õppekaarti")
 (:custom-flashcard-original . "Algne tekst")
 (:custom-flashcard-translated . "Tõlge")
 (:custom-flashcard-lang-from . "Lähtekeel")
 (:custom-flashcard-lang-to . "Sihtkeel")
 (:custom-flashcard-note . "Õppemärkus")
 (:custom-flashcard-forms . "Grammatiline analüüs")
 (:custom-flashcard-form-term . "Termin")
 (:custom-flashcard-form-explanation . "Selgitus")
 (:custom-flashcard-add-form . "Lisa grammatiline termin")
 (:custom-flashcard-remove-form . "Eemalda")
 (:custom-flashcard-ai-fill . "Täida tehisaruga")
 (:custom-flashcard-create-btn . "Loo õppekaart")
 (:custom-flashcard-update-btn . "Salvesta muudatused")

  ;; Newsletter
  (:newsletter-email-label . "E-posti aadress")
  (:newsletter-developer-label . "Olen arendaja")
  (:newsletter-developer-hint . "saa tehnilisi uuendusi")
  (:landing-newsletter-title . "Saa Hiisi uuendusi.")
  (:landing-newsletter-body . "Liitu uudiskirjaga, et saada tooteuuendusi, infot uute keelte toe, alguskaartide ja aeg-ajalt asutajaliikme pakkumiste kohta.")
  (:landing-newsletter-fine-print . "Ei mingit rämpsposti. Ainult tooteuudised.")
  (:landing-newsletter-button . "Liitu uudiskirjaga")
  (:newsletter-unsubscribe-page-title . "Loobu Hiisi uudiskirjast")
  (:newsletter-unsubscribe-title . "Loobu tellimusest")
  (:newsletter-unsubscribe-subtitle . "Sisesta oma e-post, et lõpetada Hiisi uuenduste saamine.")
  (:newsletter-unsubscribe-button . "Loobu tellimusest")
  (:newsletter-feedback-email-required . "Sisesta oma e-posti aadress.")
  (:newsletter-feedback-email-invalid . "Sisesta kehtiv e-posti aadress.")
  (:newsletter-feedback-already-signed-up . "Oled juba kirjas. Hoiame sind kursis!")
  (:newsletter-feedback-signed-up . "Oled nimekirjas! Saadame aeg-ajalt Hiisi uuendusi.")
  (:newsletter-feedback-unsubscribed . "Kui see e-post oli nimekirjas, on see Hiisi uuendustest eemaldatud.")
  (:newsletter-feedback-generic-error . "Midagi läks valesti. Proovi uuesti.")

  ;; Issue reporting
 (:issues-open-button . "Teata veast")
 (:issues-modal-title . "Teata probleemist")
 (:issues-modal-subtitle . "Kirjelda, mis läks valesti. Sinu praegune leht lisatakse automaatselt.")
 (:issues-title-label . "Lühike pealkiri")
 (:issues-title-placeholder . "Probleemi lühikokkuvõte")
 (:issues-message-label . "Mis juhtus?")
 (:issues-message-placeholder . "Lisa palun taasesitamise sammud, oodatud tulemus ja tegelik tulemus.")
 (:issues-submit . "Saada teade")
 (:issues-cancel . "Tühista")
 (:issues-success . "Sinu veateade saadeti ära. Vaatame selle esimesel võimalusel üle.")
 (:issues-error-required . "Palun kirjelda enne saatmist probleemi.")
 (:issues-error-title-too-long . "Teate pealkiri on liiga pikk. Hoia see alla 160 märgi.")
 (:issues-error-too-long . "Teate tekst on liiga pikk. Hoia see alla 4000 märgi.")
 (:issues-error-rate-limit . "Sellest allikast on saadetud liiga palju teateid. Palun oota ja proovi hiljem uuesti.")
 (:issues-error-generic . "Probleemiteadet ei õnnestunud saata. Palun proovi uuesti.")

)
