;;; Finnish translations

(
 ;; Language metadata (used for language picker)
 (:lang-name . "Suomi")
 (:lang-flag . "🇫🇮")

 ;; Language modal (first-visit language selection)
 (:lang-modal-title . "Valitse kieli")
 (:lang-modal-subtitle . "Valitse käyttöliittymän kieli:")

 ;; Navigation
 (:nav-translate . "Käännä")
 (:nav-review . "Kertaa")
 (:nav-flashcards . "Korttini")
 (:nav-dashboard . "Hallintapaneeli")
 (:nav-decks . "Pakat")
 (:nav-logout . "Kirjaudu ulos")
 (:nav-home . "Etusivu")
 (:nav-pricing . "Hinnoittelu")
 (:nav-institutions . "Oppilaitoksille")
 (:nav-export-data . "Vie tiedot")
 (:nav-open-navigation . "Avaa valikko")
 (:theme-light . "Vaalea")
 (:theme-dark . "Tumma")

 ;; App title and branding
 (:app-title . "Hiisi - Kielten oppiminen")

 ;; Landing page
 (:landing-meta-title . "Hiisi: kieltenoppimissovellus kieliopilla ja muistikorteilla")
 (:landing-meta-description . "Hiisi on kieltenoppimissovellus. Jokaisesta kääntämästäsi lauseesta tulee muistikortti, jossa on sisäänrakennettu kielioppi ja joka ajastetaan SM-2:lla, Ankin algoritmilla. 15 kieltä.")
 (:landing-learn-more . "Lue lisää")
 (:landing-how-it-works . "Näin se toimii")
 (:landing-start-trial . "Aloita Hiisin käyttö")
 (:landing-best-value . "Paras arvo")

 ;; Auth pages
 (:auth-register . "Rekisteröidy")
 (:auth-login . "Kirjaudu")
 (:auth-email . "Sähköposti")
 (:auth-password . "Salasana")
 (:auth-password-again . "Vahvista salasana")
 (:auth-display-name . "Näyttönimi")
 (:auth-register-title . "Rekisteröidy Hiisiin")
 (:auth-register-subtitle . "Luo uusi tili")
 (:auth-login-title . "Kirjaudu Hiisiin")
 (:auth-login-subtitle . "Syötä tunnuksesi")
 (:auth-login-invalid-credentials . "Virheellinen sähköposti tai salasana.")
 (:auth-login-rate-limited . "Liian monta kirjautumisyritystä. Odota muutama minuutti ja yritä uudelleen.")
(:auth-register-rate-limited . "Liikaa rekisteröintiyrityksiä. Odota muutama minuutti ja yritä uudelleen.")
(:auth-email-invalid . "Anna kelvollinen sähköpostiosoite.")
(:auth-password-too-short . "Salasanan on oltava vähintään 8 merkkiä pitkä.")
(:auth-passwords-mismatch . "Salasanat eivät täsmää.")
(:auth-display-name-invalid . "Näyttönimen on oltava 1–100 merkkiä pitkä.")
(:auth-register-email-exists . "Tällä sähköpostiosoitteella on jo tili.")
(:auth-register-unavailable . "Rekisteröityminen on tilapäisesti poissa käytöstä. Yritä myöhemmin uudelleen.")
(:auth-register-plan-required . "Valitse tilaus ennen tilin luomista.")
(:auth-preapproved-email-unrecognized . "Käytä kutsussa olevaa sähköpostiosoitetta tai valitse tilaus ennen tilin luomista.")
(:auth-institution-register . "Tuletko oppilaitoksesta?")
(:auth-institution-stage-title . "Oppilaitoksen käyttöoikeus")
(:auth-institution-stage-subtitle . "Käytä koulun tai yliopiston sähköpostia. Kelvolliset tilit avataan oppilaitoksen kautta sähköpostivahvistuksen jälkeen.")
(:auth-institution-title . "Rekisteröidy oppilaitoksesi kautta")
(:auth-institution-subtitle . "Käytä koulun tai yliopiston sähköpostiosoitetta. Jos oppilaitoksesi on jo määritetty Hiisiin, tilisi avataan sähköpostivahvistuksen jälkeen oppilaitoksen kautta; henkilökohtaisen suunnitelman rekisteröintiin kuuluu erillinen 14 päivän kokeilu.")
(:auth-institution-benefit-email . "Käytä koulun tai yliopiston sähköpostiosoitetta.")
(:auth-institution-benefit-access . "Kelvolliset tilit saavat oppilaitoksen käyttöoikeuden sähköpostivahvistuksen jälkeen.")
(:auth-institution-benefit-fallback . "Jos domainia ei tunnisteta, valitse henkilökohtainen suunnitelma tai pyydä oppilaitostasi ottamaan yhteyttä Hiisiin.")
(:auth-see-included . "Katso, mitä sisältyy")
(:auth-institution-check-access . "Tarkista käyttöoikeus")
(:auth-institution-email-eligible-title . "Oppilaitoksen käyttöoikeus vahvistettu")
(:auth-institution-email-eligible-detail . "Jatka tällä sähköpostilla luodaksesi tilin. Käyttöoikeus avataan sähköpostivahvistuksen jälkeen.")
(:auth-institution-change-email . "Käytä toista sähköpostia")
(:auth-institution-outcome-note . "Jos koulusi tai yliopistosi tarjoaa Hiisi-käyttöoikeuden, tilisi avataan sähköpostivahvistuksen jälkeen. Jos domain ei ole kelvollinen, valitse henkilökohtainen paketti aloittaaksesi 14 päivän kokeilun.")
(:auth-institution-personal-plan-link . "Näytä henkilökohtaiset paketit")
(:auth-institution-domain-unrecognized . "Emme vielä tunnista tuota oppilaitoksen sähköpostidomainia. Valitse henkilökohtainen paketti aloittaaksesi 14 päivän kokeilun, tai pyydä oppilaitostasi ottamaan yhteyttä Hiisiin.")
(:subscribe-institution-callout-title . "Käytätkö Hiisiä koulun tai yliopiston kautta?")
(:subscribe-institution-callout-body . "Rekisteröidy oppilaitoksen sähköpostilla, niin Hiisi avaa käyttöoikeuden automaattisesti, jos oppilaitoksesi on jo määritetty.")
(:auth-activation-email-send-failed . "Aktivointisähköpostin lähettäminen epäonnistui. Yritä uudelleen.")
 (:auth-forgot-password . "Unohditko salasanan?")
 (:auth-no-account . "Eikö sinulla ole tiliä?")
 (:auth-have-account . "Onko sinulla jo tili?")
 (:auth-google . "Google")
 (:auth-google-login-failed . "Google-kirjautuminen epäonnistui. Yritä uudelleen.")
 (:auth-account-created . "Tili luotu!")
 (:auth-check-email . "Tarkista sähköpostisi aktivointilinkin varalta.")
 (:auth-redirect-login . "Uudelleenohjaus kirjautumiseen")
 (:auth-seconds . "sekunnissa...")
 (:auth-go-now . "Siirry nyt")
 (:auth-not-activated . "Tiliä ei ole aktivoitu")
 (:auth-activate-title . "Aktivoi tilisi!")
 (:auth-activated . "Tili aktivoitu!")
 (:auth-activated-message . "Tilisi on aktivoitu. Voit nyt käyttää Hiisiä.")
 (:auth-redirecting . "Uudelleenohjaus")
 (:auth-go-to-app . "Siirry sovellukseen")
 (:onboarding-title . "Miten Hiisi toimii")
 (:onboarding-subtitle . "Käännä oikeaa tekstiä, tarkastele kielioppia, tallenna hyödyllisiä kohtia ja kertaa niitä myöhemmin.")
 (:onboarding-translate-detail . "Aloita oikeasta tekstistä. Hiisi näyttää käännöksen, vastinmuodot ja seuraavat opiskelutoimet yhdessä paikassa.")
 (:onboarding-grammar-detail . "Avaa kielioppierittely nähdäksesi, mitkä muodot vastaavat toisiaan lauseessa ja mitä kukin osa tekee.")
 (:onboarding-review-detail . "Tallenna hyödylliset käännökset ja kertaa niitä myöhemmin hajautetulla kertauksella, jotta ne pysyvät pitkäkestoisessa muistissa.")
 (:onboarding-decks-detail . "Ryhmittele hyödylliset kohdat pakkoihin, jaa niitä muille ja pidä toisiinsa liittyvä aineisto yhdessä.")
 (:onboarding-back . "Takaisin")
 (:onboarding-next . "Seuraava")
 (:onboarding-skip . "Ohita opas")
 (:auth-resend-title . "Lähetä aktivointisähköposti uudelleen")
 (:auth-resend-subtitle . "Anna sähköpostiosoitteesi saadaksesi uuden aktivointilinkin.")
 (:auth-resend-button . "Lähetä aktivointisähköposti uudelleen")
 (:auth-resend-success . "Aktivointisähköposti lähetetty!")
 (:auth-resend-success-detail . "Tarkista postilaatikkosi uuden aktivointilinkin saamiseksi.")
 (:auth-resend-rate-limited . "Odota muutama minuutti ennen kuin pyydät uutta aktivointisähköpostia.")
 (:auth-resend-cooldown . "Voit pyytää uuden sähköpostin ~a sekunnin kuluttua.")
 (:auth-back-to-login . "Takaisin kirjautumiseen")
 (:auth-forgot-password-title . "Unohtunut salasana")
 (:auth-forgot-password-subtitle . "Anna sähköpostiosoitteesi ja lähetämme sinulle linkin salasanan vaihtamiseen.")
 (:auth-send-reset-link . "Lähetä nollauslinkki")
 (:auth-reset-email-sent . "Linkki lähetetty!")
 (:auth-reset-email-sent-detail . "Jos tällä sähköpostiosoitteella on tili, saat pian salasanan nollauslinkin.")
 (:auth-reset-rate-limited . "Odota muutama minuutti ennen kuin pyydät uutta salasanan nollausta.")
 (:auth-reset-invalid-token . "Tämä salasanan nollauslinkki on virheellinen tai vanhentunut.")
 (:auth-reset-password-title . "Nollaa salasana")
 (:auth-reset-password-subtitle . "Syötä uusi salasanasi alle.")
 (:auth-new-password . "Uusi salasana")
 (:auth-confirm-new-password . "Vahvista uusi salasana")
 (:auth-reset-password . "Nollaa salasana")
 (:auth-password-changed . "Salasana vaihdettu!")
 (:auth-password-changed-detail . "Salasanasi on vaihdettu onnistuneesti. Voit nyt kirjautua sisään uudella salasanallasi.")
 (:auth-change-password-title . "Vaihda salasana")
 (:auth-change-password-subtitle . "Päivitä tilisi salasana.")
 (:auth-current-password . "Nykyinen salasana")
 (:auth-change-password . "Vaihda salasana")
 (:auth-back-to-app . "Takaisin sovellukseen")
 (:auth-password-updated . "Salasana päivitetty!")
 (:auth-password-updated-detail . "Salasanasi on päivitetty onnistuneesti.")
(:auth-current-password-invalid . "Nykyinen salasana on väärä.")
(:auth-new-password-same . "Uuden salasanan on oltava eri kuin nykyisen salasanan.")

 ;; Email copy
 (:email-common-hi . "Hei")
 (:email-common-tagline . "Hiisi - Opiskele kääntämällä")
 (:email-activation-subject . "Aktivoi Hiisi-tilisi")
 (:email-activation-title . "Tervetuloa Hiisiin")
 (:email-activation-body . "Kiitos rekisteröitymisestä. Aktivoi tilisi klikkaamalla alla olevaa linkkiä:")
 (:email-activation-button . "Aktivoi tili")
 (:email-activation-copy-link . "Tai kopioi tämä linkki")
 (:email-activation-expiry . "Linkki vanhenee 24 tunnin kuluttua.")
 (:email-reset-subject . "Palauta Hiisi-salasanasi")
 (:email-reset-title . "Salasanan palautuspyyntö")
 (:email-reset-body . "Saimme pyynnön palauttaa salasanasi. Aseta uusi salasana klikkaamalla alla olevaa linkkiä:")
 (:email-reset-button . "Palauta salasana")
 (:email-reset-expiry . "Linkki vanhenee 1 tunnin kuluttua.")
 (:email-reset-ignore . "Jos et pyytänyt salasanan palautusta, voit jättää tämän viestin huomiotta.")
 (:email-reminder-subject-due . "Aika kerrata Hiisi-kortteja")
 (:email-reminder-subject-streak . "Pidä Hiisi-putkesi käynnissä")
 (:email-reminder-cards-due . "korttia odottaa kertausta")
 (:email-reminder-keep-going . "Viime kertauksesta on muutama päivä. Viisi minuuttia tänään riittää pitämään sen, mitä olet jo oppinut, muistissasi.")
 (:email-reminder-button . "Kertaa nyt")
 (:email-reminder-settings . "Muistutusten asetukset")
 (:email-reminder-preview-title . "Sinua odottavat kortit")
 (:email-reminder-translation-label . "Käännös")
 (:email-reminder-more-due-today . "muuta korttia odottaa tänään")
 (:email-trial-subject . "Miten Hiisi-kokeilusi sujuu?")
 (:email-trial-expiring . "Ilmainen Hiisi-kokeilusi päättyy huomenna.")
 (:email-trial-feedback . "Nautitko Hiisistä? Kerro meille, mikä auttaa sinua eniten.")
 (:email-trial-strengths . "Voit kääntää oikeita tekstejä, tallentaa niistä muistikortteja ja oppia hajautetulla kertauksella.")
 (:email-trial-reply . "Vastaa tähän sähköpostiin, niin viestisi menee suoraan Hiisin tiimille.")
 (:email-trial-button . "Valitse tilaus")
 (:email-trial-manage . "Hallitse tilausta")
 (:email-trial-contact . "Kirjoita meille")
 (:email-plan-nudge-subject . "Käännöksesi odottavat")
 (:email-plan-nudge-title . "Käännöksesi odottavat")
 (:email-plan-nudge-intro . "Rekisteröidyit Hiisiin, mutta et ole vielä valinnut tilausta.")
 (:email-plan-nudge-benefits-intro . "Tilauksella saat:")
 (:email-plan-nudge-benefit-translations . "600 käännöstä kuukaudessa kielioppierittelyineen")
 (:email-plan-nudge-benefit-flashcards . "Rajattomasti muistikortteja hajautetulla kertauksella")
 (:email-plan-nudge-benefit-decks . "Omat pakat, joita voit järjestää ja jakaa")
 (:email-plan-nudge-pricing . "Tilaukset alkavat 10 eurosta kuukaudessa, tai säästä vuositilauksella 100 euroa vuodessa (kaksi kuukautta ilmaiseksi).")
 (:email-plan-nudge-feedback . "Jos jokin Hiisissä ei toimi sinulle, vastaa tähän sähköpostiin. Viestisi menee suoraan Hiisin tiimille.")
 (:email-plan-nudge-button . "Valitse tilaus")
 (:email-plan-nudge-unsubscribe . "Lopeta nämä sähköpostit")
 (:email-plan-nudge-unsubscribe-done-title . "Tilausviestit on poistettu käytöstä")
 (:email-plan-nudge-unsubscribe-done-body . "Et saa enää muistutusviestejä tilauksen valinnasta.")
 (:email-plan-nudge-unsubscribe-invalid-title . "Tämä linkki ei ole kelvollinen")
 (:email-plan-nudge-unsubscribe-invalid-body . "Tämä peruutuslinkki puuttuu, on vanhentunut tai ei ole enää kelvollinen.")
 (:email-invite-subject . "Kutsu Hiisiin")
 (:email-invite-title . "Sinut on kutsuttu käyttämään Hiisiä")
 (:email-invite-intro . "Sinut on kutsuttu käyttämään Hiisiä ilmaiseksi testaajana, arvostettuna ystävänä tai molempina.")
 (:email-invite-details . "Luo tili alla olevalla painikkeella ja aloita käännösten ja muistikorttien käyttö.")
 (:email-invite-button . "Luo tili")
 (:email-invite-issue-reporting . "Jos jokin hajoaa tai tuntuu väärältä, jokaisen sivun alareunassa on ongelmaraportointipainike.")
 (:email-issue-completed-subject . "Ilmoittamasi Hiisi-ongelma on korjattu")
 (:email-issue-completed-title . "Ongelma on korjattu")
 (:email-issue-completed-label . "Ongelma")
 (:email-issue-completed-followup . "Avaa Hiisi, tarkista korjaus tai jatka siitä, mihin jäit.")
 (:email-issue-completed-button . "Avaa Hiisi")
 (:email-issue-completed-open-link . "Avaa sivu")

 ;; Translation page
 (:translate-title . "Käännä")
 (:landing-public-translate-title . "Kokeile täällä")
 (:landing-public-translate-cta-title . "Jatka tästä")
 (:landing-public-translate-cta-body . "Tallenna käännöksiä opiskelukorteiksi ja kertaa niitä myöhemmin.")
 (:landing-public-translate-cta-button . "Aloita maksuton kokeilu ja jatka oppimista")
 (:translate-input-label . "Käännettävä teksti")
 (:translate-input-placeholder . "Kirjoita käännettävä teksti...")
 (:translate-from . "Lähdekieli:")
 (:translate-to . "Kohdekieli:")
 (:translate-select-target-placeholder . "Valitse kohdekieli")
 (:translate-submit . "Käännä")
 (:translate-auto-detect . "Mikä tahansa (tunnista automaattisesti)")
 (:translate-empty-state . "Käännä sana tai fraasi, niin näet täällä tuloksen, kielioppierittelyn ja opiskelutoiminnot.")
 (:translate-select-deck-placeholder . "Valitse pakka (valinnainen)")
 (:translate-new-deck . "Uusi pakka")
 (:translate-add-to-deck . "Lisää pakkaan")
 (:translate-bookmark . "Tallenna")
 (:translate-bookmarked . "Tallennettu")
 (:translate-retry . "Luo uudelleen")
 (:translate-like-tooltip . "Hyvä käännös")
 (:translate-dislike-tooltip . "Huono käännös - pyydä uusi")
 (:translate-dislike-confirm . "Tämä luo uuden käännöksen. Jatketaanko?")
 (:pronunciation-label . "Ääntäminen")
 (:pronunciation-show . "Näytä ääntäminen")
 (:pronunciation-hide . "Piilota ääntäminen")
 (:grammar-term-examples . "Esimerkit")
 (:grammar-term-related . "Liittyvät termit")
 (:grammar-term-modal-title . "Kielioppitermi")
 (:grammar-term-empty . "Valitse korostettu termi, niin näet lisätiedot.")
 (:extension-login-required . "Kirjaudu Hiisiin ennen selainlaajennuksen käyttöä.")
 (:extension-session-invalid . "Hiisi-istuntosi ei ole enää voimassa. Kirjaudu uudelleen.")
 (:extension-activation-required . "Aktivoi Hiisi-tilisi ennen selainlaajennuksen käyttöä.")
 (:extension-subscription-required . "Aloita Hiisi-kokeilu ennen selainlaajennuksen käyttöä.")

 ;; Translation and Flashcards
 (:lang-auto . "Auto")
 (:lang-unknown . "?")
 (:lang-target . "Kohde")
 (:translate-deck-create-title . "Luo uusi pakka")
 (:translate-deck-name-label . "Pakan nimi")
 (:translate-deck-name-placeholder . "esim. Suomen perusteet")
 (:translate-deck-description-label . "Kuvaus (valinnainen)")
 (:translate-deck-cancel . "Peruuta")
 (:translate-deck-create . "Luo")
 (:translate-rate-label . "Arvioi käännös")
 (:flashcards-delete . "Poista")
 (:flashcards-delete-confirm . "Haluatko varmasti poistaa tämän kortin?")
 (:flashcards-deck-search-placeholder . "Hae pakkoja...")
 (:flashcards-no-decks . "Ei vielä pakkoja. Luo ensin yksi!")
 (:flashcards-deck-cancel . "Peruuta")
 (:flashcards-recollection-tooltip . "Muistijälki: ~A")
 (:flashcards-recollection-poor . "Heikko")
 (:flashcards-recollection-fair . "Kohtalainen")
 (:flashcards-recollection-normal . "Normaali")
 (:flashcards-recollection-strong . "Vahva")
 (:flashcards-recollection-very-strong . "Erittäin vahva")

 ;; Flashcard review
 (:review-title . "Kertaus")
 (:review-session-title . "Kertausjakso")
 (:review-session-subtitle . "Harjoittele tallennettuja muistikorttejasi")
 (:review-selector-title . "Valitse, mitä kertaat")
 (:review-selector-subtitle . "Valitse pakka tai kielipari, johon haluat keskittyä tässä kertausjaksossa.")
 (:review-by-deck . "Kertaa pakan mukaan")
 (:review-by-language-pair . "Kertaa kieliparin mukaan")
 (:review-all-cards . "Kertaa kaikki kortit")
 (:review-cards-due . "korttia jonossa")
 (:review-deck-caught-up . "Kaikki kertaattu")
 (:review-all-caught-up . "Kaikki kertaattu!")

 (:review-no-cards . "Ei kerattavia kortteja")
 (:review-no-cards-desc . "Sinulla ei ole muistikortteja kerattavana juuri nyt.")
 (:review-no-cards-hint . "Käännä tekstiä ja napsauta \"Tallenna muistikortteihin\" rakentaaksesi pakkasi!")
 (:review-start-translating . "Aloita kääntäminen")
 (:review-click-reveal . "Napsauta paljastaaksesi vastauksen")
 (:review-grammar-breakdown . "Kielioppiselitys")
 (:review-how-well . "Muistitko sen?")
 (:review-again . "En")
 (:review-hard . "Juuri ja juuri")
 (:review-good . "Kyllä")
 (:review-easy . "Helposti")
 (:review-progress . "Kortti ~a/~a")
 (:review-correct-count . "Oikein")
 (:review-wrong-count . "Väärin")
 (:landing-mockup-forgot-detail . "Verbin \"olvidar\" (unohtaa) yksikön 1. persoonan preteriti")
 (:landing-mockup-keys-detail . "Possessiivi \"mis\" feminiinisen monikkosubstantiivin \"llaves\" (avaimet) kanssa")
 (:landing-mockup-home-detail . "Idiomaattinen \"en casa\" (kotona) -- artikkelia ei tarvita")
 (:landing-mockup-possession-note . "Espanjan preteriti ilmaisee päättyneitä menneitä tekoja. Subjektipronomini jätetään yleensä pois, koska verbin pääte kertoo puhujan.")
 (:landing-mockup-children-detail . "Substantiivin \"Kind\" (lapsi) nominatiivin monikko -- monikko lisää -er")
 (:landing-mockup-played-detail . "Verbin \"spielen\" (leikkiä) monikon 3. persoonan preteriti")
 (:landing-mockup-garden-detail . "Datiivi: \"in dem\" supistuu muotoon \"im\", maskuliinisen substantiivin \"Garten\" (puutarha) kanssa")
 (:landing-mockup-czech-note . "Saksa käyttää preteritia kirjallisessa kerronnassa. \"Im\" on supistunut muoto sanoista \"in\" + \"dem\" (datiivin artikkeli).")
 (:landing-mockup-deck-title . "Italian perusteet")
 (:landing-mockup-share-deck . "Jaa pakka")
 (:review-complete . "Kertaus valmis!")
 (:review-complete-msg . "Kertasit ~a korttia")
 (:review-again-btn . "Kertaa uudelleen")
 (:review-translate-more . "Käännä lisää")
 (:review-streak . "päivän putki")

 ;; Dashboard
 (:dashboard-title . "Hallintapaneeli")
 (:dashboard-welcome-title . "Käännä ensimmäinen tekstisi")
 (:dashboard-welcome-subtitle . "Käännä hyödyllinen ilmaus, tallenna se pakkaan ja kertaa se silloin, kun siitä on eniten hyötyä.")
 (:dashboard-take-quick-tour . "Katso nopea kierros")
 (:dashboard-cards-due . "Kerattavat kortit")
 (:dashboard-total-cards . "Kortit yhteensä")
 (:dashboard-mastered-cards . "Hallittuja kortteja")
 (:dashboard-subscription . "Tilaus")
 (:dashboard-subscribed-until . "Tilattu asti")
 (:dashboard-trial-ends . "Kokeilujakso päättyy")
 (:dashboard-not-subscribed . "Ei tilausta")
 (:dashboard-recent . "Viimeaikaiset käännökset")
 (:dashboard-no-translations . "Ei käännöksiä vielä")
 (:dashboard-streak . "Kertausputki")
 (:dashboard-days . "päivää")
 (:dashboard-all-caught-up . "Kaikki on kerrattu!")
 (:dashboard-all-caught-up-hint . "Käännä lisää ja kasvata kokoelmaasi.")
 (:dashboard-no-cards-title . "Luo ensimmäiset muistikorttisi")
 (:dashboard-no-cards-hint . "Käännä tekstiä ja tallenna hyödylliset ilmaukset kasvattaaksesi kokoelmaasi.")
 (:dashboard-first-use-checklist-title . "Ensimmäiset vaiheet")
 (:dashboard-first-use-checklist-translate . "Tee ensimmäinen käännöksesi")
 (:dashboard-first-use-checklist-card . "Tallenna ensimmäinen korttisi")
 (:dashboard-first-use-checklist-review . "Suorita ensimmäinen kertauksesi")
 (:dashboard-getting-started . "Näin pääset alkuun")
 (:dashboard-tip-1 . "Käännä tekstiä, jonka haluat oppia")
 (:dashboard-tip-2 . "Napsauta \"Tallenna muistikortteihin\" käännöksissä, jotka haluat muistaa")
 (:dashboard-tip-3 . "Kertaa muistikorttisi säännöllisesti - hajautettu toisto auttaa muistamaan pitkäaikaisesti")
 (:dashboard-tip-4 . "Arvioi rehellisesti - se auttaa algoritmia ajoittamaan kertauksesi optimaalisesti")

 ;; Account
 (:account-title . "Tili")
 (:account-subtitle . "Hallitse täällä profiiliasi, tilaustasi, muistutuksia, vientiä ja tilin poistamista.")
 (:account-profile-subtitle . "Pidä näyttönimesi ja sähköpostiosoitteesi ajan tasalla.")
 (:account-export-subtitle . "Lataa kopio tallennetuista käännöksistäsi, pakoistasi ja kertausdatastasi.")
 (:account-deletion-title . "Tilin poisto")
 (:account-deletion-scheduled . "Tilisi on ajastettu poistettavaksi päivänä ~A.")
 (:account-deletion-cancel-hint . "Voit perua ennen tätä päivää ja pitää tilisi.")
 (:account-deletion-cancel . "Peru poisto")
 (:account-deletion-request . "Voit pyytää tilin poistamista milloin tahansa. Poisto ajoitetaan 14 päivän päähän vahvistuksesta. Jos muutat mielesi, ota yhteyttä tukeen ennen kuin tämä 14 päivän jakso päättyy.")
 (:account-deletion-confirm . "Ajastetaanko tilin poisto 14 päivän päähän tästä päivästä?")
 (:account-deletion-schedule . "Ajasta poisto")
 (:account-reminders-title . "Sähköpostimuistutukset")
 (:account-reminders-subtitle . "Valitse, saako Hiisi lähettää sinulle sähköpostia, kun sinulla on jotain kerrattavaa.")
 (:account-reminders-opt-out . "Poista kertaamis- ja jatkomuistutukset käytöstä")
 (:account-reminders-save . "Tallenna asetukset")

 ;; Subscription
 (:subscribe-title . "Selkeä hinnoittelu")
 (:subscribe-choose-plan . "Valitse tilauksesi")
 (:subscribe-start-today . "Aloita oppiminen tänään 14 päivän ilmaisella kokeilulla")
 (:subscribe-monthly . "Kuukausittain")
 (:subscribe-annual . "Vuosittain")
 (:subscribe-founder-member . "Perustajajäsen")
 (:subscribe-monthly-price . "€10")
 (:subscribe-annual-price . "€100")
 (:subscribe-founder-price . "€79")
 (:subscribe-founder-monthly-equivalent . "€6,58/kk, laskutetaan vuosittain")
 (:subscribe-founder-savings . "Säästä €41/vuosi verrattuna kuukausimaksuun")
 (:subscribe-monthly-billing-equivalent . "€10/kk, laskutetaan kuukausittain")
 (:subscribe-monthly-billing-note . "Joustava kuukausimaksu")
 (:landing-pricing-comparison-title . "Nopea vertailu")
 (:subscribe-per-month . "/kk")
 (:subscribe-per-year . "/vuosi")
 (:subscribe-monthly-desc . "600 käännöstä kuukaudessa. Rajaton määrä muistikortteja, pakkoja ja kertauksia.")
 (:subscribe-unlimited-flashcards . "Rajattomat muistikortit")
 (:subscribe-grammar-explanations . "Kielioppiselitykset")
 (:subscribe-spaced-repetition . "Hajautettu toisto")
 (:subscribe-annual-desc . "Kaikki kuukausitilauksesta. Kaksi kuukautta ilmaiseksi.")
 (:subscribe-founder-lock . "Hinta pysyy samana niin kauan kuin tilauksesi on aktiivinen.")
 (:subscribe-founder-badge . "Rajoitettu tarjous")
 (:subscribe-founder-limit . "Vain ensimmäiselle 100 jäsenelle")
 (:subscribe-manage . "Hallitse tilausta")
 (:subscribe-activated . "Tilaus aktivoitu!")
 (:subscribe-thank-you . "Tilauksesi on aktiivinen. Täällä voit hallita laskutusta ja ostaa lisää käännöksiä.")
 (:subscribe-start-learning . "Aloita oppiminen")
 (:subscribe-management . "Tilauksen hallinta")
 (:subscribe-active . "Aktiivinen tilaus")
 (:subscribe-preapproved-access . "Ennalta hyväksytty käyttöoikeus")
 (:subscribe-status . "Tila:")
 (:subscribe-status-active . "Aktiivinen")
 (:subscribe-status-preapproved . "Ennalta hyväksytty")
 (:subscribe-preapproved-detail . "Tällä tilillä on Hiisin hallinnoima ennalta hyväksytty käyttöoikeus.")
 (:subscribe-days-remaining . "Päiviä jäljellä:")
 (:subscribe-renews-on . "Uusiutuu:")
 (:subscribe-no-subscription . "Ei aktiivista tilausta")
 (:subscribe-access-features . "Valitse tilaus, niin saat täyden käyttöoikeuden ja laskutuksen hallinnan samasta paikasta.")
 (:subscribe-view-plans . "Näytä tilausvaihtoehdot")
 (:subscribe-faq-title . "Usein kysytyt kysymykset")
 (:subscribe-faq-trial-q . "Mitä tapahtuu ilmaisen kokeilun jälkeen?")
 (:subscribe-faq-trial-a . "14 päivän kokeilu ei vaadi maksukorttia. Kun se päättyy, valitse maksullinen tilaus säilyttääksesi täyden pääsyn.")
 (:subscribe-faq-cancel-q . "Voinko peruuttaa milloin tahansa?")
 (:subscribe-faq-cancel-a . "Kyllä! Voit peruuttaa tilauksesi milloin tahansa. Pääsy säilyy laskutuskauden loppuun asti.")
 (:subscribe-faq-payment-q . "Mitä maksutapoja hyväksytte?")
 (:subscribe-faq-payment-a . "Hyväksymme kaikki yleisimmät luotto- ja pankkikortit maksukumppanimme Polar.sh:n kautta.")
 (:subscribe-copyright . "Lambda Symbolics OÜ © 2026.")
(:subscribe-checkout-unavailable . "Maksuun siirtyminen on tilapäisesti poissa käytöstä. Yritä uudelleen.")
(:subscribe-portal-unavailable . "Tilauksen hallinta on tilapäisesti poissa käytöstä. Yritä uudelleen.")
(:subscribe-founder-sold-out . "Perustajajäsenen tarjous on loppuunmyyty")
(:subscribe-founder-unavailable . "Perustajajäsenen tarjous ei ole juuri nyt saatavilla.")
(:subscribe-checkout-cta . "Tilaa")

 ;; Errors and status
 (:error-generic . "Jokin meni pieleen")
(:error-invalid-request . "Virheelliset pyyntötiedot.")
(:error-not-found . "Pyydettyä kohdetta ei löytynyt.")
(:error-forbidden . "Sinulla ei ole oikeutta tähän.")
(:error-rate-limited . "Odota hetki ja yritä uudelleen.")
 (:error-text-too-long . "Teksti on liian pitkä. Käännöksen enimmäispituus on 120 merkkiä.")
 (:error-input-too-long . "Syöte liian pitkä")
 (:error-unknown-source-lang . "Valitsemaasi lähdekieltä ei tueta.")
 (:error-unknown-target-lang . "Valitsemaasi kohdekieltä ei tueta.")
 (:error-unknown-language . "Tuntematon kieli")
 (:error-translation-unavailable . "Käännöspalvelu ei ole tilapäisesti käytettävissä. Yritä hetken kuluttua uudelleen.")
 (:error-translation-failed . "Käännös epäonnistui")
 (:error-translation-retry . "Käännöstä ei voitu luoda useiden yritysten jälkeen. Yritä muotoilla tekstisi toisin.")
 (:error-quota-exceeded . "Käännösraja saavutettu")
 (:error-quota-exceeded-detail . "Olet käyttänyt kaikki käännöksesi tälle kuukaudelle. Kiintiösi nollautuu automaattisesti joka kuukausi.")
 (:quota-low-warning . "Vain ~A käännöstä jäljellä. Harkitse lisää ostamista.")
 (:top-up-button . "Osta lisää käännöksiä")
 (:top-up-price . "5 €")
 (:top-up-amount . "300 käännöstä")
(:review-session-expired . "Kertausistuntosi on vanhentunut. Aloita uusi istunto.")

 (:error-session-expired . "Istuntosi vanheni. Kirjaudu uudelleen.")
 (:error-session-invalid . "Istuntosi ei ole enää voimassa. Kirjaudu uudelleen.")
 (:error-custom-flashcard-generation . "Selitystä ei voitu luoda. Yritä uudelleen.")
 ;; Institutions
 (:institutions-page-title . "Hiisi kouluille ja yliopistoille")
 (:institutions-hero-title . "Kieltenopetuksen työkalut, jotka on tehty luokkahuoneeseen")
 (:institutions-hero-subtitle . "Anna opiskelijoillesi jaettavia pakkoja, kieliopin huomioivaa harjoittelua ja tasaisen kertausrytmin, joka sopii oikeaan opetukseen.")
 (:institutions-section-title . "Miksi oppilaitokset käyttävät Hiisiä")
 (:institutions-section-body . "Hiisi auttaa opettajia muuttamaan oppimateriaalin ohjatuksi harjoitteluksi, jossa opiskelijat pysyvät mukana. Rakenna pakkoja kurssille, jaa ne linkillä ja tue sanaston sekä kieliopin harjoittelua ilman ylimääräistä hallinnollista työtä.")
 (:institutions-benefit-1 . "Jaettavat pakat ja omat tehtävät, jotka sopivat opetussuunnitelmaanne.")
 (:institutions-benefit-2 . "Opiskelijoiden tykkäykset ja epätykkäykset nostavat vahvimmat käännökset esiin tavallisissa opetuksen ilmauksissa.")
 (:institutions-benefit-3 . "Kielioppierittelyt ja jaksotettu kertaus tukevat enemmän kuin irrallisten sanalistojen ulkoa opettelua.")
 (:institutions-benefit-4 . "Opettajalähtöistä tukea ihmiseltä, joka kuuntelee tarkasti ja välittää luokkahuoneen tarpeista.")
 (:institutions-request-title . "Aloitetaan keskustelu")
 (:institutions-request-subtitle . "Kerro oppilaitoksestasi, kielistänne ja siitä, millaista opetuksen tukea tarvitsette. Otamme yhteyttä viikon kuluessa.")
 (:institutions-aside-title . "Mitä seuraavaksi tapahtuu")
 (:institutions-aside-body . "Tutustumme tarpeisiinne ja otamme yhteyttä viikon kuluessa sopimaan pääsystä ja käyttöönotosta oppilaitoksellenne.")
 (:institutions-field-name . "Oppilaitoksen nimi")
 (:institutions-field-name-placeholder . "Yliopistosi")
 (:institutions-field-contact-name . "Yhteyshenkilön nimi")
 (:institutions-field-contact-name-placeholder . "Nimesi")
 (:institutions-field-contact-email . "Yhteyssähköposti")
 (:institutions-field-contact-email-placeholder . "sina@yliopisto.fi")
 (:institutions-field-domains . "Sähköpostidomainit")
 (:institutions-field-domains-placeholder . "yliopisto.fi, cs.yliopisto.fi")
 (:institutions-field-domains-help . "Pilkulla erotettu luettelo oppilaitoksesi sähköpostidomaineista")
 (:institutions-field-notes . "Lisätiedot")
 (:institutions-field-notes-placeholder . "Arvioitu opiskelijamäärä, toivottu laskutuskausi, erityisvaatimukset...")
 (:institutions-submit . "Lähetä tiedustelu")
 (:institutions-success-title . "Kiitos - Hiisi kouluille ja yliopistoille")
 (:institutions-success-heading . "Kiitos!")
 (:institutions-success-body . "Olemme vastaanottaneet yhteydenottosi. Käymme läpi oppilaitoksesi tarpeet ja palaamme asiaan viikon kuluessa.")
 (:institutions-success-back . "Takaisin etusivulle")

 ;; Footer
 (:footer-privacy . "Tietosuojakäytäntö")
 (:footer-terms . "Käyttöehdot")

 ;; Early software notice
 (:early-software-notice . "Hiisi on varhaisessa kehitysvaiheessa. Löysitkö virheen tai onko sinulla ehdotus?")

 ;; Tietosuojakäytäntö
 (:privacy-title . "Tietosuojakäytäntö")
 (:privacy-updated . "Päivitetty viimeksi: tammikuu 2026")
 (:privacy-who-title . "Keitä olemme")
 (:privacy-who-body . "Hiisiä ylläpitää Lambda Symbolics OÜ, Virossa rekisteröity yritys. Virolaisena yrityksenä noudatamme Euroopan unionin yleistä tietosuoja-asetusta (GDPR).")
 (:privacy-collect-title . "Mitä tietoja keräämme")
 (:privacy-collect-intro . "Kun käytät Hiisiä, keräämme seuraavat tiedot:")
 (:privacy-collect-account-key . "Tilitiedot: ")
 (:privacy-collect-account-val . "Sähköpostiosoite, näyttönimi ja turvallisesti hajautettu salasana.")
 (:privacy-collect-learning-key . "Oppimisdata: ")
 (:privacy-collect-learning-val . "Käännöksesi, tallennetut muistikortit ja kertaushistoria.")
 (:privacy-collect-usage-key . "Käyttödata: ")
 (:privacy-collect-usage-val . "Peruspalvelinlokit turvallisuus- ja virheenkorjaustarkoituksiin.")
 (:privacy-use-title . "Miten käytämme tietojasi")
 (:privacy-use-auth-key . "Tunnistautuminen: ")
 (:privacy-use-auth-val . "Henkilöllisyytesi varmistamiseen ja tilisi suojaamiseen.")
 (:privacy-use-service-key . "Palvelun tuottaminen: ")
 (:privacy-use-service-val . "Käännösten tarjoamiseen ja muistikorttikokoelmasi hallintaan.")
 (:privacy-use-ai-key . "Tekoälykäännökset: ")
 (:privacy-use-ai-val . "Käännöspyyntösi lähetetään OpenRouteriin vastausten tuottamista varten. OpenRouter voi välittää pyynnöt määritetylle mallipalveluntarjoajalle. Katso OpenRouterin tietosuojakäytäntö, miten se käsittelee näitä tietoja.")
 (:privacy-third-title . "Kolmannen osapuolen palvelut")
 (:privacy-third-intro . "Käytämme seuraavia kolmannen osapuolen palveluja:")
 (:privacy-third-openrouter-key . "OpenRouter: ")
 (:privacy-third-openrouter-val . "Automaattisia käännöspyyntöjä varten.")
 (:privacy-third-mailgun-key . "Mailgun: ")
 (:privacy-third-mailgun-val . "Tilin aktivointi- ja transaktiosähköpostien lähettämiseen.")
 (:privacy-third-polar-key . "Polar.sh: ")
 (:privacy-third-polar-val . "Tilausmaksujen käsittelyyn.")
 (:privacy-cookies-title . "Evästeet")
 (:privacy-cookies-intro . "Käytämme vain välttämättömiä evästeitä:")
 (:privacy-cookies-auth-key . "Tunnistautumistunniste: ")
 (:privacy-cookies-auth-val . "Turvallinen, vain HTTP-yhteyden kautta käytettävä eväste, joka pitää sinut kirjautuneena.")
 (:privacy-cookies-lang-key . "Kieliasetus: ")
 (:privacy-cookies-lang-val . "Muistamaan valitsemasi käyttöliittymäkielen.")
 (:privacy-retention-title . "Tietojen säilytys")
 (:privacy-retention-body . "Tietojasi säilytetään niin kauan kuin ylläpidät tiliä. Kun pyydät poistamista, tilisi ajastetaan poistettavaksi 14 päivän kuluttua.")
 (:privacy-rights-title . "Oikeutesi (GDPR)")
 (:privacy-rights-intro . "GDPR:n perusteella sinulla on oikeus:")
 (:privacy-rights-access . "Saada pääsy henkilötietoihisi")
 (:privacy-rights-export . "Viedä tietosi (saatavilla osoitteessa /app/api/export)")
 (:privacy-rights-correct . "Pyytää virheellisten tietojen oikaisua")
 (:privacy-rights-delete . "Pyytää tilisi ja tietojesi poistamista")
 (:privacy-rights-object . "Vastustaa tietojesi käsittelyä")
 (:privacy-rights-contact . "Näiden oikeuksien käyttämiseksi ota yhteyttä osoitteeseen")
 (:privacy-contact-title . "Yhteystiedot")
 (:privacy-contact-intro . "Tietosuojaan liittyvissä kysymyksissä:")
 (:privacy-contact-email-label . "Sähköposti: ")
 (:privacy-address-1 . "Lambda Symbolics OÜ")
 (:privacy-address-2 . "Harju maakond, Tallinn, Kesklinna linnaosa, Tornimäe tn 5, 10145")

 ;; Käyttöehdot
 (:terms-title . "Käyttöehdot")
 (:terms-updated . "Päivitetty viimeksi: tammikuu 2026")
 (:terms-1-title . "1. Palvelun kuvaus")
 (:terms-1-body . "Hiisi on kieltenoppimissovellus, joka tarjoaa automaattisia käännöksiä kielioppiselityksillä sekä hajautettuun kertaukseen perustuvia muistikortteja. Palvelun tarjoaa Lambda Symbolics OÜ.")
 (:terms-2-title . "2. Tilin rekisteröinti")
 (:terms-2-body . "Hiisin käyttö edellyttää tilin luomista voimassa olevalla sähköpostiosoitteella. Olet vastuussa tunnustesi turvallisuudesta.")
 (:terms-3-title . "3. Tilaukset ja maksut")
 (:terms-3-body . "Hiisi tarjoaa maksullisia tilauksia (kuukausi ja vuosi). Tilaukset käsitellään Polar.sh:n kautta.")
 (:terms-3-list-1 . "Tilaukset uusiutuvat automaattisesti, ellei niitä peruta ennen uusimispäivää.")
 (:terms-3-list-2 . "Hyvityksiä myönnetään sovellettavan kuluttajansuojalainsäädännön mukaisesti.")
 (:terms-3-list-3 . "Maksun laiminlyönti johtaa premium-ominaisuuksien menettämiseen.")
 (:terms-4-title . "4. Hyväksyttävä käyttö")
 (:terms-4-intro . "Sitoudut olemaan:")
 (:terms-4-list-1 . "Käyttämättä palvelua laittomiin tarkoituksiin")
 (:terms-4-list-2 . "Kiertämättä käyttörajoituksia tai tietoturvatoimia")
 (:terms-4-list-3 . "Jakamatta tilitunnuksiasi muille")
 (:terms-4-list-4 . "Käyttämättä automaattisia työkaluja tavalla, joka heikentää palvelun suorituskykyä muille")
 (:terms-5-title . "5. Sisältö ja immateriaalioikeudet")
 (:terms-5-body-1 . "Hiisin tuottamat käännökset luodaan automaattisesti, eivätkä ne välttämättä ole yksilöllisiä. Voit käyttää käännöksiäsi ja muistikorttejasi henkilökohtaisiin tarkoituksiin, mutta et saa yksinoikeudellista tekijyyttä automaattisesti tuotettuun sisältöön.")
 (:terms-5-body-2 . "Hiisi-sovellus, brändi ja alkuperäinen sisältö ovat Lambda Symbolics OÜ:n omaisuutta.")
 (:terms-6-title . "6. Palvelun saatavuus")
 (:terms-6-intro . "Hiisi tarjotaan \"sellaisena kuin se on\". Emme takaa:")
 (:terms-6-list-1 . "Keskeytyksetöntä tai virheetöntä palvelua")
 (:terms-6-list-2 . "Automaattisesti tuotettujen käännösten tarkkuutta")
 (:terms-6-list-3 . "Tiettyjen ominaisuuksien saatavuutta")
 (:terms-6-body . "Voimme muuttaa tai lopettaa ominaisuuksia milloin tahansa.")
 (:terms-7-title . "7. Vastuunrajoitus")
 (:terms-7-body-1 . "Lain sallimassa enimmäislaajuudessa Lambda Symbolics OÜ ei vastaa mistään välillisistä, satunnaisista, erityisistä tai seurannaisvahingoista, jotka aiheutuvat Hiisin käytöstä.")
 (:terms-7-body-2 . "Kokonaisvastuumme ei ylitä palvelusta maksamaasi summaa vaatimusta edeltävien 12 kuukauden ajalta.")
 (:terms-8-title . "8. Tilin päättäminen")
 (:terms-8-body-1 . "Voimme keskeyttää tai lopettaa tilisi, jos rikot näitä ehtoja. Voit pyytää tilin poistamista milloin tahansa sovelluksessa.")
 (:terms-8-body-2 . "Poistopyynnön jälkeen tilisi ajastetaan poistettavaksi 14 päivän kuluttua.")
 (:terms-9-title . "9. Ehtojen muutokset")
 (:terms-9-body . "Voimme päivittää näitä ehtoja ajoittain. Hiisin käytön jatkaminen muutosten jälkeen tarkoittaa uusien ehtojen hyväksymistä.")
 (:terms-10-title . "10. Sovellettava laki")
 (:terms-10-body . "Näihin ehtoihin sovelletaan Viron lakia. Mahdolliset riidat ratkaistaan Viron tuomioistuimissa.")
 (:terms-contact-title . "Yhteystiedot")
 (:terms-contact-intro . "Jos sinulla on kysyttävää näistä ehdoista:")
 (:terms-contact-email-label . "Sähköposti: ")
 (:terms-address-1 . "Lambda Symbolics OÜ")
 (:terms-address-2 . "Harju maakond, Tallinn, Kesklinna linnaosa, Tornimäe tn 5, 10145")

 ;; Decks
 (:decks-title . "Pakkat")
 (:decks-subtitle . "Luo omia pakkoja ja jaa niitä muiden kanssa.")
 (:decks-create-title . "Luo pakka")
 (:decks-name-placeholder . "Pakan nimi")
 (:decks-desc-placeholder . "Kuvaus")
 (:decks-create-btn . "Luo pakka")
 (:decks-edit-title . "Muokkaa pakkaa")
 (:decks-edit-btn . "Muokkaa pakkaa")
 (:decks-actions-title . "Pakan toiminnot")
 (:decks-card-actions-title . "Kortin toiminnot")
 (:decks-update-btn . "Tallenna muutokset")
 (:decks-default-badge . "Automaattinen")
 (:decks-default-description . "Tätä pakkaa hallitaan automaattisesti tälle kieliparille.")
 (:decks-default-readonly . "Automaattisten pakkojen nimet ja kuvaukset ovat kiinteitä.")
 (:decks-delete-btn . "Poista pakka")
 (:decks-delete-confirm . "Haluatko varmasti poistaa tämän pakan?")
 (:decks-error-name-required . "Pakan nimi on pakollinen.")
 (:decks-error-name-too-long . "Pakan nimi saa olla enintään ~A merkkiä.")
 (:decks-error-desc-too-long . "Pakan kuvaus saa olla enintään ~A merkkiä.")
 (:decks-error-default-readonly . "Automaattisia pakkoja ei voi muokata.")
 (:decks-error-default-delete-forbidden . "Automaattisia pakkoja ei voi poistaa.")
 (:decks-your-title . "Omat pakkat")
 (:decks-col-updated . "Päivitetty")
 (:decks-no-decks . "Ei vielä pakkoja.")
 (:decks-open-btn . "Avaa")
 (:decks-view-deck-btn . "Näytä pakka")
 (:decks-start-review . "Aloita kertaus")
 (:decks-no-desc . "Ei kuvausta.")
 (:decks-share-title . "Jakolinkki")
 (:decks-share-info . "Kuka tahansa voi tuoda pakan tällä linkillä:")
 (:decks-share-copy . "Kopioi linkki")
 (:decks-share-copied . "Kopioitu")
 (:decks-add-from-flashcards-title . "Lisää muistikortteja")
 (:decks-add-from-flashcards-info . "Valitse kortti ja lisää sen käännös tähän pakkaan.")
 (:decks-create-new-flashcard . "Luo uusi muistikortti")
 (:decks-open-flashcards . "Lisää olemassa olevia muistikortteja")
 (:decks-filter-from . "Lähdekieli")
 (:decks-filter-to . "Kohdekieli")
 (:decks-filter-any . "Mikä tahansa kieli")
 (:decks-filter-include-assigned . "Näytä myös kortit, jotka ovat jo pakassa")
 (:decks-flashcards-add . "Lisää")
 (:decks-flashcards-added . "Lisätty")
 (:decks-flashcards-in-deck . "Toisessa pakassa")
 (:decks-flashcards-empty . "Yksikään kortti ei vastaa näitä suodattimia.")
 (:decks-items-title . "Pakan sisältö")
 (:decks-col-original . "Alkuperäinen")
 (:decks-col-translated . "Käännös")
 (:decks-col-lang . "Kohdekieli")
 (:decks-no-items . "Ei vielä sisältöä.")
 (:decks-share-page-title . "Jaa pakka")
 (:decks-share-preview . "Esikatsele ja tuo tämä pakka.")
 (:decks-import-title . "Tuo")
 (:decks-import-btn . "Tuo pakka")
 (:starter-decks-title . "Kirjasto")
 (:starter-decks-subtitle . "Tuo Hiisin ja yhteisön tarjoamia valmiita pakkoja.")
 (:starter-decks-marketplace-btn . "Kirjasto")
 (:starter-decks-explanation-language . "Selityskieli")
 (:starter-decks-search-label . "Etsi")
 (:starter-decks-source-label . "Lähde")
 (:starter-decks-source-all . "Kaikki pakat")
 (:starter-decks-change-language . "Vaihda")
 (:starter-decks-filters-button . "Suodattimet")
 (:starter-decks-search-placeholder . "Etsi kirjastosta")
 (:starter-decks-apply-filters . "Käytä suodattimia")
 (:starter-decks-select-triplet-hint . "Valitse lähtö- ja kohdekieli selataksesi sopivia pakkoja.")
 (:starter-decks-official-badge . "Virallinen")
 (:starter-decks-official-by-hiisi . "Hiisin virallinen")
 (:starter-decks-community-badge . "Yhteisö")
 (:starter-decks-by-hiisi . "Hiisiltä")
 (:starter-decks-preview-btn . "Esikatsele")
 (:starter-decks-card-count . "~A korttia")
 (:starter-decks-no-results . "Yksikään pakka ei vastaa näitä suodattimia.")
 (:starter-decks-source-cards-title . "Tämän pakan kortit")
 (:starter-decks-more-cards-included . "+~A muuta korttia mukana.")
 (:starter-decks-sample-title . "Esimerkkikortit")
 (:starter-decks-generating . "Valmistellaan pakkaasi: ~A")
 (:starter-decks-generating-detail . "Tuomme sen kokoelmaasi heti, kun se on valmis. Voit jatkaa kirjaston selaamista tai palata hetken kuluttua.")
 (:starter-decks-generation-failed . "Luonti epäonnistui")
 (:starter-decks-generation-failed-detail . "Viimeisin luontiyritys epäonnistui. Yritä tuoda pakka uudelleen.")
 (:starter-decks-login-detail . "Kirjaudu sisään tuodaksesi tämän pakan kokoelmaasi.")
 (:starter-decks-subscribe-btn . "Näytä hinnat")
 (:starter-decks-subscribe-detail . "Kirjaston pakat ovat käytettävissä aktiivisella tilauksella tai kokeilujaksolla.")
 (:library-submit-title . "Lähetä kirjastoon")
 (:library-submit-intro . "Lähetä tämä pakka kirjastoon ylläpidon tarkistettavaksi ennen julkaisua.")
 (:library-submit-btn . "Lähetä pakka")
 (:library-submit-approved . "Hyväksytty kirjastoon")
 (:library-submit-approved-detail . "Tämä pakka on julkaistu kirjastossa.")
 (:library-submit-pending . "Arvioitavana")
 (:library-submit-pending-detail . "Tämä pakka on lähetetty ja odottaa ylläpidon tarkistusta.")
 (:library-submit-rejected . "Vaatii muutoksia ennen julkaisua")
 (:library-submit-rejected-detail . "Tämä lähetys hylättiin. Päivitä pakka ja lähetä se uudelleen.")
 (:library-error-empty . "Lisää vähintään yksi kortti ennen kuin lähetät tämän pakan kirjastoon.")
 (:library-error-missing-triplet . "Jokaisella kirjastoon lähetettävän pakan kortilla täytyy olla täydellinen kielikolmikko.")
 (:library-error-mixed-triplet . "Kaikkien kirjastoon lähetettävän pakan korttien täytyy jakaa sama kielikolmikko.")
 (:starter-deck-topic-greetings-title . "Tervehdykset ja esittäytyminen")
 (:starter-deck-topic-greetings-description . "Tervehdyksiä, nimiä, kohteliaita perusilmaisuja ja ensitapaamisen fraaseja.")
 (:starter-deck-topic-travel-title . "Keskeiset matkailuilmaisut")
 (:starter-deck-topic-travel-description . "Asemat, liput, hinnat, avun pyytäminen ja liikkuminen.")
 (:starter-deck-topic-numbers-title . "Luvut ja hinnat")
 (:starter-deck-topic-numbers-description . "Laskemista, summia, hintoja, kerroksia ja arjen määriä.")
 (:starter-deck-topic-time-title . "Aika ja päivämäärät")
 (:starter-deck-topic-time-description . "Päivät, kuukaudet, tapaamiset, kellonajat ja suhteelliset päivämäärät.")
 (:starter-deck-topic-food-title . "Ravintola ja ruoka")
 (:starter-deck-topic-food-description . "Tilaaminen, ruokavaliot, juomat, lasku ja tavalliset ateriat kodin ulkopuolella.")
 (:starter-deck-topic-emergency-title . "Hätätilanteet ja terveys")
 (:starter-deck-topic-emergency-description . "Lääkärit, apteekit, oireet, kehonosat ja kiireellinen apu.")
 (:starter-deck-topic-directions-title . "Reittiohjeet ja liikenne")
 (:starter-deck-topic-directions-description . "Kääntyminen, pysäkit, liput, laiturit ja liikkuminen kaupungissa.")
 (:starter-deck-topic-school-title . "Koulu ja opiskelu")
 (:starter-deck-topic-school-description . "Tunnit, kotitehtävät, kokeet, koulutarvikkeet ja arjen kouluelämä.")
 (:starter-deck-topic-university-title . "Yliopisto ja opinnot")
 (:starter-deck-topic-university-description . "Luennot, seminaarit, pääaineet, tehtävät ja arjen kampuselämä.")

 ;; Flashcards management page
 (:flashcards-title . "Korttini")
 (:flashcards-subtitle . "Kaikki tallennetut korttisi yhdessä paikassa. Hae, järjestä ja hallitse.")
 (:flashcards-search-placeholder . "Hae kortteja...")
 (:flashcards-filter-button . "Suodattimet")
 (:flashcards-filter-title . "Suodata kortteja")
 (:flashcards-filter-recollection . "Kuinka hyvin osaat ne")
 (:flashcards-filter-any-recollection . "Mikä tahansa osaamistaso")
 (:flashcards-hide-perfected . "Piilota täysin osatut kortit")
 (:flashcards-col-original . "Alkuperäinen")
 (:flashcards-col-translated . "Käännös")
 (:flashcards-no-cards . "Ei vielä kortteja. Aloita kääntäminen luodaksesi niitä!")
 (:flashcards-image-label . "Kuva")
 (:flashcards-image-upload . "Lähetä kuva")
 (:flashcards-image-replace . "Vaihda kuva")
 (:flashcards-image-remove . "Poista kuva")
 (:flashcards-pagination-label . "Muistikorttisivut")
 (:flashcards-pagination-status . "Sivu ~A / ~A")
 (:flashcards-pagination-previous . "Edellinen")
 (:flashcards-pagination-next . "Seuraava")

 ;; Landing page (redesign)
 (:landing-hero-headline . "Jokainen sana selitettynä. Jokainen kertaus ajastettuna. Viisitoista kieltä.")
 (:landing-hero-headline-v1 . "Käännä lauseita helposti ja lue kielioppi omalla kielelläsi.")
 (:landing-hero-headline-v2 . "Hiisi varmistaa, ettet unohda jokaista kääntämääsi lausetta.")
 (:landing-hero-headline-v3 . "Muuta kääntämäsi lauseet sanastoksi, jota osaat käyttää.")
 (:landing-hero-subheadline . "Lisää mikä tahansa lause kirjanmerkkeihin, niin Hiisi antaa sinulle käännöksen, kieliopin, ääntämisen ja muistikortin, joka palaa kerrattavaksi.")
 (:landing-hero-trust-line . "14 päivää ilmaiseksi. Maksukorttia ei tarvita.")
 (:landing-credibility-languages . "Viisitoista kieltä")
 (:landing-credibility-flashcards . "Älykkäät muistikortit")
 (:landing-credibility-pronunciation . "Ääntämisopas")
 (:landing-languages-title . "Valitse kieli, jota olet aikonut opetella")
 (:landing-video-title . "Paina play ja tutustu Hiisiin kunnolla")
 (:landing-video-placeholder-label . "Hiisin tuote-esittelyvideon paikkavaraus")
 (:landing-video-placeholder-eyebrow . "Tuotevideo")
 (:landing-video-placeholder-copy . "Lyhyt tuotevideo näyttää tässä kirjanmerkin, kieliopin, ääntämisen ja kertauksen työnkulun.")
 (:landing-problem-title . "Viime viikolla kääntämäsi lause. Osaatko sanoa sen nyt?")
 (:landing-problem-body-1 . "Se hetki tulee usein vastaan. Näet ilmauksen. Liität sen kääntäjään. Merkitys tuntuu selvältä siinä hetkessä. Viikko kuluu. Sanamuoto on kadonnut muistista, ja merkitys katoaa sen mukana.")
 (:landing-problem-body-2 . "Käännös säilyttää merkityksen sillä hetkellä, kun luet sen. Mutta lauseen oppiminen vaatii yleensä neljä erillistä työkalua:")
 (:landing-problem-tool-1 . "Kääntäjän merkitystä varten")
 (:landing-problem-tool-2 . "Kielioppiviitteen rakennetta varten")
 (:landing-problem-tool-3 . "Ääntämisoppaan ääntä varten")
 (:landing-problem-tool-4 . "Muistikorttisovelluksen muistissa pitämistä varten")
 (:landing-problem-body-3 . "Kaikkien neljän työkalun käyttäminen vie aikaa. Ja seuraava lause on kadonnut ennen kuin saat muistikortin valmiiksi.")
 (:landing-bookmark-title . "Mitä tapahtuu, kun lisäät lauseen kirjanmerkkeihin Hiisissä")
 (:landing-bookmark-body . "Yksi napautus. Hiisi tekee lauseesta muutamassa sekunnissa rakenteisen oppimiskohteen, joka on valmis opiskeltavaksi. Lause jää kirjastoosi käännöksen ja kieliopin kanssa.")
 (:landing-bookmark-benefit-1 . "Alkuperäisen lauseen ja selkeän käännöksen")
 (:landing-bookmark-benefit-2 . "Ääntämisen kansainvälisellä foneettisella aakkostolla, IPA:lla")
 (:landing-bookmark-benefit-3 . "Kieliopin selitettynä sillä kielellä, jolla haluat lukea selitykset")
 (:landing-bookmark-benefit-4 . "Väreillä yhdistetyt sanat näyttävät, mikä käännöksen osa kuuluu mihinkin alkuperäiseen osaan")
 (:landing-bookmark-benefit-5 . "Muistikortin, joka palaa, kun muistisi tarvitsee sitä")
 (:landing-bookmark-cta . "Lisää ensimmäinen lause kirjanmerkkeihin")
 (:landing-use-cases-title . "Mihin voit käyttää Hiisiä")
 (:landing-use-cases-body . "Yksi lause riittää alkuun. Kaikki, mitä luet tai kuulet uudella kielellä, toimii Hiisissä.")
 (:landing-use-case-lyrics . "Sanat laulusta, jota kuuntelet yhä uudelleen")
 (:landing-use-case-articles . "Artikkelit kielellä, jota opettelet")
 (:landing-use-case-messages . "Viestit äidinkielisiltä ystäviltä")
 (:landing-use-case-media . "Tallentamasi repliikit elokuvista tai podcasteista")
 (:landing-use-case-current-page . "Sivu, jota luet juuri nyt")
 (:landing-benefits-title . "Rakennettu itseopiskelijoille ja opiskelijoille")
 (:landing-benefit-grammar-title . "Kielioppi sillä kielellä, jolla jo ajattelet")
 (:landing-benefit-grammar-body . "Lue ranskan kielioppia englanniksi tai espanjan kielioppia puolaksi. Huomiosi pysyy lauseessa, jota opettelet.")
 (:landing-benefit-colour-title . "Sanat yhdistetty väreillä")
 (:landing-benefit-colour-body . "Sana ja sen käännös jakavat saman värin. Näet jokaisen sanan merkityksen yhdellä silmäyksellä.")
 (:landing-benefit-pronunciation-title . "Ääntäminen, jonka voit lukea")
 (:landing-benefit-pronunciation-body . "Jokaisessa lauseessa on kirjoitettu ääntämisopas, samanlainen kuin sanakirjoissa. Näet, miltä lause kuulostaa ennen kuin sanot sen.")
 (:landing-benefit-schedule-title . "Muistikortit, jotka ajastavat itse itsensä")
 (:landing-benefit-schedule-body . "Jokaisesta kirjanmerkitystä lauseesta tulee kortti. Ankin taustalla oleva SM-2-algoritmi päättää, milloin se palaa, joten kertaat sen, minkä olet juuri unohtamassa.")
 (:landing-benefit-decks-title . "Aihepakkoja tulevia tilanteita varten")
 (:landing-benefit-decks-body . "Matkustatko ensi kuussa? Aloitatko uuden työn? Tuo valmis pakka ravintoloita tai haastatteluja varten ja kertaa ensimmäisestä päivästä alkaen.")
 (:landing-benefit-languages-title . "Viisitoista kieltä, kaikki suunnat")
 (:landing-benefit-languages-body . "Käännä espanjasta ranskaksi tai englannista saksaksi. Hiisi käsittelee kaikki suunnat koko kielijoukossa.")
 (:landing-benefits-cta . "Kokeile Hiisiä")
 (:landing-inside-title . "Miltä oppiminen Hiisissä näyttää")
 (:landing-inside-body . "Avaa Hiisi. Tämän päivän kortit odottavat, jokainen niistä tallentamasi lause, johon käännös ja kielioppi on jo liitetty. Näetkö uuden lauseen, jonka haluat säilyttää? Lisää se kirjanmerkkeihin. Se päätyy huomisen kertauspinoon.")
 (:landing-inside-flow-due . "Tänään odottavat kortit")
 (:landing-inside-flow-bookmark . "Tallenna uusi lause")
 (:landing-inside-flow-review . "Huomisen kertauspino")
 (:landing-step-1-title . "Liitä lause")
 (:landing-step-1-desc . "Minkä mittaista tahansa, millä tahansa viidestätoista kielestä. Saat käännöksen ja jokaisen sanan kieliopin erittelyn.")
 (:landing-step-2-title . "Tallenna se, mikä kannattaa muistaa")
 (:landing-step-2-desc . "Yhdellä napsautuksella käännös muuttuu muistikortiksi, alkuperäinen lause säilyy kontekstina.")
 (:landing-step-3-title . "Kertaa oikealla hetkellä")
 (:landing-step-3-desc . "Jaksotettu kertaus SM-2-algoritmilla, samalla kuin Ankissa. Kortit, joiden kanssa kamppailet, palaavat aiemmin.")
 (:landing-feature-grammar-title . "Jokainen sana selitettynä, sinun kielelläsi")
 (:landing-feature-grammar-desc . "Käännökset sisältävät sijamuodon, suvun, aspektin ja moduksen sana sanalta. Suomen partitiivi, tšekin elollisuus, puolan aspekti, saksan datiiviset yhdistelmät, kaikki merkittynä ja linkitettynä kielioppiviitteeseen.")
 (:landing-feature-srs-title . "Jaksotetun kertauksen rutiini automatisoituna")
 (:landing-feature-srs-desc . "SM-2-algoritmi mukautuu suoritukseesi. Vaikeat kortit näkyvät useammin. Helpot kortit väistyvät.")
 (:landing-feature-share-title . "Omat pakkasi tai yhteisön")
 (:landing-feature-share-desc . "Järjestä muistikortit aiheittain pakkoihin. Jaa mikä tahansa pakka linkillä tai selaa yhteisökirjastoa ja löydä muiden jakamia pakkoja.")
 (:landing-pricing-trial-note . "14 päivää ilmaista kokeilua mukana")
 (:landing-pricing-monthly-after . "14 päivää ilmaiseksi, sitten ~A/kuukausi")
 (:landing-pricing-annual-after . "14 päivää ilmaiseksi, sitten ~A/vuosi")
 (:landing-faq-title . "Usein kysytyt kysymykset")
 (:landing-faq-trial-cap-q . "Kuinka monta käännöstä saan kokeilujakson aikana?")
 (:landing-faq-trial-cap-a . "Saat 200 käännöstä 14 päivän kokeilujakson aikana. Tilauksen jälkeen saat 600 kuukaudessa.")
 (:landing-final-cta-title . "Ensimmäinen lauseesi vie viisi sekuntia.")
 (:landing-final-cta-subtitle . "Liitä mitä tahansa suomeksi, tšekiksi, puolaksi tai millä tahansa kahdestatoista muusta kielestä. Katso, mitä Hiisi tekee sille. Neljätoista päivää ilmaiseksi.")

 ;; Trial status (in-app)
 (:trial-status . "Ilmainen kokeilu")
 (:error-trial-quota-exceeded . "Kokeilukäännösten raja saavutettu")
 (:error-trial-quota-detail . "Olet käyttänyt kaikki 200 kokeilukäännöstä. Tilaa jatkaaksesi oppimista.")

 ;; Custom flashcards
 (:custom-flashcard-create-title . "Luo muistikortti")
 (:custom-flashcard-edit-title . "Muokkaa muistikorttia")
 (:custom-flashcard-original . "Alkuperäinen teksti")
 (:custom-flashcard-translated . "Käännös")
 (:custom-flashcard-lang-from . "Lähdekieli")
 (:custom-flashcard-lang-to . "Kohdekieli")
 (:custom-flashcard-note . "Opetuksellinen huomautus")
 (:custom-flashcard-forms . "Kieliopin erittely")
 (:custom-flashcard-form-term . "Termi")
 (:custom-flashcard-form-explanation . "Selitys")
 (:custom-flashcard-add-form . "Lisää kielioppitermi")
 (:custom-flashcard-remove-form . "Poista")
 (:custom-flashcard-ai-fill . "Täytä tekoälyn avulla")
 (:custom-flashcard-create-btn . "Luo muistikortti")
 (:custom-flashcard-update-btn . "Tallenna muutokset")

  ;; Newsletter
  (:newsletter-email-label . "Sähköpostiosoite")
  (:newsletter-developer-label . "Olen kehittäjä")
  (:newsletter-developer-hint . "vastaanota teknisiä päivityksiä")
  (:landing-newsletter-title . "Saa Hiisi-päivityksiä.")
  (:landing-newsletter-body . "Liity uutiskirjeeseen, niin saat tuotepäivityksiä, tietoa uusista kielistä, aloituspakoista ja satunnaisista perustajajäsenen eduista.")
  (:landing-newsletter-fine-print . "Ei roskapostia. Vain tuotepäivityksiä.")
  (:landing-newsletter-button . "Liity uutiskirjeeseen")
  (:newsletter-unsubscribe-page-title . "Peru Hiisin uutiskirje")
  (:newsletter-unsubscribe-title . "Peru tilaus")
  (:newsletter-unsubscribe-subtitle . "Anna sähköpostisi peruuttaaksesi Hiisi-päivitykset.")
  (:newsletter-unsubscribe-button . "Peru tilaus")
  (:newsletter-feedback-email-required . "Anna sähköpostiosoitteesi.")
  (:newsletter-feedback-email-invalid . "Anna kelvollinen sähköpostiosoite.")
  (:newsletter-feedback-already-signed-up . "Olet jo listalla. Pidämme sinut ajan tasalla!")
  (:newsletter-feedback-signed-up . "Olet listalla! Lähetämme silloin tällöin Hiisi-päivityksiä.")
  (:newsletter-feedback-unsubscribed . "Jos tämä sähköposti oli tilattu, se on poistettu Hiisi-päivityksistä.")
  (:newsletter-feedback-generic-error . "Jotain meni pieleen. Yritä uudelleen.")

  ;; Ongelmailmoitukset
 (:issues-open-button . "Ilmoita virheestä")
 (:issues-modal-title . "Ilmoita ongelmasta")
 (:issues-modal-subtitle . "Kuvaile, mikä meni pieleen. Nykyinen sivu liitetään mukaan automaattisesti.")
 (:issues-title-label . "Lyhyt otsikko")
 (:issues-title-placeholder . "Lyhyt yhteenveto ongelmasta")
 (:issues-message-label . "Mitä tapahtui?")
 (:issues-message-placeholder . "Kerro toistovaiheet, odotettu toiminta ja mitä tapahtui sen sijaan.")
 (:issues-submit . "Lähetä ilmoitus")
 (:issues-cancel . "Peruuta")
 (:issues-success . "Ilmoituksesi lähetettiin. Käymme sen läpi mahdollisimman pian.")
 (:issues-error-required . "Kuvaile ongelma ennen lähettämistä.")
 (:issues-error-title-too-long . "Ilmoituksen otsikko on liian pitkä. Pidä se alle 160 merkin pituisena.")
 (:issues-error-too-long . "Ilmoitusteksti on liian pitkä. Pidä se alle 4000 merkin.")
 (:issues-error-rate-limit . "Tästä lähteestä on lähetetty liikaa ilmoituksia. Odota hetki ja yritä myöhemmin uudelleen.")
 (:issues-error-generic . "Ongelmailmoituksen lähettäminen epäonnistui. Yritä uudelleen.")

)
