;;; Parisian French translations
;;; Keep keys in parity with en.lisp.

(
 ;; Language metadata (used for language picker)
 (:lang-name . "Français parisien")
 (:lang-flag . "🇫🇷")

 ;; Language modal (first-visit language selection)
 (:lang-modal-title . "Choisissez votre langue")
 (:lang-modal-subtitle . "Sélectionnez la langue de l'interface :")

 ;; Navigation
 (:nav-translate . "Traduire")
 (:nav-review . "Réviser")
 (:nav-flashcards . "Mes cartes")
 (:nav-dashboard . "Tableau de bord")
 (:nav-decks . "Paquets")
 (:nav-logout . "Déconnexion")
 (:nav-home . "Accueil")
 (:nav-pricing . "Tarifs")
 (:nav-institutions . "Pour les institutions")
 (:nav-export-data . "Exporter les données")
 (:nav-open-navigation . "Ouvrir la navigation")
 (:theme-light . "Clair")
 (:theme-dark . "Sombre")

 ;; App title and branding
 (:app-title . "Hiisi - Apprentissage des langues")

 ;; Landing page
 (:landing-meta-title . "Hiisi : appli d'apprentissage des langues avec grammaire et cartes")
 (:app-meta-description . "Hiisi est une appli d'apprentissage des langues. Chaque phrase que vous traduisez devient une carte avec grammaire intégrée, planifiée par SM-2, l'algorithme d'Anki. 15 langues.")
 (:trial-start-cta . "Commencer avec Hiisi")
 (:subscription-best-value . "Meilleur rapport qualité-prix")

 ;; Auth pages
 (:auth-register . "S'inscrire")
 (:auth-login . "Connexion")
 (:auth-email . "E-mail")
 (:auth-password . "Mot de passe")
 (:auth-password-again . "Confirmer le mot de passe")
 (:auth-display-name . "Nom affiché")
 (:auth-register-title . "S'inscrire à Hiisi")
 (:auth-register-subtitle . "Créer un compte")
 (:auth-login-title . "Connexion à Hiisi")
 (:auth-login-subtitle . "Entrez vos identifiants")
 (:auth-login-invalid-credentials . "E-mail ou mot de passe invalide.")
 (:auth-login-rate-limited . "Trop de tentatives de connexion. Veuillez attendre quelques minutes avant de réessayer.")
(:auth-register-rate-limited . "Trop de tentatives d'inscription. Veuillez attendre quelques minutes avant de réessayer.")
(:auth-email-invalid . "Veuillez saisir une adresse e-mail valide.")
(:auth-password-too-short . "Le mot de passe doit contenir au moins 8 caractères.")
(:auth-passwords-mismatch . "Les mots de passe ne correspondent pas.")
(:auth-display-name-invalid . "Le nom affiché doit contenir entre 1 et 100 caractères.")
(:auth-register-email-exists . "Un compte avec cet e-mail existe déjà.")
(:auth-register-unavailable . "L'inscription est temporairement indisponible. Veuillez réessayer plus tard.")
(:auth-register-plan-required . "Choisissez une offre avant de créer un compte.")
(:auth-preapproved-email-unrecognized . "Utilisez l'adresse e-mail de votre invitation ou choisissez une offre avant de créer un compte.")
(:auth-institution-register . "Vous venez d'un établissement ?")
(:auth-institution-stage-title . "Accès institutionnel")
(:auth-institution-stage-subtitle . "Utilisez l'e-mail de votre école ou université. Les comptes éligibles sont débloqués via l'établissement après vérification de l'e-mail.")
(:auth-institution-title . "Inscription via votre établissement")
(:auth-institution-subtitle . "Utilisez l'e-mail de votre école ou université. Si votre établissement est déjà configuré dans Hiisi, votre compte sera débloqué après vérification de l'e-mail ; l'essai individuel de 14 jours concerne l'inscription avec une offre personnelle.")
(:auth-institution-benefit-email . "Utilisez l'adresse e-mail de votre école ou université.")
(:auth-institution-benefit-access . "Les comptes éligibles reçoivent l'accès institutionnel après vérification de l'e-mail.")
(:auth-institution-benefit-fallback . "Si le domaine n'est pas reconnu, choisissez une offre individuelle ou demandez à votre établissement de contacter Hiisi.")
(:auth-see-included . "Voir ce qui est inclus")
(:auth-institution-check-access . "Vérifier l'accès")
(:auth-institution-email-eligible-title . "Accès institutionnel confirmé")
(:auth-institution-email-eligible-detail . "Continuez avec cet e-mail pour créer votre compte. L'accès sera débloqué après vérification de l'e-mail.")
(:auth-institution-change-email . "Utiliser un autre e-mail")
(:auth-institution-outcome-note . "Si votre école ou université fournit l'accès à Hiisi, votre compte est débloqué après vérification de l'e-mail. Si le domaine n'est pas éligible, choisissez une offre personnelle pour commencer l'essai de 14 jours.")
(:auth-institution-personal-plan-link . "Voir les offres personnelles")
(:auth-institution-domain-unrecognized . "Nous ne reconnaissons pas encore ce domaine d'e-mail institutionnel. Choisissez une offre personnelle pour commencer l'essai de 14 jours, ou demandez à votre établissement de contacter Hiisi.")
(:subscribe-institution-callout-title . "Vous utilisez Hiisi via une école ou une université ?")
(:subscribe-institution-callout-body . "Inscrivez-vous avec votre e-mail institutionnel et Hiisi débloquera automatiquement l'accès si votre établissement est déjà configuré.")
(:auth-activation-email-send-failed . "Impossible d'envoyer l'e-mail d'activation. Veuillez réessayer.")
 (:auth-forgot-password . "Mot de passe oublié ?")
 (:auth-no-account . "Vous n'avez pas de compte ?")
 (:auth-have-account . "Vous avez déjà un compte ?")
 (:auth-google . "Google")
 (:auth-google-login-failed . "La connexion avec Google a échoué. Veuillez réessayer.")
 (:auth-account-created . "Compte créé !")
 (:auth-check-email . "Consultez votre boîte mail pour le lien d'activation.")
 (:auth-redirect-login . "Redirection vers la connexion dans")
 (:auth-seconds . "secondes...")
 (:auth-go-now . "Y aller maintenant")
 (:auth-not-activated . "Compte non activé")
 (:auth-activate-title . "Activez votre compte !")
 (:auth-activated . "Compte activé !")
 (:auth-activated-message . "Votre compte a été activé. Vous pouvez maintenant utiliser Hiisi.")
 (:auth-redirecting . "Redirection dans")
 (:auth-go-to-app . "Aller à l'application")
 (:onboarding-title . "Comment fonctionne Hiisi")
 (:onboarding-subtitle . "Traduisez du vrai texte, examinez la grammaire, enregistrez les éléments utiles et révisez-les plus tard.")
 (:onboarding-translate-detail . "Commencez avec du vrai texte. Hiisi renvoie la traduction, les formes alignées et les prochaines actions d'étude au même endroit.")
 (:onboarding-grammar-detail . "Ouvrez l'analyse grammaticale pour voir quelles formes se correspondent dans la phrase et le rôle de chaque partie.")
 (:onboarding-review-detail . "Enregistrez les traductions utiles, puis révisez-les plus tard avec la répétition espacée pour les garder en mémoire à long terme.")
 (:onboarding-decks-detail . "Regroupez les éléments utiles dans des paquets, partagez-les avec d'autres personnes et gardez le contenu lié au même endroit.")
 (:onboarding-back . "Retour")
 (:onboarding-next . "Suivant")
 (:onboarding-skip . "Passer le guide")
 (:auth-resend-title . "Renvoyer l'e-mail d'activation")
 (:auth-resend-subtitle . "Entrez votre e-mail pour recevoir un nouveau lien d'activation.")
 (:auth-resend-button . "Renvoyer l'e-mail d'activation")
 (:auth-resend-success . "E-mail d'activation envoyé !")
 (:auth-resend-success-detail . "Consultez votre boîte mail pour le nouveau lien d'activation.")
 (:auth-resend-rate-limited . "Veuillez attendre quelques minutes avant de demander un autre e-mail d'activation.")
 (:auth-resend-cooldown . "Vous pourrez demander un autre e-mail dans ~a secondes.")
 (:auth-back-to-login . "Retour à la connexion")
 (:auth-forgot-password-title . "Mot de passe oublié")
 (:auth-forgot-password-subtitle . "Entrez votre e-mail et nous vous enverrons un lien pour réinitialiser votre mot de passe.")
 (:auth-send-reset-link . "Envoyer le lien de réinitialisation")
 (:auth-reset-email-sent . "Lien de réinitialisation envoyé !")
 (:auth-reset-email-sent-detail . "Si un compte existe avec cet e-mail, vous recevrez bientôt un lien de réinitialisation du mot de passe.")
 (:auth-reset-rate-limited . "Veuillez attendre quelques minutes avant de demander une autre réinitialisation du mot de passe.")
 (:auth-reset-invalid-token . "Ce lien de réinitialisation est invalide ou a expiré.")
 (:auth-reset-password-title . "Réinitialiser le mot de passe")
 (:auth-reset-password-subtitle . "Entrez votre nouveau mot de passe ci-dessous.")
 (:auth-new-password . "Nouveau mot de passe")
 (:auth-confirm-new-password . "Confirmer le nouveau mot de passe")
 (:auth-reset-password . "Réinitialiser le mot de passe")
 (:auth-password-changed . "Mot de passe modifié !")
 (:auth-password-changed-detail . "Votre mot de passe a bien été modifié. Vous pouvez maintenant vous connecter avec votre nouveau mot de passe.")
 (:auth-change-password-title . "Modifier le mot de passe")
 (:auth-change-password-subtitle . "Mettez à jour le mot de passe de votre compte.")
 (:auth-current-password . "Mot de passe actuel")
 (:auth-change-password . "Modifier le mot de passe")
 (:auth-back-to-app . "Retour à l'application")
 (:auth-password-updated . "Mot de passe mis à jour !")
 (:auth-password-updated-detail . "Votre mot de passe a bien été mis à jour.")
(:auth-current-password-invalid . "Le mot de passe actuel est incorrect.")
(:auth-new-password-same . "Le nouveau mot de passe doit être différent du mot de passe actuel.")

 ;; Email copy
 (:email-common-hi . "Bonjour")
 (:email-common-tagline . "Hiisi - Apprendre par la traduction")
 (:email-activation-subject . "Activez votre compte Hiisi")
 (:email-activation-title . "Bienvenue sur Hiisi")
 (:email-activation-body . "Merci pour votre inscription. Veuillez activer votre compte en cliquant sur le lien ci-dessous :")
 (:email-activation-button . "Activer le compte")
 (:email-activation-copy-link . "Ou copiez ce lien")
 (:email-activation-expiry . "Ce lien expirera dans 24 heures.")
 (:email-reset-subject . "Réinitialiser votre mot de passe Hiisi")
 (:email-reset-title . "Demande de réinitialisation du mot de passe")
 (:email-reset-body . "Nous avons reçu une demande de réinitialisation de votre mot de passe. Cliquez sur le lien ci-dessous pour définir un nouveau mot de passe :")
 (:email-reset-button . "Réinitialiser le mot de passe")
 (:email-reset-expiry . "Ce lien expirera dans 1 heure.")
 (:email-reset-ignore . "Si vous n'avez pas demandé de réinitialisation du mot de passe, vous pouvez ignorer cet e-mail.")
 (:email-reminder-subject-due . "Il est temps de réviser vos cartes Hiisi")
 (:email-reminder-subject-streak . "Continuez votre série Hiisi")
 (:email-reminder-cards-due . "cartes prêtes à réviser")
 (:email-reminder-keep-going . "Quelques jours se sont écoulés depuis votre dernière révision. Cinq minutes aujourd'hui suffisent pour que ce que vous avez déjà appris ne vous échappe pas.")
 (:email-reminder-button . "Réviser maintenant")
 (:email-reminder-settings . "Gérer les paramètres de rappel")
 (:email-reminder-preview-title . "Cartes qui vous attendent")
 (:email-reminder-translation-label . "Traduction")
 (:email-reminder-more-due-today . "autres cartes à réviser aujourd'hui")
 (:email-trial-subject . "Comment se passe votre essai Hiisi ?")
 (:email-trial-expiring . "Votre essai gratuit Hiisi se termine demain.")
 (:email-trial-feedback . "Hiisi vous plaît ? Dites-nous ce qui vous a le plus aidé.")
 (:email-trial-strengths . "Vous pouvez traduire du vrai texte, enregistrer les meilleurs éléments en cartes et apprendre avec la répétition espacée.")
 (:email-trial-reply . "Répondez à cet e-mail et votre message ira directement à l'équipe Hiisi.")
 (:email-trial-button . "Choisir une offre")
 (:email-trial-manage . "Gérer l'abonnement")
 (:email-trial-contact . "Nous écrire")
 (:email-plan-nudge-subject . "Vos traductions vous attendent")
 (:email-plan-nudge-title . "Vos traductions vous attendent")
 (:email-plan-nudge-intro . "Vous vous êtes inscrit à Hiisi, mais vous n'avez pas encore choisi d'offre.")
 (:email-plan-nudge-benefits-intro . "Voici ce que vous obtenez avec un abonnement :")
 (:email-plan-nudge-benefit-translations . "600 traductions par mois avec analyses grammaticales")
 (:email-plan-nudge-benefit-flashcards . "Cartes illimitées avec répétition espacée")
 (:email-plan-nudge-benefit-decks . "Paquets personnalisés que vous pouvez organiser et partager")
 (:email-plan-nudge-pricing . "Les offres commencent à 10 EUR/mois, ou économisez avec l'offre annuelle à 100 EUR/an (deux mois offerts).")
 (:email-plan-nudge-feedback . "Si quelque chose dans Hiisi ne vous convient pas, répondez à cet e-mail. Votre message ira directement à l'équipe Hiisi.")
 (:email-plan-nudge-button . "Choisir une offre")
 (:email-plan-nudge-unsubscribe . "Se désabonner de ces e-mails")
 (:email-plan-nudge-unsubscribe-done-title . "E-mails d'offre désactivés")
 (:email-plan-nudge-unsubscribe-done-body . "Vous ne recevrez plus d'e-mails de rappel d'offre.")
 (:email-plan-nudge-unsubscribe-invalid-title . "Ce lien n'est pas valide")
 (:email-plan-nudge-unsubscribe-invalid-body . "Ce lien de désabonnement est manquant, expiré ou n'est plus valide.")
 (:email-invite-subject . "Vous avez été invité à Hiisi")
 (:email-invite-title . "Vous avez été invité à Hiisi")
 (:email-invite-intro . "Vous avez été invité à utiliser Hiisi gratuitement, comme testeur, ami apprécié, ou les deux.")
 (:email-invite-details . "Utilisez le bouton ci-dessous pour créer votre compte et commencer à explorer les traductions et les cartes.")
 (:email-invite-button . "Créer un compte")
 (:email-invite-issue-reporting . "Si quelque chose casse ou semble étrange, un bouton de signalement se trouve en bas de chaque page.")
 (:email-issue-completed-subject . "Votre problème Hiisi a été corrigé")
 (:email-issue-completed-title . "Problème corrigé")
 (:email-issue-completed-label . "Problème")
 (:email-issue-completed-followup . "Ouvrez Hiisi pour vérifier le correctif ou reprendre là où vous vous étiez arrêté.")
 (:email-issue-completed-button . "Ouvrir Hiisi")
 (:email-issue-completed-open-link . "Ouvrir la page")

 ;; Translation page
 (:translate-title . "Traduire")
 (:translate-input-label . "Texte à traduire")
 (:translate-input-placeholder . "Entrez le texte à traduire...")
 (:translate-example-chip . "Essayez un exemple :")
 (:translate-example-sentence . "J'ai oublié mes clés à la maison.")
 (:translate-from . "Langue source :")
 (:translate-to . "Langue cible :")
 (:translate-select-target-placeholder . "Sélectionnez la langue cible")
 (:translate-submit . "Traduire")
 (:translate-auto-detect . "N'importe laquelle (détection automatique)")
 (:translate-empty-state . "Traduisez un mot ou une phrase pour voir ici le résultat, l'analyse grammaticale et les actions d'étude.")
 (:translate-select-deck-placeholder . "Sélectionner un paquet (facultatif)")
 (:translate-result-title . "Résultat de traduction")
 (:translate-save-destination-label . "Destination d'enregistrement")
 (:translate-save-to-my-cards . "Mes cartes (par défaut)")
 (:translate-save-to-deck . "Enregistrer dans le paquet")
 (:translate-saved-to-my-cards . "Enregistré dans Mes cartes")
 (:translate-saved-to-deck . "Enregistré dans ~A")
 (:translate-view-my-cards . "Voir Mes cartes")
 (:translate-new-deck . "Créer un nouveau paquet")
 (:translate-add-to-deck . "Ajouter au paquet")
 (:translate-feedback-label . "Retour sur la qualité")
 (:translate-feedback-helpful . "Utile")
 (:translate-feedback-helpful-marked . "Marqué comme utile")
 (:translate-regenerate-translation . "Regénérer la traduction")
 (:translate-regenerate-confirm . "Hiisi marquera ce résultat comme imprécis et générera une nouvelle traduction. Continuer ?")
 (:pronunciation-label . "Prononciation")
 (:pronunciation-show . "Afficher la prononciation")
 (:pronunciation-hide . "Masquer la prononciation")
 (:grammar-term-examples . "Exemples")
 (:grammar-term-related . "Termes associés")
 (:grammar-term-modal-title . "Terme grammatical")
 (:grammar-term-empty . "Sélectionnez un terme surligné pour voir les détails.")
 (:extension-login-required . "Connectez-vous à Hiisi avant d'utiliser l'extension de navigateur.")
 (:extension-session-invalid . "Votre session Hiisi n'est plus valide. Connectez-vous à nouveau.")
 (:extension-activation-required . "Activez votre compte Hiisi avant d'utiliser l'extension de navigateur.")
 (:extension-subscription-required . "Commencez un essai Hiisi avant d'utiliser l'extension de navigateur.")

 ;; Translation and Flashcards
 (:lang-auto . "Auto")
 (:lang-unknown . "?")
 (:lang-target . "Cible")
 (:translate-deck-create-title . "Créer un nouveau paquet")
 (:translate-deck-name-label . "Nom du paquet")
 (:translate-deck-name-placeholder . "p. ex. bases du finnois")
 (:translate-deck-description-label . "Description (facultative)")
 (:translate-deck-cancel . "Annuler")
 (:translate-deck-create . "Créer")
 (:translate-rate-label . "Évaluer la traduction")
 (:flashcards-delete . "Supprimer")
 (:flashcards-delete-confirm . "Voulez-vous vraiment supprimer cette carte ?")
 (:flashcards-deck-search-placeholder . "Rechercher des paquets...")
 (:flashcards-no-decks . "Aucun paquet pour l'instant. Créez-en un d'abord !")
 (:flashcards-deck-cancel . "Annuler")
 (:flashcards-recollection-tooltip . "Souvenir : ~A")
 (:flashcards-recollection-poor . "Faible")
 (:flashcards-recollection-fair . "Moyen")
 (:flashcards-recollection-normal . "Normal")
 (:flashcards-recollection-strong . "Fort")
 (:flashcards-recollection-very-strong . "Très fort")

 ;; Flashcard review
 (:review-title . "Réviser")
 (:review-session-title . "Session de révision")
 (:review-session-subtitle . "Entraînez-vous avec vos cartes enregistrées")
 (:review-selector-title . "Choisissez quoi réviser")
 (:review-selector-subtitle . "Sélectionnez un paquet ou une paire de langues pour concentrer votre session de révision.")
 (:review-by-deck . "Réviser par paquet")
 (:review-by-language-pair . "Réviser par paire de langues")
 (:review-all-cards . "Réviser toutes les cartes")
 (:review-cards-due . "cartes à réviser")
 (:review-deck-caught-up . "Tout est à jour")
 (:review-all-caught-up . "Tout est à jour !")

 (:review-no-cards . "Aucune carte à réviser")
 (:review-no-cards-desc . "Vous n'avez aucune carte due pour révision pour l'instant.")
 (:review-no-cards-hint . "Traduisez du texte et cliquez sur \"Enregistrer en carte\" pour construire votre paquet !")
 (:review-start-translating . "Commencer à traduire")
 (:review-click-reveal . "Cliquez pour révéler la réponse")
 (:review-grammar-breakdown . "Analyse grammaticale")
 (:review-how-well . "Vous en souveniez-vous ?")
 (:review-again . "Non")
 (:review-hard . "À peine")
 (:review-good . "Oui")
 (:review-easy . "Facilement")
 (:review-progress . "Carte ~a sur ~a")
 (:review-correct-count . "Correctes")
 (:review-wrong-count . "Incorrectes")
 (:mockup-forgot-detail . "1re personne du singulier au prétérit de \"olvidar\" (oublier)")
 (:mockup-keys-detail . "Possessif \"mis\" avec le nom féminin pluriel \"llaves\" (clés)")
 (:review-complete . "Session terminée !")
 (:review-complete-msg . "Vous avez révisé ~a cartes")
 (:review-again-btn . "Réviser encore")
 (:review-translate-more . "Traduire plus")
 (:review-streak . "jours de série")

 ;; Dashboard
 (:dashboard-title . "Tableau de bord")
 (:dashboard-welcome-title . "Traduisez votre premier texte")
 (:dashboard-welcome-subtitle . "Traduisez une expression utile, enregistrez-la dans un paquet et révisez-la au bon moment.")
 (:dashboard-take-quick-tour . "Faire une visite rapide")
 (:dashboard-cards-due . "Cartes dues")
 (:dashboard-total-cards . "Total des cartes")
 (:dashboard-mastered-cards . "Cartes maîtrisées")
 (:dashboard-subscription . "Abonnement")
 (:dashboard-subscribed-until . "Abonné jusqu'au")
 (:dashboard-trial-ends . "Fin de l’essai")
 (:dashboard-not-subscribed . "Non abonné")
 (:dashboard-recent . "Traductions récentes")
 (:dashboard-no-translations . "Aucune traduction pour l'instant")
 (:dashboard-streak . "Série de révision")
 (:dashboard-days . "jours")
 (:dashboard-all-caught-up . "Tout est à jour !")
 (:dashboard-all-caught-up-hint . "Traduisez davantage pour construire votre collection.")
 (:dashboard-no-cards-title . "Créez vos premières cartes d’étude")
 (:dashboard-no-cards-hint . "Traduisez du texte et enregistrez des expressions utiles pour constituer votre collection.")
 (:dashboard-first-use-checklist-title . "Premières étapes")
 (:dashboard-first-use-checklist-translate . "Faites votre première traduction")
 (:dashboard-first-use-checklist-card . "Enregistrez votre première carte")
 (:dashboard-first-use-checklist-review . "Terminez votre première révision")
 (:dashboard-getting-started . "Premiers pas")
 (:dashboard-tip-1 . "Traduisez le texte que vous voulez apprendre")
 (:dashboard-tip-2 . "Cliquez sur \"Enregistrer en carte\" sur les traductions que vous voulez retenir")
 (:dashboard-tip-3 . "Révisez vos cartes régulièrement. La répétition espacée aide à retenir à long terme")
 (:dashboard-tip-4 . "Évaluez honnêtement. Cela aide l'algorithme à planifier vos révisions de manière optimale")

 ;; Account
 (:account-title . "Compte")
 (:account-subtitle . "Consultez ici votre profil, votre abonnement, vos rappels, vos exports et vos paramètres de suppression.")
 (:account-profile-subtitle . "Gardez votre nom affiché et vos informations e-mail à jour.")
 (:account-export-subtitle . "Téléchargez une copie de vos traductions, paquets et données de révision enregistrés.")
 (:account-deletion-title . "Suppression du compte")
 (:account-deletion-scheduled . "Votre compte est programmé pour suppression le ~A.")
 (:account-deletion-cancel-hint . "Vous pouvez annuler avant cette date pour conserver votre compte.")
 (:account-deletion-cancel . "Annuler la suppression")
 (:account-deletion-request . "Vous pouvez demander la suppression du compte à tout moment. La suppression est programmée 14 jours après confirmation. Si vous changez d'avis, veuillez contacter l'assistance avant la fin de cette période de 14 jours.")
 (:account-deletion-confirm . "Programmer la suppression du compte dans 14 jours ?")
 (:account-deletion-schedule . "Programmer la suppression")
 (:account-reminders-title . "Rappels par e-mail")
 (:account-reminders-subtitle . "Choisissez si Hiisi peut vous envoyer un e-mail lorsqu'il y a quelque chose à réviser.")
 (:account-reminders-opt-out . "Se désabonner des rappels de révision et de continuation")
 (:account-reminders-save . "Enregistrer les préférences")

 ;; Subscription
 (:subscribe-title . "Tarifs simples")
 (:subscribe-choose-plan . "Choisissez votre offre")
 (:subscribe-start-today . "Commencez à apprendre aujourd'hui avec un essai gratuit de 14 jours")
 (:subscribe-monthly . "Mensuel")
 (:subscribe-annual . "Annuel")
 (:subscribe-founder-member . "Membre fondateur")
 (:subscribe-monthly-price . "10 €")
 (:subscribe-annual-price . "100 €")
 (:subscribe-founder-price . "79 €")
 (:subscribe-founder-monthly-equivalent . "6,58 €/mois, facturé annuellement")
 (:subscribe-founder-savings . "Économisez 41 €/an par rapport au mensuel")
 (:subscribe-monthly-billing-equivalent . "10 €/mois, facturé mensuellement")
 (:subscribe-monthly-billing-note . "Facturation mensuelle flexible")
 (:subscribe-per-month . "/mois")
 (:subscribe-per-year . "/an")
 (:subscribe-monthly-desc . "600 traductions par mois. Cartes, paquets et révisions illimités.")
 (:subscribe-unlimited-flashcards . "Cartes illimitées")
 (:subscribe-grammar-explanations . "Explications grammaticales")
 (:subscribe-spaced-repetition . "Répétition espacée")
 (:subscribe-annual-desc . "Tout ce qui est inclus dans Mensuel. Deux mois offerts.")
 (:subscribe-founder-lock . "Prix verrouillé tant que votre abonnement reste actif.")
 (:subscribe-founder-badge . "Offre limitée")
 (:subscribe-founder-limit . "Limité aux 100 premiers membres")
 (:subscribe-manage . "Gérer l'abonnement")
 (:subscribe-activated . "Abonnement activé !")
 (:subscribe-thank-you . "Votre abonnement est actif. Vous pouvez gérer la facturation et acheter plus de traductions ici.")
 (:subscribe-start-learning . "Commencer à apprendre")
 (:subscribe-management . "Gestion de l'abonnement")
 (:subscribe-active . "Abonnement actif")
 (:subscribe-preapproved-access . "Accès préapprouvé")
 (:subscribe-status . "Statut :")
 (:subscribe-status-active . "Actif")
 (:subscribe-status-preapproved . "Préapprouvé")
 (:subscribe-preapproved-detail . "Ce compte utilise un accès préapprouvé géré par Hiisi.")
 (:subscribe-days-remaining . "Jours restants :")
 (:subscribe-renews-on . "Renouvellement le :")
 (:subscribe-no-subscription . "Aucun abonnement actif")
 (:subscribe-access-features . "Choisissez une offre pour débloquer l'accès complet et gérer la facturation au même endroit.")
 (:subscribe-view-plans . "Voir les offres")
 (:subscribe-faq-title . "Questions fréquentes")
 (:subscribe-faq-trial-q . "Que se passe-t-il après l'essai gratuit ?")
 (:subscribe-faq-trial-a . "Votre essai de 14 jours ne demande pas de carte. À la fin, choisissez une offre payante pour garder l'accès complet.")
 (:subscribe-faq-cancel-q . "Puis-je annuler à tout moment ?")
 (:subscribe-faq-cancel-a . "Oui. Vous pouvez annuler votre abonnement à tout moment. Vous garderez l'accès jusqu'à la fin de votre période de facturation.")
 (:subscribe-faq-payment-q . "Quels moyens de paiement acceptez-vous ?")
 (:subscribe-faq-payment-a . "Nous acceptons les principales cartes de crédit et de débit via notre partenaire de paiement Polar.sh.")
 (:subscribe-copyright . "Lambda Symbolics OÜ © 2026.")
(:subscribe-checkout-unavailable . "Le paiement est temporairement indisponible. Veuillez réessayer.")
(:subscribe-portal-unavailable . "La gestion de l'abonnement est temporairement indisponible. Veuillez réessayer.")
(:subscribe-founder-sold-out . "Offre fondatrice épuisée")
(:subscribe-founder-unavailable . "L'offre fondatrice n'est pas disponible pour le moment.")
(:subscribe-checkout-cta . "S'abonner")

 ;; Generic status

 (:error-generic . "Une erreur est survenue")
(:error-invalid-request . "Données de requête invalides.")
(:error-not-found . "Ressource demandée introuvable.")
(:error-forbidden . "Vous n'avez pas accès à ceci.")
(:error-rate-limited . "Veuillez attendre un moment puis réessayer.")
 (:error-text-too-long . "Le texte est trop long. La longueur maximale de traduction est de 120 caractères.")
 (:error-input-too-long . "Entrée trop longue")
 (:error-unknown-source-lang . "La langue source sélectionnée n'est pas prise en charge.")
 (:error-unknown-target-lang . "La langue cible sélectionnée n'est pas prise en charge.")
 (:error-unknown-language . "Langue inconnue")
 (:error-translation-unavailable . "Le service de traduction est temporairement indisponible. Veuillez réessayer dans un moment.")
 (:error-translation-failed . "Échec de la traduction")
 (:error-translation-retry . "Impossible de générer une traduction après plusieurs tentatives. Veuillez reformuler votre texte.")
 (:error-quota-exceeded . "Limite de traduction atteinte")
 (:error-quota-exceeded-detail . "Vous avez utilisé toutes vos traductions pour ce mois. Votre quota se réinitialise automatiquement chaque mois.")
 (:quota-low-warning . "Il ne reste que ~A traductions. Pensez à en acheter davantage.")
 (:top-up-button . "Acheter plus de traductions")
 (:top-up-price . "5 €")
 (:top-up-amount . "300 traductions")
(:review-session-expired . "Votre session de révision a expiré. Veuillez démarrer une nouvelle session.")

 (:error-session-expired . "Votre session a expiré. Veuillez vous reconnecter.")
 (:error-session-invalid . "Votre session n'est plus valide. Veuillez vous reconnecter.")
 (:error-custom-flashcard-generation . "Nous n'avons pas pu générer l'explication. Veuillez réessayer.")
 ;; Institutions
 (:institutions-page-title . "Hiisi pour les écoles et universités")
 (:institutions-hero-title . "Des outils d'apprentissage des langues conçus pour la classe")
 (:institutions-hero-subtitle . "Offrez à vos étudiants des paquets partageables, une pratique attentive à la grammaire et des routines de révision régulières adaptées à l'enseignement réel.")
 (:institutions-section-title . "Pourquoi les institutions utilisent Hiisi")
 (:institutions-section-body . "Hiisi aide les enseignants à transformer le contenu de cours en étude guidée que les étudiants peuvent vraiment suivre. Créez des paquets pour un cours, partagez-les avec un lien et soutenez la pratique du vocabulaire et de la grammaire sans surcharge administrative.")
 (:institutions-benefit-1 . "Paquets partageables et tâches personnalisées adaptés à votre programme.")
 (:institutions-benefit-2 . "Les appréciations des étudiants aident les meilleures traductions à remonter pour les phrases fréquentes en classe.")
 (:institutions-benefit-3 . "Les analyses grammaticales et la révision espacée vont au-delà de la mémorisation de listes de mots isolés.")
 (:institutions-benefit-4 . "Un soutien pensé pour les enseignants, par quelqu'un qui écoute attentivement et se soucie des besoins de la classe.")
 (:institutions-request-title . "Démarrer une conversation")
 (:institutions-request-subtitle . "Parlez-nous de votre institution, de vos langues et du type de soutien pédagogique dont vous avez besoin. Nous vous répondrons sous une semaine.")
 (:institutions-aside-title . "Ce qui se passe ensuite")
 (:institutions-aside-body . "Nous examinons vos besoins et répondons sous une semaine pour discuter de l'accès et de la mise en place pour votre institution.")
 (:institutions-field-name . "Nom de l'institution")
 (:institutions-field-name-placeholder . "Votre université")
 (:institutions-field-contact-name . "Nom du contact")
 (:institutions-field-contact-name-placeholder . "Votre nom")
 (:institutions-field-contact-email . "E-mail du contact")
 (:institutions-field-contact-email-placeholder . "vous@universite.edu")
 (:institutions-field-domains . "Domaines e-mail")
 (:institutions-field-domains-placeholder . "universite.edu, cs.universite.edu")
 (:institutions-field-domains-help . "Liste de domaines e-mail séparés par des virgules pour votre institution")
 (:institutions-field-notes . "Informations supplémentaires")
 (:institutions-field-notes-placeholder . "Nombre estimé d'étudiants, cycle de facturation préféré, exigences particulières...")
 (:institutions-submit . "Envoyer la demande")
 (:institutions-success-title . "Merci - Hiisi pour les écoles et universités")
 (:institutions-success-heading . "Merci !")
 (:institutions-success-body . "Nous avons reçu votre demande. Nous examinerons les besoins de votre institution et vous répondrons sous une semaine.")
 (:institutions-success-back . "Retour à l'accueil")

 ;; Footer
 (:footer-privacy . "Politique de confidentialité")
 (:footer-terms . "Conditions d'utilisation")

 ;; Early software notice
 (:early-software-notice . "Hiisi est en développement précoce. Vous avez trouvé un bug ou avez une suggestion ?")

 ;; Privacy Policy
 (:privacy-title . "Politique de confidentialité")
 (:privacy-updated . "Dernière mise à jour : janvier 2026")
 (:privacy-who-title . "Qui sommes-nous")
 (:privacy-who-body . "Hiisi est exploité par Lambda Symbolics OÜ, une société enregistrée en Estonie. En tant que société estonienne, nous respectons le Règlement général sur la protection des données (RGPD) de l'Union européenne.")
 (:privacy-collect-title . "Données que nous collectons")
 (:privacy-collect-intro . "Nous collectons les informations suivantes lorsque vous utilisez Hiisi :")
 (:privacy-collect-account-key . "Informations de compte : ")
 (:privacy-collect-account-val . "Adresse e-mail, nom affiché et mot de passe haché de manière sécurisée.")
 (:privacy-collect-learning-key . "Données d'apprentissage : ")
 (:privacy-collect-learning-val . "Vos traductions, cartes enregistrées et historique de révision.")
 (:privacy-collect-usage-key . "Données d'utilisation : ")
 (:privacy-collect-usage-val . "Journaux serveur de base à des fins de sécurité et de débogage.")
 (:privacy-use-title . "Comment nous utilisons vos données")
 (:privacy-use-auth-key . "Authentification : ")
 (:privacy-use-auth-val . "Pour vérifier votre identité et sécuriser votre compte.")
 (:privacy-use-service-key . "Fourniture du service : ")
 (:privacy-use-service-val . "Pour fournir des traductions et gérer votre collection de cartes.")
 (:privacy-use-ai-key . "Traductions automatiques : ")
 (:privacy-use-ai-val . "Vos demandes de traduction sont envoyées à OpenRouter pour générer des réponses. OpenRouter peut acheminer les demandes vers le fournisseur du modèle configuré. Consultez la politique de confidentialité d'OpenRouter pour savoir comment ces données sont traitées.")
 (:privacy-third-title . "Services tiers")
 (:privacy-third-intro . "Nous utilisons les services tiers suivants :")
 (:privacy-third-openrouter-key . "OpenRouter : ")
 (:privacy-third-openrouter-val . "Pour les demandes de traduction automatique.")
 (:privacy-third-clankermails-key . "ClankerMails : ")
 (:privacy-third-clankermails-val . "Pour l'envoi des e-mails transactionnels et d'activation de compte.")
 (:privacy-third-polar-key . "Polar.sh : ")
 (:privacy-third-polar-val . "Pour le traitement des paiements d'abonnement.")
 (:privacy-cookies-title . "Cookies")
 (:privacy-cookies-intro . "Nous utilisons uniquement des cookies essentiels :")
 (:privacy-cookies-auth-key . "Jeton d'authentification : ")
 (:privacy-cookies-auth-val . "Un cookie sécurisé, HTTP-only, pour maintenir votre connexion.")
 (:privacy-cookies-lang-key . "Préférence linguistique : ")
 (:privacy-cookies-lang-val . "Pour mémoriser votre langue d'interface préférée.")
 (:privacy-retention-title . "Conservation des données")
 (:privacy-retention-body . "Vos données sont conservées tant que vous maintenez un compte. Lorsque vous demandez une suppression, votre compte est programmé pour suppression dans 14 jours.")
 (:privacy-rights-title . "Vos droits (RGPD)")
 (:privacy-rights-intro . "En vertu du RGPD, vous avez le droit de :")
 (:privacy-rights-access . "Accéder à vos données personnelles")
 (:privacy-rights-export . "Exporter vos données (disponible sur /app/api/export)")
 (:privacy-rights-correct . "Demander la correction de données inexactes")
 (:privacy-rights-delete . "Demander la suppression de votre compte et de vos données")
 (:privacy-rights-object . "Vous opposer au traitement de vos données")
 (:privacy-rights-contact . "Pour exercer ces droits, contactez-nous à")
 (:privacy-contact-title . "Contact")
 (:privacy-contact-intro . "Pour les demandes liées à la confidentialité :")
 (:privacy-contact-email-label . "E-mail : ")
 (:privacy-address-1 . "Lambda Symbolics OÜ")
 (:privacy-address-2 . "Harju maakond, Tallinn, Kesklinna linnaosa, Tornimäe tn 5, 10145")

 ;; Terms of Service
 (:terms-title . "Conditions d'utilisation")
 (:terms-updated . "Dernière mise à jour : janvier 2026")
 (:terms-1-title . "1. Description du service")
 (:terms-1-body . "Hiisi est une application d'apprentissage des langues qui fournit des traductions automatiques avec explications grammaticales et cartes à répétition espacée. Le service est exploité par Lambda Symbolics OÜ.")
 (:terms-2-title . "2. Création de compte")
 (:terms-2-body . "Pour utiliser Hiisi, vous devez créer un compte avec une adresse e-mail valide. Vous êtes responsable de la sécurité de vos identifiants.")
 (:terms-3-title . "3. Abonnement et paiements")
 (:terms-3-body . "Hiisi propose des offres d'abonnement payantes (mensuelle et annuelle). Les abonnements sont traités par Polar.sh.")
 (:terms-3-list-1 . "Les abonnements se renouvellent automatiquement sauf annulation avant la date de renouvellement.")
 (:terms-3-list-2 . "Les remboursements sont accordés conformément aux lois applicables de protection des consommateurs.")
 (:terms-3-list-3 . "Le non-paiement entraîne la perte d'accès aux fonctionnalités premium.")
 (:terms-4-title . "4. Utilisation acceptable")
 (:terms-4-intro . "Vous acceptez de ne pas :")
 (:terms-4-list-1 . "Utiliser le service à des fins illégales")
 (:terms-4-list-2 . "Tenter de contourner les limites d'utilisation ou les mesures de sécurité")
 (:terms-4-list-3 . "Partager vos identifiants de compte avec d'autres personnes")
 (:terms-4-list-4 . "Utiliser des outils automatisés pour accéder au service d'une manière qui dégrade les performances pour les autres")
 (:terms-5-title . "5. Contenu et propriété intellectuelle")
 (:terms-5-body-1 . "Les traductions générées par Hiisi sont créées automatiquement et peuvent ne pas être uniques. Vous pouvez utiliser vos traductions et cartes à des fins personnelles, mais vous ne détenez pas de droits d'auteur exclusifs sur le contenu généré automatiquement.")
 (:terms-5-body-2 . "L'application Hiisi, son identité de marque et son contenu original restent la propriété de Lambda Symbolics OÜ.")
 (:terms-6-title . "6. Disponibilité du service")
 (:terms-6-intro . "Hiisi est fourni \"tel quel\". Nous ne garantissons pas :")
 (:terms-6-list-1 . "Un service ininterrompu ou sans erreur")
 (:terms-6-list-2 . "L'exactitude des traductions générées automatiquement")
 (:terms-6-list-3 . "La disponibilité de fonctionnalités spécifiques")
 (:terms-6-body . "Nous pouvons modifier ou arrêter des fonctionnalités à tout moment.")
 (:terms-7-title . "7. Limitation de responsabilité")
 (:terms-7-body-1 . "Dans la mesure maximale autorisée par la loi, Lambda Symbolics OÜ ne pourra être tenue responsable de dommages indirects, accessoires, spéciaux ou consécutifs résultant de votre utilisation de Hiisi.")
 (:terms-7-body-2 . "Notre responsabilité totale ne dépassera pas le montant que vous avez payé pour le service au cours des 12 mois précédant la réclamation.")
 (:terms-8-title . "8. Résiliation du compte")
 (:terms-8-body-1 . "Nous pouvons suspendre ou résilier votre compte si vous enfreignez ces conditions. Vous pouvez demander la suppression de votre compte à tout moment depuis l'application.")
 (:terms-8-body-2 . "Après une demande de suppression, votre compte est programmé pour suppression dans 14 jours.")
 (:terms-9-title . "9. Modifications des conditions")
 (:terms-9-body . "Nous pouvons mettre à jour ces conditions de temps à autre. L'utilisation continue de Hiisi après les modifications vaut acceptation des nouvelles conditions.")
 (:terms-10-title . "10. Droit applicable")
 (:terms-10-body . "Ces conditions sont régies par le droit estonien. Tout litige sera résolu devant les tribunaux d'Estonie.")
 (:terms-contact-title . "Contact")
 (:terms-contact-intro . "Pour toute question sur ces conditions :")
 (:terms-contact-email-label . "E-mail : ")
 (:terms-address-1 . "Lambda Symbolics OÜ")
 (:terms-address-2 . "Harju maakond, Tallinn, Kesklinna linnaosa, Tornimäe tn 5, 10145")

 ;; Decks
 (:decks-title . "Paquets")
 (:decks-subtitle . "Créez des paquets personnalisés et partagez-les avec d'autres personnes.")
 (:decks-create-title . "Créer un paquet")
 (:decks-name-placeholder . "Nom du paquet")
 (:decks-desc-placeholder . "Description")
 (:decks-create-btn . "Créer le paquet")
 (:decks-edit-title . "Modifier le paquet")
 (:decks-edit-btn . "Modifier le paquet")
 (:decks-actions-title . "Actions du paquet")
 (:decks-card-actions-title . "Actions de la carte")
 (:decks-update-btn . "Enregistrer les modifications")
 (:decks-default-badge . "Automatique")
 (:decks-default-description . "Ce paquet est géré automatiquement pour cette paire de langues.")
 (:decks-default-readonly . "Les paquets automatiques ont des noms et descriptions fixes.")
 (:decks-delete-btn . "Supprimer le paquet")
 (:decks-delete-confirm . "Supprimer ce paquet ?")
 (:decks-error-name-required . "Le nom du paquet est obligatoire.")
 (:decks-error-name-too-long . "Le nom du paquet doit contenir au maximum ~A caractères.")
 (:decks-error-desc-too-long . "La description du paquet doit contenir au maximum ~A caractères.")
 (:decks-error-default-readonly . "Les paquets automatiques ne peuvent pas être modifiés.")
 (:decks-error-default-delete-forbidden . "Les paquets automatiques ne peuvent pas être supprimés.")
 (:decks-your-title . "Vos paquets")
 (:decks-col-updated . "Mis à jour")
 (:decks-no-decks . "Aucun paquet pour l'instant.")
 (:decks-open-btn . "Ouvrir")
 (:decks-view-deck-btn . "Voir le paquet")
 (:decks-start-review . "Commencer la révision")
 (:decks-no-desc . "Aucune description.")
 (:decks-share-title . "Lien de partage")
 (:decks-share-info . "Toute personne ayant ce lien peut importer le paquet :")
 (:decks-share-copy . "Copier le lien")
 (:decks-share-copied . "Copié")
 (:decks-add-from-flashcards-title . "Ajouter des cartes")
 (:decks-add-from-flashcards-info . "Choisissez une carte pour ajouter sa traduction à ce paquet.")
 (:decks-create-new-flashcard . "Créer une nouvelle carte")
 (:decks-open-flashcards . "Ajouter des cartes existantes")
 (:decks-filter-from . "Langue source")
 (:decks-filter-to . "Langue cible")
 (:decks-filter-any . "Toutes les langues")
 (:decks-filter-include-assigned . "Inclure les cartes déjà dans un paquet")
 (:decks-flashcards-add . "Ajouter")
 (:decks-flashcards-added . "Ajouté")
 (:decks-flashcards-in-deck . "Dans un autre paquet")
 (:decks-flashcards-empty . "Aucune carte ne correspond à ces filtres.")
 (:decks-items-title . "Éléments du paquet")
 (:decks-col-original . "Original")
 (:decks-col-translated . "Traduit")
 (:decks-col-lang . "Langue cible")
 (:decks-no-items . "Aucun élément pour l'instant.")
 (:decks-share-page-title . "Partager le paquet")
 (:decks-share-preview . "Prévisualisez et importez ce paquet.")
 (:decks-import-title . "Importer")
 (:decks-import-btn . "Importer le paquet")
 (:starter-decks-title . "Bibliothèque")
 (:starter-decks-subtitle . "Importez des paquets prêts à l'emploi fournis par Hiisi et la communauté.")
 (:starter-decks-marketplace-btn . "Bibliothèque")
 (:starter-decks-explanation-language . "Langue d'explication")
 (:starter-decks-search-label . "Recherche")
 (:starter-decks-source-label . "Source")
 (:starter-decks-source-all . "Tous les paquets")
 (:starter-decks-change-language . "Modifier")
 (:starter-decks-filters-button . "Filtres")
 (:starter-decks-search-placeholder . "Rechercher dans la bibliothèque")
 (:starter-decks-apply-filters . "Appliquer les filtres")
 (:starter-decks-select-triplet-hint . "Choisissez les langues source et cible pour parcourir les paquets correspondants.")
 (:starter-decks-official-badge . "Officiel")
 (:starter-decks-official-by-hiisi . "Officiel par Hiisi")
 (:starter-decks-community-badge . "Communauté")
 (:starter-decks-by-hiisi . "Par Hiisi")
 (:starter-decks-preview-btn . "Aperçu")
 (:starter-decks-card-count . "~A cartes")
 (:starter-decks-no-results . "Aucun paquet ne correspond à ces filtres.")
 (:starter-decks-source-cards-title . "Cartes dans ce paquet")
 (:starter-decks-more-cards-included . "+~A cartes supplémentaires incluses.")
 (:starter-decks-sample-title . "Cartes d'exemple")
 (:starter-decks-generating . "Préparation de votre paquet ~A")
 (:starter-decks-generating-detail . "Nous l'importerons dès qu'il sera prêt. Vous pouvez continuer à parcourir la Bibliothèque ou revenir dans un instant.")
 (:starter-decks-generation-failed . "Échec de la génération")
 (:starter-decks-generation-failed-detail . "La dernière tentative de génération a échoué. Essayez d'importer à nouveau le paquet.")
 (:starter-decks-login-detail . "Connectez-vous pour importer ce paquet dans votre collection.")
 (:starter-decks-subscribe-btn . "Voir les offres")
 (:starter-decks-subscribe-detail . "Les paquets de la bibliothèque sont disponibles avec un abonnement actif ou un essai.")
 (:library-submit-title . "Soumettre à la bibliothèque")
 (:library-submit-intro . "Envoyez ce paquet à la bibliothèque pour examen administrateur avant publication.")
 (:library-submit-btn . "Soumettre le paquet")
 (:library-submit-approved . "Approuvé pour la bibliothèque")
 (:library-submit-approved-detail . "Ce paquet est publié dans la bibliothèque.")
 (:library-submit-pending . "En cours d'examen")
 (:library-submit-pending-detail . "Ce paquet a été soumis et attend l'examen d'un administrateur.")
 (:library-submit-rejected . "Modifications nécessaires avant publication")
 (:library-submit-rejected-detail . "Cette soumission a été rejetée. Mettez à jour le paquet et soumettez-le à nouveau.")
 (:library-error-empty . "Ajoutez au moins une carte avant de soumettre ce paquet à la bibliothèque.")
 (:library-error-missing-triplet . "Chaque carte d'une soumission à la bibliothèque doit avoir un triplet de langues complet.")
 (:library-error-mixed-triplet . "Toutes les cartes d'une soumission à la bibliothèque doivent partager le même triplet de langues.")
 (:starter-deck-topic-greetings-title . "Salutations et présentations")
 (:starter-deck-topic-greetings-description . "Bonjour, noms, bases de politesse et phrases de première rencontre.")
 (:starter-deck-topic-travel-title . "Voyage essentiel")
 (:starter-deck-topic-travel-description . "Gares, billets, prix, aide et déplacements.")
 (:starter-deck-topic-numbers-title . "Nombres et prix")
 (:starter-deck-topic-numbers-description . "Comptage, totaux, prix, étages et quantités du quotidien.")
 (:starter-deck-topic-time-title . "Heure et dates")
 (:starter-deck-topic-time-description . "Jours, mois, rendez-vous, heure et dates relatives.")
 (:starter-deck-topic-food-title . "Restaurant et nourriture")
 (:starter-deck-topic-food-description . "Commander, besoins alimentaires, boissons, addition et repas du quotidien à l'extérieur.")
 (:starter-deck-topic-emergency-title . "Urgence et santé")
 (:starter-deck-topic-emergency-description . "Médecins, pharmacies, symptômes, parties du corps et aide urgente.")
 (:starter-deck-topic-directions-title . "Directions et transports")
 (:starter-deck-topic-directions-description . "Virages, arrêts, billets, quais et déplacements en ville.")
 (:starter-deck-topic-school-title . "École et éducation")
 (:starter-deck-topic-school-description . "Cours, devoirs, examens, objets de classe et vie scolaire quotidienne.")
 (:starter-deck-topic-university-title . "Université et études")
 (:starter-deck-topic-university-description . "Cours magistraux, séminaires, spécialisations, devoirs et vie quotidienne sur le campus.")

 ;; Flashcards management page
 (:flashcards-title . "Mes cartes")
 (:flashcards-subtitle . "Toutes vos cartes enregistrées au même endroit. Recherchez, organisez et gérez.")
 (:flashcards-search-placeholder . "Rechercher des cartes...")
 (:flashcards-filter-button . "Filtres")
 (:flashcards-filter-title . "Filtrer les cartes")
 (:flashcards-filter-recollection . "À quel point vous les connaissez")
 (:flashcards-filter-any-recollection . "Toute familiarité")
 (:flashcards-hide-perfected . "Masquer les cartes maîtrisées")
 (:flashcards-col-original . "Original")
 (:flashcards-col-translated . "Traduction")
 (:flashcards-no-cards . "Aucune carte pour l'instant. Commencez à traduire pour en créer !")
 (:flashcards-no-filtered-cards . "Aucune carte ne correspond encore à ces filtres. Commencez à traduire pour en créer !")
 (:flashcards-image-label . "Image")
 (:flashcards-image-upload . "Importer une image")
 (:flashcards-image-replace . "Remplacer l'image")
 (:flashcards-image-remove . "Supprimer l'image")
 (:flashcards-pagination-label . "Pages de cartes")
 (:flashcards-pagination-status . "Page ~A sur ~A")
 (:flashcards-pagination-previous . "Précédent")
 (:flashcards-pagination-next . "Suivant")

 ;; Landing page (redesign)
 (:landing-hero-headline-v1 . "Traduisez facilement des phrases et lisez la grammaire dans votre propre langue.")
 (:landing-hero-headline-v2 . "Hiisi veille à ce que vous n'oubliiez pas chaque phrase que vous traduisez.")
 (:landing-hero-headline-v3 . "Transformez les phrases que vous traduisez en vocabulaire que vous pouvez utiliser.")
 (:landing-hero-subheadline . "Ajoutez n'importe quelle phrase aux favoris et Hiisi vous donne la traduction, la grammaire, la prononciation et une fiche de révision qui revient pour réviser.")
 (:trial-cardless-note . "14 jours gratuits. Aucune carte requise.")

 ;; Trial status (in-app)
 (:trial-status . "Essai gratuit")
 (:error-trial-quota-exceeded . "Limite de traduction d'essai atteinte")
 (:error-trial-quota-detail . "Vous avez utilisé les 200 traductions de votre essai. Abonnez-vous pour continuer à apprendre.")

 ;; Custom flashcards
 (:custom-flashcard-create-title . "Créer une carte")
 (:custom-flashcard-edit-title . "Modifier la carte")
 (:custom-flashcard-original . "Texte original")
 (:custom-flashcard-translated . "Traduction")
 (:custom-flashcard-lang-from . "Langue source")
 (:custom-flashcard-lang-to . "Langue cible")
 (:custom-flashcard-note . "Note pédagogique")
 (:custom-flashcard-forms . "Analyse grammaticale")
 (:custom-flashcard-form-term . "Terme")
 (:custom-flashcard-form-explanation . "Explication")
 (:custom-flashcard-add-form . "Ajouter un terme grammatical")
 (:custom-flashcard-remove-form . "Supprimer")
 (:custom-flashcard-ai-fill . "Remplir automatiquement")
 (:custom-flashcard-create-btn . "Créer la carte")
 (:custom-flashcard-update-btn . "Enregistrer les modifications")

  ;; Newsletter
  (:newsletter-email-label . "Adresse e-mail")
  (:newsletter-developer-label . "Je suis développeur")
  (:newsletter-developer-hint . "recevoir les mises à jour techniques")
  (:landing-newsletter-title . "Recevez des nouvelles de Hiisi.")
  (:landing-newsletter-body . "Inscrivez-vous à la newsletter pour recevoir des nouveautés produit, les nouvelles langues prises en charge, des decks de départ et parfois des offres pour les membres fondateurs.")
  (:landing-newsletter-fine-print . "Pas de spam. Seulement des nouveautés produit.")
  (:landing-newsletter-button . "S'inscrire à la newsletter")
  (:newsletter-unsubscribe-page-title . "Se désabonner de la newsletter Hiisi")
  (:newsletter-unsubscribe-title . "Se désabonner")
  (:newsletter-unsubscribe-subtitle . "Saisissez votre e-mail pour ne plus recevoir les nouvelles de Hiisi.")
  (:newsletter-unsubscribe-button . "Se désabonner")
  (:newsletter-feedback-email-required . "Veuillez saisir votre adresse e-mail.")
  (:newsletter-feedback-email-invalid . "Veuillez saisir une adresse e-mail valide.")
  (:newsletter-feedback-already-signed-up . "Vous êtes déjà inscrit. Nous vous tiendrons au courant !")
  (:newsletter-feedback-signed-up . "Vous êtes sur la liste ! Nous vous enverrons de temps en temps des nouvelles de Hiisi.")
  (:newsletter-feedback-unsubscribed . "Si cet e-mail était inscrit, il a été retiré des nouvelles de Hiisi.")
  (:newsletter-feedback-generic-error . "Un problème est survenu. Veuillez réessayer.")

  ;; Issue reporting
 (:issues-open-button . "Signaler un bug")
 (:issues-modal-title . "Signaler un problème")
 (:issues-modal-subtitle . "Décrivez ce qui s'est mal passé. Nous inclurons automatiquement votre page actuelle.")
 (:issues-title-label . "Titre court")
 (:issues-title-placeholder . "Bref résumé du problème")
 (:issues-message-label . "Que s'est-il passé ?")
 (:issues-message-placeholder . "Veuillez inclure les étapes pour reproduire, le comportement attendu et ce qui s'est produit à la place.")
 (:issues-submit . "Envoyer le problème")
 (:issues-cancel . "Annuler")
 (:issues-success . "Votre signalement a été envoyé. Nous l'examinerons dès que possible.")
 (:issues-error-required . "Veuillez décrire le problème avant d'envoyer.")
 (:issues-error-title-too-long . "Le titre du problème est trop long. Veuillez rester sous 160 caractères.")
 (:issues-error-too-long . "Le texte du problème est trop long. Veuillez rester sous 4000 caractères.")
 (:issues-error-rate-limit . "Trop de signalements depuis cette source. Veuillez attendre puis réessayer.")
 (:issues-error-generic . "Le signalement n'a pas pu être envoyé. Veuillez réessayer.")

 ;; Landing page (Programmable Paper)
 (:landing-signal-languages . "Quinze langues")
 (:landing-signal-flashcards . "Cartes mémoire intelligentes")
 (:landing-signal-pronunciation . "Une prononciation que vous pouvez lire")
 (:landing-problem-title . "La phrase que vous avez traduite la semaine dernière. Sauriez-vous la dire maintenant ?")
 (:landing-problem-body . "Ce moment revient souvent. Vous voyez une tournure, vous la collez dans un traducteur, et le sens s'éclaire aussitôt, là, dans votre main. Une semaine passe ; la formulation a quitté votre mémoire, et le sens avec elle. Apprendre une seule phrase demande d'ordinaire quatre outils séparés :")
 (:landing-tool-translator . "Un traducteur pour le sens")
 (:landing-tool-grammar . "Une grammaire pour la structure")
 (:landing-tool-pronunciation . "Un guide de prononciation pour le son")
 (:landing-tool-flashcards . "Une application de cartes pour la mémorisation")
 (:landing-problem-outro . "Employer les quatre prend du temps, et la phrase suivante a disparu avant que la carte soit prête.")
 (:landing-bookmark-title . "Ce qui se passe quand vous enregistrez une phrase")
 (:landing-bookmark-intro . "Un geste, et Hiisi transforme la phrase en objet d'étude structuré en quelques secondes. Elle reste dans votre bibliothèque, avec tout ce qui l'accompagne :")
 (:landing-bookmark-item-translation . "La phrase d'origine et une traduction claire")
 (:landing-bookmark-item-pronunciation . "La prononciation écrite, comme dans les dictionnaires")
 (:landing-bookmark-item-grammar . "La grammaire expliquée dans la langue que vous préférez lire")
 (:landing-bookmark-item-colors . "Des mots appariés par couleur qui montrent quelle partie correspond à quelle autre")
 (:landing-bookmark-item-flashcard . "Une carte qui revient quand votre mémoire en a besoin")
 (:landing-bookmark-cta . "Enregistrez votre première phrase")
 (:landing-sources-title . "Une phrase suffit pour commencer")
 (:landing-sources-intro . "Tout ce que vous lisez ou entendez dans une nouvelle langue fonctionne avec Hiisi :")
 (:landing-source-lyrics . "Les paroles d'une chanson que vous réécoutez sans cesse")
 (:landing-source-articles . "Des articles dans la langue que vous apprenez")
 (:landing-source-messages . "Des messages d'amis locuteurs natifs")
 (:landing-source-films . "Des répliques de films ou de podcasts que vous gardez")
 (:landing-source-page . "La page que vous êtes en train de lire")
 (:landing-features-title . "Conçu pour les autodidactes et les étudiants")
 (:landing-feature-grammar-title . "La grammaire dans la langue où vous pensez")
 (:landing-feature-grammar-body . "Lisez la grammaire française en anglais, ou la grammaire espagnole en polonais. Votre attention reste sur la phrase que vous apprenez.")
 (:landing-feature-colors-title . "Des mots appariés par couleur")
 (:landing-feature-colors-body . "Un mot et sa traduction partagent la même couleur : vous voyez le sens de chaque mot d'un coup d'œil.")
 (:landing-feature-pronunciation-title . "Une prononciation que vous pouvez lire")
 (:landing-feature-pronunciation-body . "Chaque phrase s'accompagne d'un guide de prononciation écrit, celui-là même des dictionnaires. Vous voyez comment elle sonne avant de la dire.")
 (:landing-feature-flashcards-title . "Des cartes qui se programment toutes seules")
 (:landing-feature-flashcards-body . "Chaque phrase enregistrée devient une carte. L'algorithme SM-2, celui d'Anki, décide quand elle revient : vous révisez précisément ce que vous alliez oublier.")
 (:landing-feature-decks-title . "Des paquets thématiques pour ce qui arrive")
 (:landing-feature-decks-body . "Un voyage le mois prochain ? Un nouveau travail ? Importez un paquet tout prêt et révisez dès le premier jour.")
 (:landing-feature-directions-title . "Quinze langues, dans tous les sens")
 (:landing-feature-directions-body . "Traduisez de l'espagnol vers le français, ou de l'anglais vers l'allemand. Hiisi couvre toutes les directions de l'ensemble.")
 (:landing-flow-title . "À quoi ressemble l'apprentissage dans Hiisi")
 (:landing-flow-body . "Ouvrez Hiisi. Les cartes du jour vous attendent, chacune une phrase que vous avez gardée, avec sa traduction et sa grammaire. Une nouvelle phrase à retenir ? Enregistrez-la : demain, elle rejoint la pile de révision.")
 (:landing-who-title . "À qui s'adresse Hiisi")
 (:landing-who-intro . "Déjà perdu une phrase utile ? Hiisi a été conçu pour vous.")
 (:landing-who-beginners . "Les débutants qui bâtissent leurs premières phrases dans une nouvelle langue")
 (:landing-who-intermediate . "Les apprenants intermédiaires qui lisent bien mais butent sur la grammaire")
 (:landing-who-native . "Les locuteurs d'héritage qui renouent avec la langue parlée à la maison")
 (:landing-who-travellers . "Les voyageurs et les conjoints de locuteurs natifs qui veulent des phrases utilisables")
 (:landing-final-title . "Commencez avec Hiisi dès aujourd'hui")
 (:landing-final-body . "Hiisi vous donne le sens, la grammaire, la prononciation, et une carte qui revient vous trouver. Dès lors, la phrase est à vous.")
 (:landing-final-languages . "Quinze langues vous attendent, dès que vous êtes prêt.")
 (:modal-close . "Fermer")
)
