;;; Italian translations
;;; This file should contain all keys from en.lisp

(
 ;; Language metadata (used for language picker)
 (:lang-name . "Italiano")
 (:lang-flag . "🇮🇹")

 ;; Language modal (first-visit language selection)
 (:lang-modal-title . "Scegli la tua lingua")
 (:lang-modal-subtitle . "Seleziona la lingua preferita per l'interfaccia:")

 ;; Navigation
 (:nav-translate . "Traduci")
 (:nav-review . "Ripassa")
 (:nav-flashcards . "Le mie carte")
 (:nav-dashboard . "Dashboard")
 (:nav-decks . "Mazzi")
 (:nav-logout . "Esci")
 (:nav-home . "Home")
 (:nav-pricing . "Prezzi")
 (:nav-institutions . "Per istituzioni")
 (:nav-export-data . "Esporta dati")
 (:nav-open-navigation . "Apri la navigazione")
 (:theme-light . "Chiaro")
 (:theme-dark . "Scuro")

 ;; App title and branding
 (:app-title . "Hiisi - Apprendimento delle lingue")

 ;; Landing page
 (:landing-learn-more . "Scopri di più")
 (:landing-how-it-works . "Come funziona")
 (:landing-start-trial . "Inizia la prova gratuita")
 (:landing-best-value . "Miglior valore")

 ;; Auth pages
 (:auth-register . "Registrati")
 (:auth-login . "Accedi")
 (:auth-email . "Email")
 (:auth-password . "Password")
 (:auth-password-again . "Conferma password")
 (:auth-display-name . "Nome visualizzato")
 (:auth-register-title . "Registrati su Hiisi")
 (:auth-register-subtitle . "Crea un nuovo account")
 (:auth-login-title . "Accedi a Hiisi")
 (:auth-login-subtitle . "Inserisci le tue credenziali")
 (:auth-login-invalid-credentials . "Email o password non validi.")
 (:auth-login-rate-limited . "Troppi tentativi di accesso. Attendi qualche minuto e riprova.")
(:auth-register-rate-limited . "Troppi tentativi di registrazione. Attendi qualche minuto e riprova.")
(:auth-email-invalid . "Inserisci un indirizzo email valido.")
(:auth-password-too-short . "La password deve contenere almeno 8 caratteri.")
(:auth-passwords-mismatch . "Le password non coincidono.")
(:auth-display-name-invalid . "Il nome visualizzato deve contenere da 1 a 100 caratteri.")
(:auth-register-email-exists . "Esiste già un account con questa email.")
(:auth-register-unavailable . "La registrazione è temporaneamente non disponibile. Riprova più tardi.")
(:auth-register-plan-required . "Scegli un piano prima di creare un account.")
(:auth-preapproved-email-unrecognized . "Usa l'indirizzo e-mail del tuo invito oppure scegli un piano prima di creare un account.")
(:auth-institution-register . "Arrivi da un'istituzione?")
(:auth-institution-stage-title . "Accesso istituzionale")
(:auth-institution-stage-subtitle . "Usa l'email della tua scuola o università. Gli account idonei vengono sbloccati tramite l'istituzione dopo la verifica dell'email.")
(:auth-institution-title . "Registrati tramite la tua istituzione")
(:auth-institution-subtitle . "Usa l'email della tua scuola o università. Se la tua istituzione è già configurata in Hiisi, il tuo account verrà sbloccato dopo la verifica dell'email; la prova individuale di 14 giorni vale per la registrazione con un piano personale.")
(:auth-institution-benefit-email . "Usa l'indirizzo email della tua scuola o università.")
(:auth-institution-benefit-access . "Gli account idonei ricevono l'accesso istituzionale dopo la verifica dell'email.")
(:auth-institution-benefit-fallback . "Se il dominio non viene riconosciuto, scegli un piano individuale oppure chiedi alla tua istituzione di contattare Hiisi.")
(:auth-see-included . "Vedi cosa è incluso")
(:auth-institution-check-access . "Verifica l'accesso")
(:auth-institution-email-eligible-title . "Accesso istituzionale confermato")
(:auth-institution-email-eligible-detail . "Continua con questa email per creare il tuo account. L'accesso verrà sbloccato dopo la verifica dell'email.")
(:auth-institution-change-email . "Usa un'altra email")
(:auth-institution-outcome-note . "Se la tua scuola o università fornisce l'accesso a Hiisi, il tuo account viene sbloccato dopo la verifica dell'email. Se il dominio non è idoneo, scegli un piano personale per iniziare la prova di 14 giorni.")
(:auth-institution-personal-plan-link . "Vedi i piani personali")
(:auth-institution-domain-unrecognized . "Non riconosciamo ancora quel dominio email istituzionale. Scegli un piano personale per iniziare la prova di 14 giorni, oppure chiedi alla tua istituzione di contattare Hiisi.")
(:subscribe-institution-callout-title . "Usi Hiisi tramite una scuola o università?")
(:subscribe-institution-callout-body . "Registrati con la tua email istituzionale e Hiisi sbloccherà automaticamente l'accesso se la tua istituzione è già configurata.")
(:auth-activation-email-send-failed . "Non è stato possibile inviare l'email di attivazione. Riprova.")
 (:auth-forgot-password . "Password dimenticata?")
 (:auth-no-account . "Non hai un account?")
 (:auth-have-account . "Hai già un account?")
 (:auth-google . "Google")
 (:auth-google-login-failed . "Accesso con Google non riuscito. Riprova.")
 (:auth-account-created . "Account creato!")
 (:auth-check-email . "Controlla la tua email per il link di attivazione.")
 (:auth-redirect-login . "Reindirizzamento al login tra")
 (:auth-seconds . "secondi...")
 (:auth-go-now . "Vai ora")
 (:auth-not-activated . "Account non attivato")
 (:auth-activate-title . "Attiva il tuo account!")
 (:auth-activated . "Account attivato!")
 (:auth-activated-message . "Il tuo account è stato attivato. Ora puoi usare Hiisi.")
 (:auth-redirecting . "Reindirizzamento tra")
 (:auth-go-to-app . "Vai all'app")
 (:onboarding-title . "Come funziona Hiisi")
 (:onboarding-subtitle . "Traduci testo reale, osserva la grammatica, salva gli elementi utili e ripassali più tardi.")
 (:onboarding-translate-detail . "Parti da testo reale. Hiisi restituisce la traduzione, le forme allineate e le azioni di studio successive in un solo posto.")
 (:onboarding-grammar-detail . "Apri l'analisi grammaticale per vedere quali forme corrispondono nella frase e quale funzione svolge ogni parte.")
 (:onboarding-review-detail . "Salva le traduzioni utili e ripassale più tardi con la ripetizione dilazionata, così restano nella memoria a lungo termine.")
 (:onboarding-decks-detail . "Raggruppa gli elementi utili in mazzi, condividili con altri e tieni insieme il materiale correlato.")
 (:onboarding-back . "Indietro")
 (:onboarding-next . "Avanti")
 (:onboarding-skip . "Salta guida")
 (:auth-resend-title . "Reinvia email di attivazione")
 (:auth-resend-subtitle . "Inserisci la tua email per ricevere un nuovo link di attivazione.")
 (:auth-resend-button . "Reinvia email di attivazione")
 (:auth-resend-success . "Email di attivazione inviata!")
 (:auth-resend-success-detail . "Controlla la tua casella di posta per il nuovo link di attivazione.")
 (:auth-resend-rate-limited . "Per favore attendi qualche minuto prima di richiedere un'altra email di attivazione.")
 (:auth-resend-cooldown . "Puoi richiedere un'altra email tra ~a secondi.")
 (:auth-back-to-login . "Torna al login")
 (:auth-forgot-password-title . "Password dimenticata")
 (:auth-forgot-password-subtitle . "Inserisci la tua email e ti invieremo un link per reimpostare la password.")
 (:auth-send-reset-link . "Invia link di reimpostazione")
 (:auth-reset-email-sent . "Link inviato!")
 (:auth-reset-email-sent-detail . "Se esiste un account con questa email, riceverai presto un link per reimpostare la password.")
 (:auth-reset-rate-limited . "Per favore attendi qualche minuto prima di richiedere un'altra reimpostazione della password.")
 (:auth-reset-invalid-token . "Questo link di reimpostazione non è valido o è scaduto.")
 (:auth-reset-password-title . "Reimposta password")
 (:auth-reset-password-subtitle . "Inserisci la tua nuova password qui sotto.")
 (:auth-new-password . "Nuova password")
 (:auth-confirm-new-password . "Conferma nuova password")
 (:auth-reset-password . "Reimposta password")
 (:auth-password-changed . "Password cambiata!")
 (:auth-password-changed-detail . "La tua password è stata cambiata con successo. Ora puoi accedere con la tua nuova password.")
 (:auth-change-password-title . "Cambia password")
 (:auth-change-password-subtitle . "Aggiorna la password del tuo account.")
 (:auth-current-password . "Password attuale")
 (:auth-change-password . "Cambia password")
 (:auth-back-to-app . "Torna all'app")
 (:auth-password-updated . "Password aggiornata!")
 (:auth-password-updated-detail . "La tua password è stata aggiornata con successo.")
(:auth-current-password-invalid . "La password attuale non è corretta.")
(:auth-new-password-same . "La nuova password deve essere diversa da quella attuale.")

 ;; Email copy
 (:email-common-hi . "Ciao")
 (:email-common-tagline . "Hiisi - Impara attraverso la traduzione")
 (:email-activation-subject . "Attiva il tuo account Hiisi")
 (:email-activation-title . "Benvenuto in Hiisi")
 (:email-activation-body . "Grazie per esserti registrato. Attiva il tuo account facendo clic sul link seguente:")
 (:email-activation-button . "Attiva account")
 (:email-activation-copy-link . "Oppure copia questo link")
 (:email-activation-expiry . "Questo link scadrà tra 24 ore.")
 (:email-reset-subject . "Reimposta la tua password di Hiisi")
 (:email-reset-title . "Richiesta di reimpostazione della password")
 (:email-reset-body . "Abbiamo ricevuto una richiesta di reimpostazione della tua password. Fai clic sul link seguente per impostarne una nuova:")
 (:email-reset-button . "Reimposta password")
 (:email-reset-expiry . "Questo link scadrà tra 1 ora.")
 (:email-reset-ignore . "Se non hai richiesto la reimpostazione della password, puoi ignorare questa email.")
 (:email-reminder-subject-due . "È il momento di ripassare le tue carte di Hiisi")
 (:email-reminder-subject-streak . "Mantieni viva la tua serie di Hiisi")
 (:email-reminder-cards-due . "carte pronte per il ripasso")
 (:email-reminder-keep-going . "Sono passati alcuni giorni dal tuo ultimo ripasso. Cinque minuti oggi bastano perché non ti sfugga ciò che hai già imparato.")
 (:email-reminder-button . "Ripassa ora")
 (:email-reminder-settings . "Gestisci i promemoria")
 (:email-reminder-preview-title . "Carte che ti aspettano")
 (:email-reminder-translation-label . "Traduzione")
 (:email-reminder-more-due-today . "altre carte da ripassare oggi")
 (:email-trial-subject . "Come sta andando la tua prova di Hiisi?")
 (:email-trial-expiring . "La tua prova gratuita di Hiisi termina domani.")
 (:email-trial-feedback . "Ti sta piacendo Hiisi? Dicci cosa ti è stato più utile.")
 (:email-trial-strengths . "Puoi tradurre testi reali, salvare gli elementi migliori nelle flashcard e imparare con la ripetizione spaziata.")
 (:email-trial-reply . "Rispondi a questa email e il tuo messaggio arriverà direttamente al team di Hiisi.")
 (:email-trial-button . "Scegli un piano")
 (:email-trial-manage . "Gestisci abbonamento")
 (:email-trial-contact . "Scrivici")
 (:email-plan-nudge-subject . "Le tue traduzioni ti aspettano")
 (:email-plan-nudge-title . "Le tue traduzioni ti aspettano")
 (:email-plan-nudge-intro . "Ti sei registrato a Hiisi, ma non hai ancora scelto un piano.")
 (:email-plan-nudge-benefits-intro . "Ecco cosa ottieni con un abbonamento:")
 (:email-plan-nudge-benefit-translations . "600 traduzioni al mese con spiegazioni grammaticali")
 (:email-plan-nudge-benefit-flashcards . "Flashcard illimitate con ripetizione spaziata")
 (:email-plan-nudge-benefit-decks . "Mazzi personalizzati che puoi organizzare e condividere")
 (:email-plan-nudge-pricing . "I piani partono da 10 EUR al mese, oppure risparmia con il piano annuale a 100 EUR all'anno (due mesi gratis).")
 (:email-plan-nudge-feedback . "Se c'è qualcosa di Hiisi che non funziona per te, rispondi a questa email. Il tuo messaggio arriverà direttamente al team di Hiisi.")
 (:email-plan-nudge-button . "Scegli un piano")
 (:email-plan-nudge-unsubscribe . "Annulla l'iscrizione a queste email")
 (:email-plan-nudge-unsubscribe-done-title . "Email sui piani disattivate")
 (:email-plan-nudge-unsubscribe-done-body . "Non riceverai altre email di promemoria per scegliere un piano.")
 (:email-plan-nudge-unsubscribe-invalid-title . "Questo link non è valido")
 (:email-plan-nudge-unsubscribe-invalid-body . "Questo link di disiscrizione manca, è scaduto o non è più valido.")
 (:email-invite-subject . "Sei stato invitato a Hiisi")
 (:email-invite-title . "Sei stato invitato a Hiisi")
 (:email-invite-intro . "Sei stato invitato a usare Hiisi gratuitamente, come tester, amico stimato o entrambe le cose.")
 (:email-invite-details . "Usa il pulsante qui sotto per creare il tuo account e iniziare a esplorare traduzioni e flashcard.")
 (:email-invite-button . "Crea account")
 (:email-invite-issue-reporting . "Se qualcosa si rompe o non sembra giusto, c'è un pulsante per segnalare un problema in fondo a ogni pagina.")
 (:email-issue-completed-subject . "Il problema che hai segnalato su Hiisi è stato risolto")
 (:email-issue-completed-title . "Problema risolto")
 (:email-issue-completed-label . "Problema")
 (:email-issue-completed-followup . "Apri Hiisi per verificare la correzione o continuare da dove avevi interrotto.")
 (:email-issue-completed-button . "Apri Hiisi")
 (:email-issue-completed-open-link . "Apri pagina")

 ;; Translation page
 (:translate-title . "Traduci")
 (:landing-public-translate-title . "Provalo qui")
 (:translate-input-label . "Testo da tradurre")
 (:translate-input-placeholder . "Inserisci il testo da tradurre...")
 (:translate-from . "Lingua di partenza:")
 (:translate-to . "Lingua di arrivo:")
 (:translate-select-target-placeholder . "Seleziona la lingua di arrivo")
 (:translate-submit . "Traduci")
 (:translate-auto-detect . "Qualsiasi (Rilevamento automatico)")
 (:translate-empty-state . "Traduci una parola o una frase e qui vedrai il risultato, l'analisi grammaticale e le azioni di studio.")
 (:translate-select-deck-placeholder . "Seleziona mazzo (opzionale)")
 (:translate-new-deck . "Nuovo mazzo")
 (:translate-add-to-deck . "Aggiungi al mazzo")
 (:translate-bookmark . "Salva")
 (:translate-bookmarked . "Salvato")
 (:translate-retry . "Rigenera")
 (:translate-like-tooltip . "Buona traduzione")
 (:translate-dislike-tooltip . "Cattiva traduzione - richiedine una nuova")
 (:translate-dislike-confirm . "Questo genererà una nuova traduzione. Continuare?")
 (:pronunciation-label . "Pronuncia")
 (:pronunciation-show . "Mostra pronuncia")
 (:pronunciation-hide . "Nascondi pronuncia")
 (:grammar-term-examples . "Esempi")
 (:grammar-term-related . "Termini correlati")
 (:grammar-term-modal-title . "Termine grammaticale")
 (:grammar-term-empty . "Seleziona un termine evidenziato per vedere i dettagli.")
 (:extension-login-required . "Accedi a Hiisi prima di usare l'estensione del browser.")
 (:extension-session-invalid . "La tua sessione Hiisi non è più valida. Accedi di nuovo.")
 (:extension-activation-required . "Attiva il tuo account Hiisi prima di usare l'estensione del browser.")
 (:extension-subscription-required . "Avvia una prova di Hiisi prima di usare l'estensione del browser.")

 ;; Translation and Flashcards
 (:lang-auto . "Auto")
 (:lang-unknown . "?")
 (:lang-target . "Destinazione")
 (:translate-deck-create-title . "Crea nuovo mazzo")
 (:translate-deck-name-label . "Nome del mazzo")
 (:translate-deck-name-placeholder . "ad es., Fondamenti di finlandese")
 (:translate-deck-description-label . "Descrizione (opzionale)")
 (:translate-deck-cancel . "Annulla")
 (:translate-deck-create . "Crea")
 (:translate-rate-label . "Valuta la traduzione")
 (:flashcards-delete . "Elimina")
 (:flashcards-delete-confirm . "Sei sicuro di voler eliminare questa carta?")
 (:flashcards-deck-search-placeholder . "Cerca mazzi...")
 (:flashcards-no-decks . "Nessun mazzo ancora. Creane uno prima!")
 (:flashcards-deck-cancel . "Annulla")
 (:flashcards-recollection-tooltip . "Ricordo: ~A")
 (:flashcards-recollection-poor . "Debole")
 (:flashcards-recollection-fair . "Discreto")
 (:flashcards-recollection-normal . "Normale")
 (:flashcards-recollection-strong . "Forte")
 (:flashcards-recollection-very-strong . "Molto forte")

 ;; Flashcard review
 (:review-title . "Ripassa")
 (:review-session-title . "Sessione di ripasso")
 (:review-session-subtitle . "Esercitati con le tue flashcard salvate")
 (:review-selector-title . "Scegli cosa ripassare")
 (:review-selector-subtitle . "Seleziona un mazzo o una coppia di lingue su cui concentrarti in questa sessione di ripasso.")
 (:review-by-deck . "Ripassa per mazzo")
 (:review-by-language-pair . "Ripassa per coppia di lingue")
 (:review-all-cards . "Ripassa tutte le carte")
 (:review-cards-due . "carte in scadenza")
 (:review-deck-caught-up . "Tutto in pari")
 (:review-all-caught-up . "Tutto in pari!")

 (:review-no-cards . "Nessuna carta da ripassare")
 (:review-no-cards-desc . "Non hai flashcard da ripassare in questo momento.")
 (:review-no-cards-hint . "Traduci del testo e clicca \"Salva nelle flashcard\" per costruire il tuo mazzo!")
 (:review-start-translating . "Inizia a tradurre")
 (:review-click-reveal . "Clicca per rivelare la risposta")
 (:review-grammar-breakdown . "Analisi grammaticale")
 (:review-how-well . "Te lo sei ricordato?")
 (:review-again . "No")
 (:review-hard . "A fatica")
 (:review-good . "Sì")
 (:review-easy . "Facilmente")
 (:review-progress . "Carta ~a di ~a")
 (:review-correct-count . "Corrette")
 (:review-wrong-count . "Sbagliate")
 (:landing-mockup-forgot-detail . "1ª persona singolare del preterito di \"olvidar\" (dimenticare)")
 (:landing-mockup-keys-detail . "Possessivo \"mis\" con sostantivo femminile plurale \"llaves\" (chiavi)")
 (:landing-mockup-home-detail . "Espressione idiomatica \"en casa\" (a casa) -- senza articolo")
 (:landing-mockup-possession-note . "In spagnolo il preterito indica azioni passate concluse. Il pronome soggetto è di solito omesso perché la desinenza verbale identifica già il parlante.")
 (:landing-mockup-children-detail . "Nominativo plurale di \"Kind\" (bambino) -- il plurale aggiunge -er")
 (:landing-mockup-played-detail . "3ª persona plurale del preterito di \"spielen\" (giocare)")
 (:landing-mockup-garden-detail . "Dativo: \"in dem\" si contrae in \"im\", con sostantivo maschile \"Garten\" (giardino)")
 (:landing-mockup-czech-note . "Il tedesco usa il preterito nella narrativa scritta. \"Im\" è la contrazione di \"in\" + \"dem\" (articolo dativo).")
 (:landing-mockup-deck-title . "Italiano base")
 (:landing-mockup-share-deck . "Condividi mazzo")
 (:review-complete . "Sessione completata!")
 (:review-complete-msg . "Hai ripassato ~a carte")
 (:review-again-btn . "Ripassa ancora")
 (:review-translate-more . "Traduci altro")
 (:review-streak . "giorni consecutivi")

 ;; Dashboard
 (:dashboard-title . "Dashboard")
 (:dashboard-welcome-title . "Traduci il tuo primo testo")
 (:dashboard-welcome-subtitle . "Traduci una frase utile, salvala in un mazzo e ripassala quando conta.")
 (:dashboard-take-quick-tour . "Fare un tour rapido")
 (:dashboard-cards-due . "Carte da ripassare")
 (:dashboard-total-cards . "Carte totali")
 (:dashboard-mastered-cards . "Carte padroneggiate")
 (:dashboard-subscription . "Abbonamento")
 (:dashboard-subscribed-until . "Abbonato fino al")
 (:dashboard-trial-ends . "Fine della prova")
 (:dashboard-not-subscribed . "Non abbonato")
 (:dashboard-recent . "Traduzioni recenti")
 (:dashboard-no-translations . "Nessuna traduzione ancora")
 (:dashboard-streak . "Serie di ripasso")
 (:dashboard-days . "giorni")
 (:dashboard-all-caught-up . "Tutto in pari!")
 (:dashboard-all-caught-up-hint . "Traduci ancora per ampliare la tua raccolta.")
 (:dashboard-no-cards-title . "Crea le tue prime carte di studio")
 (:dashboard-no-cards-hint . "Traduci del testo e salva frasi utili per costruire la tua raccolta.")
 (:dashboard-first-use-checklist-title . "Primi passi")
 (:dashboard-first-use-checklist-translate . "Fai la tua prima traduzione")
 (:dashboard-first-use-checklist-card . "Salva la tua prima carta")
 (:dashboard-first-use-checklist-review . "Completa il tuo primo ripasso")
 (:dashboard-getting-started . "Per iniziare")
 (:dashboard-tip-1 . "Traduci il testo che vuoi imparare")
 (:dashboard-tip-2 . "Clicca \"Salva nelle flashcard\" sulle traduzioni che vuoi ricordare")
 (:dashboard-tip-3 . "Ripassa le tue flashcard regolarmente - la ripetizione spaziata ti aiuta a ricordare a lungo termine")
 (:dashboard-tip-4 . "Valuta onestamente - aiuta l'algoritmo a pianificare i ripassi in modo ottimale")

 ;; Account
 (:account-title . "Account")
 (:account-subtitle . "Gestisci qui profilo, abbonamento, promemoria, esportazioni ed eliminazione dell'account.")
 (:account-profile-subtitle . "Tieni aggiornati il nome visualizzato e l'indirizzo email.")
 (:account-export-subtitle . "Scarica una copia delle traduzioni salvate, dei mazzi e della cronologia di ripasso.")
 (:account-deletion-title . "Eliminazione account")
 (:account-deletion-scheduled . "Il tuo account è programmato per l'eliminazione il ~A.")
 (:account-deletion-cancel-hint . "Puoi annullare prima di questa data per mantenere il tuo account.")
 (:account-deletion-cancel . "Annulla eliminazione")
 (:account-deletion-request . "Puoi richiedere l'eliminazione dell'account in qualsiasi momento. L'eliminazione è programmata 14 giorni dopo la conferma. Se cambi idea, contatta l'assistenza prima che scada questo periodo di 14 giorni.")
 (:account-deletion-confirm . "Programmare l'eliminazione dell'account tra 14 giorni da oggi?")
 (:account-deletion-schedule . "Programma eliminazione")
 (:account-reminders-title . "Promemoria email")
 (:account-reminders-subtitle . "Scegli se Hiisi può inviarti email quando hai qualcosa da ripassare.")
 (:account-reminders-opt-out . "Disattiva i promemoria di ripasso e continuazione")
 (:account-reminders-save . "Salva preferenze")

 ;; Subscription
 (:subscribe-title . "Prezzi semplici")
 (:subscribe-choose-plan . "Scegli il tuo piano")
 (:subscribe-start-today . "Inizia a imparare oggi con 14 giorni di prova gratuita")
 (:subscribe-monthly . "Mensile")
 (:subscribe-annual . "Annuale")
 (:subscribe-founder-member . "Membro fondatore")
 (:subscribe-monthly-price . "€10")
 (:subscribe-annual-price . "€100")
 (:subscribe-founder-price . "€79")
 (:subscribe-per-month . "/mese")
 (:subscribe-per-year . "/anno")
 (:subscribe-monthly-desc . "600 traduzioni al mese. Flashcard, mazzi e ripassi illimitati.")
 (:subscribe-unlimited-flashcards . "Flashcard illimitate")
 (:subscribe-grammar-explanations . "Spiegazioni grammaticali")
 (:subscribe-spaced-repetition . "Ripetizione spaziata")
 (:subscribe-annual-desc . "Tutto dal piano mensile. Due mesi gratis.")
 (:subscribe-founder-lock . "Il prezzo resta bloccato finché il tuo abbonamento rimane attivo.")
 (:subscribe-founder-badge . "Offerta limitata")
 (:subscribe-founder-limit . "Riservato ai primi 100 membri")
 (:subscribe-manage . "Gestisci abbonamento")
 (:subscribe-activated . "Abbonamento attivato!")
 (:subscribe-thank-you . "Il tuo abbonamento è attivo. Qui puoi gestire la fatturazione e acquistare più traduzioni.")
 (:subscribe-start-learning . "Inizia a imparare")
 (:subscribe-management . "Gestione abbonamento")
 (:subscribe-active . "Abbonamento attivo")
 (:subscribe-preapproved-access . "Accesso pre-approvato")
 (:subscribe-status . "Stato:")
 (:subscribe-status-active . "Attivo")
 (:subscribe-status-preapproved . "Pre-approvato")
 (:subscribe-preapproved-detail . "Questo account usa un accesso pre-approvato gestito da Hiisi.")
 (:subscribe-days-remaining . "Giorni rimanenti:")
 (:subscribe-renews-on . "Si rinnova il:")
 (:subscribe-no-subscription . "Nessun abbonamento attivo")
 (:subscribe-access-features . "Scegli un piano per sbloccare l'accesso completo e gestire la fatturazione in un unico posto.")
 (:subscribe-view-plans . "Visualizza piani")
 (:subscribe-faq-title . "Domande frequenti")
 (:subscribe-faq-trial-q . "Cosa succede dopo la prova gratuita?")
 (:subscribe-faq-trial-a . "La prova di 14 giorni non richiede una carta. Al termine, scegli un piano a pagamento per mantenere l'accesso completo.")
 (:subscribe-faq-cancel-q . "Posso annullare in qualsiasi momento?")
 (:subscribe-faq-cancel-a . "Sì! Puoi annullare il tuo abbonamento in qualsiasi momento. Manterrai l'accesso fino alla fine del periodo di fatturazione.")
 (:subscribe-faq-payment-q . "Quali metodi di pagamento accettate?")
 (:subscribe-faq-payment-a . "Accettiamo tutte le principali carte di credito e debito tramite il nostro partner di pagamento Polar.sh.")
 (:subscribe-copyright . "Lambda Symbolics OÜ © 2026.")
(:subscribe-checkout-unavailable . "Il checkout è temporaneamente non disponibile. Riprova.")
(:subscribe-portal-unavailable . "La gestione dell'abbonamento è temporaneamente non disponibile. Riprova.")
(:subscribe-founder-sold-out . "L'offerta per i membri fondatori è esaurita")
(:subscribe-founder-unavailable . "L'offerta per i membri fondatori non è disponibile al momento.")
(:subscribe-checkout-cta . "Abbonati")

 ;; Errors and status
 (:error-generic . "Qualcosa è andato storto")
(:error-invalid-request . "Dati della richiesta non validi.")
(:error-not-found . "Risorsa richiesta non trovata.")
(:error-forbidden . "Non hai accesso a questo.")
(:error-rate-limited . "Attendi un momento e riprova.")
 (:error-text-too-long . "Il testo è troppo lungo. La lunghezza massima della traduzione è 120 caratteri.")
 (:error-input-too-long . "Testo troppo lungo")
 (:error-unknown-source-lang . "La lingua di origine selezionata non è supportata.")
 (:error-unknown-target-lang . "La lingua di destinazione selezionata non è supportata.")
 (:error-unknown-language . "Lingua sconosciuta")
 (:error-translation-unavailable . "Il servizio di traduzione è temporaneamente non disponibile. Riprova tra un momento.")
 (:error-translation-failed . "Traduzione fallita")
 (:error-translation-retry . "Impossibile generare una traduzione dopo vari tentativi. Prova a riformulare il testo.")
 (:error-quota-exceeded . "Limite traduzioni raggiunto")
 (:error-quota-exceeded-detail . "Hai esaurito tutte le traduzioni per questo mese. La tua quota si azzera automaticamente ogni mese.")
 (:quota-low-warning . "Solo ~A traduzioni rimaste. Considera di acquistarne altre.")
 (:top-up-button . "Acquista più traduzioni")
 (:top-up-price . "€5")
 (:top-up-amount . "300 traduzioni")
(:review-session-expired . "La tua sessione di ripasso è scaduta. Avvia una nuova sessione.")

 (:error-session-expired . "La tua sessione è scaduta. Accedi di nuovo.")
 (:error-session-invalid . "La tua sessione non è più valida. Accedi di nuovo.")
 (:error-custom-flashcard-generation . "Non siamo riusciti a generare la spiegazione. Riprova.")
 ;; Institutions
 (:institutions-page-title . "Hiisi per scuole e università")
 (:institutions-hero-title . "Strumenti per l'insegnamento delle lingue pensati per la classe")
 (:institutions-hero-subtitle . "Offri ai tuoi studenti mazzi condivisibili, pratica attenta alla grammatica e routine di ripasso costanti che si adattano all'insegnamento reale.")
 (:institutions-section-title . "Perché le istituzioni scelgono Hiisi")
 (:institutions-section-body . "Hiisi aiuta gli insegnanti a trasformare il materiale del corso in uno studio guidato che gli studenti riescono davvero a seguire. Crea mazzi per un corso, condividili con un link e sostieni il lavoro su lessico e grammatica senza ulteriore carico amministrativo.")
 (:institutions-benefit-1 . "Mazzi condivisibili e attività personalizzate in linea con il vostro curriculum.")
 (:institutions-benefit-2 . "I mi piace e non mi piace degli studenti aiutano a far emergere le traduzioni migliori per le espressioni comuni in classe.")
 (:institutions-benefit-3 . "Le analisi grammaticali e il ripasso dilazionato sostengono molto più della semplice memorizzazione di liste di parole isolate.")
 (:institutions-benefit-4 . "Un supporto con sensibilità da insegnante, da parte di chi ascolta con attenzione e tiene davvero alle esigenze della classe.")
 (:institutions-request-title . "Iniziamo a parlarne")
 (:institutions-request-subtitle . "Raccontaci della tua istituzione, delle lingue coinvolte e del tipo di supporto didattico di cui hai bisogno. Ti risponderemo entro una settimana.")
 (:institutions-aside-title . "Cosa succede dopo")
 (:institutions-aside-body . "Esaminiamo le vostre esigenze e rispondiamo entro una settimana per discutere l'accesso e la configurazione per il vostro istituto.")
 (:institutions-field-name . "Nome dell'istituzione")
 (:institutions-field-name-placeholder . "La tua università")
 (:institutions-field-contact-name . "Nome del contatto")
 (:institutions-field-contact-name-placeholder . "Il tuo nome")
 (:institutions-field-contact-email . "Email di contatto")
 (:institutions-field-contact-email-placeholder . "tuo@universita.it")
 (:institutions-field-domains . "Domini email")
 (:institutions-field-domains-placeholder . "universita.it, cs.universita.it")
 (:institutions-field-domains-help . "Elenco di domini email della tua istituzione separati da virgole")
 (:institutions-field-notes . "Informazioni aggiuntive")
 (:institutions-field-notes-placeholder . "Numero stimato di studenti, ciclo di fatturazione preferito, eventuali requisiti speciali...")
 (:institutions-submit . "Invia richiesta")
 (:institutions-success-title . "Grazie - Hiisi per scuole e università")
 (:institutions-success-heading . "Grazie!")
 (:institutions-success-body . "Abbiamo ricevuto la tua richiesta. Valuteremo le esigenze della tua istituzione e ti risponderemo entro una settimana.")
 (:institutions-success-back . "Torna alla home")

 ;; Footer
 (:footer-privacy . "Informativa sulla privacy")
 (:footer-terms . "Termini di servizio")

 ;; Early software notice
 (:early-software-notice . "Hiisi è in fase di sviluppo iniziale. Hai trovato un bug o hai un suggerimento?")

 ;; Informativa sulla privacy
 (:privacy-title . "Informativa sulla privacy")
 (:privacy-updated . "Ultimo aggiornamento: gennaio 2026")
 (:privacy-who-title . "Chi siamo")
 (:privacy-who-body . "Hiisi è gestita da Lambda Symbolics OÜ, una società registrata in Estonia. In quanto società estone, rispettiamo il Regolamento generale sulla protezione dei dati (GDPR) dell'Unione Europea.")
 (:privacy-collect-title . "Dati che raccogliamo")
 (:privacy-collect-intro . "Quando usi Hiisi, raccogliamo le seguenti informazioni:")
 (:privacy-collect-account-key . "Informazioni account: ")
 (:privacy-collect-account-val . "Indirizzo e-mail, nome visualizzato e password memorizzata con hash sicuro.")
 (:privacy-collect-learning-key . "Dati di apprendimento: ")
 (:privacy-collect-learning-val . "Le tue traduzioni, le schede salvate e la cronologia delle ripetizioni.")
 (:privacy-collect-usage-key . "Dati di utilizzo: ")
 (:privacy-collect-usage-val . "Log di base del server per sicurezza e debug.")
 (:privacy-use-title . "Come usiamo i tuoi dati")
 (:privacy-use-auth-key . "Autenticazione: ")
 (:privacy-use-auth-val . "Per verificare la tua identità e proteggere il tuo account.")
 (:privacy-use-service-key . "Erogazione del servizio: ")
 (:privacy-use-service-val . "Per fornire traduzioni e gestire la tua raccolta di schede.")
 (:privacy-use-ai-key . "Traduzioni con IA: ")
 (:privacy-use-ai-val . "Le tue richieste di traduzione vengono inviate a OpenRouter per generare risposte. OpenRouter può instradare le richieste verso il provider di modelli configurato. Consulta l'informativa sulla privacy di OpenRouter per sapere come tratta questi dati.")
 (:privacy-third-title . "Servizi di terze parti")
 (:privacy-third-intro . "Usiamo i seguenti servizi di terze parti:")
 (:privacy-third-openrouter-key . "OpenRouter: ")
 (:privacy-third-openrouter-val . "Per richieste di traduzione automatiche.")
 (:privacy-third-mailgun-key . "Mailgun: ")
 (:privacy-third-mailgun-val . "Per inviare email di attivazione account ed email transazionali.")
 (:privacy-third-polar-key . "Polar.sh: ")
 (:privacy-third-polar-val . "Per l'elaborazione dei pagamenti degli abbonamenti.")
 (:privacy-cookies-title . "Cookie")
 (:privacy-cookies-intro . "Usiamo solo cookie essenziali:")
 (:privacy-cookies-auth-key . "Token di autenticazione: ")
 (:privacy-cookies-auth-val . "Un cookie sicuro, accessibile solo via HTTP, per mantenerti autenticato.")
 (:privacy-cookies-lang-key . "Preferenza lingua: ")
 (:privacy-cookies-lang-val . "Per ricordare la lingua preferita dell'interfaccia.")
 (:privacy-retention-title . "Conservazione dei dati")
 (:privacy-retention-body . "I tuoi dati vengono conservati finché mantieni un account. Quando richiedi la cancellazione, il tuo account viene programmato per l'eliminazione in 14 giorni.")
 (:privacy-rights-title . "I tuoi diritti (GDPR)")
 (:privacy-rights-intro . "Ai sensi del GDPR, hai il diritto di:")
 (:privacy-rights-access . "Accedere ai tuoi dati personali")
 (:privacy-rights-export . "Esportare i tuoi dati (disponibile su /app/api/export)")
 (:privacy-rights-correct . "Richiedere la correzione di dati inesatti")
 (:privacy-rights-delete . "Richiedere l'eliminazione del tuo account e dei tuoi dati")
 (:privacy-rights-object . "Opporti al trattamento dei tuoi dati")
 (:privacy-rights-contact . "Per esercitare questi diritti, contattaci a")
 (:privacy-contact-title . "Contatto")
 (:privacy-contact-intro . "Per richieste relative alla privacy:")
 (:privacy-contact-email-label . "Email: ")
 (:privacy-address-1 . "Lambda Symbolics OÜ")
 (:privacy-address-2 . "Harju maakond, Tallinn, Kesklinna linnaosa, Tornimäe tn 5, 10145")

 ;; Termini di servizio
 (:terms-title . "Termini di servizio")
 (:terms-updated . "Ultimo aggiornamento: gennaio 2026")
 (:terms-1-title . "1. Descrizione del servizio")
 (:terms-1-body . "Hiisi è un'applicazione per l'apprendimento delle lingue che fornisce traduzioni automatiche con spiegazioni grammaticali e schede con ripetizione distribuita. Il servizio è gestito da Lambda Symbolics OÜ.")
 (:terms-2-title . "2. Registrazione dell'account")
 (:terms-2-body . "Per usare Hiisi devi creare un account con un indirizzo e-mail valido. Sei responsabile della sicurezza delle credenziali del tuo account.")
 (:terms-3-title . "3. Abbonamenti e pagamenti")
 (:terms-3-body . "Hiisi offre piani di abbonamento a pagamento (mensile e annuale). Gli abbonamenti sono elaborati tramite Polar.sh.")
 (:terms-3-list-1 . "Gli abbonamenti si rinnovano automaticamente salvo cancellazione prima della data di rinnovo.")
 (:terms-3-list-2 . "I rimborsi vengono forniti in conformità alle leggi applicabili di tutela dei consumatori.")
 (:terms-3-list-3 . "Il mancato pagamento comporta la perdita di accesso alle funzionalità premium.")
 (:terms-4-title . "4. Uso consentito")
 (:terms-4-intro . "Accetti di non:")
 (:terms-4-list-1 . "Usare il servizio per finalità illegali")
 (:terms-4-list-2 . "Tentare di aggirare limiti di utilizzo o misure di sicurezza")
 (:terms-4-list-3 . "Condividere le credenziali del tuo account con altri")
 (:terms-4-list-4 . "Usare strumenti automatizzati in modo da degradare le prestazioni per altri utenti")
 (:terms-5-title . "5. Contenuti e proprietà intellettuale")
 (:terms-5-body-1 . "Le traduzioni generate da Hiisi sono create automaticamente e potrebbero non essere uniche. Puoi usare traduzioni e schede per scopi personali, ma non detieni diritti esclusivi di paternità sui contenuti generati automaticamente.")
 (:terms-5-body-2 . "L'applicazione Hiisi, il marchio e i contenuti originali restano proprietà di Lambda Symbolics OÜ.")
 (:terms-6-title . "6. Disponibilità del servizio")
 (:terms-6-intro . "Hiisi viene fornita così com'è. Non garantiamo:")
 (:terms-6-list-1 . "Servizio ininterrotto o privo di errori")
 (:terms-6-list-2 . "Accuratezza delle traduzioni generate automaticamente")
 (:terms-6-list-3 . "Disponibilità di funzionalità specifiche")
 (:terms-6-body . "Possiamo modificare o interrompere funzionalità in qualsiasi momento.")
 (:terms-7-title . "7. Limitazione di responsabilità")
 (:terms-7-body-1 . "Nella misura massima consentita dalla legge, Lambda Symbolics OÜ non è responsabile per danni indiretti, incidentali, speciali o consequenziali derivanti dall'uso di Hiisi.")
 (:terms-7-body-2 . "La nostra responsabilità totale non supererà l'importo da te pagato per il servizio nei 12 mesi precedenti al reclamo.")
 (:terms-8-title . "8. Chiusura dell'account")
 (:terms-8-body-1 . "Possiamo sospendere o chiudere il tuo account se violi questi termini. Puoi richiedere l'eliminazione dell'account in qualsiasi momento dall'applicazione.")
 (:terms-8-body-2 . "Dopo una richiesta di eliminazione, il tuo account viene programmato per l'eliminazione in 14 giorni.")
 (:terms-9-title . "9. Modifiche ai termini")
 (:terms-9-body . "Possiamo aggiornare questi termini periodicamente. L'uso continuato di Hiisi dopo le modifiche costituisce accettazione dei nuovi termini.")
 (:terms-10-title . "10. Legge applicabile")
 (:terms-10-body . "Questi termini sono regolati dalle leggi dell'Estonia. Eventuali controversie saranno risolte dai tribunali dell'Estonia.")
 (:terms-contact-title . "Contatto")
 (:terms-contact-intro . "Per domande su questi termini:")
 (:terms-contact-email-label . "Email: ")
 (:terms-address-1 . "Lambda Symbolics OÜ")
 (:terms-address-2 . "Harju maakond, Tallinn, Kesklinna linnaosa, Tornimäe tn 5, 10145")

 ;; Decks
 (:decks-title . "Mazzi")
 (:decks-subtitle . "Crea mazzi personalizzati e condividili con altri.")
 (:decks-create-title . "Crea mazzo")
 (:decks-name-placeholder . "Nome del mazzo")
 (:decks-desc-placeholder . "Descrizione")
 (:decks-create-btn . "Crea mazzo")
 (:decks-edit-title . "Modifica mazzo")
 (:decks-edit-btn . "Modifica mazzo")
 (:decks-update-btn . "Salva modifiche")
 (:decks-default-badge . "Automatico")
 (:decks-default-description . "Questo mazzo è gestito automaticamente per questa coppia di lingue.")
 (:decks-default-readonly . "I mazzi automatici hanno nomi e descrizioni fissi.")
 (:decks-delete-btn . "Elimina mazzo")
 (:decks-delete-confirm . "Sei sicuro di voler eliminare questo mazzo?")
 (:decks-error-name-required . "Il nome del mazzo è obbligatorio.")
 (:decks-error-name-too-long . "Il nome del mazzo può avere al massimo ~A caratteri.")
 (:decks-error-desc-too-long . "La descrizione del mazzo può avere al massimo ~A caratteri.")
 (:decks-error-default-readonly . "I mazzi automatici non possono essere modificati.")
 (:decks-error-default-delete-forbidden . "I mazzi automatici non possono essere eliminati.")
 (:decks-your-title . "I tuoi mazzi")
 (:decks-col-updated . "Aggiornato")
 (:decks-no-decks . "Ancora nessun mazzo.")
 (:decks-open-btn . "Apri")
 (:decks-view-deck-btn . "Visualizza mazzo")
 (:decks-no-desc . "Nessuna descrizione.")
 (:decks-share-title . "Link di condivisione")
 (:decks-share-info . "Chiunque con questo link può importare il mazzo:")
 (:decks-share-copy . "Copia link")
 (:decks-share-copied . "Copiato")
 (:decks-add-from-flashcards-title . "Aggiungi traduzioni")
 (:decks-add-from-flashcards-info . "Scegli una scheda per aggiungere la sua traduzione a questo mazzo.")
 (:decks-open-flashcards . "Aggiungi dalle schede")
 (:decks-filter-from . "Lingua di partenza")
 (:decks-filter-to . "Lingua di arrivo")
 (:decks-filter-any . "Qualsiasi lingua")
 (:decks-filter-include-assigned . "Includi le schede già in un mazzo")
 (:decks-flashcards-add . "Aggiungi")
 (:decks-flashcards-added . "Aggiunto")
 (:decks-flashcards-in-deck . "In un altro mazzo")
 (:decks-flashcards-empty . "Nessuna scheda corrisponde a questi filtri.")
 (:decks-items-title . "Contenuto del mazzo")
 (:decks-col-original . "Originale")
 (:decks-col-translated . "Traduzione")
 (:decks-col-lang . "Lingua destinazione")
 (:decks-no-items . "Ancora nessun elemento.")
 (:decks-share-page-title . "Condividi mazzo")
 (:decks-share-preview . "Anteprima e importa questo mazzo.")
 (:decks-import-title . "Importa")
 (:decks-import-btn . "Importa mazzo")
 (:starter-decks-title . "Biblioteca")
 (:starter-decks-subtitle . "Importa mazzi pronti di Hiisi e della community.")
 (:starter-decks-marketplace-btn . "Biblioteca")
 (:starter-decks-explanation-language . "Lingua delle spiegazioni")
 (:starter-decks-search-label . "Cerca")
 (:starter-decks-source-label . "Origine")
 (:starter-decks-source-all . "Tutti i mazzi")
 (:starter-decks-change-language . "Cambia")
 (:starter-decks-filters-button . "Filtri")
 (:starter-decks-search-placeholder . "Cerca nella biblioteca")
 (:starter-decks-apply-filters . "Applica filtri")
 (:starter-decks-select-triplet-hint . "Scegli la lingua di partenza e di arrivo per esplorare i mazzi compatibili.")
 (:starter-decks-official-badge . "Ufficiale")
 (:starter-decks-community-badge . "Comunità")
 (:starter-decks-by-hiisi . "Di Hiisi")
 (:starter-decks-preview-btn . "Anteprima")
 (:starter-decks-card-count . "~A carte")
 (:starter-decks-no-results . "Nessun mazzo corrisponde a questi filtri.")
 (:starter-decks-source-cards-title . "Carte in questo mazzo")
 (:starter-decks-more-cards-included . "+~A altre carte incluse.")
 (:starter-decks-sample-title . "Carte di esempio")
 (:starter-decks-generating . "Preparazione del tuo mazzo ~A")
 (:starter-decks-generating-detail . "Lo importeremo appena sarà pronto. Puoi continuare a esplorare la Biblioteca o tornare tra poco.")
 (:starter-decks-generation-failed . "Generazione non riuscita")
 (:starter-decks-generation-failed-detail . "L'ultimo tentativo di generazione non è riuscito. Prova a importare di nuovo il mazzo.")
 (:starter-decks-login-detail . "Accedi per importare questo mazzo nella tua raccolta.")
 (:starter-decks-subscribe-btn . "Vedi i piani")
 (:starter-decks-subscribe-detail . "I mazzi della biblioteca sono disponibili con un abbonamento attivo o un periodo di prova.")
 (:library-submit-title . "Invia alla biblioteca")
 (:library-submit-intro . "Invia questo mazzo alla biblioteca per la revisione amministrativa prima della pubblicazione.")
 (:library-submit-btn . "Invia mazzo")
 (:library-submit-approved . "Approvato per la biblioteca")
 (:library-submit-approved-detail . "Questo mazzo è pubblicato nella biblioteca.")
 (:library-submit-pending . "In revisione")
 (:library-submit-pending-detail . "Questo mazzo è stato inviato ed è in attesa della revisione amministrativa.")
 (:library-submit-rejected . "Servono modifiche prima della pubblicazione")
 (:library-submit-rejected-detail . "Questo invio è stato rifiutato. Aggiorna il mazzo e invialo di nuovo.")
 (:library-error-empty . "Aggiungi almeno una carta prima di inviare questo mazzo alla biblioteca.")
 (:library-error-missing-triplet . "Ogni carta di un invio alla biblioteca deve avere una tripletta linguistica completa.")
 (:library-error-mixed-triplet . "Tutte le carte di un invio alla biblioteca devono condividere la stessa tripletta linguistica.")
 (:starter-deck-topic-greetings-title . "Saluti e presentazioni")
 (:starter-deck-topic-greetings-description . "Saluti, nomi, formule di cortesia di base e frasi per il primo incontro.")
 (:starter-deck-topic-travel-title . "Viaggio essenziale")
 (:starter-deck-topic-travel-description . "Stazioni, biglietti, prezzi, richieste di aiuto e orientamento.")
 (:starter-deck-topic-numbers-title . "Numeri e prezzi")
 (:starter-deck-topic-numbers-description . "Contare, totali, prezzi, piani degli edifici e quantità quotidiane.")
 (:starter-deck-topic-time-title . "Orario e date")
 (:starter-deck-topic-time-description . "Giorni, mesi, appuntamenti, orario e date relative.")
 (:starter-deck-topic-food-title . "Ristorante e cibo")
 (:starter-deck-topic-food-description . "Ordinare, esigenze alimentari, bevande, il conto e pasti quotidiani fuori casa.")
 (:starter-deck-topic-emergency-title . "Emergenze e salute")
 (:starter-deck-topic-emergency-description . "Medici, farmacie, sintomi, parti del corpo e aiuto urgente.")
 (:starter-deck-topic-directions-title . "Indicazioni e trasporti")
 (:starter-deck-topic-directions-description . "Svolte, fermate, biglietti, binari e muoversi in città.")
 (:starter-deck-topic-school-title . "Scuola e istruzione")
 (:starter-deck-topic-school-description . "Lezioni, compiti, esami, materiale scolastico e vita quotidiana a scuola.")
 (:starter-deck-topic-university-title . "Università e studi")
 (:starter-deck-topic-university-description . "Lezioni, seminari, corsi di studio, compiti e vita quotidiana nel campus.")

 ;; Flashcards management page
 (:flashcards-title . "Le mie carte")
 (:flashcards-subtitle . "Tutte le tue carte salvate in un unico posto. Cerca, organizza e gestisci.")
 (:flashcards-search-placeholder . "Cerca carte...")
 (:flashcards-filter-button . "Filtri")
 (:flashcards-filter-title . "Filtra le carte")
 (:flashcards-filter-recollection . "Quanto bene le conosci")
 (:flashcards-filter-any-recollection . "Qualsiasi livello")
 (:flashcards-hide-perfected . "Nascondi le carte già padroneggiate")
 (:flashcards-col-original . "Originale")
 (:flashcards-col-translated . "Traduzione")
 (:flashcards-no-cards . "Nessuna carta ancora. Inizia a tradurre per crearne alcune!")
 (:flashcards-image-label . "Immagine")
 (:flashcards-image-upload . "Carica immagine")
 (:flashcards-image-replace . "Sostituisci immagine")
 (:flashcards-image-remove . "Rimuovi immagine")
 (:flashcards-pagination-label . "Pagine delle schede")
 (:flashcards-pagination-status . "Pagina ~A di ~A")
 (:flashcards-pagination-previous . "Precedente")
 (:flashcards-pagination-next . "Successiva")

 ;; Landing page (redesign)
 (:landing-hero-headline . "Ogni parola spiegata. Ogni ripasso programmato. Quindici lingue.")
 (:landing-hero-subheadline . "Hiisi è il traduttore che ti insegna la grammatica mentre leggi, e l'app di flashcard che si costruisce da quello che traduci davvero.")
 (:landing-hero-trust-line . "14 giorni gratis. Nessuna carta richiesta.")
 (:landing-credibility-languages . "15 lingue")
 (:landing-credibility-ai . "Ogni parola spiegata")
 (:landing-credibility-srs . "Ripetizione dilazionata integrata")
 (:landing-languages-title . "Lingue supportate")
 (:landing-step-1-title . "Incolla una frase")
 (:landing-step-1-desc . "Di qualsiasi lunghezza, in una qualsiasi delle 15 lingue. Ottieni la traduzione e l'analisi grammaticale di ogni parola.")
 (:landing-step-2-title . "Salva ciò che vale la pena ricordare")
 (:landing-step-2-desc . "Un clic trasforma una traduzione in una flashcard, con la frase originale conservata come contesto.")
 (:landing-step-3-title . "Ripassa al momento giusto")
 (:landing-step-3-desc . "Ripetizione dilazionata con SM-2, lo stesso algoritmo di Anki. Le carte su cui fai più fatica tornano prima.")
 (:landing-feature-grammar-title . "Ogni parola spiegata, nella tua lingua")
 (:landing-feature-grammar-desc . "Le traduzioni includono caso, genere, aspetto e modo analizzati parola per parola. Partitivo finlandese, animatezza ceca, aspetto polacco, contrazioni dative tedesche, tutto etichettato e collegato a un riferimento grammaticale.")
 (:landing-feature-srs-title . "L'abitudine alla ripetizione dilazionata, automatizzata")
 (:landing-feature-srs-desc . "L'algoritmo SM-2 si adatta alle tue prestazioni. Le schede difficili appaiono più spesso. Le schede che conosci appaiono meno.")
 (:landing-feature-share-title . "I tuoi mazzi, o quelli della community")
 (:landing-feature-share-desc . "Organizza le schede in mazzi tematici. Condividi qualsiasi mazzo con un link oppure esplora la libreria della comunità per trovare mazzi condivisi da altri.")
 (:landing-pricing-trial-note . "Include 14 giorni di prova gratis")
 (:landing-pricing-monthly-after . "14 giorni gratis, poi ~A/mese")
 (:landing-pricing-annual-after . "14 giorni gratis, poi ~A/anno")
 (:landing-faq-title . "Domande frequenti")
 (:landing-faq-trial-cap-q . "Quante traduzioni ricevo durante la prova?")
 (:landing-faq-trial-cap-a . "Ricevi 200 traduzioni durante la prova di 14 giorni. Dopo l'abbonamento, ricevi 600 al mese.")
 (:landing-final-cta-title . "La tua prima frase richiede cinque secondi.")
 (:landing-final-cta-subtitle . "Incolla qualsiasi cosa in finlandese, ceco, polacco o in una qualsiasi delle altre dodici lingue. Guarda cosa ne fa Hiisi. Quattordici giorni gratis.")

 ;; Trial status (in-app)
 (:trial-status . "Prova gratuita")
 (:error-trial-quota-exceeded . "Limite traduzioni di prova raggiunto")
 (:error-trial-quota-detail . "Hai usato tutte le 200 traduzioni di prova. Abbonati per continuare a imparare.")

 ;; Custom flashcards
 (:custom-flashcard-create-title . "Crea scheda")
 (:custom-flashcard-edit-title . "Modifica scheda")
 (:custom-flashcard-original . "Testo originale")
 (:custom-flashcard-translated . "Traduzione")
 (:custom-flashcard-lang-from . "Lingua di origine")
 (:custom-flashcard-lang-to . "Lingua di destinazione")
 (:custom-flashcard-note . "Nota didattica")
 (:custom-flashcard-forms . "Analisi grammaticale")
 (:custom-flashcard-form-term . "Termine")
 (:custom-flashcard-form-explanation . "Spiegazione")
 (:custom-flashcard-add-form . "Aggiungi termine grammaticale")
 (:custom-flashcard-remove-form . "Rimuovi")
 (:custom-flashcard-ai-fill . "Compila con IA")
 (:custom-flashcard-create-btn . "Crea scheda")
 (:custom-flashcard-update-btn . "Salva modifiche")

  ;; Newsletter
  (:newsletter-email-label . "Indirizzo e-mail")
  (:newsletter-developer-label . "Sono uno sviluppatore")
  (:newsletter-developer-hint . "ricevi aggiornamenti tecnici")
  (:landing-newsletter-title . "Ricevi aggiornamenti su Hiisi.")
  (:landing-newsletter-body . "Iscriviti alla newsletter per aggiornamenti sul prodotto, nuove lingue supportate, mazzi iniziali e offerte occasionali per membri fondatori.")
  (:landing-newsletter-fine-print . "Niente spam. Solo aggiornamenti sul prodotto.")
  (:landing-newsletter-button . "Iscriviti alla newsletter")
  (:newsletter-unsubscribe-page-title . "Disiscriviti dalla newsletter di Hiisi")
  (:newsletter-unsubscribe-title . "Disiscriviti")
  (:newsletter-unsubscribe-subtitle . "Inserisci la tua e-mail per non ricevere più aggiornamenti su Hiisi.")
  (:newsletter-unsubscribe-button . "Disiscriviti")
  (:newsletter-feedback-email-required . "Inserisci il tuo indirizzo e-mail.")
  (:newsletter-feedback-email-invalid . "Inserisci un indirizzo e-mail valido.")
  (:newsletter-feedback-already-signed-up . "Sei già iscritto. Ti terremo aggiornato!")
  (:newsletter-feedback-signed-up . "Sei nella lista! Ti invieremo aggiornamenti occasionali su Hiisi.")
  (:newsletter-feedback-unsubscribed . "Se questa e-mail era iscritta, è stata rimossa dagli aggiornamenti su Hiisi.")
  (:newsletter-feedback-generic-error . "Qualcosa è andato storto. Riprova.")

  ;; Issue reporting
  (:issues-open-button . "Segnala un errore")
 (:issues-modal-title . "Segnala un problema")
 (:issues-modal-subtitle . "Descrivi cosa è andato storto. Includeremo automaticamente la pagina corrente.")
 (:issues-title-label . "Titolo breve")
 (:issues-title-placeholder . "Breve riepilogo del problema")
 (:issues-message-label . "Che cosa è successo?")
 (:issues-message-placeholder . "Indica i passaggi per riprodurre, il comportamento atteso e cosa è successo invece.")
 (:issues-submit . "Invia segnalazione")
 (:issues-cancel . "Annulla")
 (:issues-success . "La tua segnalazione è stata inviata. La controlleremo appena possibile.")
 (:issues-error-required . "Descrivi il problema prima di inviare.")
 (:issues-error-title-too-long . "Il titolo della segnalazione è troppo lungo. Mantienilo sotto i 160 caratteri.")
 (:issues-error-too-long . "Il testo della segnalazione è troppo lungo. Resta sotto i 4000 caratteri.")
 (:issues-error-rate-limit . "Troppe segnalazioni da questa origine. Attendi e riprova più tardi.")
 (:issues-error-generic . "Impossibile inviare la segnalazione. Riprova.")

)
