;;; Dutch translations

(
 ;; Language metadata (used for language picker)
 (:lang-name . "Nederlands")
 (:lang-flag . "🇳🇱")

 ;; Language modal (first-visit language selection)
 (:lang-modal-title . "Kies je taal")
 (:lang-modal-subtitle . "Selecteer je voorkeurstaal voor de interface:")

 ;; Navigation
 (:nav-translate . "Vertalen")
 (:nav-review . "Herhalen")
 (:nav-flashcards . "Mijn kaarten")
 (:nav-dashboard . "Dashboard")
 (:nav-decks . "Stapels")
 (:nav-logout . "Uitloggen")
 (:nav-home . "Home")
 (:nav-pricing . "Prijzen")
 (:nav-institutions . "Voor instellingen")
 (:nav-export-data . "Gegevens exporteren")
 (:nav-open-navigation . "Navigatie openen")
 (:theme-light . "Licht")
 (:theme-dark . "Donker")

 ;; App title and branding
 (:app-title . "Hiisi - Talen leren")

 ;; Landing page
 (:landing-meta-title . "Hiisi: app om talen te leren met grammatica en flashcards")
 (:app-meta-description . "Hiisi is een app om talen te leren. Elke zin die je vertaalt, wordt een flashcard met ingebouwde grammatica, gepland door SM-2, het Anki-algoritme. 15 talen.")
 (:trial-start-cta . "Aan de slag met Hiisi")
 (:subscription-best-value . "Beste waarde")

 ;; Auth pages
 (:auth-register . "Registreren")
 (:auth-login . "Inloggen")
 (:auth-email . "E-mail")
 (:auth-password . "Wachtwoord")
 (:auth-password-again . "Bevestig wachtwoord")
 (:auth-display-name . "Weergavenaam")
 (:auth-register-title . "Registreer bij Hiisi")
 (:auth-register-subtitle . "Maak een nieuw account aan")
 (:auth-login-title . "Log in bij Hiisi")
 (:auth-login-subtitle . "Voer je gegevens in")
 (:auth-login-invalid-credentials . "Ongeldig e-mailadres of wachtwoord.")
 (:auth-login-rate-limited . "Te veel inlogpogingen. Wacht een paar minuten en probeer het opnieuw.")
(:auth-register-rate-limited . "Te veel registratiepogingen. Wacht een paar minuten en probeer het opnieuw.")
(:auth-email-invalid . "Voer een geldig e-mailadres in.")
(:auth-password-too-short . "Het wachtwoord moet minimaal 8 tekens lang zijn.")
(:auth-passwords-mismatch . "De wachtwoorden komen niet overeen.")
(:auth-display-name-invalid . "De weergavenaam moet tussen 1 en 100 tekens lang zijn.")
(:auth-register-email-exists . "Er bestaat al een account met dit e-mailadres.")
(:auth-register-unavailable . "Registratie is tijdelijk niet beschikbaar. Probeer het later opnieuw.")
(:auth-register-plan-required . "Kies een abonnement voordat je een account maakt.")
(:auth-preapproved-email-unrecognized . "Gebruik het e-mailadres uit je uitnodiging of kies een abonnement voordat je een account maakt.")
(:auth-institution-register . "Kom je via een instelling?")
(:auth-institution-stage-title . "Institutionele toegang")
(:auth-institution-stage-subtitle . "Gebruik je school- of universiteitsmail. Geschikte accounts worden via de instelling ontgrendeld na e-mailverificatie.")
(:auth-institution-title . "Registreer via je instelling")
(:auth-institution-subtitle . "Gebruik je school- of universiteitsmail. Als je instelling al in Hiisi is ingesteld, wordt je account na e-mailverificatie via die instelling ontgrendeld; de individuele proefperiode van 14 dagen hoort bij registratie met een persoonlijk abonnement.")
(:auth-institution-benefit-email . "Gebruik het e-mailadres van je school of universiteit.")
(:auth-institution-benefit-access . "Geschikte accounts krijgen institutionele toegang na e-mailverificatie.")
(:auth-institution-benefit-fallback . "Als het domein niet wordt herkend, kies dan een individueel abonnement of vraag je instelling contact op te nemen met Hiisi.")
(:auth-see-included . "Bekijk wat is inbegrepen")
(:auth-institution-check-access . "Toegang controleren")
(:auth-institution-email-eligible-title . "Institutionele toegang bevestigd")
(:auth-institution-email-eligible-detail . "Ga verder met dit e-mailadres om je account aan te maken. Toegang wordt ontgrendeld na e-mailverificatie.")
(:auth-institution-change-email . "Gebruik een ander e-mailadres")
(:auth-institution-outcome-note . "Als je school of universiteit Hiisi-toegang biedt, wordt je account na e-mailverificatie ontgrendeld. Als het domein niet in aanmerking komt, kies dan een persoonlijk abonnement om de proefperiode van 14 dagen te starten.")
(:auth-institution-personal-plan-link . "Bekijk persoonlijke abonnementen")
(:auth-institution-domain-unrecognized . "We herkennen dat institutionele e-maildomein nog niet. Kies een persoonlijk abonnement om de proefperiode van 14 dagen te starten, of vraag je instelling contact op te nemen met Hiisi.")
(:subscribe-institution-callout-title . "Gebruik je Hiisi via een school of universiteit?")
(:subscribe-institution-callout-body . "Registreer met je institutionele e-mail en Hiisi ontgrendelt automatisch toegang als je instelling al is ingesteld.")
(:auth-activation-email-send-failed . "Het verzenden van de activatiemail is mislukt. Probeer het opnieuw.")
 (:auth-forgot-password . "Wachtwoord vergeten?")
 (:auth-no-account . "Heb je geen account?")
 (:auth-have-account . "Heb je al een account?")
 (:auth-google . "Google")
 (:auth-google-login-failed . "Inloggen met Google is mislukt. Probeer het opnieuw.")
 (:auth-account-created . "Account aangemaakt!")
 (:auth-check-email . "Controleer je e-mail voor de activatielink.")
 (:auth-redirect-login . "Doorsturen naar inloggen over")
 (:auth-seconds . "seconden...")
 (:auth-go-now . "Ga nu")
 (:auth-not-activated . "Account niet geactiveerd")
 (:auth-activate-title . "Activeer je account!")
 (:auth-activated . "Account geactiveerd!")
 (:auth-activated-message . "Je account is geactiveerd. Je kunt Hiisi nu gebruiken.")
 (:auth-redirecting . "Doorsturen over")
 (:auth-go-to-app . "Naar de app")
 (:onboarding-title . "Hoe Hiisi werkt")
 (:onboarding-subtitle . "Vertaal echte tekst, bekijk de grammatica, sla bruikbare items op en herhaal ze later.")
 (:onboarding-translate-detail . "Begin met echte tekst. Hiisi geeft de vertaling, de uitgelijnde vormen en de volgende studieacties op één plek terug.")
 (:onboarding-grammar-detail . "Open de grammaticale uitsplitsing om te zien welke vormen in de zin bij elkaar horen en welke functie elk deel heeft.")
 (:onboarding-review-detail . "Sla bruikbare vertalingen op en herhaal ze later met gespreide herhaling, zodat ze in het langetermijngeheugen blijven.")
 (:onboarding-decks-detail . "Groepeer bruikbare items in decks, deel ze met anderen en houd verwant materiaal bij elkaar.")
 (:onboarding-back . "Terug")
 (:onboarding-next . "Verder")
 (:onboarding-skip . "Gids overslaan")
 (:auth-resend-title . "Activatiemail opnieuw verzenden")
 (:auth-resend-subtitle . "Voer je e-mailadres in om een nieuwe activatielink te ontvangen.")
 (:auth-resend-button . "Activatiemail opnieuw verzenden")
 (:auth-resend-success . "Activatiemail verzonden!")
 (:auth-resend-success-detail . "Controleer je inbox voor de nieuwe activatielink.")
 (:auth-resend-rate-limited . "Wacht een paar minuten voordat je nog een activatiemail aanvraagt.")
 (:auth-resend-cooldown . "Je kunt over ~a seconden een nieuwe mail aanvragen.")
 (:auth-back-to-login . "Terug naar inloggen")
 (:auth-forgot-password-title . "Wachtwoord vergeten")
 (:auth-forgot-password-subtitle . "Voer je e-mailadres in en we sturen je een link om je wachtwoord opnieuw in te stellen.")
 (:auth-send-reset-link . "Stuur resetlink")
 (:auth-reset-email-sent . "Resetlink verzonden!")
 (:auth-reset-email-sent-detail . "Als er een account bestaat met dit e-mailadres, ontvang je binnenkort een link om je wachtwoord opnieuw in te stellen.")
 (:auth-reset-rate-limited . "Wacht een paar minuten voordat je nog een wachtwoord-reset aanvraagt.")
 (:auth-reset-invalid-token . "Deze resetlink is ongeldig of verlopen.")
 (:auth-reset-password-title . "Wachtwoord opnieuw instellen")
 (:auth-reset-password-subtitle . "Voer hieronder je nieuwe wachtwoord in.")
 (:auth-new-password . "Nieuw wachtwoord")
 (:auth-confirm-new-password . "Bevestig nieuw wachtwoord")
 (:auth-reset-password . "Wachtwoord opnieuw instellen")
 (:auth-password-changed . "Wachtwoord gewijzigd!")
 (:auth-password-changed-detail . "Je wachtwoord is succesvol gewijzigd. Je kunt nu inloggen met je nieuwe wachtwoord.")
 (:auth-change-password-title . "Wachtwoord wijzigen")
 (:auth-change-password-subtitle . "Werk het wachtwoord van je account bij.")
 (:auth-current-password . "Huidig wachtwoord")
 (:auth-change-password . "Wachtwoord wijzigen")
 (:auth-back-to-app . "Terug naar app")
 (:auth-password-updated . "Wachtwoord bijgewerkt!")
 (:auth-password-updated-detail . "Je wachtwoord is succesvol bijgewerkt.")
(:auth-current-password-invalid . "Het huidige wachtwoord is onjuist.")
(:auth-new-password-same . "Het nieuwe wachtwoord moet verschillen van het huidige wachtwoord.")

 ;; Email copy
 (:email-common-hi . "Hallo")
 (:email-common-tagline . "Hiisi - Leer door te vertalen")
 (:email-activation-subject . "Activeer je Hiisi-account")
 (:email-activation-title . "Welkom bij Hiisi")
 (:email-activation-body . "Bedankt voor je registratie. Activeer je account door op de onderstaande link te klikken:")
 (:email-activation-button . "Account activeren")
 (:email-activation-copy-link . "Of kopieer deze link")
 (:email-activation-expiry . "Deze link verloopt over 24 uur.")
 (:email-reset-subject . "Stel je Hiisi-wachtwoord opnieuw in")
 (:email-reset-title . "Verzoek om wachtwoord opnieuw in te stellen")
 (:email-reset-body . "We hebben een verzoek ontvangen om je wachtwoord opnieuw in te stellen. Klik op de onderstaande link om een nieuw wachtwoord in te stellen:")
 (:email-reset-button . "Wachtwoord opnieuw instellen")
 (:email-reset-expiry . "Deze link verloopt over 1 uur.")
 (:email-reset-ignore . "Als je geen verzoek hebt gedaan om je wachtwoord opnieuw in te stellen, kun je deze e-mail negeren.")
 (:email-reminder-subject-due . "Tijd om je Hiisi-kaarten te herhalen")
 (:email-reminder-subject-streak . "Houd je Hiisi-reeks vast")
 (:email-reminder-cards-due . "kaarten klaar om te herhalen")
 (:email-reminder-keep-going . "Het is een paar dagen geleden sinds je laatste herhaling. Vijf minuten vandaag is genoeg om wat je al geleerd hebt niet weg te laten glippen.")
 (:email-reminder-button . "Nu herhalen")
 (:email-reminder-settings . "Herinneringen beheren")
 (:email-reminder-preview-title . "Kaarten die op je wachten")
 (:email-reminder-translation-label . "Vertaling")
 (:email-reminder-more-due-today . "extra kaarten voor vandaag")
 (:email-trial-subject . "Hoe gaat je Hiisi-proefperiode?")
 (:email-trial-expiring . "Je gratis Hiisi-proefperiode eindigt morgen.")
 (:email-trial-feedback . "Bevalt Hiisi je? Laat ons weten wat je het meest heeft geholpen.")
 (:email-trial-strengths . "Je kunt echte teksten vertalen, de beste items opslaan als flashcards en leren met gespreide herhaling.")
 (:email-trial-reply . "Beantwoord deze e-mail en je bericht komt rechtstreeks bij het Hiisi-team terecht.")
 (:email-trial-button . "Kies een abonnement")
 (:email-trial-manage . "Abonnement beheren")
 (:email-trial-contact . "Mail ons")
 (:email-plan-nudge-subject . "Je vertalingen wachten op je")
 (:email-plan-nudge-title . "Je vertalingen wachten op je")
 (:email-plan-nudge-intro . "Je hebt je bij Hiisi aangemeld, maar nog geen abonnement gekozen.")
 (:email-plan-nudge-benefits-intro . "Dit krijg je met een abonnement:")
 (:email-plan-nudge-benefit-translations . "600 vertalingen per maand met grammaticale ontledingen")
 (:email-plan-nudge-benefit-flashcards . "Onbeperkte flashcards met gespreide herhaling")
 (:email-plan-nudge-benefit-decks . "Eigen decks die je kunt organiseren en delen")
 (:email-plan-nudge-pricing . "Abonnementen beginnen bij 10 EUR per maand, of bespaar met het jaarabonnement van 100 EUR per jaar (twee maanden gratis).")
 (:email-plan-nudge-feedback . "Als er iets aan Hiisi niet goed werkt voor je, beantwoord dan deze e-mail. Je bericht komt rechtstreeks bij het Hiisi-team terecht.")
 (:email-plan-nudge-button . "Kies een abonnement")
 (:email-plan-nudge-unsubscribe . "Uitschrijven voor deze e-mails")
 (:email-plan-nudge-unsubscribe-done-title . "Abonnementsmails uitgeschakeld")
 (:email-plan-nudge-unsubscribe-done-body . "Je ontvangt geen herinneringsmails meer om een abonnement te kiezen.")
 (:email-plan-nudge-unsubscribe-invalid-title . "Deze link is niet geldig")
 (:email-plan-nudge-unsubscribe-invalid-body . "Deze afmeldlink ontbreekt, is verlopen of is niet meer geldig.")
 (:email-invite-subject . "Je bent uitgenodigd voor Hiisi")
 (:email-invite-title . "Je bent uitgenodigd voor Hiisi")
 (:email-invite-intro . "Je bent uitgenodigd om Hiisi gratis te gebruiken, als tester, gewaardeerde vriend of allebei.")
 (:email-invite-details . "Gebruik de knop hieronder om je account aan te maken en vertalingen en flashcards te verkennen.")
 (:email-invite-button . "Account aanmaken")
 (:email-invite-issue-reporting . "Als er iets stukgaat of niet goed voelt, staat er onderaan elke pagina een knop om een probleem te melden.")
 (:email-issue-completed-subject . "Je Hiisi-probleem is opgelost")
 (:email-issue-completed-title . "Probleem opgelost")
 (:email-issue-completed-label . "Probleem")
 (:email-issue-completed-followup . "Open Hiisi om de oplossing te controleren of verder te gaan waar je was gebleven.")
 (:email-issue-completed-button . "Open Hiisi")
 (:email-issue-completed-open-link . "Open pagina")

 ;; Translation page
 (:translate-title . "Vertalen")
 (:translate-input-title . "Invoer")
 (:translate-input-label . "Te vertalen tekst")
 (:translate-input-placeholder . "Voer tekst in om te vertalen...")
 (:translate-example-chip . "Probeer een voorbeeld:")
 (:translate-example-sentence . "Ik ben mijn sleutels thuis vergeten.")
 (:translate-from . "Brontaal:")
 (:translate-to . "Doeltaal:")
 (:translate-select-target-placeholder . "Kies doeltaal")
 (:translate-submit . "Vertalen")
 (:translate-auto-detect . "Elke (Automatisch detecteren)")
 (:translate-empty-state . "Vertaal een woord of zin en hier zie je het resultaat, de grammaticale uitleg en studieacties.")
 (:translate-select-deck-placeholder . "Selecteer stapel (optioneel)")
 (:translate-result-title . "Vertaalresultaat")
 (:translate-save-destination-label . "Opslaglocatie")
 (:translate-save-to-my-cards . "Mijn kaarten (standaard)")
 (:translate-save-to-deck . "Opslaan in deck")
 (:translate-saved-to-my-cards . "Opgeslagen in Mijn kaarten")
 (:translate-saved-to-deck . "Opgeslagen in ~A")
 (:translate-view-my-cards . "Mijn kaarten bekijken")
 (:translate-new-deck . "Nieuwe stapel maken")
 (:translate-add-to-deck . "Toevoegen aan stapel")
 (:translate-feedback-label . "Kwaliteitsfeedback")
 (:translate-feedback-helpful . "Nuttig")
 (:translate-feedback-helpful-marked . "Gemarkeerd als nuttig")
 (:translate-regenerate-translation . "Vertaling opnieuw genereren")
 (:translate-regenerate-confirm . "Hiisi markeert dit resultaat als onnauwkeurig en genereert een nieuwe vertaling. Doorgaan?")
 (:pronunciation-label . "Uitspraak")
 (:pronunciation-show . "Uitspraak tonen")
 (:pronunciation-hide . "Uitspraak verbergen")
 (:grammar-term-examples . "Voorbeelden")
 (:grammar-term-related . "Verwante termen")
 (:grammar-term-modal-title . "Grammaticaterm")
 (:grammar-term-empty . "Selecteer een gemarkeerde term om de details te zien.")
 (:extension-login-required . "Log in bij Hiisi voordat je de browserextensie gebruikt.")
 (:extension-session-invalid . "Je Hiisi-sessie is niet meer geldig. Log opnieuw in.")
 (:extension-activation-required . "Activeer je Hiisi-account voordat je de browserextensie gebruikt.")
 (:extension-subscription-required . "Start een Hiisi-proefperiode voordat je de browserextensie gebruikt.")

 ;; Translation and Flashcards
 (:lang-auto . "Auto")
 (:lang-unknown . "?")
 (:lang-target . "Doel")
 (:translate-deck-create-title . "Nieuwe stapel maken")
 (:translate-deck-name-label . "Stapelnaam")
 (:translate-deck-name-placeholder . "bijv. Basis Fins")
 (:translate-deck-description-label . "Beschrijving (optioneel)")
 (:translate-deck-cancel . "Annuleren")
 (:translate-deck-create . "Maken")
 (:translate-rate-label . "Vertaling beoordelen")
 (:flashcards-delete . "Verwijderen")
 (:flashcards-delete-confirm . "Weet je zeker dat je deze kaart wilt verwijderen?")
 (:flashcards-deck-search-placeholder . "Stapels zoeken...")
 (:flashcards-no-decks . "Nog geen stapels. Maak er eerst een!")
 (:flashcards-deck-cancel . "Annuleren")
 (:flashcards-recollection-tooltip . "Herinnering: ~A")
 (:flashcards-recollection-poor . "Zwak")
 (:flashcards-recollection-fair . "Redelijk")
 (:flashcards-recollection-normal . "Normaal")
 (:flashcards-recollection-strong . "Sterk")
 (:flashcards-recollection-very-strong . "Zeer sterk")

 ;; Flashcard review
 (:review-title . "Herhalen")
 (:review-session-title . "Herhalingssessie")
 (:review-session-subtitle . "Oefen je opgeslagen flashcards")
 (:review-selector-title . "Kies wat je wilt herhalen")
 (:review-selector-subtitle . "Selecteer een deck of taalpaar om je herhalingssessie op te richten.")
 (:review-by-deck . "Herhaal per deck")
 (:review-by-language-pair . "Herhaal per taalpaar")
 (:review-all-cards . "Herhaal alle kaarten")
 (:review-cards-due . "kaarten te herhalen")
 (:review-deck-caught-up . "Alles bijgewerkt")
 (:review-all-caught-up . "Alles bijgewerkt!")

 (:review-no-cards . "Geen kaarten te herhalen")
 (:review-no-cards-desc . "Je hebt momenteel geen flashcards die herhaald moeten worden.")
 (:review-no-cards-hint . "Vertaal wat tekst en klik op \"Opslaan als flashcard\" om je stapel op te bouwen!")
 (:review-start-translating . "Begin met vertalen")
 (:review-click-reveal . "Klik om antwoord te tonen")
 (:review-grammar-breakdown . "Grammaticale uitleg")
 (:review-how-well . "Herinnerde je het?")
 (:review-again . "Nee")
 (:review-hard . "Nauwelijks")
 (:review-good . "Ja")
 (:review-easy . "Gemakkelijk")
 (:review-progress . "Kaart ~a van ~a")
 (:review-correct-count . "Goed")
 (:review-wrong-count . "Fout")
 (:mockup-forgot-detail . "1e persoon enkelvoud verleden tijd van \"olvidar\" (vergeten)")
 (:mockup-keys-detail . "Bezittelijk \"mis\" met vrouwelijk meervoudig zelfstandig naamwoord \"llaves\" (sleutels)")
 (:review-complete . "Sessie voltooid!")
 (:review-complete-msg . "Je hebt ~a kaarten herhaald")
 (:review-again-btn . "Opnieuw herhalen")
 (:review-translate-more . "Meer vertalen")
 (:review-streak . "dagen op rij")

 ;; Dashboard
 (:dashboard-title . "Dashboard")
 (:dashboard-welcome-title . "Vertaal je eerste tekst")
 (:dashboard-welcome-subtitle . "Vertaal een nuttige zin, sla die op in een deck en herhaal hem wanneer het ertoe doet.")
 (:dashboard-take-quick-tour . "Volg een korte rondleiding")
 (:dashboard-cards-due . "Kaarten voor vandaag")
 (:dashboard-total-cards . "Totaal kaarten")
 (:dashboard-mastered-cards . "Beheerste kaarten")
 (:dashboard-subscription . "Abonnement")
 (:dashboard-subscribed-until . "Geabonneerd tot")
 (:dashboard-trial-ends . "Proefperiode eindigt")
 (:dashboard-not-subscribed . "Niet geabonneerd")
 (:dashboard-recent . "Recente vertalingen")
 (:dashboard-no-translations . "Nog geen vertalingen")
 (:dashboard-streak . "Herhalingsreeks")
 (:dashboard-days . "dagen")
 (:dashboard-all-caught-up . "Helemaal bij!")
 (:dashboard-all-caught-up-hint . "Vertaal meer om je verzameling uit te bouwen.")
 (:dashboard-no-cards-title . "Maak je eerste studiekaarten")
 (:dashboard-no-cards-hint . "Vertaal tekst en sla nuttige zinnen op om je verzameling op te bouwen.")
 (:dashboard-first-use-checklist-title . "Eerste stappen")
 (:dashboard-first-use-checklist-translate . "Maak je eerste vertaling")
 (:dashboard-first-use-checklist-card . "Sla je eerste kaart op")
 (:dashboard-first-use-checklist-review . "Voltooi je eerste herhaling")
 (:dashboard-getting-started . "Aan de slag")
 (:dashboard-tip-1 . "Vertaal tekst die je wilt leren")
 (:dashboard-tip-2 . "Klik op \"Opslaan als flashcard\" bij vertalingen die je wilt onthouden")
 (:dashboard-tip-3 . "Herhaal je flashcards regelmatig - gespreide herhaling helpt je om langdurig te onthouden")
 (:dashboard-tip-4 . "Beoordeel eerlijk - het helpt het algoritme om je herhalingen optimaal te plannen")

 ;; Account
 (:account-title . "Account")
 (:account-subtitle . "Beheer hier je profiel, abonnement, herinneringen, exports en accountverwijdering.")
 (:account-status-title . "Status")
 (:account-profile-subtitle . "Houd je weergavenaam en e-mailadres actueel.")
 (:account-export-subtitle . "Download een kopie van je opgeslagen vertalingen, decks en herhaalgegevens.")
 (:account-deletion-title . "Account verwijderen")
 (:account-deletion-scheduled . "Je account staat gepland voor verwijdering op ~A.")
 (:account-deletion-cancel-hint . "Je kunt voor deze datum annuleren om je account te behouden.")
 (:account-deletion-cancel . "Verwijdering annuleren")
 (:account-deletion-request . "Je kunt op elk moment een verzoek tot verwijdering van je account indienen. Verwijdering wordt 14 dagen na bevestiging gepland. Als je van gedachten verandert, neem dan contact op met support voordat die periode van 14 dagen afloopt.")
 (:account-deletion-confirm . "Accountverwijdering plannen over 14 dagen vanaf vandaag?")
 (:account-deletion-schedule . "Verwijdering plannen")
 (:account-reminders-title . "E-mailherinneringen")
 (:account-reminders-subtitle . "Kies of Hiisi je mag mailen wanneer er iets voor je klaarstaat om te herhalen.")
 (:account-reminders-opt-out . "Herinneringen voor herhalen en doorgaan uitschakelen")
 (:account-reminders-save . "Voorkeuren opslaan")

 ;; Subscription
 (:subscribe-title . "Eenvoudige prijzen")
 (:subscribe-choose-plan . "Kies je abonnement")
 (:subscribe-start-today . "Begin vandaag met leren met een 14-daagse gratis proefperiode")
 (:subscribe-monthly . "Maandelijks")
 (:subscribe-annual . "Jaarlijks")
 (:subscribe-founder-member . "Oprichtend lid")
 (:subscribe-monthly-price . "€10")
 (:subscribe-annual-price . "€100")
 (:subscribe-founder-price . "€79")
 (:subscribe-founder-monthly-equivalent . "€6,58/maand, jaarlijks gefactureerd")
 (:subscribe-founder-savings . "Bespaar €41/jaar vergeleken met maandelijks")
 (:subscribe-monthly-billing-equivalent . "€10/maand, maandelijks gefactureerd")
 (:subscribe-monthly-billing-note . "Flexibele maandelijkse betaling")
 (:subscribe-per-month . "/maand")
 (:subscribe-per-year . "/jaar")
 (:subscribe-monthly-desc . "600 vertalingen per maand. Onbeperkt flashcards, stapels en herhalingen.")
 (:subscribe-unlimited-flashcards . "Onbeperkte flashcards")
 (:subscribe-grammar-explanations . "Grammatica-uitleg")
 (:subscribe-spaced-repetition . "Gespreide herhaling")
 (:subscribe-annual-desc . "Alles uit het maandplan. Twee maanden gratis.")
 (:subscribe-founder-lock . "Deze prijs blijft gelden zolang je abonnement actief blijft.")
 (:subscribe-founder-badge . "Beperkt aanbod")
 (:subscribe-founder-limit . "Beperkt tot de eerste 100 leden")
 (:subscribe-manage . "Beheer abonnement")
 (:subscribe-activated . "Abonnement geactiveerd!")
 (:subscribe-thank-you . "Je abonnement is actief. Hier kun je de facturatie beheren en meer vertalingen kopen.")
 (:subscribe-start-learning . "Begin met leren")
 (:subscribe-management . "Abonnementsbeheer")
 (:subscribe-active . "Actief abonnement")
 (:subscribe-preapproved-access . "Vooraf goedgekeurde toegang")
 (:subscribe-status . "Status:")
 (:subscribe-status-active . "Actief")
 (:subscribe-status-preapproved . "Vooraf goedgekeurd")
 (:subscribe-preapproved-detail . "Dit account gebruikt vooraf goedgekeurde toegang die door Hiisi wordt beheerd.")
 (:subscribe-days-remaining . "Dagen resterend:")
 (:subscribe-renews-on . "Verlengt op:")
 (:subscribe-no-subscription . "Geen actief abonnement")
 (:subscribe-access-features . "Kies een abonnement voor volledige toegang en facturatiebeheer op één plek.")
 (:subscribe-view-plans . "Bekijk abonnementen")
 (:subscribe-faq-title . "Veelgestelde vragen")
 (:subscribe-faq-trial-q . "Wat gebeurt er na de gratis proefperiode?")
 (:subscribe-faq-trial-a . "Je proefperiode van 14 dagen vereist geen kaart. Kies na afloop een betaald abonnement om volledige toegang te houden.")
 (:subscribe-faq-cancel-q . "Kan ik op elk moment opzeggen?")
 (:subscribe-faq-cancel-a . "Ja! Je kunt je abonnement op elk moment opzeggen. Je behoudt toegang tot het einde van je factureringsperiode.")
 (:subscribe-faq-payment-q . "Welke betaalmethoden accepteren jullie?")
 (:subscribe-faq-payment-a . "We accepteren alle gangbare creditcards en betaalkaarten via onze betalingspartner Polar.sh.")
 (:subscribe-copyright . "Lambda Symbolics OÜ © 2026.")
(:subscribe-checkout-unavailable . "Checkout is tijdelijk niet beschikbaar. Probeer het opnieuw.")
(:subscribe-portal-unavailable . "Abonnementsbeheer is tijdelijk niet beschikbaar. Probeer het opnieuw.")
(:subscribe-founder-sold-out . "Het aanbod voor oprichtende leden is uitverkocht")
(:subscribe-founder-unavailable . "Het aanbod voor oprichtende leden is nu niet beschikbaar.")
(:subscribe-checkout-cta . "Abonneren")

 ;; Errors and status
 (:error-generic . "Er ging iets mis")
(:error-invalid-request . "Ongeldige aanvraaggegevens.")
(:error-not-found . "De gevraagde bron is niet gevonden.")
(:error-forbidden . "Je hebt hier geen toegang toe.")
(:error-rate-limited . "Wacht even en probeer het opnieuw.")
 (:error-text-too-long . "Tekst is te lang. Maximale vertalingslengte is 120 tekens.")
 (:error-input-too-long . "Invoer te lang")
 (:error-unknown-source-lang . "De brontaal die je hebt geselecteerd wordt niet ondersteund.")
 (:error-unknown-target-lang . "De doeltaal die je hebt geselecteerd wordt niet ondersteund.")
 (:error-unknown-language . "Onbekende taal")
 (:error-translation-unavailable . "Vertaalservice is tijdelijk niet beschikbaar. Probeer het zo opnieuw.")
 (:error-translation-failed . "Vertaling mislukt")
 (:error-translation-retry . "Kon na meerdere pogingen geen vertaling genereren. Probeer je tekst anders te formuleren.")
 (:error-quota-exceeded . "Vertaallimiet bereikt")
 (:error-quota-exceeded-detail . "Je hebt al je vertalingen voor deze maand gebruikt. Je quotum wordt automatisch elke maand gereset.")
 (:quota-low-warning . "Nog maar ~A vertalingen over. Overweeg om meer te kopen.")
 (:top-up-button . "Koop meer vertalingen")
 (:top-up-price . "€5")
 (:top-up-amount . "300 vertalingen")
(:review-session-expired . "Je herhaalsessie is verlopen. Start een nieuwe sessie.")

 (:error-session-expired . "Je sessie is verlopen. Log opnieuw in.")
 (:error-session-invalid . "Je sessie is niet meer geldig. Log opnieuw in.")
 (:error-custom-flashcard-generation . "We konden de uitleg niet genereren. Probeer het opnieuw.")
 ;; Institutions
 (:institutions-page-title . "Hiisi voor scholen en universiteiten")
 (:institutions-hero-title . "Hulpmiddelen voor taalonderwijs, gemaakt voor de klas")
 (:institutions-hero-subtitle . "Geef je studenten deelbare stapels, grammatica-bewuste oefening en vaste herhaalroutines die passen bij echt onderwijs.")
 (:institutions-section-title . "Waarom instellingen Hiisi gebruiken")
 (:institutions-section-body . "Hiisi helpt docenten om lesmateriaal om te zetten in begeleide studie die studenten echt kunnen volhouden. Maak stapels voor een cursus, deel ze met een link en ondersteun woordenschat- en grammaticaoefening zonder extra administratieve last.")
 (:institutions-benefit-1 . "Deelbare stapels en eigen opdrachten die aansluiten op jullie curriculum.")
 (:institutions-benefit-2 . "Likes en dislikes van studenten helpen de sterkste vertalingen naar boven voor veelvoorkomende zinnen uit de les.")
 (:institutions-benefit-3 . "Grammatica-uitsplitsingen en gespreide herhaling ondersteunen meer dan het uit het hoofd leren van losse woordenlijsten.")
 (:institutions-benefit-4 . "Ondersteuning met een docentenblik, van iemand die goed luistert en echt geeft om wat er in de klas nodig is.")
 (:institutions-request-title . "Laten we in gesprek gaan")
 (:institutions-request-subtitle . "Vertel ons over je instelling, jullie talen en het soort ondersteuning dat je in het onderwijs nodig hebt. We nemen binnen een week contact op.")
 (:institutions-aside-title . "Wat er daarna gebeurt")
 (:institutions-aside-body . "Wij beoordelen uw behoeften en reageren binnen een week om de toegang en opzet voor uw instelling te bespreken.")
 (:institutions-field-name . "Naam van de instelling")
 (:institutions-field-name-placeholder . "Jouw universiteit")
 (:institutions-field-contact-name . "Contactpersoon")
 (:institutions-field-contact-name-placeholder . "Jouw naam")
 (:institutions-field-contact-email . "Contact-e-mail")
 (:institutions-field-contact-email-placeholder . "jij@universiteit.nl")
 (:institutions-field-domains . "E-maildomeinen")
 (:institutions-field-domains-placeholder . "universiteit.nl, cs.universiteit.nl")
 (:institutions-field-domains-help . "Komma-gescheiden lijst met e-maildomeinen van je instelling")
 (:institutions-field-notes . "Aanvullende informatie")
 (:institutions-field-notes-placeholder . "Geschat aantal studenten, gewenste factureringscyclus, eventuele speciale wensen...")
 (:institutions-submit . "Verzoek indienen")
 (:institutions-success-title . "Bedankt - Hiisi voor scholen en universiteiten")
 (:institutions-success-heading . "Bedankt!")
 (:institutions-success-body . "We hebben je aanvraag ontvangen. We bekijken de behoeften van je instelling en nemen binnen een week contact op.")
 (:institutions-success-back . "Terug naar start")

 ;; Footer
 (:footer-privacy . "Privacybeleid")
 (:footer-terms . "Servicevoorwaarden")

 ;; Early software notice
 (:early-software-notice . "Hiisi is in vroege ontwikkeling. Een bug gevonden of een suggestie?")

 ;; Privacybeleid
 (:privacy-title . "Privacybeleid")
 (:privacy-updated . "Laatst bijgewerkt: januari 2026")
 (:privacy-who-title . "Wie wij zijn")
 (:privacy-who-body . "Hiisi wordt beheerd door Lambda Symbolics OÜ, een bedrijf dat is geregistreerd in Estland. Als Ests bedrijf voldoen wij aan de Algemene Verordening Gegevensbescherming (AVG/GDPR) van de Europese Unie.")
 (:privacy-collect-title . "Gegevens die wij verzamelen")
 (:privacy-collect-intro . "Wanneer je Hiisi gebruikt, verzamelen wij de volgende informatie:")
 (:privacy-collect-account-key . "Accountgegevens: ")
 (:privacy-collect-account-val . "E-mailadres, weergavenaam en een veilig gehashte wachtwoordwaarde.")
 (:privacy-collect-learning-key . "Leerdata: ")
 (:privacy-collect-learning-val . "Je vertalingen, opgeslagen flashcards en repetitiegeschiedenis.")
 (:privacy-collect-usage-key . "Gebruiksgegevens: ")
 (:privacy-collect-usage-val . "Basisserverlogs voor beveiliging en foutopsporing.")
 (:privacy-use-title . "Hoe wij je gegevens gebruiken")
 (:privacy-use-auth-key . "Authenticatie: ")
 (:privacy-use-auth-val . "Om je identiteit te verifiëren en je account te beveiligen.")
 (:privacy-use-service-key . "Dienstverlening: ")
 (:privacy-use-service-val . "Om vertalingen te leveren en je flashcardverzameling te beheren.")
 (:privacy-use-ai-key . "AI-vertalingen: ")
 (:privacy-use-ai-val . "Je vertaalverzoeken worden naar OpenRouter gestuurd om antwoorden te genereren. OpenRouter kan verzoeken doorsturen naar de geconfigureerde modelprovider. Zie het privacybeleid van OpenRouter voor hoe deze gegevens worden verwerkt.")
 (:privacy-third-title . "Diensten van derden")
 (:privacy-third-intro . "Wij gebruiken de volgende diensten van derden:")
 (:privacy-third-openrouter-key . "OpenRouter: ")
 (:privacy-third-openrouter-val . "Voor automatische vertaalverzoeken.")
 (:privacy-third-clankermails-key . "ClankerMails: ")
 (:privacy-third-clankermails-val . "Voor het versturen van accountactivatie- en transactie-e-mails.")
 (:privacy-third-polar-key . "Polar.sh: ")
 (:privacy-third-polar-val . "Voor de verwerking van abonnementsbetalingen.")
 (:privacy-cookies-title . "Cookies")
 (:privacy-cookies-intro . "Wij gebruiken alleen essentiële cookies:")
 (:privacy-cookies-auth-key . "Authenticatietoken: ")
 (:privacy-cookies-auth-val . "Een veilige HTTP-only cookie om je ingelogd te houden.")
 (:privacy-cookies-lang-key . "Taalvoorkeur: ")
 (:privacy-cookies-lang-val . "Om je voorkeursinterface-taal te onthouden.")
 (:privacy-retention-title . "Bewaartermijn van gegevens")
 (:privacy-retention-body . "Je gegevens worden bewaard zolang je een account hebt. Wanneer je verwijdering aanvraagt, wordt je account gepland voor verwijdering over 14 dagen.")
 (:privacy-rights-title . "Jouw rechten (GDPR)")
 (:privacy-rights-intro . "Onder de GDPR heb je het recht om:")
 (:privacy-rights-access . "Toegang te krijgen tot je persoonsgegevens")
 (:privacy-rights-export . "Je gegevens te exporteren (beschikbaar op /app/api/export)")
 (:privacy-rights-correct . "Correctie van onjuiste gegevens aan te vragen")
 (:privacy-rights-delete . "Verwijdering van je account en gegevens aan te vragen")
 (:privacy-rights-object . "Bezwaar te maken tegen verwerking van je gegevens")
 (:privacy-rights-contact . "Om deze rechten uit te oefenen, neem contact met ons op via")
 (:privacy-contact-title . "Contact")
 (:privacy-contact-intro . "Voor privacygerelateerde vragen:")
 (:privacy-contact-email-label . "E-mail: ")
 (:privacy-address-1 . "Lambda Symbolics OÜ")
 (:privacy-address-2 . "Harju maakond, Tallinn, Kesklinna linnaosa, Tornimäe tn 5, 10145")

 ;; Gebruiksvoorwaarden
 (:terms-title . "Gebruiksvoorwaarden")
 (:terms-updated . "Laatst bijgewerkt: januari 2026")
 (:terms-1-title . "1. Beschrijving van de dienst")
 (:terms-1-body . "Hiisi is een app voor taalverwerving die automatische vertalingen met grammaticale uitleg en flashcards met gespreide herhaling biedt. De dienst wordt beheerd door Lambda Symbolics OÜ.")
 (:terms-2-title . "2. Accountregistratie")
 (:terms-2-body . "Om Hiisi te gebruiken moet je een account maken met een geldig e-mailadres. Je bent verantwoordelijk voor de beveiliging van je accountgegevens.")
 (:terms-3-title . "3. Abonnement en betalingen")
 (:terms-3-body . "Hiisi biedt betaalde abonnementen (maandelijks en jaarlijks). Abonnementen worden verwerkt via Polar.sh.")
 (:terms-3-list-1 . "Abonnementen worden automatisch verlengd tenzij ze vóór de verlengingsdatum worden opgezegd.")
 (:terms-3-list-2 . "Terugbetalingen worden verleend in overeenstemming met toepasselijke consumentenwetgeving.")
 (:terms-3-list-3 . "Niet-betaling leidt tot verlies van toegang tot premiumfuncties.")
 (:terms-4-title . "4. Toegestaan gebruik")
 (:terms-4-intro . "Je stemt ermee in om niet:")
 (:terms-4-list-1 . "De dienst te gebruiken voor illegale doeleinden")
 (:terms-4-list-2 . "Te proberen gebruikslimieten of beveiligingsmaatregelen te omzeilen")
 (:terms-4-list-3 . "Je accountgegevens met anderen te delen")
 (:terms-4-list-4 . "Geautomatiseerde tools te gebruiken op een manier die de prestaties voor anderen verslechtert")
 (:terms-5-title . "5. Inhoud en intellectueel eigendom")
 (:terms-5-body-1 . "Door Hiisi gegenereerde vertalingen worden automatisch gemaakt en zijn mogelijk niet uniek. Je mag je vertalingen en flashcards voor persoonlijke doeleinden gebruiken, maar je hebt geen exclusieve auteursrechten op automatisch gegenereerde inhoud.")
 (:terms-5-body-2 . "De Hiisi-applicatie, branding en oorspronkelijke inhoud blijven eigendom van Lambda Symbolics OÜ.")
 (:terms-6-title . "6. Beschikbaarheid van de dienst")
 (:terms-6-intro . "Hiisi wordt geleverd zoals die is. Wij garanderen niet:")
 (:terms-6-list-1 . "Ononderbroken of foutloze dienstverlening")
 (:terms-6-list-2 . "Nauwkeurigheid van automatisch gegenereerde vertalingen")
 (:terms-6-list-3 . "Beschikbaarheid van specifieke functies")
 (:terms-6-body . "Wij kunnen functies op elk moment wijzigen of beëindigen.")
 (:terms-7-title . "7. Beperking van aansprakelijkheid")
 (:terms-7-body-1 . "Voor zover wettelijk toegestaan is Lambda Symbolics OÜ niet aansprakelijk voor enige indirecte, incidentele, bijzondere of gevolgschade die voortvloeit uit je gebruik van Hiisi.")
 (:terms-7-body-2 . "Onze totale aansprakelijkheid is beperkt tot het bedrag dat je in de 12 maanden voorafgaand aan de claim voor de dienst hebt betaald.")
 (:terms-8-title . "8. Beëindiging van account")
 (:terms-8-body-1 . "Wij kunnen je account opschorten of beëindigen als je deze voorwaarden schendt. Je kunt op elk moment via de applicatie verwijdering van je account aanvragen.")
 (:terms-8-body-2 . "Na een verwijderverzoek wordt je account gepland voor verwijdering over 14 dagen.")
 (:terms-9-title . "9. Wijzigingen in de voorwaarden")
 (:terms-9-body . "Wij kunnen deze voorwaarden van tijd tot tijd bijwerken. Door Hiisi te blijven gebruiken na wijzigingen, accepteer je de nieuwe voorwaarden.")
 (:terms-10-title . "10. Toepasselijk recht")
 (:terms-10-body . "Op deze voorwaarden is het recht van Estland van toepassing. Eventuele geschillen worden beslecht door de rechtbanken van Estland.")
 (:terms-contact-title . "Contact")
 (:terms-contact-intro . "Voor vragen over deze voorwaarden:")
 (:terms-contact-email-label . "E-mail: ")
 (:terms-address-1 . "Lambda Symbolics OÜ")
 (:terms-address-2 . "Harju maakond, Tallinn, Kesklinna linnaosa, Tornimäe tn 5, 10145")

 ;; Decks
 (:decks-title . "Stapels")
 (:decks-subtitle . "Maak aangepaste stapels en deel ze met anderen.")
 (:decks-create-title . "Stapel maken")
 (:decks-name-placeholder . "Stapelnaam")
 (:decks-desc-placeholder . "Beschrijving")
 (:decks-create-btn . "Stapel maken")
 (:decks-edit-title . "Stapel bewerken")
 (:decks-edit-btn . "Stapel bewerken")
 (:decks-actions-title . "Stapelacties")
 (:decks-card-actions-title . "Kaartacties")
 (:decks-update-btn . "Wijzigingen opslaan")
 (:decks-default-badge . "Automatisch")
 (:decks-default-description . "Deze stapel wordt automatisch beheerd voor dit talenpaar.")
 (:decks-default-readonly . "Automatische stapels hebben vaste namen en beschrijvingen.")
 (:decks-delete-btn . "Stapel verwijderen")
 (:decks-delete-confirm . "Weet je zeker dat je deze stapel wilt verwijderen?")
 (:decks-error-name-required . "De naam van de stapel is verplicht.")
 (:decks-error-name-too-long . "De naam van de stapel mag maximaal ~A tekens bevatten.")
 (:decks-error-desc-too-long . "De beschrijving van de stapel mag maximaal ~A tekens bevatten.")
 (:decks-error-default-readonly . "Automatische stapels kunnen niet worden bewerkt.")
 (:decks-error-default-delete-forbidden . "Automatische stapels kunnen niet worden verwijderd.")
 (:decks-your-title . "Jouw stapels")
 (:decks-col-updated . "Bijgewerkt")
 (:decks-no-decks . "Nog geen stapels.")
 (:decks-open-btn . "Openen")
 (:decks-view-deck-btn . "Deck bekijken")
 (:decks-start-review . "Start herhaling")
 (:decks-no-desc . "Geen beschrijving.")
 (:decks-share-title . "Deellink")
 (:decks-share-info . "Iedereen met deze link kan de stapel importeren:")
 (:decks-share-copy . "Link kopiëren")
 (:decks-share-copied . "Gekopieerd")
 (:decks-add-from-flashcards-title . "Flashcards toevoegen")
 (:decks-add-from-flashcards-info . "Kies een kaart om de vertaling aan deze stapel toe te voegen.")
 (:decks-create-new-flashcard . "Nieuwe flashcard maken")
 (:decks-open-flashcards . "Bestaande flashcards toevoegen")
 (:decks-filter-from . "Brontaal")
 (:decks-filter-to . "Doeltaal")
 (:decks-filter-any . "Elke taal")
 (:decks-filter-include-assigned . "Neem kaartjes op die al in een stapel zitten")
 (:decks-flashcards-add . "Toevoegen")
 (:decks-flashcards-added . "Toegevoegd")
 (:decks-flashcards-in-deck . "In een andere stapel")
 (:decks-flashcards-empty . "Geen kaartjes komen overeen met deze filters.")
 (:decks-items-title . "Stapelinhoud")
 (:decks-col-original . "Origineel")
 (:decks-col-translated . "Vertaling")
 (:decks-col-lang . "Doeltaal")
 (:decks-no-items . "Nog geen items.")
 (:decks-share-page-title . "Stapel delen")
 (:decks-share-preview . "Voorbeeld en importeer deze stapel.")
 (:decks-import-title . "Importeren")
 (:decks-import-btn . "Stapel importeren")
 (:starter-decks-title . "Bibliotheek")
 (:starter-decks-subtitle . "Importeer kant-en-klare decks van Hiisi en de community.")
 (:starter-decks-marketplace-btn . "Bibliotheek")
 (:starter-decks-explanation-language . "Uitlegtaal")
 (:starter-decks-search-label . "Zoeken")
 (:starter-decks-source-label . "Bron")
 (:starter-decks-source-all . "Alle decks")
 (:starter-decks-change-language . "Wijzigen")
 (:starter-decks-filters-button . "Filters")
 (:starter-decks-search-placeholder . "Zoek in de bibliotheek")
 (:starter-decks-apply-filters . "Filters toepassen")
 (:starter-decks-select-triplet-hint . "Kies bron- en doeltaal om passende decks te bekijken.")
 (:starter-decks-official-badge . "Officieel")
 (:starter-decks-official-by-hiisi . "Officieel van Hiisi")
 (:starter-decks-community-badge . "Community")
 (:starter-decks-by-hiisi . "Van Hiisi")
 (:starter-decks-preview-btn . "Bekijken")
 (:starter-decks-card-count . "~A kaarten")
 (:starter-decks-no-results . "Geen decks komen overeen met deze filters.")
 (:starter-decks-source-cards-title . "Kaarten in deze set")
 (:starter-decks-more-cards-included . "+~A extra kaarten inbegrepen.")
 (:starter-decks-sample-title . "Voorbeeldkaarten")
 (:starter-decks-generating . "Je deck ~A wordt voorbereid")
 (:starter-decks-generating-detail . "We importeren het zodra het klaar is. Je kunt verder bladeren in de Bibliotheek of zo terugkomen.")
 (:starter-decks-generation-failed . "Genereren mislukt")
 (:starter-decks-generation-failed-detail . "De laatste genereerpoging is mislukt. Probeer het deck opnieuw te importeren.")
 (:starter-decks-login-detail . "Log in om dit deck in je verzameling te importeren.")
 (:starter-decks-subscribe-btn . "Bekijk plannen")
 (:starter-decks-subscribe-detail . "Bibliotheekdecks zijn beschikbaar met een actief abonnement of een proefperiode.")
 (:library-submit-title . "Indienen bij de bibliotheek")
 (:library-submit-intro . "Dien dit deck in bij de bibliotheek voor administratieve beoordeling vóór publicatie.")
 (:library-submit-btn . "Deck indienen")
 (:library-submit-approved . "Goedgekeurd voor de bibliotheek")
 (:library-submit-approved-detail . "Dit deck is gepubliceerd in de bibliotheek.")
 (:library-submit-pending . "In beoordeling")
 (:library-submit-pending-detail . "Dit deck is ingediend en wacht op administratieve beoordeling.")
 (:library-submit-rejected . "Heeft wijzigingen nodig vóór publicatie")
 (:library-submit-rejected-detail . "Deze inzending is afgewezen. Werk het deck bij en dien het opnieuw in.")
 (:library-error-empty . "Voeg minstens één kaart toe voordat je dit deck indient bij de bibliotheek.")
 (:library-error-missing-triplet . "Elke kaart in een bibliotheekinzending moet een volledig taaltriplet hebben.")
 (:library-error-mixed-triplet . "Alle kaarten in een bibliotheekinzending moeten hetzelfde taaltriplet delen.")
 (:starter-deck-topic-greetings-title . "Begroetingen en kennismaking")
 (:starter-deck-topic-greetings-description . "Begroetingen, namen, beleefde basiszinnen en uitdrukkingen voor een eerste ontmoeting.")
 (:starter-deck-topic-travel-title . "Essentieel reizen")
 (:starter-deck-topic-travel-description . "Stations, tickets, prijzen, hulp vragen en je verplaatsen.")
 (:starter-deck-topic-numbers-title . "Getallen en prijzen")
 (:starter-deck-topic-numbers-description . "Tellen, totalen, prijzen, verdiepingen en alledaagse hoeveelheden.")
 (:starter-deck-topic-time-title . "Tijd en data")
 (:starter-deck-topic-time-description . "Dagen, maanden, afspraken, kloktijden en relatieve datums.")
 (:starter-deck-topic-food-title . "Restaurant en eten")
 (:starter-deck-topic-food-description . "Bestellen, dieetwensen, drankjes, de rekening en alledaagse maaltijden buitenshuis.")
 (:starter-deck-topic-emergency-title . "Noodsituaties en gezondheid")
 (:starter-deck-topic-emergency-description . "Artsen, apotheken, symptomen, lichaamsdelen en dringende hulp.")
 (:starter-deck-topic-directions-title . "Routebeschrijvingen en vervoer")
 (:starter-deck-topic-directions-description . "Afslaan, haltes, tickets, perrons en je verplaatsen in de stad.")
 (:starter-deck-topic-school-title . "School en onderwijs")
 (:starter-deck-topic-school-description . "Lessen, huiswerk, examens, schoolspullen en het dagelijks leven op school.")
 (:starter-deck-topic-university-title . "Universiteit en studie")
 (:starter-deck-topic-university-description . "Colleges, seminars, studierichtingen, opdrachten en het dagelijks leven op de campus.")

 ;; Flashcards management page
 (:flashcards-title . "Mijn kaarten")
 (:flashcards-subtitle . "Al je opgeslagen kaarten op één plek. Zoek, organiseer en beheer.")
 (:flashcards-search-placeholder . "Kaarten zoeken...")
 (:flashcards-filter-button . "Filters")
 (:flashcards-filter-title . "Kaarten filteren")
 (:flashcards-filter-recollection . "Hoe goed je ze kent")
 (:flashcards-filter-any-recollection . "Elk niveau")
 (:flashcards-hide-perfected . "Beheerste kaartjes verbergen")
 (:flashcards-col-original . "Origineel")
 (:flashcards-col-translated . "Vertaling")
 (:flashcards-no-cards . "Nog geen kaarten. Begin met vertalen om er een paar te maken!")
 (:flashcards-no-filtered-cards . "Nog geen kaarten komen overeen met deze filters. Begin met vertalen om er een paar te maken!")
 (:flashcards-image-label . "Afbeelding")
 (:flashcards-image-upload . "Afbeelding uploaden")
 (:flashcards-image-replace . "Afbeelding vervangen")
 (:flashcards-image-remove . "Afbeelding verwijderen")
 (:flashcards-pagination-label . "Flashcardpagina's")
 (:flashcards-pagination-status . "Pagina ~A van ~A")
 (:flashcards-pagination-previous . "Vorige")
 (:flashcards-pagination-next . "Volgende")

 ;; Landing page (redesign)
 (:landing-hero-headline-v1 . "Vertaal zinnen eenvoudig en lees de grammatica in je eigen taal.")
 (:landing-hero-headline-v2 . "Hiisi zorgt ervoor dat je niet elke zin vergeet die je vertaalt.")
 (:landing-hero-headline-v3 . "Maak van de zinnen die je vertaalt woordenschat die je kunt gebruiken.")
 (:landing-hero-subheadline . "Maak van een willekeurige zin een bladwijzer en Hiisi geeft je de vertaling, de grammatica, de uitspraak en een flashcard die terugkomt om te herhalen.")
 (:trial-cardless-note . "14 dagen gratis. Geen kaart nodig.")

 ;; Trial status (in-app)
 (:trial-status . "Gratis proefperiode")
 (:error-trial-quota-exceeded . "Proefvertalingslimiet bereikt")
 (:error-trial-quota-detail . "Je hebt alle 200 proefvertalingen gebruikt. Abonneer om door te leren.")

 ;; Custom flashcards
 (:custom-flashcard-create-title . "Flashcard aanmaken")
 (:custom-flashcard-edit-title . "Flashcard bewerken")
 (:custom-flashcard-original . "Originele tekst")
 (:custom-flashcard-translated . "Vertaling")
 (:custom-flashcard-lang-from . "Brontaal")
 (:custom-flashcard-lang-to . "Doeltaal")
 (:custom-flashcard-note . "Educatieve notitie")
 (:custom-flashcard-forms . "Grammaticale analyse")
 (:custom-flashcard-form-term . "Term")
 (:custom-flashcard-form-explanation . "Uitleg")
 (:custom-flashcard-add-form . "Grammaticale term toevoegen")
 (:custom-flashcard-remove-form . "Verwijderen")
 (:custom-flashcard-ai-fill . "Invullen met AI")
 (:custom-flashcard-create-btn . "Flashcard aanmaken")
 (:custom-flashcard-update-btn . "Wijzigingen opslaan")

  ;; Newsletter
  (:newsletter-email-label . "E-mailadres")
  (:newsletter-developer-label . "Ik ben ontwikkelaar")
  (:newsletter-developer-hint . "ontvang technische updates")
  (:landing-newsletter-title . "Ontvang Hiisi-updates.")
  (:landing-newsletter-body . "Meld je aan voor de nieuwsbrief voor productupdates, ondersteuning voor nieuwe talen, starterdecks en af en toe aanbiedingen voor oprichtersleden.")
  (:landing-newsletter-fine-print . "Geen spam. Alleen productupdates.")
  (:landing-newsletter-button . "Meld je aan voor de nieuwsbrief")
  (:newsletter-unsubscribe-page-title . "Afmelden voor de Hiisi-nieuwsbrief")
  (:newsletter-unsubscribe-title . "Afmelden")
  (:newsletter-unsubscribe-subtitle . "Vul je e-mailadres in om geen Hiisi-updates meer te ontvangen.")
  (:newsletter-unsubscribe-button . "Afmelden")
  (:newsletter-feedback-email-required . "Vul je e-mailadres in.")
  (:newsletter-feedback-email-invalid . "Vul een geldig e-mailadres in.")
  (:newsletter-feedback-already-signed-up . "Je bent al aangemeld. We houden je op de hoogte!")
  (:newsletter-feedback-signed-up . "Je staat op de lijst! We sturen af en toe Hiisi-updates.")
  (:newsletter-feedback-unsubscribed . "Als dit e-mailadres was aangemeld, is het verwijderd uit Hiisi-updates.")
  (:newsletter-feedback-generic-error . "Er is iets misgegaan. Probeer het opnieuw.")

  ;; Issue reporting
  (:issues-open-button . "Bug melden")
 (:issues-modal-title . "Probleem melden")
 (:issues-modal-subtitle . "Beschrijf wat er misging. We voegen je huidige pagina automatisch toe.")
 (:issues-title-label . "Korte titel")
 (:issues-title-placeholder . "Korte samenvatting van het probleem")
 (:issues-message-label . "Wat is er gebeurd?")
 (:issues-message-placeholder . "Vermeld stappen om te reproduceren, verwacht gedrag en wat er in plaats daarvan gebeurde.")
 (:issues-submit . "Melding verzenden")
 (:issues-cancel . "Annuleren")
 (:issues-success . "Je melding is verzonden. We bekijken die zo snel mogelijk.")
 (:issues-error-required . "Beschrijf het probleem voordat je verzendt.")
 (:issues-error-title-too-long . "De titel van de melding is te lang. Houd deze onder 160 tekens.")
 (:issues-error-too-long . "De melding is te lang. Houd het onder 4000 tekens.")
 (:issues-error-rate-limit . "Te veel meldingen vanaf deze bron. Wacht even en probeer later opnieuw.")
 (:issues-error-generic . "De probleemmelding kon niet worden verzonden. Probeer het opnieuw.")

 ;; Landing page (Programmable Paper)
 (:landing-signal-languages . "Vijftien talen")
 (:landing-signal-flashcards . "Slimme flashcards")
 (:landing-signal-pronunciation . "Uitspraak die je kunt lezen")
 (:landing-problem-title . "De zin die je vorige week vertaalde. Kun je hem nu zeggen?")
 (:landing-problem-body . "Dat moment komt vaak voor. Je ziet een uitdrukking, plakt die in een vertaler, en de betekenis is meteen duidelijk, daar in je hand. Er gaat een week voorbij; de bewoording is uit je geheugen verdwenen en de betekenis erbij. Eén zin leren vraagt gewoonlijk vier aparte hulpmiddelen:")
 (:landing-tool-translator . "Een vertaler voor de betekenis")
 (:landing-tool-grammar . "Een grammaticanaslagwerk voor de structuur")
 (:landing-tool-pronunciation . "Een uitspraakgids voor de klank")
 (:landing-tool-flashcards . "Een flashcard-app om te onthouden")
 (:landing-problem-outro . "Alle vier gebruiken kost tijd, en de volgende zin is al weg voordat de kaart af is.")
 (:landing-bookmark-title . "Wat er gebeurt als je een zin bewaart")
 (:landing-bookmark-intro . "Eén tik, en Hiisi maakt van de zin binnen seconden een gestructureerd leerobject. Hij blijft in je bibliotheek, met alles erbij:")
 (:landing-bookmark-item-translation . "De oorspronkelijke zin en een heldere vertaling")
 (:landing-bookmark-item-pronunciation . "De uitspraak uitgeschreven, zoals woordenboeken dat doen")
 (:landing-bookmark-item-grammar . "Grammatica uitgelegd in de taal die jij het liefst leest")
 (:landing-bookmark-item-colors . "Kleurgekoppelde woorden laten zien welk deel bij welk hoort")
 (:landing-bookmark-item-flashcard . "Een flashcard die terugkomt wanneer je geheugen hem nodig heeft")
 (:landing-bookmark-cta . "Bewaar je eerste zin")
 (:landing-sources-title . "Eén zin is genoeg om te beginnen")
 (:landing-sources-intro . "Alles wat je in een nieuwe taal leest of hoort, werkt met Hiisi:")
 (:landing-source-lyrics . "De tekst van een liedje dat je blijft afspelen")
 (:landing-source-articles . "Artikelen in de taal die je leert")
 (:landing-source-messages . "Berichten van moedertaalvrienden")
 (:landing-source-films . "Zinnen uit films of podcasts die je bewaart")
 (:landing-source-page . "De pagina die je nu aan het lezen bent")
 (:landing-features-title . "Gemaakt voor zelfstudenten en studenten")
 (:landing-feature-grammar-title . "Grammatica in de taal waarin je denkt")
 (:landing-feature-grammar-body . "Lees Franse grammatica in het Nederlands, of Spaanse grammatica in het Pools. Je aandacht blijft bij de zin die je leert.")
 (:landing-feature-colors-title . "Woorden gekoppeld op kleur")
 (:landing-feature-colors-body . "Een woord en zijn vertaling delen dezelfde kleur, zodat je de betekenis van elk woord in één oogopslag ziet.")
 (:landing-feature-pronunciation-title . "Uitspraak die je kunt lezen")
 (:landing-feature-pronunciation-body . "Elke zin komt met een uitgeschreven uitspraakgids, dezelfde soort die woordenboeken gebruiken. Je ziet hoe hij klinkt voordat je hem zegt.")
 (:landing-feature-flashcards-title . "Flashcards die zichzelf inplannen")
 (:landing-feature-flashcards-body . "Elke bewaarde zin wordt een kaart. Het SM-2-algoritme achter Anki bepaalt wanneer hij terugkomt, zodat je herhaalt wat je bijna vergeten was.")
 (:landing-feature-decks-title . "Themadecks voor wat eraan komt")
 (:landing-feature-decks-body . "Volgende maand op reis? Nieuwe baan? Importeer een kant-en-klaar deck en herhaal vanaf dag één.")
 (:landing-feature-directions-title . "Vijftien talen, elke richting")
 (:landing-feature-directions-body . "Vertaal Spaans naar Frans, of Engels naar Duits. Hiisi kan elke richting binnen de hele set aan.")
 (:landing-flow-title . "Hoe leren in Hiisi eruitziet")
 (:landing-flow-body . "Open Hiisi. De kaarten van vandaag liggen klaar, elk een zin die jij bewaarde, met vertaling en grammatica erbij. Zie je een nieuwe zin die je wilt houden? Bewaar hem, en morgen zit hij in de herhaalstapel.")
 (:landing-who-title . "Voor wie Hiisi is")
 (:landing-who-intro . "Wel eens een bruikbare zin kwijtgeraakt? Hiisi is voor jou gebouwd.")
 (:landing-who-beginners . "Beginners die hun eerste zinnen in een nieuwe taal opbouwen")
 (:landing-who-intermediate . "Gevorderden die vlot lezen maar struikelen over grammatica")
 (:landing-who-native . "Sprekers van huis uit die de taal van thuis weer oppakken")
 (:landing-who-travellers . "Reizigers en partners van moedertaalsprekers die zinnen willen die ze kunnen gebruiken")
 (:landing-final-title . "Begin vandaag met Hiisi")
 (:landing-final-body . "Hiisi geeft je de betekenis, de grammatica, de uitspraak en een flashcard die jou weer opzoekt. Vanaf dat moment is de zin van jou.")
 (:landing-final-languages . "Vijftien talen staan klaar wanneer jij dat bent.")
 (:modal-close . "Sluiten")
)
