;;; Norwegian translations (Bokmål)
;;; This file must contain all keys from en.lisp

(
 ;; Language metadata (used for language picker)
 (:lang-name . "Norsk")
 (:lang-flag . "🇳🇴")

 ;; Language modal (first-visit language selection)
 (:lang-modal-title . "Velg språk")
 (:lang-modal-subtitle . "Velg foretrukket språk for grensesnittet:")

 ;; Navigation
 (:nav-translate . "Oversett")
 (:nav-review . "Repeter")
 (:nav-flashcards . "Mine kort")
 (:nav-dashboard . "Oversikt")
 (:nav-decks . "Kortstokker")
 (:nav-logout . "Logg ut")
 (:nav-home . "Hjem")
 (:nav-pricing . "Priser")
 (:nav-institutions . "For institusjoner")
 (:nav-export-data . "Eksporter data")
 (:nav-open-navigation . "Åpne navigasjonen")
 (:theme-light . "Lys")
 (:theme-dark . "Mørk")

 ;; App title and branding
 (:app-title . "Hiisi - Språklæring")

 ;; Landing page
 (:landing-meta-title . "Hiisi: språklæringsapp med grammatikk og flashcards")
 (:landing-meta-description . "Hiisi er en språklæringsapp. Hver setning du oversetter, blir et flashcard med innebygd grammatikk, planlagt med SM-2, Anki-algoritmen. 15 språk.")
 (:landing-learn-more . "Lær mer")
 (:landing-how-it-works . "Slik fungerer det")
 (:landing-start-trial . "Kom i gang med Hiisi")
 (:landing-best-value . "Best verdi")

 ;; Auth pages
 (:auth-register . "Registrer")
 (:auth-login . "Logg inn")
 (:auth-email . "E-post")
 (:auth-password . "Passord")
 (:auth-password-again . "Bekreft passord")
 (:auth-display-name . "Visningsnavn")
 (:auth-register-title . "Registrer deg på Hiisi")
 (:auth-register-subtitle . "Opprett en ny konto")
 (:auth-login-title . "Logg inn på Hiisi")
 (:auth-login-subtitle . "Skriv inn opplysningene dine")
 (:auth-login-invalid-credentials . "Ugyldig e-post eller passord.")
 (:auth-login-rate-limited . "For mange innloggingsforsok. Vent noen minutter og prov igjen.")
(:auth-register-rate-limited . "For mange registreringsforsøk. Vent noen minutter og prøv igjen.")
(:auth-email-invalid . "Skriv inn en gyldig e-postadresse.")
(:auth-password-too-short . "Passordet må være minst 8 tegn langt.")
(:auth-passwords-mismatch . "Passordene stemmer ikke overens.")
(:auth-display-name-invalid . "Visningsnavnet må være mellom 1 og 100 tegn langt.")
(:auth-register-email-exists . "Det finnes allerede en konto med denne e-postadressen.")
(:auth-register-unavailable . "Registrering er midlertidig utilgjengelig. Prøv igjen senere.")
(:auth-register-plan-required . "Velg et abonnement før du oppretter en konto.")
(:auth-preapproved-email-unrecognized . "Bruk e-postadressen fra invitasjonen din, eller velg et abonnement før du oppretter en konto.")
(:auth-institution-register . "Kommer du fra en institusjon?")
(:auth-institution-stage-title . "Institusjonstilgang")
(:auth-institution-stage-subtitle . "Bruk e-postadressen fra skolen eller universitetet ditt. Kvalifiserte kontoer låses opp gjennom institusjonen etter e-postbekreftelse.")
(:auth-institution-title . "Registrer deg gjennom institusjonen din")
(:auth-institution-subtitle . "Bruk e-postadressen fra skolen eller universitetet ditt. Hvis institusjonen allerede er satt opp i Hiisi, låses kontoen opp gjennom den etter e-postbekreftelse; den individuelle prøveperioden på 14 dager gjelder registrering med personlig abonnement.")
(:auth-institution-benefit-email . "Bruk e-postadressen fra skolen eller universitetet ditt.")
(:auth-institution-benefit-access . "Kvalifiserte kontoer får institusjonstilgang etter e-postbekreftelse.")
(:auth-institution-benefit-fallback . "Hvis domenet ikke gjenkjennes, velg et individuelt abonnement eller be institusjonen din kontakte Hiisi.")
(:auth-see-included . "Se hva som er inkludert")
(:auth-institution-check-access . "Sjekk tilgang")
(:auth-institution-email-eligible-title . "Institusjonstilgang bekreftet")
(:auth-institution-email-eligible-detail . "Fortsett med denne e-postadressen for å opprette kontoen. Tilgangen låses opp etter e-postbekreftelse.")
(:auth-institution-change-email . "Bruk en annen e-postadresse")
(:auth-institution-outcome-note . "Hvis skolen eller universitetet ditt gir tilgang til Hiisi, låses kontoen opp etter e-postbekreftelse. Hvis domenet ikke er kvalifisert, velg et personlig abonnement for å starte prøveperioden på 14 dager.")
(:auth-institution-personal-plan-link . "Se personlige abonnementer")
(:auth-institution-domain-unrecognized . "Vi kjenner ikke igjen dette institusjonelle e-postdomenet ennå. Velg et personlig abonnement for å starte prøveperioden på 14 dager, eller be institusjonen din kontakte Hiisi.")
(:subscribe-institution-callout-title . "Bruker du Hiisi gjennom en skole eller et universitet?")
(:subscribe-institution-callout-body . "Registrer deg med institusjons-e-posten din, så låser Hiisi opp tilgang automatisk hvis institusjonen din allerede er satt opp.")
(:auth-activation-email-send-failed . "Kunne ikke sende aktiverings-e-post. Prøv igjen.")
 (:auth-forgot-password . "Glemt passord?")
 (:auth-no-account . "Har du ikke konto?")
 (:auth-have-account . "Har du allerede en konto?")
 (:auth-google . "Google")
 (:auth-google-login-failed . "Innlogging med Google mislyktes. Prøv igjen.")
 (:auth-account-created . "Konto opprettet!")
 (:auth-check-email . "Sjekk e-posten din for aktiveringslenken.")
 (:auth-redirect-login . "Omdirigerer til innlogging om")
 (:auth-seconds . "sekunder...")
 (:auth-go-now . "Gå nå")
 (:auth-not-activated . "Konto ikke aktivert")
 (:auth-activate-title . "Aktiver kontoen din!")
 (:auth-activated . "Konto aktivert!")
 (:auth-activated-message . "Kontoen din er aktivert. Du kan nå bruke Hiisi.")
 (:auth-redirecting . "Omdirigerer om")
 (:auth-go-to-app . "Gå til appen")
 (:onboarding-title . "Hvordan Hiisi fungerer")
 (:onboarding-subtitle . "Oversett ekte tekst, se på grammatikken, lagre nyttige elementer og repeter dem senere.")
 (:onboarding-translate-detail . "Begynn med ekte tekst. Hiisi viser oversettelsen, de tilordnede formene og de neste studiehandlingene på ett sted.")
 (:onboarding-grammar-detail . "Åpne grammatikkgjennomgangen for å se hvilke former som svarer til hverandre i setningen og hvilken rolle hver del har.")
 (:onboarding-review-detail . "Lagre nyttige oversettelser og repeter dem senere med spredt repetisjon, slik at de blir værende i langtidsminnet.")
 (:onboarding-decks-detail . "Samle nyttige elementer i kortstokker, del dem med andre og hold sammen materiale som hører sammen.")
 (:onboarding-back . "Tilbake")
 (:onboarding-next . "Neste")
 (:onboarding-skip . "Hopp over guide")
 (:auth-resend-title . "Send aktiveringsmail på nytt")
 (:auth-resend-subtitle . "Skriv inn e-posten din for å motta en ny aktiveringslenke.")
 (:auth-resend-button . "Send aktiveringsmail på nytt")
 (:auth-resend-success . "Aktiveringsmail sendt!")
 (:auth-resend-success-detail . "Sjekk innboksen din for den nye aktiveringslenken.")
 (:auth-resend-rate-limited . "Vennligst vent noen minutter før du ber om en ny aktiveringsmail.")
 (:auth-resend-cooldown . "Du kan be om en ny mail om ~a sekunder.")
 (:auth-back-to-login . "Tilbake til innlogging")
 (:auth-forgot-password-title . "Glemt passord")
 (:auth-forgot-password-subtitle . "Skriv inn e-posten din, så sender vi deg en lenke for å tilbakestille passordet.")
 (:auth-send-reset-link . "Send tilbakestillingslenke")
 (:auth-reset-email-sent . "Lenke sendt!")
 (:auth-reset-email-sent-detail . "Hvis det finnes en konto med den e-posten, vil du snart motta en lenke for å tilbakestille passordet.")
 (:auth-reset-rate-limited . "Vennligst vent noen minutter før du ber om en ny tilbakestilling av passord.")
 (:auth-reset-invalid-token . "Denne tilbakestillingslenken er ugyldig eller utløpt.")
 (:auth-reset-password-title . "Tilbakestill passord")
 (:auth-reset-password-subtitle . "Skriv inn ditt nye passord nedenfor.")
 (:auth-new-password . "Nytt passord")
 (:auth-confirm-new-password . "Bekreft nytt passord")
 (:auth-reset-password . "Tilbakestill passord")
 (:auth-password-changed . "Passord endret!")
 (:auth-password-changed-detail . "Passordet ditt er endret. Du kan nå logge inn med ditt nye passord.")
 (:auth-change-password-title . "Endre passord")
 (:auth-change-password-subtitle . "Oppdater kontoens passord.")
 (:auth-current-password . "Nåværende passord")
 (:auth-change-password . "Endre passord")
 (:auth-back-to-app . "Tilbake til appen")
 (:auth-password-updated . "Passord oppdatert!")
 (:auth-password-updated-detail . "Passordet ditt er oppdatert.")
(:auth-current-password-invalid . "Nåværende passord er feil.")
(:auth-new-password-same . "Det nye passordet må være forskjellig fra det nåværende passordet.")

 ;; Email copy
 (:email-common-hi . "Hei")
 (:email-common-tagline . "Hiisi - Lær gjennom oversettelse")
 (:email-activation-subject . "Aktiver Hiisi-kontoen din")
 (:email-activation-title . "Velkommen til Hiisi")
 (:email-activation-body . "Takk for at du registrerte deg. Aktiver kontoen din ved å klikke på lenken nedenfor:")
 (:email-activation-button . "Aktiver konto")
 (:email-activation-copy-link . "Eller kopier denne lenken")
 (:email-activation-expiry . "Denne lenken utløper om 24 timer.")
 (:email-reset-subject . "Tilbakestill Hiisi-passordet ditt")
 (:email-reset-title . "Forespørsel om tilbakestilling av passord")
 (:email-reset-body . "Vi har mottatt en forespørsel om å tilbakestille passordet ditt. Klikk på lenken nedenfor for å angi et nytt passord:")
 (:email-reset-button . "Tilbakestill passord")
 (:email-reset-expiry . "Denne lenken utløper om 1 time.")
 (:email-reset-ignore . "Hvis du ikke ba om å tilbakestille passordet, kan du ignorere denne e-posten.")
 (:email-reminder-subject-due . "På tide å repetere Hiisi-kortene dine")
 (:email-reminder-subject-streak . "Hold Hiisi-streaken din i gang")
 (:email-reminder-cards-due . "kort klare for repetisjon")
 (:email-reminder-keep-going . "Det er noen dager siden din siste repetisjon. Fem minutter i dag er nok til å hindre at det du allerede har lært glir bort.")
 (:email-reminder-button . "Repeter nå")
 (:email-reminder-settings . "Administrer påminnelser")
 (:email-reminder-preview-title . "Kort som venter på deg")
 (:email-reminder-translation-label . "Oversettelse")
 (:email-reminder-more-due-today . "flere kort å repetere i dag")
 (:email-trial-subject . "Hvordan går Hiisi-prøveperioden din?")
 (:email-trial-expiring . "Den gratis Hiisi-prøveperioden din slutter i morgen.")
 (:email-trial-feedback . "Liker du Hiisi? Fortell oss hva som hjelper deg mest.")
 (:email-trial-strengths . "Du kan oversette ekte tekster, lagre de beste elementene som flashcards og lære med repetisjon over tid.")
 (:email-trial-reply . "Svar på denne e-posten, så går meldingen din direkte til Hiisi-teamet.")
 (:email-trial-button . "Velg et abonnement")
 (:email-trial-manage . "Administrer abonnement")
 (:email-trial-contact . "Skriv til oss")
 (:email-plan-nudge-subject . "Oversettelsene dine venter")
 (:email-plan-nudge-title . "Oversettelsene dine venter")
 (:email-plan-nudge-intro . "Du har registrert deg i Hiisi, men har ikke valgt noe abonnement ennå.")
 (:email-plan-nudge-benefits-intro . "Dette får du med et abonnement:")
 (:email-plan-nudge-benefit-translations . "600 oversettelser per måned med grammatikkforklaringer")
 (:email-plan-nudge-benefit-flashcards . "Ubegrensede flashcards med repetisjon over tid")
 (:email-plan-nudge-benefit-decks . "Egne kortstokker du kan organisere og dele")
 (:email-plan-nudge-pricing . "Abonnementene starter på 10 EUR per måned, eller spar med årsabonnementet til 100 EUR per år (to måneder gratis).")
 (:email-plan-nudge-feedback . "Hvis det er noe med Hiisi som ikke fungerer for deg, svar på denne e-posten. Meldingen din går rett til Hiisi-teamet.")
 (:email-plan-nudge-button . "Velg et abonnement")
 (:email-plan-nudge-unsubscribe . "Stopp disse e-postene")
 (:email-plan-nudge-unsubscribe-done-title . "E-poster om abonnement er slått av")
 (:email-plan-nudge-unsubscribe-done-body . "Du vil ikke få flere påminnelser på e-post om å velge abonnement.")
 (:email-plan-nudge-unsubscribe-invalid-title . "Denne lenken er ikke gyldig")
 (:email-plan-nudge-unsubscribe-invalid-body . "Denne avmeldingslenken mangler, er utløpt eller er ikke lenger gyldig.")
 (:email-invite-subject . "Du har blitt invitert til Hiisi")
 (:email-invite-title . "Du har blitt invitert til Hiisi")
 (:email-invite-intro . "Du har blitt invitert til å bruke Hiisi gratis som tester, verdsatt venn eller begge deler.")
 (:email-invite-details . "Bruk knappen nedenfor for å opprette kontoen din og begynne å utforske oversettelser og flashcards.")
 (:email-invite-button . "Opprett konto")
 (:email-invite-issue-reporting . "Hvis noe går i stykker eller føles feil, finnes det en knapp for å rapportere et problem nederst på hver side.")
 (:email-issue-completed-subject . "Problemet du rapporterte i Hiisi er rettet")
 (:email-issue-completed-title . "Problemet er rettet")
 (:email-issue-completed-label . "Problem")
 (:email-issue-completed-followup . "Åpne Hiisi for å kontrollere rettelsen eller fortsette der du slapp.")
 (:email-issue-completed-button . "Åpne Hiisi")
 (:email-issue-completed-open-link . "Åpne side")

 ;; Translation page
 (:translate-title . "Oversett")
 (:landing-public-translate-title . "Prøv det her")
 (:landing-public-translate-cta-title . "Fortsett flyten")
 (:landing-public-translate-cta-body . "Lagre oversettelser som studiekort og repeter dem senere.")
 (:landing-public-translate-cta-button . "Start gratis prøveperiode og lær videre")
 (:translate-input-label . "Tekst å oversette")
 (:translate-input-placeholder . "Skriv inn tekst å oversette...")
 (:translate-from . "Kildespråk:")
 (:translate-to . "Målspråk:")
 (:translate-select-target-placeholder . "Velg målspråk")
 (:translate-submit . "Oversett")
 (:translate-auto-detect . "Alle (Automatisk gjenkjenning)")
 (:translate-empty-state . "Oversett et ord eller en frase, så ser du resultatet, grammatikkgjennomgangen og studiehandlingene her.")
 (:translate-select-deck-placeholder . "Velg kortstokk (valgfritt)")
 (:translate-new-deck . "Ny kortstokk")
 (:translate-add-to-deck . "Legg til i kortstokk")
 (:translate-bookmark . "Lagre")
 (:translate-bookmarked . "Lagret")
 (:translate-retry . "Generer igjen")
 (:translate-like-tooltip . "God oversettelse")
 (:translate-dislike-tooltip . "Dårlig oversettelse - be om en ny")
 (:translate-dislike-confirm . "Dette genererer en ny oversettelse. Fortsette?")
 (:pronunciation-label . "Uttale")
 (:pronunciation-show . "Vis uttale")
 (:pronunciation-hide . "Skjul uttale")
 (:grammar-term-examples . "Eksempler")
 (:grammar-term-related . "Relaterte termer")
 (:grammar-term-modal-title . "Grammatikkterm")
 (:grammar-term-empty . "Velg et uthevet begrep for å se detaljer.")
 (:extension-login-required . "Logg inn på Hiisi før du bruker nettleserutvidelsen.")
 (:extension-session-invalid . "Hiisi-økten din er ikke lenger gyldig. Logg inn på nytt.")
 (:extension-activation-required . "Aktiver Hiisi-kontoen din før du bruker nettleserutvidelsen.")
 (:extension-subscription-required . "Start en Hiisi-prøveperiode før du bruker nettleserutvidelsen.")

 ;; Translation and Flashcards
 (:lang-auto . "Auto")
 (:lang-unknown . "?")
 (:lang-target . "Mål")
 (:translate-deck-create-title . "Lag ny kortstokk")
 (:translate-deck-name-label . "Navn på kortstokk")
 (:translate-deck-name-placeholder . "f.eks. Finsk grunnlag")
 (:translate-deck-description-label . "Beskrivelse (valgfritt)")
 (:translate-deck-cancel . "Avbryt")
 (:translate-deck-create . "Lag")
 (:translate-rate-label . "Vurder oversettelse")
 (:flashcards-delete . "Slett")
 (:flashcards-delete-confirm . "Er du sikker på at du vil slette dette kortet?")
 (:flashcards-deck-search-placeholder . "Søk i kortstokker...")
 (:flashcards-no-decks . "Ingen kortstokker ennå. Lag en først!")
 (:flashcards-deck-cancel . "Avbryt")
 (:flashcards-recollection-tooltip . "Hukommelse: ~A")
 (:flashcards-recollection-poor . "Svak")
 (:flashcards-recollection-fair . "Grei")
 (:flashcards-recollection-normal . "Normal")
 (:flashcards-recollection-strong . "Sterk")
 (:flashcards-recollection-very-strong . "Veldig sterk")

 ;; Flashcard review
 (:review-title . "Repeter")
 (:review-session-title . "Repetisjonsøkt")
 (:review-session-subtitle . "Øv på dine lagrede flashcards")
 (:review-selector-title . "Velg hva du vil repetere")
 (:review-selector-subtitle . "Velg en kortstokk eller et språkpar for å fokusere repetisjonsøkten.")
 (:review-by-deck . "Repeter etter kortstokk")
 (:review-by-language-pair . "Repeter etter språkpar")
 (:review-all-cards . "Repeter alle kort")
 (:review-cards-due . "kort å repetere")
 (:review-deck-caught-up . "Alt repetert")
 (:review-all-caught-up . "Alt repetert!")

 (:review-no-cards . "Ingen kort å repetere")
 (:review-no-cards-desc . "Du har ingen flashcards som skal repeteres akkurat nå.")
 (:review-no-cards-hint . "Oversett noe tekst og klikk \"Lagre som flashcard\" for å bygge kortstokken din!")
 (:review-start-translating . "Begynn å oversette")
 (:review-click-reveal . "Klikk for å vise svar")
 (:review-grammar-breakdown . "Grammatisk forklaring")
 (:review-how-well . "Husket du det?")
 (:review-again . "Nei")
 (:review-hard . "Knapt")
 (:review-good . "Ja")
 (:review-easy . "Lett")
 (:review-progress . "Kort ~a av ~a")
 (:review-correct-count . "Riktig")
 (:review-wrong-count . "Feil")
 (:landing-mockup-forgot-detail . "1. person entall preteritum av \"olvidar\" (å glemme)")
 (:landing-mockup-keys-detail . "Eiendomsord \"mis\" med feminint flertallssubstantiv \"llaves\" (nøkler)")
 (:landing-mockup-home-detail . "Idiomatisk \"en casa\" (hjemme) -- ingen artikkel nødvendig")
 (:landing-mockup-possession-note . "På spansk markerer preteritum fullførte handlinger i fortiden. Subjektspronomenet utelates vanligvis fordi verbendelsen allerede viser hvem som snakker.")
 (:landing-mockup-children-detail . "Nominativ flertall av \"Kind\" (barn) -- flertall legger til -er")
 (:landing-mockup-played-detail . "3. person flertall preteritum av \"spielen\" (å leke)")
 (:landing-mockup-garden-detail . "Dativ: \"in dem\" trekkes sammen til \"im\", med maskulint substantiv \"Garten\" (hage)")
 (:landing-mockup-czech-note . "Tysk bruker preteritum i skriftlig fortelling. \"Im\" er en sammentrekning av \"in\" + \"dem\" (dativartikkel).")
 (:landing-mockup-deck-title . "Italiensk grunnleggende")
 (:landing-mockup-share-deck . "Del kortstokk")
 (:review-complete . "Økt fullført!")
 (:review-complete-msg . "Du repeterte ~a kort")
 (:review-again-btn . "Repeter igjen")
 (:review-translate-more . "Oversett mer")
 (:review-streak . "dager på rad")

 ;; Dashboard
 (:dashboard-title . "Oversikt")
 (:dashboard-welcome-title . "Oversett din første tekst")
 (:dashboard-welcome-subtitle . "Oversett en nyttig frase, lagre den i en kortstokk og repeter den når det gjelder.")
 (:dashboard-take-quick-tour . "Ta en rask omvisning")
 (:dashboard-cards-due . "Kort for i dag")
 (:dashboard-total-cards . "Totalt antall kort")
 (:dashboard-mastered-cards . "Mestrede kort")
 (:dashboard-subscription . "Abonnement")
 (:dashboard-subscribed-until . "Abonnerer til")
 (:dashboard-trial-ends . "Prøveperioden slutter")
 (:dashboard-not-subscribed . "Ikke abonnert")
 (:dashboard-recent . "Nylige oversettelser")
 (:dashboard-no-translations . "Ingen oversettelser ennå")
 (:dashboard-streak . "Rekke med repetisjoner")
 (:dashboard-days . "dager")
 (:dashboard-all-caught-up . "Alt er ajour!")
 (:dashboard-all-caught-up-hint . "Oversett mer for å bygge opp samlingen din.")
 (:dashboard-no-cards-title . "Lag dine første studiekort")
 (:dashboard-no-cards-hint . "Oversett tekst og lagre nyttige fraser for å bygge opp samlingen din.")
 (:dashboard-first-use-checklist-title . "Første steg")
 (:dashboard-first-use-checklist-translate . "Gjør din første oversettelse")
 (:dashboard-first-use-checklist-card . "Lagre ditt første kort")
 (:dashboard-first-use-checklist-review . "Fullfør din første repetisjon")
 (:dashboard-getting-started . "Kom i gang")
 (:dashboard-tip-1 . "Oversett tekst du vil lære")
 (:dashboard-tip-2 . "Klikk \"Lagre som flashcard\" på oversettelser du vil huske")
 (:dashboard-tip-3 . "Repeter flashcards jevnlig - spredt repetisjon hjelper deg å huske på lang sikt")
 (:dashboard-tip-4 . "Vurder ærlig - det hjelper algoritmen å planlegge repetisjonene dine optimalt")

 ;; Account
 (:account-title . "Konto")
 (:account-subtitle . "Administrer profil, abonnement, påminnelser, eksporter og sletting av konto her.")
 (:account-profile-subtitle . "Hold visningsnavnet og e-postadressen din oppdatert.")
 (:account-export-subtitle . "Last ned en kopi av lagrede oversettelser, kortstokker og repetisjonsdata.")
 (:account-deletion-title . "Sletting av konto")
 (:account-deletion-scheduled . "Kontoen din er planlagt slettet den ~A.")
 (:account-deletion-cancel-hint . "Du kan avbryte før denne datoen for å beholde kontoen.")
 (:account-deletion-cancel . "Avbryt sletting")
 (:account-deletion-request . "Du kan be om sletting av kontoen når som helst. Sletting planlegges 14 dager etter bekreftelse. Hvis du ombestemmer deg, kontakt støtte før denne 14-dagersperioden utløper.")
 (:account-deletion-confirm . "Planlegg sletting av konto om 14 dager fra i dag?")
 (:account-deletion-schedule . "Planlegg sletting")
 (:account-reminders-title . "E-postpåminnelser")
 (:account-reminders-subtitle . "Velg om Hiisi kan sende deg e-post når det venter noe du kan repetere.")
 (:account-reminders-opt-out . "Slå av påminnelser om repetisjon og fortsettelse")
 (:account-reminders-save . "Lagre innstillinger")

 ;; Subscription
 (:subscribe-title . "Enkel prissetting")
 (:subscribe-choose-plan . "Velg ditt abonnement")
 (:subscribe-start-today . "Begynn å lære i dag med 14 dagers gratis prøveperiode")
 (:subscribe-monthly . "Månedlig")
 (:subscribe-annual . "Årlig")
 (:subscribe-founder-member . "Grunnleggermedlem")
 (:subscribe-monthly-price . "€10")
 (:subscribe-annual-price . "€100")
 (:subscribe-founder-price . "€79")
 (:subscribe-founder-monthly-equivalent . "€6,58/måned, faktureres årlig")
 (:subscribe-founder-savings . "Spar €41/år sammenlignet med månedlig betaling")
 (:subscribe-monthly-billing-equivalent . "€10/måned, faktureres månedlig")
 (:subscribe-monthly-billing-note . "Fleksibel månedlig betaling")
 (:landing-pricing-comparison-title . "Rask sammenligning")
 (:subscribe-per-month . "/måned")
 (:subscribe-per-year . "/år")
 (:subscribe-monthly-desc . "600 oversettelser per måned. Ubegrenset med studiekort, kortstokker og repetisjoner.")
 (:subscribe-unlimited-flashcards . "Ubegrensede flashcards")
 (:subscribe-grammar-explanations . "Grammatiske forklaringer")
 (:subscribe-spaced-repetition . "Spredt repetisjon")
 (:subscribe-annual-desc . "Alt fra månedsplanen. To måneder gratis.")
 (:subscribe-founder-lock . "Prisen er låst så lenge abonnementet ditt forblir aktivt.")
 (:subscribe-founder-badge . "Begrenset tilbud")
 (:subscribe-founder-limit . "Begrenset til de første 100 medlemmene")
 (:subscribe-manage . "Administrer abonnement")
 (:subscribe-activated . "Abonnement aktivert!")
 (:subscribe-thank-you . "Abonnementet ditt er aktivt. Her kan du administrere fakturering og kjøpe flere oversettelser.")
 (:subscribe-start-learning . "Begynn å lære")
 (:subscribe-management . "Abonnementshåndtering")
 (:subscribe-active . "Aktivt abonnement")
 (:subscribe-preapproved-access . "Forhåndsgodkjent tilgang")
 (:subscribe-status . "Status:")
 (:subscribe-status-active . "Aktiv")
 (:subscribe-status-preapproved . "Forhåndsgodkjent")
 (:subscribe-preapproved-detail . "Denne kontoen bruker forhåndsgodkjent tilgang administrert av Hiisi.")
 (:subscribe-days-remaining . "Dager igjen:")
 (:subscribe-renews-on . "Fornyes den:")
 (:subscribe-no-subscription . "Ingen aktivt abonnement")
 (:subscribe-access-features . "Velg et abonnement for full tilgang og fakturering på ett sted.")
 (:subscribe-view-plans . "Se abonnementer")
 (:subscribe-faq-title . "Ofte stilte spørsmål")
 (:subscribe-faq-trial-q . "Hva skjer etter gratis prøveperiode?")
 (:subscribe-faq-trial-a . "Prøveperioden på 14 dager krever ikke kort. Når den er over, velger du et betalt abonnement for å beholde full tilgang.")
 (:subscribe-faq-cancel-q . "Kan jeg kansellere når som helst?")
 (:subscribe-faq-cancel-a . "Ja! Du kan kansellere abonnementet ditt når som helst. Du beholder tilgang til slutten av faktureringsperioden.")
 (:subscribe-faq-payment-q . "Hvilke betalingsmetoder godtar dere?")
 (:subscribe-faq-payment-a . "Vi godtar alle store kredittkort og debetkort gjennom vår betalingspartner Polar.sh.")
 (:subscribe-copyright . "Lambda Symbolics OÜ © 2026.")
(:subscribe-checkout-unavailable . "Utsjekk er midlertidig utilgjengelig. Prøv igjen.")
(:subscribe-portal-unavailable . "Abonnementshåndtering er midlertidig utilgjengelig. Prøv igjen.")
(:subscribe-founder-sold-out . "Tilbudet for grunnleggermedlemmer er utsolgt")
(:subscribe-founder-unavailable . "Tilbudet for grunnleggermedlemmer er ikke tilgjengelig akkurat nå.")
(:subscribe-checkout-cta . "Abonner")

 ;; Errors and status
 (:error-generic . "Noe gikk galt")
(:error-invalid-request . "Ugyldige forespørselsdata.")
(:error-not-found . "Fant ikke den forespurte ressursen.")
(:error-forbidden . "Du har ikke tilgang til dette.")
(:error-rate-limited . "Vent litt og prøv igjen.")
 (:error-text-too-long . "Teksten er for lang. Maksimal oversettelseslengde er 120 tegn.")
 (:error-input-too-long . "Teksten er for lang")
 (:error-unknown-source-lang . "Kildespråket du valgte støttes ikke.")
 (:error-unknown-target-lang . "Målspråket du valgte støttes ikke.")
 (:error-unknown-language . "Ukjent språk")
 (:error-translation-unavailable . "Oversettelsestjenesten er midlertidig utilgjengelig. Prøv igjen om et øyeblikk.")
 (:error-translation-failed . "Oversettelse mislyktes")
 (:error-translation-retry . "Kunne ikke generere en oversettelse etter flere forsøk. Prøv å omformulere teksten din.")
 (:error-quota-exceeded . "Oversettelsesgrense nådd")
 (:error-quota-exceeded-detail . "Du har brukt alle oversettelsene dine for denne måneden. Kvoten din tilbakestilles automatisk hver måned.")
 (:quota-low-warning . "Kun ~A oversettelser igjen. Vurder å kjøpe flere.")
 (:top-up-button . "Kjøp flere oversettelser")
 (:top-up-price . "€5")
 (:top-up-amount . "300 oversettelser")
(:review-session-expired . "Økt for repetisjon har utløpt. Start en ny økt.")

 (:error-session-expired . "Økten din har utløpt. Logg inn igjen.")
 (:error-session-invalid . "Økten din er ikke lenger gyldig. Logg inn igjen.")
 (:error-custom-flashcard-generation . "Vi klarte ikke å lage forklaringen. Prøv igjen.")
 ;; Institutions
 (:institutions-page-title . "Hiisi for skoler og universiteter")
 (:institutions-hero-title . "Språkundervisningsverktøy laget for klasserommet")
 (:institutions-hero-subtitle . "Gi studentene dine delbare kortstokker, grammatikkbevisst øving og jevne repetisjonsrutiner som passer inn i virkelig undervisning.")
 (:institutions-section-title . "Hvorfor institusjoner bruker Hiisi")
 (:institutions-section-body . "Hiisi hjelper lærere med å gjøre undervisningsmateriale om til veiledet arbeid som studentene faktisk klarer å følge opp. Lag kortstokker for et kurs, del dem med en lenke, og støtt arbeid med ordforråd og grammatikk uten ekstra administrativt arbeid.")
 (:institutions-benefit-1 . "Delbare kortstokker og egne oppgaver som passer læreplanen deres.")
 (:institutions-benefit-2 . "Studentenes liker- og misliker-tilbakemeldinger hjelper de beste oversettelsene opp for vanlige uttrykk i undervisningen.")
 (:institutions-benefit-3 . "Grammatikkgjennomganger og fordelt repetisjon støtter mer enn pugging av isolerte ordlister.")
 (:institutions-benefit-4 . "Lærerorientert støtte fra noen som lytter nøye og bryr seg om behovene i klasserommet.")
 (:institutions-request-title . "La oss ta en prat")
 (:institutions-request-subtitle . "Fortell oss om institusjonen deres, språkene dere jobber med og hvilken undervisningsstøtte dere trenger. Vi svarer innen en uke.")
 (:institutions-aside-title . "Hva skjer videre")
 (:institutions-aside-body . "Vi gjennomgår behovene deres og svarer innen en uke for å avtale tilgang og oppsett for institusjonen deres.")
 (:institutions-field-name . "Institusjonsnavn")
 (:institutions-field-name-placeholder . "Ditt universitet")
 (:institutions-field-contact-name . "Kontaktperson")
 (:institutions-field-contact-name-placeholder . "Ditt navn")
 (:institutions-field-contact-email . "Kontakt-e-post")
 (:institutions-field-contact-email-placeholder . "deg@universitet.no")
 (:institutions-field-domains . "E-postdomener")
 (:institutions-field-domains-placeholder . "universitet.no, cs.universitet.no")
 (:institutions-field-domains-help . "Komma-separert liste over e-postdomener for institusjonen din")
 (:institutions-field-notes . "Tilleggsinformasjon")
 (:institutions-field-notes-placeholder . "Estimert antall studenter, foretrukket faktureringssyklus, eventuelle spesielle krav...")
 (:institutions-submit . "Send forespørsel")
 (:institutions-success-title . "Takk - Hiisi for skoler og universiteter")
 (:institutions-success-heading . "Takk!")
 (:institutions-success-body . "Vi har mottatt forespørselen deres. Vi går gjennom behovene til institusjonen og tar kontakt innen en uke.")
 (:institutions-success-back . "Tilbake til forsiden")

 ;; Footer
 (:footer-privacy . "Personvernerklæring")
 (:footer-terms . "Vilkår for bruk")

 ;; Early software notice
 (:early-software-notice . "Hiisi er under tidlig utvikling. Funnet en feil eller har du et forslag?")

 ;; Personvernerklæring
 (:privacy-title . "Personvernerklæring")
 (:privacy-updated . "Sist oppdatert: januar 2026")
 (:privacy-who-title . "Hvem vi er")
 (:privacy-who-body . "Hiisi drives av Lambda Symbolics OÜ, et selskap registrert i Estland. Som estisk selskap følger vi EUs personvernforordning (GDPR).")
 (:privacy-collect-title . "Data vi samler inn")
 (:privacy-collect-intro . "Når du bruker Hiisi, samler vi inn følgende informasjon:")
 (:privacy-collect-account-key . "Kontoinformasjon: ")
 (:privacy-collect-account-val . "E-postadresse, visningsnavn og et sikkert hashet passord.")
 (:privacy-collect-learning-key . "Læringsdata: ")
 (:privacy-collect-learning-val . "Oversettelsene dine, lagrede studiekort og repetisjonshistorikk.")
 (:privacy-collect-usage-key . "Bruksdata: ")
 (:privacy-collect-usage-val . "Grunnleggende serverlogger for sikkerhet og feilsøking.")
 (:privacy-use-title . "Hvordan vi bruker dataene dine")
 (:privacy-use-auth-key . "Autentisering: ")
 (:privacy-use-auth-val . "For å bekrefte identiteten din og sikre kontoen din.")
 (:privacy-use-service-key . "Tjenesteleveranse: ")
 (:privacy-use-service-val . "For å levere oversettelser og administrere samlingen din av studiekort.")
 (:privacy-use-ai-key . "AI-oversettelser: ")
 (:privacy-use-ai-val . "Oversettelsesforespørslene dine sendes til OpenRouter for å generere svar. OpenRouter kan videresende forespørsler til den konfigurerte modellleverandøren. Se OpenRouters personvernerklæring for hvordan disse dataene behandles.")
 (:privacy-third-title . "Tredjepartstjenester")
 (:privacy-third-intro . "Vi bruker følgende tredjepartstjenester:")
 (:privacy-third-openrouter-key . "OpenRouter: ")
 (:privacy-third-openrouter-val . "For automatiske oversettelsesforespørsler.")
 (:privacy-third-mailgun-key . "Mailgun: ")
 (:privacy-third-mailgun-val . "For sending av aktiverings- og transaksjonse-poster.")
 (:privacy-third-polar-key . "Polar.sh: ")
 (:privacy-third-polar-val . "For behandling av abonnementsbetalinger.")
 (:privacy-cookies-title . "Informasjonskapsler")
 (:privacy-cookies-intro . "Vi bruker bare nødvendige informasjonskapsler:")
 (:privacy-cookies-auth-key . "Autentiseringstoken: ")
 (:privacy-cookies-auth-val . "En sikker HTTP-only informasjonskapsel som holder deg innlogget.")
 (:privacy-cookies-lang-key . "Språkpreferanse: ")
 (:privacy-cookies-lang-val . "For å huske foretrukket språk i brukergrensesnittet.")
 (:privacy-retention-title . "Lagring av data")
 (:privacy-retention-body . "Dataene dine lagres så lenge du har en konto. Når du ber om sletting, planlegges kontoen din slettet om 14 dager.")
 (:privacy-rights-title . "Dine rettigheter (GDPR)")
 (:privacy-rights-intro . "Etter GDPR har du rett til å:")
 (:privacy-rights-access . "Få tilgang til personopplysningene dine")
 (:privacy-rights-export . "Eksportere dataene dine (tilgjengelig på /app/api/export)")
 (:privacy-rights-correct . "Be om retting av uriktige data")
 (:privacy-rights-delete . "Be om sletting av kontoen og dataene dine")
 (:privacy-rights-object . "Protestere mot behandling av dataene dine")
 (:privacy-rights-contact . "For å utøve disse rettighetene, kontakt oss på")
 (:privacy-contact-title . "Kontakt")
 (:privacy-contact-intro . "For personvernrelaterte spørsmål:")
 (:privacy-contact-email-label . "E-post: ")
 (:privacy-address-1 . "Lambda Symbolics OÜ")
 (:privacy-address-2 . "Harju maakond, Tallinn, Kesklinna linnaosa, Tornimäe tn 5, 10145")

 ;; Bruksvilkår
 (:terms-title . "Bruksvilkår")
 (:terms-updated . "Sist oppdatert: januar 2026")
 (:terms-1-title . "1. Beskrivelse av tjenesten")
 (:terms-1-body . "Hiisi er en språklæringsapp som tilbyr automatiske oversettelser med grammatiske forklaringer og studiekort med distribuert repetisjon. Tjenesten drives av Lambda Symbolics OÜ.")
 (:terms-2-title . "2. Registrering av konto")
 (:terms-2-body . "For å bruke Hiisi må du opprette en konto med en gyldig e-postadresse. Du er ansvarlig for sikkerheten til kontoinformasjonen din.")
 (:terms-3-title . "3. Abonnement og betaling")
 (:terms-3-body . "Hiisi tilbyr betalte abonnementer (månedlig og årlig). Abonnement behandles gjennom Polar.sh.")
 (:terms-3-list-1 . "Abonnement fornyes automatisk hvis det ikke sies opp før fornyelsesdato.")
 (:terms-3-list-2 . "Refusjon gis i samsvar med gjeldende forbrukervernlovgivning.")
 (:terms-3-list-3 . "Manglende betaling fører til tap av tilgang til premiumfunksjoner.")
 (:terms-4-title . "4. Akseptabel bruk")
 (:terms-4-intro . "Du samtykker i å ikke:")
 (:terms-4-list-1 . "Bruke tjenesten til ulovlige formål")
 (:terms-4-list-2 . "Forsøke å omgå bruksgrenser eller sikkerhetstiltak")
 (:terms-4-list-3 . "Dele kontoinformasjonen din med andre")
 (:terms-4-list-4 . "Bruke automatiserte verktøy på en måte som svekker ytelsen for andre")
 (:terms-5-title . "5. Innhold og immaterielle rettigheter")
 (:terms-5-body-1 . "Oversettelser som genereres av Hiisi lages automatisk og er kanskje ikke unike. Du kan bruke oversettelsene og studiekortene dine til personlige formål, men du har ikke eksklusiv opphavsrett til automatisk generert innhold.")
 (:terms-5-body-2 . "Hiisi-applikasjonen, merkevaren og originalt innhold forblir eiendom til Lambda Symbolics OÜ.")
 (:terms-6-title . "6. Tilgjengelighet")
 (:terms-6-intro . "Hiisi leveres som den er. Vi garanterer ikke:")
 (:terms-6-list-1 . "Uavbrutt eller feilfri tjeneste")
 (:terms-6-list-2 . "Nøyaktigheten av automatisk genererte oversettelser")
 (:terms-6-list-3 . "Tilgjengeligheten av spesifikke funksjoner")
 (:terms-6-body . "Vi kan endre eller avvikle funksjoner når som helst.")
 (:terms-7-title . "7. Ansvarsbegrensning")
 (:terms-7-body-1 . "I den grad loven tillater det, er Lambda Symbolics OÜ ikke ansvarlig for indirekte, tilfeldige, særskilte eller følgeskader som oppstår ved bruk av Hiisi.")
 (:terms-7-body-2 . "Vårt totale ansvar skal ikke overstige beløpet du har betalt for tjenesten i de 12 månedene før kravet.")
 (:terms-8-title . "8. Oppsigelse av konto")
 (:terms-8-body-1 . "Vi kan suspendere eller avslutte kontoen din hvis du bryter disse vilkårene. Du kan når som helst be om sletting av konto i applikasjonen.")
 (:terms-8-body-2 . "Ved slettingsforespørsel planlegges kontoen din slettet om 14 dager.")
 (:terms-9-title . "9. Endringer i vilkår")
 (:terms-9-body . "Vi kan oppdatere disse vilkårene fra tid til annen. Fortsatt bruk av Hiisi etter endringer innebærer at du godtar de nye vilkårene.")
 (:terms-10-title . "10. Lovvalg")
 (:terms-10-body . "Disse vilkårene er underlagt estisk lov. Eventuelle tvister skal avgjøres av domstolene i Estland.")
 (:terms-contact-title . "Kontakt")
 (:terms-contact-intro . "For spørsmål om disse vilkårene:")
 (:terms-contact-email-label . "E-post: ")
 (:terms-address-1 . "Lambda Symbolics OÜ")
 (:terms-address-2 . "Harju maakond, Tallinn, Kesklinna linnaosa, Tornimäe tn 5, 10145")

 ;; Decks
 (:decks-title . "Kortstokker")
 (:decks-subtitle . "Lag egne kortstokker og del dem med andre.")
 (:decks-create-title . "Lag kortstokk")
 (:decks-name-placeholder . "Navn på kortstokk")
 (:decks-desc-placeholder . "Beskrivelse")
 (:decks-create-btn . "Lag kortstokk")
 (:decks-edit-title . "Rediger kortstokk")
 (:decks-edit-btn . "Rediger kortstokk")
 (:decks-actions-title . "Kortstokkhandlinger")
 (:decks-card-actions-title . "Korthandlinger")
 (:decks-update-btn . "Lagre endringer")
 (:decks-default-badge . "Automatisk")
 (:decks-default-description . "Denne kortstokken administreres automatisk for dette språkparet.")
 (:decks-default-readonly . "Automatiske kortstokker har faste navn og beskrivelser.")
 (:decks-delete-btn . "Slett kortstokk")
 (:decks-delete-confirm . "Er du sikker på at du vil slette denne kortstokken?")
 (:decks-error-name-required . "Navn på kortstokk er påkrevd.")
 (:decks-error-name-too-long . "Navnet på kortstokken kan være på maks ~A tegn.")
 (:decks-error-desc-too-long . "Beskrivelsen av kortstokken kan være på maks ~A tegn.")
 (:decks-error-default-readonly . "Automatiske kortstokker kan ikke redigeres.")
 (:decks-error-default-delete-forbidden . "Automatiske kortstokker kan ikke slettes.")
 (:decks-your-title . "Dine kortstokker")
 (:decks-col-updated . "Oppdatert")
 (:decks-no-decks . "Ingen kortstokker ennå.")
 (:decks-open-btn . "Åpne")
 (:decks-view-deck-btn . "Vis kortstokk")
 (:decks-start-review . "Start repetisjon")
 (:decks-no-desc . "Ingen beskrivelse.")
 (:decks-share-title . "Delingslenke")
 (:decks-share-info . "Alle med denne lenken kan importere kortstokken:")
 (:decks-share-copy . "Kopier lenke")
 (:decks-share-copied . "Kopiert")
 (:decks-add-from-flashcards-title . "Legg til studiekort")
 (:decks-add-from-flashcards-info . "Velg et kort for å legge oversettelsen til i denne kortstokken.")
 (:decks-create-new-flashcard . "Opprett nytt studiekort")
 (:decks-open-flashcards . "Legg til eksisterende studiekort")
 (:decks-filter-from . "Kildespråk")
 (:decks-filter-to . "Målspråk")
 (:decks-filter-any . "Alle språk")
 (:decks-filter-include-assigned . "Inkluder kort som allerede er i en kortstokk")
 (:decks-flashcards-add . "Legg til")
 (:decks-flashcards-added . "Lagt til")
 (:decks-flashcards-in-deck . "I en annen kortstokk")
 (:decks-flashcards-empty . "Ingen kort samsvarer med disse filtrene.")
 (:decks-items-title . "Innhold i kortstokk")
 (:decks-col-original . "Original")
 (:decks-col-translated . "Oversettelse")
 (:decks-col-lang . "Målspråk")
 (:decks-no-items . "Ingen elementer ennå.")
 (:decks-share-page-title . "Del kortstokk")
 (:decks-share-preview . "Forhåndsvis og importer denne kortstokken.")
 (:decks-import-title . "Importer")
 (:decks-import-btn . "Importer kortstokk")
 (:starter-decks-title . "Bibliotek")
 (:starter-decks-subtitle . "Importer ferdige kortstokker fra Hiisi og fellesskapet.")
 (:starter-decks-marketplace-btn . "Bibliotek")
 (:starter-decks-explanation-language . "Forklaringsspråk")
 (:starter-decks-search-label . "Søk")
 (:starter-decks-source-label . "Kilde")
 (:starter-decks-source-all . "Alle kortstokker")
 (:starter-decks-change-language . "Endre")
 (:starter-decks-filters-button . "Filtre")
 (:starter-decks-search-placeholder . "Søk i biblioteket")
 (:starter-decks-apply-filters . "Bruk filtre")
 (:starter-decks-select-triplet-hint . "Velg kilde- og målspråk for å bla gjennom passende kortstokker.")
 (:starter-decks-official-badge . "Offisiell")
 (:starter-decks-official-by-hiisi . "Offisiell fra Hiisi")
 (:starter-decks-community-badge . "Fellesskap")
 (:starter-decks-by-hiisi . "Fra Hiisi")
 (:starter-decks-preview-btn . "Forhåndsvis")
 (:starter-decks-card-count . "~A kort")
 (:starter-decks-no-results . "Ingen kortstokker passer disse filtrene.")
 (:starter-decks-source-cards-title . "Kort i denne kortstokken")
 (:starter-decks-more-cards-included . "+~A flere kort inkludert.")
 (:starter-decks-sample-title . "Eksempelkort")
 (:starter-decks-generating . "Forbereder kortstokken din: ~A")
 (:starter-decks-generating-detail . "Vi importerer den så snart den er klar. Du kan fortsette å bla i Biblioteket eller komme tilbake om litt.")
 (:starter-decks-generation-failed . "Genereringen mislyktes")
 (:starter-decks-generation-failed-detail . "Siste forsøk på å generere kortstokken mislyktes. Prøv å importere kortstokken på nytt.")
 (:starter-decks-login-detail . "Logg inn for å importere denne kortstokken til samlingen din.")
 (:starter-decks-subscribe-btn . "Se planer")
 (:starter-decks-subscribe-detail . "Kortstokker i biblioteket er tilgjengelige med et aktivt abonnement eller en prøveperiode.")
 (:library-submit-title . "Send til biblioteket")
 (:library-submit-intro . "Send denne kortstokken til biblioteket for administrativ gjennomgang før publisering.")
 (:library-submit-btn . "Send kortstokk")
 (:library-submit-approved . "Godkjent for biblioteket")
 (:library-submit-approved-detail . "Denne kortstokken er publisert i biblioteket.")
 (:library-submit-pending . "Til vurdering")
 (:library-submit-pending-detail . "Denne kortstokken er sendt inn og venter på administrativ vurdering.")
 (:library-submit-rejected . "Trenger endringer før publisering")
 (:library-submit-rejected-detail . "Denne innsendingen ble avvist. Oppdater kortstokken og send den inn på nytt.")
 (:library-error-empty . "Legg til minst ett kort før du sender denne kortstokken til biblioteket.")
 (:library-error-missing-triplet . "Hvert kort i en biblioteksinnsending må ha et fullstendig språktrippel.")
 (:library-error-mixed-triplet . "Alle kort i en biblioteksinnsending må ha det samme språktrippelet.")
 (:starter-deck-topic-greetings-title . "Hilsener og presentasjoner")
 (:starter-deck-topic-greetings-description . "Hilsener, navn, høflige grunnuttrykk og fraser for et første møte.")
 (:starter-deck-topic-travel-title . "Essensiell reise")
 (:starter-deck-topic-travel-description . "Stasjoner, billetter, priser, hjelp og å finne veien.")
 (:starter-deck-topic-numbers-title . "Tall og priser")
 (:starter-deck-topic-numbers-description . "Telling, totalsummer, priser, etasjer og dagligdagse mengder.")
 (:starter-deck-topic-time-title . "Tid og datoer")
 (:starter-deck-topic-time-description . "Dager, måneder, avtaler, klokkeslett og relative datoer.")
 (:starter-deck-topic-food-title . "Restaurant og mat")
 (:starter-deck-topic-food-description . "Bestilling, kosthensyn, drikke, regningen og vanlige måltider ute.")
 (:starter-deck-topic-emergency-title . "Nødsituasjoner og helse")
 (:starter-deck-topic-emergency-description . "Leger, apotek, symptomer, kroppsdeler og akutt hjelp.")
 (:starter-deck-topic-directions-title . "Veibeskrivelser og transport")
 (:starter-deck-topic-directions-description . "Veibeskrivelser, holdeplasser, billetter, plattformer og å komme seg rundt i byen.")
 (:starter-deck-topic-school-title . "Skole og utdanning")
 (:starter-deck-topic-school-description . "Timer, lekser, prøver, skolesaker og hverdagslivet på skolen.")
 (:starter-deck-topic-university-title . "Universitet og studier")
 (:starter-deck-topic-university-description . "Forelesninger, seminarer, studieretninger, oppgaver og hverdagslivet på campus.")

 ;; Flashcards management page
 (:flashcards-title . "Mine kort")
 (:flashcards-subtitle . "Alle dine lagrede kort på ett sted. Søk, organiser og administrer.")
 (:flashcards-search-placeholder . "Søk i kort...")
 (:flashcards-filter-button . "Filtre")
 (:flashcards-filter-title . "Filtrer kort")
 (:flashcards-filter-recollection . "Hvor godt du kan dem")
 (:flashcards-filter-any-recollection . "Hvilket som helst nivå")
 (:flashcards-hide-perfected . "Skjul fullt innlærte kort")
 (:flashcards-col-original . "Original")
 (:flashcards-col-translated . "Oversettelse")
 (:flashcards-no-cards . "Ingen kort ennå. Begynn å oversette for å lage noen!")
 (:flashcards-image-label . "Bilde")
 (:flashcards-image-upload . "Last opp bilde")
 (:flashcards-image-replace . "Bytt bilde")
 (:flashcards-image-remove . "Fjern bilde")
 (:flashcards-pagination-label . "Flashcard-sider")
 (:flashcards-pagination-status . "Side ~A av ~A")
 (:flashcards-pagination-previous . "Forrige")
 (:flashcards-pagination-next . "Neste")

 ;; Landing page (redesign)
 (:landing-hero-headline . "Hvert ord forklart. Hver repetisjon planlagt. Femten språk.")
 (:landing-hero-headline-v1 . "Oversett setninger enkelt og les grammatikken på ditt eget språk.")
 (:landing-hero-headline-v2 . "Hiisi sørger for at du ikke glemmer hver setning du oversetter.")
 (:landing-hero-headline-v3 . "Gjør setningene du oversetter, til ordforråd du kan bruke.")
 (:landing-hero-subheadline . "Bokmerk hvilken som helst setning, så gir Hiisi deg oversettelsen, grammatikken, uttalen og et studiekort som kommer tilbake til repetisjon.")
 (:landing-hero-trust-line . "14 dager gratis. Ingen kort kreves.")
 (:landing-credibility-languages . "Femten språk")
 (:landing-credibility-flashcards . "Smarte studiekort")
 (:landing-credibility-pronunciation . "Uttaleguide")
 (:landing-languages-title . "Velg språket du lenge har hatt lyst til å lære")
 (:landing-video-title . "Trykk på spill av og bli ordentlig kjent med Hiisi")
 (:landing-video-placeholder-label . "Plassholder for Hiisis produktvideo")
 (:landing-video-placeholder-eyebrow . "Produktvideo")
 (:landing-video-placeholder-copy . "En kort produktvideo vil vise flyten med bokmerker, grammatikk, uttale og repetisjon her.")
 (:landing-problem-title . "Setningen du oversatte forrige uke. Klarer du å si den nå?")
 (:landing-problem-body-1 . "Det øyeblikket skjer ofte. Du ser en frase. Du limer den inn i en oversetter. Betydningen gir mening, akkurat der i hånden din. En uke går. Ordene har forlatt minnet, og betydningen har blitt med dem.")
 (:landing-problem-body-2 . "Oversettelsen holder på betydningen i øyeblikket du leser den. Men å lære en setning krever vanligvis fire separate verktøy:")
 (:landing-problem-tool-1 . "En oversetter for betydningen")
 (:landing-problem-tool-2 . "En grammatikkreferanse for strukturen")
 (:landing-problem-tool-3 . "En uttaleguide for lyden")
 (:landing-problem-tool-4 . "En studiekort-app for å beholde det i minnet")
 (:landing-problem-body-3 . "Å bruke alle fire verktøyene tar tid. Og neste setning er borte før du er ferdig med studiekortet.")
 (:landing-bookmark-title . "Hva som skjer når du bokmerker en setning i Hiisi")
 (:landing-bookmark-body . "Ett trykk. Hiisi gjør setningen til et strukturert læringselement på sekunder, klart til å studeres. Setningen blir liggende i biblioteket ditt, med oversettelse og grammatikk vedlagt.")
 (:landing-bookmark-benefit-1 . "Den opprinnelige setningen og en tydelig oversettelse")
 (:landing-bookmark-benefit-2 . "Uttale i det internasjonale fonetiske alfabetet, IPA")
 (:landing-bookmark-benefit-3 . "Grammatikk forklart på språket du foretrekker å lese forklaringer på")
 (:landing-bookmark-benefit-4 . "Fargematchede ord viser hvilken oversettelsesdel som hører til hvilket originalord")
 (:landing-bookmark-benefit-5 . "Et studiekort som kommer tilbake når hukommelsen trenger det")
 (:landing-bookmark-cta . "Bokmerk din første setning")
 (:landing-use-cases-title . "Hva du kan bruke Hiisi på")
 (:landing-use-cases-body . "En setning er nok til å starte. Alt du leser eller hører på et nytt språk, fungerer med Hiisi.")
 (:landing-use-case-lyrics . "Sangtekster fra en sang du spiller om igjen")
 (:landing-use-case-articles . "Artikler på språket du lærer")
 (:landing-use-case-messages . "Meldinger fra venner som har språket som morsmål")
 (:landing-use-case-media . "Linjer fra filmer eller podkaster du lagrer")
 (:landing-use-case-current-page . "Siden du leser akkurat nå")
 (:landing-benefits-title . "Bygget for selvstudenter og studenter")
 (:landing-benefit-grammar-title . "Grammatikk på språket du allerede tenker på")
 (:landing-benefit-grammar-body . "Les fransk grammatikk på engelsk eller spansk grammatikk på polsk. Oppmerksomheten din blir værende på setningen du lærer.")
 (:landing-benefit-colour-title . "Ord koblet med farge")
 (:landing-benefit-colour-body . "Et ord og oversettelsen deler samme farge. Du ser betydningen av hvert ord med ett blikk.")
 (:landing-benefit-pronunciation-title . "Uttale du kan lese")
 (:landing-benefit-pronunciation-body . "Hver setning kommer med en skrevet uttaleguide, samme type som ordbøker bruker. Du ser hvordan setningen høres ut før du sier den.")
 (:landing-benefit-schedule-title . "Studiekort som planlegger seg selv")
 (:landing-benefit-schedule-body . "Hver bokmerkede setning blir et kort. SM-2-algoritmen bak Anki bestemmer når det kommer tilbake, så du repeterer det du er i ferd med å glemme.")
 (:landing-benefit-decks-title . "Temadeck for det som kommer")
 (:landing-benefit-decks-body . "Reiser du neste måned? Starter du i ny jobb? Importer et ferdig deck for restauranter eller intervjuer og repeter fra dag én.")
 (:landing-benefit-languages-title . "Femten språk, alle retninger")
 (:landing-benefit-languages-body . "Oversett spansk til fransk eller engelsk til tysk. Hiisi håndterer alle retninger i hele settet.")
 (:landing-benefits-cta . "Prøv Hiisi")
 (:landing-step-1-title . "Lim inn en setning")
 (:landing-step-1-desc . "Hvilken som helst lengde, på et av 15 språk. Du får oversettelsen pluss en grammatikkanalyse av hvert ord.")
 (:landing-step-2-title . "Lagre det som er verdt å huske")
 (:landing-step-2-desc . "Ett klikk gjør en oversettelse til et studiekort, med den opprinnelige setningen bevart som kontekst.")
 (:landing-step-3-title . "Repeter på rett tidspunkt")
 (:landing-step-3-desc . "Distribuert repetisjon med SM-2, samme algoritme som Anki. Kort du sliter med, kommer tilbake tidligere.")
 (:landing-feature-grammar-title . "Hvert ord forklart, på ditt språk")
 (:landing-feature-grammar-desc . "Oversettelser kommer med kasus, kjønn, aspekt og modus analysert ord for ord. Finsk partitiv, tsjekkisk bestemthet av levende, polsk aspekt, tyske dativsammentrekninger, alt merket og lenket til en grammatikkreferanse.")
 (:landing-feature-srs-title . "Vanen med distribuert repetisjon, automatisert")
 (:landing-feature-srs-desc . "SM-2-algoritmen tilpasser seg resultatene dine. Vanskelige kort vises oftere. Kort du kan, vises sjeldnere.")
 (:landing-feature-share-title . "Dine kortstokker, eller fellesskapets")
 (:landing-feature-share-desc . "Organiser studiekort i tematiske kortstokker. Del en kortstokk med en lenke, eller bla gjennom fellesskapsbiblioteket etter kortstokker andre har delt.")
 (:landing-pricing-trial-note . "Inkluderer 14 dagers gratis prøveperiode")
 (:landing-pricing-monthly-after . "14 dager gratis, deretter ~A/måned")
 (:landing-pricing-annual-after . "14 dager gratis, deretter ~A/år")
 (:landing-faq-title . "Ofte stilte spørsmål")
 (:landing-faq-trial-cap-q . "Hvor mange oversettelser får jeg i prøveperioden?")
 (:landing-faq-trial-cap-a . "Du får 200 oversettelser i løpet av 14 dagers prøveperiode. Etter abonnement får du 600 per måned.")
 (:landing-final-cta-title . "Din første setning tar fem sekunder.")
 (:landing-final-cta-subtitle . "Lim inn hva som helst på finsk, tsjekkisk, polsk eller et av de andre tolv språkene. Se hva Hiisi gjør med det. Fjorten dager gratis.")

 ;; Trial status (in-app)
 (:trial-status . "Gratis prøveperiode")
 (:error-trial-quota-exceeded . "Grense for prøveoversettelser nådd")
 (:error-trial-quota-detail . "Du har brukt alle 200 prøveoversettelsene. Abonner for å fortsette å lære.")

 ;; Custom flashcards
 (:custom-flashcard-create-title . "Opprett studiekort")
 (:custom-flashcard-edit-title . "Rediger studiekort")
 (:custom-flashcard-original . "Originaltekst")
 (:custom-flashcard-translated . "Oversettelse")
 (:custom-flashcard-lang-from . "Kildespråk")
 (:custom-flashcard-lang-to . "Målspråk")
 (:custom-flashcard-note . "Pedagogisk notat")
 (:custom-flashcard-forms . "Grammatikkanalyse")
 (:custom-flashcard-form-term . "Begrep")
 (:custom-flashcard-form-explanation . "Forklaring")
 (:custom-flashcard-add-form . "Legg til grammatikkbegrep")
 (:custom-flashcard-remove-form . "Fjern")
 (:custom-flashcard-ai-fill . "Fyll ut med KI")
 (:custom-flashcard-create-btn . "Opprett studiekort")
 (:custom-flashcard-update-btn . "Lagre endringer")

  ;; Newsletter
  (:newsletter-email-label . "E-postadresse")
  (:newsletter-developer-label . "Jeg er utvikler")
  (:newsletter-developer-hint . "motta tekniske oppdateringer")
  (:landing-newsletter-title . "Få Hiisi-oppdateringer.")
  (:landing-newsletter-body . "Meld deg på nyhetsbrevet for produktoppdateringer, støtte for nye språk, startdekk og sporadiske tilbud for grunnlegger-medlemmer.")
  (:landing-newsletter-fine-print . "Ingen spam. Bare produktoppdateringer.")
  (:landing-newsletter-button . "Meld deg på nyhetsbrevet")
  (:newsletter-unsubscribe-page-title . "Meld deg av Hiisi-nyhetsbrevet")
  (:newsletter-unsubscribe-title . "Meld deg av")
  (:newsletter-unsubscribe-subtitle . "Skriv inn e-posten din for å slutte å motta Hiisi-oppdateringer.")
  (:newsletter-unsubscribe-button . "Meld deg av")
  (:newsletter-feedback-email-required . "Skriv inn e-postadressen din.")
  (:newsletter-feedback-email-invalid . "Skriv inn en gyldig e-postadresse.")
  (:newsletter-feedback-already-signed-up . "Du er allerede påmeldt. Vi holder deg oppdatert!")
  (:newsletter-feedback-signed-up . "Du er på listen! Vi sender sporadiske Hiisi-oppdateringer.")
  (:newsletter-feedback-unsubscribed . "Hvis denne e-posten var påmeldt, er den fjernet fra Hiisi-oppdateringer.")
  (:newsletter-feedback-generic-error . "Noe gikk galt. Prøv igjen.")

  ;; Issue reporting
  (:issues-open-button . "Rapporter en feil")
 (:issues-modal-title . "Rapporter et problem")
 (:issues-modal-subtitle . "Beskriv hva som gikk galt. Vi legger automatisk ved siden du er på.")
 (:issues-title-label . "Kort tittel")
 (:issues-title-placeholder . "Kort oppsummering av problemet")
 (:issues-message-label . "Hva skjedde?")
 (:issues-message-placeholder . "Ta med trinn for å gjenskape, forventet oppførsel og hva som faktisk skjedde.")
 (:issues-submit . "Send rapport")
 (:issues-cancel . "Avbryt")
 (:issues-success . "Rapporten din ble sendt. Vi ser på den så snart vi kan.")
 (:issues-error-required . "Beskriv problemet før du sender inn.")
 (:issues-error-title-too-long . "Sakstittelen er for lang. Hold den under 160 tegn.")
 (:issues-error-too-long . "Rapportteksten er for lang. Hold den under 4000 tegn.")
 (:issues-error-rate-limit . "For mange rapporter fra denne kilden. Vent litt og prøv igjen senere.")
 (:issues-error-generic . "Problemrapporten kunne ikke sendes. Prøv igjen.")

)
