;;; Polish translations
;;; This file should contain all keys from en.lisp

(
 ;; Language metadata (used for language picker)
 (:lang-name . "Polski")
 (:lang-flag . "🇵🇱")

 ;; Language modal (first-visit language selection)
 (:lang-modal-title . "Wybierz język")
 (:lang-modal-subtitle . "Wybierz preferowany język interfejsu:")

 ;; Navigation
 (:nav-translate . "Tłumacz")
 (:nav-review . "Powtórka")
 (:nav-flashcards . "Moje fiszki")
 (:nav-dashboard . "Panel")
 (:nav-decks . "Talie")
 (:nav-logout . "Wyloguj")
 (:nav-home . "Strona główna")
 (:nav-pricing . "Cennik")
 (:nav-institutions . "Dla instytucji")
 (:nav-export-data . "Eksportuj dane")
 (:nav-open-navigation . "Otwórz nawigację")
 (:theme-light . "Jasny")
 (:theme-dark . "Ciemny")

 ;; App title and branding
 (:app-title . "Hiisi - Nauka języków")

 ;; Landing page
 (:landing-meta-title . "Hiisi: aplikacja do nauki języków z gramatyką i fiszkami")
 (:landing-meta-description . "Hiisi to aplikacja do nauki języków. Każde przetłumaczone zdanie staje się fiszką z wbudowaną gramatyką, zaplanowaną przez SM-2, algorytm Anki. 15 języków.")
 (:landing-start-trial . "Zacznij korzystać z Hiisi")
 (:landing-best-value . "Najlepsza oferta")

 ;; Auth pages
 (:auth-register . "Zarejestruj się")
 (:auth-login . "Zaloguj się")
 (:auth-email . "Email")
 (:auth-password . "Hasło")
 (:auth-password-again . "Potwierdź hasło")
 (:auth-display-name . "Nazwa wyświetlana")
 (:auth-register-title . "Zarejestruj się w Hiisi")
 (:auth-register-subtitle . "Utwórz nowe konto")
 (:auth-login-title . "Zaloguj się do Hiisi")
 (:auth-login-subtitle . "Wprowadź swoje dane")
 (:auth-login-invalid-credentials . "Nieprawidlowy e-mail lub haslo.")
 (:auth-login-rate-limited . "Zbyt wiele prob logowania. Poczekaj kilka minut i sproboj ponownie.")
(:auth-register-rate-limited . "Zbyt wiele prób rejestracji. Odczekaj kilka minut i spróbuj ponownie.")
(:auth-email-invalid . "Podaj prawidłowy adres e-mail.")
(:auth-password-too-short . "Hasło musi mieć co najmniej 8 znaków.")
(:auth-passwords-mismatch . "Hasła nie są takie same.")
(:auth-display-name-invalid . "Wyświetlana nazwa musi mieć od 1 do 100 znaków.")
(:auth-register-email-exists . "Konto z tym adresem e-mail już istnieje.")
(:auth-register-unavailable . "Rejestracja jest tymczasowo niedostępna. Spróbuj ponownie później.")
(:auth-register-plan-required . "Wybierz plan przed utworzeniem konta.")
(:auth-preapproved-email-unrecognized . "Użyj adresu e-mail z zaproszenia albo wybierz plan przed utworzeniem konta.")
(:auth-institution-register . "Jesteś z instytucji?")
(:auth-institution-stage-title . "Dostęp instytucjonalny")
(:auth-institution-stage-subtitle . "Użyj e-maila szkoły lub uczelni. Uprawnione konta są odblokowywane przez instytucję po weryfikacji e-maila.")
(:auth-institution-title . "Zarejestruj się przez swoją instytucję")
(:auth-institution-subtitle . "Użyj adresu e-mail szkoły lub uczelni. Jeśli Twoja instytucja jest już skonfigurowana w Hiisi, konto zostanie odblokowane po weryfikacji e-maila; indywidualny 14-dniowy okres próbny dotyczy rejestracji z osobistym planem.")
(:auth-institution-benefit-email . "Użyj adresu e-mail swojej szkoły lub uczelni.")
(:auth-institution-benefit-access . "Uprawnione konta otrzymują dostęp instytucjonalny po weryfikacji e-maila.")
(:auth-institution-benefit-fallback . "Jeśli domena nie zostanie rozpoznana, wybierz indywidualny plan albo poproś instytucję o kontakt z Hiisi.")
(:auth-see-included . "Zobacz, co jest wliczone")
(:auth-institution-check-access . "Sprawdź dostęp")
(:auth-institution-email-eligible-title . "Dostęp instytucjonalny potwierdzony")
(:auth-institution-email-eligible-detail . "Kontynuuj z tym adresem e-mail, aby utworzyć konto. Dostęp zostanie odblokowany po weryfikacji e-maila.")
(:auth-institution-change-email . "Użyj innego e-maila")
(:auth-institution-outcome-note . "Jeśli Twoja szkoła lub uczelnia zapewnia dostęp do Hiisi, konto zostanie odblokowane po weryfikacji e-maila. Jeśli domena nie kwalifikuje się, wybierz osobisty plan, aby rozpocząć 14-dniowy okres próbny.")
(:auth-institution-personal-plan-link . "Zobacz osobiste plany")
(:auth-institution-domain-unrecognized . "Nie rozpoznajemy jeszcze tej instytucjonalnej domeny e-mail. Wybierz osobisty plan, aby rozpocząć 14-dniowy okres próbny, albo poproś swoją instytucję o kontakt z Hiisi.")
(:subscribe-institution-callout-title . "Używasz Hiisi przez szkołę lub uczelnię?")
(:subscribe-institution-callout-body . "Zarejestruj się instytucjonalnym e-mailem, a Hiisi automatycznie odblokuje dostęp, jeśli Twoja instytucja jest już skonfigurowana.")
(:auth-activation-email-send-failed . "Nie udało się wysłać wiadomości aktywacyjnej. Spróbuj ponownie.")
 (:auth-forgot-password . "Zapomniałeś hasła?")
 (:auth-no-account . "Nie masz konta?")
 (:auth-have-account . "Masz już konto?")
 (:auth-google . "Google")
 (:auth-google-login-failed . "Logowanie przez Google nie powiodło się. Spróbuj ponownie.")
 (:auth-account-created . "Konto utworzone!")
 (:auth-check-email . "Sprawdź swoją skrzynkę email, aby znaleźć link aktywacyjny.")
 (:auth-redirect-login . "Przekierowanie do logowania za")
 (:auth-seconds . "sekund...")
 (:auth-go-now . "Przejdź teraz")
 (:auth-not-activated . "Konto nie zostało aktywowane")
 (:auth-activate-title . "Aktywuj swoje konto!")
 (:auth-activated . "Konto aktywowane!")
 (:auth-activated-message . "Twoje konto zostało aktywowane. Możesz teraz korzystać z Hiisi.")
 (:auth-redirecting . "Przekierowanie za")
 (:auth-go-to-app . "Przejdź do aplikacji")
 (:onboarding-title . "Jak działa Hiisi")
 (:onboarding-subtitle . "Tłumacz prawdziwy tekst, sprawdzaj gramatykę, zapisuj przydatne elementy i powtarzaj je później.")
 (:onboarding-translate-detail . "Zacznij od prawdziwego tekstu. Hiisi pokazuje tłumaczenie, dopasowane formy i kolejne działania do nauki w jednym miejscu.")
 (:onboarding-grammar-detail . "Otwórz analizę gramatyczną, aby zobaczyć, które formy odpowiadają sobie w zdaniu i jaką funkcję pełni każda część.")
 (:onboarding-review-detail . "Zapisuj przydatne tłumaczenia i powtarzaj je później z użyciem powtórek rozłożonych w czasie, aby zostały w pamięci długotrwałej.")
 (:onboarding-decks-detail . "Grupuj przydatne elementy w taliach, udostępniaj je innym i trzymaj powiązany materiał razem.")
 (:onboarding-back . "Wstecz")
 (:onboarding-next . "Dalej")
 (:onboarding-skip . "Pomiń przewodnik")
 (:auth-resend-title . "Wyślij ponownie email aktywacyjny")
 (:auth-resend-subtitle . "Wpisz swój email, aby otrzymać nowy link aktywacyjny.")
 (:auth-resend-button . "Wyślij ponownie email aktywacyjny")
 (:auth-resend-success . "Email aktywacyjny wysłany!")
 (:auth-resend-success-detail . "Sprawdź swoją skrzynkę odbiorczą, aby znaleźć nowy link aktywacyjny.")
 (:auth-resend-rate-limited . "Poczekaj kilka minut przed ponownym wysłaniem emaila aktywacyjnego.")
 (:auth-resend-cooldown . "Możesz poprosić o kolejny email za ~a sekund.")
 (:auth-back-to-login . "Wróć do logowania")
 (:auth-forgot-password-title . "Zapomniałem hasła")
 (:auth-forgot-password-subtitle . "Wpisz swój email, a wyślemy ci link do zresetowania hasła.")
 (:auth-send-reset-link . "Wyślij link do resetowania")
 (:auth-reset-email-sent . "Link wysłany!")
 (:auth-reset-email-sent-detail . "Jeśli konto z tym emailem istnieje, wkrótce otrzymasz link do zresetowania hasła.")
 (:auth-reset-rate-limited . "Poczekaj kilka minut przed kolejną próbą resetowania hasła.")
 (:auth-reset-invalid-token . "Ten link do resetowania jest nieprawidłowy lub wygasł.")
 (:auth-reset-password-title . "Zresetuj hasło")
 (:auth-reset-password-subtitle . "Wpisz swoje nowe hasło poniżej.")
 (:auth-new-password . "Nowe hasło")
 (:auth-confirm-new-password . "Potwierdź nowe hasło")
 (:auth-reset-password . "Zresetuj hasło")
 (:auth-password-changed . "Hasło zmienione!")
 (:auth-password-changed-detail . "Twoje hasło zostało pomyślnie zmienione. Możesz teraz zalogować się nowym hasłem.")
 (:auth-change-password-title . "Zmień hasło")
 (:auth-change-password-subtitle . "Zaktualizuj hasło do swojego konta.")
 (:auth-current-password . "Obecne hasło")
 (:auth-change-password . "Zmień hasło")
 (:auth-back-to-app . "Wróć do aplikacji")
 (:auth-password-updated . "Hasło zaktualizowane!")
 (:auth-password-updated-detail . "Twoje hasło zostało pomyślnie zaktualizowane.")
(:auth-current-password-invalid . "Obecne hasło jest nieprawidłowe.")
(:auth-new-password-same . "Nowe hasło musi być inne niż obecne hasło.")

 ;; Email copy
 (:email-common-hi . "Cześć")
 (:email-common-tagline . "Hiisi - Ucz się przez tłumaczenie")
 (:email-activation-subject . "Aktywuj swoje konto Hiisi")
 (:email-activation-title . "Witaj w Hiisi")
 (:email-activation-body . "Dziękujemy za rejestrację. Aktywuj swoje konto, klikając poniższy link:")
 (:email-activation-button . "Aktywuj konto")
 (:email-activation-copy-link . "Lub skopiuj ten link")
 (:email-activation-expiry . "Link wygaśnie za 24 godziny.")
 (:email-reset-subject . "Zresetuj hasło do Hiisi")
 (:email-reset-title . "Prośba o zresetowanie hasła")
 (:email-reset-body . "Otrzymaliśmy prośbę o zresetowanie Twojego hasła. Kliknij poniższy link, aby ustawić nowe hasło:")
 (:email-reset-button . "Zresetuj hasło")
 (:email-reset-expiry . "Link wygaśnie za 1 godzinę.")
 (:email-reset-ignore . "Jeśli nie prosiłeś o zresetowanie hasła, możesz zignorować tę wiadomość.")
 (:email-reminder-subject-due . "Czas powtórzyć Twoje fiszki w Hiisi")
 (:email-reminder-subject-streak . "Utrzymaj swoją serię w Hiisi")
 (:email-reminder-cards-due . "fiszek gotowych do powtórki")
 (:email-reminder-keep-going . "Minęło kilka dni od Twojej ostatniej powtórki. Pięć minut dzisiaj wystarczy, aby to, czego się już nauczyłeś, nie wymknęło się z pamięci.")
 (:email-reminder-button . "Powtórz teraz")
 (:email-reminder-settings . "Zarządzaj przypomnieniami")
 (:email-reminder-preview-title . "Fiszki, które na Ciebie czekają")
 (:email-reminder-translation-label . "Tłumaczenie")
 (:email-reminder-more-due-today . "więcej fiszek do powtórki dzisiaj")
 (:email-trial-subject . "Jak idzie Twój okres próbny w Hiisi?")
 (:email-trial-expiring . "Twój bezpłatny okres próbny Hiisi kończy się jutro.")
 (:email-trial-feedback . "Podoba Ci się Hiisi? Powiedz nam, co pomaga Ci najbardziej.")
 (:email-trial-strengths . "Możesz tłumaczyć prawdziwe teksty, zapisywać najlepsze elementy jako fiszki i uczyć się dzięki powtórkom rozłożonym w czasie.")
 (:email-trial-reply . "Odpowiedz na tę wiadomość, a Twoja wiadomość trafi bezpośrednio do zespołu Hiisi.")
 (:email-trial-button . "Wybierz plan")
 (:email-trial-manage . "Zarządzaj subskrypcją")
 (:email-trial-contact . "Napisz do nas")
 (:email-plan-nudge-subject . "Twoje tłumaczenia czekają")
 (:email-plan-nudge-title . "Twoje tłumaczenia czekają")
 (:email-plan-nudge-intro . "Zarejestrowałeś się w Hiisi, ale jeszcze nie wybrałeś planu.")
 (:email-plan-nudge-benefits-intro . "Oto co otrzymujesz w subskrypcji:")
 (:email-plan-nudge-benefit-translations . "600 tłumaczeń miesięcznie z objaśnieniami gramatycznymi")
 (:email-plan-nudge-benefit-flashcards . "Nieograniczone fiszki z powtórkami rozłożonymi w czasie")
 (:email-plan-nudge-benefit-decks . "Własne talie, które możesz organizować i udostępniać")
 (:email-plan-nudge-pricing . "Plany zaczynają się od 10 EUR miesięcznie, a plan roczny kosztuje 100 EUR rocznie (dwa miesiące gratis).")
 (:email-plan-nudge-feedback . "Jeśli coś w Hiisi nie działa dla Ciebie tak, jak powinno, odpowiedz na tę wiadomość. Twoja wiadomość trafi bezpośrednio do zespołu Hiisi.")
 (:email-plan-nudge-button . "Wybierz plan")
 (:email-plan-nudge-unsubscribe . "Wypisz się z tych wiadomości")
 (:email-plan-nudge-unsubscribe-done-title . "Wiadomości o planach wyłączone")
 (:email-plan-nudge-unsubscribe-done-body . "Nie będziesz już otrzymywać wiadomości przypominających o wyborze planu.")
 (:email-plan-nudge-unsubscribe-invalid-title . "Ten link jest nieprawidłowy")
 (:email-plan-nudge-unsubscribe-invalid-body . "Ten link wypisu jest brakujący, wygasł albo nie jest już ważny.")
 (:email-invite-subject . "Zostałeś zaproszony do Hiisi")
 (:email-invite-title . "Zostałeś zaproszony do Hiisi")
 (:email-invite-intro . "Zostałeś zaproszony do korzystania z Hiisi za darmo jako tester, ceniony przyjaciel lub jedno i drugie.")
 (:email-invite-details . "Użyj poniższego przycisku, aby utworzyć konto i zacząć odkrywać tłumaczenia oraz fiszki.")
 (:email-invite-button . "Utwórz konto")
 (:email-invite-issue-reporting . "Jeśli coś się zepsuje lub będzie wydawało się nie tak, na dole każdej strony znajdziesz przycisk zgłaszania problemów.")
 (:email-issue-completed-subject . "Zgłoszony przez Ciebie problem w Hiisi został naprawiony")
 (:email-issue-completed-title . "Problem naprawiony")
 (:email-issue-completed-label . "Problem")
 (:email-issue-completed-followup . "Otwórz Hiisi, aby sprawdzić poprawkę lub kontynuować od miejsca, w którym przerwałeś.")
 (:email-issue-completed-button . "Otwórz Hiisi")
 (:email-issue-completed-open-link . "Otwórz stronę")

 ;; Translation page
 (:translate-title . "Tłumacz")
 (:translate-input-label . "Tekst do przetłumaczenia")
 (:translate-input-placeholder . "Wprowadź tekst do przetłumaczenia...")
 (:translate-example-chip . "Wypróbuj przykład:")
 (:translate-example-sentence . "Zapomniałem kluczy w domu.")
 (:translate-from . "Język źródłowy:")
 (:translate-to . "Język docelowy:")
 (:translate-select-target-placeholder . "Wybierz język docelowy")
 (:translate-submit . "Przetłumacz")
 (:translate-auto-detect . "Dowolny (Autowykrywanie)")
 (:translate-empty-state . "Przetłumacz słowo lub frazę, a tutaj zobaczysz wynik, omówienie gramatyki i działania do nauki.")
 (:translate-select-deck-placeholder . "Wybierz talię (opcjonalnie)")
 (:translate-result-title . "Wynik tłumaczenia")
 (:translate-save-destination-label . "Miejsce zapisu")
 (:translate-save-to-my-cards . "Moje fiszki (domyślnie)")
 (:translate-save-to-deck . "Zapisz w talii")
 (:translate-saved-to-my-cards . "Zapisano w Moje fiszki")
 (:translate-saved-to-deck . "Zapisano w ~A")
 (:translate-view-my-cards . "Zobacz Moje fiszki")
 (:translate-new-deck . "Utwórz nową talię")
 (:translate-add-to-deck . "Dodaj do talii")
 (:translate-feedback-label . "Ocena jakości")
 (:translate-feedback-helpful . "Pomocne")
 (:translate-feedback-helpful-marked . "Oznaczono jako pomocne")
 (:translate-regenerate-translation . "Wygeneruj tłumaczenie ponownie")
 (:translate-regenerate-confirm . "Hiisi oznaczy ten wynik jako niedokładny i wygeneruje nowe tłumaczenie. Kontynuować?")
 (:pronunciation-label . "Wymowa")
 (:pronunciation-show . "Pokaż wymowę")
 (:pronunciation-hide . "Ukryj wymowę")
 (:grammar-term-examples . "Przykłady")
 (:grammar-term-related . "Powiązane pojęcia")
 (:grammar-term-modal-title . "Termin gramatyczny")
 (:grammar-term-empty . "Wybierz wyróżniony termin, aby zobaczyć szczegóły.")
 (:extension-login-required . "Zaloguj się do Hiisi, zanim użyjesz rozszerzenia przeglądarki.")
 (:extension-session-invalid . "Twoja sesja Hiisi nie jest już ważna. Zaloguj się ponownie.")
 (:extension-activation-required . "Aktywuj konto Hiisi, zanim użyjesz rozszerzenia przeglądarki.")
 (:extension-subscription-required . "Rozpocznij okres próbny Hiisi, zanim użyjesz rozszerzenia przeglądarki.")

 ;; Translation and Flashcards
 (:lang-auto . "Auto")
 (:lang-unknown . "?")
 (:lang-target . "Cel")
 (:translate-deck-create-title . "Utwórz nową talię")
 (:translate-deck-name-label . "Nazwa talii")
 (:translate-deck-name-placeholder . "np. Podstawy fińskiego")
 (:translate-deck-description-label . "Opis (opcjonalny)")
 (:translate-deck-cancel . "Anuluj")
 (:translate-deck-create . "Utwórz")
 (:translate-rate-label . "Oceń tłumaczenie")
 (:flashcards-delete . "Usuń")
 (:flashcards-delete-confirm . "Czy na pewno chcesz usunąć tę fiszkę?")
 (:flashcards-deck-search-placeholder . "Szukaj talii...")
 (:flashcards-no-decks . "Brak talii. Utwórz najpierw jedną!")
 (:flashcards-deck-cancel . "Anuluj")
 (:flashcards-recollection-tooltip . "Zapamiętanie: ~A")
 (:flashcards-recollection-poor . "Słabe")
 (:flashcards-recollection-fair . "Umiarkowane")
 (:flashcards-recollection-normal . "Normalne")
 (:flashcards-recollection-strong . "Silne")
 (:flashcards-recollection-very-strong . "Bardzo silne")

 ;; Flashcard review
 (:review-title . "Powtórka")
 (:review-session-title . "Sesja powtórkowa")
 (:review-session-subtitle . "Ćwicz zapisane fiszki")
 (:review-selector-title . "Wybierz, co chcesz powtórzyć")
 (:review-selector-subtitle . "Wybierz talię lub parę językową, na której chcesz skupić sesję powtórkową.")
 (:review-by-deck . "Powtórka według talii")
 (:review-by-language-pair . "Powtórka według pary językowej")
 (:review-all-cards . "Powtórz wszystkie fiszki")
 (:review-cards-due . "kart do powtórki")
 (:review-deck-caught-up . "Wszystko powtórzone")
 (:review-all-caught-up . "Wszystko powtórzone!")

 (:review-no-cards . "Brak fiszek do powtórki")
 (:review-no-cards-desc . "Nie masz teraz żadnych fiszek do powtórki.")
 (:review-no-cards-hint . "Przetłumacz tekst i kliknij \"Zapisz do fiszek\", aby zbudować swoją talię!")
 (:review-start-translating . "Zacznij tłumaczyć")
 (:review-click-reveal . "Kliknij, aby odsłonić odpowiedź")
 (:review-grammar-breakdown . "Rozkład gramatyczny")
 (:review-how-well . "Czy udało Ci się przypomnieć?")
 (:review-again . "Nie")
 (:review-hard . "Z trudem")
 (:review-good . "Tak")
 (:review-easy . "Łatwo")
 (:review-progress . "Fiszka ~a z ~a")
 (:review-correct-count . "Poprawne")
 (:review-wrong-count . "Błędne")
 (:landing-mockup-forgot-detail . "1. osoba liczby pojedynczej czasu przeszłego \"olvidar\" (zapomnieć)")
 (:landing-mockup-keys-detail . "Zaimek dzierżawczy \"mis\" z rzeczownikiem żeńskim w liczbie mnogiej \"llaves\" (klucze)")
 (:review-complete . "Sesja zakończona!")
 (:review-complete-msg . "Powtórzyłeś ~a fiszek")
 (:review-again-btn . "Powtórz ponownie")
 (:review-translate-more . "Tłumacz więcej")
 (:review-streak . "dni z rzędu")

 ;; Dashboard
 (:dashboard-title . "Panel")
 (:dashboard-welcome-title . "Przetłumacz swój pierwszy tekst")
 (:dashboard-welcome-subtitle . "Przetłumacz przydatną frazę, zapisz ją w talii i powtórz, gdy będzie to ważne.")
 (:dashboard-take-quick-tour . "Szybki przewodnik")
 (:dashboard-cards-due . "Fiszki na dziś")
 (:dashboard-total-cards . "Wszystkie fiszki")
 (:dashboard-mastered-cards . "Opanowanych fiszek")
 (:dashboard-subscription . "Subskrypcja")
 (:dashboard-subscribed-until . "Subskrypcja do")
 (:dashboard-trial-ends . "Koniec okresu próbnego")
 (:dashboard-not-subscribed . "Brak subskrypcji")
 (:dashboard-recent . "Ostatnie tłumaczenia")
 (:dashboard-no-translations . "Brak tłumaczeń")
 (:dashboard-streak . "Seria powtórek")
 (:dashboard-days . "dni")
 (:dashboard-all-caught-up . "Wszystko nadrobione!")
 (:dashboard-all-caught-up-hint . "Tłumacz więcej, aby rozbudować swoją kolekcję.")
 (:dashboard-no-cards-title . "Utwórz pierwsze fiszki do nauki")
 (:dashboard-no-cards-hint . "Przetłumacz tekst i zapisz przydatne zwroty, aby zbudować swoją kolekcję.")
 (:dashboard-first-use-checklist-title . "Pierwsze kroki")
 (:dashboard-first-use-checklist-translate . "Wykonaj pierwsze tłumaczenie")
 (:dashboard-first-use-checklist-card . "Zapisz pierwszą fiszkę")
 (:dashboard-first-use-checklist-review . "Ukończ pierwszą powtórkę")
 (:dashboard-getting-started . "Jak zacząć")
 (:dashboard-tip-1 . "Tłumacz tekst, którego chcesz się nauczyć")
 (:dashboard-tip-2 . "Kliknij \"Zapisz do fiszek\" przy tłumaczeniach, które chcesz zapamiętać")
 (:dashboard-tip-3 . "Regularnie powtarzaj fiszki - powtórki rozłożone w czasie pomagają zapamiętać na dłużej")
 (:dashboard-tip-4 . "Oceniaj szczerze - pomaga to algorytmowi optymalnie planować powtórki")

 ;; Account
 (:account-title . "Konto")
 (:account-subtitle . "Zarządzaj tutaj profilem, subskrypcją, przypomnieniami, eksportem i usunięciem konta.")
 (:account-profile-subtitle . "Dbaj o aktualność swojej nazwy wyświetlanej i adresu e-mail.")
 (:account-export-subtitle . "Pobierz kopię zapisanych tłumaczeń, talii i historii powtórek.")
 (:account-deletion-title . "Usunięcie konta")
 (:account-deletion-scheduled . "Twoje konto jest zaplanowane do usunięcia na ~A.")
 (:account-deletion-cancel-hint . "Możesz anulować przed tą datą, aby zachować konto.")
 (:account-deletion-cancel . "Anuluj usunięcie")
 (:account-deletion-request . "Możesz poprosić o usunięcie konta w dowolnym momencie. Usunięcie jest zaplanowane 14 dni po potwierdzeniu. Jeśli zmienisz zdanie, skontaktuj się z pomocą przed upływem tych 14 dni.")
 (:account-deletion-confirm . "Zaplanować usunięcie konta za 14 dni od dziś?")
 (:account-deletion-schedule . "Zaplanuj usunięcie")
 (:account-reminders-title . "Przypomnienia e-mail")
 (:account-reminders-subtitle . "Wybierz, czy Hiisi może wysyłać Ci e-maile, gdy czeka na Ciebie coś do powtórki.")
 (:account-reminders-opt-out . "Wyłącz przypomnienia o powtórkach i kontynuacji")
 (:account-reminders-save . "Zapisz preferencje")

 ;; Subscription
 (:subscribe-title . "Prosty cennik")
 (:subscribe-choose-plan . "Wybierz swój plan")
 (:subscribe-start-today . "Zacznij naukę już dziś z 14-dniowym bezpłatnym okresem próbnym")
 (:subscribe-monthly . "Miesięczny")
 (:subscribe-annual . "Roczny")
 (:subscribe-founder-member . "Członek założyciel")
 (:subscribe-monthly-price . "€10")
 (:subscribe-annual-price . "€100")
 (:subscribe-founder-price . "€79")
 (:subscribe-founder-monthly-equivalent . "€6,58/miesiąc, płatne rocznie")
 (:subscribe-founder-savings . "Oszczędzasz €41/rok względem płatności miesięcznej")
 (:subscribe-monthly-billing-equivalent . "€10/miesiąc, płatne co miesiąc")
 (:subscribe-monthly-billing-note . "Elastyczna płatność miesięczna")
 (:subscribe-per-month . "/miesiąc")
 (:subscribe-per-year . "/rok")
 (:subscribe-monthly-desc . "600 tłumaczeń miesięcznie. Nieograniczone fiszki, talie i powtórki.")
 (:subscribe-unlimited-flashcards . "Nieograniczona liczba fiszek")
 (:subscribe-grammar-explanations . "Wyjaśnienia gramatyczne")
 (:subscribe-spaced-repetition . "Powtórki rozłożone w czasie")
 (:subscribe-annual-desc . "Wszystko z planu miesięcznego. Dwa miesiące gratis.")
 (:subscribe-founder-lock . "Cena pozostaje taka sama, dopóki subskrypcja pozostaje aktywna.")
 (:subscribe-founder-badge . "Oferta ograniczona")
 (:subscribe-founder-limit . "Ograniczone do pierwszych 100 członków")
 (:subscribe-manage . "Zarządzaj subskrypcją")
 (:subscribe-activated . "Subskrypcja aktywowana!")
 (:subscribe-thank-you . "Twoja subskrypcja jest aktywna. Tutaj możesz zarządzać płatnościami i kupić więcej tłumaczeń.")
 (:subscribe-start-learning . "Rozpocznij naukę")
 (:subscribe-management . "Zarządzanie subskrypcją")
 (:subscribe-active . "Aktywna subskrypcja")
 (:subscribe-preapproved-access . "Wstępnie zatwierdzony dostęp")
 (:subscribe-status . "Status:")
 (:subscribe-status-active . "Aktywna")
 (:subscribe-status-preapproved . "Wstępnie zatwierdzony")
 (:subscribe-preapproved-detail . "To konto korzysta ze wstępnie zatwierdzonego dostępu zarządzanego przez Hiisi.")
 (:subscribe-days-remaining . "Pozostało dni:")
 (:subscribe-renews-on . "Odnawia się:")
 (:subscribe-no-subscription . "Brak aktywnej subskrypcji")
 (:subscribe-access-features . "Wybierz plan, aby odblokować pełny dostęp i zarządzać płatnościami w jednym miejscu.")
 (:subscribe-view-plans . "Zobacz plany")
 (:subscribe-faq-title . "Najczęściej zadawane pytania")
 (:subscribe-faq-trial-q . "Co się dzieje po zakończeniu bezpłatnego okresu próbnego?")
 (:subscribe-faq-trial-a . "14-dniowy okres próbny nie wymaga karty. Po jego zakończeniu wybierz płatny plan, aby zachować pełny dostęp.")
 (:subscribe-faq-cancel-q . "Czy mogę anulować w dowolnym momencie?")
 (:subscribe-faq-cancel-a . "Tak! Możesz anulować subskrypcję w dowolnym momencie. Zachowasz dostęp do końca okresu rozliczeniowego.")
 (:subscribe-faq-payment-q . "Jakie metody płatności akceptujecie?")
 (:subscribe-faq-payment-a . "Akceptujemy wszystkie główne karty kredytowe i debetowe za pośrednictwem naszego partnera płatniczego Polar.sh.")
 (:subscribe-copyright . "Lambda Symbolics OÜ © 2026.")
(:subscribe-checkout-unavailable . "Proces płatności jest tymczasowo niedostępny. Spróbuj ponownie.")
(:subscribe-portal-unavailable . "Zarządzanie subskrypcją jest tymczasowo niedostępne. Spróbuj ponownie.")
(:subscribe-founder-sold-out . "Oferta dla członków założycieli jest wyprzedana")
(:subscribe-founder-unavailable . "Oferta dla członków założycieli jest obecnie niedostępna.")
(:subscribe-checkout-cta . "Subskrybuj")

 ;; Errors and status
 (:error-generic . "Coś poszło nie tak")
(:error-invalid-request . "Nieprawidłowe dane żądania.")
(:error-not-found . "Nie znaleziono żądanego zasobu.")
(:error-forbidden . "Nie masz do tego dostępu.")
(:error-rate-limited . "Odczekaj chwilę i spróbuj ponownie.")
 (:error-text-too-long . "Tekst jest za długi. Maksymalna długość tłumaczenia to 120 znaków.")
 (:error-input-too-long . "Tekst za długi")
 (:error-unknown-source-lang . "Wybrany język źródłowy nie jest obsługiwany.")
 (:error-unknown-target-lang . "Wybrany język docelowy nie jest obsługiwany.")
 (:error-unknown-language . "Nieznany język")
 (:error-translation-unavailable . "Usługa tłumaczenia jest chwilowo niedostępna. Spróbuj ponownie za chwilę.")
 (:error-translation-failed . "Tłumaczenie nie powiodło się")
 (:error-translation-retry . "Nie udało się wygenerować tłumaczenia po wielu próbach. Spróbuj przeformułować tekst.")
 (:error-quota-exceeded . "Osiągnięto limit tłumaczeń")
 (:error-quota-exceeded-detail . "Wykorzystałeś wszystkie tłumaczenia na ten miesiąc. Twój limit odnawia się automatycznie co miesiąc.")
 (:quota-low-warning . "Zostało tylko ~A tłumaczeń. Rozważ zakup większej ilości.")
 (:top-up-button . "Kup więcej tłumaczeń")
 (:top-up-price . "5 €")
 (:top-up-amount . "300 tłumaczeń")
(:review-session-expired . "Sesja powtórek wygasła. Rozpocznij nową sesję.")

 (:error-session-expired . "Twoja sesja wygasła. Zaloguj się ponownie.")
 (:error-session-invalid . "Twoja sesja nie jest już ważna. Zaloguj się ponownie.")
 (:error-custom-flashcard-generation . "Nie udało się wygenerować wyjaśnienia. Spróbuj ponownie.")
 ;; Institutions
 (:institutions-page-title . "Hiisi dla szkół i uniwersytetów")
 (:institutions-hero-title . "Narzędzia do nauczania języków stworzone z myślą o klasie")
 (:institutions-hero-subtitle . "Daj swoim uczniom i studentom udostępnialne talie, ćwiczenia uwzględniające gramatykę i stały rytm powtórek, który pasuje do prawdziwego nauczania.")
 (:institutions-section-title . "Dlaczego instytucje wybierają Hiisi")
 (:institutions-section-body . "Hiisi pomaga nauczycielom zamieniać materiały z lekcji w prowadzone ćwiczenia, za którymi uczniowie naprawdę nadążają. Twórz talie dla kursu, udostępniaj je linkiem i wspieraj pracę nad słownictwem oraz gramatyką bez dodatkowego obciążenia administracyjnego.")
 (:institutions-benefit-1 . "Udostępnialne talie i własne zadania dopasowane do waszego programu nauczania.")
 (:institutions-benefit-2 . "Polubienia i odrzucenia studentów pomagają wynosić najlepsze tłumaczenia dla częstych zwrotów z klasy.")
 (:institutions-benefit-3 . "Rozbicia gramatyczne i powtórki w odstępach wspierają znacznie więcej niż samo zapamiętywanie oderwanych list słów.")
 (:institutions-benefit-4 . "Wsparcie z perspektywy nauczyciela od osoby, która uważnie słucha i naprawdę dba o potrzeby klasy.")
 (:institutions-request-title . "Porozmawiajmy")
 (:institutions-request-subtitle . "Napisz nam o swojej instytucji, językach i rodzaju wsparcia dydaktycznego, którego potrzebujecie. Odpowiemy w ciągu tygodnia.")
 (:institutions-aside-title . "Co dalej")
 (:institutions-aside-body . "Zapoznajemy się z waszymi potrzebami i odpowiadamy w ciągu tygodnia, aby omówić dostęp i konfigurację dla waszej instytucji.")
 (:institutions-field-name . "Nazwa instytucji")
 (:institutions-field-name-placeholder . "Twój uniwersytet")
 (:institutions-field-contact-name . "Imię i nazwisko kontaktowe")
 (:institutions-field-contact-name-placeholder . "Twoje imię")
 (:institutions-field-contact-email . "E-mail kontaktowy")
 (:institutions-field-contact-email-placeholder . "ty@uniwersytet.pl")
 (:institutions-field-domains . "Domeny e-mail")
 (:institutions-field-domains-placeholder . "uniwersytet.pl, cs.uniwersytet.pl")
 (:institutions-field-domains-help . "Lista domen e-mail Twojej instytucji oddzielona przecinkami")
 (:institutions-field-notes . "Dodatkowe informacje")
 (:institutions-field-notes-placeholder . "Szacowana liczba studentów, preferowany cykl rozliczeniowy, specjalne wymagania...")
 (:institutions-submit . "Wyślij zapytanie")
 (:institutions-success-title . "Dziękujemy - Hiisi dla szkół i uniwersytetów")
 (:institutions-success-heading . "Dziękujemy!")
 (:institutions-success-body . "Otrzymaliśmy wasze zapytanie. Przeanalizujemy potrzeby instytucji i skontaktujemy się w ciągu tygodnia.")
 (:institutions-success-back . "Wróć na stronę główną")

 ;; Footer
 (:footer-privacy . "Polityka prywatności")
 (:footer-terms . "Regulamin")

 ;; Early software notice
 (:early-software-notice . "Hiisi jest we wczesnej fazie rozwoju. Znalazłeś błąd lub masz sugestię?")

 ;; Polityka prywatności
 (:privacy-title . "Polityka prywatności")
 (:privacy-updated . "Ostatnia aktualizacja: styczeń 2026")
 (:privacy-who-title . "Kim jesteśmy")
 (:privacy-who-body . "Hiisi jest obsługiwane przez Lambda Symbolics OÜ, spółkę zarejestrowaną w Estonii. Jako estońska firma przestrzegamy ogólnego rozporządzenia o ochronie danych (GDPR) Unii Europejskiej.")
 (:privacy-collect-title . "Dane, które zbieramy")
 (:privacy-collect-intro . "Podczas korzystania z Hiisi zbieramy następujące informacje:")
 (:privacy-collect-account-key . "Informacje o koncie: ")
 (:privacy-collect-account-val . "Adres e-mail, nazwa wyświetlana oraz bezpiecznie haszowane hasło.")
 (:privacy-collect-learning-key . "Dane o nauce: ")
 (:privacy-collect-learning-val . "Twoje tłumaczenia, zapisane fiszki i historia powtórek.")
 (:privacy-collect-usage-key . "Dane użycia: ")
 (:privacy-collect-usage-val . "Podstawowe logi serwera do celów bezpieczeństwa i debugowania.")
 (:privacy-use-title . "Jak wykorzystujemy Twoje dane")
 (:privacy-use-auth-key . "Uwierzytelnianie: ")
 (:privacy-use-auth-val . "Aby potwierdzić Twoją tożsamość i zabezpieczyć konto.")
 (:privacy-use-service-key . "Świadczenie usługi: ")
 (:privacy-use-service-val . "Aby dostarczać tłumaczenia i zarządzać Twoją kolekcją fiszek.")
 (:privacy-use-ai-key . "Tłumaczenia AI: ")
 (:privacy-use-ai-val . "Twoje żądania tłumaczenia są wysyłane do OpenRoutera w celu wygenerowania odpowiedzi. OpenRouter może kierować żądania do skonfigurowanego dostawcy modelu. Zobacz politykę prywatności OpenRoutera, aby dowiedzieć się, jak przetwarza te dane.")
 (:privacy-third-title . "Usługi stron trzecich")
 (:privacy-third-intro . "Korzystamy z następujących usług stron trzecich:")
 (:privacy-third-openrouter-key . "OpenRouter: ")
 (:privacy-third-openrouter-val . "Do automatycznych żądań tłumaczenia.")
 (:privacy-third-clankermails-key . "ClankerMails: ")
 (:privacy-third-clankermails-val . "Do wysyłania e-maili aktywacyjnych i transakcyjnych.")
 (:privacy-third-polar-key . "Polar.sh: ")
 (:privacy-third-polar-val . "Do przetwarzania płatności subskrypcyjnych.")
 (:privacy-cookies-title . "Pliki cookie")
 (:privacy-cookies-intro . "Używamy wyłącznie niezbędnych plików cookie:")
 (:privacy-cookies-auth-key . "Token uwierzytelniania: ")
 (:privacy-cookies-auth-val . "Bezpieczny plik cookie HTTP-only, który utrzymuje zalogowanie.")
 (:privacy-cookies-lang-key . "Preferencja języka: ")
 (:privacy-cookies-lang-val . "Aby zapamiętać preferowany język interfejsu.")
 (:privacy-retention-title . "Przechowywanie danych")
 (:privacy-retention-body . "Twoje dane są przechowywane tak długo, jak utrzymujesz konto. Gdy poprosisz o usunięcie, Twoje konto zostanie zaplanowane do usunięcia za 14 dni.")
 (:privacy-rights-title . "Twoje prawa (GDPR)")
 (:privacy-rights-intro . "Zgodnie z GDPR masz prawo do:")
 (:privacy-rights-access . "Dostępu do swoich danych osobowych")
 (:privacy-rights-export . "Eksportu swoich danych (dostępny pod adresem /app/api/export)")
 (:privacy-rights-correct . "Żądania sprostowania nieprawidłowych danych")
 (:privacy-rights-delete . "Żądania usunięcia konta i danych")
 (:privacy-rights-object . "Sprzeciwu wobec przetwarzania swoich danych")
 (:privacy-rights-contact . "Aby skorzystać z tych praw, skontaktuj się z nami pod adresem")
 (:privacy-contact-title . "Kontakt")
 (:privacy-contact-intro . "W sprawach związanych z prywatnością:")
 (:privacy-contact-email-label . "E-mail: ")
 (:privacy-address-1 . "Lambda Symbolics OÜ")
 (:privacy-address-2 . "Harju maakond, Tallinn, Kesklinna linnaosa, Tornimäe tn 5, 10145")

 ;; Warunki korzystania z usługi
 (:terms-title . "Warunki korzystania z usługi")
 (:terms-updated . "Ostatnia aktualizacja: styczeń 2026")
 (:terms-1-title . "1. Opis usługi")
 (:terms-1-body . "Hiisi to aplikacja do nauki języków oferująca automatyczne tłumaczenia z wyjaśnieniami gramatycznymi oraz fiszki z rozłożonymi powtórkami. Usługa jest obsługiwana przez Lambda Symbolics OÜ.")
 (:terms-2-title . "2. Rejestracja konta")
 (:terms-2-body . "Aby korzystać z Hiisi, musisz utworzyć konto z prawidłowym adresem e-mail. Odpowiadasz za bezpieczeństwo danych logowania do konta.")
 (:terms-3-title . "3. Subskrypcja i płatności")
 (:terms-3-body . "Hiisi oferuje płatne plany subskrypcji (miesięczny i roczny). Subskrypcje są przetwarzane przez Polar.sh.")
 (:terms-3-list-1 . "Subskrypcje odnawiają się automatycznie, jeśli nie zostaną anulowane przed datą odnowienia.")
 (:terms-3-list-2 . "Zwroty są realizowane zgodnie z obowiązującymi przepisami ochrony konsumentów.")
 (:terms-3-list-3 . "Brak płatności powoduje utratę dostępu do funkcji premium.")
 (:terms-4-title . "4. Dozwolone użycie")
 (:terms-4-intro . "Zgadzasz się, że nie będziesz:")
 (:terms-4-list-1 . "Używać usługi do celów niezgodnych z prawem")
 (:terms-4-list-2 . "Próbować obchodzić limitów użycia ani zabezpieczeń")
 (:terms-4-list-3 . "Udostępniać danych logowania do konta innym osobom")
 (:terms-4-list-4 . "Używać narzędzi automatycznych w sposób pogarszający wydajność usługi dla innych")
 (:terms-5-title . "5. Treści i własność intelektualna")
 (:terms-5-body-1 . "Tłumaczenia generowane przez Hiisi są tworzone automatycznie i mogą nie być unikalne. Możesz używać swoich tłumaczeń i fiszek do celów osobistych, ale nie przysługują Ci wyłączne prawa autorskie do treści generowanych automatycznie.")
 (:terms-5-body-2 . "Aplikacja Hiisi, marka i oryginalne treści pozostają własnością Lambda Symbolics OÜ.")
 (:terms-6-title . "6. Dostępność usługi")
 (:terms-6-intro . "Hiisi jest dostarczane w stanie takim, jaki jest. Nie gwarantujemy:")
 (:terms-6-list-1 . "Nieprzerwanej i bezbłędnej pracy usługi")
 (:terms-6-list-2 . "Dokładności automatycznie generowanych tłumaczeń")
 (:terms-6-list-3 . "Dostępności określonych funkcji")
 (:terms-6-body . "Możemy modyfikować lub wycofywać funkcje w dowolnym momencie.")
 (:terms-7-title . "7. Ograniczenie odpowiedzialności")
 (:terms-7-body-1 . "W maksymalnym zakresie dozwolonym przez prawo Lambda Symbolics OÜ nie ponosi odpowiedzialności za szkody pośrednie, przypadkowe, szczególne ani wtórne wynikające z korzystania z Hiisi.")
 (:terms-7-body-2 . "Nasza łączna odpowiedzialność nie przekroczy kwoty zapłaconej przez Ciebie za usługę w ciągu 12 miesięcy poprzedzających roszczenie.")
 (:terms-8-title . "8. Zakończenie konta")
 (:terms-8-body-1 . "Możemy zawiesić lub zakończyć Twoje konto, jeśli naruszysz te warunki. W dowolnym momencie możesz zażądać usunięcia konta w aplikacji.")
 (:terms-8-body-2 . "Po zgłoszeniu usunięcia Twoje konto zostanie zaplanowane do usunięcia za 14 dni.")
 (:terms-9-title . "9. Zmiany warunków")
 (:terms-9-body . "Możemy okresowo aktualizować te warunki. Dalsze korzystanie z Hiisi po zmianach oznacza akceptację nowych warunków.")
 (:terms-10-title . "10. Prawo właściwe")
 (:terms-10-body . "Niniejsze warunki podlegają prawu Estonii. Wszelkie spory będą rozstrzygane przez sądy Estonii.")
 (:terms-contact-title . "Kontakt")
 (:terms-contact-intro . "W razie pytań dotyczących tych warunków:")
 (:terms-contact-email-label . "E-mail: ")
 (:terms-address-1 . "Lambda Symbolics OÜ")
 (:terms-address-2 . "Harju maakond, Tallinn, Kesklinna linnaosa, Tornimäe tn 5, 10145")

 ;; Decks
 (:decks-title . "Talie")
 (:decks-subtitle . "Twórz własne talie i udostępniaj je innym.")
 (:decks-create-title . "Utwórz talię")
 (:decks-name-placeholder . "Nazwa talii")
 (:decks-desc-placeholder . "Opis")
 (:decks-create-btn . "Utwórz talię")
 (:decks-edit-title . "Edytuj talię")
 (:decks-edit-btn . "Edytuj talię")
 (:decks-actions-title . "Akcje talii")
 (:decks-card-actions-title . "Akcje karty")
 (:decks-update-btn . "Zapisz zmiany")
 (:decks-default-badge . "Automatyczna")
 (:decks-default-description . "Ta talia jest zarządzana automatycznie dla tej pary języków.")
 (:decks-default-readonly . "Automatyczne talie mają stałe nazwy i opisy.")
 (:decks-delete-btn . "Usuń talię")
 (:decks-delete-confirm . "Czy na pewno chcesz usunąć tę talię?")
 (:decks-error-name-required . "Nazwa talii jest wymagana.")
 (:decks-error-name-too-long . "Nazwa talii może mieć maksymalnie ~A znaków.")
 (:decks-error-desc-too-long . "Opis talii może mieć maksymalnie ~A znaków.")
 (:decks-error-default-readonly . "Talii automatycznych nie można edytować.")
 (:decks-error-default-delete-forbidden . "Talii automatycznych nie można usuwać.")
 (:decks-your-title . "Twoje talie")
 (:decks-col-updated . "Zaktualizowano")
 (:decks-no-decks . "Brak talii.")
 (:decks-open-btn . "Otwórz")
 (:decks-view-deck-btn . "Zobacz talię")
 (:decks-start-review . "Rozpocznij powtórkę")
 (:decks-no-desc . "Brak opisu.")
 (:decks-share-title . "Link do udostępnienia")
 (:decks-share-info . "Każdy z tym linkiem może zaimportować talię:")
 (:decks-share-copy . "Kopiuj link")
 (:decks-share-copied . "Skopiowano")
 (:decks-add-from-flashcards-title . "Dodaj fiszki")
 (:decks-add-from-flashcards-info . "Wybierz fiszkę, aby dodać jej tłumaczenie do tej talii.")
 (:decks-create-new-flashcard . "Utwórz nową fiszkę")
 (:decks-open-flashcards . "Dodaj istniejące fiszki")
 (:decks-filter-from . "Język źródłowy")
 (:decks-filter-to . "Język docelowy")
 (:decks-filter-any . "Dowolny język")
 (:decks-filter-include-assigned . "Uwzględnij fiszki, które są już w talii")
 (:decks-flashcards-add . "Dodaj")
 (:decks-flashcards-added . "Dodano")
 (:decks-flashcards-in-deck . "W innej talii")
 (:decks-flashcards-empty . "Brak fiszek spełniających te filtry.")
 (:decks-items-title . "Zawartość talii")
 (:decks-col-original . "Oryginał")
 (:decks-col-translated . "Tłumaczenie")
 (:decks-col-lang . "Język docelowy")
 (:decks-no-items . "Brak elementów.")
 (:decks-share-page-title . "Udostępnij talię")
 (:decks-share-preview . "Podgląd i import tej talii.")
 (:decks-import-title . "Importuj")
 (:decks-import-btn . "Importuj talię")
 (:starter-decks-title . "Biblioteka")
 (:starter-decks-subtitle . "Importuj gotowe talie od Hiisi i społeczności.")
 (:starter-decks-marketplace-btn . "Biblioteka")
 (:starter-decks-explanation-language . "Język objaśnień")
 (:starter-decks-search-label . "Szukaj")
 (:starter-decks-source-label . "Źródło")
 (:starter-decks-source-all . "Wszystkie talie")
 (:starter-decks-change-language . "Zmień")
 (:starter-decks-filters-button . "Filtry")
 (:starter-decks-search-placeholder . "Szukaj w bibliotece")
 (:starter-decks-apply-filters . "Zastosuj filtry")
 (:starter-decks-select-triplet-hint . "Wybierz język źródłowy i docelowy, aby przeglądać pasujące talie.")
 (:starter-decks-official-badge . "Oficjalna")
 (:starter-decks-official-by-hiisi . "Oficjalne od Hiisi")
 (:starter-decks-community-badge . "Społeczność")
 (:starter-decks-by-hiisi . "Od Hiisi")
 (:starter-decks-preview-btn . "Podgląd")
 (:starter-decks-card-count . "~A kart")
 (:starter-decks-no-results . "Żadne talie nie pasują do tych filtrów.")
 (:starter-decks-source-cards-title . "Karty w tej talii")
 (:starter-decks-more-cards-included . "+~A dodatkowych kart w zestawie.")
 (:starter-decks-sample-title . "Karty przykładowe")
 (:starter-decks-generating . "Przygotowujemy Twoją talię ~A")
 (:starter-decks-generating-detail . "Zaimportujemy ją, gdy tylko będzie gotowa. Możesz dalej przeglądać Bibliotekę albo wrócić za chwilę.")
 (:starter-decks-generation-failed . "Tworzenie nie powiodło się")
 (:starter-decks-generation-failed-detail . "Ostatnia próba utworzenia nie powiodła się. Spróbuj ponownie zaimportować talię.")
 (:starter-decks-login-detail . "Zaloguj się, aby zaimportować tę talię do swojej kolekcji.")
 (:starter-decks-subscribe-btn . "Zobacz plany")
 (:starter-decks-subscribe-detail . "Talie z biblioteki są dostępne w ramach aktywnej subskrypcji lub okresu próbnego.")
 (:library-submit-title . "Wyślij do biblioteki")
 (:library-submit-intro . "Wyślij tę talię do biblioteki do przeglądu administracyjnego przed publikacją.")
 (:library-submit-btn . "Wyślij talię")
 (:library-submit-approved . "Zatwierdzono do biblioteki")
 (:library-submit-approved-detail . "Ta talia jest opublikowana w bibliotece.")
 (:library-submit-pending . "W trakcie przeglądu")
 (:library-submit-pending-detail . "Ta talia została wysłana i czeka na przegląd administracyjny.")
 (:library-submit-rejected . "Wymaga zmian przed publikacją")
 (:library-submit-rejected-detail . "To zgłoszenie zostało odrzucone. Zaktualizuj talię i wyślij ją ponownie.")
 (:library-error-empty . "Dodaj co najmniej jedną kartę, zanim wyślesz tę talię do biblioteki.")
 (:library-error-missing-triplet . "Każda karta w zgłoszeniu do biblioteki musi mieć pełną trójkę językową.")
 (:library-error-mixed-triplet . "Wszystkie karty w zgłoszeniu do biblioteki muszą mieć tę samą trójkę językową.")
 (:starter-deck-topic-greetings-title . "Powitania i przedstawianie się")
 (:starter-deck-topic-greetings-description . "Powitania, imiona, uprzejme podstawy i zwroty na pierwsze spotkanie.")
 (:starter-deck-topic-travel-title . "Podstawy podróżowania")
 (:starter-deck-topic-travel-description . "Dworce, bilety, ceny, proszenie o pomoc i poruszanie się.")
 (:starter-deck-topic-numbers-title . "Liczby i ceny")
 (:starter-deck-topic-numbers-description . "Liczenie, sumy, ceny, piętra i codzienne ilości.")
 (:starter-deck-topic-time-title . "Czas i daty")
 (:starter-deck-topic-time-description . "Dni, miesiące, spotkania, godziny i daty względne.")
 (:starter-deck-topic-food-title . "Restauracja i jedzenie")
 (:starter-deck-topic-food-description . "Zamawianie, potrzeby dietetyczne, napoje, rachunek i codzienne posiłki poza domem.")
 (:starter-deck-topic-emergency-title . "Nagłe sytuacje i zdrowie")
 (:starter-deck-topic-emergency-description . "Lekarze, apteki, objawy, części ciała i pilna pomoc.")
 (:starter-deck-topic-directions-title . "Wskazywanie drogi i transport")
 (:starter-deck-topic-directions-description . "Skręcanie, przystanki, bilety, perony i poruszanie się po mieście.")
 (:starter-deck-topic-school-title . "Szkoła i edukacja")
 (:starter-deck-topic-school-description . "Lekcje, zadania domowe, egzaminy, przybory szkolne i codzienne życie w szkole.")
 (:starter-deck-topic-university-title . "Uniwersytet i studia")
 (:starter-deck-topic-university-description . "Wykłady, seminaria, kierunki, prace zaliczeniowe i codzienne życie na kampusie.")

 ;; Flashcards management page
 (:flashcards-title . "Moje fiszki")
 (:flashcards-subtitle . "Wszystkie zapisane fiszki w jednym miejscu. Szukaj, organizuj i zarządzaj.")
 (:flashcards-search-placeholder . "Szukaj fiszek...")
 (:flashcards-filter-button . "Filtry")
 (:flashcards-filter-title . "Filtruj fiszki")
 (:flashcards-filter-recollection . "Jak dobrze je znasz")
 (:flashcards-filter-any-recollection . "Dowolny poziom")
 (:flashcards-hide-perfected . "Ukryj opanowane fiszki")
 (:flashcards-col-original . "Oryginał")
 (:flashcards-col-translated . "Tłumaczenie")
 (:flashcards-no-cards . "Brak fiszek. Zacznij tłumaczyć, aby je utworzyć!")
 (:flashcards-no-filtered-cards . "Żadne fiszki nie pasują jeszcze do tych filtrów. Zacznij tłumaczyć, aby je utworzyć!")
 (:flashcards-image-label . "Obraz")
 (:flashcards-image-upload . "Prześlij obraz")
 (:flashcards-image-replace . "Zastąp obraz")
 (:flashcards-image-remove . "Usuń obraz")
 (:flashcards-pagination-label . "Strony fiszek")
 (:flashcards-pagination-status . "Strona ~A z ~A")
 (:flashcards-pagination-previous . "Poprzednia")
 (:flashcards-pagination-next . "Następna")

 ;; Landing page (redesign)
 (:landing-hero-headline-v1 . "Łatwo tłumacz zdania i czytaj gramatykę w swoim języku.")
 (:landing-hero-headline-v2 . "Hiisi pilnuje, żeby każde przetłumaczone zdanie nie zniknęło z pamięci.")
 (:landing-hero-headline-v3 . "Zamień tłumaczone zdania w słownictwo, którego potrafisz używać.")
 (:landing-hero-subheadline . "Dodaj dowolne zdanie do zakładek, a Hiisi poda tłumaczenie, gramatykę, wymowę i fiszkę, która wróci do powtórki.")
 (:landing-hero-trust-line . "14 dni za darmo. Karta nie jest wymagana.")

 ;; Trial status (in-app)
 (:trial-status . "Darmowy okres próbny")
 (:error-trial-quota-exceeded . "Osiągnięto limit próbnych tłumaczeń")
 (:error-trial-quota-detail . "Wykorzystałeś wszystkie 200 próbnych tłumaczeń. Zasubskrybuj, aby kontynuować naukę.")

 ;; Custom flashcards
 (:custom-flashcard-create-title . "Utwórz fiszkę")
 (:custom-flashcard-edit-title . "Edytuj fiszkę")
 (:custom-flashcard-original . "Oryginalny tekst")
 (:custom-flashcard-translated . "Tłumaczenie")
 (:custom-flashcard-lang-from . "Język źródłowy")
 (:custom-flashcard-lang-to . "Język docelowy")
 (:custom-flashcard-note . "Notatka edukacyjna")
 (:custom-flashcard-forms . "Analiza gramatyczna")
 (:custom-flashcard-form-term . "Termin")
 (:custom-flashcard-form-explanation . "Wyjaśnienie")
 (:custom-flashcard-add-form . "Dodaj termin gramatyczny")
 (:custom-flashcard-remove-form . "Usuń")
 (:custom-flashcard-ai-fill . "Wypełnij za pomocą AI")
 (:custom-flashcard-create-btn . "Utwórz fiszkę")
 (:custom-flashcard-update-btn . "Zapisz zmiany")

  ;; Newsletter
  (:newsletter-email-label . "Adres e-mail")
  (:newsletter-developer-label . "Jestem programistą")
  (:newsletter-developer-hint . "otrzymuj aktualizacje techniczne")
  (:landing-newsletter-title . "Otrzymuj aktualizacje Hiisi.")
  (:landing-newsletter-body . "Zapisz się do newslettera, aby otrzymywać informacje o produkcie, obsłudze nowych języków, taliach startowych i okazjonalnych ofertach dla członków założycieli.")
  (:landing-newsletter-fine-print . "Bez spamu. Tylko informacje o produkcie.")
  (:landing-newsletter-button . "Zapisz się do newslettera")
  (:newsletter-unsubscribe-page-title . "Wypisz się z newslettera Hiisi")
  (:newsletter-unsubscribe-title . "Wypisz się")
  (:newsletter-unsubscribe-subtitle . "Wpisz swój e-mail, aby przestać otrzymywać aktualizacje Hiisi.")
  (:newsletter-unsubscribe-button . "Wypisz się")
  (:newsletter-feedback-email-required . "Wpisz swój adres e-mail.")
  (:newsletter-feedback-email-invalid . "Wpisz prawidłowy adres e-mail.")
  (:newsletter-feedback-already-signed-up . "Jesteś już zapisany. Będziemy informować!")
  (:newsletter-feedback-signed-up . "Jesteś na liście! Będziemy wysyłać okazjonalne informacje o Hiisi.")
  (:newsletter-feedback-unsubscribed . "Jeśli ten e-mail był zapisany, został usunięty z aktualizacji Hiisi.")
  (:newsletter-feedback-generic-error . "Coś poszło nie tak. Spróbuj ponownie.")

  ;; Issue reporting
  (:issues-open-button . "Zgłoś błąd")
 (:issues-modal-title . "Zgłoś problem")
 (:issues-modal-subtitle . "Opisz, co poszło nie tak. Automatycznie dołączymy bieżącą stronę.")
 (:issues-title-label . "Krótki tytuł")
 (:issues-title-placeholder . "Krótkie podsumowanie problemu")
 (:issues-message-label . "Co się stało?")
 (:issues-message-placeholder . "Podaj kroki odtworzenia, oczekiwane działanie i to, co wydarzyło się zamiast tego.")
 (:issues-submit . "Wyślij zgłoszenie")
 (:issues-cancel . "Anuluj")
 (:issues-success . "Twoje zgłoszenie zostało wysłane. Sprawdzimy je tak szybko, jak się da.")
 (:issues-error-required . "Opisz problem przed wysłaniem.")
 (:issues-error-title-too-long . "Tytuł zgłoszenia jest za długi. Utrzymaj go poniżej 160 znaków.")
 (:issues-error-too-long . "Treść zgłoszenia jest za długa. Zachowaj limit 4000 znaków.")
 (:issues-error-rate-limit . "Zbyt wiele zgłoszeń z tego źródła. Poczekaj i spróbuj ponownie później.")
 (:issues-error-generic . "Nie udało się wysłać zgłoszenia. Spróbuj ponownie.")

 ;; Landing page (Programmable Paper)
 (:landing-signal-languages . "Piętnaście języków")
 (:landing-signal-flashcards . "Sprytne fiszki")
 (:landing-signal-pronunciation . "Wymowa, którą można przeczytać")
 (:landing-problem-title . "Zdanie, które przetłumaczyłeś w zeszłym tygodniu. Powiesz je teraz?")
 (:landing-problem-body . "Ta chwila zdarza się często. Widzisz zwrot, wklejasz go do tłumacza i znaczenie staje się jasne, tu, w twojej dłoni. Mija tydzień; brzmienie uleciało z pamięci, a znaczenie razem z nim. Nauka jednego zdania wymaga zwykle czterech osobnych narzędzi:")
 (:landing-tool-translator . "Tłumacza do znaczenia")
 (:landing-tool-grammar . "Gramatyki do struktury")
 (:landing-tool-pronunciation . "Przewodnika wymowy do brzmienia")
 (:landing-tool-flashcards . "Aplikacji z fiszkami do zapamiętania")
 (:landing-problem-outro . "Korzystanie ze wszystkich czterech zajmuje czas, a kolejne zdanie znika, zanim skończysz fiszkę.")
 (:landing-bookmark-title . "Co się dzieje, gdy zapisujesz zdanie")
 (:landing-bookmark-intro . "Jedno dotknięcie i Hiisi w kilka sekund zamienia zdanie w uporządkowany element nauki. Zostaje w twojej bibliotece ze wszystkim, co do niego należy:")
 (:landing-bookmark-item-translation . "Oryginalne zdanie i czytelne tłumaczenie")
 (:landing-bookmark-item-pronunciation . "Wymowa zapisana tak, jak robią to słowniki")
 (:landing-bookmark-item-grammar . "Gramatyka objaśniona w języku, w którym czytasz najchętniej")
 (:landing-bookmark-item-colors . "Słowa połączone kolorami pokazują, która część odpowiada której")
 (:landing-bookmark-item-flashcard . "Fiszka, która wraca, gdy twoja pamięć jej potrzebuje")
 (:landing-bookmark-cta . "Zapisz swoje pierwsze zdanie")
 (:landing-sources-title . "Na początek wystarczy jedno zdanie")
 (:landing-sources-intro . "Wszystko, co czytasz lub słyszysz w nowym języku, działa z Hiisi:")
 (:landing-source-lyrics . "Tekst piosenki, którą wciąż odtwarzasz")
 (:landing-source-articles . "Artykuły w języku, którego się uczysz")
 (:landing-source-messages . "Wiadomości od znajomych mówiących w tym języku od urodzenia")
 (:landing-source-films . "Kwestie z filmów lub podcastów, które zachowujesz")
 (:landing-source-page . "Strona, którą właśnie czytasz")
 (:landing-features-title . "Zbudowane dla samouków i studentów")
 (:landing-feature-grammar-title . "Gramatyka w języku, w którym myślisz")
 (:landing-feature-grammar-body . "Czytaj gramatykę francuską po polsku albo hiszpańską po angielsku. Twoja uwaga zostaje przy zdaniu, którego się uczysz.")
 (:landing-feature-colors-title . "Słowa połączone kolorem")
 (:landing-feature-colors-body . "Słowo i jego tłumaczenie dzielą ten sam kolor, więc znaczenie każdego słowa widzisz od razu.")
 (:landing-feature-pronunciation-title . "Wymowa, którą można przeczytać")
 (:landing-feature-pronunciation-body . "Każde zdanie ma pisany przewodnik wymowy, taki sam, jakiego używają słowniki. Widzisz, jak brzmi, zanim je wypowiesz.")
 (:landing-feature-flashcards-title . "Fiszki, które planują się same")
 (:landing-feature-flashcards-body . "Każde zapisane zdanie staje się fiszką. Algorytm SM-2, ten sam co w Anki, decyduje, kiedy wróci, więc powtarzasz dokładnie to, co miałeś właśnie zapomnieć.")
 (:landing-feature-decks-title . "Talie tematyczne na to, co przed tobą")
 (:landing-feature-decks-body . "Podróż w przyszłym miesiącu? Nowa praca? Zaimportuj gotową talię i powtarzaj od pierwszego dnia.")
 (:landing-feature-directions-title . "Piętnaście języków, dowolny kierunek")
 (:landing-feature-directions-body . "Tłumacz z hiszpańskiego na francuski albo z angielskiego na niemiecki. Hiisi obsługuje każdy kierunek w całym zestawie.")
 (:landing-flow-title . "Jak wygląda nauka w Hiisi")
 (:landing-flow-body . "Otwórz Hiisi. Dzisiejsze fiszki już czekają, każda to zdanie, które zapisałeś, z tłumaczeniem i gramatyką. Widzisz nowe zdanie, które chcesz zachować? Zapisz je, a jutro trafi do powtórek.")
 (:landing-who-title . "Dla kogo jest Hiisi")
 (:landing-who-intro . "Zgubiłeś kiedyś przydatne zdanie? Hiisi powstało właśnie dla ciebie.")
 (:landing-who-beginners . "Początkujący, którzy układają pierwsze zwroty w nowym języku")
 (:landing-who-intermediate . "Średnio zaawansowani, którzy czytają dobrze, ale potykają się o gramatykę")
 (:landing-who-native . "Osoby wracające do języka, którym mówiło się w domu")
 (:landing-who-travellers . "Podróżnicy i partnerzy rodzimych użytkowników, którzy chcą zdań do użycia")
 (:landing-final-title . "Zacznij korzystać z Hiisi już dziś")
 (:landing-final-body . "Hiisi daje ci znaczenie, gramatykę, wymowę i fiszkę, która sama cię odnajdzie. Od tej chwili zdanie należy do ciebie.")
 (:landing-final-languages . "Piętnaście języków czeka, aż będziesz gotowy.")
 (:modal-close . "Zamknij")
)
