;;; European Portuguese translations
;;; This file follows the structure of en.lisp (authoritative source)

(
 ;; Language metadata (used for language picker)
 (:lang-name . "Português europeu")
 (:lang-flag . "🇵🇹")

 ;; Language modal (first-visit language selection)
 (:lang-modal-title . "Escolha o seu idioma")
 (:lang-modal-subtitle . "Selecione o seu idioma preferido para a interface:")

 ;; Navigation
 (:nav-translate . "Traduzir")
 (:nav-review . "Rever")
 (:nav-flashcards . "Os meus cartões")
 (:nav-dashboard . "Painel")
 (:nav-decks . "Baralhos")
 (:nav-logout . "Sair")
 (:nav-home . "Início")
 (:nav-pricing . "Preços")
 (:nav-institutions . "Para instituições")
 (:nav-export-data . "Exportar Dados")
 (:nav-open-navigation . "Abrir navegação")
 (:theme-light . "Claro")
 (:theme-dark . "Escuro")

 ;; App title and branding
 (:app-title . "Hiisi - Aprendizagem de línguas")

 ;; Landing page
 (:landing-meta-title . "Hiisi: aplicação de aprendizagem de línguas com gramática e cartões")
 (:landing-meta-description . "Hiisi é uma aplicação de aprendizagem de línguas. Cada frase que traduz torna-se um cartão com gramática integrada, agendado pelo SM-2, o algoritmo do Anki. 15 línguas.")
 (:landing-learn-more . "Saber mais")
 (:landing-how-it-works . "Como funciona")
 (:landing-start-trial . "Começar com o Hiisi")
 (:landing-best-value . "Melhor valor")

 ;; Auth pages
 (:auth-register . "Registar")
 (:auth-login . "Entrar")
 (:auth-email . "E-mail")
 (:auth-password . "Palavra-passe")
 (:auth-password-again . "Confirmar palavra-passe")
 (:auth-display-name . "Nome de apresentação")
 (:auth-register-title . "Registe-se no Hiisi")
 (:auth-register-subtitle . "Criar uma nova conta")
 (:auth-login-title . "Entrar no Hiisi")
 (:auth-login-subtitle . "Introduza as suas credenciais")
 (:auth-login-invalid-credentials . "E-mail ou palavra-passe inválidos.")
 (:auth-login-rate-limited . "Muitas tentativas de início de sessão. Aguarde alguns minutos e tente novamente.")
(:auth-register-rate-limited . "Demasiadas tentativas de registo. Aguarde alguns minutos e tente novamente.")
(:auth-email-invalid . "Introduza um endereço de e-mail válido.")
(:auth-password-too-short . "A palavra-passe tem de ter pelo menos 8 caracteres.")
(:auth-passwords-mismatch . "As palavras-passe não coincidem.")
(:auth-display-name-invalid . "O nome visível tem de ter entre 1 e 100 caracteres.")
(:auth-register-email-exists . "Já existe uma conta com este e-mail.")
(:auth-register-unavailable . "O registo está temporariamente indisponível. Tente novamente mais tarde.")
(:auth-register-plan-required . "Escolha um plano antes de criar uma conta.")
(:auth-preapproved-email-unrecognized . "Use o endereço de e-mail do convite ou escolha um plano antes de criar uma conta.")
(:auth-institution-register . "Vem de uma instituição?")
(:auth-institution-stage-title . "Acesso institucional")
(:auth-institution-stage-subtitle . "Use o e-mail da sua escola ou universidade. As contas elegíveis são desbloqueadas através da instituição após a verificação do e-mail.")
(:auth-institution-title . "Registe-se através da sua instituição")
(:auth-institution-subtitle . "Use o e-mail da sua escola ou universidade. Se a sua instituição já estiver configurada no Hiisi, a sua conta será desbloqueada após a verificação do e-mail; o teste individual de 14 dias aplica-se ao registo com um plano pessoal.")
(:auth-institution-benefit-email . "Use o endereço de e-mail da sua escola ou universidade.")
(:auth-institution-benefit-access . "As contas elegíveis recebem acesso institucional após a verificação do e-mail.")
(:auth-institution-benefit-fallback . "Se o domínio não for reconhecido, escolha um plano individual ou peça à sua instituição para contactar a Hiisi.")
(:auth-see-included . "Ver o que está incluído")
(:auth-institution-check-access . "Verificar acesso")
(:auth-institution-email-eligible-title . "Acesso institucional confirmado")
(:auth-institution-email-eligible-detail . "Continue com este e-mail para criar a sua conta. O acesso será desbloqueado após a verificação do e-mail.")
(:auth-institution-change-email . "Usar outro e-mail")
(:auth-institution-outcome-note . "Se a sua escola ou universidade fornecer acesso à Hiisi, a sua conta é desbloqueada após a verificação do e-mail. Se o domínio não for elegível, escolha um plano pessoal para iniciar o teste de 14 dias.")
(:auth-institution-personal-plan-link . "Ver planos pessoais")
(:auth-institution-domain-unrecognized . "Ainda não reconhecemos esse domínio de e-mail institucional. Escolha um plano pessoal para iniciar o teste de 14 dias, ou peça à sua instituição para contactar a Hiisi.")
(:subscribe-institution-callout-title . "Usa a Hiisi através de uma escola ou universidade?")
(:subscribe-institution-callout-body . "Registe-se com o seu e-mail institucional e a Hiisi desbloqueará o acesso automaticamente se a sua instituição já estiver configurada.")
(:auth-activation-email-send-failed . "Não foi possível enviar o e-mail de ativação. Tente novamente.")
 (:auth-forgot-password . "Esqueceu-se da palavra-passe?")
 (:auth-no-account . "Não tem uma conta?")
 (:auth-have-account . "Já tem uma conta?")
 (:auth-google . "Google")
 (:auth-google-login-failed . "Falha ao iniciar sessão com o Google. Tente novamente.")
 (:auth-account-created . "Conta criada!")
 (:auth-check-email . "Verifique o seu e-mail para encontrar a ligação de ativação.")
 (:auth-redirect-login . "A redirecionar para o início de sessão em")
 (:auth-seconds . "segundos...")
 (:auth-go-now . "Ir agora")
 (:auth-not-activated . "Conta não ativada")
 (:auth-activate-title . "Ative a sua conta!")
 (:auth-activated . "Conta ativada!")
 (:auth-activated-message . "A sua conta foi ativada. Agora pode usar a Hiisi.")
 (:auth-redirecting . "A redirecionar em")
 (:auth-go-to-app . "Ir para a aplicação")
 (:onboarding-title . "Como o Hiisi funciona")
 (:onboarding-subtitle . "Traduza texto real, veja a gramática, guarde itens úteis e reveja-os mais tarde.")
 (:onboarding-translate-detail . "Comece com texto real. O Hiisi devolve a tradução, as formas alinhadas e as próximas ações de estudo num único lugar.")
 (:onboarding-grammar-detail . "Abra a análise gramatical para ver quais formas correspondem na frase e qual função cada parte desempenha.")
 (:onboarding-review-detail . "Guarde traduções úteis e reveja-as mais tarde com repetição espaçada para que permaneçam na memória de longo prazo.")
 (:onboarding-decks-detail . "Agrupe itens úteis em baralhos, partilhe-os com outras pessoas e mantenha o material relacionado junto.")
 (:onboarding-back . "Voltar")
 (:onboarding-next . "Seguinte")
 (:onboarding-skip . "Ignorar guia")
 (:auth-resend-title . "Reenviar e-mail de ativação")
 (:auth-resend-subtitle . "Introduza o seu e-mail para receber uma nova ligação de ativação.")
 (:auth-resend-button . "Reenviar e-mail de ativação")
 (:auth-resend-success . "E-mail de ativação enviado!")
 (:auth-resend-success-detail . "Verifique a sua caixa de entrada para encontrar a nova ligação de ativação.")
 (:auth-resend-rate-limited . "Aguarde alguns minutos antes de pedir outro e-mail de ativação.")
 (:auth-resend-cooldown . "Pode pedir outro e-mail em ~a segundos.")
 (:auth-back-to-login . "Voltar ao início de sessão")
 (:auth-forgot-password-title . "Esqueci-me da palavra-passe")
 (:auth-forgot-password-subtitle . "Introduza o seu e-mail e enviaremos uma ligação para repor a palavra-passe.")
 (:auth-send-reset-link . "Enviar ligação de reposição")
 (:auth-reset-email-sent . "Ligação enviada!")
 (:auth-reset-email-sent-detail . "Se existir uma conta com esse e-mail, receberá em breve uma ligação para repor a palavra-passe.")
 (:auth-reset-rate-limited . "Aguarde alguns minutos antes de pedir outra reposição de palavra-passe.")
 (:auth-reset-invalid-token . "Esta ligação de reposição é inválida ou expirou.")
 (:auth-reset-password-title . "Repor palavra-passe")
 (:auth-reset-password-subtitle . "Introduza a sua nova palavra-passe abaixo.")
 (:auth-new-password . "Nova palavra-passe")
 (:auth-confirm-new-password . "Confirmar nova palavra-passe")
 (:auth-reset-password . "Repor palavra-passe")
 (:auth-password-changed . "Palavra-passe alterada!")
 (:auth-password-changed-detail . "A sua palavra-passe foi alterada com sucesso. Agora pode entrar com a nova palavra-passe.")
 (:auth-change-password-title . "Alterar palavra-passe")
 (:auth-change-password-subtitle . "Atualize a palavra-passe da sua conta.")
 (:auth-current-password . "Palavra-passe atual")
 (:auth-change-password . "Alterar palavra-passe")
 (:auth-back-to-app . "Voltar à aplicação")
 (:auth-password-updated . "Palavra-passe atualizada!")
 (:auth-password-updated-detail . "A sua palavra-passe foi atualizada com sucesso.")
(:auth-current-password-invalid . "A palavra-passe atual está incorreta.")
(:auth-new-password-same . "A nova palavra-passe tem de ser diferente da palavra-passe atual.")

 ;; Email copy
 (:email-common-hi . "Olá")
 (:email-common-tagline . "Hiisi - Aprende através da tradução")
 (:email-activation-subject . "Ativa a tua conta Hiisi")
 (:email-activation-title . "Bem-vindo ao Hiisi")
 (:email-activation-body . "Obrigado por te registares. Ativa a tua conta clicando na ligação abaixo:")
 (:email-activation-button . "Ativar conta")
 (:email-activation-copy-link . "Ou copia esta ligação")
 (:email-activation-expiry . "Esta ligação expira em 24 horas.")
 (:email-reset-subject . "Repõe a tua palavra-passe do Hiisi")
 (:email-reset-title . "Pedido de reposição de palavra-passe")
 (:email-reset-body . "Recebemos um pedido para repor a tua palavra-passe. Clica na ligação abaixo para definir uma nova palavra-passe:")
 (:email-reset-button . "Repor palavra-passe")
 (:email-reset-expiry . "Esta ligação expira em 1 hora.")
 (:email-reset-ignore . "Se não pediste a reposição da palavra-passe, podes ignorar este e-mail.")
 (:email-reminder-subject-due . "Está na hora de rever os teus cartões do Hiisi")
 (:email-reminder-subject-streak . "Mantém a tua sequência do Hiisi")
 (:email-reminder-cards-due . "cartões prontos para rever")
 (:email-reminder-keep-going . "Já passaram alguns dias desde a tua última revisão. Cinco minutos hoje chegam para não deixares escapar o que já aprendeste.")
 (:email-reminder-button . "Rever agora")
 (:email-reminder-settings . "Gerir lembretes")
 (:email-reminder-preview-title . "Cartões à tua espera")
 (:email-reminder-translation-label . "Tradução")
 (:email-reminder-more-due-today . "cartões adicionais para rever hoje")
 (:email-trial-subject . "Como está a correr o teu período experimental do Hiisi?")
 (:email-trial-expiring . "O teu período experimental gratuito do Hiisi termina amanhã.")
 (:email-trial-feedback . "Estás a gostar do Hiisi? Diz-nos o que te tem ajudado mais.")
 (:email-trial-strengths . "Podes traduzir textos reais, guardar os melhores itens em flashcards e aprender com repetição espaçada.")
 (:email-trial-reply . "Responde a este e-mail e a tua mensagem irá diretamente para a equipa do Hiisi.")
 (:email-trial-button . "Escolher um plano")
 (:email-trial-manage . "Gerir subscrição")
 (:email-trial-contact . "Escreve-nos")
 (:email-plan-nudge-subject . "As tuas traduções estão à tua espera")
 (:email-plan-nudge-title . "As tuas traduções estão à tua espera")
 (:email-plan-nudge-intro . "Registaste-te no Hiisi, mas ainda não escolheste um plano.")
 (:email-plan-nudge-benefits-intro . "Eis o que recebes com uma subscrição:")
 (:email-plan-nudge-benefit-translations . "600 traduções por mês com análises gramaticais")
 (:email-plan-nudge-benefit-flashcards . "Flashcards ilimitados com repetição espaçada")
 (:email-plan-nudge-benefit-decks . "Baralhos personalizados que podes organizar e partilhar")
 (:email-plan-nudge-pricing . "Os planos começam em 10 EUR por mês, ou poupa com o plano anual de 100 EUR por ano (dois meses gratuitos).")
 (:email-plan-nudge-feedback . "Se houver algo no Hiisi que não esteja a funcionar para ti, responde a este e-mail. A tua mensagem vai diretamente para a equipa do Hiisi.")
 (:email-plan-nudge-button . "Escolher um plano")
 (:email-plan-nudge-unsubscribe . "Cancelar estes e-mails")
 (:email-plan-nudge-unsubscribe-done-title . "E-mails sobre planos desativados")
 (:email-plan-nudge-unsubscribe-done-body . "Já não vais receber mais lembretes por e-mail para escolher um plano.")
 (:email-plan-nudge-unsubscribe-invalid-title . "Esta ligação não é válida")
 (:email-plan-nudge-unsubscribe-invalid-body . "Esta ligação de cancelamento está em falta, expirou ou já não é válida.")
 (:email-invite-subject . "Foste convidado para o Hiisi")
 (:email-invite-title . "Foste convidado para o Hiisi")
 (:email-invite-intro . "Foste convidado a usar o Hiisi gratuitamente, como tester, amigo valioso ou ambos.")
 (:email-invite-details . "Usa o botão abaixo para criar a tua conta e começar a explorar traduções e flashcards.")
 (:email-invite-button . "Criar conta")
 (:email-invite-issue-reporting . "Se algo se partir ou parecer errado, há um botão para reportar problemas no rodapé de cada página.")
 (:email-issue-completed-subject . "O teu problema no Hiisi foi corrigido")
 (:email-issue-completed-title . "Problema corrigido")
 (:email-issue-completed-label . "Problema")
 (:email-issue-completed-followup . "Abre o Hiisi para verificar a correção ou continuar de onde paraste.")
 (:email-issue-completed-button . "Abrir Hiisi")
 (:email-issue-completed-open-link . "Abrir página")

 ;; Translation page
 (:translate-title . "Traduzir")
 (:landing-public-translate-title . "Experimente aqui")
 (:landing-public-translate-cta-title . "Mantenha o ritmo")
 (:landing-public-translate-cta-body . "Guarde traduções como cartões de estudo e reveja-as mais tarde.")
 (:landing-public-translate-cta-button . "Comece o teste gratuito e continue a aprender")
 (:translate-input-label . "Texto para traduzir")
 (:translate-input-placeholder . "Introduza o texto para traduzir...")
 (:translate-from . "Idioma de origem:")
 (:translate-to . "Idioma de destino:")
 (:translate-select-target-placeholder . "Selecione o idioma de destino")
 (:translate-submit . "Traduzir")
 (:translate-auto-detect . "Qualquer (Detectar automaticamente)")
 (:translate-empty-state . "Traduza uma palavra ou frase e verá aqui o resultado, a análise gramatical e as ações de estudo.")
 (:translate-select-deck-placeholder . "Selecionar baralho (opcional)")
 (:translate-new-deck . "Novo baralho")
 (:translate-add-to-deck . "Adicionar ao baralho")
 (:translate-bookmark . "Guardar")
 (:translate-bookmarked . "Guardado")
 (:translate-retry . "Gerar novamente")
 (:translate-like-tooltip . "Boa tradução")
 (:translate-dislike-tooltip . "Má tradução - pedir uma nova")
 (:translate-dislike-confirm . "Isto irá gerar uma nova tradução. Continuar?")
 (:pronunciation-label . "Pronúncia")
 (:pronunciation-show . "Mostrar pronúncia")
 (:pronunciation-hide . "Ocultar pronúncia")
 (:grammar-term-examples . "Exemplos")
 (:grammar-term-related . "Termos relacionados")
 (:grammar-term-modal-title . "Termo gramatical")
 (:grammar-term-empty . "Selecione um termo destacado para ver os detalhes.")
 (:extension-login-required . "Inicia sessão no Hiisi antes de usar a extensão do navegador.")
 (:extension-session-invalid . "A tua sessão Hiisi já não é válida. Inicia sessão novamente.")
 (:extension-activation-required . "Ativa a tua conta Hiisi antes de usar a extensão do navegador.")
 (:extension-subscription-required . "Inicia um período experimental do Hiisi antes de usar a extensão do navegador.")

 ;; Translation and Flashcards
 (:lang-auto . "Auto")
 (:lang-unknown . "?")
 (:lang-target . "Destino")
 (:translate-deck-create-title . "Criar novo baralho")
 (:translate-deck-name-label . "Nome do baralho")
 (:translate-deck-name-placeholder . "ex.: Fundamentos de finlandês")
 (:translate-deck-description-label . "Descrição (opcional)")
 (:translate-deck-cancel . "Cancelar")
 (:translate-deck-create . "Criar")
 (:translate-rate-label . "Avaliar tradução")
 (:flashcards-delete . "Eliminar")
 (:flashcards-delete-confirm . "Tem a certeza de que pretende eliminar este cartão?")
 (:flashcards-deck-search-placeholder . "Pesquisar baralhos...")
 (:flashcards-no-decks . "Ainda não há baralhos. Crie primeiro um baralho!")
 (:flashcards-deck-cancel . "Cancelar")
 (:flashcards-recollection-tooltip . "Recordação: ~A")
 (:flashcards-recollection-poor . "Fraca")
 (:flashcards-recollection-fair . "Razoável")
 (:flashcards-recollection-normal . "Normal")
 (:flashcards-recollection-strong . "Forte")
 (:flashcards-recollection-very-strong . "Muito forte")

 ;; Flashcard review
 (:review-title . "Rever")
 (:review-session-title . "Sessão de revisão")
 (:review-session-subtitle . "Pratique os seus cartões guardados")
 (:review-selector-title . "Escolha o que rever")
 (:review-selector-subtitle . "Selecione um baralho ou par de idiomas para focar a sua sessão de revisão.")
 (:review-by-deck . "Rever por baralho")
 (:review-by-language-pair . "Rever por par de idiomas")
 (:review-all-cards . "Rever todos os cartões")
 (:review-cards-due . "cartões pendentes")
 (:review-deck-caught-up . "Tudo em dia")
 (:review-all-caught-up . "Tudo em dia!")

 (:review-no-cards . "Nenhum cartão para rever")
 (:review-no-cards-desc . "Não tem nenhum cartão pendente para revisão neste momento.")
 (:review-no-cards-hint . "Traduza algum texto e clique em \"Guardar em cartões\" para criar o seu baralho!")
 (:review-start-translating . "Começar a traduzir")
 (:review-click-reveal . "Clique para revelar a resposta")
 (:review-grammar-breakdown . "Análise Gramatical")
 (:review-how-well . "Lembrou-se?")
 (:review-again . "Não")
 (:review-hard . "Com dificuldade")
 (:review-good . "Sim")
 (:review-easy . "Facilmente")
 (:review-progress . "Cartão ~a de ~a")
 (:review-correct-count . "Corretas")
 (:review-wrong-count . "Erradas")
 (:landing-mockup-forgot-detail . "1.ª pessoa do singular do pretérito de \"olvidar\" (esquecer)")
 (:landing-mockup-keys-detail . "Possessivo \"mis\" com substantivo feminino plural \"llaves\" (chaves)")
 (:landing-mockup-home-detail . "Expressão idiomática \"en casa\" (em casa) -- sem artigo")
 (:landing-mockup-possession-note . "Em espanhol, o pretérito marca ações passadas concluídas. O pronome sujeito é geralmente omitido porque a terminação verbal já identifica o falante.")
 (:landing-mockup-children-detail . "Nominativo plural de \"Kind\" (criança) -- o plural acrescenta -er")
 (:landing-mockup-played-detail . "3.ª pessoa do plural do pretérito de \"spielen\" (brincar)")
 (:landing-mockup-garden-detail . "Dativo: \"in dem\" contrai-se em \"im\", com substantivo masculino \"Garten\" (jardim)")
 (:landing-mockup-czech-note . "O alemão usa o pretérito na narrativa escrita. \"Im\" é a contração de \"in\" + \"dem\" (artigo dativo).")
 (:landing-mockup-deck-title . "Italiano básico")
 (:landing-mockup-share-deck . "Partilhar baralho")
 (:review-complete . "Sessão concluída!")
 (:review-complete-msg . "Reviu ~a cartões")
 (:review-again-btn . "Rever novamente")
 (:review-translate-more . "Traduzir mais")
 (:review-streak . "dias de sequência")

 ;; Dashboard
 (:dashboard-title . "Painel")
 (:dashboard-welcome-title . "Traduza o seu primeiro texto")
 (:dashboard-welcome-subtitle . "Traduza uma frase útil, guarde-a num baralho e reveja-a quando for importante.")
 (:dashboard-take-quick-tour . "Fazer uma visita rápida")
 (:dashboard-cards-due . "Cartões pendentes")
 (:dashboard-total-cards . "Total de cartões")
 (:dashboard-mastered-cards . "Cartões dominados")
 (:dashboard-subscription . "Assinatura")
 (:dashboard-subscribed-until . "Assinado até")
 (:dashboard-trial-ends . "Período experimental termina")
 (:dashboard-not-subscribed . "Não assinado")
 (:dashboard-recent . "Traduções recentes")
 (:dashboard-no-translations . "Nenhuma tradução ainda")
 (:dashboard-streak . "Sequência de Revisão")
 (:dashboard-days . "dias")
 (:dashboard-all-caught-up . "Tudo em dia!")
 (:dashboard-all-caught-up-hint . "Traduza mais para ampliar a sua coleção.")
 (:dashboard-no-cards-title . "Crie os seus primeiros cartões de estudo")
 (:dashboard-no-cards-hint . "Traduza texto e guarde frases úteis para criar a sua coleção.")
 (:dashboard-first-use-checklist-title . "Primeiros passos")
 (:dashboard-first-use-checklist-translate . "Faça a sua primeira tradução")
 (:dashboard-first-use-checklist-card . "Guarde o seu primeiro cartão")
 (:dashboard-first-use-checklist-review . "Conclua a sua primeira revisão")
 (:dashboard-getting-started . "Primeiros passos")
 (:dashboard-tip-1 . "Traduza textos que quer aprender")
 (:dashboard-tip-2 . "Clique em \"Guardar em cartões\" nas traduções que quer lembrar")
 (:dashboard-tip-3 . "Reveja os seus cartões regularmente - a repetição espaçada ajuda a lembrar a longo prazo")
 (:dashboard-tip-4 . "Avalie honestamente - isso ajuda o algoritmo a agendar as suas revisões da melhor forma")

 ;; Account
 (:account-title . "Conta")
 (:account-subtitle . "Gira aqui o seu perfil, subscrição, lembretes, exportações e eliminação da conta.")
 (:account-profile-subtitle . "Mantenha o seu nome de apresentação e o seu e-mail atualizados.")
 (:account-export-subtitle . "Descarregue uma cópia das suas traduções guardadas, baralhos e dados de revisão.")
 (:account-deletion-title . "Eliminação da conta")
 (:account-deletion-scheduled . "A sua conta está programada para eliminação em ~A.")
 (:account-deletion-cancel-hint . "Pode cancelar antes dessa data para manter a sua conta.")
 (:account-deletion-cancel . "Cancelar eliminação")
 (:account-deletion-request . "Pode pedir a eliminação da conta a qualquer momento. A eliminação é agendada para 14 dias após a confirmação. Se mudar de ideias, contacte o suporte antes do fim desse período de 14 dias.")
 (:account-deletion-confirm . "Agendar a eliminação da conta para 14 dias a partir de hoje?")
 (:account-deletion-schedule . "Agendar eliminação")
 (:account-reminders-title . "Lembretes por e-mail")
 (:account-reminders-subtitle . "Escolha se a Hiisi pode enviar e-mails quando houver algo à espera de revisão.")
 (:account-reminders-opt-out . "Desativar lembretes de revisão e continuação")
 (:account-reminders-save . "Guardar preferências")

 ;; Subscription
 (:subscribe-title . "Preços simples")
 (:subscribe-choose-plan . "Escolha o seu plano")
 (:subscribe-start-today . "Comece a aprender hoje com 14 dias de teste gratuito")
 (:subscribe-monthly . "Mensal")
 (:subscribe-annual . "Anual")
 (:subscribe-founder-member . "Membro fundador")
 (:subscribe-monthly-price . "€10")
 (:subscribe-annual-price . "€100")
 (:subscribe-founder-price . "€79")
 (:subscribe-founder-monthly-equivalent . "€6,58/mês, faturado anualmente")
 (:subscribe-founder-savings . "Poupe €41/ano face ao pagamento mensal")
 (:subscribe-monthly-billing-equivalent . "€10/mês, faturado mensalmente")
 (:subscribe-monthly-billing-note . "Faturação mensal flexível")
 (:landing-pricing-comparison-title . "Comparação rápida")
 (:subscribe-per-month . "/mês")
 (:subscribe-per-year . "/ano")
 (:subscribe-monthly-desc . "600 traduções por mês. Cartões, baralhos e revisões ilimitados.")
 (:subscribe-unlimited-flashcards . "Flashcards ilimitados")
 (:subscribe-grammar-explanations . "Explicações gramaticais")
 (:subscribe-spaced-repetition . "Repetição espaçada")
 (:subscribe-annual-desc . "Tudo do plano mensal. Dois meses gratuitos.")
 (:subscribe-founder-lock . "O preço mantém-se enquanto a sua subscrição permanecer ativa.")
 (:subscribe-founder-badge . "Oferta limitada")
 (:subscribe-founder-limit . "Limitado aos primeiros 100 membros")
 (:subscribe-manage . "Gerir subscrição")
 (:subscribe-activated . "Subscrição ativada!")
 (:subscribe-thank-you . "A sua subscrição está ativa. Aqui pode gerir a faturação e comprar mais traduções.")
 (:subscribe-start-learning . "Começar a aprender")
 (:subscribe-management . "Gestão da subscrição")
 (:subscribe-active . "Subscrição ativa")
 (:subscribe-preapproved-access . "Acesso pré-aprovado")
 (:subscribe-status . "Status:")
 (:subscribe-status-active . "Ativa")
 (:subscribe-status-preapproved . "Pré-aprovado")
 (:subscribe-preapproved-detail . "Esta conta usa um acesso pré-aprovado gerido pela Hiisi.")
 (:subscribe-days-remaining . "Dias restantes:")
 (:subscribe-renews-on . "Renova em:")
 (:subscribe-no-subscription . "Nenhuma subscrição ativa")
 (:subscribe-access-features . "Escolha um plano para desbloquear acesso completo e gerir a faturação num só lugar.")
 (:subscribe-view-plans . "Ver planos")
 (:subscribe-faq-title . "Perguntas frequentes")
 (:subscribe-faq-trial-q . "O que acontece após o teste gratuito?")
 (:subscribe-faq-trial-a . "O teste de 14 dias não requer cartão. Quando terminar, escolha um plano pago para manter acesso completo.")
 (:subscribe-faq-cancel-q . "Posso cancelar a qualquer momento?")
 (:subscribe-faq-cancel-a . "Sim. Pode cancelar a sua subscrição a qualquer momento. Mantém o acesso até ao fim do período de faturação.")
 (:subscribe-faq-payment-q . "Que métodos de pagamento aceitam?")
 (:subscribe-faq-payment-a . "Aceitamos todos os principais cartões de crédito e débito através do nosso parceiro de pagamentos Polar.sh.")
 (:subscribe-copyright . "Lambda Symbolics OÜ © 2026.")
(:subscribe-checkout-unavailable . "O checkout está temporariamente indisponível. Tente novamente.")
(:subscribe-portal-unavailable . "A gestão da subscrição está temporariamente indisponível. Tente novamente.")
(:subscribe-founder-sold-out . "A oferta para membros fundadores esgotou")
(:subscribe-founder-unavailable . "A oferta para membros fundadores não está disponível neste momento.")
(:subscribe-checkout-cta . "Subscrever")

 ;; Errors and status
 (:error-generic . "Algo correu mal")
(:error-invalid-request . "Dados de pedido inválidos.")
(:error-not-found . "O recurso pedido não foi encontrado.")
(:error-forbidden . "Não tem acesso a isto.")
(:error-rate-limited . "Aguarde um momento e tente novamente.")
 (:error-text-too-long . "O texto é demasiado longo. O comprimento máximo da tradução é de 120 caracteres.")
 (:error-input-too-long . "Entrada demasiado longa")
 (:error-unknown-source-lang . "O idioma de origem selecionado não é suportado.")
 (:error-unknown-target-lang . "O idioma de destino selecionado não é suportado.")
 (:error-unknown-language . "Idioma desconhecido")
 (:error-translation-unavailable . "O serviço de tradução está temporariamente indisponível. Tente novamente dentro de momentos.")
 (:error-translation-failed . "A tradução falhou")
 (:error-translation-retry . "Não foi possível gerar uma tradução após várias tentativas. Tente reformular o texto.")
 (:error-quota-exceeded . "Limite de traduções atingido")
 (:error-quota-exceeded-detail . "Usou todas as suas traduções deste mês. A sua quota é reposta automaticamente todos os meses.")
 (:quota-low-warning . "Apenas ~A traduções restantes. Considere comprar mais.")
 (:top-up-button . "Comprar mais traduções")
 (:top-up-price . "€5")
 (:top-up-amount . "300 traduções")
(:review-session-expired . "A sua sessão de revisão expirou. Inicie uma nova sessão.")

 (:error-session-expired . "A sua sessão expirou. Inicie sessão novamente.")
 (:error-session-invalid . "A sua sessão já não é válida. Inicie sessão novamente.")
 (:error-custom-flashcard-generation . "Não foi possível gerar a explicação. Tente novamente.")
 ;; Institutions
 (:institutions-page-title . "Hiisi para escolas e universidades")
 (:institutions-hero-title . "Ferramentas de ensino de línguas feitas para a sala de aula")
 (:institutions-hero-subtitle . "Dê aos seus estudantes baralhos partilháveis, prática com atenção à gramática e rotinas de revisão consistentes que encaixam no ensino real.")
 (:institutions-section-title . "Porque é que as instituições usam a Hiisi")
 (:institutions-section-body . "A Hiisi ajuda docentes a transformar material letivo em estudo orientado que os estudantes conseguem realmente acompanhar. Crie baralhos para uma disciplina, partilhe-os com um link e apoie a prática de vocabulário e gramática sem carga administrativa extra.")
 (:institutions-benefit-1 . "Baralhos partilháveis e tarefas personalizadas que acompanham o vosso currículo.")
 (:institutions-benefit-2 . "Os gostos e desgostos dos estudantes ajudam a fazer subir as melhores traduções para expressões comuns na sala de aula.")
 (:institutions-benefit-3 . "As análises gramaticais e a revisão espaçada apoiam muito mais do que decorar listas isoladas de palavras.")
 (:institutions-benefit-4 . "Apoio com sensibilidade de professor por parte de alguém que escuta com atenção e se importa com as necessidades da sala de aula.")
 (:institutions-request-title . "Vamos conversar")
 (:institutions-request-subtitle . "Fale-nos da sua instituição, das vossas línguas e do tipo de apoio pedagógico de que necessitam. Responderemos no prazo de uma semana.")
 (:institutions-aside-title . "O que acontece a seguir")
 (:institutions-aside-body . "Analisamos as vossas necessidades e respondemos no prazo de uma semana para discutir o acesso e a configuração para a vossa instituição.")
 (:institutions-field-name . "Nome da instituição")
 (:institutions-field-name-placeholder . "A sua universidade")
 (:institutions-field-contact-name . "Nome do contacto")
 (:institutions-field-contact-name-placeholder . "O seu nome")
 (:institutions-field-contact-email . "E-mail de contacto")
 (:institutions-field-contact-email-placeholder . "nome@universidade.pt")
 (:institutions-field-domains . "Domínios de e-mail")
 (:institutions-field-domains-placeholder . "universidade.edu, cs.universidade.edu")
 (:institutions-field-domains-help . "Lista de domínios de e-mail da sua instituição, separados por vírgulas")
 (:institutions-field-notes . "Informações adicionais")
 (:institutions-field-notes-placeholder . "Número estimado de estudantes, ciclo de faturação preferido, quaisquer requisitos especiais...")
 (:institutions-submit . "Enviar pedido")
 (:institutions-success-title . "Obrigado - Hiisi para escolas e universidades")
 (:institutions-success-heading . "Obrigado!")
 (:institutions-success-body . "Recebemos o seu pedido de contacto. Vamos analisar as necessidades da sua instituição e responder no prazo de uma semana.")
 (:institutions-success-back . "Voltar à página inicial")

 ;; Footer
 (:footer-privacy . "Política de Privacidade")
 (:footer-terms . "Termos de Serviço")

 ;; Early software notice
 (:early-software-notice . "Hiisi está em desenvolvimento inicial. Encontrou um bug ou tem uma sugestão?")

 ;; Política de privacidade
 (:privacy-title . "Política de privacidade")
 (:privacy-updated . "Última atualização: janeiro de 2026")
 (:privacy-who-title . "Quem somos")
 (:privacy-who-body . "A Hiisi é operada pela Lambda Symbolics OÜ, uma empresa registada na Estónia. Como empresa estónia, cumprimos o Regulamento Geral sobre a Proteção de Dados (GDPR) da União Europeia.")
 (:privacy-collect-title . "Dados que recolhemos")
 (:privacy-collect-intro . "Quando utiliza a Hiisi, recolhemos as seguintes informações:")
 (:privacy-collect-account-key . "Informações da conta: ")
 (:privacy-collect-account-val . "Endereço de e-mail, nome de apresentação e palavra-passe guardada com hash seguro.")
 (:privacy-collect-learning-key . "Dados de aprendizagem: ")
 (:privacy-collect-learning-val . "As suas traduções, cartões guardados e histórico de revisão.")
 (:privacy-collect-usage-key . "Dados de utilização: ")
 (:privacy-collect-usage-val . "Registos básicos do servidor para segurança e depuração.")
 (:privacy-use-title . "Como usamos os seus dados")
 (:privacy-use-auth-key . "Autenticação: ")
 (:privacy-use-auth-val . "Para verificar a sua identidade e proteger a sua conta.")
 (:privacy-use-service-key . "Prestação do serviço: ")
 (:privacy-use-service-val . "Para fornecer traduções e gerir a sua coleção de cartões.")
 (:privacy-use-ai-key . "Traduções com IA: ")
 (:privacy-use-ai-val . "Os seus pedidos de tradução são enviados para a OpenRouter para gerar respostas. A OpenRouter pode encaminhar os pedidos para o fornecedor de modelos configurado. Consulte a política de privacidade da OpenRouter para saber como trata estes dados.")
 (:privacy-third-title . "Serviços de terceiros")
 (:privacy-third-intro . "Usamos os seguintes serviços de terceiros:")
 (:privacy-third-openrouter-key . "OpenRouter: ")
 (:privacy-third-openrouter-val . "Para pedidos automáticos de tradução.")
 (:privacy-third-mailgun-key . "Mailgun: ")
 (:privacy-third-mailgun-val . "Para envio de e-mails de ativação de conta e e-mails transacionais.")
 (:privacy-third-polar-key . "Polar.sh: ")
 (:privacy-third-polar-val . "Para processamento de pagamentos de subscrição.")
 (:privacy-cookies-title . "Cookies")
 (:privacy-cookies-intro . "Usamos apenas cookies essenciais:")
 (:privacy-cookies-auth-key . "Token de autenticação: ")
 (:privacy-cookies-auth-val . "Um cookie seguro, HTTP-only, para manter a sua sessão iniciada.")
 (:privacy-cookies-lang-key . "Preferência de idioma: ")
 (:privacy-cookies-lang-val . "Para memorizar o idioma preferido da interface.")
 (:privacy-retention-title . "Retenção de dados")
 (:privacy-retention-body . "Os seus dados são guardados enquanto mantiver uma conta. Quando pede eliminação, a sua conta é agendada para ser eliminada em 14 dias.")
 (:privacy-rights-title . "Os seus direitos (GDPR)")
 (:privacy-rights-intro . "Ao abrigo do GDPR, tem direito a:")
 (:privacy-rights-access . "Aceder aos seus dados pessoais")
 (:privacy-rights-export . "Exportar os seus dados (disponível em /app/api/export)")
 (:privacy-rights-correct . "Pedir a correção de dados incorretos")
 (:privacy-rights-delete . "Pedir a eliminação da sua conta e dos seus dados")
 (:privacy-rights-object . "Opor-se ao tratamento dos seus dados")
 (:privacy-rights-contact . "Para exercer estes direitos, contacte-nos em")
 (:privacy-contact-title . "Contacto")
 (:privacy-contact-intro . "Para questões de privacidade:")
 (:privacy-contact-email-label . "E-mail: ")
 (:privacy-address-1 . "Lambda Symbolics OÜ")
 (:privacy-address-2 . "Harju maakond, Tallinn, Kesklinna linnaosa, Tornimäe tn 5, 10145")

 ;; Termos de serviço
 (:terms-title . "Termos de serviço")
 (:terms-updated . "Última atualização: janeiro de 2026")
 (:terms-1-title . "1. Descrição do serviço")
 (:terms-1-body . "A Hiisi é uma aplicação de aprendizagem de línguas que fornece traduções automáticas, explicações gramaticais e cartões de repetição distribuída. O serviço é operado pela Lambda Symbolics OÜ.")
 (:terms-2-title . "2. Registo de conta")
 (:terms-2-body . "Para usar a Hiisi, tem de criar uma conta com um endereço de e-mail válido. É responsável por manter a segurança das credenciais da sua conta.")
 (:terms-3-title . "3. Subscrição e pagamentos")
 (:terms-3-body . "A Hiisi oferece planos pagos de subscrição (mensal e anual). As subscrições são processadas através da Polar.sh.")
 (:terms-3-list-1 . "As subscrições renovam automaticamente, salvo cancelamento antes da data de renovação.")
 (:terms-3-list-2 . "Os reembolsos são concedidos de acordo com a legislação aplicável de proteção do consumidor.")
 (:terms-3-list-3 . "A falta de pagamento resulta na perda de acesso a funcionalidades premium.")
 (:terms-4-title . "4. Utilização aceitável")
 (:terms-4-intro . "Concorda em não:")
 (:terms-4-list-1 . "Usar o serviço para qualquer finalidade ilegal")
 (:terms-4-list-2 . "Tentar contornar limites de utilização ou medidas de segurança")
 (:terms-4-list-3 . "Partilhar as credenciais da sua conta com terceiros")
 (:terms-4-list-4 . "Usar ferramentas automatizadas de forma a degradar o desempenho para outras pessoas")
 (:terms-5-title . "5. Conteúdo e propriedade intelectual")
 (:terms-5-body-1 . "As traduções geradas pela Hiisi são criadas automaticamente e podem não ser únicas. Pode usar as suas traduções e cartões para fins pessoais, mas não detém direitos exclusivos de autoria sobre conteúdo gerado automaticamente.")
 (:terms-5-body-2 . "A aplicação Hiisi, a marca e o conteúdo original continuam a ser propriedade da Lambda Symbolics OÜ.")
 (:terms-6-title . "6. Disponibilidade do serviço")
 (:terms-6-intro . "A Hiisi é fornecida tal como está. Não garantimos:")
 (:terms-6-list-1 . "Serviço ininterrupto ou sem erros")
 (:terms-6-list-2 . "Precisão das traduções geradas automaticamente")
 (:terms-6-list-3 . "Disponibilidade de funcionalidades específicas")
 (:terms-6-body . "Podemos modificar ou descontinuar funcionalidades a qualquer momento.")
 (:terms-7-title . "7. Limitação de responsabilidade")
 (:terms-7-body-1 . "Na máxima medida permitida por lei, a Lambda Symbolics OÜ não será responsável por quaisquer danos indiretos, incidentais, especiais ou consequentes resultantes da sua utilização da Hiisi.")
 (:terms-7-body-2 . "A nossa responsabilidade total não excederá o montante pago por si pelo serviço nos 12 meses anteriores à reclamação.")
 (:terms-8-title . "8. Encerramento de conta")
 (:terms-8-body-1 . "Podemos suspender ou terminar a sua conta se violar estes termos. Pode pedir a eliminação da conta a qualquer momento na aplicação.")
 (:terms-8-body-2 . "Após pedido de eliminação, a sua conta é agendada para ser eliminada em 14 dias.")
 (:terms-9-title . "9. Alterações aos termos")
 (:terms-9-body . "Podemos atualizar estes termos ocasionalmente. O uso continuado da Hiisi após alterações constitui aceitação dos novos termos.")
 (:terms-10-title . "10. Lei aplicável")
 (:terms-10-body . "Estes termos regem-se pela legislação da Estónia. Quaisquer litígios serão resolvidos nos tribunais da Estónia.")
 (:terms-contact-title . "Contacto")
 (:terms-contact-intro . "Para questões sobre estes termos:")
 (:terms-contact-email-label . "E-mail: ")
 (:terms-address-1 . "Lambda Symbolics OÜ")
 (:terms-address-2 . "Harju maakond, Tallinn, Kesklinna linnaosa, Tornimäe tn 5, 10145")

 ;; Decks
 (:decks-title . "Baralhos")
 (:decks-subtitle . "Crie baralhos personalizados e partilhe-os com outros.")
 (:decks-create-title . "Criar baralho")
 (:decks-name-placeholder . "Nome do baralho")
 (:decks-desc-placeholder . "Descrição")
 (:decks-create-btn . "Criar baralho")
 (:decks-edit-title . "Editar baralho")
 (:decks-edit-btn . "Editar baralho")
 (:decks-actions-title . "Ações do baralho")
 (:decks-card-actions-title . "Ações do cartão")
 (:decks-update-btn . "Guardar alterações")
 (:decks-default-badge . "Automático")
 (:decks-default-description . "Este baralho é gerido automaticamente para este par de línguas.")
 (:decks-default-readonly . "Os baralhos automáticos têm nomes e descrições fixos.")
 (:decks-delete-btn . "Eliminar baralho")
 (:decks-delete-confirm . "Tem a certeza de que quer eliminar este baralho?")
 (:decks-error-name-required . "O nome do baralho é obrigatório.")
 (:decks-error-name-too-long . "O nome do baralho deve ter no máximo ~A caracteres.")
 (:decks-error-desc-too-long . "A descrição do baralho deve ter no máximo ~A caracteres.")
 (:decks-error-default-readonly . "Os baralhos automáticos não podem ser editados.")
 (:decks-error-default-delete-forbidden . "Os baralhos automáticos não podem ser eliminados.")
 (:decks-your-title . "Os seus baralhos")
 (:decks-col-updated . "Atualizado")
 (:decks-no-decks . "Ainda não há baralhos.")
 (:decks-open-btn . "Abrir")
 (:decks-view-deck-btn . "Ver baralho")
 (:decks-start-review . "Iniciar revisão")
 (:decks-no-desc . "Sem descrição.")
 (:decks-share-title . "Link de partilha")
 (:decks-share-info . "Qualquer pessoa com este link pode importar o baralho:")
 (:decks-share-copy . "Copiar link")
 (:decks-share-copied . "Copiado")
 (:decks-add-from-flashcards-title . "Adicionar cartões")
 (:decks-add-from-flashcards-info . "Escolha um cartão para adicionar a tradução a este baralho.")
 (:decks-create-new-flashcard . "Criar novo cartão")
 (:decks-open-flashcards . "Adicionar cartões existentes")
 (:decks-filter-from . "Idioma de origem")
 (:decks-filter-to . "Idioma de destino")
 (:decks-filter-any . "Qualquer idioma")
 (:decks-filter-include-assigned . "Incluir cartões que já estão num baralho")
 (:decks-flashcards-add . "Adicionar")
 (:decks-flashcards-added . "Adicionado")
 (:decks-flashcards-in-deck . "Noutro baralho")
 (:decks-flashcards-empty . "Nenhum cartão corresponde a estes filtros.")
 (:decks-items-title . "Conteúdo do baralho")
 (:decks-col-original . "Original")
 (:decks-col-translated . "Tradução")
 (:decks-col-lang . "Língua destino")
 (:decks-no-items . "Ainda não há itens.")
 (:decks-share-page-title . "Partilhar baralho")
 (:decks-share-preview . "Pré-visualizar e importar este baralho.")
 (:decks-import-title . "Importar")
 (:decks-import-btn . "Importar baralho")
 (:starter-decks-title . "Biblioteca")
 (:starter-decks-subtitle . "Importe baralhos prontos fornecidos pela Hiisi e pela comunidade.")
 (:starter-decks-marketplace-btn . "Biblioteca")
 (:starter-decks-explanation-language . "Idioma das explicações")
 (:starter-decks-search-label . "Pesquisar")
 (:starter-decks-source-label . "Origem")
 (:starter-decks-source-all . "Todos os baralhos")
 (:starter-decks-change-language . "Alterar")
 (:starter-decks-filters-button . "Filtros")
 (:starter-decks-search-placeholder . "Pesquisar na biblioteca")
 (:starter-decks-apply-filters . "Aplicar filtros")
 (:starter-decks-select-triplet-hint . "Escolha o idioma de origem e de destino para explorar baralhos correspondentes.")
 (:starter-decks-official-badge . "Oficial")
 (:starter-decks-official-by-hiisi . "Oficial da Hiisi")
 (:starter-decks-community-badge . "Comunidade")
 (:starter-decks-by-hiisi . "Da Hiisi")
 (:starter-decks-preview-btn . "Pré-visualizar")
 (:starter-decks-card-count . "~A cartões")
 (:starter-decks-no-results . "Nenhum baralho corresponde a estes filtros.")
 (:starter-decks-source-cards-title . "Cartões neste baralho")
 (:starter-decks-more-cards-included . "+~A cartões adicionais incluídos.")
 (:starter-decks-sample-title . "Cartões de exemplo")
 (:starter-decks-generating . "A preparar o seu baralho ~A")
 (:starter-decks-generating-detail . "Vamos importá-lo assim que estiver pronto. Pode continuar a explorar a Biblioteca ou voltar dentro de instantes.")
 (:starter-decks-generation-failed . "A geração falhou")
 (:starter-decks-generation-failed-detail . "A última tentativa de geração falhou. Tente importar o baralho novamente.")
 (:starter-decks-login-detail . "Inicie sessão para importar este baralho para a sua coleção.")
 (:starter-decks-subscribe-btn . "Ver planos")
 (:starter-decks-subscribe-detail . "Os baralhos da biblioteca estão disponíveis com uma subscrição ativa ou um período experimental.")
 (:library-submit-title . "Enviar para a biblioteca")
 (:library-submit-intro . "Envie este baralho para a biblioteca para revisão administrativa antes da publicação.")
 (:library-submit-btn . "Enviar baralho")
 (:library-submit-approved . "Aprovado para a biblioteca")
 (:library-submit-approved-detail . "Este baralho está publicado na biblioteca.")
 (:library-submit-pending . "Em revisão")
 (:library-submit-pending-detail . "Este baralho foi enviado e está à espera de revisão administrativa.")
 (:library-submit-rejected . "Precisa de alterações antes da publicação")
 (:library-submit-rejected-detail . "Este envio foi rejeitado. Atualize o baralho e envie-o novamente.")
 (:library-error-empty . "Adicione pelo menos um cartão antes de enviar este baralho para a biblioteca.")
 (:library-error-missing-triplet . "Cada cartão de um envio para a biblioteca deve ter um triplo linguístico completo.")
 (:library-error-mixed-triplet . "Todos os cartões de um envio para a biblioteca devem partilhar o mesmo triplo linguístico.")
 (:starter-deck-topic-greetings-title . "Saudações e apresentações")
 (:starter-deck-topic-greetings-description . "Saudações, nomes, bases de cortesia e frases para o primeiro encontro.")
 (:starter-deck-topic-travel-title . "Viagem essencial")
 (:starter-deck-topic-travel-description . "Estações, bilhetes, preços, pedidos de ajuda e deslocações.")
 (:starter-deck-topic-numbers-title . "Números e preços")
 (:starter-deck-topic-numbers-description . "Contagem, totais, preços, andares e quantidades do dia a dia.")
 (:starter-deck-topic-time-title . "Hora e datas")
 (:starter-deck-topic-time-description . "Dias, meses, compromissos, horas e datas relativas.")
 (:starter-deck-topic-food-title . "Restaurante e comida")
 (:starter-deck-topic-food-description . "Pedir, restrições alimentares, bebidas, a conta e refeições do dia a dia fora de casa.")
 (:starter-deck-topic-emergency-title . "Emergências e saúde")
 (:starter-deck-topic-emergency-description . "Médicos, farmácias, sintomas, partes do corpo e ajuda urgente.")
 (:starter-deck-topic-directions-title . "Direções e transportes")
 (:starter-deck-topic-directions-description . "Orientação, paragens, bilhetes, plataformas e deslocações pela cidade.")
 (:starter-deck-topic-school-title . "Escola e educação")
 (:starter-deck-topic-school-description . "Aulas, trabalhos de casa, exames, material escolar e o dia a dia na escola.")
 (:starter-deck-topic-university-title . "Universidade e estudos")
 (:starter-deck-topic-university-description . "Aulas, seminários, cursos, trabalhos e o dia a dia no campus.")

 ;; Flashcards management page
 (:flashcards-title . "Os meus cartões")
 (:flashcards-subtitle . "Todos os seus cartões guardados num só lugar. Pesquise, organize e gira.")
 (:flashcards-search-placeholder . "Pesquisar cartões...")
 (:flashcards-filter-button . "Filtros")
 (:flashcards-filter-title . "Filtrar cartões")
 (:flashcards-filter-recollection . "Quão bem os conhece")
 (:flashcards-filter-any-recollection . "Qualquer nível")
 (:flashcards-hide-perfected . "Ocultar cartões dominados")
 (:flashcards-col-original . "Original")
 (:flashcards-col-translated . "Tradução")
 (:flashcards-no-cards . "Ainda não há cartões. Comece a traduzir para criar alguns!")
 (:flashcards-image-label . "Imagem")
 (:flashcards-image-upload . "Enviar imagem")
 (:flashcards-image-replace . "Substituir imagem")
 (:flashcards-image-remove . "Remover imagem")
 (:flashcards-pagination-label . "Páginas dos cartões")
 (:flashcards-pagination-status . "Página ~A de ~A")
 (:flashcards-pagination-previous . "Anterior")
 (:flashcards-pagination-next . "Seguinte")

 ;; Landing page (redesign)
 (:landing-hero-headline . "Cada palavra explicada. Cada revisão agendada. Quinze idiomas.")
 (:landing-hero-headline-v1 . "Traduza frases facilmente e leia a gramática na sua própria língua.")
 (:landing-hero-headline-v2 . "O Hiisi garante que não se esquece de cada frase que traduz.")
 (:landing-hero-headline-v3 . "Transforme as frases que traduz em vocabulário que sabe usar.")
 (:landing-hero-subheadline . "Guarde qualquer frase nos favoritos e o Hiisi dá-lhe a tradução, a gramática, a pronúncia e um cartão de estudo que volta para revisão.")
 (:landing-hero-trust-line . "14 dias gratuitos. Não é preciso cartão.")
 (:landing-credibility-languages . "Quinze línguas")
 (:landing-credibility-flashcards . "Cartões inteligentes")
 (:landing-credibility-pronunciation . "Guia de pronúncia")
 (:landing-languages-title . "Escolha a língua que anda a querer aprender")
 (:landing-video-title . "Carregue em reproduzir e conheça bem o Hiisi")
 (:landing-video-placeholder-label . "Espaço reservado para o vídeo de produto do Hiisi")
 (:landing-video-placeholder-eyebrow . "Vídeo de produto")
 (:landing-video-placeholder-copy . "Um vídeo curto de produto mostrará aqui o fluxo de favoritos, gramática, pronúncia e revisão.")
 (:landing-step-1-title . "Cole uma frase")
 (:landing-step-1-desc . "De qualquer tamanho, em qualquer um dos 15 idiomas. Recebe a tradução e uma análise gramatical de cada palavra.")
 (:landing-step-2-title . "Guarde o que vale a pena lembrar")
 (:landing-step-2-desc . "Um clique transforma uma tradução num cartão, com a frase original guardada como contexto.")
 (:landing-step-3-title . "Reveja no momento certo")
 (:landing-step-3-desc . "Repetição espaçada com SM-2, o mesmo algoritmo do Anki. Cartões com que tem mais dificuldade voltam mais cedo.")
 (:landing-feature-grammar-title . "Cada palavra explicada, na sua língua")
 (:landing-feature-grammar-desc . "As traduções vêm com caso, género, aspeto e modo analisados palavra a palavra. Partitivo finlandês, animacidade checa, aspeto polaco, contrações dativas alemãs, tudo etiquetado e ligado a uma referência gramatical.")
 (:landing-feature-srs-title . "O hábito da repetição espaçada, automatizado")
 (:landing-feature-srs-desc . "O algoritmo SM-2 adapta-se ao seu desempenho. Cartões difíceis aparecem com mais frequência. Cartões que domina aparecem menos.")
 (:landing-feature-share-title . "Os seus baralhos, ou os da comunidade")
 (:landing-feature-share-desc . "Organize as cartas em baralhos temáticos. Partilhe qualquer baralho com um link ou explore a biblioteca da comunidade para encontrar baralhos partilhados por outros.")
 (:landing-pricing-trial-note . "Inclui 14 dias de teste gratuito")
 (:landing-pricing-monthly-after . "14 dias gratuitos, depois ~A/mês")
 (:landing-pricing-annual-after . "14 dias gratuitos, depois ~A/ano")
 (:landing-faq-title . "Perguntas frequentes")
 (:landing-faq-trial-cap-q . "Quantas traduções recebo durante o teste?")
 (:landing-faq-trial-cap-a . "Recebe 200 traduções durante o teste de 14 dias. Após a subscrição, recebe 600 por mês.")
 (:landing-final-cta-title . "A sua primeira frase demora cinco segundos.")
 (:landing-final-cta-subtitle . "Cole o que quiser em finlandês, checo, polaco ou qualquer um dos outros doze idiomas. Veja o que o Hiisi faz com isso. Catorze dias gratuitos.")

 ;; Trial status (in-app)
 (:trial-status . "Teste gratuito")
 (:error-trial-quota-exceeded . "Limite de traduções de teste atingido")
 (:error-trial-quota-detail . "Usou todas as 200 traduções de teste. Subscreva para continuar a aprender.")

 ;; Custom flashcards
 (:custom-flashcard-create-title . "Criar cartão")
 (:custom-flashcard-edit-title . "Editar cartão")
 (:custom-flashcard-original . "Texto original")
 (:custom-flashcard-translated . "Tradução")
 (:custom-flashcard-lang-from . "Idioma de origem")
 (:custom-flashcard-lang-to . "Idioma de destino")
 (:custom-flashcard-note . "Nota educativa")
 (:custom-flashcard-forms . "Análise gramatical")
 (:custom-flashcard-form-term . "Termo")
 (:custom-flashcard-form-explanation . "Explicação")
 (:custom-flashcard-add-form . "Adicionar termo gramatical")
 (:custom-flashcard-remove-form . "Remover")
 (:custom-flashcard-ai-fill . "Preencher com IA")
 (:custom-flashcard-create-btn . "Criar cartão")
 (:custom-flashcard-update-btn . "Guardar alterações")

  ;; Newsletter
  (:newsletter-email-label . "Endereço de e-mail")
  (:newsletter-developer-label . "Sou programador")
  (:newsletter-developer-hint . "receber atualizações técnicas")
  (:landing-newsletter-title . "Receba novidades da Hiisi.")
  (:landing-newsletter-body . "Subscreva a newsletter para receber novidades do produto, suporte a novas línguas, baralhos iniciais e ofertas ocasionais para membros fundadores.")
  (:landing-newsletter-fine-print . "Sem spam. Apenas novidades do produto.")
  (:landing-newsletter-button . "Subscrever newsletter")
  (:newsletter-unsubscribe-page-title . "Cancelar subscrição da newsletter da Hiisi")
  (:newsletter-unsubscribe-title . "Cancelar subscrição")
  (:newsletter-unsubscribe-subtitle . "Introduza o seu e-mail para deixar de receber novidades da Hiisi.")
  (:newsletter-unsubscribe-button . "Cancelar subscrição")
  (:newsletter-feedback-email-required . "Introduza o seu endereço de e-mail.")
  (:newsletter-feedback-email-invalid . "Introduza um endereço de e-mail válido.")
  (:newsletter-feedback-already-signed-up . "Já está inscrito. Manteremos contacto!")
  (:newsletter-feedback-signed-up . "Está na lista! Enviaremos novidades ocasionais da Hiisi.")
  (:newsletter-feedback-unsubscribed . "Se este e-mail estava inscrito, foi removido das novidades da Hiisi.")
  (:newsletter-feedback-generic-error . "Algo correu mal. Tente novamente.")

  ;; Issue reporting
  (:issues-open-button . "Reportar um erro")
 (:issues-modal-title . "Reportar um problema")
 (:issues-modal-subtitle . "Descreva o que deu errado. Vamos incluir automaticamente a página atual.")
 (:issues-title-label . "Título curto")
 (:issues-title-placeholder . "Resumo breve do problema")
 (:issues-message-label . "O que aconteceu?")
 (:issues-message-placeholder . "Inclua passos para reproduzir, comportamento esperado e o que aconteceu no lugar.")
 (:issues-submit . "Enviar relato")
 (:issues-cancel . "Cancelar")
 (:issues-success . "Seu relato foi enviado. Vamos analisá-lo assim que possível.")
 (:issues-error-required . "Descreva o problema antes de enviar.")
(:issues-error-title-too-long . "O título do relato é demasiado longo. Mantenha-o com menos de 160 caracteres.")
 (:issues-error-too-long . "O texto do relato é demasiado longo. Mantenha-o abaixo de 4000 caracteres.")
 (:issues-error-rate-limit . "Muitos relatos desta origem. Aguarde e tente novamente mais tarde.")
 (:issues-error-generic . "Não foi possível enviar o relato de problema. Tente novamente.")

)
