;;; Russian translations
;;; Русские переводы

(
 ;; Language metadata (used for language picker)
 (:lang-name . "Русский")
 (:lang-flag . "🇷🇺")

 ;; Language modal (first-visit language selection)
 (:lang-modal-title . "Выберите язык")
 (:lang-modal-subtitle . "Выберите предпочтительный язык интерфейса:")

 ;; Navigation
 (:nav-translate . "Перевод")
 (:nav-review . "Повторение")
 (:nav-flashcards . "Мои карточки")
 (:nav-dashboard . "Панель")
 (:nav-decks . "Колоды")
 (:nav-logout . "Выйти")
 (:nav-home . "Главная")
 (:nav-pricing . "Цены")
 (:nav-institutions . "Для учреждений")
 (:nav-export-data . "Экспорт данных")
 (:nav-open-navigation . "Открыть навигацию")
 (:theme-light . "Светлая")
 (:theme-dark . "Тёмная")

 ;; App title and branding
 (:app-title . "Hiisi - Изучение языков")

 ;; Landing page
 (:landing-learn-more . "Узнать больше")
 (:landing-how-it-works . "Как это работает")
 (:landing-start-trial . "Начать бесплатно")
 (:landing-best-value . "Лучшая цена")

 ;; Auth pages
 (:auth-register . "Регистрация")
 (:auth-login . "Войти")
 (:auth-email . "Email")
 (:auth-password . "Пароль")
 (:auth-password-again . "Подтвердите пароль")
 (:auth-display-name . "Отображаемое имя")
 (:auth-register-title . "Регистрация в Hiisi")
 (:auth-register-subtitle . "Создать новый аккаунт")
 (:auth-login-title . "Вход в Hiisi")
 (:auth-login-subtitle . "Введите данные")
 (:auth-login-invalid-credentials . "Неверный адрес электронной почты или пароль.")
 (:auth-login-rate-limited . "Слишком много попыток входа. Подождите несколько минут и попробуйте снова.")
(:auth-register-rate-limited . "Слишком много попыток регистрации. Подождите несколько минут и попробуйте снова.")
(:auth-email-invalid . "Введите корректный адрес электронной почты.")
(:auth-password-too-short . "Пароль должен содержать не менее 8 символов.")
(:auth-passwords-mismatch . "Пароли не совпадают.")
(:auth-display-name-invalid . "Отображаемое имя должно содержать от 1 до 100 символов.")
(:auth-register-email-exists . "Учетная запись с этим адресом электронной почты уже существует.")
(:auth-register-unavailable . "Регистрация временно недоступна. Попробуйте позже.")
(:auth-register-plan-required . "Выберите тариф перед созданием аккаунта.")
(:auth-institution-register . "Вы из учебного заведения?")
(:auth-institution-title . "Регистрация через ваше учебное заведение")
(:auth-institution-subtitle . "Используйте e-mail школы или университета. Если у вашего учебного заведения есть активный доступ к Hiisi, аккаунт будет открыт после подтверждения e-mail.")
(:auth-institution-domain-unrecognized . "Мы пока не распознаем этот институциональный домен e-mail. Выберите тариф или попросите ваше заведение связаться с Hiisi.")
(:subscribe-institution-callout-title . "Используете Hiisi через школу или университет?")
(:subscribe-institution-callout-body . "Зарегистрируйтесь с институциональным e-mail, и Hiisi автоматически откроет доступ, если ваше заведение уже настроено.")
(:auth-activation-email-send-failed . "Не удалось отправить письмо для активации. Попробуйте снова.")
 (:auth-forgot-password . "Забыли пароль?")
 (:auth-no-account . "Нет аккаунта?")
 (:auth-have-account . "Уже есть аккаунт?")
 (:auth-google . "Войти через Google")
 (:auth-google-login-failed . "Не удалось войти через Google. Попробуйте ещё раз.")
 (:auth-account-created . "Аккаунт создан")
 (:auth-check-email . "Проверьте почту для активации аккаунта")
 (:auth-redirect-login . "Перенаправление на страницу входа через")
 (:auth-seconds . "секунд")
 (:auth-go-now . "Перейти сейчас")
 (:auth-not-activated . "Аккаунт не активирован. Проверьте почту для получения ссылки активации.")
 (:auth-activate-title . "Активация аккаунта")
 (:auth-activated . "Аккаунт активирован!")
 (:auth-activated-message . "Ваш аккаунт активирован. Теперь вы можете использовать Hiisi.")
 (:auth-redirecting . "Перенаправление через")
 (:auth-go-to-app . "Перейти в приложение")
 (:onboarding-title . "Как работает Hiisi")
 (:onboarding-subtitle . "Переводите реальный текст, разбирайте грамматику, сохраняйте полезные элементы и повторяйте их позже.")
 (:onboarding-translate-detail . "Начните с реального текста. Hiisi показывает перевод, сопоставленные формы и следующие учебные действия в одном месте.")
 (:onboarding-grammar-detail . "Откройте грамматический разбор, чтобы увидеть, какие формы соответствуют друг другу в предложении и какую роль играет каждая часть.")
 (:onboarding-review-detail . "Сохраняйте полезные переводы и повторяйте их позже с интервальным повторением, чтобы они закреплялись в долговременной памяти.")
 (:onboarding-decks-detail . "Объединяйте полезные элементы в колоды, делитесь ими с другими и держите связанный материал вместе.")
 (:onboarding-back . "Назад")
 (:onboarding-next . "Далее")
 (:onboarding-skip . "Пропустить обзор")
 (:auth-resend-title . "Отправить письмо активации повторно")
 (:auth-resend-subtitle . "Введите email, чтобы получить новую ссылку активации.")
 (:auth-resend-button . "Отправить письмо активации повторно")
 (:auth-resend-success . "Письмо активации отправлено!")
 (:auth-resend-success-detail . "Проверьте почту для получения новой ссылки активации.")
 (:auth-resend-rate-limited . "Пожалуйста, подождите несколько минут перед повторной отправкой.")
 (:auth-resend-cooldown . "Вы можете запросить новое письмо через ~a секунд.")
 (:auth-back-to-login . "Вернуться к входу")
 (:auth-forgot-password-title . "Забыли пароль")
 (:auth-forgot-password-subtitle . "Введите email и мы отправим вам ссылку для сброса пароля.")
 (:auth-send-reset-link . "Отправить ссылку для сброса")
 (:auth-reset-email-sent . "Ссылка отправлена!")
 (:auth-reset-email-sent-detail . "Если аккаунт с таким email существует, вы скоро получите ссылку для сброса пароля.")
 (:auth-reset-rate-limited . "Пожалуйста, подождите несколько минут перед следующим запросом сброса пароля.")
 (:auth-reset-invalid-token . "Эта ссылка для сброса недействительна или истекла.")
 (:auth-reset-password-title . "Сброс пароля")
 (:auth-reset-password-subtitle . "Введите новый пароль ниже.")
 (:auth-new-password . "Новый пароль")
 (:auth-confirm-new-password . "Подтвердите новый пароль")
 (:auth-reset-password . "Сбросить пароль")
 (:auth-password-changed . "Пароль изменён!")
 (:auth-password-changed-detail . "Ваш пароль успешно изменён. Теперь вы можете войти с новым паролем.")
 (:auth-change-password-title . "Изменить пароль")
 (:auth-change-password-subtitle . "Обновите пароль вашего аккаунта.")
 (:auth-current-password . "Текущий пароль")
 (:auth-change-password . "Изменить пароль")
 (:auth-back-to-app . "Вернуться в приложение")
 (:auth-password-updated . "Пароль обновлён!")
 (:auth-password-updated-detail . "Ваш пароль успешно обновлён.")
(:auth-current-password-invalid . "Текущий пароль введён неверно.")
(:auth-new-password-same . "Новый пароль должен отличаться от текущего пароля.")

 ;; Email copy
 (:email-common-hi . "Привет")
 (:email-common-tagline . "Hiisi - Изучайте языки через перевод")
 (:email-activation-subject . "Активируйте свою учетную запись Hiisi")
 (:email-activation-title . "Добро пожаловать в Hiisi")
 (:email-activation-body . "Спасибо за регистрацию. Активируйте свою учетную запись, перейдя по ссылке ниже:")
 (:email-activation-button . "Активировать учетную запись")
 (:email-activation-copy-link . "Или скопируйте эту ссылку")
 (:email-activation-expiry . "Срок действия этой ссылки истекает через 24 часа.")
 (:email-reset-subject . "Сбросьте пароль Hiisi")
 (:email-reset-title . "Запрос на сброс пароля")
 (:email-reset-body . "Мы получили запрос на сброс вашего пароля. Перейдите по ссылке ниже, чтобы задать новый пароль:")
 (:email-reset-button . "Сбросить пароль")
 (:email-reset-expiry . "Срок действия этой ссылки истекает через 1 час.")
 (:email-reset-ignore . "Если вы не запрашивали сброс пароля, можете проигнорировать это письмо.")
 (:email-reminder-subject-due . "Пора повторить ваши карточки Hiisi")
 (:email-reminder-subject-streak . "Поддерживайте свою серию в Hiisi")
 (:email-reminder-cards-due . "карточек готовы к повторению")
 (:email-reminder-keep-going . "С последнего повторения прошло несколько дней. Пяти минут сегодня достаточно, чтобы то, что вы уже выучили, не ускользнуло из памяти.")
 (:email-reminder-button . "Повторить сейчас")
 (:email-reminder-settings . "Управление напоминаниями")
 (:email-reminder-preview-title . "Карточки ждут вас")
 (:email-reminder-translation-label . "Перевод")
 (:email-reminder-more-due-today . "карточек ещё нужно повторить сегодня")
 (:email-trial-subject . "Как проходит ваш пробный период Hiisi?")
 (:email-trial-expiring . "Ваш бесплатный пробный период Hiisi заканчивается завтра.")
 (:email-trial-feedback . "Вам нравится Hiisi? Расскажите, что помогает вам больше всего.")
 (:email-trial-strengths . "Вы можете переводить реальные тексты, сохранять лучшие элементы в карточки и учиться с помощью интервальных повторений.")
 (:email-trial-reply . "Просто ответьте на это письмо, и ваше сообщение сразу попадет команде Hiisi.")
 (:email-trial-button . "Выбрать тариф")
 (:email-trial-manage . "Управление подпиской")
 (:email-trial-contact . "Напишите нам")
 (:email-plan-nudge-subject . "Ваши переводы ждут вас")
 (:email-plan-nudge-title . "Ваши переводы ждут вас")
 (:email-plan-nudge-intro . "Вы зарегистрировались в Hiisi, но ещё не выбрали тариф.")
 (:email-plan-nudge-benefits-intro . "Вот что вы получаете с подпиской:")
 (:email-plan-nudge-benefit-translations . "600 переводов в месяц с грамматическими разборами")
 (:email-plan-nudge-benefit-flashcards . "Неограниченные карточки с интервальным повторением")
 (:email-plan-nudge-benefit-decks . "Собственные колоды, которые можно упорядочивать и делиться ими")
 (:email-plan-nudge-pricing . "Тарифы начинаются от 10 EUR в месяц, а с годовым тарифом за 100 EUR в год вы экономите два месяца оплаты.")
 (:email-plan-nudge-feedback . "Если в Hiisi что-то не работает для вас как надо, ответьте на это письмо. Ваше сообщение сразу попадёт команде Hiisi.")
 (:email-plan-nudge-button . "Выбрать тариф")
 (:email-plan-nudge-unsubscribe . "Отписаться от этих писем")
 (:email-plan-nudge-unsubscribe-done-title . "Письма о тарифах отключены")
 (:email-plan-nudge-unsubscribe-done-body . "Вы больше не будете получать письма-напоминания о выборе тарифа.")
 (:email-plan-nudge-unsubscribe-invalid-title . "Эта ссылка недействительна")
 (:email-plan-nudge-unsubscribe-invalid-body . "Эта ссылка для отписки отсутствует, истекла или больше недействительна.")
 (:email-invite-subject . "Вас пригласили в Hiisi")
 (:email-invite-title . "Вас пригласили в Hiisi")
 (:email-invite-intro . "Вас пригласили пользоваться Hiisi бесплатно, как тестировщика, ценного друга или и то и другое.")
 (:email-invite-details . "Используйте кнопку ниже, чтобы создать учетную запись и начать изучать переводы и карточки.")
 (:email-invite-button . "Создать учетную запись")
 (:email-invite-issue-reporting . "Если что-то сломается или покажется неправильным, внизу каждой страницы есть кнопка для сообщения о проблеме.")
 (:email-issue-completed-subject . "Сообщенная вами проблема в Hiisi была исправлена")
 (:email-issue-completed-title . "Проблема исправлена")
 (:email-issue-completed-label . "Проблема")
 (:email-issue-completed-followup . "Откройте Hiisi, чтобы проверить исправление или продолжить с того места, где вы остановились.")
 (:email-issue-completed-button . "Открыть Hiisi")
 (:email-issue-completed-open-link . "Открыть страницу")

 ;; Translation page
 (:translate-title . "Перевод")
 (:translate-input-label . "Текст для перевода")
 (:translate-input-placeholder . "Введите текст для перевода...")
 (:translate-from . "Исходный язык:")
 (:translate-to . "Язык перевода:")
 (:translate-select-target-placeholder . "Выберите язык перевода")
 (:translate-submit . "Перевести")
 (:translate-auto-detect . "Любой (Автоопределение)")
 (:translate-empty-state . "Переведите слово или фразу, и здесь появятся результат, грамматический разбор и учебные действия.")
 (:translate-select-deck-placeholder . "Выберите колоду (необязательно)")
 (:translate-new-deck . "Новая колода")
 (:translate-add-to-deck . "Добавить в колоду")
 (:translate-bookmark . "Сохранить")
 (:translate-bookmarked . "Сохранено")
 (:translate-retry . "Сгенерировать заново")
 (:translate-like-tooltip . "Хороший перевод")
 (:translate-dislike-tooltip . "Плохой перевод - запросить новый")
 (:translate-dislike-confirm . "Это сгенерирует новый перевод. Продолжить?")
 (:pronunciation-label . "Произношение")
 (:pronunciation-show . "Показать произношение")
 (:pronunciation-hide . "Скрыть произношение")
 (:grammar-term-examples . "Примеры")
 (:grammar-term-related . "Связанные термины")
 (:grammar-term-modal-title . "Грамматический термин")
 (:grammar-term-empty . "Выберите выделенный термин, чтобы увидеть подробности.")
 (:extension-login-required . "Войдите в Hiisi перед использованием расширения браузера.")
 (:extension-session-invalid . "Ваш сеанс Hiisi больше недействителен. Войдите снова.")
 (:extension-activation-required . "Активируйте свой аккаунт Hiisi перед использованием расширения браузера.")
 (:extension-subscription-required . "Запустите пробный период Hiisi перед использованием расширения браузера.")

 ;; Translation and Flashcards
 (:lang-auto . "Авто")
 (:lang-unknown . "?")
 (:lang-target . "Цель")
 (:translate-deck-create-title . "Создать новую колоду")
 (:translate-deck-name-label . "Название колоды")
 (:translate-deck-name-placeholder . "например, Основы финского")
 (:translate-deck-description-label . "Описание (необязательно)")
 (:translate-deck-cancel . "Отмена")
 (:translate-deck-create . "Создать")
 (:translate-rate-label . "Оценить перевод")
 (:flashcards-delete-confirm . "Вы уверены, что хотите удалить эту карточку?")
 (:flashcards-deck-search-placeholder . "Искать колоды...")
 (:flashcards-no-decks . "Колоды пока нет. Сначала создайте одну!")
 (:flashcards-deck-cancel . "Отмена")
 (:flashcards-recollection-tooltip . "Запоминание: ~A")
 (:flashcards-recollection-poor . "Слабое")
 (:flashcards-recollection-fair . "Среднее")
 (:flashcards-recollection-normal . "Нормальное")
 (:flashcards-recollection-strong . "Сильное")
 (:flashcards-recollection-very-strong . "Очень сильное")

 ;; Flashcard review
 (:review-title . "Повторение")
 (:review-session-title . "Сессия повторения")
 (:review-session-subtitle . "Практикуйте сохранённые карточки")
 (:review-selector-title . "Выберите, что повторять")
 (:review-selector-subtitle . "Выберите колоду или языковую пару, на которой хотите сосредоточиться в этой сессии повторения.")
 (:review-by-deck . "Повторять по колоде")
 (:review-by-language-pair . "Повторять по языковой паре")
 (:review-all-cards . "Повторить все карточки")
 (:review-cards-due . "карт к повторению")
 (:review-deck-caught-up . "Всё повторено")
 (:review-all-caught-up . "Всё повторено!")

 (:review-no-cards . "Нет карточек для повторения")
 (:review-no-cards-desc . "У вас нет карточек, запланированных на повторение прямо сейчас.")
 (:review-no-cards-hint . "Переведите текст и нажмите \"Сохранить в карточки\", чтобы создать колоду!")
 (:review-start-translating . "Начать переводить")
 (:review-click-reveal . "Нажмите, чтобы показать ответ")
 (:review-grammar-breakdown . "Грамматический разбор")
 (:review-how-well . "Вы вспомнили?")
 (:review-again . "Нет")
 (:review-hard . "С трудом")
 (:review-good . "Да")
 (:review-easy . "Легко")
 (:review-progress . "Карточка ~a из ~a")
 (:review-correct-count . "Правильно")
 (:review-wrong-count . "Неправильно")
 (:landing-mockup-forgot-detail . "1-е лицо единственного числа претерита глагола \"olvidar\" (забыть)")
 (:landing-mockup-keys-detail . "Притяжательное \"mis\" с существительным женского рода множественного числа \"llaves\" (ключи)")
 (:landing-mockup-home-detail . "Идиоматическое \"en casa\" (дома) -- артикль не нужен")
 (:landing-mockup-possession-note . "В испанском языке претерит обозначает завершённые прошедшие действия. Подлежащее-местоимение обычно опускается, так как окончание глагола уже указывает на говорящего.")
 (:landing-mockup-children-detail . "Именительный падеж множественного числа существительного \"Kind\" (ребёнок) -- множественное число с -er")
 (:landing-mockup-played-detail . "3-е лицо множественного числа претерита глагола \"spielen\" (играть)")
 (:landing-mockup-garden-detail . "Дательный падеж: \"in dem\" сливается в \"im\" с существительным мужского рода \"Garten\" (сад)")
 (:landing-mockup-czech-note . "Немецкий язык использует претерит в письменном повествовании. \"Im\" -- это слияние \"in\" + \"dem\" (артикль дательного падежа).")
 (:landing-mockup-deck-title . "Основы итальянского")
 (:landing-mockup-share-deck . "Поделиться колодой")
 (:review-complete . "Сессия завершена!")
 (:review-complete-msg . "Вы повторили ~a карточек")
 (:review-again-btn . "Повторить снова")
 (:review-translate-more . "Переводить ещё")
 (:review-streak . "дней подряд")

 ;; Dashboard
 (:dashboard-title . "Панель")
 (:dashboard-cards-due . "Карточек на сегодня")
 (:dashboard-total-cards . "Всего карточек")
 (:dashboard-mastered-cards . "Освоенных карточек")
 (:dashboard-subscription . "Подписка")
 (:dashboard-subscribed-until . "Подписка до")
 (:dashboard-not-subscribed . "Нет подписки")
 (:dashboard-recent . "Недавние переводы")
 (:dashboard-no-translations . "Пока нет переводов")
 (:dashboard-streak . "Текущая серия")
 (:dashboard-days . "дней")
 (:dashboard-all-caught-up . "Все повторено!")
 (:dashboard-all-caught-up-hint . "Переводите больше, чтобы пополнять свою коллекцию.")
 (:dashboard-getting-started . "Начало работы")
 (:dashboard-tip-1 . "Переводите текст, который хотите выучить")
 (:dashboard-tip-2 . "Нажмите \"Сохранить в карточки\" на переводах, которые хотите запомнить")
 (:dashboard-tip-3 . "Регулярно повторяйте карточки — интервальное повторение помогает запоминать надолго")
 (:dashboard-tip-4 . "Оценивайте честно — это помогает алгоритму оптимально планировать повторения")

 ;; Account
 (:account-title . "Аккаунт")
 (:account-subtitle . "Здесь можно управлять профилем, подпиской, напоминаниями, экспортом и удалением аккаунта.")
 (:account-profile-subtitle . "Поддерживайте отображаемое имя и адрес электронной почты в актуальном состоянии.")
 (:account-export-subtitle . "Скачайте копию сохранённых переводов, колод и данных повторения.")
 (:account-deletion-title . "Удаление аккаунта")
 (:account-deletion-scheduled . "Ваш аккаунт запланирован к удалению на ~A.")
 (:account-deletion-cancel-hint . "Вы можете отменить удаление до этой даты, чтобы сохранить аккаунт.")
 (:account-deletion-cancel . "Отменить удаление")
 (:account-deletion-request . "Вы можете запросить удаление аккаунта в любое время. Удаление будет запланировано через 14 дней после подтверждения. Если вы передумаете, свяжитесь с поддержкой до окончания этого 14-дневного срока.")
 (:account-deletion-confirm . "Запланировать удаление аккаунта через 14 дней с сегодняшнего дня?")
 (:account-deletion-schedule . "Запланировать удаление")
 (:account-reminders-title . "Напоминания по email")
 (:account-reminders-subtitle . "Выберите, может ли Hiisi отправлять вам письма, когда у вас есть что повторить.")
 (:account-reminders-opt-out . "Отключить напоминания о повторении и продолжении")
 (:account-reminders-save . "Сохранить настройки")

 ;; Subscription
 (:subscribe-title . "Простые цены")
 (:subscribe-monthly . "Месячный")
 (:subscribe-annual . "Годовой")
 (:subscribe-founder-member . "Участник-основатель")
 (:subscribe-monthly-price . "€10")
 (:subscribe-annual-price . "€100")
 (:subscribe-founder-price . "€79")
 (:subscribe-monthly-desc . "600 переводов в месяц. Неограниченное количество карточек, колод и повторений.")
 (:subscribe-annual-desc . "Всё из месячного плана. Два месяца бесплатно.")
 (:subscribe-founder-lock . "Цена сохраняется, пока ваша подписка остаётся активной.")
 (:subscribe-founder-badge . "Ограниченное предложение")
 (:subscribe-founder-limit . "Только для первых 100 участников")
 (:subscribe-manage . "Управление подпиской")
 (:subscribe-choose-plan . "Выберите тариф")
 (:subscribe-start-today . "Начните учиться сегодня с бесплатным пробным периодом на 14 дней")
 (:subscribe-per-month . "/месяц")
 (:subscribe-per-year . "/год")
 (:subscribe-unlimited-flashcards . "Неограниченное количество карточек")
 (:subscribe-grammar-explanations . "Грамматические объяснения")
 (:subscribe-spaced-repetition . "Интервальное повторение")
 (:subscribe-activated . "Подписка активирована")
 (:subscribe-thank-you . "Ваша подписка активна. Здесь можно управлять оплатой и покупать дополнительные переводы.")
 (:subscribe-start-learning . "Начать обучение")
 (:subscribe-management . "Управление подпиской")
 (:subscribe-active . "Активна")
 (:subscribe-preapproved-access . "Предварительно одобренный доступ")
 (:subscribe-status . "Статус подписки")
 (:subscribe-status-active . "Ваша подписка активна")
 (:subscribe-status-preapproved . "Предварительно одобрен")
 (:subscribe-preapproved-detail . "Эта учётная запись использует предварительно одобренный доступ, управляемый Hiisi.")
 (:subscribe-days-remaining . "дней осталось")
 (:subscribe-renews-on . "Продление")
 (:subscribe-no-subscription . "Нет активной подписки")
 (:subscribe-access-features . "Выберите тариф, чтобы получить полный доступ и управлять оплатой в одном месте.")
 (:subscribe-view-plans . "Посмотреть тарифы")
 (:subscribe-faq-title . "Часто задаваемые вопросы")
 (:subscribe-faq-trial-q . "Есть ли пробный период?")
 (:subscribe-faq-trial-a . "Для 14-дневного пробного периода не требуется карта. Когда он закончится, выберите платный тариф, чтобы сохранить доступ.")
 (:subscribe-faq-cancel-q . "Могу ли я отменить подписку?")
 (:subscribe-faq-cancel-a . "Да, вы можете отменить подписку в любое время. Доступ сохранится до конца оплаченного периода.")
 (:subscribe-faq-payment-q . "Какие способы оплаты принимаются?")
 (:subscribe-faq-payment-a . "Мы принимаем все основные кредитные карты через Polar.")
 (:subscribe-copyright . "Все права защищены")
(:subscribe-checkout-unavailable . "Оформление оплаты временно недоступно. Попробуйте снова.")
(:subscribe-portal-unavailable . "Управление подпиской временно недоступно. Попробуйте снова.")
(:subscribe-founder-sold-out . "Предложение для участников-основателей распродано")
(:subscribe-founder-unavailable . "Предложение для участников-основателей сейчас недоступно.")
(:subscribe-checkout-cta . "Оформить подписку")

 ;; Errors and status
 (:error-generic . "Что-то пошло не так")
(:error-invalid-request . "Некорректные данные запроса.")
(:error-not-found . "Запрошенный ресурс не найден.")
(:error-forbidden . "У вас нет доступа к этому.")
(:error-rate-limited . "Подождите немного и попробуйте снова.")
 (:error-text-too-long . "Текст слишком длинный. Максимальная длина перевода — 120 символов.")
 (:error-input-too-long . "Слишком длинный ввод")
 (:error-unknown-source-lang . "Выбранный исходный язык не поддерживается.")
 (:error-unknown-target-lang . "Выбранный целевой язык не поддерживается.")
 (:error-unknown-language . "Неизвестный язык")
 (:error-translation-unavailable . "Сервис перевода временно недоступен. Пожалуйста, попробуйте позже.")
 (:error-translation-failed . "Ошибка перевода")
 (:error-translation-retry . "Не удалось сгенерировать перевод после нескольких попыток. Попробуйте переформулировать текст.")
 (:error-quota-exceeded . "Лимит переводов исчерпан")
 (:error-quota-exceeded-detail . "Вы использовали все переводы за этот месяц. Ваша квота автоматически сбрасывается каждый месяц.")
 (:quota-low-warning . "Осталось всего ~A переводов. Рассмотрите возможность покупки.")
 (:top-up-button . "Купить больше переводов")
 (:top-up-price . "5 €")
 (:top-up-amount . "300 переводов")
(:review-session-expired . "Ваша сессия повторения истекла. Начните новую сессию.")

 (:error-session-expired . "Ваша сессия истекла. Пожалуйста, войдите снова.")
 (:error-session-invalid . "Ваша сессия больше недействительна. Пожалуйста, войдите снова.")
 (:error-custom-flashcard-generation . "Не удалось создать объяснение. Попробуйте ещё раз.")
 ;; Institutions
 (:institutions-page-title . "Hiisi для школ и университетов")
 (:institutions-hero-title . "Инструменты для преподавания языков, созданные для класса")
 (:institutions-hero-subtitle . "Дайте своим студентам и ученикам общие колоды, практику с вниманием к грамматике и устойчивый ритм повторения, который вписывается в реальное преподавание.")
 (:institutions-section-title . "Почему учреждения выбирают Hiisi")
 (:institutions-section-body . "Hiisi помогает преподавателям превращать учебные материалы в направляемую практику, за которой учащиеся действительно успевают. Создавайте колоды для курса, делитесь ими по ссылке и поддерживайте работу со словарным запасом и грамматикой без лишней административной нагрузки.")
 (:institutions-benefit-1 . "Колоды для совместного использования и собственные задания, соответствующие вашей программе.")
 (:institutions-benefit-2 . "Лайки и дизлайки учащихся помогают поднимать лучшие переводы для распространённых фраз из учебных материалов.")
 (:institutions-benefit-3 . "Грамматические разборы и интервальное повторение поддерживают не только заучивание отдельных списков слов.")
 (:institutions-benefit-4 . "Поддержка с учительским взглядом от человека, который внимательно слушает и действительно заботится о потребностях класса.")
 (:institutions-request-title . "Давайте обсудим")
 (:institutions-request-subtitle . "Расскажите нам о вашей организации, языках и о том, какая учебная поддержка вам нужна. Мы ответим в течение недели.")
 (:institutions-aside-title . "Что дальше")
 (:institutions-aside-body . "Мы изучим ваши потребности и ответим в течение недели, чтобы обсудить доступ и настройку для вашего учреждения.")
 (:institutions-field-name . "Название учреждения")
 (:institutions-field-name-placeholder . "Ваш университет")
 (:institutions-field-contact-name . "Контактное лицо")
 (:institutions-field-contact-name-placeholder . "Ваше имя")
 (:institutions-field-contact-email . "Контактный email")
 (:institutions-field-contact-email-placeholder . "vy@universitet.ru")
 (:institutions-field-domains . "Домены email")
 (:institutions-field-domains-placeholder . "universitet.ru, cs.universitet.ru")
 (:institutions-field-domains-help . "Список доменов электронной почты вашей организации через запятую")
 (:institutions-field-notes . "Дополнительная информация")
 (:institutions-field-notes-placeholder . "Примерное количество студентов, предпочтительный цикл оплаты, особые требования...")
 (:institutions-submit . "Отправить запрос")
 (:institutions-success-title . "Спасибо - Hiisi для школ и университетов")
 (:institutions-success-heading . "Спасибо!")
 (:institutions-success-body . "Мы получили ваше обращение. Мы рассмотрим потребности вашей организации и свяжемся с вами в течение недели.")
 (:institutions-success-back . "Назад на главную")

 ;; Footer
 (:footer-privacy . "Политика конфиденциальности")
 (:footer-terms . "Условия использования")

 ;; Early software notice
 (:early-software-notice . "Hiisi находится на ранней стадии разработки. Нашли ошибку или есть предложение?")

 ;; Политика конфиденциальности
 (:privacy-title . "Политика конфиденциальности")
 (:privacy-updated . "Последнее обновление: январь 2026")
 (:privacy-who-title . "Кто мы")
 (:privacy-who-body . "Hiisi управляется компанией Lambda Symbolics OÜ, зарегистрированной в Эстонии. Как эстонская компания, мы соблюдаем Общий регламент по защите данных (GDPR) Европейского Союза.")
 (:privacy-collect-title . "Какие данные мы собираем")
 (:privacy-collect-intro . "Когда вы используете Hiisi, мы собираем следующую информацию:")
 (:privacy-collect-account-key . "Данные аккаунта: ")
 (:privacy-collect-account-val . "Адрес электронной почты, отображаемое имя и безопасно хэшированный пароль.")
 (:privacy-collect-learning-key . "Учебные данные: ")
 (:privacy-collect-learning-val . "Ваши переводы, сохранённые карточки и история повторений.")
 (:privacy-collect-usage-key . "Данные использования: ")
 (:privacy-collect-usage-val . "Базовые серверные логи для целей безопасности и отладки.")
 (:privacy-use-title . "Как мы используем ваши данные")
 (:privacy-use-auth-key . "Аутентификация: ")
 (:privacy-use-auth-val . "Для подтверждения вашей личности и защиты вашего аккаунта.")
 (:privacy-use-service-key . "Предоставление сервиса: ")
 (:privacy-use-service-val . "Для предоставления переводов и управления вашей коллекцией карточек.")
 (:privacy-use-ai-key . "Переводы с ИИ: ")
 (:privacy-use-ai-val . "Ваши запросы на перевод отправляются в OpenRouter для формирования ответов. OpenRouter может направлять запросы выбранному провайдеру модели. Смотрите политику конфиденциальности OpenRouter, чтобы узнать, как он обрабатывает эти данные.")
 (:privacy-third-title . "Сторонние сервисы")
 (:privacy-third-intro . "Мы используем следующие сторонние сервисы:")
 (:privacy-third-openrouter-key . "OpenRouter: ")
 (:privacy-third-openrouter-val . "Для автоматических запросов на перевод.")
 (:privacy-third-mailgun-key . "Mailgun: ")
 (:privacy-third-mailgun-val . "Для отправки писем активации аккаунта и транзакционных писем.")
 (:privacy-third-polar-key . "Polar.sh: ")
 (:privacy-third-polar-val . "Для обработки платежей по подписке.")
 (:privacy-cookies-title . "Cookie")
 (:privacy-cookies-intro . "Мы используем только необходимые cookie:")
 (:privacy-cookies-auth-key . "Токен аутентификации: ")
 (:privacy-cookies-auth-val . "Безопасный cookie с доступом только по HTTP, который сохраняет вход в систему.")
 (:privacy-cookies-lang-key . "Языковое предпочтение: ")
 (:privacy-cookies-lang-val . "Чтобы запомнить предпочтительный язык интерфейса.")
 (:privacy-retention-title . "Хранение данных")
 (:privacy-retention-body . "Ваши данные хранятся, пока у вас есть аккаунт. Когда вы запрашиваете удаление, удаление аккаунта планируется через 14 дней.")
 (:privacy-rights-title . "Ваши права (GDPR)")
 (:privacy-rights-intro . "Согласно GDPR вы имеете право:")
 (:privacy-rights-access . "Получить доступ к вашим персональным данным")
 (:privacy-rights-export . "Экспортировать ваши данные (доступно по адресу /app/api/export)")
 (:privacy-rights-correct . "Запросить исправление неточных данных")
 (:privacy-rights-delete . "Запросить удаление аккаунта и данных")
 (:privacy-rights-object . "Возражать против обработки ваших данных")
 (:privacy-rights-contact . "Чтобы воспользоваться этими правами, свяжитесь с нами по адресу")
 (:privacy-contact-title . "Контакт")
 (:privacy-contact-intro . "По вопросам конфиденциальности:")
 (:privacy-contact-email-label . "E-mail: ")
 (:privacy-address-1 . "Lambda Symbolics OÜ")
 (:privacy-address-2 . "Harju maakond, Tallinn, Kesklinna linnaosa, Tornimäe tn 5, 10145")

 ;; Условия использования
 (:terms-title . "Условия использования")
 (:terms-updated . "Последнее обновление: январь 2026")
 (:terms-1-title . "1. Описание сервиса")
 (:terms-1-body . "Hiisi - это приложение для изучения языков, которое предоставляет автоматические переводы с грамматическими объяснениями и карточки с распределённым повторением. Сервис управляется Lambda Symbolics OÜ.")
 (:terms-2-title . "2. Регистрация аккаунта")
 (:terms-2-body . "Чтобы пользоваться Hiisi, необходимо создать аккаунт с действующим адресом электронной почты. Вы несёте ответственность за безопасность данных вашего аккаунта.")
 (:terms-3-title . "3. Подписка и платежи")
 (:terms-3-body . "Hiisi предлагает платные тарифы подписки (ежемесячный и годовой). Подписки обрабатываются через Polar.sh.")
 (:terms-3-list-1 . "Подписки продлеваются автоматически, если не отменены до даты продления.")
 (:terms-3-list-2 . "Возвраты осуществляются в соответствии с применимым законодательством о защите прав потребителей.")
 (:terms-3-list-3 . "Неоплата приводит к потере доступа к премиум-функциям.")
 (:terms-4-title . "4. Допустимое использование")
 (:terms-4-intro . "Вы соглашаетесь не:")
 (:terms-4-list-1 . "Использовать сервис для незаконных целей")
 (:terms-4-list-2 . "Пытаться обходить ограничения использования или меры безопасности")
 (:terms-4-list-3 . "Передавать данные аккаунта другим лицам")
 (:terms-4-list-4 . "Использовать автоматизированные инструменты так, чтобы ухудшать работу сервиса для других")
 (:terms-5-title . "5. Контент и интеллектуальная собственность")
 (:terms-5-body-1 . "Переводы, создаваемые Hiisi, генерируются автоматически и могут быть неуникальными. Вы можете использовать свои переводы и карточки в личных целях, но не получаете исключительных авторских прав на автоматически созданный контент.")
 (:terms-5-body-2 . "Приложение Hiisi, бренд и оригинальный контент остаются собственностью Lambda Symbolics OÜ.")
 (:terms-6-title . "6. Доступность сервиса")
 (:terms-6-intro . "Hiisi предоставляется как есть. Мы не гарантируем:")
 (:terms-6-list-1 . "Бесперебойную и безошибочную работу сервиса")
 (:terms-6-list-2 . "Точность автоматически сгенерированных переводов")
 (:terms-6-list-3 . "Доступность конкретных функций")
 (:terms-6-body . "Мы можем изменять или прекращать функции в любое время.")
 (:terms-7-title . "7. Ограничение ответственности")
 (:terms-7-body-1 . "В максимально допустимой законом степени Lambda Symbolics OÜ не несёт ответственности за любые косвенные, случайные, специальные или последующие убытки, возникающие в связи с использованием Hiisi.")
 (:terms-7-body-2 . "Наша совокупная ответственность не превышает сумму, уплаченную вами за сервис за 12 месяцев, предшествующих претензии.")
 (:terms-8-title . "8. Прекращение аккаунта")
 (:terms-8-body-1 . "Мы можем приостановить или закрыть ваш аккаунт, если вы нарушите эти условия. Вы можете в любое время запросить удаление аккаунта через приложение.")
 (:terms-8-body-2 . "После запроса на удаление ваш аккаунт будет запланирован к удалению через 14 дней.")
 (:terms-9-title . "9. Изменения условий")
 (:terms-9-body . "Мы можем периодически обновлять эти условия. Продолжение использования Hiisi после изменений означает принятие новых условий.")
 (:terms-10-title . "10. Применимое право")
 (:terms-10-body . "Эти условия регулируются законодательством Эстонии. Любые споры рассматриваются судами Эстонии.")
 (:terms-contact-title . "Контакт")
 (:terms-contact-intro . "По вопросам об этих условиях:")
 (:terms-contact-email-label . "E-mail: ")
 (:terms-address-1 . "Lambda Symbolics OÜ")
 (:terms-address-2 . "Harju maakond, Tallinn, Kesklinna linnaosa, Tornimäe tn 5, 10145")

 ;; Decks
 (:decks-title . "Колоды")
 (:decks-subtitle . "Создавайте собственные колоды и делитесь ими с другими.")
 (:decks-create-title . "Создать колоду")
 (:decks-name-placeholder . "Название колоды")
 (:decks-desc-placeholder . "Описание")
 (:decks-create-btn . "Создать колоду")
 (:decks-edit-title . "Редактировать колоду")
 (:decks-edit-btn . "Редактировать колоду")
 (:decks-update-btn . "Сохранить изменения")
 (:decks-default-badge . "Автоматическая")
 (:decks-default-description . "Эта колода управляется автоматически для этой языковой пары.")
 (:decks-default-readonly . "У автоматических колод фиксированные названия и описания.")
 (:decks-delete-btn . "Удалить колоду")
 (:decks-delete-confirm . "Вы уверены, что хотите удалить эту колоду?")
 (:decks-error-name-required . "Название колоды обязательно.")
 (:decks-error-name-too-long . "Название колоды должно быть не длиннее ~A символов.")
 (:decks-error-desc-too-long . "Описание колоды должно быть не длиннее ~A символов.")
 (:decks-error-default-readonly . "Автоматические колоды нельзя редактировать.")
 (:decks-error-default-delete-forbidden . "Автоматические колоды нельзя удалять.")
 (:decks-your-title . "Ваши колоды")
 (:decks-col-updated . "Обновлено")
 (:decks-no-decks . "Колод пока нет.")
 (:decks-open-btn . "Открыть")
 (:decks-no-desc . "Без описания.")
 (:decks-share-title . "Ссылка для обмена")
 (:decks-share-info . "Любой с этой ссылкой может импортировать колоду:")
 (:decks-share-copy . "Скопировать ссылку")
 (:decks-share-copied . "Скопировано")
 (:decks-add-from-flashcards-title . "Добавить переводы")
 (:decks-add-from-flashcards-info . "Выберите карточку, чтобы добавить её перевод в эту колоду.")
 (:decks-open-flashcards . "Добавить из карточек")
 (:decks-filter-from . "Язык источника")
 (:decks-filter-to . "Язык перевода")
 (:decks-filter-any . "Любой язык")
 (:decks-filter-include-assigned . "Показывать карточки, которые уже в колоде")
 (:decks-flashcards-add . "Добавить")
 (:decks-flashcards-added . "Добавлено")
 (:decks-flashcards-in-deck . "В другой колоде")
 (:decks-flashcards-empty . "Нет карточек, соответствующих этим фильтрам.")
 (:decks-items-title . "Содержимое колоды")
 (:decks-col-original . "Оригинал")
 (:decks-col-translated . "Перевод")
 (:decks-col-lang . "Целевой язык")
 (:decks-no-items . "Элементов пока нет.")
 (:decks-share-page-title . "Поделиться колодой")
 (:decks-share-preview . "Предпросмотр и импорт этой колоды.")
 (:decks-import-title . "Импорт")
 (:decks-import-btn . "Импортировать колоду")
 (:starter-decks-title . "Библиотека")
 (:starter-decks-subtitle . "Импортируйте готовые колоды от Hiisi и сообщества.")
 (:starter-decks-marketplace-btn . "Библиотека")
 (:starter-decks-explanation-language . "Язык объяснений")
 (:starter-decks-search-label . "Поиск")
 (:starter-decks-source-label . "Источник")
 (:starter-decks-source-all . "Все колоды")
 (:starter-decks-search-placeholder . "Искать в библиотеке")
 (:starter-decks-apply-filters . "Применить фильтры")
 (:starter-decks-select-triplet-hint . "Выберите исходный и целевой язык, чтобы просматривать подходящие колоды.")
 (:starter-decks-official-badge . "Официальная")
 (:starter-decks-community-badge . "Сообщество")
 (:starter-decks-by-hiisi . "От Hiisi")
 (:starter-decks-preview-btn . "Предпросмотр")
 (:starter-decks-card-count . "~A карточек")
 (:starter-decks-no-results . "Нет колод, подходящих под эти фильтры.")
 (:starter-decks-source-cards-title . "Карточки в этой колоде")
 (:starter-decks-sample-title . "Примеры карточек")
 (:starter-decks-generating . "Колода создаётся...")
 (:starter-decks-generating-detail . "Эта колода сейчас создаётся для вашей языковой тройки. Оставьте страницу открытой или вернитесь через минуту.")
 (:starter-decks-generation-failed . "Создание не удалось")
 (:starter-decks-generation-failed-detail . "Последняя попытка создания не удалась. Попробуйте импортировать колоду ещё раз.")
 (:starter-decks-login-detail . "Войдите, чтобы импортировать эту колоду в свою коллекцию.")
 (:starter-decks-subscribe-btn . "Посмотреть тарифы")
 (:starter-decks-subscribe-detail . "Колоды библиотеки доступны при активной подписке или пробном периоде.")
 (:library-submit-title . "Отправить в библиотеку")
 (:library-submit-intro . "Отправьте эту колоду в библиотеку на проверку администратором перед публикацией.")
 (:library-submit-btn . "Отправить колоду")
 (:library-submit-approved . "Одобрено для библиотеки")
 (:library-submit-approved-detail . "Эта колода опубликована в библиотеке.")
 (:library-submit-pending . "На проверке")
 (:library-submit-pending-detail . "Эта колода отправлена и ожидает проверки администрацией.")
 (:library-submit-rejected . "Перед публикацией нужны изменения")
 (:library-submit-rejected-detail . "Эта отправка была отклонена. Обновите колоду и отправьте её снова.")
 (:library-error-empty . "Добавьте хотя бы одну карточку, прежде чем отправлять эту колоду в библиотеку.")
 (:library-error-missing-triplet . "У каждой карточки в отправке в библиотеку должна быть полная языковая тройка.")
 (:library-error-mixed-triplet . "Все карточки в отправке в библиотеку должны иметь одну и ту же языковую тройку.")
 (:starter-deck-topic-greetings-title . "Приветствия и знакомство")
 (:starter-deck-topic-greetings-description . "Приветствия, имена, вежливые базовые фразы и выражения для первой встречи.")
 (:starter-deck-topic-travel-title . "Базовые фразы для поездок")
 (:starter-deck-topic-travel-description . "Вокзалы, билеты, цены, просьбы о помощи и ориентирование в дороге.")
 (:starter-deck-topic-numbers-title . "Числа и цены")
 (:starter-deck-topic-numbers-description . "Счёт, суммы, цены, этажи и повседневные количества.")
 (:starter-deck-topic-time-title . "Время и даты")
 (:starter-deck-topic-time-description . "Дни, месяцы, встречи, время на часах и относительные даты.")
 (:starter-deck-topic-food-title . "Ресторан и еда")
 (:starter-deck-topic-food-description . "Заказ, особенности питания, напитки, счёт и повседневные приёмы пищи вне дома.")
 (:starter-deck-topic-emergency-title . "Экстренные ситуации и здоровье")
 (:starter-deck-topic-emergency-description . "Врачи, аптеки, симптомы, части тела и срочная помощь.")
 (:starter-deck-topic-directions-title . "Ориентирование и транспорт")
 (:starter-deck-topic-directions-description . "Повороты, остановки, билеты, платформы и передвижение по городу.")
 (:starter-deck-topic-school-title . "Школа и учёба")
 (:starter-deck-topic-school-description . "Уроки, домашние задания, экзамены, школьные принадлежности и повседневная школьная жизнь.")
 (:starter-deck-topic-university-title . "Университет и учёба")
 (:starter-deck-topic-university-description . "Лекции, семинары, специальности, задания и повседневная жизнь в кампусе.")

 ;; Flashcards management page
 (:flashcards-title . "Мои карточки")
 (:flashcards-subtitle . "Все ваши сохранённые карточки в одном месте. Ищите, организуйте и управляйте.")
 (:flashcards-search-placeholder . "Поиск карточек...")
 (:flashcards-filter-button . "Фильтры")
 (:flashcards-filter-title . "Фильтр карточек")
 (:flashcards-filter-recollection . "Насколько хорошо вы их знаете")
 (:flashcards-filter-any-recollection . "Любой уровень")
 (:flashcards-hide-perfected . "Скрыть полностью освоенные карточки")
 (:flashcards-col-original . "Оригинал")
 (:flashcards-col-translated . "Перевод")
 (:flashcards-no-cards . "Карточек пока нет. Начните переводить, чтобы создать их!")
 (:flashcards-image-label . "Изображение")
 (:flashcards-image-upload . "Загрузить изображение")
 (:flashcards-image-replace . "Заменить изображение")
 (:flashcards-image-remove . "Удалить изображение")

 ;; Landing page (redesign)
 (:landing-hero-headline . "Каждое слово объяснено. Каждое повторение запланировано. Пятнадцать языков.")
 (:landing-hero-subheadline . "Hiisi — это переводчик, который учит вас грамматике во время чтения, и приложение с карточками, которое само строится из того, что вы переводите.")
 (:landing-hero-trust-line . "14 дней бесплатно. Карта не требуется.")
 (:landing-credibility-languages . "15 языков")
 (:landing-credibility-ai . "Каждое слово объяснено")
 (:landing-credibility-srs . "Встроено интервальное повторение")
 (:landing-languages-title . "Поддерживаемые языки")
 (:landing-step-1-title . "Вставьте предложение")
 (:landing-step-1-desc . "Любой длины, на любом из 15 языков. Вы получите перевод и грамматический разбор каждого слова.")
 (:landing-step-2-title . "Сохраните то, что стоит запомнить")
 (:landing-step-2-desc . "Один клик превращает перевод в карточку, а исходное предложение сохраняется как контекст.")
 (:landing-step-3-title . "Повторяйте в нужный момент")
 (:landing-step-3-desc . "Интервальное повторение с SM-2, тем же алгоритмом, что и в Anki. Карточки, с которыми вы затрудняетесь, возвращаются чаще.")
 (:landing-feature-grammar-title . "Каждое слово объяснено, на вашем языке")
 (:landing-feature-grammar-desc . "Переводы сопровождаются падежом, родом, видом и наклонением, разобранными слово за словом. Финский партитив, чешская одушевлённость, польский вид, немецкие слияния дательного падежа, всё помечено и связано с грамматическим справочником.")
 (:landing-feature-srs-title . "Привычка интервального повторения автоматизированна")
 (:landing-feature-srs-desc . "Алгоритм SM-2 адаптируется к вашим результатам. Сложные карточки появляются чаще. Карточки, которые вы уже знаете, появляются реже.")
 (:landing-feature-share-title . "Ваши колоды или колоды сообщества")
 (:landing-feature-share-desc . "Систематизируйте карточки в тематические колоды. Делитесь любой колодой по ссылке или просматривайте библиотеку сообщества в поисках колод, которыми поделились другие.")
 (:landing-pricing-trial-note . "Включает 14 дней бесплатного пробного периода")
 (:landing-pricing-monthly-after . "14 дней бесплатно, затем ~A/месяц")
 (:landing-pricing-annual-after . "14 дней бесплатно, затем ~A/год")
 (:landing-faq-title . "Часто задаваемые вопросы")
 (:landing-faq-trial-cap-q . "Сколько переводов я получу в пробный период?")
 (:landing-faq-trial-cap-a . "Вы получаете 200 переводов в течение 14-дневного пробного периода. После подписки вы получаете 600 в месяц.")
 (:landing-final-cta-title . "Ваше первое предложение займёт пять секунд.")
 (:landing-final-cta-subtitle . "Вставьте что угодно на финском, чешском, польском или любом из двенадцати других языков. Посмотрите, что Hiisi с этим сделает. Четырнадцать дней бесплатно.")

 ;; Trial status (in-app)
 (:trial-status . "Бесплатный пробный период")
 (:error-trial-quota-exceeded . "Лимит пробных переводов достигнут")
 (:error-trial-quota-detail . "Вы использовали все 200 пробных переводов. Подпишитесь, чтобы продолжить обучение.")

 ;; Custom flashcards
 (:custom-flashcard-create-title . "Создать карточку")
 (:custom-flashcard-edit-title . "Редактировать карточку")
 (:custom-flashcard-original . "Исходный текст")
 (:custom-flashcard-translated . "Перевод")
 (:custom-flashcard-lang-from . "Исходный язык")
 (:custom-flashcard-lang-to . "Целевой язык")
 (:custom-flashcard-note . "Учебная заметка")
 (:custom-flashcard-forms . "Грамматический разбор")
 (:custom-flashcard-form-term . "Термин")
 (:custom-flashcard-form-explanation . "Объяснение")
 (:custom-flashcard-add-form . "Добавить грамматический термин")
 (:custom-flashcard-remove-form . "Удалить")
 (:custom-flashcard-ai-fill . "Заполнить с помощью ИИ")
 (:custom-flashcard-create-btn . "Создать карточку")
 (:custom-flashcard-update-btn . "Сохранить изменения")

  ;; Newsletter
  (:newsletter-email-label . "Адрес электронной почты")
  (:newsletter-developer-label . "Я разработчик")
  (:newsletter-developer-hint . "получать технические обновления")
  (:landing-newsletter-title . "Получайте новости Hiisi.")
  (:landing-newsletter-body . "Подпишитесь на рассылку, чтобы получать новости продукта, информацию о поддержке новых языков, стартовых колодах и редких предложениях для основателей.")
  (:landing-newsletter-fine-print . "Без спама. Только новости продукта.")
  (:landing-newsletter-button . "Подписаться на рассылку")
  (:newsletter-unsubscribe-page-title . "Отписаться от рассылки Hiisi")
  (:newsletter-unsubscribe-title . "Отписаться")
  (:newsletter-unsubscribe-subtitle . "Введите свой адрес электронной почты, чтобы больше не получать новости Hiisi.")
  (:newsletter-unsubscribe-button . "Отписаться")
  (:newsletter-feedback-email-required . "Введите адрес электронной почты.")
  (:newsletter-feedback-email-invalid . "Введите действительный адрес электронной почты.")
  (:newsletter-feedback-already-signed-up . "Вы уже подписаны. Мы будем держать вас в курсе!")
  (:newsletter-feedback-signed-up . "Вы в списке! Мы будем иногда отправлять новости Hiisi.")
  (:newsletter-feedback-unsubscribed . "Если этот адрес был подписан, он удален из новостей Hiisi.")
  (:newsletter-feedback-generic-error . "Что-то пошло не так. Попробуйте еще раз.")

  ;; Issue reporting
 (:issues-open-button . "Сообщить об ошибке")
 (:issues-modal-title . "Сообщить о проблеме")
 (:issues-modal-subtitle . "Опишите, что пошло не так. Текущая страница будет добавлена автоматически.")
 (:issues-title-label . "Краткий заголовок")
 (:issues-title-placeholder . "Краткое описание проблемы")
 (:issues-message-label . "Что произошло?")
 (:issues-message-placeholder . "Укажите шаги для воспроизведения, ожидаемое поведение и что произошло вместо этого.")
 (:issues-submit . "Отправить сообщение")
 (:issues-cancel . "Отмена")
 (:issues-success . "Ваше сообщение отправлено. Мы рассмотрим его как можно скорее.")
 (:issues-error-required . "Опишите проблему перед отправкой.")
 (:issues-error-title-too-long . "Заголовок обращения слишком длинный. Оставьте не более 160 символов.")
 (:issues-error-too-long . "Текст сообщения слишком длинный. Оставьте не более 4000 символов.")
 (:issues-error-rate-limit . "С этого источника отправлено слишком много сообщений. Подождите и попробуйте позже.")
 (:issues-error-generic . "Не удалось отправить сообщение о проблеме. Попробуйте снова.")

)
