;;; Swedish translations

(
 ;; Language metadata (used for language picker)
 (:lang-name . "Svenska")
 (:lang-flag . "🇸🇪")

 ;; Language modal (first-visit language selection)
 (:lang-modal-title . "Välj ditt språk")
 (:lang-modal-subtitle . "Välj ditt föredragna språk för gränssnittet:")

 ;; Navigation
 (:nav-translate . "Översätt")
 (:nav-review . "Repetera")
 (:nav-flashcards . "Mina kort")
 (:nav-dashboard . "Översikt")
 (:nav-decks . "Kortlekar")
 (:nav-logout . "Logga ut")
 (:nav-home . "Hem")
 (:nav-pricing . "Priser")
 (:nav-institutions . "För institutioner")
 (:nav-export-data . "Exportera data")
 (:nav-open-navigation . "Öppna navigeringen")
 (:theme-light . "Ljust")
 (:theme-dark . "Mörkt")

 ;; App title and branding
 (:app-title . "Hiisi - Språkinlärning")

 ;; Landing page
 (:landing-meta-title . "Hiisi: språkinlärningsapp med grammatik och flashcards")
 (:landing-meta-description . "Hiisi är en språkinlärningsapp. Varje mening du översätter blir ett flashcard med inbyggd grammatik, schemalagt med SM-2, Anki-algoritmen. 15 språk.")
 (:landing-learn-more . "Läs mer")
 (:landing-how-it-works . "Så fungerar det")
 (:landing-start-trial . "Kom igång med Hiisi")
 (:landing-best-value . "Bäst värde")

 ;; Auth pages
 (:auth-register . "Registrera")
 (:auth-login . "Logga in")
 (:auth-email . "E-post")
 (:auth-password . "Lösenord")
 (:auth-password-again . "Bekräfta lösenord")
 (:auth-display-name . "Visningsnamn")
 (:auth-register-title . "Registrera dig på Hiisi")
 (:auth-register-subtitle . "Skapa ett nytt konto")
 (:auth-login-title . "Logga in på Hiisi")
 (:auth-login-subtitle . "Ange dina uppgifter")
 (:auth-login-invalid-credentials . "Ogiltig e-post eller losenord.")
 (:auth-login-rate-limited . "For manga inloggningsforsok. Vanta nagra minuter och forsok igen.")
(:auth-register-rate-limited . "För många registreringsförsök. Vänta några minuter och försök igen.")
(:auth-email-invalid . "Ange en giltig e-postadress.")
(:auth-password-too-short . "Lösenordet måste vara minst 8 tecken långt.")
(:auth-passwords-mismatch . "Lösenorden matchar inte.")
(:auth-display-name-invalid . "Visningsnamnet måste vara mellan 1 och 100 tecken långt.")
(:auth-register-email-exists . "Det finns redan ett konto med den här e-postadressen.")
(:auth-register-unavailable . "Registrering är tillfälligt otillgänglig. Försök igen senare.")
(:auth-register-plan-required . "Välj en plan innan du skapar ett konto.")
(:auth-preapproved-email-unrecognized . "Använd e-postadressen från din inbjudan, eller välj en plan innan du skapar ett konto.")
(:auth-institution-register . "Kommer du från en institution?")
(:auth-institution-stage-title . "Institutionsåtkomst")
(:auth-institution-stage-subtitle . "Använd din skolas eller ditt universitets e-postadress. Behöriga konton låses upp via institutionen efter e-postverifiering.")
(:auth-institution-title . "Registrera dig via din institution")
(:auth-institution-subtitle . "Använd din skolas eller ditt universitets e-postadress. Om din institution redan är konfigurerad i Hiisi låses kontot upp via den efter e-postverifiering; den individuella 14-dagars provperioden gäller registrering med en personlig plan.")
(:auth-institution-benefit-email . "Använd din skolas eller ditt universitets e-postadress.")
(:auth-institution-benefit-access . "Behöriga konton får institutionsåtkomst efter e-postverifiering.")
(:auth-institution-benefit-fallback . "Om domänen inte känns igen, välj en individuell plan eller be din institution kontakta Hiisi.")
(:auth-see-included . "Se vad som ingår")
(:auth-institution-check-access . "Kontrollera åtkomst")
(:auth-institution-email-eligible-title . "Institutionsåtkomst bekräftad")
(:auth-institution-email-eligible-detail . "Fortsätt med den här e-postadressen för att skapa ditt konto. Åtkomsten låses upp efter e-postverifiering.")
(:auth-institution-change-email . "Använd en annan e-postadress")
(:auth-institution-outcome-note . "Om din skola eller ditt universitet ger tillgång till Hiisi låses kontot upp efter e-postverifiering. Om domänen inte är behörig väljer du en personlig plan för att starta provperioden på 14 dagar.")
(:auth-institution-personal-plan-link . "Visa personliga planer")
(:auth-institution-domain-unrecognized . "Vi känner inte igen den institutionella e-postdomänen än. Välj en personlig plan för att starta provperioden på 14 dagar, eller be din institution kontakta Hiisi.")
(:subscribe-institution-callout-title . "Använder du Hiisi via en skola eller ett universitet?")
(:subscribe-institution-callout-body . "Registrera dig med din institutionella e-postadress, så låser Hiisi upp åtkomst automatiskt om din institution redan är konfigurerad.")
(:auth-activation-email-send-failed . "Det gick inte att skicka aktiveringsmejlet. Försök igen.")
 (:auth-forgot-password . "Glömt lösenordet?")
 (:auth-no-account . "Har du inget konto?")
 (:auth-have-account . "Har du redan ett konto?")
 (:auth-google . "Fortsätt med Google")
 (:auth-google-login-failed . "Det gick inte att logga in med Google. Försök igen.")
 (:auth-account-created . "Konto skapat!")
 (:auth-check-email . "Kontrollera din e-post för aktiveringslänken.")
 (:auth-redirect-login . "Omdirigerar till inloggning om")
 (:auth-seconds . "sekunder")
 (:auth-go-now . "Gå nu")
 (:auth-not-activated . "Kontot är inte aktiverat. Kontrollera din e-post för aktiveringslänken.")
 (:auth-activate-title . "Aktivera ditt konto")
 (:auth-activated . "Konto aktiverat!")
 (:auth-activated-message . "Ditt konto har aktiverats. Du kan nu använda Hiisi.")
 (:auth-redirecting . "Omdirigerar om")
 (:auth-go-to-app . "Gå till appen")
 (:onboarding-title . "Hur Hiisi fungerar")
 (:onboarding-subtitle . "Översätt verklig text, granska grammatiken, spara användbara poster och repetera dem senare.")
 (:onboarding-translate-detail . "Börja med verklig text. Hiisi visar översättningen, de matchade formerna och nästa studieåtgärder på ett ställe.")
 (:onboarding-grammar-detail . "Öppna grammatikgenomgången för att se vilka former som motsvarar varandra i meningen och vilken funktion varje del har.")
 (:onboarding-review-detail . "Spara användbara översättningar och repetera dem senare med utspridd repetition så att de stannar i långtidsminnet.")
 (:onboarding-decks-detail . "Samla användbara poster i kortlekar, dela dem med andra och håll ihop material som hör samman.")
 (:onboarding-back . "Tillbaka")
 (:onboarding-next . "Nästa")
 (:onboarding-skip . "Hoppa över guiden")
 (:auth-resend-title . "Skicka aktiveringsmail igen")
 (:auth-resend-subtitle . "Ange din e-postadress för att få en ny aktiveringslänk.")
 (:auth-resend-button . "Skicka aktiveringsmail igen")
 (:auth-resend-success . "Aktiveringsmail skickat!")
 (:auth-resend-success-detail . "Kontrollera din inkorg för den nya aktiveringslänken.")
 (:auth-resend-rate-limited . "Vänta några minuter innan du begär ett nytt aktiveringsmail.")
 (:auth-resend-cooldown . "Du kan begära ett nytt mail om ~a sekunder.")
 (:auth-back-to-login . "Tillbaka till inloggning")
 (:auth-forgot-password-title . "Glömt lösenord")
 (:auth-forgot-password-subtitle . "Ange din e-postadress så skickar vi dig en länk för att återställa ditt lösenord.")
 (:auth-send-reset-link . "Skicka återställningslänk")
 (:auth-reset-email-sent . "Länk skickad!")
 (:auth-reset-email-sent-detail . "Om ett konto finns med den e-postadressen kommer du snart att få en länk för att återställa lösenordet.")
 (:auth-reset-rate-limited . "Vänta några minuter innan du begär en ny lösenordsåterställning.")
 (:auth-reset-invalid-token . "Denna återställningslänk är ogiltig eller har upphört.")
 (:auth-reset-password-title . "Återställ lösenord")
 (:auth-reset-password-subtitle . "Ange ditt nya lösenord nedan.")
 (:auth-new-password . "Nytt lösenord")
 (:auth-confirm-new-password . "Bekräfta nytt lösenord")
 (:auth-reset-password . "Återställ lösenord")
 (:auth-password-changed . "Lösenord ändrat!")
 (:auth-password-changed-detail . "Ditt lösenord har ändrats. Du kan nu logga in med ditt nya lösenord.")
 (:auth-change-password-title . "Ändra lösenord")
 (:auth-change-password-subtitle . "Uppdatera ditt kontolösenord.")
 (:auth-current-password . "Nuvarande lösenord")
 (:auth-change-password . "Ändra lösenord")
 (:auth-back-to-app . "Tillbaka till appen")
 (:auth-password-updated . "Lösenord uppdaterat!")
 (:auth-password-updated-detail . "Ditt lösenord har uppdaterats.")
(:auth-current-password-invalid . "Det nuvarande lösenordet är fel.")
(:auth-new-password-same . "Det nya lösenordet måste skilja sig från det nuvarande lösenordet.")

 ;; Email copy
 (:email-common-hi . "Hej")
 (:email-common-tagline . "Hiisi - Lär dig genom översättning")
 (:email-activation-subject . "Aktivera ditt Hiisi-konto")
 (:email-activation-title . "Välkommen till Hiisi")
 (:email-activation-body . "Tack för att du registrerade dig. Aktivera ditt konto genom att klicka på länken nedan:")
 (:email-activation-button . "Aktivera konto")
 (:email-activation-copy-link . "Eller kopiera den här länken")
 (:email-activation-expiry . "Den här länken upphör att gälla om 24 timmar.")
 (:email-reset-subject . "Återställ ditt Hiisi-lösenord")
 (:email-reset-title . "Begäran om återställning av lösenord")
 (:email-reset-body . "Vi har fått en begäran om att återställa ditt lösenord. Klicka på länken nedan för att ange ett nytt lösenord:")
 (:email-reset-button . "Återställ lösenord")
 (:email-reset-expiry . "Den här länken upphör att gälla om 1 timme.")
 (:email-reset-ignore . "Om du inte begärde en återställning av lösenordet kan du ignorera det här mejlet.")
 (:email-reminder-subject-due . "Dags att repetera dina Hiisi-kort")
 (:email-reminder-subject-streak . "Behåll din Hiisi-svit")
 (:email-reminder-cards-due . "kort redo för repetition")
 (:email-reminder-keep-going . "Det har gått några dagar sedan din senaste repetition. Fem minuter i dag räcker för att det du redan har lärt dig inte ska glida bort.")
 (:email-reminder-button . "Repetera nu")
 (:email-reminder-settings . "Hantera påminnelser")
 (:email-reminder-preview-title . "Kort som väntar på dig")
 (:email-reminder-translation-label . "Översättning")
 (:email-reminder-more-due-today . "fler kort att repetera idag")
 (:email-trial-subject . "Hur går din Hiisi-provperiod?")
 (:email-trial-expiring . "Din kostnadsfria Hiisi-provperiod slutar i morgon.")
 (:email-trial-feedback . "Tycker du om Hiisi? Berätta vad som har hjälpt dig mest.")
 (:email-trial-strengths . "Du kan översätta riktiga texter, spara de bästa delarna som flashcards och lära dig med utspridd repetition.")
 (:email-trial-reply . "Svara på det här mejlet så går ditt meddelande direkt till Hiisi-teamet.")
 (:email-trial-button . "Välj abonnemang")
 (:email-trial-manage . "Hantera abonnemang")
 (:email-trial-contact . "Skriv till oss")
 (:email-plan-nudge-subject . "Dina översättningar väntar")
 (:email-plan-nudge-title . "Dina översättningar väntar")
 (:email-plan-nudge-intro . "Du har registrerat dig på Hiisi men har ännu inte valt något abonnemang.")
 (:email-plan-nudge-benefits-intro . "Det här får du med en prenumeration:")
 (:email-plan-nudge-benefit-translations . "600 översättningar per månad med grammatiska genomgångar")
 (:email-plan-nudge-benefit-flashcards . "Obegränsade flashcards med utspridd repetition")
 (:email-plan-nudge-benefit-decks . "Egna kortlekar som du kan organisera och dela")
 (:email-plan-nudge-pricing . "Planerna börjar på 10 EUR per månad, eller spara med årsplanen för 100 EUR per år (två månader gratis).")
 (:email-plan-nudge-feedback . "Om något med Hiisi inte fungerar för dig, svara på det här mejlet. Ditt meddelande går direkt till Hiisi-teamet.")
 (:email-plan-nudge-button . "Välj abonnemang")
 (:email-plan-nudge-unsubscribe . "Avsluta de här mejlen")
 (:email-plan-nudge-unsubscribe-done-title . "Mejl om abonnemang avstängda")
 (:email-plan-nudge-unsubscribe-done-body . "Du kommer inte att få fler påminnelsemejl om att välja abonnemang.")
 (:email-plan-nudge-unsubscribe-invalid-title . "Den här länken är inte giltig")
 (:email-plan-nudge-unsubscribe-invalid-body . "Den här avregistreringslänken saknas, har gått ut eller är inte längre giltig.")
 (:email-invite-subject . "Du har blivit inbjuden till Hiisi")
 (:email-invite-title . "Du har blivit inbjuden till Hiisi")
 (:email-invite-intro . "Du har blivit inbjuden att använda Hiisi gratis som testare, uppskattad vän eller båda delarna.")
 (:email-invite-details . "Använd knappen nedan för att skapa ditt konto och börja utforska översättningar och flashcards.")
 (:email-invite-button . "Skapa konto")
 (:email-invite-issue-reporting . "Om något går sönder eller känns fel finns det en knapp för att rapportera problem längst ner på varje sida.")
 (:email-issue-completed-subject . "Ditt Hiisi-problem har åtgärdats")
 (:email-issue-completed-title . "Problemet är åtgärdat")
 (:email-issue-completed-label . "Problem")
 (:email-issue-completed-followup . "Öppna Hiisi för att kontrollera rättelsen eller fortsätta där du slutade.")
 (:email-issue-completed-button . "Öppna Hiisi")
 (:email-issue-completed-open-link . "Öppna sidan")

 ;; Translation page
 (:translate-title . "Översätt")
 (:landing-public-translate-title . "Prova här")
 (:landing-public-translate-cta-title . "Fortsätt i samma takt")
 (:landing-public-translate-cta-body . "Spara översättningar som studiekort och repetera dem senare.")
 (:landing-public-translate-cta-button . "Starta gratis provperiod och fortsätt lära dig")
 (:translate-input-label . "Text att översätta")
 (:translate-input-placeholder . "Skriv text att översätta...")
 (:translate-from . "Källspråk:")
 (:translate-to . "Målspråk:")
 (:translate-select-target-placeholder . "Välj målspråk")
 (:translate-submit . "Översätt")
 (:translate-auto-detect . "Valfritt (Identifiera automatiskt)")
 (:translate-empty-state . "Översätt ett ord eller en fras så ser du resultatet, grammatikgenomgången och studieåtgärderna här.")
 (:translate-select-deck-placeholder . "Välj kortlek (valfritt)")
 (:translate-new-deck . "Ny kortlek")
 (:translate-add-to-deck . "Lägg till i kortlek")
 (:translate-bookmark . "Spara")
 (:translate-bookmarked . "Sparat")
 (:translate-retry . "Generera igen")
 (:translate-like-tooltip . "Bra översättning")
 (:translate-dislike-tooltip . "Dålig översättning - begär en ny")
 (:translate-dislike-confirm . "Detta genererar en ny översättning. Fortsätta?")
 (:pronunciation-label . "Uttal")
 (:pronunciation-show . "Visa uttal")
 (:pronunciation-hide . "Dölj uttal")
 (:grammar-term-examples . "Exempel")
 (:grammar-term-related . "Relaterade termer")
 (:grammar-term-modal-title . "Grammatikterm")
 (:grammar-term-empty . "Välj en markerad term för att se detaljer.")
 (:extension-login-required . "Logga in på Hiisi innan du använder webbläsartillägget.")
 (:extension-session-invalid . "Din Hiisi-session är inte längre giltig. Logga in igen.")
 (:extension-activation-required . "Aktivera ditt Hiisi-konto innan du använder webbläsartillägget.")
 (:extension-subscription-required . "Starta en Hiisi-provperiod innan du använder webbläsartillägget.")

 ;; Translation and Flashcards
 (:lang-auto . "Auto")
 (:lang-unknown . "?")
 (:lang-target . "Mål")
 (:translate-deck-create-title . "Skapa ny kortlek")
 (:translate-deck-name-label . "Kortlekens namn")
 (:translate-deck-name-placeholder . "t.ex. Finska grunder")
 (:translate-deck-description-label . "Beskrivning (valfri)")
 (:translate-deck-cancel . "Avbryt")
 (:translate-deck-create . "Skapa")
 (:translate-rate-label . "Betygsätt översättning")
 (:flashcards-delete . "Ta bort")
 (:flashcards-delete-confirm . "Är du säker på att du vill ta bort det här kortet?")
 (:flashcards-deck-search-placeholder . "Sök kortlekar...")
 (:flashcards-no-decks . "Inga kortlekar ännu. Skapa en först!")
 (:flashcards-deck-cancel . "Avbryt")
 (:flashcards-recollection-tooltip . "Minnesstyrka: ~A")
 (:flashcards-recollection-poor . "Svag")
 (:flashcards-recollection-fair . "Måttlig")
 (:flashcards-recollection-normal . "Normal")
 (:flashcards-recollection-strong . "Stark")
 (:flashcards-recollection-very-strong . "Mycket stark")

 ;; Flashcard review
 (:review-title . "Repetera")
 (:review-session-title . "Repetitionssession")
 (:review-session-subtitle . "Öva på dina sparade flashcards")
 (:review-selector-title . "Välj vad du vill repetera")
 (:review-selector-subtitle . "Välj en kortlek eller ett språkpar att fokusera på i repetitionspasset.")
 (:review-by-deck . "Repetera efter kortlek")
 (:review-by-language-pair . "Repetera efter språkpar")
 (:review-all-cards . "Repetera alla kort")
 (:review-cards-due . "kort att repetera")
 (:review-deck-caught-up . "Allt repeterat")
 (:review-all-caught-up . "Allt repeterat!")

 (:review-no-cards . "Inga kort att repetera")
 (:review-no-cards-desc . "Du har inga flashcards som behöver repeteras just nu.")
 (:review-no-cards-hint . "Översätt lite text och klicka \"Spara som flashcard\" för att bygga din kortlek!")
 (:review-start-translating . "Börja översätta")
 (:review-click-reveal . "Klicka för att visa svaret")
 (:review-grammar-breakdown . "Grammatikförklaring")
 (:review-how-well . "Kom du ihåg det?")
 (:review-again . "Nej")
 (:review-hard . "Knappt")
 (:review-good . "Ja")
 (:review-easy . "Lätt")
 (:review-progress . "Kort ~a av ~a")
 (:review-correct-count . "Rätt")
 (:review-wrong-count . "Fel")
 (:landing-mockup-forgot-detail . "1:a person singularis preteritum av \"olvidar\" (att glömma)")
 (:landing-mockup-keys-detail . "Possessiv \"mis\" med feminint pluralsubstantiv \"llaves\" (nycklar)")
 (:landing-mockup-home-detail . "Idiomatiskt \"en casa\" (hemma) -- ingen artikel behövs")
 (:landing-mockup-possession-note . "I spanskan markerar preteritum avslutade handlingar i det förflutna. Subjektspronomenet utelämnas vanligtvis eftersom verbändelsen redan anger talaren.")
 (:landing-mockup-children-detail . "Nominativ plural av \"Kind\" (barn) -- pluralformen lägger till -er")
 (:landing-mockup-played-detail . "3:e person pluralis preteritum av \"spielen\" (att leka)")
 (:landing-mockup-garden-detail . "Dativ: \"in dem\" dras samman till \"im\", med maskulint substantiv \"Garten\" (trädgård)")
 (:landing-mockup-czech-note . "Tyskan använder preteritum i skriftligt berättande. \"Im\" är en sammandragning av \"in\" + \"dem\" (dativartikel).")
 (:landing-mockup-deck-title . "Italienska grunder")
 (:landing-mockup-share-deck . "Dela kortlek")
 (:review-complete . "Session klar!")
 (:review-complete-msg . "Du repeterade ~a kort")
 (:review-again-btn . "Repetera igen")
 (:review-translate-more . "Översätt mer")
 (:review-streak . "dagar i rad")

 ;; Dashboard
 (:dashboard-title . "Översikt")
 (:dashboard-welcome-title . "Översätt din första text")
 (:dashboard-welcome-subtitle . "Översätt en användbar fras, spara den i en kortlek och repetera den när det behövs.")
 (:dashboard-take-quick-tour . "Ta en snabb rundtur")
 (:dashboard-cards-due . "Kort för idag")
 (:dashboard-total-cards . "Totalt antal kort")
 (:dashboard-mastered-cards . "Bemästrade kort")
 (:dashboard-subscription . "Prenumeration")
 (:dashboard-subscribed-until . "Prenumererar till")
 (:dashboard-trial-ends . "Provperioden slutar")
 (:dashboard-not-subscribed . "Ingen prenumeration")
 (:dashboard-recent . "Senaste översättningar")
 (:dashboard-no-translations . "Inga översättningar än")
 (:dashboard-streak . "Nuvarande svit")
 (:dashboard-days . "dagar")
 (:dashboard-all-caught-up . "Allt är avklarat!")
 (:dashboard-all-caught-up-hint . "Översätt mer för att bygga upp din samling.")
 (:dashboard-no-cards-title . "Skapa dina första studiekort")
 (:dashboard-no-cards-hint . "Översätt text och spara användbara fraser för att bygga upp din samling.")
 (:dashboard-first-use-checklist-title . "Första stegen")
 (:dashboard-first-use-checklist-translate . "Gör din första översättning")
 (:dashboard-first-use-checklist-card . "Spara ditt första kort")
 (:dashboard-first-use-checklist-review . "Slutför din första repetition")
 (:dashboard-getting-started . "Kom igång")
 (:dashboard-tip-1 . "Översätt text du vill lära dig")
 (:dashboard-tip-2 . "Klicka \"Spara som flashcard\" på översättningar du vill komma ihåg")
 (:dashboard-tip-3 . "Repetera dina flashcards regelbundet - spaced repetition hjälper dig minnas långsiktigt")
 (:dashboard-tip-4 . "Bedöm ärligt - det hjälper algoritmen schemalägga dina repetitioner optimalt")

 ;; Account
 (:account-title . "Konto")
 (:account-subtitle . "Hantera profil, prenumeration, påminnelser, exporter och radering av konto här.")
 (:account-profile-subtitle . "Håll ditt visningsnamn och din e-postadress uppdaterade.")
 (:account-export-subtitle . "Ladda ner en kopia av dina sparade översättningar, kortlekar och repetitionsdata.")
 (:account-deletion-title . "Kontoradering")
 (:account-deletion-scheduled . "Ditt konto är planerat att raderas den ~A.")
 (:account-deletion-cancel-hint . "Du kan avbryta före detta datum för att behålla kontot.")
 (:account-deletion-cancel . "Avbryt radering")
 (:account-deletion-request . "Du kan begära att kontot raderas när som helst. Radering planeras 14 dagar efter bekräftelse. Om du ångrar dig, kontakta support innan den här 14-dagarsperioden löper ut.")
 (:account-deletion-confirm . "Planera kontoradering om 14 dagar från i dag?")
 (:account-deletion-schedule . "Planera radering")
 (:account-reminders-title . "E-postpåminnelser")
 (:account-reminders-subtitle . "Välj om Hiisi får mejla dig när det finns något att repetera.")
 (:account-reminders-opt-out . "Stäng av påminnelser om repetition och fortsättning")
 (:account-reminders-save . "Spara inställningar")

 ;; Subscription
 (:subscribe-title . "Enkla priser")
 (:subscribe-monthly . "Månadsvis")
 (:subscribe-annual . "Årsvis")
 (:subscribe-founder-member . "Grundarmedlem")
 (:subscribe-monthly-price . "€10")
 (:subscribe-annual-price . "€100")
 (:subscribe-founder-price . "€79")
 (:subscribe-founder-monthly-equivalent . "€6,58/månad, faktureras årsvis")
 (:subscribe-founder-savings . "Spara €41/år jämfört med månadsbetalning")
 (:subscribe-monthly-billing-equivalent . "€10/månad, faktureras månadsvis")
 (:subscribe-monthly-billing-note . "Flexibel månadsbetalning")
 (:landing-pricing-comparison-title . "Snabb jämförelse")
 (:subscribe-monthly-desc . "600 översättningar per månad. Obegränsat med flashkort, kortlekar och repetitioner.")
 (:subscribe-annual-desc . "Allt från månadsplanen. Två månader gratis.")
 (:subscribe-founder-lock . "Priset är låst så länge din prenumeration förblir aktiv.")
 (:subscribe-founder-badge . "Begränsat erbjudande")
 (:subscribe-founder-limit . "Begränsat till de första 100 medlemmarna")
 (:subscribe-manage . "Hantera prenumeration")
 (:subscribe-choose-plan . "Välj din plan")
 (:subscribe-start-today . "Börja lära dig idag med 14 dagars gratis provperiod")
 (:subscribe-per-month . "per månad")
 (:subscribe-per-year . "per år")
 (:subscribe-unlimited-flashcards . "Obegränsade flashcards")
 (:subscribe-grammar-explanations . "Grammatikförklaringar")
 (:subscribe-spaced-repetition . "Spaced repetition-schemaläggning")
 (:subscribe-activated . "Prenumeration aktiverad!")
 (:subscribe-thank-you . "Din prenumeration är aktiv. Här kan du hantera betalningen och köpa fler översättningar.")
 (:subscribe-start-learning . "Börja lära dig")
 (:subscribe-management . "Hantera prenumeration")
 (:subscribe-active . "Aktiv")
 (:subscribe-preapproved-access . "Förhandsgodkänd åtkomst")
 (:subscribe-status . "Prenumerationsstatus")
 (:subscribe-status-active . "Din prenumeration är aktiv")
 (:subscribe-status-preapproved . "Förhandsgodkänd")
 (:subscribe-preapproved-detail . "Det här kontot använder förhandsgodkänd åtkomst som hanteras av Hiisi.")
 (:subscribe-days-remaining . "dagar kvar")
 (:subscribe-renews-on . "Förnyas den")
 (:subscribe-no-subscription . "Ingen aktiv prenumeration")
 (:subscribe-access-features . "Välj en plan för full åtkomst och betalningshantering på ett ställe.")
 (:subscribe-view-plans . "Visa planer")
 (:subscribe-faq-title . "Vanliga frågor")
 (:subscribe-faq-trial-q . "Finns det en gratis provperiod?")
 (:subscribe-faq-trial-a . "Provperioden på 14 dagar kräver inget kort. När den är slut väljer du en betald plan för att behålla full åtkomst.")
 (:subscribe-faq-cancel-q . "Kan jag avbryta när som helst?")
 (:subscribe-faq-cancel-a . "Ja, du kan avbryta din prenumeration när som helst. Du behåller tillgång till slutet av faktureringsperioden.")
 (:subscribe-faq-payment-q . "Vilka betalningsmetoder accepteras?")
 (:subscribe-faq-payment-a . "Vi accepterar alla större kreditkort och PayPal.")
 (:subscribe-copyright . "© 2025 Hiisi. Alla rättigheter förbehållna.")
(:subscribe-checkout-unavailable . "Kassa är tillfälligt otillgänglig. Försök igen.")
(:subscribe-portal-unavailable . "Abonnemangshantering är tillfälligt otillgänglig. Försök igen.")
(:subscribe-founder-sold-out . "Erbjudandet för grundarmedlemmar är slutsålt")
(:subscribe-founder-unavailable . "Erbjudandet för grundarmedlemmar är inte tillgängligt just nu.")
(:subscribe-checkout-cta . "Prenumerera")

 ;; Errors and status
 (:error-generic . "Något gick fel")
(:error-invalid-request . "Ogiltiga begärandedata.")
(:error-not-found . "Den begärda resursen hittades inte.")
(:error-forbidden . "Du har inte åtkomst till detta.")
(:error-rate-limited . "Vänta en stund och försök igen.")
 (:error-text-too-long . "Texten är för lång. Maximal översättningslängd är 120 tecken.")
 (:error-input-too-long . "Inmatningen är för lång")
 (:error-unknown-source-lang . "Källspråket du valde stöds inte.")
 (:error-unknown-target-lang . "Målspråket du valde stöds inte.")
 (:error-unknown-language . "Okänt språk")
 (:error-translation-unavailable . "Översättningstjänsten är tillfälligt otillgänglig. Försök igen om en stund.")
 (:error-translation-failed . "Översättningen misslyckades")
 (:error-translation-retry . "Kunde inte generera en översättning efter flera försök. Försök omformulera din text.")
 (:error-quota-exceeded . "Översättningsgräns nådd")
 (:error-quota-exceeded-detail . "Du har använt alla dina översättningar för denna månad. Din kvot återställs automatiskt varje månad.")
 (:quota-low-warning . "Endast ~A översättningar kvar. Överväg att köpa fler.")
 (:top-up-button . "Köp fler översättningar")
 (:top-up-price . "5 €")
 (:top-up-amount . "300 översättningar")
(:review-session-expired . "Din repetitionssession har gått ut. Starta en ny session.")

 (:error-session-expired . "Din session har gått ut. Logga in igen.")
 (:error-session-invalid . "Din session är inte längre giltig. Logga in igen.")
 (:error-custom-flashcard-generation . "Vi kunde inte skapa förklaringen. Försök igen.")
 ;; Institutions
 (:institutions-page-title . "Hiisi för skolor och universitet")
 (:institutions-hero-title . "Språkundervisningsverktyg byggda för klassrummet")
 (:institutions-hero-subtitle . "Ge dina studenter delbara kortlekar, grammatikmedveten träning och stabila repetitionsrutiner som fungerar i verklig undervisning.")
 (:institutions-section-title . "Varför institutioner använder Hiisi")
 (:institutions-section-body . "Hiisi hjälper lärare att förvandla kursmaterial till vägledd träning som studenter faktiskt orkar följa. Skapa kortlekar för en kurs, dela dem med en länk och stöd arbete med ordförråd och grammatik utan extra administrativ belastning.")
 (:institutions-benefit-1 . "Delbara kortlekar och egna uppgifter som passar er undervisning.")
 (:institutions-benefit-2 . "Studenternas gilla- och ogilla-markeringar hjälper de starkaste översättningarna att lyftas fram för vanliga fraser i undervisningen.")
 (:institutions-benefit-3 . "Grammatikuppdelningar och utspridd repetition stöder mer än att bara memorera fristående ordlistor.")
 (:institutions-benefit-4 . "Lärarnära stöd från någon som lyssnar noga och bryr sig om behoven i klassrummet.")
 (:institutions-request-title . "Låt oss prata")
 (:institutions-request-subtitle . "Berätta om er institution, era språk och vilken undervisningsstöd ni behöver. Vi återkommer inom en vecka.")
 (:institutions-aside-title . "Vad händer härnäst")
 (:institutions-aside-body . "Vi granskar era behov och svarar inom en vecka för att diskutera åtkomst och upplägg för er institution.")
 (:institutions-field-name . "Institutionsnamn")
 (:institutions-field-name-placeholder . "Ditt universitet")
 (:institutions-field-contact-name . "Kontaktperson")
 (:institutions-field-contact-name-placeholder . "Ditt namn")
 (:institutions-field-contact-email . "Kontakt-e-post")
 (:institutions-field-contact-email-placeholder . "du@universitet.se")
 (:institutions-field-domains . "E-postdomäner")
 (:institutions-field-domains-placeholder . "universitet.se, cs.universitet.se")
 (:institutions-field-domains-help . "Kommaseparerad lista över e-postdomäner för din institution")
 (:institutions-field-notes . "Ytterligare information")
 (:institutions-field-notes-placeholder . "Uppskattat antal studenter, föredragen faktureringscykel, särskilda krav...")
 (:institutions-submit . "Skicka förfrågan")
 (:institutions-success-title . "Tack - Hiisi för skolor och universitet")
 (:institutions-success-heading . "Tack!")
 (:institutions-success-body . "Vi har tagit emot er förfrågan. Vi går igenom institutionens behov och återkommer inom en vecka.")
 (:institutions-success-back . "Tillbaka till startsidan")

 ;; Footer
 (:footer-privacy . "Integritetspolicy")
 (:footer-terms . "Användarvillkor")

 ;; Early software notice
 (:early-software-notice . "Hiisi är under tidig utveckling. Hittat en bugg eller har du ett förslag?")

 ;; Integritetspolicy
 (:privacy-title . "Integritetspolicy")
 (:privacy-updated . "Senast uppdaterad: januari 2026")
 (:privacy-who-title . "Vilka vi är")
 (:privacy-who-body . "Hiisi drivs av Lambda Symbolics OÜ, ett företag registrerat i Estland. Som estniskt företag följer vi EU:s allmänna dataskyddsförordning (GDPR).")
 (:privacy-collect-title . "Data vi samlar in")
 (:privacy-collect-intro . "När du använder Hiisi samlar vi in följande information:")
 (:privacy-collect-account-key . "Kontoinformation: ")
 (:privacy-collect-account-val . "E-postadress, visningsnamn och ett säkert hashat lösenord.")
 (:privacy-collect-learning-key . "Inlärningsdata: ")
 (:privacy-collect-learning-val . "Dina översättningar, sparade flashkort och din repetitionshistorik.")
 (:privacy-collect-usage-key . "Användningsdata: ")
 (:privacy-collect-usage-val . "Grundläggande serverloggar för säkerhet och felsökning.")
 (:privacy-use-title . "Hur vi använder dina data")
 (:privacy-use-auth-key . "Autentisering: ")
 (:privacy-use-auth-val . "För att verifiera din identitet och skydda ditt konto.")
 (:privacy-use-service-key . "Tjänsteleverans: ")
 (:privacy-use-service-val . "För att tillhandahålla översättningar och hantera din flashkortsamling.")
 (:privacy-use-ai-key . "AI-översättningar: ")
 (:privacy-use-ai-val . "Dina översättningsförfrågningar skickas till OpenRouter för att generera svar. OpenRouter kan vidarebefordra förfrågningar till den konfigurerade modellleverantören. Se OpenRouters integritetspolicy för hur dessa uppgifter hanteras.")
 (:privacy-third-title . "Tredjepartstjänster")
 (:privacy-third-intro . "Vi använder följande tredjepartstjänster:")
 (:privacy-third-openrouter-key . "OpenRouter: ")
 (:privacy-third-openrouter-val . "För automatiska översättningsförfrågningar.")
 (:privacy-third-mailgun-key . "Mailgun: ")
 (:privacy-third-mailgun-val . "För att skicka aktiveringsmail och transaktionsmail.")
 (:privacy-third-polar-key . "Polar.sh: ")
 (:privacy-third-polar-val . "För hantering av abonnemangsbetalningar.")
 (:privacy-cookies-title . "Cookies")
 (:privacy-cookies-intro . "Vi använder endast nödvändiga cookies:")
 (:privacy-cookies-auth-key . "Autentiseringstoken: ")
 (:privacy-cookies-auth-val . "En säker HTTP-only cookie som håller dig inloggad.")
 (:privacy-cookies-lang-key . "Språkinställning: ")
 (:privacy-cookies-lang-val . "För att komma ihåg ditt föredragna gränssnittsspråk.")
 (:privacy-retention-title . "Lagring av data")
 (:privacy-retention-body . "Dina data lagras så länge du har ett konto. När du begär radering schemaläggs ditt konto för radering om 14 dagar.")
 (:privacy-rights-title . "Dina rättigheter (GDPR)")
 (:privacy-rights-intro . "Enligt GDPR har du rätt att:")
 (:privacy-rights-access . "Få tillgång till dina personuppgifter")
 (:privacy-rights-export . "Exportera dina data (tillgängligt på /app/api/export)")
 (:privacy-rights-correct . "Begära rättelse av felaktiga uppgifter")
 (:privacy-rights-delete . "Begära radering av ditt konto och dina data")
 (:privacy-rights-object . "Invända mot behandling av dina data")
 (:privacy-rights-contact . "För att utöva dessa rättigheter, kontakta oss på")
 (:privacy-contact-title . "Kontakt")
 (:privacy-contact-intro . "För frågor om integritet:")
 (:privacy-contact-email-label . "E-post: ")
 (:privacy-address-1 . "Lambda Symbolics OÜ")
 (:privacy-address-2 . "Harju maakond, Tallinn, Kesklinna linnaosa, Tornimäe tn 5, 10145")

 ;; Användarvillkor
 (:terms-title . "Användarvillkor")
 (:terms-updated . "Senast uppdaterade: januari 2026")
 (:terms-1-title . "1. Tjänstebeskrivning")
 (:terms-1-body . "Hiisi är en språkinlärningsapp som erbjuder automatiserade översättningar med grammatiska förklaringar och flashkort med distribuerad repetition. Tjänsten drivs av Lambda Symbolics OÜ.")
 (:terms-2-title . "2. Kontoregistrering")
 (:terms-2-body . "För att använda Hiisi måste du skapa ett konto med en giltig e-postadress. Du ansvarar för säkerheten för dina kontouppgifter.")
 (:terms-3-title . "3. Abonnemang och betalningar")
 (:terms-3-body . "Hiisi erbjuder betalda abonnemang (månadsvis och årsvis). Abonnemang hanteras via Polar.sh.")
 (:terms-3-list-1 . "Abonnemang förnyas automatiskt om de inte sägs upp före förnyelsedatumet.")
 (:terms-3-list-2 . "Återbetalning ges i enlighet med tillämpliga konsumentskyddslagar.")
 (:terms-3-list-3 . "Utebliven betalning leder till förlorad tillgång till premiumfunktioner.")
 (:terms-4-title . "4. Tillåten användning")
 (:terms-4-intro . "Du samtycker till att inte:")
 (:terms-4-list-1 . "Använda tjänsten för olagliga ändamål")
 (:terms-4-list-2 . "Försöka kringgå användningsgränser eller säkerhetsåtgärder")
 (:terms-4-list-3 . "Dela dina kontouppgifter med andra")
 (:terms-4-list-4 . "Använda automatiserade verktyg på ett sätt som försämrar tjänstens prestanda för andra")
 (:terms-5-title . "5. Innehåll och immateriella rättigheter")
 (:terms-5-body-1 . "Översättningar som genereras av Hiisi skapas automatiskt och är kanske inte unika. Du får använda dina översättningar och flashkort för personliga ändamål, men du har inte exklusiv upphovsrätt till automatiskt genererat innehåll.")
 (:terms-5-body-2 . "Hiisi-applikationen, varumärket och originalinnehållet förblir Lambda Symbolics OÜ:s egendom.")
 (:terms-6-title . "6. Tjänstens tillgänglighet")
 (:terms-6-intro . "Hiisi tillhandahålls i befintligt skick. Vi garanterar inte:")
 (:terms-6-list-1 . "Oavbruten eller felfri tjänst")
 (:terms-6-list-2 . "Noggrannhet i automatiskt genererade översättningar")
 (:terms-6-list-3 . "Tillgång till specifika funktioner")
 (:terms-6-body . "Vi kan ändra eller avveckla funktioner när som helst.")
 (:terms-7-title . "7. Ansvarsbegränsning")
 (:terms-7-body-1 . "I den utsträckning lagen tillåter ansvarar Lambda Symbolics OÜ inte för indirekta, tillfälliga, särskilda eller följdskador som uppstår genom din användning av Hiisi.")
 (:terms-7-body-2 . "Vårt totala ansvar överstiger inte det belopp du har betalat för tjänsten under de 12 månader som föregår kravet.")
 (:terms-8-title . "8. Uppsägning av konto")
 (:terms-8-body-1 . "Vi kan stänga av eller avsluta ditt konto om du bryter mot dessa villkor. Du kan när som helst begära radering av konto i applikationen.")
 (:terms-8-body-2 . "Vid begäran om radering schemaläggs ditt konto för radering om 14 dagar.")
 (:terms-9-title . "9. Ändringar av villkor")
 (:terms-9-body . "Vi kan uppdatera dessa villkor då och då. Fortsatt användning av Hiisi efter ändringar innebär att du accepterar de nya villkoren.")
 (:terms-10-title . "10. Tillämplig lag")
 (:terms-10-body . "Dessa villkor regleras av estnisk lag. Eventuella tvister ska avgöras av domstolar i Estland.")
 (:terms-contact-title . "Kontakt")
 (:terms-contact-intro . "För frågor om dessa villkor:")
 (:terms-contact-email-label . "E-post: ")
 (:terms-address-1 . "Lambda Symbolics OÜ")
 (:terms-address-2 . "Harju maakond, Tallinn, Kesklinna linnaosa, Tornimäe tn 5, 10145")

 ;; Decks
 (:decks-title . "Kortlekar")
 (:decks-subtitle . "Skapa egna kortlekar och dela dem med andra.")
 (:decks-create-title . "Skapa kortlek")
 (:decks-name-placeholder . "Kortlekens namn")
 (:decks-desc-placeholder . "Beskrivning")
 (:decks-create-btn . "Skapa kortlek")
 (:decks-edit-title . "Redigera kortlek")
 (:decks-edit-btn . "Redigera kortlek")
 (:decks-actions-title . "Kortleksåtgärder")
 (:decks-card-actions-title . "Kortåtgärder")
 (:decks-update-btn . "Spara ändringar")
 (:decks-default-badge . "Automatisk")
 (:decks-default-description . "Den här kortleken hanteras automatiskt för det här språkparet.")
 (:decks-default-readonly . "Automatiska kortlekar har fasta namn och beskrivningar.")
 (:decks-delete-btn . "Ta bort kortlek")
 (:decks-delete-confirm . "Är du säker på att du vill ta bort den här kortleken?")
 (:decks-error-name-required . "Kortlekens namn är obligatoriskt.")
 (:decks-error-name-too-long . "Kortlekens namn får vara högst ~A tecken långt.")
 (:decks-error-desc-too-long . "Kortlekens beskrivning får vara högst ~A tecken lång.")
 (:decks-error-default-readonly . "Automatiska kortlekar kan inte redigeras.")
 (:decks-error-default-delete-forbidden . "Automatiska kortlekar kan inte tas bort.")
 (:decks-your-title . "Dina kortlekar")
 (:decks-col-updated . "Uppdaterad")
 (:decks-no-decks . "Inga kortlekar ännu.")
 (:decks-open-btn . "Öppna")
 (:decks-view-deck-btn . "Visa kortlek")
 (:decks-start-review . "Starta repetition")
 (:decks-no-desc . "Ingen beskrivning.")
 (:decks-share-title . "Delningslänk")
 (:decks-share-info . "Alla med denna länk kan importera kortleken:")
 (:decks-share-copy . "Kopiera länk")
 (:decks-share-copied . "Kopierad")
 (:decks-add-from-flashcards-title . "Lägg till flashkort")
 (:decks-add-from-flashcards-info . "Välj ett kort för att lägga till dess översättning i den här kortleken.")
 (:decks-create-new-flashcard . "Skapa nytt flashkort")
 (:decks-open-flashcards . "Lägg till befintliga flashkort")
 (:decks-filter-from . "Källspråk")
 (:decks-filter-to . "Målspråk")
 (:decks-filter-any . "Alla språk")
 (:decks-filter-include-assigned . "Inkludera kort som redan finns i en kortlek")
 (:decks-flashcards-add . "Lägg till")
 (:decks-flashcards-added . "Tillagt")
 (:decks-flashcards-in-deck . "I en annan kortlek")
 (:decks-flashcards-empty . "Inga kort matchar dessa filter.")
 (:decks-items-title . "Kortlekens innehåll")
 (:decks-col-original . "Original")
 (:decks-col-translated . "Översättning")
 (:decks-col-lang . "Målspråk")
 (:decks-no-items . "Inga objekt ännu.")
 (:decks-share-page-title . "Dela kortlek")
 (:decks-share-preview . "Förhandsgranska och importera denna kortlek.")
 (:decks-import-title . "Importera")
 (:decks-import-btn . "Importera kortlek")
 (:starter-decks-title . "Bibliotek")
 (:starter-decks-subtitle . "Importera färdiga kortlekar från Hiisi och communityn.")
 (:starter-decks-marketplace-btn . "Bibliotek")
 (:starter-decks-explanation-language . "Förklaringsspråk")
 (:starter-decks-search-label . "Sök")
 (:starter-decks-source-label . "Källa")
 (:starter-decks-source-all . "Alla kortlekar")
 (:starter-decks-change-language . "Ändra")
 (:starter-decks-filters-button . "Filter")
 (:starter-decks-search-placeholder . "Sök i biblioteket")
 (:starter-decks-apply-filters . "Använd filter")
 (:starter-decks-select-triplet-hint . "Välj källspråk och målspråk för att bläddra bland matchande kortlekar.")
 (:starter-decks-official-badge . "Officiell")
 (:starter-decks-official-by-hiisi . "Officiell från Hiisi")
 (:starter-decks-community-badge . "Community")
 (:starter-decks-by-hiisi . "Av Hiisi")
 (:starter-decks-preview-btn . "Förhandsgranska")
 (:starter-decks-card-count . "~A kort")
 (:starter-decks-no-results . "Inga kortlekar matchar dessa filter.")
 (:starter-decks-source-cards-title . "Kort i den här leken")
 (:starter-decks-more-cards-included . "+~A fler kort ingår.")
 (:starter-decks-sample-title . "Exempelkort")
 (:starter-decks-generating . "Förbereder din kortlek ~A")
 (:starter-decks-generating-detail . "Vi importerar den så snart den är klar. Du kan fortsätta bläddra i Biblioteket eller komma tillbaka om en stund.")
 (:starter-decks-generation-failed . "Skapandet misslyckades")
 (:starter-decks-generation-failed-detail . "Det senaste försöket att skapa kortleken misslyckades. Försök importera kortleken igen.")
 (:starter-decks-login-detail . "Logga in för att importera den här kortleken till din samling.")
 (:starter-decks-subscribe-btn . "Se planer")
 (:starter-decks-subscribe-detail . "Bibliotekets kortlekar är tillgängliga med en aktiv prenumeration eller provperiod.")
 (:library-submit-title . "Skicka till biblioteket")
 (:library-submit-intro . "Skicka den här kortleken till biblioteket för administrativ granskning före publicering.")
 (:library-submit-btn . "Skicka kortlek")
 (:library-submit-approved . "Godkänd för biblioteket")
 (:library-submit-approved-detail . "Den här kortleken är publicerad i biblioteket.")
 (:library-submit-pending . "Under granskning")
 (:library-submit-pending-detail . "Den här kortleken har skickats in och väntar på administrativ granskning.")
 (:library-submit-rejected . "Behöver ändringar före publicering")
 (:library-submit-rejected-detail . "Den här inskickningen avslogs. Uppdatera kortleken och skicka in den igen.")
 (:library-error-empty . "Lägg till minst ett kort innan du skickar den här kortleken till biblioteket.")
 (:library-error-missing-triplet . "Varje kort i en biblioteksinsändning måste ha en fullständig språktripel.")
 (:library-error-mixed-triplet . "Alla kort i en biblioteksinsändning måste ha samma språktripel.")
 (:starter-deck-topic-greetings-title . "Hälsningar och presentationer")
 (:starter-deck-topic-greetings-description . "Hälsningar, namn, artiga grunder och fraser för ett första möte.")
 (:starter-deck-topic-travel-title . "Viktiga resefraser")
 (:starter-deck-topic-travel-description . "Stationer, biljetter, priser, hjälp och att ta sig runt.")
 (:starter-deck-topic-numbers-title . "Tal och priser")
 (:starter-deck-topic-numbers-description . "Räkning, totalsummor, priser, våningar och vardagliga mängder.")
 (:starter-deck-topic-time-title . "Tid och datum")
 (:starter-deck-topic-time-description . "Dagar, månader, möten, klockslag och relativa datum.")
 (:starter-deck-topic-food-title . "Restaurang och mat")
 (:starter-deck-topic-food-description . "Beställning, kostönskemål, drycker, notan och vanliga måltider ute.")
 (:starter-deck-topic-emergency-title . "Nödsituationer och hälsa")
 (:starter-deck-topic-emergency-description . "Läkare, apotek, symtom, kroppsdelar och akut hjälp.")
 (:starter-deck-topic-directions-title . "Vägbeskrivningar och transport")
 (:starter-deck-topic-directions-description . "Svängar, hållplatser, biljetter, perronger och att ta sig runt i staden.")
 (:starter-deck-topic-school-title . "Skola och utbildning")
 (:starter-deck-topic-school-description . "Lektioner, läxor, prov, skolmaterial och vardagslivet i skolan.")
 (:starter-deck-topic-university-title . "Universitet och studier")
 (:starter-deck-topic-university-description . "Föreläsningar, seminarier, huvudämnen, uppgifter och vardagslivet på campus.")

 ;; Flashcards management page
 (:flashcards-title . "Mina kort")
 (:flashcards-subtitle . "Alla dina sparade kort på ett ställe. Sök, organisera och hantera.")
 (:flashcards-search-placeholder . "Sök kort...")
 (:flashcards-filter-button . "Filter")
 (:flashcards-filter-title . "Filtrera kort")
 (:flashcards-filter-recollection . "Hur bra du kan dem")
 (:flashcards-filter-any-recollection . "Vilken nivå som helst")
 (:flashcards-hide-perfected . "Dölj fullständigt inlärda kort")
 (:flashcards-col-original . "Original")
 (:flashcards-col-translated . "Översättning")
 (:flashcards-no-cards . "Inga kort ännu. Börja översätta för att skapa några!")
 (:flashcards-image-label . "Bild")
 (:flashcards-image-upload . "Ladda upp bild")
 (:flashcards-image-replace . "Byt bild")
 (:flashcards-image-remove . "Ta bort bild")
 (:flashcards-pagination-label . "Flashcard-sidor")
 (:flashcards-pagination-status . "Sida ~A av ~A")
 (:flashcards-pagination-previous . "Föregående")
 (:flashcards-pagination-next . "Nästa")

 ;; Landing page (redesign)
 (:landing-hero-headline . "Varje ord förklarat. Varje repetition schemalagd. Femton språk.")
 (:landing-hero-headline-v1 . "Översätt meningar enkelt och läs grammatiken på ditt eget språk.")
 (:landing-hero-headline-v2 . "Hiisi ser till att du inte glömmer varje mening du översätter.")
 (:landing-hero-headline-v3 . "Gör meningarna du översätter till ordförråd du kan använda.")
 (:landing-hero-subheadline . "Bokmärk vilken mening som helst så ger Hiisi dig översättningen, grammatiken, uttalet och ett flashkort som kommer tillbaka för repetition.")
 (:landing-hero-trust-line . "14 dagar gratis. Inget kort krävs.")
 (:landing-credibility-languages . "Femton språk")
 (:landing-credibility-flashcards . "Smarta flashkort")
 (:landing-credibility-pronunciation . "Uttalsguide")
 (:landing-languages-title . "Välj språket du länge har tänkt lära dig")
 (:landing-step-1-title . "Klistra in en mening")
 (:landing-step-1-desc . "Vilken längd som helst, på något av 15 språk. Du får översättningen plus en grammatikanalys av varje ord.")
 (:landing-step-2-title . "Spara det som är värt att minnas")
 (:landing-step-2-desc . "Ett klick förvandlar en översättning till ett flashkort, med den ursprungliga meningen bevarad som kontext.")
 (:landing-step-3-title . "Repetera vid rätt tillfälle")
 (:landing-step-3-desc . "Distribuerad repetition med SM-2, samma algoritm som Anki. Kort du kämpar med kommer tillbaka tidigare.")
 (:landing-feature-grammar-title . "Varje ord förklarat, på ditt språk")
 (:landing-feature-grammar-desc . "Översättningar kommer med kasus, genus, aspekt och modus analyserade ord för ord. Finsk partitiv, tjeckisk animathet, polsk aspekt, tyska dativsammandragningar, allt märkt och länkat till en grammatikreferens.")
 (:landing-feature-srs-title . "Vanan av distribuerad repetition, automatiserad")
 (:landing-feature-srs-desc . "SM-2-algoritmen anpassar sig efter din prestation. Svåra kort visas oftare. Kort du kan visas mer sällan.")
 (:landing-feature-share-title . "Dina kortlekar, eller gemenskapens")
 (:landing-feature-share-desc . "Ordna flashkort i tematiska kortlekar. Dela vilken kortlek som helst med en länk, eller bläddra i gemenskapens bibliotek efter kortlekar som andra har delat.")
 (:landing-pricing-trial-note . "Inkluderar 14 dagars gratis provperiod")
 (:landing-pricing-monthly-after . "14 dagar gratis, sedan ~A/månad")
 (:landing-pricing-annual-after . "14 dagar gratis, sedan ~A/år")
 (:landing-faq-title . "Vanliga frågor")
 (:landing-faq-trial-cap-q . "Hur många översättningar får jag under provperioden?")
 (:landing-faq-trial-cap-a . "Du får 200 översättningar under din 14-dagars provperiod. Efter prenumeration får du 600 per månad.")
 (:landing-final-cta-title . "Din första mening tar fem sekunder.")
 (:landing-final-cta-subtitle . "Klistra in vad som helst på finska, tjeckiska, polska eller något av de andra tolv språken. Se vad Hiisi gör med det. Fjorton dagar gratis.")

 ;; Trial status (in-app)
 (:trial-status . "Gratis provperiod")
 (:error-trial-quota-exceeded . "Gräns för provöversättningar nådd")
 (:error-trial-quota-detail . "Du har använt alla 200 provöversättningar. Prenumerera för att fortsätta lära.")

 ;; Custom flashcards
 (:custom-flashcard-create-title . "Skapa flashkort")
 (:custom-flashcard-edit-title . "Redigera flashkort")
 (:custom-flashcard-original . "Originaltext")
 (:custom-flashcard-translated . "Översättning")
 (:custom-flashcard-lang-from . "Källspråk")
 (:custom-flashcard-lang-to . "Målspråk")
 (:custom-flashcard-note . "Pedagogisk anteckning")
 (:custom-flashcard-forms . "Grammatikanalys")
 (:custom-flashcard-form-term . "Term")
 (:custom-flashcard-form-explanation . "Förklaring")
 (:custom-flashcard-add-form . "Lägg till grammatikterm")
 (:custom-flashcard-remove-form . "Ta bort")
 (:custom-flashcard-ai-fill . "Fyll i med AI")
 (:custom-flashcard-create-btn . "Skapa flashkort")
 (:custom-flashcard-update-btn . "Spara ändringar")

  ;; Newsletter
  (:newsletter-email-label . "E-postadress")
  (:newsletter-developer-label . "Jag är utvecklare")
  (:newsletter-developer-hint . "få tekniska uppdateringar")
  (:landing-newsletter-title . "Få Hiisi-uppdateringar.")
  (:landing-newsletter-body . "Anmäl dig till nyhetsbrevet för produktuppdateringar, stöd för nya språk, startkortlekar och tillfälliga erbjudanden för grundarmedlemmar.")
  (:landing-newsletter-fine-print . "Ingen spam. Bara produktuppdateringar.")
  (:landing-newsletter-button . "Anmäl dig till nyhetsbrevet")
  (:newsletter-unsubscribe-page-title . "Avsluta prenumeration på Hiisis nyhetsbrev")
  (:newsletter-unsubscribe-title . "Avsluta prenumeration")
  (:newsletter-unsubscribe-subtitle . "Ange din e-post för att sluta få Hiisi-uppdateringar.")
  (:newsletter-unsubscribe-button . "Avsluta prenumeration")
  (:newsletter-feedback-email-required . "Ange din e-postadress.")
  (:newsletter-feedback-email-invalid . "Ange en giltig e-postadress.")
  (:newsletter-feedback-already-signed-up . "Du är redan anmäld. Vi håller dig uppdaterad!")
  (:newsletter-feedback-signed-up . "Du står på listan! Vi skickar då och då uppdateringar om Hiisi.")
  (:newsletter-feedback-unsubscribed . "Om den här e-posten var anmäld har den tagits bort från Hiisi-uppdateringar.")
  (:newsletter-feedback-generic-error . "Något gick fel. Försök igen.")

  ;; Issue reporting
  (:issues-open-button . "Rapportera ett fel")
 (:issues-modal-title . "Rapportera ett problem")
 (:issues-modal-subtitle . "Beskriv vad som gick fel. Vi lägger automatiskt till sidan du är på.")
 (:issues-title-label . "Kort titel")
 (:issues-title-placeholder . "Kort sammanfattning av problemet")
 (:issues-message-label . "Vad hände?")
 (:issues-message-placeholder . "Ange steg för att återskapa, förväntat beteende och vad som hände i stället.")
 (:issues-submit . "Skicka rapport")
 (:issues-cancel . "Avbryt")
 (:issues-success . "Din rapport har skickats. Vi tittar på den så snart vi kan.")
 (:issues-error-required . "Beskriv problemet innan du skickar.")
 (:issues-error-title-too-long . "Ärendets titel är för lång. Håll den under 160 tecken.")
 (:issues-error-too-long . "Rapporttexten är för lång. Håll den under 4000 tecken.")
 (:issues-error-rate-limit . "För många rapporter från denna källa. Vänta och försök igen senare.")
 (:issues-error-generic . "Problemrapporten kunde inte skickas. Försök igen.")

)
